### ISSUE TITLE
6.0 Feedback:  Unavailable robots display robot settings and pipettes and modules 

### ISSUE THREAD

**Issue by nusrat813** [Opentrons/opentrons#10032]
### Current Behavior

If a robot that was previously online but is now offline, the robot will continue to display robot settings, pipettes and modules
<img width="719" alt="Screen Shot 2022-04-20 at 3 50 48 PM" src="https://user-images.githubusercontent.com/30632549/164491153-017fc5cd-33e0-42f6-8e6d-6dc0f8fc1401.png">
<img width="699" alt="Screen Shot 2022-04-20 at 3 50 44 PM" src="https://user-images.githubusercontent.com/30632549/164491161-4d868fad-7153-4c1e-af9e-c21bc1c11bd3.png">
 

### Expected Behavior

A user should not be able to see the contents of a robot if the robot is unavailable
![Screen Shot 2022-04-20 at 3 53 22 PM](https://user-images.githubusercontent.com/30632549/164491445-d6f6bf8a-2f54-4d83-b362-40bfcb72d75e.png)
 

### Operating system

Mac

**Comment by nusrat813** [comment]
Robot server not being up - we want to make the settings still available

**Comment by emilywools** [comment]
per figma, if a robot is offline, the user should not be able to access settings. 

https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=1297%3A91474

**Comment by y3rsh** [comment]
verified
