### ISSUE TITLE
5.1 Feedback:  Custom labware that successfully uploaded is not found upon python protocol analysis

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#10039]
### Overview

2 custom labware files were successfully uploaded.
When I upload a python protocol referencing those I get an analysis error.
<img width="991" alt="image" src="https://user-images.githubusercontent.com/502770/164552333-e797ca83-f330-44c9-8827-ccb58bf60822.png">
<img width="994" alt="image" src="https://user-images.githubusercontent.com/502770/164552630-9a864ef0-b8f5-4675-b291-ba5b49eef81d.png">

### Current Behavior

Labware uploaded in 5.0.2 or in beta is not found during analysis of the python protocol.

### Expected Behavior

All labware previously uploaded (custom folders accounted for) and labware uploaded in 5.1 will be found.

### Steps To Reproduce

```gherkin
Given I have uploaded 2 custom labware in the labware tab
And I have a robot connected on Wi-Fi
And I navigate to Protocols
When I upload my protocol that references the custom labware
Then I receive an analysis error that the labware is missing but it is not.
```

### Operating system

Mac

### Robot setup or anything else?

[FilesToReproduce.zip](https://github.com/Opentrons/opentrons/files/8535102/FilesToReproduce.zip)

**Comment by nusrat813** [comment]
Not yet implemented - @b-cooper is there a ticket open for this implementation? 
If not, can we get a ticket up for beta.1
