### ISSUE TITLE
feat: API allow pipette.transfer() to go to side of well and change speed flow rate

### ISSUE THREAD

**Issue by clolalan7** [Opentrons/opentrons#10034]
Sorry if I missed this, but is there a way to tell the pipette to do a transfer on the side of a well and to a lower flow rate? I need to use the transfer command in a script to do a quick water wash of beads (on magnet), and with the default transfer, the liquid flows on the beads and I am losing my DNA. 
thanks

**Comment by braldrich** [comment]
Working with this customer who came into the support inbox
