### ISSUE TITLE
6.0 Feedback:  Proceed to setup has a pause before proceeding to setup

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#10040]
### Overview

Proceed to setup has a pause before proceeding to setup and this caused me to click the button multiple times.

### Expected Behavior

Immediate navigation or some kind of feedback to the user that the button was clicked successfully?

### Steps To Reproduce

```gherkin
Given I have uploaded a simple protocol
And I have a robot connected on Wi-Fi
And I navigate to Devices
And I expand my connected robot
And I Click "Run a protocol"
And on the slide out I choose the simple protocol (selected by default when I have just one uploaded protocol)
When I click "Proceed to setup"
Then a pause happens before the setup page loads
```

### Operating system

Mac

### Robot setup or anything else?
even small protocols cause this
[.py protocol](https://github.com/Opentrons/opentrons/files/8535379/logo.py.zip)
[.json protocol](https://github.com/Opentrons/opentrons/files/8535329/simple.json.zip)

**Comment by emilywools** [comment]
yes we should provide feedback to the user that this button was clicked. we could show a loader inside the button while this is happening. @mmencarelli do you have any thoughts here?

**Comment by mmencarelli** [comment]
@emilywools When the user clicks 'proceed to setup' the app performs an analysis of the protocol which takes a few seconds, which is what I think @y3rsh is encountering there. 

We have a loading state for this as a solution (screenshot below), but I don't think it's been implemented yet. Right, @b-cooper ? 

![Screen Shot 2022-04-29 at 12.01.05 PM.png](https://images.zenhubusercontent.com/62225a2a0aad103955578520/525b039b-76e5-477c-9afd-fe959e54b395)

**Comment by nusrat813** [comment]
@b-cooper - can you look at the design provided by mel?

**Comment by y3rsh** [comment]
Now that we are progressing to the run setup page and have the analyzing on robot spinner, this experience is much improved.
