### ISSUE TITLE
5.1 Feedback:  A single protocol can be uploaded many times 

### ISSUE THREAD

**Issue by nusrat813** [Opentrons/opentrons#10047]
### Current Behavior

A single protocol can be uploaded many times  - the app does not reanalyze the file as one file 
<img width="1191" alt="Screen Shot 2022-04-21 at 11 51 52 PM" src="https://user-images.githubusercontent.com/30632549/164752654-c2ab48d7-e43a-4e18-9793-7e2a456c46fa.png">

### Expected Behavior

Is the expected behavior supposed to be like the custom labware upload where there is a modal that says do you want to overwrite the file? 

### Steps To Reproduce

1. Upload a protocol 
2. Upload the same protocol multiple times

### Operating system

Mac

**Comment by nusrat813** [comment]
See expected behavior comment 
@emilywools - do you have any insight on this?

**Comment by nusrat813** [comment]
Expected behavior at the moment 
Feature request - not in scope for 5.1 currently @mikecardarelli -to ticket

**Comment by mikecardarelli** [comment]
New ticket https://app.zenhub.com/workspaces/app--ui-5f6248dba845b000139aa767/issues/opentrons/opentrons/10181
