### ISSUE TITLE
6.0 Feedback:  app goes white screen when clicked on Devices tab, after uploading a protocol

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#10055]
### Overview

When a user clicks on device tab after uploading a protocol -> app goes balnk

### Current Behavior

App is blank when the user clicks on Devices tab - beta 5.1.0-beta.0
![Screen Shot 2022-04-24 at 8 27 51 PM](https://user-images.githubusercontent.com/39049853/165003216-0f5fd2f2-07fd-42be-b418-87ecc2839d59.png)

![Screen Shot 2022-04-24 at 8 30 17 PM](https://user-images.githubusercontent.com/39049853/165003314-d85a014b-3785-4e3c-8fab-b3e040f016de.png)

![Screen Shot 2022-04-24 at 8 32 04 PM](https://user-images.githubusercontent.com/39049853/165003404-dbf6af1d-2995-4215-a9c6-83083b783990.png)

### Expected Behavior

App should not go blank

### Steps To Reproduce

1. Goto protocol tab and upload a protocol
2. Before the protocol is fully analyzed and the deckmap is displayed on protocol page -> user clicks on device page
3.  The app goes balnk. I am able to see the analysis.json on my mac `Library/Application Support/Opentrons/protocols/123fd6ca-3bd6-4d92-afc4-195e9ebb411f/analysis`
4. Attaching the analysis 
[analysis.json.zip](https://github.com/Opentrons/opentrons/files/8550799/analysis.json.zip)

**Comment by nusrat813** [comment]
@hartm9 - Can you ticket your comment as a separate issue?

**Comment by nusrat813** [comment]
Do we need to make a decision about disabling tabs during certain analyses? (ex: protocol analyzing, proceed to setup, rerun)

**Comment by b-cooper** [comment]
We do not need to disable tabs during analyses.  This a bug that has to do with the "Choose a Protocol Slideout" (which is part of the Devices tab) is not properly handling in progress analyses.

**Comment by y3rsh** [comment]
I can still reproduce this
![quickwhitescreen](https://user-images.githubusercontent.com/502770/170068158-7029d3fb-e8b7-4cdc-9b23-71d1cc479916.gif)

**Comment by mcous** [comment]
This ticket interacts with #10468. If you quit out of the app while the protocol is still spinning, the protocol will never get an analysis object, which will cause this same whitescreen

**Comment by y3rsh** [comment]
Verified fixed.
