### ISSUE TITLE
6.0 Feedback: many UI elements offer "Copy Link" contextual menu item

### ISSUE THREAD

**Issue by ecormany** [Opentrons/opentrons#10054]
### Overview

Most UI elements in the new app UI can spawn a contextual menu item with a "Copy Link" item.

<img width="153" alt="Screen Shot 2022-04-22 at 5 06 26 PM" src="https://user-images.githubusercontent.com/1958332/164794685-62921ce4-c88d-4ed0-82fb-428f57e7a22d.png">
<img width="310" alt="Screen Shot 2022-04-22 at 5 06 38 PM" src="https://user-images.githubusercontent.com/1958332/164794687-fd6b5000-8ec6-48e9-b27a-4e8bb776a7a3.png">
<img width="126" alt="Screen Shot 2022-04-22 at 5 06 47 PM" src="https://user-images.githubusercontent.com/1958332/164794690-5228c2c0-02f2-4717-932f-4d481e930dd4.png">
<img width="301" alt="Screen Shot 2022-04-22 at 5 07 10 PM" src="https://user-images.githubusercontent.com/1958332/164794692-04da0f30-7a04-4842-ba90-d4698f59cee4.png">

### Current Behavior

Most UI elements in the new app UI can spawn a contextual menu item, which usually only contains a "Copy Link" item (and also "Copy" if the text is selectable). This item does in fact copy a `file:///` URL to the clipboard, but its contents serve no purpose to the end user.

### Expected Behavior

These contextual menus should not appear if their only item is "Copy Link". Alternatively, if the URLs produced by Copy Link serve some internal or debugging purpose, the feature should be enabled by advanced preference / feature flag only.

### Steps To Reproduce

1. Launch the Opentrons App.
2. Right click on certain interface elements. These include (but are not limited to) sidebar text items, sidebar icons, protocol cards, and robot cards. Labware cards do _not_ spawn these menus.
3. Click Copy Link.

A link similar to `file:///Applications/Opentrons.app/Contents/Resources/app.asar/ui/index.html#/robots` will be put on the clipboard. This URL is meaningless because the app.asar file is not a bundle whose contents can be viewed individually.

Note: This behavior is also present in earlier versions of the app; it just manifests on significantly fewer UI elements.

### Operating system

Mac

**Comment by emilywools** [comment]
we would like to remove all copy link context menus

**Comment by koji** [comment]
@ecormany 
Do you think we should remove look up too?

![Screen Shot 2022-05-16 at 6 29 05 PM](https://user-images.githubusercontent.com/474225/168692909-83215e38-0a33-45bd-b602-5a2f82cc22d7.png)

**Comment by ecormany** [comment]
"Look Up" is a standard OS option and most importantly does what it claims to do, so I think we can leave it. "Copy Link" doesn't copy a functioning link to anything.

**Comment by y3rsh** [comment]
On mac<img width="800" alt="image" src="https://user-images.githubusercontent.com/502770/170491407-83fda103-513f-4822-aa23-613bc38607b0.png">
On Windoes 11 and Linux I get only Inspect element.
