### ISSUE TITLE
6.0 Feedback:  Cancel run doesnot show the protocol run banner with cancelled status

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#10057]
### Overview

When a run is cancelled, protocol run page should display a banner with cancelled run state.

### Current Behavior

This can be seen in the screenshot that the protocol was cancelled. with protocol start and end time stamps
<img width="1017" alt="Screen Shot 2022-04-25 at 2 33 54 AM" src="https://user-images.githubusercontent.com/39049853/165033084-9b7e5cdd-4a06-42ea-a545-99fd4b07c3d5.png">

### Expected Behavior

<img width="559" alt="Screen Shot 2022-04-25 at 2 35 51 AM" src="https://user-images.githubusercontent.com/39049853/165033339-e00b3960-13da-4aaa-8197-e084ca6ebc13.png">

### Steps To Reproduce

1. Run a protocol -> cancel it at step 1.
2. Protocol proceeds to home , but later doesnot show the protocol run banner as shown in the expected behaviour.

**Comment by y3rsh** [comment]
verified
![image](https://user-images.githubusercontent.com/502770/172622961-9f742a11-62c4-4b1c-af3e-c9e2e7397aa0.png)
