### ISSUE TITLE
5.1 Feedback:  protocol that client-side py can't analyze

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#10058]
### Overview

[Test_Speaker.py.zip](https://github.com/Opentrons/opentrons/files/8555781/Test_Speaker.py.zip)

the app won't analyze this protocol, not sure why. its in a forever-loading state.

![Screen Shot 2022-04-25 at 11 11 18 AM](https://user-images.githubusercontent.com/4339860/165118493-ef0fb548-73a7-46b2-bd80-93a8b1472c8d.png)
 

### Current Behavior

when i import this protocol into the app, the card appears but the protocol never fully analyzes.

### Expected Behavior

i expect this protocol to analyze and show deck state info and i can click into the detail page

### Steps To Reproduce

import the attached protocol to the beta

### Operating system

Mac

**Comment by nusrat813** [comment]
@y3rsh can you download and try this on your robot?

**Comment by y3rsh** [comment]
> @y3rsh can you download and try this on your robot?

This protocol references the a full robot file system path directly `/etc/audio/speaker-test.mp3` which would be a problem but the way it is referenced in this case does **NOT** cause the problem.
A bad path is masked with this code, no exception is raised.
```python
AUDIO_FILE_PATH = '/etc/audio/speaker-test.mp3'
def run_quiet_process(command):
    subprocess.check_output('{} &> /dev/null'.format(command), shell=True)
def test_speaker():
    print('Speaker')
    print('Next\t--> CTRL-C')
    try:
        run_quiet_process('mpg123 {}'.format(AUDIO_FILE_PATH))
    except KeyboardInterrupt:
        pass
        print()
```

**Comment by mcous** [comment]
Moved to #10142
