### ISSUE TITLE
6.0 Feedback:  Protocol Analysis Failure: libcrypt.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ethanfjones** [Opentrons/opentrons#10064]
### Overview

When I try to upload a simple protocol
```
from opentrons import protocol_api

metadata = {'apiLevel': '2.12'}

def run(protocol: protocol_api.ProtocolContext):
    plate = protocol.load_labware('corning_96_wellplate_360ul_flat', 1)
    tiprack_1 = protocol.load_labware('opentrons_96_tiprack_300ul', 2)
    p300 = protocol.load_instrument('p300_single_gen2', 'right', tip_racks=[tiprack_1])

    p300.pick_up_tip()
    p300.aspirate(100, plate['A1'])
    p300.dispense(100, plate['B1'])
    p300.drop_tip()
```

the below error is throw

> Command failed with exit code 127: /tmp/.mount_OpentrFxLjs0/resources/python/bin/python3 -m opentrons.cli analyze --json
> /home/opentrons/.config/Opentrons/protocols/cbc58829-9713-417b-b60c-dedacce2d0a6/src
> /tmp/.mount_OpentrFxljs0/resources/python/bin/python3: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory

![screenshot_20220425_115942](https://user-images.githubusercontent.com/94644983/165149776-0524d667-6757-47bd-aafa-1d8199589770.png)

I am running the app on Manjaro 21.2.6

### Current Behavior

A protocol analysis error is thrown when I upload a protocol

### Expected Behavior

The protocol should upload without an error being thrown 

### Steps To Reproduce

Try to upload any protocol 

### Operating system

Linux

### Robot setup or anything else?

Wi-Fi 

I was able to resolve this by installing libxcrypt via AUR

**Comment by nusrat813** [comment]
@nusrat813 - task: try to repo

**Comment by nusrat813** [comment]
Need for support documentation for python packages 

#9788 - app setting to overwrite path to python

**Comment by nusrat813** [comment]
I was not able to repo this issue

**Comment by b-cooper** [comment]
Closing as this appears to be fixed
