### ISSUE TITLE
5.1 Feedback: cosmetic padding difference between Labware and Protocols tabs

### ISSUE THREAD

**Issue by ecormany** [Opentrons/opentrons#10065]
### Overview

The main container div (class `Box-sc-8ozbhb-0`) has different top padding on the Labware tab (24px) vs the Protocols tab (16px). This is most noticeable because the Import button at the top right jumps around when switching between the two.

### Current Behavior

The padding is different, making the tabs feel inconsistent.

### Expected Behavior

Standardize on one top padding value for this div. (Side padding is 16px, so 16px all around seems best to me.)

### Steps To Reproduce

1. Open the app.
2. Switch between the Labware and Protocols tabs in the side nav.
<img width="923" alt="Screen Shot 2022-04-25 at 2 48 54 PM" src="https://user-images.githubusercontent.com/1958332/165156297-3b7a32d4-9b55-41d8-9d2e-5506b5416612.png">
<img width="923" alt="Screen Shot 2022-04-25 at 2 49 19 PM" src="https://user-images.githubusercontent.com/1958332/165156301-1b08363e-e3c9-4c86-bf64-d74a3abb57d5.png">

### Operating system

Mac

**Comment by mmencarelli** [comment]
Thanks for making a ticket for this @ecormany ! Noticed the same—should be our 1rem padding all around (16px)
