### ISSUE TITLE
5.1 Feedback: app default main nav item is devices, should be protocols

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#10081]
### Overview

when you open the app, it defaults to the devices tab. it should instead default to the protocols tab.

### Current Behavior

when you open the app, it defaults to the devices tab 

### Expected Behavior

when you open the app, it should default to the Protocols tab

### Steps To Reproduce

open the app

### Operating system

Mac

**Comment by y3rsh** [comment]
verified on mac,windows and linux
