### ISSUE TITLE
6.0 Feedback:  Protocols > Protocol Detail overflow menu persists after no selection

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#10086]
### Overview

When I open the overflow menu on a protocol detail it does not disappear when I click off of it.  The only way it collapses without selecting an item in the menu is to click the overflow menu kebab again.

### Current Behavior

https://user-images.githubusercontent.com/502770/165359299-cf1e30aa-8570-4042-9a47-a9c9ff5c0fb5.mp4

### Expected Behavior

Clicking off of the the menu or clicking the kebab would close the menu.

### Steps To Reproduce

See the video.

### Operating system

Mac

**Comment by nusrat813** [comment]
Overflow menus in the devices tab disappear when you click off of them - we should have the same behavior for the protocol detail overflow menu

**Comment by y3rsh** [comment]
verified
<img width="800" alt="image" src="https://user-images.githubusercontent.com/502770/170496603-b63ba582-fdf8-4ac1-b9df-f5a5d1266ee7.png">
