### ISSUE TITLE
5.1 Feedback:  We show a link to latest release notes on Robot settings but not app settings

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#10089]
### Overview

missing link to latest release notes in github on app settings page

### Current Behavior

when i go to the robot settings page, i can see a link to the latest release notes in github. when i go to the app settings page, there is not a link to the latest release notes in github
<img width="1136" alt="Screen Shot 2022-04-26 at 2 17 57 PM" src="https://user-images.githubusercontent.com/4339860/165366231-10bfc910-bca2-4acf-8498-14cea86c192f.png">
.
<img width="518" alt="Screen Shot 2022-04-26 at 2 17 48 PM" src="https://user-images.githubusercontent.com/4339860/165366234-7b49b747-3bc9-409d-97d4-90127c462321.png">

### Expected Behavior

the app settings page should have a link to the latest release notes in github

### Steps To Reproduce

navigate to app settings and go to the App Software Version section.

### Operating system

Mac

**Comment by koji** [comment]
- [ ] Add ExternalLink to GeneralSettings
- [ ] Add test for 👆

**Comment by nusrat813** [comment]
Verified fixed
