### ISSUE TITLE
5.1 Feedback:  See how to setup a new robot modal

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#10085]
### Overview

the link to display the modal, as well as the modal styling is a bit off

![Screen Shot 2022-04-26 at 12 32 33 PM](https://user-images.githubusercontent.com/4339860/165349500-a9749c64-ab6c-42f2-933f-a3cd1c6c1623.png)
![Screen Shot 2022-04-26 at 12 36 01 PM](https://user-images.githubusercontent.com/4339860/165349536-fff7566e-7e06-4ab0-941c-2508529cc0ee.png)

### Current Behavior

link:
the "see how to set up a new robot" link font size is too big

modal:
Close is not capitalized
Not enough space between the body copy and the link to the help article

### Expected Behavior

link:
should be 11pt

modal:
should capitalize Close
needs 16px between body copy and link

### Steps To Reproduce

go to devices page
click "See how to set up a new robot"

### Operating system

Mac

**Comment by koji** [comment]
- [ ] Add css(TYPOGRAPHY) to Link
- [ ] Capitalize `close`
- [ ] Update Modal

**Comment by y3rsh** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/502770/170499218-0524c689-b13e-46b2-8b1a-df35a550842b.png">

<img width="800" alt="image" src="https://user-images.githubusercontent.com/502770/170499185-685cdb29-ef3a-414e-ab9b-8d5d337d2842.png">
