### ISSUE TITLE
5.1 Feedback: Looking for robots loader

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#10080]
### Overview

on app launch, the devices tab of the app shows a "looking for robots" loader. Can we get rid of this? Is there a reason we need to show this? If we need to show it, can we restyle it to be smaller?
![Screen Shot 2022-04-26 at 9 23 30 AM](https://user-images.githubusercontent.com/4339860/165309954-4bb9dcab-c674-4309-9736-298909892c86.png)

### Current Behavior

on app launch, the devices tab of the app shows a "looking for robots" loader.

### Expected Behavior

i dont think we need to show this loaded on app launch

### Steps To Reproduce

open the app

### Operating system

Mac

**Comment by nusrat813** [comment]
No reason to show

**Comment by nusrat813** [comment]
Verified fixed
