### ISSUE TITLE
6.0 Feedback:  Long Protocol Name cuts off the X button on "Run protocol" slideout

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#10087]
### Overview

With a sufficiently long protocol name like `MagneticV2TempV2MixTransferNoPause`
The X button on the "Run protocol" slideout gets cut off
![image](https://user-images.githubusercontent.com/502770/165359936-d5757945-e9f1-4d7b-b054-44f2f899553f.png)

### Current Behavior

X cut off

### Expected Behavior

X not cut off

### Steps To Reproduce

Import a protocol with a long name.
[MagneticV2TempV2MixTransferNoPause.json.zip](https://github.com/Opentrons/opentrons/files/8565630/MagneticV2TempV2MixTransferNoPause.json.zip)
 Go to protocol detail  and click run a protoco

https://user-images.githubusercontent.com/502770/165360482-885819b0-f991-43e9-9813-5690c44088d8.mp4

l

### Operating system

Mac

**Comment by emilywools** [comment]
@mmencarelli can you weigh in here?

**Comment by mmencarelli** [comment]
There should be a 8px margin between the title and the 'x' button. I think this is happening because there's no space in the name of the robot. Could we force a break in the name somehow?

**Comment by nusrat813** [comment]
@mmencarelli - was a final decision made on this?

**Comment by emilywools** [comment]
@nusrat813 i think we need someone from SWE to weigh in on this.

**Comment by koji** [comment]
![Screen Shot 2022-05-19 at 9 51 35 PM](https://user-images.githubusercontent.com/474225/169433569-a8b42e61-9c83-4ad4-bb93-7296daa98ca9.png)

**Comment by y3rsh** [comment]
verified
<img width="800" alt="image" src="https://user-images.githubusercontent.com/502770/170494430-636e6e0f-1de5-42d9-a65a-b4889894bf5e.png">
