### ISSUE TITLE
5.1 Feedback:  Cursor doesn't change on labware cards

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#10091]
### Overview

when you hover over a labware card on the labware tab, the cursor does not change to a finger (is that the right word????)

### Current Behavior

when you hover over a labware card on the labware tab, the cursor does not change to a finger (is that the right word????)

### Expected Behavior

when you hover over a labware card on the labware tab, the cursor should change to a finger

### Steps To Reproduce

go to labware page and hover over a labware card

### Operating system

Mac

**Comment by koji** [comment]
@emilywools 
finger = `pointer` in css
https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

**Comment by nusrat813** [comment]
verified fixed
