### ISSUE TITLE
5.1 Feedback:  labware card: copy API name icon does not match Figma

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#10093]
### Overview

labware card: copy API name icon does not match Figma

### Current Behavior

the copy icon on the labware card shows a clipboard icon.

### Expected Behavior

The copy icon on the labware card should show the new copy icon

### Steps To Reproduce

go to labware page and look at the copy icon on the labware card

### Operating system

Mac

**Comment by emilywools** [comment]
link to figma node: https://www.figma.com/file/l7BAJAGICr10ELsSqQD0Sr/UI-Overhaul?node-id=2180%3A85399

**Comment by koji** [comment]
This has been fixed by #10101

**Comment by y3rsh** [comment]
<img width="812" alt="image" src="https://user-images.githubusercontent.com/502770/170500311-d6b92d8f-c6aa-424d-a352-188465210140.png">
