### ISSUE TITLE
5.1 Feedback: radio button component does not match figma

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#10095]
### Overview

the radio button on the App Settings > Advanced > Tip length calibration settings do not match figma
![Screen Shot 2022-04-26 at 4 30 09 PM](https://user-images.githubusercontent.com/4339860/165387246-7b3b6103-dc44-47ab-9b72-865d56cc91c6.png)

### Current Behavior

the radio buttons on the tip length calibration settings do not match the figma designs, the selected radio button is gray

### Expected Behavior

the selected radio button should be blue with a blue outline. see this figma node: https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=1297%3A88764

### Steps To Reproduce

go to app settings > advanced

### Operating system

Mac

**Comment by koji** [comment]
This will be solved by #9767


![Screen Shot 2022-04-26 at 11 34 57 PM](https://user-images.githubusercontent.com/474225/165434802-2b1cb91c-3beb-41da-a73d-cb27c5edd668.png)

**Comment by y3rsh** [comment]
verified in alpha 1
![image](https://user-images.githubusercontent.com/502770/172620920-dfcfded4-51aa-42b7-ac1a-300ae958d814.png)
