### ISSUE TITLE
5.1 Feedback:  App is unresponsive when a failed analysis protocol is run

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#10098]
### Overview

When a failed analyzed protocol is run, choose a robot slideout appears -> but after clicking on "Proceed to setup" -> App is unresponsive

### Current Behavior

App does nothing when  "Proceed to setup" button is clicked
https://user-images.githubusercontent.com/39049853/165544252-3053437e-8f1b-4868-854b-bcf5c71ab678.mov
<img width="1410" alt="Screen Shot 2022-04-27 at 10 43 23 AM" src="https://user-images.githubusercontent.com/39049853/165544996-8baccccf-9bb2-43b3-9926-7a7bbe4566f9.png">

### Expected Behavior
![Screen Shot 2022-04-27 at 10 41 06 AM](https://user-images.githubusercontent.com/39049853/165544517-b0d03c92-a82a-46d2-b49f-80bcb530deb3.png)

### Steps To Reproduce

1. Click on the overflow menu of a protocol with failed analysis
2. Run option is available
3. click on the run button - and choose the robot to run the protocol on -click on proceed to setup
4. Robot is busy pop-up appears - clicking on clear and proceed to setup does nothing. App is unresponsive
5. Also, i am getting a 422 error on POST request on /protocols api.

**Comment by emilywools** [comment]
https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=8250%3A330560

**Comment by reachojhaneha** [comment]
Thanks @emilywools , if run option should be available for the protocol with failed analysis, i am getting a 422 error on POST request on /protocols api. 
<img width="1012" alt="Screen Shot 2022-04-27 at 10 24 37 AM" src="https://user-images.githubusercontent.com/39049853/165541085-a2aef7fa-6bc8-4465-8b7d-0b783b22f82e.png">

At the UI level, there is no response. App is not responding at all.

I will change the ticket with this 422 error issue

**Comment by nusrat813** [comment]
@reachojhaneha - please attach the file used for this error 
@mcous - try to repo 
@mikecardarelli - ticket for run creation failure (protocol + run creation bundle)

**Comment by reachojhaneha** [comment]
[upload_protocol.json.zip](https://github.com/Opentrons/opentrons/files/8594136/upload_protocol.json.zip)

**Comment by mikecardarelli** [comment]
@nusrat813 Do you remember what exactly needed a new ticket here? I can't remember what we decided on Friday.
