### ISSUE TITLE
5.1 Feedback:  Clearing unavailable robots removes the available robot and then brings it back to available robot

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#10108]
### Overview

clicking on "clear unavailable robots" -> clears the available robot, makes it unavailable -> and then brings it back to available robot

### Current Behavior

https://user-images.githubusercontent.com/39049853/165600462-9445b03e-55ab-4604-a8b4-695f7833267a.mov

### Expected Behavior

Only the unavailable robots should be removed and the unavailable robot section should not be displayed

### Steps To Reproduce

1. Click on "clear unavailable robots list" in Advanced settings in app settings
2. Now go to the devices page
3. Available robot goes to the unavailable state -> then coming back to the available state.
4. the correct behavior is unavailable robots should be removed and the unavailable robot section should be removed

**Comment by koji** [comment]
@reachojhaneha 
Had a conversation about this with the team. 
Actually, the current behavior isn't ideal but for now, we don't change this functionality.
