### ISSUE TITLE
5.1 Feedback:  missing fields (creation method, author, last analyzed , description) on protocol detail page

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#10100]
### Overview

Generate a PD protocol with author and description but when you upload that protocol on App -> the details are not populated. Same for python protocol

### Current Behavior

<img width="1020" alt="Screen Shot 2022-04-26 at 6 21 26 PM" src="https://user-images.githubusercontent.com/39049853/165402308-01c209ac-5ce1-4207-840a-2f3309a774f1.png">

### Expected Behavior

<img width="728" alt="Screen Shot 2022-04-26 at 6 22 02 PM" src="https://user-images.githubusercontent.com/39049853/165402379-438d14d0-f003-494f-8d96-1af8d2128df6.png">

### Steps To Reproduce

- Upload a protocol on the app
- Goto protocol details page -> creation method, author, description, last analyzed details are not displayed.

**Comment by reachojhaneha** [comment]
closing this issue as the feature is still in development. Just verified with Brian about it

**Comment by y3rsh** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/502770/170500060-3393251a-9efe-490a-b516-127113ec0ced.png">
