### ISSUE TITLE
5.1 Feedback:  App settings - custom labware source folder icon is too small

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#10105]
### Overview

App settings - custom labware source folder icon is too small
<img width="885" alt="Screen Shot 2022-04-27 at 12 06 26 PM" src="https://user-images.githubusercontent.com/4339860/165563351-c1cdbc9c-c610-48ca-b79d-b34b37be4660.png">

### Current Behavior

the icon to the right of the custom labware folder is too small

### Expected Behavior

the icon to the right of the custom labware source folder should be bigger / match figma
https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=1297%3A88764

### Steps To Reproduce

go to app settings > advanced > custom labware source folder

### Operating system

Mac

**Comment by koji** [comment]
@emilywools @mmencarelli 
Actually, the current code is using the same size as well as Figma (8px `spacing3` 0.5 rem)

What do you think about the followings?

0.7 rem
![Screen Shot 2022-04-27 at 4 41 44 PM](https://user-images.githubusercontent.com/474225/165627719-54ee1ab5-2469-4951-bad3-7517791f8a13.png)

1 rem
![Screen Shot 2022-04-27 at 4 42 06 PM](https://user-images.githubusercontent.com/474225/165627756-4d9adfcf-aae8-4c08-a759-de7e998182ed.png)

**Comment by y3rsh** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/502770/170499453-15cef562-f0f5-4f2b-b414-e93cb848fe75.png">

**Comment by emilywools** [comment]
wow the text hierarchy looks SO much better too!!!!!!!
