### ISSUE TITLE
5.1 Feedback:  Robot Settings > Advanced > Usage settings styling is off

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#10106]
### Overview

 Robot Settings > Advanced > Usage settings styling is off
<img width="1136" alt="Screen Shot 2022-04-27 at 12 13 45 PM" src="https://user-images.githubusercontent.com/4339860/165564261-456a8d7e-776a-4362-b1c2-454dddf01b28.png">

### Current Behavior

the font size and spacing is not correct for the usage settings section of the advanced app settings

### Expected Behavior

the "usage settings" should be h3-semibold
the individual item title underneath this section should be p-semibold

https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=1297%3A90420

### Steps To Reproduce

go to robot > settings > advanced

### Operating system

Mac

**Comment by koji** [comment]
@emilywools 
`Usage Settings` is h3 and font-weight 600
![Screen Shot 2022-04-27 at 5 54 22 PM](https://user-images.githubusercontent.com/474225/165637818-1bb2823e-2e01-4389-b1ec-f68b246d3ea1.png)

`Pause protocol when robot door opens` is p and font-weight 600
![Screen Shot 2022-04-27 at 5 55 25 PM](https://user-images.githubusercontent.com/474225/165638058-e1245175-e702-47b9-9446-b4d8feff91ae.png)

**Comment by emilywools** [comment]
hmm thanks for looking into this @koji. [@mmencarelli](https://github.com/mmencarelli) can you investigate why this looks off?

**Comment by emilywools** [comment]
@mmencarelli is going to create a new ticket to capture this feedback. closing for now
