### ISSUE TITLE
6.0 Feedback:  deckmap is missing on slideout of device page for protocols that have long names

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#10109]
### Overview

A protocol with long name doesn't displays the deck map.

### Current Behavior

<img width="1440" alt="Screen Shot 2022-04-27 at 3 17 00 PM" src="https://user-images.githubusercontent.com/39049853/165602806-4fa4ff48-45a6-4f0d-a832-4acbed29f351.png">

The protocol has a very large name, hence the deck map is not displayed on the choose a protocol slideout

### Expected Behavior

<img width="301" alt="Screen Shot 2022-04-27 at 3 17 56 PM" src="https://user-images.githubusercontent.com/39049853/165602987-e9caf047-0155-461a-99ec-5927c1a0a528.png">
 
deckmap and the protocol name should be displayed

### Steps To Reproduce

Upload a protocol with large name
On the device page, choose a robot -> click on Run protocol button
Choose a protocol slideout appears -> the protocol with large name doesn't displays the deckmap

**Comment by nusrat813** [comment]
@mmencarelli - can you create what the design for the following: 
-if title was >3 lines 
-file name with no space

**Comment by emilywools** [comment]
I talked to @b-cooper and we want to take this approach:

items to address this issue:

- [ ] deckmap needs a min width so the size is consistent no matter how long the text is
- [ ] protocol name should be displayed as 3 lines max (if it can wrap), if it can't wrap because the name has no spaces, truncate using ellipses at 1 line; add a title attribute so a user can see the full name on hover

**Comment by mmencarelli** [comment]
> I talked to @b-cooper and we want to take this approach:
> 
> items to address this issue:
> 
> * [ ]  deckmap needs a min width so the size is consistent no matter how long the text is
> * [ ]  protocol name should be displayed as 3 lines max (if it can wrap), if it can't wrap because the name has no spaces, truncate using ellipses at 1 line; add a title attribute so a user can see the full name on hover

Sorry @nusrat813 — still needing a system on how to keep track of github mentions. Thanks, @emilywools for following up with @b-cooper. That sounds good! Min-width size should be 76px, and 3 lines max truncating content if there's more is perfect.

**Comment by koji** [comment]
![Screen Shot 2022-05-19 at 9 57 19 PM](https://user-images.githubusercontent.com/474225/169433536-d880328a-8a15-47f7-aab3-91ec106e7d3b.png)
