### ISSUE TITLE
6.0 Feedback:  App settings main nav active state is missing

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#10104]
### Overview

When a user is on the app settings page, the left nav does not indicate that this is the active nav item if the user goes to the Privacy or Advanced tab
<img width="1136" alt="Screen Shot 2022-04-27 at 12 08 45 PM" src="https://user-images.githubusercontent.com/4339860/165563153-6b8f4197-194e-44e3-980d-3c6d4dda8161.png">

<img width="1136" alt="Screen Shot 2022-04-27 at 12 08 12 PM" src="https://user-images.githubusercontent.com/4339860/165563157-7c255f90-8b1e-4075-b480-d2e6a7344497.png">

### Current Behavior

When a user is on the app settings page, the left nav does not indicate that this is the active nav item

### Expected Behavior

when a user is on the app settings page, the left nav should display the active state for the app settings icon

### Steps To Reproduce

open the app, go to app settings and go to the privacy or advanced tab

### Operating system

Mac

**Comment by nusrat813** [comment]
Only a problem for app settings - privacy advanced and feature flags
