### ISSUE TITLE
5.1 Feedback:  Robot detail page offline state styling

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#10116]
### Overview

the pipettes and modules text for the offline robot detail page ("Robot must be on the network to see pipettes and modules") should be centered instead of left aligned

<img width="1136" alt="Screen Shot 2022-04-28 at 8 25 15 AM" src="https://user-images.githubusercontent.com/4339860/165752053-d6dd9021-fa6e-4c42-823e-b55e9b954707.png">

### Current Behavior

the pipettes and modules text on the robot detail page offline state ("Robot must be on the network to see pipettes and modules") is left aligned

### Expected Behavior

the pipettes and modules text on the robot detail page offline state ("Robot must be on the network to see pipettes and modules") should be centered

https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=1297%3A91474

### Steps To Reproduce

click on an offline robot to go to the detail page. 

### Operating system

Mac

**Comment by nusrat813** [comment]
Verified fixed
