### ISSUE TITLE
6.0 Feedback:  wifi symbol is out of the <div> in robots slideout

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#10111]
### Overview

wifi symbol / usb symbol is out of the <div> on Robot slideout

### Current Behavior

<img width="315" alt="Screen Shot 2022-04-27 at 4 12 45 PM" src="https://user-images.githubusercontent.com/39049853/165623084-73d20644-a54c-4d5e-a280-0128aba1b8cc.png">

### Expected Behavior

![Screen Shot 2022-04-27 at 4 14 02 PM](https://user-images.githubusercontent.com/39049853/165623334-c8bc5e63-4ceb-4d75-8d42-a9a7f4caaccb.png)

### Steps To Reproduce

Goto Protocols landing page -> Goto protocols details page -> click on the protocol card, robots slideout opens.
the Wifi symbol / usb symbol is out of the <div>

**Comment by mmencarelli** [comment]
The first—text wrap with the wifi appended to the end of the 2nd line! Mocked up here
<img width="316" alt="Screen Shot 2022-05-02 at 11 30 13 AM" src="https://user-images.githubusercontent.com/54682054/166304493-ef281871-0823-49d3-913f-60de0930d6d8.png">

**Comment by y3rsh** [comment]
verified
<img width="800" alt="image" src="https://user-images.githubusercontent.com/502770/170497700-f4c9d0ec-be40-4e95-875a-c43c3094d8fe.png">
