### ISSUE TITLE
LL: Some product images contain a line on the right edge

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#10122]
# Current Behavior
Some labware images in the Labware Library contain a strange edge on the right edge
![Screen Shot 2022-04-28 at 2.17.31 PM.png](https://images.zenhubusercontent.com/5e20a4f595a33208d0d768ab/95bec806-2d51-483f-9c96-99fff8e984d6)

# Expected behavior
We should crop and reupload these images so they render correctly in the Labware Library and OT App 5.1. 

# Open questions

- [ ] Where do these images live in GitHub? I'm not seeing them in shared data

**Comment by koji** [comment]
@mikecardarelli @skyewindsor 
5.1.0 (I saw this when I reviewed labware PR from Sarah)
https://github.com/Opentrons/opentrons/tree/edge/app/src/organisms/Labware/LabwareDetails/images

old one?
https://github.com/Opentrons/opentrons/tree/edge/labware-library/src/images

**Comment by skyewindsor** [comment]
@koji There was only one image that I could find with this cropping line issue. So, I think this ticket is fully solved by https://github.com/Opentrons/opentrons/pull/10256

**Comment by koji** [comment]
@skyewindsor
If my memory serves me correctly,  we will need to move images into one folder.  #10163 
If we move images, we will need to modify the labware code. That is the reason why I said  'partially'.
