### ISSUE TITLE
6.0 Feedback: Confusing display of multiple runs of a protocol

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#10131]
### Overview

If I rerun multiple protocols of the same name they load in the app in a confusing order. I show a lot of duplicates, but I have to keep track of the timestamps. That is not ideal.

**Comment by nusrat813** [comment]
@nusrat813 Sorting ticket open - what is the default sorting order? 

date of the last run is not in scope for 5.1.0

**Comment by y3rsh** [comment]
@nusrat813 link sorting ticket.

**Comment by nusrat813** [comment]
Sorting PR - https://github.com/Opentrons/opentrons/pull/10223

**Comment by nusrat813** [comment]
The default sorting should be alphabetical
