### ISSUE TITLE
Epic: Liquid Setup in OT App

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#10133]
# Overview
Beginning in OT App 5.0, users can easily review:

- (1) their robot’s calibration data

- (2) the module setup information

- (3) the labware setup information before running their protocol on the OT-2

One request that we’ve heard consistently from customers is that they would like to be able to view the (4) liquid setup information for their protocol. 

For the OT App 6.1 release, we’d like to begin showing liquid setup information in the UI:

- In a 4th protocol setup accordion on the protocol run details page 

- And in a new liquids tab on the protocol details page 

This will be easier to implement for PD protocols since liquid information is already included, but some experimental new API endpoints will be needed to support this functionality within Python protocols.

**Comment by SyntaxColoring** [comment]
Closing this old ZenHub epic as stale. We've moved these things to Jira.
