### ISSUE TITLE
feat(PAPIv2): Add new Python interfaces to support Liquid Setup

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#10134]
## Overview

As a Python protocol creator, I would like to define the state of protocol liquids at protocol start.

## Acceptance criteria

A Python protocol author may:

- [ ] Define a liquid with a name and optional metadata
- [ ] Load that liquid into various wells in the protocol's loaded labware

An HTTP API client may:

- [ ] Observe the loaded liquid locations in the output from protocol analysis / runs

## Implementation notes

This ticket requires two main pushes:

- A new method (or methods) of the Python Protocol API v2 to create and load liquids
- A mapping of the `broker` notifications of that method to the ProtocolEngine commands added in #10158

### Proposed Python API

Keeping things as close as possible to the JSON schema:

```python
from opentrons.protocol_api import ProtocolContext
metadata = {
    "apiLevel": "2.14",  # < or whatever, new PAPIv2 version necessary
}


def run(protocol: ProtocolContext) -> None:
    well_plate = protocol.load_labware("corning_96_wellplate_360ul_flat", location=2)
    
    water = protocol.create_liquid(    # simply returns a dataclass, does not issue a command
        displayName="water",
        displayColor="#0000ff"
        description="Good ol' H20"
    )

    protocol.load_liquid(    # issues a command, maps to PE `LoadLiquid`
        labware=well_plate,
        liquid=water,
        volumeByWell={
            "A1": 100,
            ...
        }
    )

    ...
```

## Feedback space

Collecting feedback here from the thread(s) below:

- Using `Well` interfaces is preferable to string names
- Loading a single liquid into multiple wells is important
    - Would loading a single liquid into multiple labware also be important?
    - Maybe something like `protocol.load_liquid(..., locations=[well_plate['A1'], ...])`

**Comment by SyntaxColoring** [comment]
Some API thoughts off the top of my head.

-----

The Python Protocol API has several good ways of addressing wells—by name, by number, by row/column, etc. We can let people use all of them by operating on `Well` objects instead of IDs.

So instead of this:

```python
protocol.load_liquid(
    labware=well_plate,
    liquid=water,
    volumeByWell={
        "A1": 100,
        ...
    }
)
```

I think we should do something like this:

```python
protocol.load_liquid(
    liquid=water,
    location=labware["A1"],
    volume=100,
)
```

Or:

```python
labware["A1"].load_liquid(water, volume=100)
```

This would also enable nice forms of reuse, like:

```
master_mix_well = labware["A1"]

master_mix_well.load_liquid(master_mix_liquid)

pipette.aspirate(master_mix_well, 10)
```

-----

Do we want `volume=...`  or `ul=...`?

-----

The point of this, for now, is for the Opentrons App to present a view of all the liquids the operator is expected to physically load into the robot **as part of protocol setup.**

At what point in the protocol do we take the snapshot of which liquids have been loaded so far? Which `load_liquid()`s are part of protocol setup and which ones are after?

Options off the top of my head:

* Report *all* the liquids that are loaded *anywhere* in the protocol. 
    * I don't think we should do this. Effectively, we'd be making every `load_liquid()` command part of the *initial protocol setup,* and I think we want to avoid painting ourselves into that corner. We'd be making things quite difficult to extend for supporting changing deck state, where a scientist may want multiple separate liquid load points throughout their protocol.
* Report all the liquids that are loaded before the first "movement command."
    * I guess this would work, but it feels like a hack to me. It's implicit and hard to explain.
* Mark the bounds of the setup part of the protocol explicitly with something like `protocol.mark_done_setup()`.
    * I personally favor this solution at the moment, but it's also hard to explain, in its own ways.

**Comment by ecormany** [comment]
> ```python
> labware["A1"].load_liquid(water, volume=100)
> ```

This feels nice and idiomatic. Would similar syntax be viable for loading into multiple wells at once?

----

> Do we want `volume=...` or `ul=...`?

We strongly _discourage_ using a `u` when writing the abbreviation for microliters, so I equally strongly favor `volume`. It's also the name used in `transfer()` etc., although it's often omitted there.

----

> At what point in the protocol do we take the snapshot of which liquids have been loaded so far? Which `load_liquid()`s are part of protocol setup and which ones are not?

This really is about modifying the deck state by manually loading additional liquids. The only way to reliably do that now is with `pause()`, so another option would be to consider everything before the first pause "initial". If other, more specific modification calls are added at some point, they could also be added to the list of triggers.

**Comment by SyntaxColoring** [comment]
> > ```python
> > labware["A1"].load_liquid(water, volume=100)
> > ```
> 
> This feels nice and idiomatic. Would similar syntax be viable for loading into multiple wells at once?

I'd hope we get that for free with `for` loops.

```python
for well in labware.columns()[0]:
    well.load_liquid(water, volume=100)  # Load 100 µL of water into each well of the leftmost column.
```


> > Do we want `volume=...` or `ul=...`?
> 
> We strongly _discourage_ using a `u` when writing the abbreviation for microliters, so I equally strongly favor `volume`. It's also the name used in `transfer()` etc., although it's often omitted there.

Yeah. I'm not too worried about the µL vs. ul thing here, personally. Python has different orthographic rules than English, so it has different conventions, and that's okay. Another example: we have a style rule to capitalize "GEN2" in pipette names, but it would be weird if I spelled a Python variable as `p300_single_GEN2`; it should be `p300_single_gen2`.

**Comment by ecormany** [comment]
Fair enough on the `ul` point. Even so, `volume` follows our own Python-based precedent.

**Comment by TamarZanzouri** [comment]
moved to Jira
