### ISSUE TITLE
feat(engine): Update analysis responses to include liquid setup information

### ISSUE THREAD

**Issue by mattwelch** [Opentrons/opentrons#10158]
As an Opentrons client application, I would like to receive information from the robot (in the analysis results) about the liquid setup at the start of a protocol run.

This work support #8909 and #8833

## Acceptance Criteria

- [ ] Liquid setup is built into the protocol translation layer
- [ ] Engine can consume and store load liquid/liquid setup commands (to be able to report back in analysis results)
- [ ] Liquid setup representation in JSON schema v6 is finalized and agreed upon
- [ ] Consensus on serialization support

## Implementation notes

- Add `LoadLiquid` (and `LoadLiquidParams`, etc.) command interfaces to `ProtocolEngine`
    - Params: check JSONv6 schema 
    - Implementation can be no-op
- `loadLiquid` commands in JSONv6 protocols should be properly translated to engine command
    - Note: in the engine, `params.liquidId` should be optional

### Not in scope

- At this time, we do not need to track liquids in ProtocolEngine state
    - Instead, the UI will do this based on commands
    - In the future, adding reactions to the ProtocolEngine state store to `LoadLiquid` + liquid handling commands will allow us to add backend liquid tracking as needed

**Comment by TamarZanzouri** [comment]
moved to Jira
