### ISSUE TITLE
Update API docs with new Python liquid setup commands

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#10164]
# Overview
Once we add the new API endpoints for liquid setup in Python protocols, we'll need to make sure we update the Python API docs to explain how to use this new feature. The API reference should automatically be updated, but this ticket is to track any additional documentation that we'll need. 

# Acceptance criteria

- [ ] Users can read in our documentation about how to add liquid setup information to their Python protocols

**Comment by ecormany** [comment]
This was completed in #12251.
