### ISSUE TITLE
Run record: collapse all accordions by default

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#10179]
when a user lands on the run record setup tab (after selecting a robot + protocol), collapse all accordion steps by default so a user can see an overview of all steps.

**Comment by b-cooper** [comment]
This should have been closed by previous LPC enhancement  PR, confirm this in edge then close

**Comment by emilywools** [comment]
confirmed that all accordions are collapsed in edge![Screen Shot 2022-05-13 at 3.27.49 PM.png](https://images.zenhubusercontent.com/5f57e13054c0d9cd55c2adb3/2ac4b2a5-c888-4e03-b64f-d0d5b2b3d760)

**Comment by y3rsh** [comment]
verified
