### ISSUE TITLE
5.1 Feedback:  Devices > Robot Detail> Magnetic module Set engage height button becomes clickable 

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#10172]
### Overview

On a robot detail page when you click the magnetic module overflow menu > set engage height and you put in an integer value (in or out of acceptable range) then delete it, the "Set Engage Height" button becomes active and you may click it.  
![image](https://user-images.githubusercontent.com/502770/166291853-18ded844-092f-4fe9-b4d2-0b18c737111a.png)

> seems to be happening on similar slideouts like Temperature Module > Set module temperature 

### Current Behavior

"Set Engage Height" button is clickable when the engage height value field is empty

### Expected Behavior

"Set Engage Height" button is only clickable when the engage height value is present and in range.

### Operating system

Mac

**Comment by b-cooper** [comment]
confirm this is not a problem in edge as it should have been fixed by previous work by @sakibh

**Comment by emilywools** [comment]
confirmed that this is fixed in edge![Screen Shot 2022-05-13 at 3.22.48 PM.png](https://images.zenhubusercontent.com/5f57e13054c0d9cd55c2adb3/25dfae36-723d-44bb-8b2c-d0ab567036ce)
