### ISSUE TITLE
5.1 Feedback:  OT-2 serial number isn't showing up 

### ISSUE THREAD

**Issue by Gyliann** [Opentrons/opentrons#10184]
### Overview

I am unable to see the my OT-2 serial number

### Current Behavior

Currently my OT-2 serial number says muddy-dawn 

### Expected Behavior

My serial number should say OT220...

### Steps To Reproduce

1. Click on my OT-2 
2. Went to advance settings 
3. Following that, I looked for the robot serial number 
<img width="960" alt="Screenshot 2022-05-02 172726" src="https://user-images.githubusercontent.com/74389436/166331476-0a2bc5f3-c069-4900-9bab-2e07d8e16ace.png">

### Operating system

Windows

### Robot setup or anything else?

Connected to WIFI. I have 14 unavailable OT-2s on my app

**Comment by koji** [comment]
This is expected behavior. Got the confirmation from Brian.
