### ISSUE TITLE
Make selected path more visible

### ISSUE THREAD

**Issue by anthonywilleee** [Opentrons/opentrons#10196]
# Overview

It is difficult for users to tell what path is selected on a Transfer step. To make this clearer, we will put each transfer path selection (single, multi-aspirate, multi-dispense) on its own row, with a radio button next to each selection

![Screen Shot 2022-05-03 at 4.00.53 PM.png](https://images.zenhubusercontent.com/5f772bd73389cd8dbeb34a48/5eae0f3e-7463-47f7-bdef-a035b06da3b8)

# Implementation Details

- Each transfer path selection (single, multi-aspirate, multi-dispense) will exist on its own row
- There is a radio button next to each path selection, to make it clearer which path is selected
- If multi-dispense is selected, multi-dispense input fields display under the selection

# Design Links

- https://www.figma.com/file/695ogls23YsQYImRcGYDE1/Heater-Shaker?node-id=3308%3A86368

# Acceptance Criteria

- Each transfer path selection (single, multi-aspirate, multi-dispense) exists on its own row
- There is a radio button next to each path selection, to make it clearer which path is selected
- If multi-dispense is selected, multi-dispense input fields display under the multi-dispense selection
- All other functionality remains the same

**Comment by sanni-t** [comment]
Closing as outdated.
