### ISSUE TITLE
6.0 Feedback:  Support link is broken on unavailable robots

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#10206]
### Overview

When i click on "Why is this robot unavailable?" modal on unavailable robot -> "[Learn more about troubleshooting connection problems]" -> app doesn't redirect to the support document

### Current Behavior

<img width="1031" alt="Screen Shot 2022-05-04 at 10 37 59 AM" src="https://user-images.githubusercontent.com/39049853/166705088-e378e310-d2b5-4a28-99db-cac8d229cb60.png">

### Expected Behavior

Support document should be launched in a browser 

### Steps To Reproduce

1. Goto unavailable robots
2.  Clickon overflow menu -> choose "Why is this robot unavailable?" when the modal opens up
3. click on "[Learn more about troubleshooting connection problems]"
4. When i click on (https://support.opentrons.com/en/articles/2687601-troubleshooting-connection-problems) - the document is available
5. Link broken between app and support doc

**Comment by emilywools** [comment]
here is the SFDC link: https://support.opentrons.com/s/article/Troubleshooting-connection-problems

**Comment by y3rsh** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/502770/170496040-2ce3c410-6abc-4e68-bf2c-04265a219c18.png">
