### ISSUE TITLE
6.0 Feedback: Open menu overflow appears above of a slideout on T1 Protocols

### ISSUE THREAD

**Issue by mmencarelli** [Opentrons/opentrons#10209]
### Overview

Menu overflow appears above of the slideout on T1 Protocols when you click 'import'

### Current Behavior

[Loom video](https://www.loom.com/share/b17be4e6e91d4dc5b6062aacdf8e21bb)

### Expected Behavior

The menu should be below the slideout, or automatically closes when you perform another action (like open another menu, or click the import button)

### Steps To Reproduce

n/a

### Operating system

Mac

### Robot setup or anything else?

n/a

**Comment by y3rsh** [comment]
Verified.  Now when you click import the menu disappears.  On the next click you can then click import.
