### ISSUE TITLE
6.0 Feedback [Design QA]:  Global Component, navbar, #10147

### ISSUE THREAD

**Issue by mmencarelli** [Opentrons/opentrons#10203]
### Overview

This issue references the overarching 'Global Components' ticket, #10147

---

### Current Behavior

n/a

### Expected Behavior

<img width="521" alt="Screen Shot 2022-05-03 at 3 19 37 PM" src="https://user-images.githubusercontent.com/54682054/166577024-6cbafe9c-1384-41c7-bc0b-5b1cad7d9161.png">

- [x] Add dark-grey/hover (#24313F) to the library
- [x] Add dark-grey/selected (#24313F) to the library
- [x] Update the .Navbar__NavbarLink :hover to the dark-grey/hover
- [x] Update the .Navbar__NavbarLink :selected to the dark-grey/selected 
- [x] Update the icon color (#e3e3e3)

### Steps To Reproduce

n/a

### Robot setup or anything else?

n/a

**Comment by koji** [comment]
@mmencarelli 
if you want to link to a specific issue, you just need to type #number since GitHub creates a link automatically.
