### ISSUE TITLE
Add additional client-side restrictions on robot names to protect against robot-side bugs 

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#10214]
# Overview

Currently, the Opentrons App validates robot names according to ~~these rules~~ [rules similar to these](https://github.com/Opentrons/opentrons/issues/10214#issuecomment-1119767036): 

> You can use letters, numbers, spaces, special characters (!?$*) and emojis.
> 35 characters max

And in theory, the OT-2 can have a display name that's mostly arbitrary Unicode.

In practice, robot renaming has several bugs:

* https://github.com/Opentrons/opentrons/issues/9960
* https://github.com/Opentrons/opentrons/issues/10126
* https://github.com/Opentrons/opentrons/issues/10197
* https://github.com/Opentrons/opentrons/issues/10198

Since the OT-2 persists its display name across boots, hitting some of these bugs can have lasting effects. So, out of conservatism, in the initial release of the robot rename feature, we should limit input to names that are unlikely to trigger any of these bugs.

When these bugs have been resolved and we've had more time to vet our back-end code, we can lift these restrictions, and go back to the app's current restrictions of:

# Acceptance criteria

* The Opentrons App's robot rename field should only allow ASCII A-Z and ASCII 0-9 [edit: and ASCII lowercase a-z]. This means it should *disallow* spaces, special characters, and emoji. 
* The Opentrons App's robot rename field should continue to disallow names longer than 35 characters.
    * I believe the robot can safely handle ASCII names less than 63 characters long (and perhaps exactly 63—unclear). My understanding is that the current limit of 35 comes from the app's own design and testing concerns.
* Copy should also be updated.
* Since these new restrictions are intended to be temporary, I suggest leaving a `# TODO` comment pointing back to this ticket for traceability.

**Comment by koji** [comment]
@SyntaxColoring 
We changed the rules of a robot name

>Choose a name for your robot. You can use letters, numbers, spaces, and these special characters: !?$*’-_.
We disallow a user to use space for the first letter.

**Comment by SyntaxColoring** [comment]
Noted, thanks. I think this ticket still stands. Anything not ASCII A-Z 0-9 is at risk of not being handled correctly.

**Comment by koji** [comment]
> @SyntaxColoring Are lowercase letters acceptable?

@mikecardarelli  I got confirmation from Max. The lowercase letters are acceptable.
