### ISSUE TITLE
robot-server: "reset" stored runs

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#10238]
## Overview

As an HTTP API client, I'd like to reset the state of my robot's run history. This supports the UI #8792.

## Acceptance criteria

- [ ] Factory reset slide-out in app includes "Run history"
    - This UI is driven by the endpoint
- [ ] Removing "run history" removes all stored runs, protocols, and analyses

## Implementation notes

* The best way to implement is likely to remove and re-create the database entirely.
    * Edit @SyntaxColoring: I agree with this, but we should make sure there won't be any problems with deleting the database and protocols directory while it's in use.

**Comment by TamarZanzouri** [comment]
meeting notes with @SyntaxColoring @aptrons22 :
1. add reset runs option in route:
'/settings/reset/options'
mark option as reset after 
2. after adding the option to the list 
change route '/settings/reset'
to accept the option id set to true 
3. move logic to a collaborator class? if its api level use api reset() else mark db file to delete

DB actions should include: 
on robot reboot drop the DB\delete file
