### ISSUE TITLE
bug: H-S driver side parsing issue

### ISSUE THREAD

**Issue by shlokamin** [Opentrons/opentrons#10249]
# Overview

When attempting to close the H-S labware latch from the H-S module card, there is a H-S driver-side parsing issue where the parser expects a different response than it's getting from the firmware. 

# Steps to reproduce

Try to close the labware latch from the app, you should see this error below:

```
"error": {
                "id": "b2932d62-78bf-488b-b7e9-4d9001abff7a",
                "errorType": "UnexpectedProtocolError",
                "createdAt": "2022-05-09T21:17:26.277516+00:00",
                "detail": "ParseError(error_message=Unexpected argument to parse_labware_latch_status_response, parse_source=M241 STATE:IDLE_CLOSED)"
            }, 
```

**Comment by laviera** [comment]
@pmoegenburg - Can u check on this ticket related to parsing issue ?
