### ISSUE TITLE
6.0 Feedback:  [Design QA] Robot Settings Page#10151 & Robot Settings > Advanced > Usage settings styling is off #10106

### ISSUE THREAD

**Issue by mmencarelli** [Opentrons/opentrons#10263]
### Overview

Round 1 design QA for Robot Settings page

### Current Behavior

View the [annotated Figma frame](https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=11756%3A288136)

----
**Calibration**
- [x] (1) Update the font styling here to the updated label font size  (11 font size, 12px line height)
- [x] (2) Update font colour to our 'dark-black'
- [x] (3) Update this link to our 'link/primary/blue/internal' styling. There's a heavier font weight and a hover state
- [x] (4) Update the tertiary button styling. Need correct hover/pressed/potentially disabled state (cant activate disabled using devtools)
- [x] (5) Are we nixing the rest of the content on this page? If so, let's nix that last line beneath content. Also, let me know so I can update designs.

**Networking**
- [x] (1) Update all text to our 'dark-black' on this page
- [x] (2) Should be semi-bold
- [x] (3) Update to our 'input/field-with-label' component. The label should be our label styling, currently our p styling
- [x] (4) Missing 24px margin
- [x] (5) Double the size of the icon, should be 12x12
- [x] (6) Missing hover state on the primary link styling
- [x] (7) 1rem spacing between link and "looking for
- [x] (8) Need to update these icons

**Advanced**
- [x] (1) Bit too much spacing here, should be 1rem from the edge of the container
- [x] (2) Update all text to our 'dark-black' on this page
- [x] (3) Should be 1 rem beneath each section header (about, usage settings, trouble shooting, legacy settings). Also, making a last-minute decision to update the headers from h3's to h2's and semibold to help add some distinction.
- [x] (4) Update tertiary button style
- [x] (5) Needs our link styling (semibold, hover states)
- [ ] (6) Missing the 'update now' button? This displays when the toast saying there's an update available. 
- [x] (7) Upping the margin to 40px between each section (sorry, this is new!)
- [x] (8) Update these to our toggle component
- [x] (9) Update size of font, size of icon and add the states in
- [x] (10) Looks like a margin-bottom of 1rem snuck in there

<img width="1173" alt="Screen Shot 2022-05-10 at 3 14 21 PM" src="https://user-images.githubusercontent.com/54682054/167730538-fcedac8b-d5aa-4a53-9dd6-e89663d25ac6.png">
<img width="1188" alt="Screen Shot 2022-05-10 at 3 14 27 PM" src="https://user-images.githubusercontent.com/54682054/167730547-6176e1bf-03fc-4d17-88f4-3b0dff066241.png">
<img width="1206" alt="Screen Shot 2022-05-10 at 3 14 34 PM" src="https://user-images.githubusercontent.com/54682054/167730551-3c1ab1ad-d947-4592-88a8-a4e5092114a4.png">
<img width="1223" alt="Screen Shot 2022-05-10 at 3 14 38 PM" src="https://user-images.githubusercontent.com/54682054/167730555-ede762dc-e080-4dff-a7a7-80b343deb7eb.png">

**Comment by koji** [comment]
https://user-images.githubusercontent.com/474225/168160607-9fd4c41c-f880-4a47-bd0b-a7ef239b071c.mov

**Comment by koji** [comment]
![Screen Shot 2022-05-12 at 5 33 12 PM](https://user-images.githubusercontent.com/474225/168171715-e6601453-1f07-4481-85b3-41dec326f114.png)

**Comment by koji** [comment]
@mmencarelli 
![Screen Shot 2022-05-12 at 6 03 36 PM](https://user-images.githubusercontent.com/474225/168175456-319d7ee6-b4ba-4c4f-9b5a-a1a09ea25428.png)

**Comment by mmencarelli** [comment]
> @mmencarelli ![Screen Shot 2022-05-12 at 6 03 36 PM](https://user-images.githubusercontent.com/474225/168175456-319d7ee6-b4ba-4c4f-9b5a-a1a09ea25428.png)

Yup, I can see the confusion. If you step out two levels you'll see that the component includes some padding around the vector. So vector is 8x8, but there should be some padding around it that cause it to be 12x12. [Video here](https://www.loom.com/share/35a60164e3344afa9ab61fa54847006b)

**Comment by koji** [comment]
@mmencarelli thank you for the video.

After checking components, noticed that ExternalLink's line-height was 16px instead of 20px.

The following is line-height 20px. What do you think of these?

0.5 rem 8px
<img width="337" alt="Screen Shot 2022-05-13 at 10 39 04 AM" src="https://user-images.githubusercontent.com/474225/168308075-a05aec14-a6db-4fbe-9225-aa157b3eb7ef.png">

0.6 rem 9.6px
<img width="392" alt="Screen Shot 2022-05-13 at 10 44 18 AM" src="https://user-images.githubusercontent.com/474225/168308515-3875c047-3571-486f-97b9-1c6e8d721d29.png">


0.75 rem 12px
<img width="355" alt="Screen Shot 2022-05-13 at 10 40 16 AM" src="https://user-images.githubusercontent.com/474225/168308196-63115318-b8b3-47fa-86e8-729b0f31294e.png">

**Comment by koji** [comment]
Default fontColor `#4a4a4a`

**Comment by koji** [comment]
![Screen Shot 2022-05-13 at 7 56 08 PM](https://user-images.githubusercontent.com/474225/168402529-bf719e2b-7053-41fe-996e-13b879a410fe.png)

**Comment by mmencarelli** [comment]
> @mmencarelli thank you for the video.
> 
> After checking components, noticed that ExternalLink's `line-height` was 16px instead of 20px and added `align-items: center` to centralize text and icon vertically.
> 
> The following is `line-height` 20px. What do you think of these?
> 
> 0.5 rem 8px <img alt="Screen Shot 2022-05-13 at 10 39 04 AM" width="337" src="https://user-images.githubusercontent.com/474225/168308075-a05aec14-a6db-4fbe-9225-aa157b3eb7ef.png">
> 
> 0.6 rem 9.6px <img alt="Screen Shot 2022-05-13 at 10 44 18 AM" width="392" src="https://user-images.githubusercontent.com/474225/168308515-3875c047-3571-486f-97b9-1c6e8d721d29.png">
> 
> 0.75 rem 12px <img alt="Screen Shot 2022-05-13 at 10 40 16 AM" width="355" src="https://user-images.githubusercontent.com/474225/168308196-63115318-b8b3-47fa-86e8-729b0f31294e.png">

Love the options! 0.5 rem 8px is the one :)

**Comment by koji** [comment]
@mmencarelli Thank you for your feedback!

**Comment by koji** [comment]
- [ ] icon size 0.5 rem for ExternalLink
