### ISSUE TITLE
6.0 Feedback: clicking outside modal loads protocol detail page

### ISSUE THREAD

**Issue by ecormany** [Opentrons/opentrons#10277]
### Overview

There are three ways to dismiss analysis error modals, one of which unexpectedly goes to the protocol detail page.

### Current Behavior

Clicking outside a protocol analysis error modal moves from the protocol list page to the detail page for that protocol. Clicking the "X" button at the top of the modal or "Close" at the bottom of the modal dismisses the modal properly, returning to the protocol list page (which is visible underneath the modal the entire time).

This also happens when clicking outside the "Delete Protocol" confirmation modal.

### Expected Behavior

All three methods of dismissing the modal should behave identically, returning to the immediately previous (and still visible) page.

As an alternative, clicking outside the modal could do nothing, i.e. require the user to click a button to dismiss it.

### Steps To Reproduce

For error modals:
1. Import a protocol that will fail analysis. 
[tabs_and_spaces.py.zip](https://github.com/Opentrons/opentrons/files/8682729/tabs_and_spaces.py.zip)
2. Click on "error details" in the banner that appears on the newly imported protocol.
3. Click anywhere outside the modal that appears.

For deletion modals:
1. Click the overflow menu on any protocol in the list, and choose "Delete protocol"
2. Click anywhere outside the modal that appears.

https://user-images.githubusercontent.com/1958332/168172548-8af7cc5b-3a93-4f7a-9b21-e3611b7dbefa.mov

### Operating system

Mac

**Comment by y3rsh** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/502770/170495412-273e0093-5896-44c8-b5d4-fc14f0978f52.png">
