### ISSUE TITLE
6.0 Feedback: robot ignoring `delay()` commands in Python protocols

### ISSUE THREAD

**Issue by ecormany** [Opentrons/opentrons#10279]
### Overview

On v5.1.0-beta.0 of the robot server, all `delay()` commands are ignored. Downgrading to 5.0.2 resolves the issue.

### Current Behavior

When running a Python protocol on a robot running v5.1.0-beta.0 of the robot server, `delay()` commands have no effect. They appear in the run log for the protocol, but all other actions are performed as quickly as possible, with no delays.

### Expected Behavior

Each `delay()` action should pause the robot's movements for exactly as long as specified and as shown in the run log.

### Steps To Reproduce

1. Import a protocol that includes `delay()` commands.
[move.py.zip](https://github.com/Opentrons/opentrons/files/8682792/move.py.zip)

2. Run the protocol on a robot running the beta server.

Downgrading to robot server 5.0.2 restores the expected behavior. Upgrading to the beta again reintroduces the bug.

### Operating system

Mac

### Robot setup or anything else?

Robot Server Version
v5.1.0-beta.0

Robot Serial Number
OT2CEP20210812R11

Firmware Version
v1.1.0-25e5cea

**Comment by y3rsh** [comment]
@SyntaxColoring I reproduced this from edge.

**Comment by SyntaxColoring** [comment]
Also reproduced. Looking into this now.

**Comment by y3rsh** [comment]
Delays respected upon retesting.
