### ISSUE TITLE
Delay Command Kills Robot Run

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1028]
Using a 'delay' command in a protocol causes the protocol run to stop and not recover.

## Expected Behavior
- Robot should delay for specified amount of time and then continue running

## Observed Behavior
- Robot delays for specified about of time, begins next action (?), and then stops

## Steps to Recreate
- Connect to robot young-moon (science bot)
- Load a protocol with 'p300.delay(seconds=60)'
-- Tested with protocol copied below
- Run protocol
- Observe robot pause for appropriate amount of time at delay step, make an additional movement (possibly beginning of next aspirate?) and then stop
- Remove delay from protocol
- Run protocol and observe that it runs fine
- Note: also observed with 'robot.pause('')'

**Comment by btmorr** [comment]
Worked on this a little bit with Kinnary. It looks like this may have been a power-supply issue. Leaving the ticket open for now, but may not be a software bug
