### ISSUE TITLE
6.0 Feedback:  [Design QA] Global Components, App size + min-width #10147

### ISSUE THREAD

**Issue by mmencarelli** [Opentrons/opentrons#10289]
### Overview

This is some some overall feedback on viewport sizing. 

### Current Behavior

- [ ] Currently the app opens up at 1020x768px but I'd like to change it to 800x760px to match the designs in Figma
- [ ] Can we add a min-width to the app of 600px

**Comment by b-cooper** [comment]
Let's try to get this one in before the first release candidate is tagged

**Comment by ecormany** [comment]
Min width (and height) would also address https://github.com/Opentrons/opentrons/issues/9651.

**Comment by y3rsh** [comment]
default size is 800X760 and min width is 600
this is working on mac,linux, and windows.
