### ISSUE TITLE
6.0 Feedback:  Help icon in the app is disabled 

### ISSUE THREAD

**Issue by braldrich** [Opentrons/opentrons#10301]
### Overview

Clicking on the help icon in the lower left corner of the app, next to the settings icon, doesn't produce a response. 

### Current Behavior

Nothing happens when clicking the help icon. 
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/95253244/168679449-39064320-950b-4f20-9b70-e72773916898.png">

### Expected Behavior

Clicking on the app icon should bring you to a help page or resources for support. 

### Steps To Reproduce

Click on the help icon in the lower app, regardless of the section of the app that is active. 

### Operating system

Mac

### Robot setup or anything else?

Connected to robot via ethernet

**Comment by koji** [comment]
This has been solved by #10302
