### ISSUE TITLE
Usability: Larger Font On Deck Map and Labware

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1031]
As a user, I would like a larger font size for labware descriptions, so they're easier to see.

## Acceptance Criteria
- Increase font size for labware calibration deck map

## Design / Font Spec
- Zeplin -> Working Components Library -> Deck / OT2 / Slots / Labels

**Comment by umbhau** [comment]
@howisthisnamenottakenyet @pantslakz -- just doing some housecleaning. Is this still on the wishlist, or can i close it?

**Comment by howisthisnamenottakenyet** [comment]
@umbhau I'm down with closing it

**Comment by pantslakz** [comment]
Yes lets close, as we'll tackle this globally now via components
