### ISSUE TITLE
Usability: User-Friendly Robot States

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1033]
PLACEHOLDER
As a user, I would like understandable labels for my robot's current state.

## Acceptance Criteria
- Map back-end robot states to user friendly descriptions 
- Display states in Robot Settings page (existing feature)

## Copy
    - blank - "Ready"
    - ‘Loaded’ - "Loaded name_of_protocol.JSON"
    - ‘Running’ - "Running name_of_protocol.JSON"
    - ‘Paused’ - "Paused Name_of_protocol.JSON"
    - ‘Error’ - ? error with protocol, or error with robot ?
    - ‘Finished’ - "Finished running name_of_protocol.JSON"
    - ‘Stopped’ - "Stopped name_of_protocol.JSON" ?

**Comment by umbhau** [comment]
@mcous -- could you provide us with a list of robot states currently returned from the robot? Will come up with friendlier copy.

**Comment by pantslakz** [comment]
@mcous shared some robot states. I put them in with copy suggestions above - but uncertain about two of them (@umbhau thoughts?)

**Comment by Matt-Zwimpfer** [comment]
Will be addressed separately (App team)
