### ISSUE TITLE
Usability: Wifi Connected State

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1034]
As a user, I would like a clear indication that I've already connected to wifi (currently, the empty password field makes it looks like a to-do)

## Acceptance Criteria
- Add placeholder asterisks to the wifi connectivity password field if robot is currently connected to wifi

## Implementation Notes
- Open to other ideas (hiding pw field, etc).

**Comment by mcous** [comment]
Superseded by #2347
