### ISSUE TITLE
spike(robot-server): evaluate performance of async SQLAlchemy

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#10365]
## Overview

As currently implemented, our SQLite access for persistence in the the `/runs` and `/protocols` endpoints uses SQLAlchemy's default, synchronous API. The `robot-server` application uses a single-process, cooperative-multitasking architecture via Python's `async/await`.

Our synchronous database access _may_ be causing significant performance issues by blocking the application's thread(s) from processing other important tasks, like hardware interaction or executing protocol logic.

## Acceptance criteria

Expected output of this spike :

- [ ] A write-up about why or why not SQLAlchemy's async interface would improve
- [ ] If we expect performance to improve, a prototype swapping our usage of SQLAlchemy's `Engine` with its available async interface: [`AsyncEngine`](https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html)

**Comment by SyntaxColoring** [comment]
Cross-reference: #10025
