### ISSUE TITLE
6.0 Feedback:  "See how to setup a new robot" link on device landing page is broken

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#10384]
### Overview

"See how to setup a new robot" link on device landing page is broken

### Current Behavior

<img width="1025" alt="Screen Shot 2022-05-20 at 1 23 38 PM" src="https://user-images.githubusercontent.com/39049853/169580580-776bc2f0-8936-48e7-861c-1e9f67e3a06b.png">

When i click on "see how to setup a new robot" link is broken, there is no response

### Expected Behavior

upon clicking the link, a modal should opeen

### Steps To Reproduce

Go to device landing page -> click on "See how to setup a new robot"

**Comment by koji** [comment]
@reachojhaneha Does this happen to you when you click the link right after starting the app?

**Comment by reachojhaneha** [comment]
@koji , this happens all the time

**Comment by koji** [comment]
@reachojhaneha could you try this branch `app_fix-see-how-to-setup-new-robot-modal`?

**Comment by y3rsh** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/502770/170495803-6e1d4844-4d4e-4ad8-98e0-bb1be1d1d227.png">
