### ISSUE TITLE
Calibration Tab Not Visibly Active

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1038]
When a user arrives in the calibration tab via the 'calibrate' link in the protocol upload tab, the 'calibrate' primary nav tab is not visibly active (it is not dark grey).

## Expected Behavior
- 'Calibrate' tab in primary nav should be dark grey when active

## Observed Behavior
- 'Calibrate' tab in primary nav is inactive (not dark grey), despite being selected.

## Steps to Recreate
- Open run app Version 3.0.0 (3.0.0.6749)
- Connect to any robot
- Load any protocol
- Click "Continue to Calibrate to set up your pipettes and labware for the run" in the right page
- Observe that you are now on the 'Calibrate' page, but the 'Calibrate' primary nav tab is not active

**Comment by mcous** [comment]
This was fixed by #1578
