### ISSUE TITLE
6.0 Feedback:  Jump to current step feature  disappears after few seconds

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#10383]
### Current Behavior

Jump to current step feature disappears after few seconds
<img width="1026" alt="Screen Shot 2022-05-20 at 1 18 37 PM" src="https://user-images.githubusercontent.com/39049853/169579813-49fd2ab3-d6fb-422c-acf0-daf7a131e721.png">

### Expected Behavior

Jump to current step

### Steps To Reproduce

1. Run a protocol from protocol detail page
2. After the run is completed, jump to current step button is not displayed

**Comment by nusrat813** [comment]
@reachojhaneha Is this issue only happening when the run is complete?

**Comment by reachojhaneha** [comment]
@nusrat813 , i am seeing this button appear for a fraction of seconds and disappear after the run is completed
