### ISSUE TITLE
bug: Linux app does not launch on Ubuntu

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#10396]
## Overview

@nusrat813 and myself were unable to launch `edge` build of the app on Ubuntu as of 2022-05-20.

## Steps to reproduce

1. Download an `edge` build of the app
2. Do the usual app image stuff `chmod a+x ./Opentrons...AppImage`
3. Try to launch the app

## Observations

If you launch the production app from the terminal, you will see logs from the main process, so it _seems_ to be some sort of failure to launch the renderer process, or some partial failure of the main process that locks things up.

## Notes

We still need to find the regression point

**Comment by y3rsh** [comment]
I was able to launch the appimage https://s3.amazonaws.com/opentrons-app/builds/Opentrons-v5.1.0-beta.0-linux-b18160-edge.AppImage
on Ubuntu 22.04
I did have to `sudo apt install libfuse2` so that the appimage would run.
