### ISSUE TITLE
6.0 Feedback: Should "run a protocol" CTA be consistent throughout the experience?

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#10404]
### Overview

In some places the button to run a protocol says "run protocol" and in others it says "run a protocol"

do we need to be consistent? i think we are inconsistent because saying "run a protocol" on a protocol detail page sounds odd. But should we say "run protocol" everywhere?

cc @ecormany

**Comment by ecormany** [comment]
My intuition is that `Run protocol` means run a specific protocol. As @emilywools indicated, on the protocol detail page, the only protocol you can run is _that_ protocol. 

In contrast, `Run a protocol` means the user still has to pick which protocol — and strongly implies that will be the next thing they'll be asked to do after clicking the button. This is exactly the behavior on the device detail page.

Following this distinction, the one string that I've found that needs to change is in the device overflow menu: `Run protocol` should become `Run a protocol`.
