### ISSUE TITLE
6.0 Feedback: add current sorting method to labware landing page + protocols landing page

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#10403]
### Overview

right now the current sort order is not displayed, so the user never knows what sort order the page is currently in. We should display the sort order so its clear to the user.

see Figma: https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=1297%3A90568

### Current Behavior

current sort order is not displayed on protocols landing page and labware landing page

### Expected Behavior

sort order should be displayed by the sort button on the protocols landing page and the labware landing page

**Comment by koji** [comment]
- [ ] labware
- [ ] protocls
