### ISSUE TITLE
feat: labware creator copy fix

### ISSUE THREAD

**Issue by skyewindsor** [Opentrons/opentrons#10422]
# Overview

There are a couple copy updates that need to be made to the LC.

The labware creator copy states users can only implement a single channel pipette in the labware definition test protocol. Multichannels can be used in the test protocol for certain labware types, so this should be changed. 

Tip racks need to be added to the header paragraph as well. Details below. 

# Implementation details

Copy should include the multichannel and say: "Your file will be exported with a protocol that will help you test and troubleshoot your labware definition on the robot. The protocol requires a Single or Multi-Channel pipette on the right mount of your robot."

Screenshot of the location in LC: 
![Screen Shot 2022-05-24 at 9 53 56 AM](https://user-images.githubusercontent.com/95719575/170090589-734b4f9a-4985-48f8-a989-a3c916a2cea7.png)

The copy in the header of the Labware Creator should include tipracks and say: "This tool will allow you to create definitions for well plates, reservoirs, tubes in tube racks, tip racks, and plates/tubes in Opentrons aluminum blocks that do not already exist in the [Labware Library](https://labware.opentrons.com/)."

![Screen Shot 2022-05-24 at 10 07 35 AM](https://user-images.githubusercontent.com/95719575/170092887-7f84b8fc-ec22-4376-aa5a-ada3a5d7fd3f.png)

# Acceptance criteria

- [ ] Labware Creator test guide section includes Multichannel pipette copy
- [ ] The Labware Creator heading includes tip rack copy

**Comment by mikecardarelli** [comment]
New JIRA ticket: https://opentrons.atlassian.net/browse/RAUT-201
