### ISSUE TITLE
6.0 Feedback:  Copy tweak needed for "Why is my robot not avail" modal

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#10425]
### Overview

right now the "Why is my robot not available" modal has this line:

`If none of these work, contact Opentrons Support for help (via the chat link in this app, or by emailing support@opentrons.com).`

we should update this to the following

`If none of these work, contact Opentrons Support for help (via the question mark link in this app, or by emailing support@opentrons.com).`

**Comment by y3rsh** [comment]
verified
<img width="800" alt="image" src="https://user-images.githubusercontent.com/502770/170491104-1a8c61a2-3473-48fe-9edc-39971374450f.png">
