### ISSUE TITLE
feat: labware creator test guide fixes

### ISSUE THREAD

**Issue by skyewindsor** [Opentrons/opentrons#10424]
# Overview

There are a couple of fixes that need to be made to the Labware Creator labware definition test guide. Test guide can be found here and is linked at the bottom of the [Labware Creator](https://labware.opentrons.com/create/) page: https://opentrons-publications.s3.us-east-2.amazonaws.com/labwareDefinition_testGuide.pdf

# Implementation details

In the LC test protocol, step 2a is not executed. The python file needs to be updated to center over the last well in the labware like what step 2a indicates in the test guide. The labware test protocol can be found in the monorepo here: `labware-library/src/labware-creator/protocolTemplates/CustomLabware_testprotocol.py `
![Screen Shot 2022-05-24 at 10 19 06 AM](https://user-images.githubusercontent.com/95719575/170094755-c9fcb95f-0607-40f6-ab9b-c78f322dc6d2.png)

Also, at the bottom of the test guide, this sentence needs to be fixed to say "If your robot still misses the calibration points on the deck when you run this protocol contact support@opentrons.com". Make sure "teh" is corrected to "the" and there is a period in the support email address instead of a comma. 
![Screen Shot 2022-05-24 at 10 21 33 AM](https://user-images.githubusercontent.com/95719575/170095148-54d28b05-f688-48c7-adf7-acd260a0d710.png)

# Acceptance criteria

- [ ] Step 2a in labware definition test protocol is added
- [ ] The typos at the end of the test guide are fixed

**Comment by skyewindsor** [comment]
Hey @chazmanc I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/app--ui-5f6248dba845b000139aa767/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by mikecardarelli** [comment]
New JIRA ticket: https://opentrons.atlassian.net/browse/RAUT-198
