### ISSUE TITLE
6.0 Feedback: Robot update modal closes the first time you try to use it

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#10431]
### Overview

The first time I try to use the robot update modal, it closes without doing anything. Can reproduce consistently.

### Current Behavior

![2022-05-24 15 34 17](https://user-images.githubusercontent.com/2963448/170122163-a640b041-d361-4429-ae9a-65ec2a4ae5a2.gif)

### Expected Behavior

The robot update wizard should proceed when I click "View Robot Update"

### Steps To Reproduce

1. Using the production v5.0.2 app, get an OT-2 onto v5.0.2
2. Open the development app from `edge`
3. Navigate to "Devices"
4. Click on "View update" > "Update robot now" > "View robot update"
5. Wizard closes instead of proceeding

If you then go through steps 4 and 5 again, the robot update will proceed normally.

### Operating system

Mac

### Robot setup or anything else?

- My OT-2R was on v5.0.2 production
- My app was on `edge` (a731395)
    - As of this commit, the app is unable to update v5 robots: #10430
    - However, the premature wizard close seems orthogonal
- Feel free to close this ticket in favor of #9808 and/or #9809

**Comment by nusrat813** [comment]
Retest on alpha

**Comment by y3rsh** [comment]
https://user-images.githubusercontent.com/502770/170560462-f2c0bf3a-feb8-4e97-add9-125a2ceef5e8.mp4

**Comment by y3rsh** [comment]
verified fixed
