### ISSUE TITLE
6.0 Feedback: cannot re-install current software version to robot

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#10435]
### Overview

In the v5 release of the app, one can "re-install" the current version of the robot software. This is an important feature that can get around some weird issues, especially those caused by meddling with the robot's read-only filesystem.

### Current Behavior

There is no re-install button in the robot's advanced settings:

<img width="736" alt="Screen Shot 2022-05-24 at 17 37 00" src="https://user-images.githubusercontent.com/2963448/170136578-9bcb5150-0155-4821-aa08-db66277ffd1b.png">

### Expected Behavior

There should be a re-install button, according to the designs:

<img width="858" alt="Screen Shot 2022-05-24 at 3 57 36 PM" src="https://user-images.githubusercontent.com/2963448/170136662-d62aee61-3474-49fd-9908-af37cb64f1b9.png">

### Steps To Reproduce

1. Open the app
2. Navigate to a robot's advanced settings page

### Operating system

Mac

### Robot setup or anything else?

Tested on `edge` at 04f24cd

**Comment by mcous** [comment]
Still missing issue in `alpha.2`

## v6.0.0-alpha.2

<img width="1136" alt="Screen Shot 2022-06-10 at 09 01 05" src="https://user-images.githubusercontent.com/2963448/173070836-ae8a324a-e361-4fd1-9750-eb47e4708bc7.png">

## v5.x (expected)

<img width="1136" alt="Screen Shot 2022-06-10 at 09 12 44" src="https://user-images.githubusercontent.com/2963448/173071964-30b76b08-c70a-49ed-9c5e-2499668d56f4.png">

<img width="1136" alt="Screen Shot 2022-06-10 at 09 12 52" src="https://user-images.githubusercontent.com/2963448/173071969-98bb9499-e265-4fc7-8e8e-1d6640a53c60.png">

**Comment by bndo** [comment]
Closed by #10773

**Comment by y3rsh** [comment]
successfully re-installed 6.0.0-alpha.3 on my robot from the app.
