### ISSUE TITLE
6.0 Feedback:  white screen after renaming the robot name

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#10433]
### Overview

change the name of a robot -> then click on the advance tab on robot-settings. App goes blank

### Current Behavior

<img width="786" alt="Screen Shot 2022-05-24 at 5 13 36 PM" src="https://user-images.githubusercontent.com/39049853/170133389-bfc44417-91da-4d00-bd2c-cc16f5d98af1.png">

![Screen Shot 2022-05-24 at 5 13 59 PM](https://user-images.githubusercontent.com/39049853/170133453-4bba44ef-2ced-47ef-9fef-11e2408bc055.png)

### Steps To Reproduce

1. Goto robot-settings
2.  Goto to advance tab -> rename the robot -> enter a valid name -> click on rename robot button
3.  then click on advance tab -> app goes blank

### Operating system

Mac

**Comment by koji** [comment]
@reachojhaneha  Did you use a real robot when you rename the robot name?

**Comment by reachojhaneha** [comment]
@koji thats correct i used my real robot for renaming

**Comment by koji** [comment]
@reachojhaneha thanks.
I haven't seen that case before. I will go to the office tomorrow and try to reproduce that.
