### ISSUE TITLE
6.0 Feedback: app update available modal sized incorrectly

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#10434]
### Overview

- The size and overlay of the app's "App update available" modal seems wrong
- If you dismiss the modal at app launch, it pops up again, sized differently but still incorrectly, if you click the "gear" menu

#### App launch

<img width="912" alt="Screen Shot 2022-05-24 at 17 09 19" src="https://user-images.githubusercontent.com/2963448/170132901-d2456964-ea6b-4099-af36-cb3c321c417b.png">

#### App settings page

<img width="912" alt="Screen Shot 2022-05-24 at 17 25 45" src="https://user-images.githubusercontent.com/2963448/170135267-75e17b9d-b1a2-4664-b853-7a10a38106a5.png">

### Expected Behavior

Going off v5, I'd expect:

- The modal looks the same no matter where it opens from
- It doesn't open again after you dismiss it
- A darker opacity on the overlay, so it doesn't look like the nav UI is interactable
- A consistent margin around the entire modal

### Steps To Reproduce

1. Set your app's channel to `stable`
2. Close and relaunch the dev app from `edge`

### Operating system

Mac

**Comment by nusrat813** [comment]
Retest on alpha

**Comment by jerader** [comment]
@emilywools, what opacity do we want the background to be? Right now, it is at 35%

**Comment by mcous** [comment]
The vertical spacing still looks wrong to me, why was this closed?

## v5.x (expected vertical spacing)

<img width="1136" alt="Screen Shot 2022-06-10 at 08 49 15" src="https://user-images.githubusercontent.com/2963448/173067961-cb91a578-3c57-4afd-ae8f-8b397139befd.png">

## v6.0.0-alpha.2

<img width="1136" alt="Screen Shot 2022-06-10 at 08 48 47" src="https://user-images.githubusercontent.com/2963448/173068012-f4d7cb3f-b411-4ed6-8a67-4f103094e594.png">

**Comment by mcous** [comment]
Still present in `release_6.0.0` on 5d775be

<img width="1136" alt="Screen Shot 2022-06-30 at 12 04 53 PM" src="https://user-images.githubusercontent.com/2963448/176725328-915e6215-9a38-4266-9abb-2014266aba86.png">
