### ISSUE TITLE
6.0 Feedback:  title missing in labware detail slideout

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#10436]
### Overview

labware detail slideout has incorrect title 

### Current Behavior

<img width="820" alt="Screen Shot 2022-05-24 at 5 38 40 PM" src="https://user-images.githubusercontent.com/39049853/170137463-f01b7a8f-f8cc-471e-9930-28436563110d.png">

### Expected Behavior

Labware Name should be in title

### Steps To Reproduce

1. click on the labware to see the labware detail slideout
2. Slideout title should be labware Name

**Comment by y3rsh** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/502770/170505778-5a3018f8-a942-42d4-910e-d05def51a710.png">
