### ISSUE TITLE
6.0 Feedback: badly written protocol will analyze forever

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#10468]
### Overview

If a user inputs a poorly written protocol that goes into an infinite loop (or something similar, like an accidental `time.sleep` for too long), the app's protocol analysis will spin forever.

### Current Behavior

Protocol analysis spins forever in the app. If you quit the app, it doesn't look like there is a phantom process left around or anything particularly bad.

### Expected Behavior

The analysis fails, with some sort of message, e.g.

> The protocol analysis did not complete after {x amount of time}. Please see {some troubleshooting resource}

### Steps To Reproduce

Toy protocol that will hit this bug

```python
from opentrons import protocol_api, types

metadata = {
    "apiLevel": "2.12",
}


def run(ctx: protocol_api.ProtocolContext) -> None:
    while True:
        ...
```

This is a silly example, but in real life, protocols that have to do stuff like talk to external services or load external data that aren't properly guarded with `if not ctx.is_simulating:` are the things that are more likely to trigger this.

### Robot setup or anything else?

This could be handled on the `opentrons.cli` side (e.g. a `--fail-after` argument or similar) or the app side. The most robust solution would probably involve timeout guards on both sides, but that might not be necessary. 

Alternatively, we could also explore the idea of an incomplete analysis. If a protocol analysis times out, we may have still captured the various `load_labware` et. al. commands that are really important for the app. If the analysis could come back as `incomplete` or something with a warning, that could be more helpful than a yes/no timeout.

**Comment by nusrat813** [comment]
@b-cooper thoughts on 2 solutions proposed by Mike

**Comment by nusrat813** [comment]
Design on how missing analysis should be

**Comment by SyntaxColoring** [comment]
Are this and https://github.com/Opentrons/opentrons/issues/6126 duplicates of each other?

**Comment by mikecardarelli** [comment]
Brian is leading towards the incomplete analysis approach

**Comment by mcous** [comment]
Duplicate of #6126
