### ISSUE TITLE
6.0 Feedback:  DB reset not integrated into factory reset in the app

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#10477]
### Overview

If I check everything and factory reset, the DB was not deleted.
<img width="800" alt="image" src="https://user-images.githubusercontent.com/502770/170566101-618ec38f-57da-4f52-8a35-6a0a27f214e7.png">
<img width="800" alt="image" src="https://user-images.githubusercontent.com/502770/170566118-8ca24b6f-dfdc-4b78-8b12-496e6e49b199.png">

### Current Behavior

I believe the capability was just not yet integrated.

### Operating system

Mac

**Comment by koji** [comment]
@y3rsh 

Could you tell me your test environment since actually, the reset function is working on my end?

**Comment by y3rsh** [comment]
@koji 
The data like calibrations is all reset as expected.
This is specifically about the newly persisted in 6.0 data.
The robot now persists protocols, runs, and analyses through reboot.
The clear out that data, Robot Services added #10395 so that the DB is cleared out.

**Comment by koji** [comment]
@y3rsh you mean only runsHistory reset doesn't work? 
If so, the issue will be solved by #10461

**Comment by koji** [comment]
Closed by  #10461

**Comment by nusrat813** [comment]
Verified fix
