### ISSUE TITLE
6.0 Feedback: Show the reason why a robot is unreachable in robot overflow menu

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#10474]
### Overview

in the pre 6.0 app, when a user connects to a robot and it fails, we display a "connection failed" modal and one of the following reasons:

`Your OT-2’s API server is not responding correctly to requests at IP address [IP].`

or

`This OT-2 has been seen recently, but is currently not reachable at IP address [IP].`

![image](https://user-images.githubusercontent.com/4339860/170549960-d1b3d668-8769-43f0-8e19-f331a3566dc6.png)

in the 6.0 world, we don't have a way for a user to connect to 1 robot at a time any more. We should add this messaging (if we have it) to the "Why is my robot not available" modal that is displayed as an overflow menu item on an unavailable robot on the robot landing page. 

see figma for mockups:
https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=1297%3A88551

**Comment by mikecardarelli** [comment]
Won't fix
