### ISSUE TITLE
6.0 Feedback:  Missing Calibration alert still present after finishing calibration

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#10485]
### Overview

Just finished calibrating the highlighted pipette
<img width="800" alt="image" src="https://user-images.githubusercontent.com/502770/170577285-acf04fd4-236b-4ac5-a09a-4f9a1a887b83.png">

**Comment by reachojhaneha** [comment]
I am able to reproduce the issue, looks like refresh issue. After i came to robot settings from device page, calibration details were populated.
![Screen Shot 2022-05-26 at 6 02 41 PM](https://user-images.githubusercontent.com/39049853/170587315-affb0efd-b784-485e-a488-5e3a9fc34aa6.png)
.

**Comment by y3rsh** [comment]
verified fixed.
