### ISSUE TITLE
6.0 Feedback:  <title> Run protocol button still blue when robot is unavailable 

### ISSUE THREAD

**Issue by nusrat813** [Opentrons/opentrons#10487]
### Current Behavior

Robot is unavailable - run protocol button is still displayed as blue (upon clicking nothing happens)
<img width="855" alt="Screen Shot 2022-05-26 at 4 31 52 PM" src="https://user-images.githubusercontent.com/30632549/170578743-420b5d9f-cbd3-45db-9368-2c00bc18d927.png">
<img width="855" alt="Screen Shot 2022-05-26 at 4 32 03 PM" src="https://user-images.githubusercontent.com/30632549/170578747-eb3df605-785c-47d3-96fe-f65fb3958135.png">

### Expected Behavior

Button should be grayed out 

### Operating system

Mac

**Comment by jerader** [comment]
I'm unable to reproduce this on latest edge:

https://user-images.githubusercontent.com/66035149/172452521-50b74795-034b-4b27-89df-8d5d0c176f33.mov

**Comment by vabruzzo** [comment]
i am also unable to reproduce
