### ISSUE TITLE
6.0 Feedback:  "See how robot calibration works" link in robot settings needs resizing

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#10489]
### Overview

 "See how robot calibration works" link in robot settings needs resizing, currently it captures the entire app.

### Current Behavior

![Screen Shot 2022-05-26 at 6 12 16 PM](https://user-images.githubusercontent.com/39049853/170588314-0d6ac7dc-73e5-4c48-a611-ef8d41c4b859.png)

### Expected Behavior

modal needs resizing

### Steps To Reproduce

1. Goto robot settings page
2. Click on "See how robot calibration works" link

**Comment by koji** [comment]
@reachojhaneha 
This is the same as #10406
