### ISSUE TITLE
6.0 Feedback:  App does not display spinner when refresh button in devices tab clicked

### ISSUE THREAD

**Issue by nusrat813** [Opentrons/opentrons#10483]
### Current Behavior

The app does not display a spinner when refresh button to find robots is clicked 

### Expected Behavior

![image](https://user-images.githubusercontent.com/30632549/170573712-a2b971a4-769f-4892-9ba2-792610cf93a6.png)

### Steps To Reproduce

1. Click refresh button
<img width="795" alt="Screen Shot 2022-05-26 at 4 20 35 PM" src="https://user-images.githubusercontent.com/30632549/170573557-aef9c785-bd52-4dce-a975-0710a5d4f1c8.png">
 

2. See no spinner is displayed, blank app 
<img width="794" alt="Screen Shot 2022-05-26 at 4 18 21 PM" src="https://user-images.githubusercontent.com/30632549/170573586-8f37e566-9496-4022-9e78-8adf09bb7e4e.png">
 

### Operating system

Mac

**Comment by nusrat813** [comment]
@b-cooper - PR #10399

**Comment by y3rsh** [comment]
refresh button works but a couple issues on the new view
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/502770/172426613-0cbc562c-f03c-440e-a2c8-c43a4042c43f.png">
