### ISSUE TITLE
6.0 Feedback:  Deck Calibration completed but deck calibrations alert still present

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#10484]
### Overview

Complete deck calibration but alert does not go away.
Must navigate away from the page and back.
<img width="800" alt="image" src="https://user-images.githubusercontent.com/502770/170575118-6a874e47-22e8-4ae3-9dda-869832d22974.png">

### after navigating away and back
<img width="800" alt="image" src="https://user-images.githubusercontent.com/502770/170575032-9821eaac-9a76-4c1b-b0cb-f5c30e453521.png">

### Operating system

Mac

**Comment by reachojhaneha** [comment]
@koji @y3rsh , i faced the same issue. But after returning to robot settings page from other tabs, this message was gone. More like refresh issue

**Comment by koji** [comment]
@reachojhaneha thanks
yup, I just reproduced the issue. I will fix this issue.

**Comment by nusrat813** [comment]
Verified fixed
