### ISSUE TITLE
bug: fixed trash labware details page not linked

### ISSUE THREAD

**Issue by skyewindsor** [Opentrons/opentrons#10492]
# Overview

The link to the labware details page for the Opentrons fixed trash does not work on opentrons.com

# Steps to reproduce

1. Navigate to the fixed trash in the online [labware library](https://labware.opentrons.com/)
2. Click on the hyperlinked blue text "Opentrons Fixed Trash"
3. See the dead page

Here are the relevant dimensions that should show up on the fixed trash details page: 
Well Count

1

MAX VOLUME
3200 mL

Footprint (mm)

LENGTH
210.75

WIDTH
79.75

HEIGHT
93.50

Well Measurements (mm)

DEPTH
187.50

X-SIZE
107.11

Y-SIZE
165.67

Spacing (mm)

X-OFFSET
105.38

Y-OFFSET
39.88

X-SPACING
0.00

Y-SPACING
0.00

# Current behavior

No labware details page shows up when clicking on the opentrons fixed trash in the online labware library.

# Expected behavior

- [ ] All labware details should show up when clicking the fixed trash link

**Comment by mikecardarelli** [comment]
New JIRA ticket: https://opentrons.atlassian.net/browse/RAUT-206
