### ISSUE TITLE
6.0 Feedback:  Clicking robot Settings > Check Health homes the robot gantry but nothing happens in the app

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#10491]
### Overview

<img width="800" alt="image" src="https://user-images.githubusercontent.com/502770/170590311-89f29efa-7114-44d2-a3d6-54e46c8be77a.png">

### Current Behavior

Nothing happens in the app after clicking Device > My robot > Robot Settings 
check health

**Comment by nusrat813** [comment]
Verified fix
