### ISSUE TITLE
6.0 Feedback:  App goes blank while choosing a different tip rack option during tip length calibration

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#10490]
### Overview

https://user-images.githubusercontent.com/39049853/170590280-47b7a93d-9c8a-4238-aeda-b93da5cf05b9.mov

### Current Behavior

<img width="1438" alt="Screen Shot 2022-05-26 at 6 28 24 PM" src="https://user-images.githubusercontent.com/39049853/170589912-73787c76-574c-4813-8a4b-87cb9803571e.png">

There are no network errors

### Expected Behavior

app should not white screen

### Steps To Reproduce

1. Goto devices page
2. click on the robot
3. Goto robot settings
4. Goto Tip length calibrations -> click on the overflow menu
5. click on Recalibrate Tip length and Pipette Offset option
6. Click on "Use a different Tip Rack"
<img width="757" alt="Screen Shot 2022-05-26 at 6 28 03 PM" src="https://user-images.githubusercontent.com/39049853/170589876-94a99250-85f7-47a0-a3e3-d5519fd66f04.png">

**Comment by koji** [comment]
@reachojhaneha 
Could you try this branch `app_fix-different-tiprack-white-screen` for #10490?

**Comment by nusrat813** [comment]
Verified fix
