### ISSUE TITLE
bug: LL aluminum block links not working

### ISSUE THREAD

**Issue by skyewindsor** [Opentrons/opentrons#10494]
# Overview

All aluminum block definitions in the online LL are broken when opening them in a new tab. 

# Steps to reproduce

1. Navigate to any aluminum block definition in the [LL](https://labware.opentrons.com/)
2. Secondary click on the labware name hyperlink and select "open link in a new tab"
3. See the broken page

Here are the definitions affected by this: 
[Opentrons 24 Well Aluminum Block with Generic 2 mL Screwcap](https://labware.opentrons.com/opentrons_24_aluminumblock_generic_2ml_screwcap?category=aluminumBlock)
[Opentrons 24 Well Aluminum Block with NEST 0.5 mL Screwcap](https://labware.opentrons.com/opentrons_24_aluminumblock_nest_0.5ml_screwcap?category=aluminumBlock)
[Opentrons 24 Well Aluminum Block with NEST 1.5 mL Screwcap](https://labware.opentrons.com/opentrons_24_aluminumblock_nest_1.5ml_screwcap?category=aluminumBlock)
[Opentrons 24 Well Aluminum Block with NEST 1.5 mL Snapcap](https://labware.opentrons.com/opentrons_24_aluminumblock_nest_1.5ml_snapcap?category=aluminumBlock)
[Opentrons 24 Well Aluminum Block with NEST 2 mL Screwcap](https://labware.opentrons.com/opentrons_24_aluminumblock_nest_2ml_screwcap?category=aluminumBlock)
[Opentrons 24 Well Aluminum Block with NEST 2 mL Snapcap](https://labware.opentrons.com/opentrons_24_aluminumblock_nest_2ml_snapcap?category=aluminumBlock)
[Opentrons 96 Well Aluminum Block with Bio-Rad Well Plate 200 µL](https://labware.opentrons.com/opentrons_96_aluminumblock_biorad_wellplate_200ul?category=aluminumBlock)
[Opentrons 96 Well Aluminum Block with Generic PCR Strip 200 µL](https://labware.opentrons.com/opentrons_96_aluminumblock_generic_pcr_strip_200ul?category=aluminumBlock)
[Opentrons 96 Well Aluminum Block with NEST Well Plate 100 µL](https://labware.opentrons.com/opentrons_96_aluminumblock_nest_wellplate_100ul?category=aluminumBlock)

# Current behavior

All hyperlinks for the aluminum block definitions are broken when opening them in a new browser tab. 

# Expected behavior

- [ ] The labware details page should get served when a user opens any aluminum block link in a new tab

**Comment by mikecardarelli** [comment]
New JIRA ticket: https://opentrons.atlassian.net/browse/RAUT-205
