### ISSUE TITLE
feat: update opentrons fixed trash svg in LL

### ISSUE THREAD

**Issue by skyewindsor** [Opentrons/opentrons#10496]
# Overview

The Opentrons fixed trash image looks really wonky, so we need a new svg to replace it.
![Screen Shot 2022-05-26 at 3 59 13 PM](https://user-images.githubusercontent.com/95719575/170592885-1e74e16b-b43c-4f2f-aa61-551abf3e934a.png)

# Acceptance criteria

- [ ] The fixed trash image is an accurate representation of what the trash bin looks like
- [ ] The new fixed trash image shows up in the online LL and in the App

**Comment by mikecardarelli** [comment]
New JIRA ticket: https://opentrons.atlassian.net/browse/RAUT-204
