### ISSUE TITLE
Make E/W labware filter mandatory

### ISSUE THREAD

**Issue by anthonywilleee** [Opentrons/opentrons#10508]
# Overview

Filter labware over 53mm in E/W slots. Filter should not have a checkbox (meaning filter is mandatory)

# Implementation Details

- Ensure that there is no checkbox on the on the Add Labware filter for E/W slots
- Match design in Figma

# Design Link

![Screen Shot 2022-05-27 at 12.45.43 PM.png](https://images.zenhubusercontent.com/5f772bd73389cd8dbeb34a48/92a627b6-e38a-4697-8602-cd8a8246b8a9)
- https://www.figma.com/file/695ogls23YsQYImRcGYDE1/Heater-Shaker?node-id=2770%3A88367

# Acceptance Criteria
- No checkbox on Add Labware >53mm filter for E/W slots
- Add labware modal matches design linked in Figma

**Comment by shlokamin** [comment]
de-scoping for now. this will be caught by step generation
