### ISSUE TITLE
6.0 Feedback:  6.0.0-alpha.0 - app settings text is repeated

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#10500]
### Overview

The text is repeated twice on the App Software Version section of App Settings > General

![Screen Shot 2022-05-27 at 8 56 55 AM](https://user-images.githubusercontent.com/4339860/170703813-4c1cd098-cf08-4d63-8ca7-2c0980263481.png)

**Comment by y3rsh** [comment]
verified
