### ISSUE TITLE
6.0 Feedback:  6.0.0-alpha-0 - Robot updated but the app doesn't change

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#10501]
### Overview

I updated the robot and afterwards, the app still said that robot has an update

![Screen Shot 2022-05-27 at 9 12 02 AM](https://user-images.githubusercontent.com/4339860/170706102-135bdada-2f7b-4cbb-a1a6-33b4b70cbfcb.png)
.
![Screen Shot 2022-05-27 at 9 13 13 AM](https://user-images.githubusercontent.com/4339860/170706197-506867bd-d422-4654-9a45-469671c87a90.png)

**Comment by emilywools** [comment]
update: when i left the robot detail page, the app no longer shows that an update is available.

**Comment by emilywools** [comment]
... but the overflow menu still has an item to "Update robot software"
![Screen Shot 2022-05-27 at 9 28 55 AM](https://user-images.githubusercontent.com/4339860/170708934-7ffee29a-262b-43b8-9a93-e56dded4a706.png)

**Comment by ecormany** [comment]
same as #10041. 

good catch on the overflow menu being affected too, though.

**Comment by bndo** [comment]
Closing as duplicate
