### ISSUE TITLE
Robot selection slideout: show a warning if a robot's software needs to be updated

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#10503]
# Overview
It would be nice to see which robots are running software that is mismatched from the current OT app's version when the user is viewing the robot selection slide-out. 

# Design
We can use the same style of warnings that we show when in-app analysis fails:
![Frame 4952.png](https://images.zenhubusercontent.com/5e20a4f595a33208d0d768ab/f1ee89fc-5294-4ac5-9d97-6199c55d9eda)
See the bottom left corner of this frame for the Figma designs: https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=5196%3A190443

# Acceptance Criteria

- [ ] A warning icon is shown if the robot is running a different software version than the app

- [ ] Clicking on the robot card should reveal a warning message about the robot sw being out of sync

- [ ] Clicking on the "Go to Robot" link should proceed the user to the Robot's device details page

- [ ] If an out of date robot is selected, the "Proceed to setup" CTA button should be inactive

**Comment by mikecardarelli** [comment]
Bumping this issue. Seems important based on the external BETA feedback we're receiving

**Comment by b-cooper** [comment]
Closed by #10895

**Comment by nusrat813** [comment]
Verified fixed
