### ISSUE TITLE
6.0 Feedback:  502 bad gateway error after restarting the robot

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#10528]
### Overview

getting 502 bad gate way error
Under robot settings Advanced -> enable option “disable homing the gantry when restarting robot”
From device detail page -> restart the robot(from overflow menu) 

### Current Behavior

<img width="1118" alt="Screen Shot 2022-05-31 at 10 36 30 AM" src="https://user-images.githubusercontent.com/39049853/171199935-2309fb53-ff44-46cf-86c8-b8d2b76bffdf.png">

<img width="1126" alt="Screen Shot 2022-05-31 at 10 36 53 AM" src="https://user-images.githubusercontent.com/39049853/171200021-1fe0955d-9f18-4447-b3bf-34f3566af385.png">

<img width="1131" alt="Screen Shot 2022-05-31 at 10 37 24 AM" src="https://user-images.githubusercontent.com/39049853/171200140-c40956bc-53dd-4609-a584-cc6a6b56a03f.png">

### Steps To Reproduce

1. Under robot settings Advanced -> enable option “disable homing the gantry when restarting robot”
2. From device detail page -> restart the robot(from overflow menu)

**Comment by mcous** [comment]
@reachojhaneha does your robot eventually start responding? The robot's `/health` endpoint is expected to go from `502` to `503` to `200` during startup. If the robot eventually comes up, then this is expected behavior.

I just tried setting the flag on an OT-2R in the office, and the robot responded with 502/3 until the motor control board came up, then switched to 200 as expected

**Comment by reachojhaneha** [comment]
@mcous , after the reset i do see 200 response code and robot eventually comes up. But there is a 403 error code with ping
<img width="1440" alt="Screen Shot 2022-05-31 at 2 40 28 PM" src="https://user-images.githubusercontent.com/39049853/171261569-10a7389b-40f3-42b8-a56e-f54d335c6cca.png">

Response:
-----------

{"type":"error.list","request_id":"00040q2ktl51tao9g8s0","errors":[{"code":"blocked","message":"App suspended"}]}

**Comment by reachojhaneha** [comment]
this is consistent with resetting the robot

**Comment by mcous** [comment]
Closing as expected behavior during robot boot. Opened #10547 to track 403 from Intercom API
