### ISSUE TITLE
Minimap designs for PD H-S 

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#10538]
## Background
Current functionality in PD: When a module has collision warnings in PD, there's a reflection of the problem slots on the mini map on the file page. Hovering on the mini map gives further detail. 

## Acceptance criteria
- [ ] Update the copy for existing Temp/Mag GEN1 <> 8-Channel GEN1 pipettes so that it's reflective of current hardware naming conventions
- [ ] Create a tooltip for H-S warnings

## Figma link
https://www.figma.com/file/695ogls23YsQYImRcGYDE1/Heater-Shaker?node-id=4996%3A94442

**Comment by anthonywilleee** [comment]
@shlokamin Descoping in favor of PD touch ups epic, we can come back to this later
