### ISSUE TITLE
6.0 Feedback:  Tip Length Calibration status does not update after tip length calibration

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#10531]
### Overview

```gherkin
Given I am on setup for run
And I need to complete tip length calibration
When I complete the calibration
And am back on the setup for run page
Then the calibration does not reflect as completed
```  

> You may work around by navigating to devices then back to the run setup but at this is a primary flow this is a critical bug.

### Current Behavior

https://user-images.githubusercontent.com/502770/171204830-ab0f09de-4f60-4803-b1a1-222c93f625ca.mp4

### Expected Behavior

Tip length calibration status updated so I may proceed to labware setup.

### Steps To Reproduce

My example [tiprack_repro.json.zip](https://github.com/Opentrons/opentrons/files/8806283/tiprack_repro.json.zip)
Use a simple protocol with a pipette you have attached but with tiprack that you do **NOT** have calibrated.
 

### Operating system

Mac

**Comment by nusrat813** [comment]
Verified fix
