### ISSUE TITLE
heater-shaker: add command publisher support

### ISSUE THREAD

**Issue by sanni-t** [Opentrons/opentrons#10539]
# Overview

#10426 introduces the heater-shaker context and its methods. We need to be able to show user-friendly descriptions for all the commands in the heater-shaker context. So add the new h/s command types and add them to the command publisher infrastructure. Commands to be supported by the publisher:

- `set_and_wait_for_temperature`
- `set_target_temperature`
- `wait_for_temperature`
- `set_and_wait_for_shake_speed`
- `open_labware_latch`
- `close_labware_latch`
- `deactivate_shaker`
- `deactivate_heater`

# Implementation details

- add the new command types w/ payload to `opentrons/commands/types`
- add the payload texts in `opentrons/commands/module_commands.py`
- add publish decorator to the h/s methods and remove the TODOs

# Acceptance criteria

Commands should show up in the run log as user-friendly text

**Comment by mcous** [comment]
Closed by #10585, which was merged into a feature branch so did not get autoclosed by GH
