### ISSUE TITLE
6.0 Feedback:  Delete protocol run record from overflow menu does not close after protocol is deleted 

### ISSUE THREAD

**Issue by nusrat813** [Opentrons/opentrons#10545]
### Current Behavior

https://user-images.githubusercontent.com/30632549/171259439-f8cb61c8-8c96-4bdb-9273-5ba63993b044.mp4

Overflow menu for the specific run does not close after the run as been completed 

User can just keep clicking to delete runs for other protocols 

### Expected Behavior

Overflow menu should close after run is deleted 

### Operating system

Mac

**Comment by y3rsh** [comment]
I still see dome odd behavior on these menus when I `make -C app dev`
<img width="800" alt="image" src="https://user-images.githubusercontent.com/502770/171884448-05068ab4-3670-47ee-9b94-3aa42644cdfe.png">

**Comment by koji** [comment]
Closed by #10587

**Comment by y3rsh** [comment]
verified fixed
