### ISSUE TITLE
6.0 Feedback:  MultIple kebab menus for protocol runs can be open at the same time causing overlap 

### ISSUE THREAD

**Issue by nusrat813** [Opentrons/opentrons#10548]
### Current Behavior

<img width="794" alt="Screen Shot 2022-05-31 at 2 36 08 PM" src="https://user-images.githubusercontent.com/30632549/171261130-b096a12e-eeb7-4f57-a2a9-693fe44ae617.png">

Multiple kebab menus can be open at once causing a overlap in the menu

### Operating system

Mac

**Comment by koji** [comment]
Closed by #10587
