### ISSUE TITLE
6.0 Feedback:  lookup for IP address of an available robot shows as "not found"

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#10553]
### Overview

Enter the (wifi)IP of a robot which is available, in "connect to a robot via IP address". Adding a valid IP address shows not found. The robot is connected via usb and adding the wifi IP address shows as not found

### Current Behavior

https://user-images.githubusercontent.com/39049853/171274249-e05aa4f4-e664-4b7a-a5e1-4439a41b5260.mov

### Expected Behavior

The wifi IP address should be found

### Steps To Reproduce

1. Connect a device with USB
<img width="808" alt="Screen Shot 2022-05-31 at 3 47 15 PM" src="https://user-images.githubusercontent.com/39049853/171272410-6fbe8212-646d-4aec-a5e4-a23804aad64c.png">

2. Goto robot settings and fetch the wifi IP address -> from robot settings
<img width="816" alt="Screen Shot 2022-05-31 at 3 48 10 PM" src="https://user-images.githubusercontent.com/39049853/171272564-73e2f778-cfb4-4d85-aff6-389cb7713f7f.png">

3. Goto App-settings -> connect to a robot via IP address -> click on set up connection
4. Enter the wifi address -> click on add
<img width="572" alt="Screen Shot 2022-05-31 at 3 54 10 PM" src="https://user-images.githubusercontent.com/39049853/171273601-359fd646-295c-4317-aa68-2ffdf0237cdf.png">

**Comment by nusrat813** [comment]
work around - unplug usb 

Investigate - @b-cooper 

Potential fix - read all UP address from discovered robots to back this view

**Comment by koji** [comment]
This isn't an issue since the case in this ticket is an edge case.
Basically, users use `connect to a robot via IP address` to detect a robot that isn't in Available robots list.
