### ISSUE TITLE
6.0 Feedback:  T1 Protocol Card SVG Fix

### ISSUE THREAD

**Issue by mmencarelli** [Opentrons/opentrons#10555]
### Overview

This is to fix a spacing issue around the SVG on the protocol cards. 

### Current Behavior

[Link to the figma frame ](https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=11331%3A330817)with annotations

[Loom video link](https://www.figma.com/file/2xjSLHXquNsKvC1mV9NMjr/Milestone-2?node-id=955%3A144959) explaining the issue 

- [ ] (13) Think I'll need to work 1-on-1 with a dev to understand what's going on here. Loom video should explain most of it! Just DM me when you start working on this. 

<img width="220" alt="Screen Shot 2022-05-31 at 2 25 22 PM" src="https://user-images.githubusercontent.com/54682054/171287200-7be7c57b-acec-47e1-9046-0bbd1d825c52.png">

**Comment by aptrons22** [comment]
Keeping this issue open until further notice from Mel.  Thanks

**Comment by koji** [comment]
This will solved by #10993
