### ISSUE TITLE
6.0 Feedback:  Upload a protocol that will parse on the app but will not on the robot.

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#10569]
### Overview

Given the attached protocol which has python 3.10 syntax.
We see that it will upload and be analyzed by the application due to the application having bundled python 3.10.
When we proceed to run nothing will happen because the POST to `/protocols` of the protocol returns 422
![image](https://user-images.githubusercontent.com/502770/171471269-09f2ac85-8b26-4e43-a99c-782e46a04f36.png)

### Current Behavior

Robot selection slide out is still present and you can't proceed to run.

### Expected Behavior

Not sure what the design is but if the robot cannot parse the protocol we probably should not run the protocol.

### Steps To Reproduce

Use
[310only.py.zip](https://github.com/Opentrons/opentrons/files/8817804/310only.py.zip)
 

### Operating system

Mac

**Comment by nusrat813** [comment]
Reuse error state in slide out that was previously used for analysIs errors - https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=12587%3A283630

**Comment by bndo** [comment]
Need to surface the caught error

**Comment by b-cooper** [comment]
Acceptance criteria for solving this include:

- [ ] display the inline error message from the protocol record creation error response
- [ ] add a spinner/disable to the "proceed to run" CTA after it has been pressed and any of the subsequent requests are in progress

**Comment by y3rsh** [comment]
![image](https://user-images.githubusercontent.com/502770/176451988-b7597462-b04a-43ce-8161-dcde7da53b8b.png)
