### ISSUE TITLE
6.0 Feedback:  App displays a pipette offset missing when no pipette is in that mount

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#10574]
### Overview

if a user only has 1 pipette attached, the empty mount displays a banner saying the pipette offset calibration is missing. if the mount is empty, nothing is missing. we should remove this banner from empty mounts

![image (1)](https://user-images.githubusercontent.com/4339860/171492047-0406668f-ba71-41a0-862d-540c8d96ddd3.png)

**Comment by y3rsh** [comment]
I can still reproduce this in Alpha1
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/502770/172414325-0f48b940-5cf0-4530-b045-ec06fa55c883.png">

**Comment by y3rsh** [comment]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/502770/173060502-e62bf66e-c798-4ff2-b711-639f00dfb295.png">
