### ISSUE TITLE
6.0 Feedback: Robot usage settings do not show live values until they're modified

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#10577]
### Overview

These switches will sometimes appear off, even if they're actually on.

<img width="800" alt="Screen Shot 2022-06-01 at 4 13 37 PM" src="https://user-images.githubusercontent.com/3236864/171497428-da4083bc-9854-44ce-b376-9c18d98a67fa.png">

### Steps To Reproduce

1. Go to some robot's page. In the **Advanced** tab, under **Usage Settings,** toggle both **Pause protocol when robot door opens** and **Disable homing the gantry when restarting robot** on.
2. Quit and reopen the Opentrons App.
3. Navigate to the same usage settings again.
4. **Observe that both switches will be off.** Expected: both switches should be on, since that's how you left them.
5. Toggle one of the switches on again.
6. **Observe that both of the switches are now on.**
   
   https://user-images.githubusercontent.com/3236864/171498719-0d3ca561-dd03-4e99-aba7-fff0dd61ea75.mov

It's as if the app isn't fetching the current settings upon initial connection, and it takes a modification to force it to refresh.

### Operating system

Mac

### Robot setup or anything else?

Connecting over Wi-Fi.

**Comment by nusrat813** [comment]
Verified fix
