### ISSUE TITLE
6.0 Feedback: Styling is not correct when only 1 pipette is attached to the robot

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#10575]
### Overview

when one pipette is attached to the robot, we should not display an empty line item. we should only display 1 row in the table

![image (1)](https://user-images.githubusercontent.com/4339860/171492865-2b1f9a8b-e2b2-43a2-a42f-4248f3c65bb6.png)

See figma: https://www.figma.com/file/l7BAJAGICr10ELsSqQD0Sr/Design-System?node-id=2383%3A88338

**Comment by koji** [comment]
This is solved by  #10657
