### ISSUE TITLE
6.0 Feedback:  software updates still shown after disabling software updates settings

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#10576]
### Overview

disable the software update alert (general app settings)-> then change the update channel to stable(advance app settings). Even though the alert is turned off, i am seeing the software update pop-up appearing

### Current Behavior

<img width="1435" alt="Screen Shot 2022-06-01 at 4 14 35 PM" src="https://user-images.githubusercontent.com/39049853/171493347-62bd23d1-f899-4aad-9e66-a4c1c267355e.png">

There is a success banner
software update modal

### Steps To Reproduce

disable the software update alert (general app settings)-> then change the update channel to stable(advance app settings).

**Comment by bndo** [comment]
Closed via #10732
