### ISSUE TITLE
Add 6 new standard definitions to the Labware Library

### ISSUE THREAD

**Issue by skyewindsor** [Opentrons/opentrons#10578]
# Overview

6 new standard definitions should be added to the Labware Library that are commonly exported from the Labware Creator.

# Implementation details

Note that all new additions to the LL will require a post-5.0 compatibility banner as outlined in [this ticket](https://app.zenhub.com/workspaces/app--ui-5f6248dba845b000139aa767/issues/opentrons/opentrons/9575). 

1) Analytical Sales and Services 24 Well Reservoir 3250uL ([labware defintion](https://drive.google.com/drive/u/1/folders/1wzmH8H-XM4LzUvtNlqjfjUl9-IetCaQo) / [image](https://www.analytical-sales.com/wp-content/uploads/2019/10/24296.jpg) / [website link](https://www.analytical-sales.com/product/clear-pp-reservoir-24-well-low-profile-pyramid-bottom-24296/))
2) Axygen 12 Well Reservoir 1750uL ([labware defintion](https://drive.google.com/drive/u/1/folders/1NI4sgAR_7L9dKPgXV4gPvE6taXTPKIcm) / [image](https://www.fisherbiotec.com.au/wp-content/uploads/2019/01/Axygen-Reservoirs-multi-02-21Jan19.jpg) / [website link](https://ecatalog.corning.com/life-sciences/b2c/US/en/Genomics-%26-Molecular-Biology/Automation-Consumables/Automation-Reservoirs/Axygen%C2%AE-Reagent-Reservoirs/p/axygenReagentReservoirs))
3) Thermo Scientific Abgene 96 Well Plate 200uL ([labware defintion](https://drive.google.com/drive/u/1/folders/1Fdc7IpBC3Ai8_veHOWGC4d83CrGMqJcX) / [image](https://assets.thermofisher.com/TFS-Assets/CCG/Thermo-Scientific/product-images/21-2093095-AB0800-STD-00.jpg-650.jpg) / [website link](https://www.thermofisher.com/order/catalog/product/AB0800?SID=srch-srp-AB0800))
4) Thermo Scientific Abgene 96 Deep Well Plate 0.8mL ([labware defintion](https://drive.google.com/drive/u/1/folders/1LM9S-odJglgPyoqtY6VzQyceRcXfqH04) / [image](https://assets.thermofisher.com/TFS-Assets/CCG/Thermo-Scientific/product-images/22-3950896-3772488-FAM-00.jpg-650.jpg) / [website link](https://www.thermofisher.com/order/catalog/product/AB0765?SID=srch-srp-AB0765))
5) Thermo Scientific 384 Well Plate 40 uL ([labware defintion](https://drive.google.com/drive/u/1/folders/14dqjfTcT0VgJcv48jKtjAnQ96K1EFFhB) / [image](https://drive.google.com/drive/u/1/folders/16T0T0DyJ3ry39vb-2OePD-kubKmCVKAU) / [website link](https://www.thermofisher.com/order/catalog/product/AB1384))
6) Thermo Scientific 96 Deep Well Plate 1.2mL ([labware defintion](https://drive.google.com/drive/u/1/folders/1dhQctXo_yR-U7ccJUNCkKalTviPSxYB8) / [image](https://assets.thermofisher.cn/TFS-Assets/CCG/Thermo-Scientific/product-images/22-3950905-AB1127-STD-00.jpg-650.jpg) / [website link](https://www.thermofisher.cn/order/catalog/product/AB1127?SID=srch-hj-AB1127))

# Acceptance criteria

All 6 new definitions render correctly in the Labware Library

- [ ] Analytical Sales and Services 24 Well Reservoir 3250uL
- [ ] Axygen 12 Well Reservoir 1750uL 
- [ ] Thermo Scientific Abgene 96 Well Plate 200uL
- [ ] Thermo Scientific Abgene 96 Deep Well Plate 0.8mL
- [ ] Thermo Scientific 384 Well Plate 40 uL
- [ ] Thermo Scientific 96 Deep Well Plate 1.2mL 
- [ ] All new additions have the post-5.0 compatibility banner

**Comment by mikecardarelli** [comment]
New JIRA ticket lives here: https://opentrons.atlassian.net/browse/RLAB-108
