### ISSUE TITLE
6.0 Feedback:  Disconnecting robot when on a protocol run page leaves the page in awkward state

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#10584]
### Given I am on a run page/setup for run of a protocol
<img width="824" alt="image" src="https://user-images.githubusercontent.com/502770/171644999-a983716a-655e-416a-98da-c8a7e52b26f5.png">

### When I power off/disconnect the robot the page then changes to this state.
<img width="824" alt="image" src="https://user-images.githubusercontent.com/502770/171645042-57fb1aa7-4e33-4d0b-b09e-523e2cd41430.png">

### Expected Behavior

More clearly indicate the robot for this run is disconnected?

**Comment by nusrat813** [comment]
Verified fixed
