### ISSUE TITLE
6.0 Feedback:  conditional rendering of text in the slideout based on network discovery

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#10594]
### Overview

If the discovery was successful -> app displays refresh above the list of networks
If the discovery was unsuccessful -> app displays "Discovery timed out. Try again"

### Current Behavior

<img width="376" alt="Screen Shot 2022-06-02 at 3 02 55 PM" src="https://user-images.githubusercontent.com/39049853/171715347-fd836555-028a-43ac-a382-6db37482ff25.png">

All the time "Discovery timed out. Try again" -> is displayed

### Expected Behavior

![Screen Shot 2022-06-02 at 3 03 48 PM](https://user-images.githubusercontent.com/39049853/171716290-1b136b16-f8d1-4897-a87a-f83c6abd58bc.png)

### Steps To Reproduce

1. Goto app settings ->  on the connect to robot via IP address -> click on setup connection button
2. Enter the IP address and  click add -> if the Ip address is found "Refresh" button alone should be displayed
3. Again Enter the IP address and  click add -> if the Ip address is not found then "Discovery Timed Out. Try again" text should be found

**Comment by bndo** [comment]
Closed via #10784

**Comment by y3rsh** [comment]
verified
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/502770/176683663-ef640049-3206-4e61-adac-016b097b1763.png">
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/502770/176683687-838dd086-cb41-489b-b059-61ec00e93f0b.png">
