### ISSUE TITLE
bug: Clicking 'proceed to setup' on 'choose a protocol to run' slideout leads nowhere

### ISSUE THREAD

**Issue by mmencarelli** [Opentrons/opentrons#10616]
# Overview

This issue might be a two-parter: 
(1) I was able to upload a .png file as a protocol
(2) I was able to select this .png on the "choose a protocol to run". When clicking "proceed to setup" nothing happens. 

# Steps to reproduce

[Loom video](https://www.loom.com/share/7b64f63537ab4ae083cb4c003e053253)

# Expected behavior

1. I don't know if we have rules in places for this, but ideally we're only upload .py or .json files into the protocol page
2. Expecting the slideout to close and an error toast to appear explaining the issue when I tried to run the .png file

**Comment by koji** [comment]
- [ ] add file ext check
- [ ] show an error message
