### ISSUE TITLE
6.0 Feedback:  Slide-outs

### ISSUE THREAD

**Issue by mmencarelli** [Opentrons/opentrons#10618]
### Current Behavior

Link to [annotated frame in Figma ](https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=13793%3A416275)

### **Import custom labware def + toast**
- [x] (1) Size of this button should be 24px (currently 20px)
- [ ] (2) remove the box-shadow
- [ ] (3) Going to sneak this toast edit in here for simplicity sake, but can we add a max-width of these toasts to like 70% of the viewport? This percentage should also work when we shrink down to our min-width size 
- [ ] (4) Can we make it a rule that the toasts stay for 8s instead of 4? Noticing that it's a bit quick. 
- [ ] (5) Could we have the toast fade in and out like[ this example? ](https://polaris.shopify.com/components/feedback-indicators/toast#navigation)
- [ ] (6) Center this text
- [ ] (7) needs 2rem margin-top

<img width="291" alt="Screen Shot 2022-06-03 at 10 12 25 AM" src="https://user-images.githubusercontent.com/54682054/171913280-77901ddc-205b-48be-970e-80f63dc4f253.png">
<img width="862" alt="Screen Shot 2022-06-03 at 10 07 04 AM" src="https://user-images.githubusercontent.com/54682054/171912548-27c5c0ee-1ff9-4a42-9ed8-99128ae1f8cb.png">

### **Import a protocol slideout, round 2**
- [ ] (1)  center this text
- [ ] (2) remove box-shadow
- [x] (3) Update the size from 20px to 24px 

### **Choose a protocol to run slideout**
- [ ] (1) All links should be our opentrons blue! 
- [ ] (2) Update size of button to 24px, currently 20px
- [ ] (3) Can we add a white background to the SVG? 
- [ ] (4) Have a set-width for the SVG of 76x68px 
- [ ] (5) Noticed that when I hover over a mini card, the cursor doesn't change to the hand vs the mouse? Linking still works, but the cursor doesn't change. 
- [ ] (6) Remove box shadow from .guMWjt

Unfortunately cannot test out the two warning states we have for the mini cards. If possible, would the dev that picks this up be able to send me screenshots? 

<img width="353" alt="Screen Shot 2022-06-03 at 11 51 19 AM" src="https://user-images.githubusercontent.com/54682054/171929432-6d9a0443-4870-4c74-9c21-bdaa6acebbd2.png">
<img width="349" alt="Screen Shot 2022-06-03 at 11 51 23 AM" src="https://user-images.githubusercontent.com/54682054/171929440-dc60dbca-c0ec-4db4-9554-4d5733e3a5cb.png">
<img width="334" alt="Screen Shot 2022-06-03 at 11 51 44 AM" src="https://user-images.githubusercontent.com/54682054/171929447-9c27be1d-673c-437d-ba9e-c732b26d1a3b.png">
<img width="347" alt="Screen Shot 2022-06-03 at 11 51 47 AM" src="https://user-images.githubusercontent.com/54682054/171929451-0eae748c-67f9-4994-8c70-e921a9bb1ea8.png">

### **Choose a robot to run slideout**

- [ ] (1) Add a margin-right: .5rem to the `Slideout_title_Choose` 
- [x] (2) Make the icon 24px vs 20px 
- [ ] (3) Got an extra 8px margin top above "refresh list". Should be 16px total between the line above and refresh list
- [ ] (4) Missing hover state for the "refresh list" link. Could we change this text to "refresh"? 
- [ ] (5) Robot image should be a fixed width of 64x57px 
- [ ] (6) Technically this content should be vertically centered within the container. So should be down a bit more 
- [ ] (7) Remove `background-color: #f8f8f8;` from the hover state
- [ ] (8) Also missing the cursor change to the hand signifying a clickable item when hovering over this card 
- [ ] (9) Are we nixing this content? if so, let me know so I can update the designs. 
- [ ] (10) Remove box shadow from this button
- [ ] (11) Made a pitch to add a countdown timer when the user clicks "refresh". To the left of the screenshot in figma you'll see the designs 
- [ ] (12) Make the icon bigger, should be 20x20px and should be _darkGreyEnabled_
- [ ] (13) If the discovery times out, then the copy changes to "try again". [Check out the designs on Figma.](https://www.figma.com/file/2xjSLHXquNsKvC1mV9NMjr/Milestone-2?node-id=394%3A115065)

<img width="617" alt="Screen Shot 2022-06-03 at 12 11 44 PM" src="https://user-images.githubusercontent.com/54682054/171932945-acfb8637-9ee0-40dc-8ed9-9da91d7b0b20.png">
<img width="575" alt="Screen Shot 2022-06-03 at 12 11 49 PM" src="https://user-images.githubusercontent.com/54682054/171932958-a2350248-6711-41f4-a170-71c5e18ec80f.png">
<img width="321" alt="Screen Shot 2022-06-03 at 12 11 54 PM" src="https://user-images.githubusercontent.com/54682054/171932965-0f0ff2df-69e0-41e4-ab9f-e487b599d7fb.png">

### **manually add a robot via IP address slideout**
Full functionality download found on [Figma](https://www.figma.com/file/2xjSLHXquNsKvC1mV9NMjr/Milestone-2?node-id=89%3A57224). 

- [x] (1) Update icon to 24px 
- [x] (2) Icon should be fixed to the end of the entire link, vs placed to the right in the same container 
- [x] (3) Update to be our _label/semibold_ font styling
- [ ] (4) Update this component to our _input/field-with-label_ component. So the height changes to 32px, there's a border-radius, and the states are different. 
- [x] (5) **Functionality feedback** Upon opening the slideout, the discovery should kick off. Currently does not. 
- [ ] (6) **Functionality feedback** Available robots should automatically float to the top of the list. The order of this last is by last added.
- [x] (7) Need 8px margin top and bottom on the line 
- [x] (8) Bump up the type size in this to reflect the label styling 
- [x] (9) Add in the states to the the _btn-icon/close_
- [x] (10) Remove the box-shadow from this button 
- [x] (11) Up the size of the error message, should be 11px 
- [x] (12) 4px margin between input field and the error label

<img width="543" alt="Screen Shot 2022-06-03 at 12 42 54 PM" src="https://user-images.githubusercontent.com/54682054/171938789-60970f08-fe91-4224-93e9-9fcd118d52f1.png">

### **Rename robot slideout**

- [x] (1) Update icon to 24px 
- [ ] (2) Did we change this copy? if so, let me know and I can update design. 
- [ ] (3) Add a margin of 4px between "35 character max" and error message
- [ ] (4) Remove our box-shadow from the button

<img width="297" alt="Screen Shot 2022-06-03 at 12 52 21 PM" src="https://user-images.githubusercontent.com/54682054/171940550-1f32cd70-d856-43f7-9ef8-3a316ef4659d.png">

### **Factory reset slideout** 

- [x] (1) Update icon size to 24px 
- [ ] (2) Should be our _toast-basic_ style unless something has changed? 
- [x] (3) Add 8px margin between each row 
- [x] (4) Update the checkbox component to the new component style 
- [x] (5) Update the colour to _darkBlack_
- [ ] (6) Remove box shadow 
<img width="278" alt="Screen Shot 2022-06-03 at 12 56 58 PM" src="https://user-images.githubusercontent.com/54682054/171941303-bd521369-be0e-40f7-bb32-54b62f2bad4b.png">

### **Labware definition slideout**

- [x] (1) Missing the states for the 'x' button
- [ ] (2) I'm not 100% sure this is the updated version of this icon? Also, can we center it vertically with the text? Icon should be down a few pixels 
- [x] (3) Up the size of the icon to 16x16px, currently at 10x10 
- [x] (4) Add 8px margin between each line
- [x] (5) Update font colour to _darkGreyEnabled_

<img width="282" alt="Screen Shot 2022-06-03 at 1 03 54 PM" src="https://user-images.githubusercontent.com/54682054/171942486-448c87e8-c412-4ab4-8cff-18e5e175e2ca.png">

**Comment by koji** [comment]
Working on Connect to a robot via IP slideout

**Comment by koji** [comment]
Probably I will open PRs separately since that way would make code review easier.

**Comment by koji** [comment]
- [ ] Import custom labware def + toast
- [ ] Import a protocol slideout, round 2
- [ ] Choose a protocol to run slideout
- [ ] Choose a robot to run slideout
- [ ] manually add a robot via IP address slideout
- [ ] Rename robot slideout
- [ ] Factory reset slideout
- [ ] Labware definition slideout
