### ISSUE TITLE
6.0 Feedback: [Design QA] T1 Device Landing Page

### ISSUE THREAD

**Issue by mmencarelli** [Opentrons/opentrons#10611]
### Current Behavior

Link to [annotated frame in Figma ](https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=13793%3A274729)

- [x] (1) Because we don't have a button in the top right of the `DevicesLanding_title` the height of the container is a bit less tall. Needs to match the other pages at a height of 36px. 
- [x] (2) Missing states on this _styling/link/secondary/grey/internal_
- [x] (3) Missing states on _btn-icon/accordion_
- [x] (4) Missing states on the _card/medium/robot_
- [x] (5) Needs to be set widths for these columns so if a pipette is empty, the columns still align across all cards 
- [x] (6) Needs a bit more spacing on these icons. I have 0.25rem between them 
- [x] (7) Needs to be `darkGreyEnabled` when enabled, and then `darkBlackEnabled` when on hover + tooltip
- [x] (8) Needs .25rem margin between header and copy across all these columns
- [x] (9) There's a margin of 8px above this button, needs to be 4px on top and 4px to the right 
- [x] (10) When I click on the button the focus state appears, but that should only appear when the user is physically tabbing through the links. The active state is displayed to the left (viewable in the figma frame) and does not include the orange outline. 
- [x] (11) Placement of the dropdown is off, needs to be directly below the button with .25rem margin between. 
- [x] (12) Should be our stroke version of the tertiary button, also remove the box-shadow! 
- [x] (13) _RobotStatusBanner_opentrons-dev_goToRun_ should be at the top of the container, currently centered within

<img width="831" alt="Screen Shot 2022-06-03 at 11 01 25 AM" src="https://user-images.githubusercontent.com/54682054/171920757-8c8f75d5-887a-4cce-9335-daa4cd141c14.png">

<img width="845" alt="Screen Shot 2022-06-03 at 9 37 40 AM" src="https://user-images.githubusercontent.com/54682054/171908184-0cb7a534-98fd-4149-b321-158b382e0d79.png">

<img width="257" alt="Screen Shot 2022-06-03 at 9 37 19 AM" src="https://user-images.githubusercontent.com/54682054/171908199-e64c31b6-a37f-497b-9339-7dfccfc85807.png">

**Comment by bndo** [comment]
removed ^ label because ~90% of these changes have been merged, the others have separate issues (#10886 for number 5.)
