### ISSUE TITLE
6.0 Feedback:  Override Path to Python add copy to indicate restart required

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#10612]
### Overview

While investigating #10607 
@mcous noted 
- App must be restarted for change to take effect, but UI does not state this
- App's file picker uses an `<input>` element and `<button>` element; the semantically correct (and easier) solution is to use `<label>` styled like a button wrapping an `<input`>` so you don't have to do `onClick` trickery

> I think the first item to add copy indicating app restart is required is essential and should be a quick fix.

**Comment by b-cooper** [comment]
Instead of changing the copy to require restarting the app. Let's update this config so that a restart is not required.  

This can be done by using the `handleConfigChange` to listen for changes to the `config.python.pathToPythonOverride`
