### ISSUE TITLE
Sync color const with Design System Colours

### ISSUE THREAD

**Issue by koji** [Opentrons/opentrons#10633]
Sync colors
https://www.figma.com/file/l7BAJAGICr10ELsSqQD0Sr?node-id=1780:90941#206886155

**Comment by koji** [comment]
- [ ] fundamentals
  - [ ] white
  - [ ] background
  - [ ] backgroundShade
  - [ ] lightBlue
  - [ ] medBlue
  - [ ] focus
 
- [ ] blue
  - [ ] blueEnabled
  - [ ] blueHover
  - [ ] bluePressed
  - [ ] blueSelected (missing on Figma)  


- [ ] darkBlack
  - [ ] darkBlackEnabled
  - [ ] darkBlackHover
  - [ ] darkBlackPressed   (missing on Figma)  
  - [ ] darkBlackSelected
  - [ ] darkBlackLight


- [ ] yellow
  - [ ] dandelionYellowEnabled
  - [ ] dandelionYellowHover
  - [ ] dandelionYellowPressed
  - [ ] dandelionYellowSelected (missing on Figma)  


- [ ] grey
  - [ ] lightGreyEnabled
  - [ ] lightGreyHover
  - [ ] medGreyEnabled
  - [ ] medGreyHover
  - [ ] medGreyPressed
  - [ ] medGreySelected
  - [ ] darkGreyHover
  - [ ] darkGreyPressed
  - [ ] darkGreyDisabled 
 

- [ ] success
  - [ ] successBackground
  - [ ] successEnabled
  - [ ] successHover
  - [ ] successText (missing on Figma)
  - [ ] successDisabled


- [ ] warning
  - [ ] warningBackground
  - [ ] warningEnabled
  - [ ] warningHover
  - [ ] warningText (missing on Figma)
  - [ ] warningDisabled

   
- [ ] error
  - [ ] errorBackground
  - [ ] errorEnabled
  - [ ] errorHover
  - [ ] errorText
  - [ ] errorDisabled

**Comment by koji** [comment]
Need?
`export const blueFocus = '#deecff'`

**Comment by koji** [comment]
- [ ] StyledText p color={COLOR.darkBlackEnabled} remove `color`

**Comment by mmencarelli** [comment]
- focus is in Figma 
- no blueSelected
- we have darkBlackHover
- there is no darkBlackSelected
- we have darkBlackLight
- no dandelionYellowSelected
- we have  lightGreyEnabled and  lightGreyHover
- we have medGreyEnabled
- medGreyPressed and medGreySelected are there and they are the same
-  darkGreyPressed and darkGreyDisabled are there
- successText replaces successHover (was mislabeled)
- warningText replaces warningHover (was mislabeled
- successHover and warningHover get nixed
-

**Comment by mmencarelli** [comment]
Also, can we add all the liquid colours? 
<img width="441" alt="Screen Shot 2022-06-07 at 9 47 07 AM" src="https://user-images.githubusercontent.com/54682054/172437933-4c4e627e-bd3d-4f7e-835e-107ecd25511d.png">

**Comment by koji** [comment]
@mmencarelli 
Is it possible to change the name like liquid/blue liquid/orange etc?

I feel using numbers for color names doesn't make code readable.

@sakibh  @smb2268 
Do you have any suggestions on this?

**Comment by koji** [comment]
@mmencarelli added colors to `colors.ts`
