### ISSUE TITLE
6.0 Feedback:  [Design QA] Modal Dialogs #10167

### ISSUE THREAD

**Issue by mmencarelli** [Opentrons/opentrons#10631]
### Overview

This is first round design QA on all the modals in our app. 

### Current Behavior

[Link to view the annotated frame in Figma. ](https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=13869%3A276334)

**Why is this not available modal**
- [x] (1) Needs 1.5 rem margin beneath the button. Also remove the box shadow. 
<img width="418" alt="Screen Shot 2022-06-06 at 12 19 40 PM" src="https://user-images.githubusercontent.com/54682054/172231828-e7de2ca2-a724-425a-a32f-1eeb6c9ca4a0.png">

**How to set up a new robot**
- [x] (1) Remove the box-shadow from the button
- [x] (2) Needs 1.5 rem margin beneath the button. Also remove the box shadow

<img width="398" alt="Screen Shot 2022-06-06 at 10 58 56 AM" src="https://user-images.githubusercontent.com/54682054/172218338-49038d64-24c4-4891-9d32-7b7eb01e9340.png">

**Delete this labware definition**
- [x] (1) Hasn't been implemented yet (including the background overlay update)
<img width="513" alt="Screen Shot 2022-06-06 at 12 22 15 PM" src="https://user-images.githubusercontent.com/54682054/172232201-b0532382-e4f8-4c30-bacf-e05bdbbadb1a.png">

**Factory settings modal**
- [x] (1) When this modal appears the breadcrumbs still appear above the background overlay
- [x] (2) Add a spacing of 1.5 rem between the 'cancel' and the button
- [x] (3) Have we updated the text here? Let me know and I'll update the designs 
- [x] (4) Hover state for this error version of the button isn't linked up! On hover it turns blue. Also remove the box shadow
- [x] (5) I have a sneaky feeling these toast icons haven't been updated 

<img width="653" alt="Screen Shot 2022-06-06 at 4 28 23 PM" src="https://user-images.githubusercontent.com/54682054/172265622-fc83366b-8274-4976-9dab-c1df793da5e5.png">

**Software Update Modal**
Don't know if this one has been updated?
<img width="1322" alt="Screen Shot 2022-06-06 at 4 29 23 PM" src="https://user-images.githubusercontent.com/54682054/172265700-7fa2c81a-789d-4d3f-9601-474b408b1e86.png">
 

**How to restore to a previous software version modal**

- [x] (1) Needs 1.5 rem margin beneath the button
- [x] (2) Adjust the margins between the text to be .5rem (8px)
- [x] (3) Remove box shadow from button

<img width="570" alt="Screen Shot 2022-06-06 at 4 33 15 PM" src="https://user-images.githubusercontent.com/54682054/172266000-70db853a-25a3-4a14-ad71-6f302d0d6b18.png">

**Comment by bndo** [comment]
Closed by #10762
