### ISSUE TITLE
bug: Factory-resetting deck calibration leaves behind legacy calibrations from before v4.0

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#10654]
# Overview

When you clear an OT-2's deck calibrations, it appears to leave behind any calibration files that were created in robot software versions prior to v4.0. (v4.0 overhauled the way that robot calibration works.) This causes a confusing user experience because the app will show the robot as having a deck calibration no matter how many times you factory-reset it.
 
In other words, it seems like our code for getting the current deck calibration is smart enough to find these legacy files, but our code for factory-resetting deck calibrations isn't.

# Steps to reproduce

1. Start with a robot that has deck calibrations created under a robot software version prior to v4. You can check this by SSHing in and looking for files like `/data/deck_calibration*.json`. (I'm working from memory, so I might have the exact filename pattern wrong.) If they exist, those are from prior to v4.
2. Find the **Factory Reset** menu in the Opentrons App.
3. Select **Clear Deck Calibration**.
4. Select **Clear data and restart robot.**
5. Reconnect to the robot and go to its page.

# Current behavior

* On the robot's filesystem, and in the robot's HTTP API, the factory reset does not clear the deck calibrations from prior to v4.
* The Opentrons App sees that there is still a deck calibration and does not prompt you to calibrate the deck before using the robot.

# Expected behavior

After the factory reset and reboot, the Opentrons App should prompt you to calibrate the deck.

So, either:

* The Opentrons App should specially treat a robot that has a legacy deck calibration as having no deck calibration, for the purposes of prompting users to calibrate the deck. It can detect this by looking for `"source": "legacy"` in `GET /calibration/status`.
* The factory reset should clear all deck calibrations, including those prior to v4.0.

**Comment by mcous** [comment]
Closed by #10656
