### ISSUE TITLE
6.0 Feedback: device detail page loading process

### ISSUE THREAD

**Issue by ecormany** [Opentrons/opentrons#10658]
### Overview

Much of the information on the device detail page changes as it is loaded for the first time (or when reloading the page). It flashes warnings that can be distracting or concerning to users. Some information remains inaccurate even after everything is loaded.

### Current Behavior

These sections show incorrect information as they load:

1. Pipettes
     - [ ] Pipette images do not show initially (going be addressed in a follow up ticket: https://github.com/Opentrons/opentrons/issues/10847) 
     - [x] "Pipette Offset calibration missing. Calibrate deck first." warning shows very briefly
     - [x] "Pipette Offset calibration needed. Calibrate now" shows slightly longer
2. Protocol runs
    - [x] Entries in the Protocol column initially appear as hex identifiers, and only later update to display names.

These sections show incorrect information even after load:
- [ ] Protocol run status shows as "Canceled" for all runs prior to 6.0.0-alpha1
- [ ] Protocol run duration shows as time between protocol timestamp and present time, instead of between protocol start and end (this will be addressed in this ticket: https://github.com/Opentrons/opentrons/issues/10738) 

https://user-images.githubusercontent.com/1958332/172464999-46c2bf77-3cd4-4817-86d1-04f94f5a19d5.mov

### Expected Behavior

- Pipette images should display at same time as pipette names
- Pipette warnings should never show in a state when they are not needed
- Protocol hex identifiers should never be shown instead of names
- Run durations should be accurate

### Steps To Reproduce

Connect to a robot and navigate to its page under Devices. The above behavior happens on first load or when manually triggering a reload from the View menu.

### Operating system

Mac

**Comment by jerader** [comment]
Pipette images do not show initially will be addressed in a follow up ticket: https://github.com/Opentrons/opentrons/issues/10847

**Comment by jerader** [comment]
Protocol run duration shows as time between protocol timestamp and present time, instead of between protocol start and end will be addressed in this ticket: https://github.com/Opentrons/opentrons/issues/10738)

**Comment by bndo** [comment]
Closed by #10848

**Comment by y3rsh** [comment]
I have not seen any of the warning banner behavior described but I still see the id taking some seconds to be replaced with the user friendly name.
https://user-images.githubusercontent.com/502770/176688098-50d9a79f-ef87-4d4b-8572-f4d700812208.mp4

**Comment by nusrat813** [comment]
Verified fixed
