### ISSUE TITLE
Jupyter Broken

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1066]
Unable to load Jupyter notebook with latest robot build. 

## Expected Behavior
Able to open Jupyter notebook

## Observed Behavior
Jupyter notebook will not load, w/error message "this site can’t be reached".

See below the error message from Resin:
![image](https://user-images.githubusercontent.com/31892318/37851884-e9c6d2bc-2eb6-11e8-8c64-bf4ea6853f10.png)
- The library pyzmq version did not get updated correctly to match the newly updated tornado dependency. See https://github.com/jupyter/notebook/issues/3407

## Steps to Reproduce
Connect to any productionbot on commit ebe78a5
Attempt to load jupyter notebook 
Observe notebook fails to load with error message "this site can’t be reached"

reported by Kinnari

**Comment by umbhau** [comment]
@btmorr @Laura-Danielle 

Sounds like you observed this first-hand -- do you have enough details to work on this, or can I help with investigation?

**Comment by btmorr** [comment]
This is not related to Jupyter--it happens when install fails in a curious manner where the transferred files exist but are empty. I've only observed this happening once, and we have other features in progress to protect against it, but I don't think this ticket has any specific action to be taken.
