### ISSUE TITLE
6.0 Feedback:  Device pipettes, deck calibration and health check is disabled until a protocol is uploaded after software upgrade

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#10676]
### Overview

Functionalities are disabled on robot settings page
- this behavior can be reproduced in robot-server too

### Current Behavior

https://user-images.githubusercontent.com/39049853/172681301-b3b48fc4-499b-497a-ae51-9fa29d5e564e.mov

<img width="1021" alt="Screen Shot 2022-06-08 at 1 46 50 PM" src="https://user-images.githubusercontent.com/39049853/172683276-61a57416-f56a-444d-b9db-467d09e7d608.png">

<img width="1018" alt="Screen Shot 2022-06-08 at 1 47 11 PM" src="https://user-images.githubusercontent.com/39049853/172683327-987ac71e-f96f-4c98-96cd-575eb43332bd.png">

### Steps To Reproduce

1. Perform software update on app and robot to 6.0.0-alpha-1
2. Now from devices page or device detail page -> click on robot settings
3. I notice that Device pipettes are disabled , even if robot has pipettes page shows no pipettes
4. deck calibration is disabled
5. and health check is disabled
6. After the protocol is uploaded to the device -> from device page to go robot settings page 
7. All the above functionalities are enabled and reflected correctly

**Comment by y3rsh** [comment]
verified fixed.
