### ISSUE TITLE
6.0 Feedback:  Software upgrade is available is displayed for unavailable robots

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#10670]
### Overview

Software upgrade banner is displayed for unavailable robots

### Current Behavior

![Screen Shot 2022-06-08 at 11 53 15 AM](https://user-images.githubusercontent.com/39049853/172662044-6a0c3cae-da59-43fc-8e49-81772af333fa.png)

### Expected Behavior

upgrade banner should not be available

### Steps To Reproduce

1. Robot server is not running
2. it is displayed in the Unavailable robot section, with the software update is available banner
3. Similar behavior is seen with robot OT2 where the app goes unavailable after the upgrade, and OT2 appears in the unavailable section - still displaying the software upgrade banner
![Screen Shot 2022-06-08 at 10 26 12 AM](https://user-images.githubusercontent.com/39049853/172662964-8eea59bb-7b41-4066-b3eb-860a83c4e61f.png)

**Comment by y3rsh** [comment]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/502770/173056864-13a861c5-fde3-4434-8cf9-150e92201324.png">
Then turned off the robot
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/502770/173056936-368c1c18-1128-428f-b5a7-672dc573e23d.png">
