### ISSUE TITLE
Protocol Details Page: deck map expanded view modal

### ISSUE THREAD

**Issue by skyewindsor** [Opentrons/opentrons#10691]
# Overview

Users will be able to view an expanded deck map modal when the expand icon is pressed on the [protocol details page](https://www.figma.com/file/2xjSLHXquNsKvC1mV9NMjr/Milestone-2?node-id=1029%3A138252).

# Implementation details

This modal appears when the user clicks the “expand” icon on the sticky view component on the T2 protocol page. 

# Design

https://www.figma.com/file/2xjSLHXquNsKvC1mV9NMjr/Milestone-2?node-id=1036%3A138926

# Acceptance criteria

- [ ] Modal appears when the user clicks the “expand” icon on the sticky view component on the T2 protocol page
- [ ] User sees a static image of the deck map in the modal
- [ ] Clicking 'x' or anywhere outside the modal closes it

**Comment by koji** [comment]
This functionality has been implemented
