### ISSUE TITLE
bug: labware creator test pipettes list P1000 Multis

### ISSUE THREAD

**Issue by skyewindsor** [Opentrons/opentrons#10692]
# Overview

The Labware Test Protocol section of Labware Creator currently lists GEN1 and GEN2 P1000 multichannel pipettes as options in the drop down list.

# Steps to reproduce

1. Load this existing [labware definitio](https://drive.google.com/drive/u/1/folders/14dqjfTcT0VgJcv48jKtjAnQ96K1EFFhB)n into LC
2. Scroll to the labware test section and click the pipette dropdown

# Current behavior

LC shows GEN1 P1000 Multi and GEN2 P1000 Multi as options in the pipette dropdown

# Expected behavior

GEN1 P1000 Multi and GEN2 P1000 Multi should be removed as options from LC

**Comment by mikecardarelli** [comment]
New JIRA ticket: https://opentrons.atlassian.net/browse/RAUT-202
