### ISSUE TITLE
Protocol Details Page: min width screen size responsiveness 

### ISSUE THREAD

**Issue by skyewindsor** [Opentrons/opentrons#10690]
# Overview

The protocol details page needs to be responsive according to the dimensions outlined in the design below. 

# Implementation details

Note that at the min-width screen size of 600px, the character count in the description box gets reduced to 125 characters before content gets truncated.

# Design

https://www.figma.com/file/2xjSLHXquNsKvC1mV9NMjr/Milestone-2?node-id=1034%3A139889

# Acceptance criteria

- [ ] The protocol details page renders correctly at a 600px viewport width

**Comment by koji** [comment]
Created a ticket for this on Jira
Devs will take care of this issue.
