### ISSUE TITLE
chore(robot-server): upgrade Pydantic to support latest mypy

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#10702]
## Overview

We [want to upgrade mypy](https://github.com/Opentrons/opentrons/issues/10701), but our current version of Pydantic [has a bug](https://github.com/samuelcolvin/pydantic/issues/3528) in its mypy plugin that makes it incompatible with later versions of mypy.

## Acceptance criteria

- [ ] Robot server uses latest version of Pydantic
- [ ] `opentrons` package accepts latest version of Pydantic
    - If it seems responsible / possible, we should expand the version of Pydantic for the `api` package rather than setting it to something exact

**Comment by SyntaxColoring** [comment]
Moved to Jira: RSS-49
