### ISSUE TITLE
bug(api): Heater-Shaker latch status not being updated or read properly

### ISSUE THREAD

**Issue by ecormany** [Opentrons/opentrons#10707]
# Overview

In the current implementation of the H-S API in #10426, the value of `labware_latch_status()` is not updated immediately after a `close_labware_latch()` or `open_labware_latch()` call. Putting a `set_and_wait_for_shake_speed()` command in between triggers the status to update. However, the shake command is not properly throwing errors when the latch status is not `idle_closed`.

# Steps to reproduce

For write failure: Get the value of `labware_latch_status()` after issuing a `close_labware_latch()` or `open_labware_latch()` command but without an intervening shake command. It will be the previous status (`idle_unknown` at protocol start).

```python
	hs = protocol.load_module('heaterShakerModuleV1', 6)
	hs.open_labware_latch()
	hs.labware_latch_status  # idle_unknown
```

```python
	hs = protocol.load_module('heaterShakerModuleV1', 6)
	hs.close_labware_latch()
	hs.labware_latch_status  # idle_unknown
```

```python
	hs = protocol.load_module('heaterShakerModuleV1', 6)
	hs.close_labware_latch()
	hs.set_and_wait_for_shake_speed(500)
	hs.deactivate_shaker()
	hs.open_labware_latch()
	hs.labware_latch_status  # idle_closed [sic!]
```

```python
	hs = protocol.load_module('heaterShakerModuleV1', 6)
	hs.close_labware_latch()
	hs.set_and_wait_for_shake_speed(500)
	hs.labware_latch_status  # idle_closed
```

For read failure: Issue a `set_and_wait_for_shake_speed()` command when the latch status is not `idle_closed`. It will succeed.

```python
	hs = protocol.load_module('heaterShakerModuleV1', 6)
	hs.open_labware_latch()
	hs.set_and_wait_for_shake_speed(500)
	hs.current_speed  # 500
```

# Current behavior

- `close_labware_latch()` and `open_labware_latch()` do not change latch status by themselves.
- `set_and_wait_for_shake_speed()` allows shaking with `idle_unknown` status. It can also incorrectly read the status as `idle_closed` or `idle_unknown` when it should be `idle_open`.

# Expected behavior

- `close_labware_latch()` should update the latch status to `closing` and then `idle_closed` (this transition should be effectively immediate in simulation)
- `open_labware_latch()` should update the latch status to `opening` and then `idle_open` (this transition should be effectively immediate in simulation)
- `set_and_wait_for_shake_speed()` should throw an error if the latch status is not `idle_closed`.

**Comment by mcous** [comment]
I believe this issue should be fixed as of #10727; in my testing with the app and EVT H/S hardware, the latch status reacted correctly to latch commands.

Please re-open if this should not have been closed

**Comment by mcous** [comment]
I re-opened because I'm to get a H/S protocol to analyze. I'm getting:

```
CannotPerformModuleAction [line 31]: Cannot start H/S shake unless labware latch is closed
```

Even though my protocol has an explicit `heater_shaker.close_labware_latch()`

**Comment by ecormany** [comment]
Same for me, it's the opposite problem now. With…
```python
	hs.close_labware_latch()
	hs.set_and_wait_for_shake_speed(500)
```
…i get the "cannot start" error.

**Comment by mcous** [comment]
Figured out the issue, it's this TODO here: https://github.com/Opentrons/opentrons/blob/b8c7c8878a8c99ad2f2c5d6bc150faecb0b7f7d4/api/src/opentrons/hardware_control/modules/heater_shaker.py#L390

@sannit it's looks like a simple little fix, was going to include it in #10426 so we can actually test:

```python
    async def _wait_for_labware_latch(
        self, status: HeaterShakerLabwareLatchStatus
    ) -> None:
        """Wait until the hardware reports the labware latch status matches."""
        while self.labware_latch_status != status:
            await self.wait_next_poll()
```

**Comment by mcous** [comment]
> since the analysis is no longer reliant on slow simulation mechanism that reaches into the hardware control, the latch's status is not updated during analysis

I don't think this is true; to the best of my knowledge, fast sim still uses "simulating" modules from the hardware API. My above fix makes protocol analysis work

**Comment by sanni-t** [comment]
> I don't think this is true; to the best of my knowledge, fast sim still uses "simulating" modules from the hardware API. My above fix makes protocol analysis work

Oh ok. I definitely misunderstood then

**Comment by ecormany** [comment]
@sanni-t All looks fixed in simulation, closing this ticket.
