### ISSUE TITLE
6.0 Feedback:  Robot upgrade fails after 20min - blocked unable to perform alpha testing

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#10714]
### Overview

I am getting errors when upgrading robot to alpha-2, leading to upgrade failure  with write EPIPE error. It took close to 20min for "Robot Update in progress" modal followed by error.

### Current Behavior

![Screen Shot 2022-06-09 at 8 25 24 PM](https://user-images.githubusercontent.com/39049853/172969731-7889d679-92d4-4064-9214-ebc05341f550.png)
<img width="1428" alt="Screen Shot 2022-06-09 at 8 25 33 PM" src="https://user-images.githubusercontent.com/39049853/172969751-1b9f79d0-8579-44ac-9046-fbba497d4de5.png">
<img width="1395" alt="Screen Shot 2022-06-09 at 8 56 31 PM" src="https://user-images.githubusercontent.com/39049853/172969765-7c1519f6-1d22-45b8-80f8-6bf210a36db4.png">
<img width="1430" alt="Screen Shot 2022-06-09 at 9 04 38 PM" src="https://user-images.githubusercontent.com/39049853/172969793-3f569733-2853-4d2f-99a8-4f531f3a6e0f.png">

### Expected Behavior

Robot Update should be successful

### Steps To Reproduce

Steps to reproduce:

1. Upgrade the app
2. App goes for restart
3. Click on device -> go to device landing page -> select a protocol and current a protocol but don't start it
4. Click on “view update ” link from software update banner
5. “Robot update in progress” modal shows up and after 20min fails with write EPIPE error
6. console shows 409 conflict with /server/update/begin endpoint

Troubleshooting steps:
restarted the app
restarted the robot
then did robot upgrade -> consistently failed for 3 times

`nehaojha@nehas-MBP opentrons % curl \
-H 'Content-Type: application/json' \
-H 'opentrons-version: *' \
192.168.1.64:31950/health
{"name":"VeryQWEQWEHC12312362379746582222222","robot_model":"OT-2 Standard","api_version":"6.0.0-alpha.1","fw_version":"v1.1.0-25e5cea","board_revision":"2.1","logs":["/logs/serial.log","/logs/api.log","/logs/server.log"],"system_version":"v1.10.0","maximum_protocol_api_version":[2,12],"minimum_protocol_api_version":[2,0],"links":{"apiLog":"/logs/api.log","serialLog":"/logs/serial.log","serverLog":"/logs/server.log","apiSpec":"/openapi.json","systemTime":"/system/time"}}%    nehaojha@nehas-MBP opentrons % `
### Operating system

Mac

**Comment by laviera** [comment]
@reachojhaneha - these errors look somewhat network related ...
1.  What version are u upgrading from ?
2. can u post the logs from the robot ?

**Comment by reachojhaneha** [comment]
@laviera I am upgrading from alpha-1
Here are the logs from robot
[api.log](https://github.com/Opentrons/opentrons/files/8878744/api.log)
[serial.log](https://github.com/Opentrons/opentrons/files/8878745/serial.log)
[server.log](https://github.com/Opentrons/opentrons/files/8878747/server.log)

**Comment by reachojhaneha** [comment]
![Screen Shot 2022-06-10 at 8 58 51 AM](https://user-images.githubusercontent.com/39049853/173069491-e6d15707-a87c-4f5b-adab-9fbfdff98506.png)
I was able to upgrade my robot with USB cable. 
Closing issue
