### ISSUE TITLE
6.0 Feedback: robot update modal disappears prematurely

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#10721]
### Overview

During a robot upgrade, the robot will briefly become "unhealthy" as the server reboots. In the v5 app, the robot upgrade modal will remain present, even as the robot becomes unhealthy, displaying a "Robot is rebooting" message.

In the v6 app, the UI navigates away from the robot's settings page / update modal as soon as the robot becomes unhealthy, dropping you to a "Devices" page that's missing your robot.

### Current Behavior

In v6, the "Robot is restarting" message flashes briefly, then you are dropped to this screen:

<img width="1136" alt="Screen Shot 2022-06-10 at 09 37 58" src="https://user-images.githubusercontent.com/2963448/173078008-1df2a1c6-ee57-4ca3-b88a-3c5ea2c21d32.png">

The robot being updated is hidden in the "Unavailable" collapsed section. Eventually, when the robot finishes rebooting, it displays here again

### Expected Behavior

This is the end of a robot update in v5. Notice the changes in the robot sidebar as the robot becomes unconnectable, but the update modal remains open

![2022-06-10 09 29 58](https://user-images.githubusercontent.com/2963448/173076514-da188ad7-7360-40b7-8fec-72caca20db3a.gif)

At the conclusion of the update, the user is given a success message when the app detects the robot is healthy again with the correct version

<img width="1136" alt="Screen Shot 2022-06-10 at 09 31 57" src="https://user-images.githubusercontent.com/2963448/173076616-ed573e64-d352-432f-a21d-208cb9df61f9.png">

### Steps To Reproduce

Update a robot using the v6 app and compare it to an update run from the v5 app.

**Comment by y3rsh** [comment]
After discussion we would like to remove this success message entirely.   Once the new flow is implemented a success modal will be a part of the flow.

**Comment by rwarshauer** [comment]
Video to long to attach, but robot goes through update. Message pops up saying robot is restarting. No success screen, robot reboots to updated version.
