### ISSUE TITLE
6.0 Feedback:  [Design QA] Device Details Page#10150

### ISSUE THREAD

**Issue by mmencarelli** [Opentrons/opentrons#10730]
### Current Behavior

[Annotated Figma frame](https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=14185%3A283354)

- [ ] (1) Just want to note that when I click on the 'x', nothing happens
- [x] (2) Should be 1rem margin here
- [x] (3) With the addition of the toast, the menu overflow is off and doesn't have the 4px margin on the top and right side 
- [x] (4) This image should not change placement when there's a toast message present
- [x] (5) This svg should be 20x20 vs 16x16 
- [x] (6) Enabled colour in our toggle component should be darkGreyEnabled
- [x] (7) Update colour of h6 to darkGreyEnabled
- [x] (8) Remove box-shadow
- [x] (9) Extra margin on right/left side. Looks like we have 4px on `PipetteCard_P10 Single-Channel GEN1` and 8px on `Flex-sc-1qhp8l7-0 lfWeqr`
- [x] (10) update `Flex-sc-1qhp8l7-0 kEIVxu` colour of border to our mediumGreyEnabled
- [x] (11) This open menu needs to be placed 4px below and aligned with the button. Check out the documentation in the design system for placement 
- [x] (12) There's a bit of space to the left of the toggle that makes it indent to the right from the header above it
- [x] (13) Could we update the image for the OT-2 to a retina image? It's looking blurry on my screen. I'll attach a new image with the same ratio at double the size. 
- [x] (14) Wanted to flag this  (664px width)
- [x] (15) Wanted to flag this (952px width) 
![OT2-R_220px_300dpi](https://user-images.githubusercontent.com/54682054/173147654-e7b1a2f9-8eba-40b5-a65c-de4b48e0288f.png)

<img width="623" alt="Screen Shot 2022-06-10 at 1 12 05 PM" src="https://user-images.githubusercontent.com/54682054/173143466-a1cf2bb0-c0f1-42dc-a67c-c6878463bd5e.png">
<img width="509" alt="Screen Shot 2022-06-10 at 1 12 10 PM" src="https://user-images.githubusercontent.com/54682054/173143474-e27c40b4-c9a6-42c8-9e72-229ed1eaeb75.png">
<img width="711" alt="Screen Shot 2022-06-10 at 1 12 16 PM" src="https://user-images.githubusercontent.com/54682054/173143477-38389edb-5402-4e82-a081-5ba4ccad18cb.png">

**Comment by vabruzzo** [comment]
this issue can also address #10771

**Comment by vabruzzo** [comment]
1 will be fixed when #10732 is merged in.
