### ISSUE TITLE
6.0 Feedback: magnetic module engage height maxima in UI are wrong

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#10736]
### Overview

The module controls UI states the following minimum and maximum engage heights

| generation | minimum | maximum |
| --- | --- | --- |
| gen 1 | -5 mm | 40 mm |
| gen 2 | -4 mm | 16 mm |

Every one of these values is wrong

### Current Behavior

<img width="1136" alt="Screen Shot 2022-06-13 at 14 49 28" src="https://user-images.githubusercontent.com/2963448/173424175-e7f56f56-4854-46d3-8594-fe144bddcd89.png">

<img width="1136" alt="Screen Shot 2022-06-13 at 14 47 03" src="https://user-images.githubusercontent.com/2963448/173423632-475a3b38-8475-4636-b4ff-19a0d6459acf.png">

### Expected Behavior

Correct engage height minimums and maximums, in actual `mm`, which is what the `/commands` and `/modules` endpoint use and report

| generation | minimum | maximum |
| --- | --- | --- |
| gen 1 | -2.5 mm* | 20 mm |
| gen 2 | -2.5 mm | 20 mm |

*Note: This value should be `-4 mm` in reality, but there is currently a bug in the hardware control API: #9585. Until 9585 is fixed, `-2.5 mm` is the lowest value the API will accept/report.

**Comment by y3rsh** [comment]
Validated -2.5 - 20 are the valid and indicated as the range in the app.  Confirming the value also moves the mag module platform as expected.  2 gen 2 mag modules simultaneously connected also work and display the correct data in the module card.
<img width="426" alt="image" src="https://user-images.githubusercontent.com/502770/176701362-54c885e4-20e2-41d0-927f-38fed3c49610.png">
