### ISSUE TITLE
6.0 Feedback:  lights toggle looks clickable when robot not available

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#10739]
### Overview

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/502770/173441241-92229571-6701-467b-9e01-042c12c0ffa9.png">

**Comment by koji** [comment]
@y3rsh you mean that the app should make the light button `disabled`?

**Comment by y3rsh** [comment]
Yes, since everything else is disabled when the root is unavailable.

**Comment by nusrat813** [comment]
@koji - any update on this?

**Comment by koji** [comment]
@nusrat813 The toggle button for the light has been disabled in an unavailable robot card.

![Screen Shot 2022-07-14 at 1 39 42 PM](https://user-images.githubusercontent.com/474225/179047739-b2a0fe8b-7f3c-4f95-aeb2-7709bb4b72e7.png)
