### ISSUE TITLE
6.0 Feedback:  On protocol run record start and end times are not displayed.

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#10738]
### Overview

This protocol completed. The start and end times of each command are in the json when you download it, but are not shown in the app.
![image](https://user-images.githubusercontent.com/502770/173438448-53515545-2f9a-4ef2-b487-637d1438f619.png)

### Current Behavior

Not shown.

### Expected Behavior

Shown.

### Steps To Reproduce

Run a protocol with steps that complete.
cancel or complete teh run
from the devices screen  view the protocol run record
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/502770/173439687-a6327a28-1ba4-4ef6-b1dd-946a83f52e7e.png">

### Operating system

Mac

**Comment by bndo** [comment]
No one has been able to repro this for a while. The related PR #10860 will be merged shortly

**Comment by vabruzzo** [comment]
@bndo i've merged #10860 and unassigned myself from this ticket. I will move it to bug backlog in case it pops up again.

**Comment by bndo** [comment]
I'm going to close this because it has the `required-for-6.0` label on it. @y3rsh just FYI for when you're back!

**Comment by nusrat813** [comment]
Verified fixed
