### ISSUE TITLE
Tip Probe Infinite Loop

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1073]
Robot will not complete tip probe if you try to re-do it after calibrating a tip rack.

## Expected Behavior
- User can calibrate a tip rack, return to tip probe, and complete tip probe

## Observed Behavior
- If user returns to tip probe after calibrating a tip rack, robot never finishes tip probe (it goes through the motions, but reports 'pipette not calibrated' at end.

## Steps to reproduce
- Open app (reproduced on Version 3.0.0-beta.0 (3.0.0-beta.0.6986))
- Connect to any robot (reproduced with bitter-wood on commit ebe78a5)
- Load protocol below
- Tip probe and calibrate tip rack
- Click on 'left' pipette in 'Pipette Calibration' in sidebar to return to pipette calibration
- Re-do pipette calibration
- Observe robot completes tip probe but reports 'pipette not calibrated' and asks user to do tip probe again (infinite loop).

reported by Jane S

**Comment by mcous** [comment]
Unable to reproduce on `3.1.2`, so presuming fixed
