### ISSUE TITLE
6.0 Analytics: Hook back up the events related to running protocols

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#10749]
# Overview
A number of Mixpanel events stopped firing after the shift from 4.7.0 to 5.0.x. Let's hook them back up to the new UI  elements.

# Acceptance criteria
Make sure the following events are hooked up to the buttons on the protocol run details page: 
- [x] runStart

- [x] runFinish

- [x] runPause

- [x] runResume

- [x] runCancel

- [x] runAgain (from Protocol Run Detail Page CTA button)

- [x] runAgain (from Protocol Run Detail Page overflow menu)

**Comment by y3rsh** [comment]
This is reopened as alpha.3 seems to be pushing at mixpanel but no events besides robotUpdate* are available.
This issue is blocking for the 6.0 release but not for beta.

**Comment by bndo** [comment]
Closing as events were confirmed firing and in mixpanel

**Comment by rwarshauer** [comment]
All listed buttons verified in Beta3 as working
