### ISSUE TITLE
SPIKE: Investigate handling hash tags in robot names in react router

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#10756]
# Overview
This will help us handle situations where more than 1 robot is given the same name on a network. The second robot to receive a name with be disambiguated with a `#` sign. This `#` causes problems in-app due to the way react router handles these symbols. 

# Goal
Let's see if we can work around the limitations in react-router

**Comment by koji** [comment]
react-router version: v5.1.1
