### ISSUE TITLE
6.0 Feedback: Lights turn off during deck cal

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#10752]
### Overview

I initiated a deck cal on v6.0.0-beta.0. When I got to the initial pick up tip step, the lights turned off. The lights should be on for the entire calibration sequence.

**Comment by koji** [comment]
Sorry, I turned off the light when @emilywools tried to do deck cal.
I'm 100 sure that the light always turns on when an OT-2 does deck cal, pipette offset cal, and tip length since I've done them so many times since last month and that hasn't happened even once.
