### ISSUE TITLE
6.0 Analytics: Replace deprecated protocol upload events

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#10750]
# Overview
With the UX changes in OT App 6.0, we won't need the protocol upload events that we used in 5.0 and earlier. Instead, we should replace them with 2 new events related to creating a protocol run record. 

# Acceptance Criteria

- [ ] Remove `protocolUploadRequest` 

- [ ] Remove`protocolUploadResponse`

- [ ] Add a new event for `createProtocolRecordRequest`

- [ ] Add a new event for `createProtocolRecordResponse`

**Comment by bndo** [comment]
Closed by #11112
