### ISSUE TITLE
6.0 Feedback:  reducing width of window casues div to not overflow correctly 

### ISSUE THREAD

**Issue by nusrat813** [Opentrons/opentrons#10771]
### Overview

653x987

### Current Behavior

<img width="645" alt="Screen Shot 2022-06-14 at 3 28 18 PM" src="https://user-images.githubusercontent.com/30632549/173879976-68dfcbbe-f630-4f90-98f2-982402bbeb40.png">
<img width="520" alt="Screen Shot 2022-06-15 at 12 38 08 PM" src="https://user-images.githubusercontent.com/30632549/173880235-1533d56b-adfa-4fa8-ae49-0e98b182e948.png">

**Comment by vabruzzo** [comment]
@nusrat813  this was fixed in another design QA pr that was reviewed and merged into release_6.0.0
I will keep this open for you if you'd like to QA on that branch or close it out.

**Comment by nusrat813** [comment]
Verified fixed
