### ISSUE TITLE
Robot Settings: Calibration status section

### ISSUE THREAD

**Issue by skyewindsor** [Opentrons/opentrons#10788]
# Overview

A new calibration status section needs to be added to the robot settings page. 

# Implementation Details

This will replace the "About Calibration" section

# Design

https://www.figma.com/file/2xjSLHXquNsKvC1mV9NMjr/Milestone-2?node-id=1400%3A157559

# Acceptance criteria

- [ ] "Launch calibration" button opens calibration dashboard
- [ ] Calibration status banner appears in this section
- [ ] "See how calibration works" hyperlink opens "how the calibration works" modal from PUR

# Selectors for E2E

- [ ] Launch calibration
- [ ] See how calibration works

**Comment by koji** [comment]
This has been implemented and 6.2 has this.
