### ISSUE TITLE
6.0 Feedback:  overflow menu is overlapping with slideout on device landing page

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#10782]
### Current Behavior

<img width="1017" alt="Screen Shot 2022-06-15 at 4 01 50 PM" src="https://user-images.githubusercontent.com/39049853/173916656-81cd395e-5917-4b07-9b87-bf65e5c78c9e.png">

### Steps To Reproduce

1. App is on 6.0.0-beta-0 
2. click on overflow menu
3. Click on run a protocol button
4. the slideout opens but the overflow menu is persistent.

**Comment by b-cooper** [comment]
Closed by #10990

**Comment by y3rsh** [comment]
### verified alpha5
https://user-images.githubusercontent.com/502770/177564458-e42a3728-0df8-4059-9930-6e92fba6a205.mp4
