### ISSUE TITLE
Robot Settings: Download calibration section

### ISSUE THREAD

**Issue by skyewindsor** [Opentrons/opentrons#10789]
# Overview

The "download calibration data" button will have its own section and needs to be moved to the bottom of the robot settings page.

# Implementation details

Button is selectable even if no calibration data present

# Design

View the disabled and active versions of this section in these two renderings: https://www.figma.com/file/2xjSLHXquNsKvC1mV9NMjr/Milestone-2?node-id=84%3A51932

# Acceptance criteria

- [ ] Download calibration section renders correctly
- [ ] Download calibration data button greyed out when there's no calibration data
- [ ] Download calibration data button enabled when there is calibration data
- [ ] Body copy updated to "Save all three types of calibration data as a JSON file."

**Comment by koji** [comment]
The PR for this has been merged into edge
