### ISSUE TITLE
6.0 Feedback:  Protocols with long names overlap in protocol run history 

### ISSUE THREAD

**Issue by nusrat813** [Opentrons/opentrons#10797]
### Overview

1315X840

### Current Behavior

<img width="856" alt="Capture1122" src="https://user-images.githubusercontent.com/30632549/174115544-c98016e5-c815-44dd-b8ff-6b0fd5e1994f.PNG">

### Operating system

Windows

**Comment by koji** [comment]
- [ ] Need the design team support for spacing

**Comment by koji** [comment]
Ask about adding padding to the protocol to Emily and Mel. If they agree with that as a solution, we can add it.
If not, we should close this since actually there is no overlap.

**Comment by nusrat813** [comment]
@koji - any update on this?

**Comment by koji** [comment]
@nusrat813 This will be solved by #11054
