### ISSUE TITLE
6.0 Feedback: app no longer syncs robot time

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#10804]
### Overview

Prior to the OT-2R, OT-2's did not ship with a real-time clock module installed. This means that whenever an OT-2OG is turned off, it loses track of the time.

To account for this, #6501 added functionality to the app that would sync the OT-2's clock with the user's computer at the time the "Connect" button/toggle was pressed. The v6 app seems to have removed this behavior, which will cause large and confusing time differences between non-refresh OT-2s and the app anywhere timestamps are used.

(This also affects OT-2Rs whose RTC's backup battery has died, which will take several years of operation to drain)

### Current Behavior

The app never checks or sets the OT-2's clock.

### Expected Behavior

At some point before a robot is used or interacted with, the app should:

1. Check the robot's time
2. If the robot's time disagrees by some threshold with the app, set the robot's time
    - <= v5 app uses 60 seconds as the threshold

### Robot setup or anything else?

See https://github.com/Opentrons/opentrons/blob/f003365aa47b3906f5ff6b3162e200d786043a5e/app/src/redux/robot-admin/epic/syncTimeOnConnectEpic.ts for previous sync time logic

**Comment by bndo** [comment]
Connect to clock before the run is created.

**Comment by mikecardarelli** [comment]
I think we can live without this for the next BETA release.
