### ISSUE TITLE
Calibration Dashboard: empty pipette mount

### ISSUE THREAD

**Issue by skyewindsor** [Opentrons/opentrons#10824]
# Overview

These should be the states of the calibration dashboard when there is an empty pipette mount. 

# Implementation details

When a mount is empty there are no highlighted calibrations and no ability to open/close the card

# Design

https://www.figma.com/file/2xjSLHXquNsKvC1mV9NMjr/6.2-Liquid-Setup%2C-Changing-Deck-State%2C-Wizards?node-id=2304%3A194016

# Acceptance criteria

- [ ] Empty mount has no open/close functionality
- [ ] Progress tracker skips empty mount card
- [ ] Empty mount card is not clickable 
- [ ] Empty mount card still appears in normal ordering on the dashboard

**Comment by koji** [comment]
This was released as 6.3.
