### ISSUE TITLE
If robot needs to be updated, always display the update available banner and warn if robot is busy

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#10831]
1. If the robot has an update available, always show the software update available banner on the robot card on the robot landing page, the robot detail page and the Robot Settings > Advanced Settings page

2. If the user launches the View Update modal and clicks Update Robot, show an “Are you sure” modal to the user to let them know updating will kill any in-progress actions.

See Figma for design details: https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=5196%3A190443

**Comment by y3rsh** [comment]
We **STRONGLY** suggest you update your robot.

https://user-images.githubusercontent.com/502770/176705860-fc06516d-65a5-4ec5-9b53-6dc82d89ca4d.mp4

Confirmation modal present.

https://user-images.githubusercontent.com/502770/176706973-d774d2b7-5bd8-4373-add6-a7a51d043ae8.mp4

**Comment by emilywools** [comment]
maybe you shouldn't be able to dismiss this banner and we should make this more emphatic.

A software update is available for this robot. <something about how you need to update to access the robot's functionality>.

cc @ecormany ?
