### ISSUE TITLE
Labware definition `magneticModuleEngageHeight` field is specified ambiguously

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#10830]
# Overview

Labware definitions have an optional `magneticModuleEngageHeight` field, which is [described](https://github.com/Opentrons/opentrons/blob/b8c7c8878a8c99ad2f2c5d6bc150faecb0b7f7d4/shared-data/labware/schemas/2.json#L156-L159):

> Distance to move magnetic module magnets to engage

## Ambiguity in measurement that we should resolve

The description is ambiguous in two ways:

1. It does not say which origin point we're measuring from. It could be:
   
   * The Magnetic Module's labware base plane.
   * A Magnetic Module GEN1's home point.
   * A Magnetic Module GEN2's home point (might effectively be the same as for GEN1, not sure).
  
2. It does not say what units we're measuring in. It could be:

   * Millimeters.
   * Magnetic-Module-GEN1–compatible "short millimeters".

We use various combinations of home point vs. base plane and millimeters vs. short millimeters elsewhere in our codebase, so there is cause for uncertainty.

## Legacy behavior that we should document

There is a hard-coded list of labware whose `magneticModuleEngageHeight` we treat specially.

In Protocol Designer:

https://github.com/Opentrons/opentrons/blob/b8c7c8878a8c99ad2f2c5d6bc150faecb0b7f7d4/shared-data/js/getLabware.ts#L65-L78

And in the Python Protocol API:

https://github.com/Opentrons/opentrons/blob/b8c7c8878a8c99ad2f2c5d6bc150faecb0b7f7d4/api/src/opentrons/protocol_api/module_contexts.py#L28-L34

The exact way in which we treat them specially differs between Protocol Designer and the Python Protocol API, which contributes to bug #9529. It's not immediately clear to me which side is correct. See that ticket for details.

I think we need to document this behavior as part of the `magneticModuleEngageHeight` field because:

* The implementation needs to be duplicated between Protocol Designer and the Python Protocol API. When the two implementations differ, it's difficult to tell which one is correct unless the correct behavior is documented somewhere central, like here.
* This *is*, technically, required information to correctly interpret the `magneticModuleEngageHeight` field, in the general case.

# Acceptance criteria

At a minimum, the description in the JSON schema should specify:

* [ ] Which origin point we should use for new labware definitions.
* [ ] Which units we should use for new labware definitions.

But ideally also:

* [ ] The list of special labware.
* [ ] How to interpret `magneticModuleEngageHeight` for those labware.
    * [ ] Which origin point?
    * [ ] Which units?

These can be punted to another ticket if the investigation turns out to be too much.

**Comment by mcous** [comment]
Moved to RSS-110
