### ISSUE TITLE
6.0 Feedback:  When a run is in a terminal state, Rerun protocol and Run a protocol should be available

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#10856]
### Overview

When a run is in a terminal state (completed, failed or canceled), a user should be able to run a protocol the following ways:

1. Run a protocol button on Robot detail page
2. Rerun protocol from ... menu on recent runs page

right now both of those are disabled when a protocol is current and in a terminal state. These two ways should be enabled.

<img width="628" alt="Screen Shot 2022-06-21 at 4 22 56 PM" src="https://user-images.githubusercontent.com/4339860/174891938-e6a40507-9124-42cb-a343-1dcc256bd4e2.png">

**Comment by ecormany** [comment]
I think this is related to #10854 — all these features seem to be blocked by the robot thinking it's busy when it's actually done with a protocol.

**Comment by y3rsh** [comment]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/502770/176477304-7884a924-97ba-4299-a9f1-76e0ed2fc2af.png">
