### ISSUE TITLE
6.0 Feedback: 'No module named pandas' 

### ISSUE THREAD

**Issue by nusrat813** [Opentrons/opentrons#10874]
### Current Behavior

Pandas package not found when uploading protocol 

slack nus for protocol 

reproducible on mac and windows 
![Image from iOS (7)](https://user-images.githubusercontent.com/30632549/175328357-2a41f57b-0bf5-41f5-b248-952d1c9f339f.jpg)

### Operating system

Windows

**Comment by SyntaxColoring** [comment]
This looks like an instance of the app's local Python environment differing from the robot's Python environment.

`pandas` is on the robot I'm *pretty sure,* and protocols may expect it to be there. It's almost certainly not in the app's local Python environment.

**Comment by ecormany** [comment]
`pip list` on my robot running 6.0.0a2 lists pandas 0.25.3. I've never installed it on my local Python.

**Comment by y3rsh** [comment]
verified
[smalles.py.zip](https://github.com/Opentrons/opentrons/files/9011072/smalles.py.zip)
is analyzed on the app.
