### ISSUE TITLE
6.0 Feedback: Design Feedback -  FactoryReset Slideout

### ISSUE THREAD

**Issue by koji** [Opentrons/opentrons#10888]
- [x] (1) Up the size of this icon to 24px, currently it's 20px
 - [x] (2) Wondering why this is a different style from design?
 - [x] (3) Add 8px margin between the list items
 - [x] (4) Looks like there's a barely noticeable grey line right underneath the button?
 ~~- [ ] (5) remove box shadow from .layXKe~~
 ~~- [ ] (6) Looks like the SVG is a bit thicker than the designs—when you get to this step, contact me and I can try~~ sending you another SVG
 - [x] (7) The hover state colour should be our darkGreyHover (#646468), currently it's #283d52
 - [x] (8) When I try to tab through all the links using my keyboard none of the links of the tabs go into their focusVisible state

<img width="611" alt="174907002-e2077252-120c-41b4-82e9-6e1a72b45112" src="https://user-images.githubusercontent.com/474225/175404045-2df767db-6474-4caa-981e-59f6ca55637d.png">

The original feedback is in #10819

**Comment by koji** [comment]
@mmencarelli 
Could you tell me how you find No.4 line? (I don't see it).
Could you tell me about No.5 and No.6 since they are not in the image you shared with us?

**Comment by mmencarelli** [comment]
> @mmencarelli Could you tell me how you find No.4 line? (I don't see it). Could you tell me about No.5 and No.6 since they are not in the image you shared with us?

1. I've just checked again and it's still there! but it's just very very faint. it's exactly here at the bottom of this blue space 
<img width="392" alt="Screen Shot 2022-06-24 at 12 19 24 PM" src="https://user-images.githubusercontent.com/54682054/175651079-99130d63-4fa5-4e11-9c68-95bbe4851963.png">

2. I can't seem to find where i'm referring to removing the box-shadow, you're good for now! 


Also, I'm noticing there's no margin between the checkbox and the copy. Don't know if this is in progress, but just make sure that gets back in there!

**Comment by koji** [comment]
@mmencarelli 
Thank you for pointing out the space issue (I removed it accidentally)
