### ISSUE TITLE
6.0 Feedback:  [Design QA] Round 2: T2 Device Details

### ISSUE THREAD

**Issue by mmencarelli** [Opentrons/opentrons#10892]
### Overview

This is round 2 of the T2 Device Details page. First round review can be found at #10842

### Expected Behavior

Round 2 feedback on T2 Device Details Page

[Link to view annotated frame in Figma](https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=14185%3A283354)

This is looking so good btw!

- [x]  (1) I have my viewport at 1000px, and wondering why the temp module card isn't locking into that second column?
- [x]  (2) Can we add in the different states to the toggle? I've pulled them all to the right of this screenshot in figma
- [x]  (3) Let's up the margin-bottom on .dZngDm to 1rem
- [x]  (4) Not sure if this is the appropriate place for this feedback: Noticing that when I open the menu overflow and click it again to close it doesn't close it. [Recording here.](https://www.loom.com/share/cfc065177ca149258cc7942663c65de2)
- [x]  (5) Just a wee bit too much spacing going on here, couldn't quite figure out what the culprit was. Should have 1rem (purple box height)
- [x]  (6) Could we have an 8px margin between columns so we don't have text get super close like this?
- [x]  (7) I'm not sure how things are linked, but I noticed that this overflow button isn't picking up @jerader's latest push to fix the various states of this button.
- [x]  (8) Also, can we push the open menu 4px down? currently sitting at the bottom of the menu button icon but should be a bit of space between them
- [x]  (9) Noticing this empty space here

 
<img width="1125" alt="Screen Shot 2022-06-23 at 3 37 09 PM" src="https://user-images.githubusercontent.com/54682054/175426630-2f1f5f31-5b86-4e9b-83b2-b8f5e6cca2b0.png">
<img width="1102" alt="Screen Shot 2022-06-23 at 3 37 14 PM" src="https://user-images.githubusercontent.com/54682054/175426638-09337563-371a-46aa-8831-ca67380fb5a0.png">

**Comment by jerader** [comment]
> Can we add in the different states to the toggle? I've pulled them all to the right of this screenshot in figma

This will be addressed by my other PR: https://github.com/Opentrons/opentrons/pull/11020
