### ISSUE TITLE
6.0 Feedback: Jump to current step does not always display 

### ISSUE THREAD

**Issue by nusrat813** [Opentrons/opentrons#10898]
### Current Behavior

Jump to current step is not always displayed when a user is not active on the run lug. Have to scroll a few times for the jump to current step to display 

see video:

https://user-images.githubusercontent.com/30632549/175561392-5cbb5dc7-b59e-42b4-aa9e-dbb68cd99111.MOV

 

### Expected Behavior

Jump to current step should display after commands are outside of current window display 

### Operating system

Windows

**Comment by bndo** [comment]
Closed with the associated PR
