### ISSUE TITLE
6.0 Feedback:  [Design QA] Round 2: Connect a Robot via IP Address slideout

### ISSUE THREAD

**Issue by mmencarelli** [Opentrons/opentrons#10891]
### Overview

This design review is r2 for the 'connect a robot via IP address'. The first round review can be seen here #10618

### Expected Behavior

Link to view annotated figma frame

 (1) Increase button size to 24px vs the 20px it's at
 (2) Change this font size to our 'label' styling. So it should be 11px vs the 13px it's at
 (3) Align the various states for our text field with the design system (image of side by side comparison outlining the differences included in this PR and in figma if you want to go into the designs). Hover, activated, error and focus-visible need some attention
 (4) Let's have 8px margin-left on the actual input text so it's not so close to the left hand side
 (5) Let's remove the margin-top: 4px on the error text actually.
 (6) Are we able to get this text to be a countdown? If it's not in scope, then static text is fine. If that's the case, then please confirm that we're capturing that future change for a later release. Don't want it to fall between the cracks. Also, can we capitalize "searching" so it's "Searching"
 (7) Update colour of spinner to darkGreyEnabled
 (8) Can we change this text string to "Not Found"
 (9) Can we reverse the order of display here, so any available connections automatically appear at the top? The logic on top of that is that it's in order of user search.
 (10) Can we add margin: 4px 0px; to .mWBlO
 (11) Missing hover state on the "refresh" button
 (12) remove the box-shadow from the button
 (13) increase font size on the button to 11px (currently around 9px)

<img width="576" alt="Screen Shot 2022-06-23 at 2 57 36 PM" src="https://user-images.githubusercontent.com/54682054/175424531-81c242d5-fe53-48cf-ba2f-57f1722d36ed.png">

<img width="680" alt="Screen Shot 2022-06-23 at 2 57 46 PM" src="https://user-images.githubusercontent.com/54682054/175424537-179685d0-ec10-427c-80e3-1b09de5a9032.png">

**Comment by koji** [comment]
Created an issue on Jira.
