### ISSUE TITLE
6.0 Feedback: [Design QA] T3 Protocol Run Page

### ISSUE THREAD

**Issue by mmencarelli** [Opentrons/opentrons#10908]
### Overview

**This is not a full design QA for T3 Protocol Run page. Due to time constraints, I'm only including what needs to be done for 6.0**

### Expected Behavior

[Link to annotated figma frame ](https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=14699%3A293844)

- [x] (1) I believe we changed all instances of "run ID" to 'run'? Might want to double check with @b-cooper 
- [x] (2) Left align "protocol end" column with the column above "status" 
- [x] (3) Few things here—remove the white bg on this button. Also the hover state is displaying the non-error version. Aka, it should not turn blue on hover 
- [x] (4) Needs hover state on these tabs. I've put this in 2 other PR's in the past few days so maybe see if someone has already done this and link it up with their work? 
- [x] (5) Can we set a max-width for the deck map in both labware and module setup to be 740px? Responsive otherwise as the user scales the viewport down. If we set a max-width, then just make sure it stays centered within the frame. Same thing on labware setup
- [x] (6) Update size of icon to be 1rem
- [x] (7) Update font styling to be h3 semibold 
- [x] (8) Update this tertiary button to reflect our design system. (update text to be label-semibold, remove box shadow, include various states incl hover and focusVisible) 
- [x] (9) Make sure it's 1.5rem margin below. Looks like there's extra margin on the button 
- [x] (10) Make sure there's 40px margin between content and button
- [x] (11) remove the ability for these buttons to text wrap
- [x] (12) has this copy changed? If so, please let me know as I'll need to update designs 
- [x] (13) Update styling, make sure the hover state is in there 

<img width="820" alt="Screen Shot 2022-06-24 at 1 18 24 PM" src="https://user-images.githubusercontent.com/54682054/175661666-fa33c485-5acb-4870-8677-1907e3e1b3cc.png">
<img width="579" alt="Screen Shot 2022-06-24 at 1 20 26 PM" src="https://user-images.githubusercontent.com/54682054/175661668-b29b1c62-b4eb-46d8-8232-0944f6adbff7.png">
<img width="777" alt="Screen Shot 2022-06-24 at 1 20 32 PM" src="https://user-images.githubusercontent.com/54682054/175661670-d0dd5cde-14ce-42b7-97d2-82d6324c4dbe.png">
<img width="742" alt="Screen Shot 2022-06-24 at 1 20 37 PM" src="https://user-images.githubusercontent.com/54682054/175661674-567e1573-eabd-49b0-b5f6-49362838f865.png">

**Comment by vabruzzo** [comment]
#4 is being addressed by @jerader in #10906
