### ISSUE TITLE
6.0 Feedback:  Labware section needs custom labware category 

### ISSUE THREAD

**Issue by alexjoel42** [Opentrons/opentrons#10917]
### Overview

# General Background and ask
We have a great labware tab (which I have used a lot). It does make it more difficult to find what custom labware has been loaded on my OT-2. Would it be possible for us to add a "Custom Labware" category?

## Why would we do this?
From a customer's perspective, I have seen them load several versions of the same labware if they don't have a technical drawing and need to make them better. 

Scrolling through gets pretty difficult. Also, if you want to copy and paste the names it's easier if they're all in one place. 

### Current Behavior

You have to scroll to find any custom labware that you have.

### Expected Behavior

We should have a designated custom labware section

### Steps To Reproduce

N/a

### Operating system

Mac

**Comment by mikecardarelli** [comment]
This might be a better ticket to track this request: https://github.com/Opentrons/opentrons/issues/10141
