### ISSUE TITLE
shared-data: add Armadillo labware + h/s adapter definition

### ISSUE THREAD

**Issue by sanni-t** [Opentrons/opentrons#10915]
# Overview

Create a definition for `Opentrons 96 Well PCR Adapter with Armadillo Well Plate 100uL`.
Labware & manufacturer info: https://www.fishersci.com/shop/products/armadillo-96-well-pcr-plate-1/AB2396
Drawing: https://assets.fishersci.com/TFS-Assets/LSG/manuals/MAN0014460_Armadillo_96_PCR_Plate_QR.pdf

Note: This labware is supposed to be dimensionally same as Nest PCR plate which already exists in labware definitions. Verify that they are indeed the same and then you can just duplicate the Nest plate+ adapter definition and change product ID & brand names

Requested loadName & display name: #10973 #10938

**Comment by TamarZanzouri** [comment]
loadName= opentrons_96_pcr_adapter_armadillo_wellplate_200ul
