### ISSUE TITLE
6.0 Feedback: [Design QA] Labware T1 Slideout

### ISSUE THREAD

**Issue by koji** [Opentrons/opentrons#10926]
### Overview
The original feedback is in #10618
[To a dev who picks this up]
Please do not close #10618 until finish fixing all slideouts design feedback.
If you have any questions on this feedback, please ask about your questions to Mel.

### Current Behavior

Link to [annotated frame in Figma ](https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=13793%3A416275)

### **Import custom labware def + toast**
- [x] (1) Size of this button should be 24px (currently 20px)
- [x] (2) remove the box-shadow
- [x] (3) Going to sneak this toast edit in here for simplicity sake, but can we add a max-width of these toasts to like 70% of the viewport? This percentage should also work when we shrink down to our min-width size 
- [x] (4) Can we make it a rule that the toasts stay for 8s instead of 4? Noticing that it's a bit quick. 
- [x] (5) Could we have the toast fade in and out like[ this example? ](https://polaris.shopify.com/components/feedback-indicators/toast#navigation)
- [x] (6) Center this text
- [x] (7) needs 2rem margin-top

<img width="291" alt="Screen Shot 2022-06-03 at 10 12 25 AM" src="https://user-images.githubusercontent.com/54682054/171913280-77901ddc-205b-48be-970e-80f63dc4f253.png">
<img width="862" alt="Screen Shot 2022-06-03 at 10 07 04 AM" src="https://user-images.githubusercontent.com/54682054/171912548-27c5c0ee-1ff9-4a42-9ed8-99128ae1f8cb.png">

**Comment by koji** [comment]
@mmencarelli 
We can add a similar animation to Toast. What we can do is the following.

1. switch animation from `slide-in` to `slide-up`.
2. keep both animations (`slide-in` and `slide-up`) and use one of animations depending on a page

**Comment by mmencarelli** [comment]
> 

This sounds good, would it be possible to check on this branch what you're referring to?

**Comment by koji** [comment]
> > 
> 
> This sounds good, would it be possible to check on this branch what you're referring to?

@mmencarelli yes, if you check out this branch and try to import a protocol into the app.
You can see slideup animation and the current duration is 5 sec.
