### ISSUE TITLE
Update H/S definition loadNames

### ISSUE THREAD

**Issue by skyewindsor** [Opentrons/opentrons#10938]
# Overview

The heater shaker adapter definitions need updated loadNames.

# Acceptance criteria

The API loadNames are corrected to the following: 

- [ ] opentrons_96_deep_well_adapter_nest_wellplate_2ml_deep
- [ ] opentrons_96_flat_bottom_adapter_nest_wellplate_200ul_flat
- [ ] opentrons_96_pcr_adapter_nest_wellplate_100ul_pcr_full_skirt
- [ ] opentrons_universal_flat_adapter_corning_384_wellplate_112ul_flat
- [ ] opentrons_96_pcr_adapter_armadillo_wellplate_200ul

**Comment by TamarZanzouri** [comment]
- [x] opentrons_96_deep_well_adapter_nest_wellplate_2ml_deep
- [ ] opentrons_96_flat_bottom_adapter_nest_wellplate_200ul_flat - this is correct in the file name and in the loadName
- [x] opentrons_96_pcr_adapter_nest_wellplate_100ul_pcr_full_skirt
- [x] opentrons_universal_flat_adapter_corning_384_wellplate_112ul_flat
- [ ] opentrons_96_pcr_adapter_armadillo_wellplate_200ul
