### ISSUE TITLE
6.0 Feedback:  Tip length calibration method selection ignored before calibration beings 

### ISSUE THREAD

**Issue by nusrat813** [Opentrons/opentrons#10939]
### Current Behavior

![Screen Shot 2022-06-28 at 1 14 29 PM](https://user-images.githubusercontent.com/30632549/176289520-dbc3b5fe-e70d-4337-91ad-3e241d470a12.png)

![image (4)](https://user-images.githubusercontent.com/30632549/176296183-ccc82062-3188-4d68-b83a-1fb02597d249.png)

When a user selects always show prompt for calibration method, user is not prompted with modal and automatically gets trash bin as calibration method 

### Expected Behavior

User should get prompted with selection modal 

### Operating system

Mac

**Comment by nusrat813** [comment]
Not a beta blocker but we want to get it into release

**Comment by y3rsh** [comment]
I am not being prompted.

https://user-images.githubusercontent.com/502770/176953963-ba57fdfe-276e-4ffd-9420-24b7326c3186.mp4

**Comment by brenthagen** [comment]
@y3rsh are there any other ways to launch tip length calibration other than from:
 - the protocol run details page setup tab, addressed in https://github.com/Opentrons/opentrons/pull/10976
 - the robot settings page calibration tab, addressed in https://github.com/Opentrons/opentrons/pull/10991

**Comment by y3rsh** [comment]
verified.  The settings seem to be respected everywhere I opened tip calibration from
robot device details
robot settings
