### ISSUE TITLE
6.0 Feedback:  Protocol setup: pipette calibration modal disappears before I can click return tip to tip rack and exit

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#10941]
### Overview
```gherkin
Given I proceed to setup on a protocol when a pipette needs calibration
When I get to the final step of the pipette calibration
Then I am navigated to the setup for run page without time 
to click the `RETURN TIP TO TIP RACK AND EXIT`  button
And the robot is in a bad state, tip on the pipette and not homed 
```
> Calibration steps truncated in the video

https://user-images.githubusercontent.com/502770/176444975-e1f61ed2-95b5-4a79-8b1b-cb97302c4b15.mp4

I must navigate to the device details page, then I can see the modal and click  `RETURN TIP TO TIP RACK AND EXIT` 

https://user-images.githubusercontent.com/502770/176444954-bf088eaa-aabc-4a35-9456-82952daf3ffd.mp4

### Current Behavior

Seems once there is a valid calibration detected through the API call then the page reloads hiding the modal?

### Expected Behavior

The modal does not disappear, I can click the button and the tip is returned and gantry homed.

### Steps To Reproduce

Example in video.

### Operating system

Mac

**Comment by b-cooper** [comment]
Closed By #10955
