### ISSUE TITLE
6.0 Feedback:  Setup for run: Deck map labware offsets seem visually unaligned

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#10942]
### Overview

On the protocol setup page complete LPC and then see the deckmap has the offsets but they all look a little off.
![image](https://user-images.githubusercontent.com/502770/176446823-ada76c1c-0177-418d-a689-ab6885ae41cb.png)

**Comment by emilywools** [comment]
hey Josh do you mean they look off visually or the values are wrong?

**Comment by y3rsh** [comment]
I believe they are accurate values, they are off visually.  The `T` text in the row is misaligned vertically and then in some places the `T` is even missing or is chopped off.

**Comment by rwarshauer** [comment]
Issue is resolved in Beta2
![Screen Shot 2022-07-12 at 1.58.03 PM.png](https://images.zenhubusercontent.com/628bed2ee44f587815e4ae53/e04042d3-c1b8-4107-902d-0b297d3b9f55)

**Comment by emilywools** [comment]
@rwarshauer this does not look correct. the labware in slots 1, 2, 3, 5, 6 has the labware name right aligned instead of left aligned.

**Comment by rwarshauer** [comment]
![Screen Shot 2022-07-12 at 1 58 03 PM](https://user-images.githubusercontent.com/106115893/178563760-6b7546bc-5ca1-411e-9e72-337762347535.png)
Beta2 
Alignment of some slots is to the left and some to the right as mentioned by Emily
