### ISSUE TITLE
LL: change display name for NEST deep well plate

### ISSUE THREAD

**Issue by skyewindsor** [Opentrons/opentrons#10966]
# Overview

The display name for NEST 96 Deepwell Plate 2mL needs to be updated to align with LL naming conventions.

# Acceptance criteria

- [ ] Name renders as "NEST 96 Deep Well Plate 2mL"

**Comment by mikecardarelli** [comment]
New JIRA ticket: https://opentrons.atlassian.net/browse/RAUT-203
