### ISSUE TITLE
How to Restore A previous Software Version Modal flashes and goes to Protocol Landing

### ISSUE THREAD

**Issue by jerader** [Opentrons/opentrons#10972]
### Overview

Click on the `See how to restore a previous software version` link in the General Settings. Nothing in the modal is clickable. The modal closes and redirects to the Protocols Landing page.

https://images.zenhubusercontent.com/38644841/f1463c13-5066-44c2-a180-1c894c185df0/screen_recording_2022_06_30_at_3_42_13_pm.mov

### Acceptance Criteria
- [ ] modal should work properly and links should direct to correct pages

**Comment by y3rsh** [comment]
validated.  modal appears and all elements and links are as expected.
