### ISSUE TITLE
Robot Default Configs: Aspirate Speed

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1098]
As a user, I would like my robot to use a tested default aspirate speed.

## Acceptance Criteria
- Set default aspirate speed as per Robot Config spreadsheet, below.
- Includes min, max, and default speed
- Speeds are set per pipette model

## Implementation Notes
- While we're at it, we're want to update 'aspirate_flow_rate' to µl/mm (removing 'default aspirate seconds')
-- current pipette config: "aspirate_flow_rate=10 / DEFAULT_ASPIRATE_SECONDS"

- Side note on how we go from µl/s to steps/sec:
-- Pipette.py ‘set_flow_rate_ method converts µl to mm using _µl_to_mm function and then calls .set_speed on the pipette
-- .set_speed takes a mm/sec value and saves it
-- firmware (Caitlyn) converts mm/sec to steps/sec

## Resources
- [Robot config spreadsheet](https://docs.google.com/spreadsheets/d/1KOGUng337g-blA8Kw40QwSXYjWRodoclLBR8LQOQYd0/edit#gid=749988930)

**Comment by umbhau** [comment]
@andySigler This one should be good to go, except we need to confirm the units in the config spreadsheet. I linked to the test script in the spreadsheet; we can walk through it together.

**Comment by btmorr** [comment]
This is either done or irrelevant
