### ISSUE TITLE
LL: Update Labware Library with h/s adapter definitions

### ISSUE THREAD

**Issue by skyewindsor** [Opentrons/opentrons#10980]
# Overview

The heater shaker adapter definitions need to be added to the next Labware Library release.

1. Opentrons 96 Deep Well Adapter with NEST Deep Well Plate 2mL ([labware definition](https://github.com/Opentrons/opentrons/blob/edge/shared-data/labware/definitions/2/opentrons_96_deepwell_adapter_nest_wellplate_2ml_deep/1.json) / [image of adapter](https://drive.google.com/drive/u/1/folders/1GwPkk16ouO5I4pG_7GPQi2LmQ88NnRHk) / [image of plate](https://cdn11.bigcommerce.com/s-zmwgbev7rb/images/stencil/1280x1280/products/130/474/NEST2mlDeepWellPlate-VBottom__03828.1653425319.png?c=1) / [adapter website link](https://shop.opentrons.com/deep-well-adapter/) / [plate website link](https://shop.opentrons.com/nest-2-ml-96-well-deep-well-plate-v-bottom/) / adapter catalog number = 991-00066 , Plate catalog number = 503001, 503501 )

2. Opentrons 96 PCR Adapter with NEST Well Plate 100ul ([labware definition](https://github.com/Opentrons/opentrons/blob/edge/shared-data/labware/definitions/2/opentrons_96_pcr_plate_adapter_nest_wellplate_100ul_pcr_full_skirt/1.json) / [image of adapter](https://drive.google.com/drive/u/1/folders/1GwPkk16ouO5I4pG_7GPQi2LmQ88NnRHk) / [image of plate](https://cdn11.bigcommerce.com/s-zmwgbev7rb/images/stencil/1280x1280/products/146/476/NEST_0.1_mL_96-Well_PCR_Plate_Full_Skirt_-1_950px__86077.1653424783.jpg?c=1) / [adapter website link](https://shop.opentrons.com/pcr-adapter/) / [plate website link](https://shop.opentrons.com/nest-0-1-ml-96-well-pcr-plate-full-skirt/) / Adapter catalog number = 991-00064 / plate catalog numbers = 402501 )

3. Opentrons 96 PCR Adapter with Armadillo Well Plate 200ul ( [labware definition](https://github.com/Opentrons/opentrons/blob/edge/shared-data/labware/definitions/2/opentrons_96_pcr_adapter_armadillo_wellplate_200ul/1.json) / [image of adapter](https://drive.google.com/drive/u/1/folders/1GwPkk16ouO5I4pG_7GPQi2LmQ88NnRHk) / [image of plate](https://assets.fishersci.com/TFS-Assets/LSG/product-images/AB-2396_clear.jpg-650.jpg) / [adapter website link](https://shop.opentrons.com/pcr-adapter/
) / [plate website link](https://www.fishersci.com/shop/products/armadillo-96-well-pcr-plate-1/AB2396) / Adapter catalog number = 991-00064  / Plate catalog number = AB2396)

4. Opentrons 96 Flat Bottom Adapter with NEST 96 Well Plate 200 µL Flat ([labware definition](https://github.com/Opentrons/opentrons/blob/edge/shared-data/labware/definitions/2/opentrons_96_flat_bottom_adapter_nest_wellplate_200ul_flat/1.json) / [adapter image](https://drive.google.com/drive/u/1/folders/1GwPkk16ouO5I4pG_7GPQi2LmQ88NnRHk) / [labware image](https://cdn11.bigcommerce.com/s-zmwgbev7rb/images/stencil/1280x1280/products/136/473/NEST_96_Well_Plate_Flat_-_1_950px__48342.1653425234.jpg?c=1) / [adapter website link](https://shop.opentrons.com/96-flat-bottom-adapter/) / [labware website link](https://shop.opentrons.com/nest-96-well-plate-flat/) / adapter catalog number =  991-00065 / plate catalog number = 701011)

5. Opentrons Universal Flat Adapter with Corning 384 Well Plate 112 µL Flat ([labware definition](https://github.com/Opentrons/opentrons/blob/edge/shared-data/labware/definitions/2/opentrons_flat_plate_adapter_corning_384_wellplate_112ul_flat/1.json) / [image 1](https://drive.google.com/drive/u/1/folders/1GwPkk16ouO5I4pG_7GPQi2LmQ88NnRHk) / [image 2](https://www.corning.com/catalog/cls/products/c/corning384WellClearPolystyreneMicroplates/images/3680-384-clear-ps-plate_A.jpg/_jcr_content/renditions/product.zoom.1200.jpg) / [adapter website link](https://shop.opentrons.com/universal-flat-adapter/) / [plate website link](https://ecatalog.corning.com/life-sciences/b2c/US/en/Microplates/Assay-Microplates/384-Well-Microplates/Corning%C2%AE-384-well-Clear-Polystyrene-Microplates/p/corning384WellClearPolystyreneMicroplates) / adapter catalog number = 991-00067 , plate catalog numbers = 3640, 3680, 3700, 3701, 3702, 3702BC, 3844)

6. Armadillo 96 Well Plate 200 µl ([labware definition](https://github.com/Opentrons/opentrons/blob/edge/shared-data/labware/definitions/2/armadillo_96_wellplate_200ul_pcr_full_skirt/1.json) / [image](https://assets.fishersci.com/TFS-Assets/LSG/product-images/AB-2396_clear.jpg-650.jpg) / [plate website link](https://www.fishersci.com/shop/products/armadillo-96-well-pcr-plate-1/AB2396) / plate catalog numbers = AB2396)

# Implementation details

Make sure a post-6.1 warning banner is present on opentrons.com all definitions in this ticket. This does not apply to the app LL. Related ticket [here](https://app.zenhub.com/workspaces/app--ui-5f6248dba845b000139aa767/issues/opentrons/opentrons/9575).

# Acceptance criteria

All labware renders correctly with correct naming, images, and website links.

- [ ] Opentrons 96 Deep Well Adapter with NEST Deep Well Plate 2mL
- [ ] Opentrons 96 PCR Adapter with NEST Well Plate 100ul
- [ ] Opentrons 96 PCR Adapter with Armadillo Well Plate 200ul
- [ ] Opentrons 96 Flat Bottom Adapter with NEST 96 Well Plate 200 µL Flat
- [ ] Opentrons Universal Flat Adapter with Corning 384 Well Plate 112 µL Flat
- [ ] Armadillo 96 Well Plate 200 µl
- [ ] All Labware have post-6.1 compatibility banner rendering correctly

**Comment by mikecardarelli** [comment]
New JIRA ticket lives here: https://opentrons.atlassian.net/browse/RLAB-110
