### ISSUE TITLE
Robot Default Configs: Tip Pickup 

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1099]
As a user, I would like my robot to use a tested, effective method for picking up tips.

## Acceptance Criteria
- Robot uses default method for picking up tips, as specified in robot default configs doc (below)
- Default includes specified method (# of presses, and increment in distance per press) and current
- Defaults are set per pipette model

## Resources
- [Robot config spreadsheet](https://docs.google.com/spreadsheets/d/1KOGUng337g-blA8Kw40QwSXYjWRodoclLBR8LQOQYd0/edit#gid=749988930)

**Comment by umbhau** [comment]
@andySigler drop tip story we talked about. 

Just pending a results from the drop-tip test to confirm an 0.6 A pick-up current doesn't cause any downstream problems.

**Comment by btmorr** [comment]
This is either done or irrelevant
