### ISSUE TITLE
App [Housekeeping]: Overflow Menu Logic Consolidatioon 

### ISSUE THREAD

**Issue by b-cooper** [Opentrons/opentrons#11009]
# Overview

- Audit all overflow menu's added to the app in the 6.0.0 release. Have them covered by a responsible generic component that captures all of their needs.
- Instead of fixing the width of the menu items, make the generic overflow menu component capable of growing with the widest item without wrapping.
- interrogate the usage of `stopPropagation` for individual items in the menu as well as the menu itself (if rendered into a clickable item like a protocol card)

**Comment by koji** [comment]
- suggested solution for the first one

`current`
```ts
const sortOverflowWrapperRef = useOnClickOutside({
    onClickOutside: () => setShowSortByMenu(false),
  }) as React.RefObject<HTMLDivElement>
```

`suggested`
```ts
const sortOverflowWrapperRef = useOnClickOutside<HTMLDivElement>({
  onClickOutside: () => setShowSortByMenu(false),
})
```

- suggested solution for the second one
use `whiteSpace: nowrap` instead of using hard-coded numbers ex `width="11rem"`
