### ISSUE TITLE
6.0 Feedback: Protocols Tab shouldn't initialize to :focus-visible

### ISSUE THREAD

**Issue by b-cooper** [Opentrons/opentrons#11011]
![Screen Shot 2022-07-06 at 10.04.37 AM (1).png](https://images.zenhubusercontent.com/5e1e15beea955f9181a402d3/d771ed61-97ea-480d-9639-ce3ed3603cef)

The App defaults to the Protocols Tab on launch. The `:focus-visible` pseudo-class is being applied to the nav item, though it shouldn't be focused at all

**Comment by nusrat813** [comment]
Verified in beta.2
![Screen Shot 2022-07-12 at 1.49.10 PM.png](https://images.zenhubusercontent.com/5e2720c7aaf6ad22b4062408/8b085fbf-6e49-4083-b108-dce44921293a
)
