### ISSUE TITLE
bug: Long Labware names dont get truncated or "..." in Protocol Designer

### ISSUE THREAD

**Issue by rwarshauer** [Opentrons/opentrons#11014]
If you have a long labware name the name just keeps going and shows no indication that its truncated or longer.
# Overview

# Steps to reproduce
1. Open PD
2. Create protocol
3. Go to design -> Add labware
4. Make labware name super long

# Current behavior
Name just keeps going with no truncation or indication

# Expected behavior
... or shows its longer then shown

![Screen Shot 2022-07-06 at 11 29 37 AM](https://user-images.githubusercontent.com/106115893/177588784-468cc09c-b911-4ad9-99a8-5ec77da418b2.png)

**Comment by y3rsh** [comment]
Closing, work against https://opentrons.atlassian.net/browse/RQA-165
