### ISSUE TITLE
Connectivity: disconnect() does not work.

### ISSUE THREAD

**Issue by collinedington** [Opentrons/opentrons#1103]
## overview

Seemingly a bug where `robot.disconnect()` fails silently, allowing the robot to continue receiving instructions. 

## behavior

After sending `robot.disconnect()`, subsequent commands are still executed.

## steps to reproduce

Using opentrons API 2.5.2 with python 3.6.4 on MacOS Sierra, connected to OT1 hood over usb serial by using `robot.connect('/dev/cu.usbmodem1421')`.

**Comment by mcous** [comment]
Thanks for filing this ticket! Our architecture has changed quite drastically between the OT-1 and the [OT-2](http://opentrons.com/ot-2); the OT-2 contains its own Linux computer that will handle the Serial connection to the motor driver so you don't have to worry about it.

Unfortunately, this change means that we don't have the engineering resources to address this issue with the OT-1 and the legacy app. I'm going to close this ticket as wontfix for now, but if anyone in the community would like to help update the legacy app, we're happy to help. Legacy OT-1 code lives in the `ot1-stable` branch of this repository.
