### ISSUE TITLE
6.0 Feedback:  Add status bar for 'Sending file to robot' step of updates/downgrades

### ISSUE THREAD

**Issue by rwarshauer** [Opentrons/opentrons#11033]
### Overview

When you update the robot the first step of sending the file just shows dots bouncing. This may be fine for fast connections, but updating over wifi on slow connections this looks like its just frozen.

### Current Behavior

Dots bounce while waiting

### Expected Behavior

Progress bar with % complete like other steps

### Steps To Reproduce

1. Open Opentrons app
2. Pick robot
3. Upgrade or downgrad
![Screen Shot 2022-07-07 at 9 53 17 AM](https://user-images.githubusercontent.com/106115893/177790544-112b6c52-1867-452c-b780-3062d2e6a7ff.png)
e

### Operating system

Mac

**Comment by nusrat813** [comment]
getting revamped in calibration wizard overhaul
