### ISSUE TITLE
6.0 Feedback:  Updating robot to Beta1 sometimes results in loops

### ISSUE THREAD

**Issue by rwarshauer** [Opentrons/opentrons#11034]
### Overview

After updating a robot the update was good, but now it just saws updating robot with no step indicated. Yesterday while stuck in some weird loops due to possible networking issues it looped back around to 'Sending file' step. Today it just says updating with no step Listed

### Current Behavior

Loops after update- But does update

### Expected Behavior

Back to normal app screen after update

### Steps To Reproduce

1. Have a robot on Alpha5
2. Update to beta1
3. Observ
![Screen Shot 2022-07-07 at 10 00 29 AM](https://user-images.githubusercontent.com/106115893/177792614-f934f7a8-9fe6-497f-a691-a53083728251.png)
e

### Operating system

Mac

### Robot setup or anything else?

Workaround- Quit app after update and relaunch

**Comment by SyntaxColoring** [comment]
Stale.
