### ISSUE TITLE
6.0 Feedback:  Last two steps of a completed protocol do not have time values listed

### ISSUE THREAD

**Issue by rwarshauer** [Opentrons/opentrons#11041]
### Overview

After finishing a run all the time values per step show but the last two steps.

### Current Behavior

Protocol finishes but last two steps have no times

### Expected Behavior

Times

### Steps To Reproduce

1. Run protocol
2. Finish protocol
3. Observ
[QABOT_🛠 Logo-Modules-CustomLabware 🛠_2022-07-07T16_57_02.684Z.json.zip](https://github.com/Opentrons/opentrons/files/9065960/QABOT_.Logo-Modules-CustomLabware._2022-07-07T16_57_02.684Z.json.zip)
![Screen Shot 2022-07-07 at 1 06 22 PM](https://user-images.githubusercontent.com/106115893/177830812-c4f80a96-e32c-45af-82f0-1bd98a244a7e.png)
e

### Operating system

Mac

**Comment by koji** [comment]
Run Log part has been updated. This issue won't happen.
