### ISSUE TITLE
6.0 Feedback:  Tooltip for heater shaker overflow menu is not in correct spot

### ISSUE THREAD

**Issue by rwarshauer** [Opentrons/opentrons#11043]
### Overview

The tool tip when hovering over set temp is very low and looks to be tool tip for another button

### Current Behavior

Tool tip is super low

### Expected Behavior

Tool tip right below button

### Steps To Reproduce

1. Open App
2. Go to robot with H/S
3. Click overflow menu
4. Hoover set temp
5. Observ
<img width="168" alt="Screen Shot 2022-07-07 at 1 30 28 PM" src="https://user-images.githubusercontent.com/106115893/177834777-a0afb719-9097-4fda-9414-10ade4a91a47.png">
e

### Operating system

Mac

**Comment by jerader** [comment]
Closing this since the tooltip will be removed in this ticket: https://github.com/Opentrons/opentrons/issues/11074
