### ISSUE TITLE
6.0 Feedback:  Run protocol slide-out robot click should only select never unselect

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#11057]
### Overview

`Run protocol` robot selection slide-out should behave like `Run a protocol` slide-out where clicks on protocols only select, never unselect.

When the `Run protocol` slide-out opens and a robot is selected by default I ALWAYS clicked it anyway.  This unselected that robot, causing me to have to click that robot again before being able to click proceed to setup.

### current

https://user-images.githubusercontent.com/502770/178008199-8a109609-f21d-488f-9c47-23811ba4fe66.mp4

### preferred

https://user-images.githubusercontent.com/502770/178008443-27a09056-84e3-4a6c-a3d9-ef8b0ac12f78.mp4

**Comment by b-cooper** [comment]
Closed by #11065
