### ISSUE TITLE
6.0 Feedback:  LPC labware name should wrap to 2 lines, not run into the next column of data

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#11062]
### Overview

current state:
if a labware name is long, it runs into the next column of text.
<img width="1001" alt="Screen Shot 2022-07-08 at 1 59 31 PM" src="https://user-images.githubusercontent.com/4339860/178046733-6122f51d-e06a-4bec-87b0-da778d226563.png">

expected behavior:
the labware name should wrap to 2 lines and truncate if longer than 2 lines

**Comment by bndo** [comment]
Closed via associated PR

**Comment by nusrat813** [comment]
Verified in beta.2 ![Screen Shot 2022-07-12 at 1.31.49 PM.png](https://ima![Screen Shot 2022-07-12 at 1.32.10 PM.png](https://images.zenhubusercontent.com/5e2720c7aaf6ad22b4062408/ec6c4490-0c85-45b3-8d4d-fcf9c767460b)ges.zenhubusercontent.com/5e2720c7aaf6ad22b4062408/1e40ee83-4746-47f5-9b10-6df48cef26da)
