### ISSUE TITLE
6.0 Feedback:  Overall Design QA

### ISSUE THREAD

**Issue by mmencarelli** [Opentrons/opentrons#11076]
### Overview

must-address feedback for 6.0

### Current Behavior

**T1 Protocols Page**
- [x] (1) Missing hover state on protocol card
- [x] (2) Fix spacing issue on the card. Please refer to original designs. 
- [x] (3) Fix spacing on open menu

<img width="954" alt="Screen Shot 2022-07-11 at 2 34 40 PM" src="https://user-images.githubusercontent.com/54682054/178334196-c6e09af9-e95d-42e6-acd9-cfad1d2d140a.png">

**app-wide**
- [x] (1) Navigation hover has been fixed on edge, push this to 6.0. Basically the hover colour is off, shouldn't be grey. 
- [x] (2) Can we close the menu on click? [Loom showing current state] This is on a lot of the buttons. (https://www.loom.com/share/42e678efaf204b8a83f79f54b0ba557e) - This is fixed everywhere except the Robot Settings Calibration which will be fixed by my PR: https://github.com/Opentrons/opentrons/pull/11020

<img width="110" alt="Screen Shot 2022-07-11 at 2 35 06 PM" src="https://user-images.githubusercontent.com/54682054/178334233-24608367-7091-41ab-a812-c9d6640b556b.png">

**T1 Labware Page**
- [x] (1) Get open menu in appropriate position (not cutting off screen)
- [x] (2) Add hover state to the card
- [x] (3) If the copy button has no interactivity to inform the user they've copied the line, then we should nix this button entirely
- [x] (4) Wrap text so users don't see this
<img width="992" alt="Screen Shot 2022-07-11 at 2 35 55 PM" src="https://user-images.githubusercontent.com/54682054/178334403-12768d42-728d-45eb-9bb8-6c7c92a5248a.png">
<img width="592" alt="Screen Shot 2022-07-11 at 2 36 00 PM" src="https://user-images.githubusercontent.com/54682054/178334429-2b73e6a5-6acc-4313-89bf-b1f382cf8d75.png">

**T2 Devices**
- [x] (1) Users shouldn't see an empty space
<img width="927" alt="Screen Shot 2022-07-11 at 2 36 36 PM" src="https://user-images.githubusercontent.com/54682054/178334500-3993ddde-fca9-44f9-a534-28c4c0335af1.png">

**T3 Robot Settings + T1 App Settings**
- [x] (1) Can we bump up the size of the toggles that are smaller to match the larger grey one? 
<img width="942" alt="Screen Shot 2022-07-11 at 2 37 20 PM" src="https://user-images.githubusercontent.com/54682054/178334617-a44449c1-2b22-4d20-8cba-41a920492e43.png">

**T4 Protocol Run**
- [x] (1) Update the hover state on this button. shouldn't go to blue 
- [x] (2) This shouldn't happen! 

<img width="946" alt="Screen Shot 2022-07-11 at 2 37 46 PM" src="https://user-images.githubusercontent.com/54682054/178334708-62cf4c76-d206-4628-ab44-1ac8032a7f66.png">
<img width="940" alt="Screen Shot 2022-07-11 at 2 37 50 PM" src="https://user-images.githubusercontent.com/54682054/178334711-49c0d3c7-4ebd-42e8-a624-5e5c3777c013.png">

**Comment by bndo** [comment]
Closed with #11081 merge
