### ISSUE TITLE
6.0 Feedback:  inconsistent  warnings for H/S module

### ISSUE THREAD

**Issue by rwarshauer** [Opentrons/opentrons#11079]
### Overview

Warnings aren't shown in all similar places

### Current Behavior

In test shake the hot module warning is not showing

### Expected Behavior

Matchs with warnings 

### Steps To Reproduce

1. Open App
2. Go to device with H/S
3. Set temp to 50
4. Go t test shak
![Screen Shot 2022-07-11 at 3 17 50 PM](https://user-images.githubusercontent.com/106115893/178341659-fc4ab3ef-4258-4a31-8030-49e17a29bb2d.png)
e

### Operating system

Mac

**Comment by jerader** [comment]
Closing this because the updated designs remove the Module Card portion of the H-S slideout all together
