### ISSUE TITLE
heater-shaker: implement timed shaking in PAPIv2

### ISSUE THREAD

**Issue by sanni-t** [Opentrons/opentrons#11087]
As a heater-shaker user, I'd like to have my h/s shake in the background for a set duration of time and stop automatically after the set amount of time.

# Design

Implement a `start_timed_shake` (name TBD) command that takes `seconds` and `minutes` as its arguments. This command should send a shake command to the module and start a background task that monitors time. At the end of the set time, the command should send a stop shake command to the module. 

Implement a mechanism to inform a protocol that a timed shake has ended so that it can perform steps that require an idle shaker. This can be implemented in two ways:

1. Using a context manager:
So a timed shake in a protocol will look like this-
```
with heater_shaker.timed_shake(rpm=123, duration=234):
  # Pipetting while shaking
  p20.aspirate(20, non_heater_shaker_labware)
  p20.dispense(20, some_other_labware)

# Pipetting that requires a deactivated shaker
p20.aspirate(20, heater_shaker_labware)
p20.dispence(20, some_other_labware)

```

2. Using 2 separate commands:

```
heater_shaker.start_timed_shake(rpm=123, duration=234)
# Pipetting while shaking
p20.aspirate(20, non_heater_shaker_labware)
p20.dispense(20, some_other_labware)

heater_shaker.verify_stopped()    # Strictly required gating command

# Pipetting that requires a deactivated shaker
p20.aspirate(20, heater_shaker_labware)
p20.dispence(20, some_other_labware)
```

# Implementation requirements:

- The protocol context state should get updated to reflect the end of shake
- Users should not be able to send another shake command while timed shake is happening
- The background task should be cancelled upon a protocol cancel
- The task should not pause when protocol is paused (TODO: confirm this w/ product. In absence of an emergency stop button and mid-protocol stateless commands, we will need to think about whether to pause the movement when protocol is paused)

**Comment by SyntaxColoring** [comment]
Closing this as "won't do", as part of general ticket cleanup.

As far as I know, there hasn't been a pressing need for this. `ProtocolContext.delay()` has been good enough.
