### ISSUE TITLE
heater-shaker: implement timed shaking in protocol engine

### ISSUE THREAD

**Issue by sanni-t** [Opentrons/opentrons#11089]
This ticket tracks engine-side implementation of timed shaking described in #11087.

As a protocol engine user, I'd like to have my h/s shake in the background for a set duration of time and stop automatically after the set amount of time.

# Design

Implement a `startTimedShake` (name TBD) command that takes `seconds` and `minutes` as its parameters. This command should send a shake command to the module and start a background task that monitors time. At the end of the set time, the command should send a stop shake command to the module. 

# For discussion

In order for gating commands that will require a stopped shaker, we could either implement a separate `verifyStopped` command that is similar to option#2 in the PAPIv2 ticket or require PD & other PE users to monitor the state of the heater-shaker via `/modules`.

If we decide to go with option#2 for PAPIv2 then it'd be easy to pick the same technique for PE. But if we want to implement a context manager for PAPIv2, then there's no obvious counter-part for PE. 

# Implementation requirements:

- The protocol engine state should get updated to reflect the end of shake
- Users should not be able to send another shake command while timed shake is happening
- The background task should be cancelled upon a protocol cancel
- The task should not pause when protocol is paused (TODO: confirm this w/ product. In absence of an emergency stop button and mid-protocol stateless commands, we will need to think about whether to pause the movement when protocol is paused)

**Comment by SyntaxColoring** [comment]
Closing as "won't do." See https://github.com/Opentrons/opentrons/issues/11087#issuecomment-1954869239.
