### ISSUE TITLE
6.0 Feedback:  All three modules that heat have different wording to stop heating element

### ISSUE THREAD

**Issue by rwarshauer** [Opentrons/opentrons#11080]
### Overview

There are three different wordings on the temp modules to stop heating

### Current Behavior

All wording is different

### Expected Behavior

Since they do the same thing match the wording

### Steps To Reproduce

1. Open App
2. Go to devices
3. Set temp on thermocyler
4. Set temp on H/S
5. Set temp on Temp deck
6. Stop heating on all of the
![Screen Shot 2022-07-11 at 3 29 45 PM](https://user-images.githubusercontent.com/106115893/178344025-b6b4e9e0-6704-499c-ba27-9470acb0c4ba.png)
![Screen Shot 2022-07-11 at 3 29 50 PM](https://user-images.githubusercontent.com/106115893/178344027-7abd2c2c-74d3-4505-94fe-73340307e694.png)
![Screen Shot 2022-07-11 at 3 30 00 PM](https://user-images.githubusercontent.com/106115893/178344029-d59b8120-c600-4c29-adc8-f85fb4bbcbbf.png)
m

### Operating system

Mac

**Comment by emilywools** [comment]
good eye Rob!!

**Comment by anthonywilleee** [comment]
@rwarshauer these modules actually do different things. both temp & thermocycler modules have active cooling, while the h-s does not. in addition, the TC has both block and lid. recommend no changes

**Comment by anthonywilleee** [comment]
@rwarshauer for the temp, "deactivate module" might stop cooling as well, so "deactivate heater" would be inaccurate

**Comment by rwarshauer** [comment]
Gotcha!

**Comment by jerader** [comment]
I think this ticket might be resolved now since https://github.com/Opentrons/opentrons/pull/11132 merged. Right now: Heater-shaker says `Deactivate heater`, temp says: `Deactivate module`, and TC says `Deactivate lid` and `Deactivate block` Is that correct?
