### ISSUE TITLE
Update H-S Advanced settings headline copy

### ISSUE THREAD

**Issue by anthonywilleee** [Opentrons/opentrons#11083]
# Overview

Changing headline for H-S attachment modal settings to be more descriptive

# Implementation Details
- Update the headline on H-S attachment modal settings to read "Confirm Heater-Shaker is attached before using it"
- Setting lives in Advanced settings and defaults to ON

# Design links
- https://www.figma.com/file/695ogls23YsQYImRcGYDE1/Heater-Shaker?node-id=5690%3A93333

# Acceptance Criteria
- Headline in H-S attachment modal settings displays: "Confirm Heater-Shaker is attached before using it"

**Comment by sakibh** [comment]
Closing this ticket. It was decided to not change the copy.
