### ISSUE TITLE
6.0 Feedback: Make Deck Setup Expand to Full-Screen Modal when clicked

### ISSUE THREAD

**Issue by DerekMaggio** [Opentrons/opentrons#11092]
### Overview

Currently when you upload a protocol it provides a picture of the deck setup. This picture is quite small and even on my 32" monitor a little hard to tell what each piece is. 

### Current Behavior

Currently there is not way to make the picture bigger
![image (9)](https://user-images.githubusercontent.com/20705756/178519694-611e88e6-104c-4000-9330-1313a4ba939f.png)

### Expected Behavior

If you click on the picture it should open up a modal that expands to the size of the Opentrons App so you can see the whole deck overview in greater detail. 

Having an clickable _Expand_ button in the title bar might be nice too

### Operating system

Linux

**Comment by koji** [comment]
The OT-3 Desktop app will have this functionality and the ticket on Jira.
