### ISSUE TITLE
6.0 Feedback:  Cancel button present on view protocol run record

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#11095]
### Overview

When I view a protocol run record the `Cancel run` button is present
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/502770/178534218-d66876b3-1afa-45b8-b5f6-7b5cd6c3eafe.png">

https://user-images.githubusercontent.com/502770/178534288-cf3c819b-eb34-409a-a0d8-be8dfd4eefaa.mp4

### Current Behavior

Cancel Run button present when viewing a historical run

### Expected Behavior

Cancel run button only present when a run may be cancelled.

### Steps To Reproduce

Run a protocol and then view its run record.

### Operating system

Mac

**Comment by bndo** [comment]
Closed by #11081

**Comment by nusrat813** [comment]
Verified in beta.3 

[Uploading... Screen Shot 2022-07-14 at 11.33.18 AM.png]
