### ISSUE TITLE
6.0 Feedback:  Protocol run record start and end times not shown

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#11109]
### Overview

For this protocol start and end times are not shown for any step.
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/502770/178586026-fc8451ec-b8b2-493e-9331-babbbf124bd2.png">

### API run responses
[responses.log](https://github.com/Opentrons/opentrons/files/9096507/responses.log)

### App protocol folder 

> **Hunch** Maybe this is happening because there are 2 local analyses?  The first analysis fails because the custom labware file is not imported yet.  This is a part of the smoke test on purpose to use the reanalyze feature.

[dbc62979-b87e-4790-9bc6-d8eaba722457.zip](https://github.com/Opentrons/opentrons/files/9096516/dbc62979-b87e-4790-9bc6-d8eaba722457.zip)

**Comment by nusrat813** [comment]
@b-cooper - to investigate

**Comment by y3rsh** [comment]
### The run log download
[kansas_16e1af36-159a-4c54-96d7-9e49b94d6df2_2022-07-12T13_40_54.874Z.json.zip](https://github.com/Opentrons/opentrons/files/9096969/kansas_16e1af36-159a-4c54-96d7-9e49b94d6df2_2022-07-12T13_40_54.874Z.json.zip)

**Comment by b-cooper** [comment]
Closed by #11114
