### ISSUE TITLE
6.0 Feedback:  Text in labware offset is not consistent in aligning 

### ISSUE THREAD

**Issue by rwarshauer** [Opentrons/opentrons#11108]
### Overview

Labware offset was fixed in 10942, but the text alignment is no longer consistent

### Current Behavior

Some deck slots text is aligned right and others its left

### Expected Behavior

Matching alignment (Presumably left) on all slots

### Steps To Reproduce

On the protocol setup page complete LPC and then see the deckmap has the offsets but they all look a little off.
![Screen Shot 2022-07-12 at 1 58 03 PM](https://user-images.githubusercontent.com/106115893/178579102-ab276836-c501-445b-9d14-849d32f0c834.png)

### Operating system

Mac

**Comment by nusrat813** [comment]
@b-cooper to investigate

**Comment by nusrat813** [comment]
Verified in beta.3 

![image (5).png](https://images.zenhubusercontent.com/5e2720c7aaf6ad22b4062408/070e7ac4-ab10-4767-8194-92ad3b510191)
