### ISSUE TITLE
6.0 Feedback:  Updating robot from file silently fails when there is an active run

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#11105]
### Overview

```gherkin
Given I have a current run
When I browse filesystem to manually update my robot I pick a file
Then nothing happens
```
The app is correctly blocking the process but no feedback is given to the user.
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/502770/178574595-3821d938-b781-4e0f-a11b-f44794bbb532.png">

### Current Behavior

Silent failure

### Expected Behavior

Cannot even click `Browse file system`

**Comment by koji** [comment]
@y3rsh when the app detects `run`, this page shows `Banner` under the page title.
You couldn't see the Banner when you tried this?

**Comment by y3rsh** [comment]
The banner is not there when I first go to the page, it seemed to show up after I clicked the button.
https://user-images.githubusercontent.com/502770/178599413-02a7ab07-48fa-40d8-bf92-a5bc7edfc548.mp4

**Comment by y3rsh** [comment]
> Once you un-current the run, you must reload this app settings page (navigate away and back) before the process will work.

Investigated this as a separate issue.  I experienced this on the first time because I un-currented the run from a different app connected to the same robot.  If you un-current in the same app this would force the page to be re-loaded because you have to navigate away and then back to un-current.

I do not know we would consider this a bug or not.

https://user-images.githubusercontent.com/502770/178602044-874daf8f-6718-43d6-a21c-7dd0d581b1d7.mp4

**Comment by nusrat813** [comment]
Verified in beta.3 

![Screen Shot 2022-07-14 at 11.36.49 AM.png](https://images.zenhubusercontent.com/5e2720c7aaf6ad22b4062408/a53304f6-4de4-4c6b-bb09-c2c9d2827017)
