### ISSUE TITLE
6.0 Feedback:  Device detail: module card display issue when all module cards have update firmware banner

### ISSUE THREAD

**Issue by y3rsh** [Opentrons/opentrons#11120]
### Overview

```gherkin
Given you force the robot server into a state where all modules need a firmware update
And you setup the robot with > 2 modules
When you view the device details page for that robot
Then one of the module cards is cut off and may not be interacted with even with resizing the app
```

> This issue is low severity because it only happens when at least 3 modules have the update firmware banner.  This **does** expose risk though.  Explicit permutation testing of pipettes/modules/order/banners/errors to exercise layout is not done on this page.

### Behavior

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/502770/178789350-92df83fc-d733-4ddf-863e-b56132ca6239.png">

https://user-images.githubusercontent.com/502770/178793910-f7e3e86b-174c-4d2e-b803-26c0b17afda8.mp4

### Steps To Reproduce

- replace robot-server/simulators/test.json with the below

```js
{
  "attached_instruments": {
    "right": {
      "model": "p300_single_v1",
      "id": "321",
      "max_volume": 300,
      "name": "p300_single",
      "tip_length": 0,
      "channels": 1
    },
    "left": {
      "model": "p10_single_v1",
      "id": "123",
      "max_volume": 10,
      "name": "p10_single",
      "tip_length": 0,
      "channels": 1
    }
  },
  "attached_modules": {
    "thermocycler": [
      {
        "function_name": "set_temperature",
        "kwargs": {
          "temperature": 3,
          "hold_time_seconds": 1,
          "hold_time_minutes": 2,
          "ramp_rate": 4,
          "volume": 5
        }
      },
      {
        "function_name": "set_lid_temperature",
        "kwargs": {
          "temperature": 4
        }
      }
    ],
    "magdeck": [
      {
        "function_name": "engage",
        "kwargs": {
          "height": 4
        }
      }
    ],
    "tempdeck": [
      {
        "function_name": "set_temperature",
        "kwargs": {
          "celsius": 26
        }
      }
    ]
  }
}
```
- above line 123 in `robot-server/robot_server/modules/module_data_mapper.py` add
```python
has_available_update = False
# if ModuleType.THERMOCYCLER == module_type:
#    has_available_update = True
```

https://github.com/Opentrons/opentrons/blob/bec8e23b9dfc4d29c88d5b5de73dd315a0c00885/robot-server/robot_server/modules/module_data_mapper.py#L123-L138

- `make -C robot-server dev`
- navigate to device details in the app of the dev robot (must add connecting to localhost)

### Operating system

Mac

**Comment by koji** [comment]
The display issue comes from the current height settings with media queries.
- need to consider Banner height
- avoid hardcoding as much as possible
