### ISSUE TITLE
Fleet Management: Automatically Update Firmware

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1115]
As a user, I would like firmware updates to be included in my robot updates, so that I can get the latest firmware builds whenever I update my robot.

## Acceptance Criteria
- Make firmware update an automatic part of robot update

**Comment by btmorr** [comment]
`/server/update_firmware` endpoint is already in place, so I don't believe there's any BE work outstanding for this ticket

**Comment by umbhau** [comment]
As per @btmorr  - will bundle into BE (include in wheel)
