### ISSUE TITLE
Fleet Management: Robot Pulls Updates from Resin

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1116]
As a user, I would like for my robot to pull updates from Resin whenever possible, so that I don't have to rely on Opentrons updating my robot (at potentially inconvenient times)

## Acceptance Criteria
- Robot update should check if wifi is available
- If wifi is available, API should check for latest resin commit and pull if available

## Notes
- This allows users to pull docker container updates when they update their robots, so that we don't have to push updates to robots (and restart them at potentially inconvenient times).
- To disable rolling update (dangerous), see https://github.com/resin-io-playground/staged-releases/blob/master/disable-rolling-release-on-fleet.sh
- To set a robot to a particular commit from Resin, see https://github.com/resin-io-playground/staged-releases/blob/master/set-device-to-a-build.sh

**Comment by btmorr** [comment]
We're going to handle/avoid Resin update through different means
