### ISSUE TITLE
Fleet Management: Firmware Version in Run App

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1118]
As a run app user, I would like to be able to see my robot's firmware and container versions, so that I can decide whether to update.

## Acceptance Criteria
- [x] Add firmware version to App's Robot Settings page Information card
- ~Add firmware version  to App's Robot Settings page update modal~
- ~Add container version to App's Robot Settings page Information card~
- ~Add container version  to App's Robot Settings page update modal~

## Implementation Notes

- Actual update can be 'dumb' and doesn't need to change - API will decide whether to automatically container, which it will only do if it is on wifi (so it can access resin) and there is an update available.
- Dependent on #1117 

## Design

- [ ] @pantslakz to provide updated copy for robot update modal

---

Edit: Removed "Container Version" specs because that aspect needs more thought from API side of things

Edit2: Removed "Firmware version in update modal" spec because, after discussion with @pantslakz, it was deemed too confusing to the user

**Comment by mcous** [comment]
Additional acceptance criteria removed, meaning this ticket was adequately addressed by #1633
