### ISSUE TITLE
Fleet Management: Move Persistent Storage to USB Drive

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1119]
As a fleet manager, I would like to be able to move robots between apps without losing data in persistent storage.

## Acceptance Criteria
- Move persistent storage from inside docker container to the USB thumb drive.

## Notes
- Moving robots between resin apps completely replaces the docker container, so we lose any data it containers.
- This builds on PR1101, which moves data from environment variables to persistent storage.

**Comment by btmorr** [comment]
Not sure exactly when it was done, but this has been in for quite some time
