### ISSUE TITLE
App [Housekeeping] add test to pages/Protocols

### ISSUE THREAD

**Issue by koji** [Opentrons/opentrons#11219]
Currently, components in`pages/Protocols` are missing test cases.

- [x] add test cases for `ProtocolList`
- [x] add test cases for [ProtocolsLanding](https://github.com/Opentrons/opentrons/tree/edge/app/src/pages/Protocols/ProtocolsLanding)

**Comment by jerader** [comment]
Looks like `ProtocolDetails` already has a test file (`app/src/organisms/ProtocolDetails/__tests__/ProtocolDetails.test.tsx`). But `ProtocolList` doesn't, so I will add that.
