### ISSUE TITLE
bug: When a command fails during Labware Position Check, the error dialog is formatted wrongly and goes away on its own

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#11226]
# Overview

The Opentrons App seems to be mishandling Protocol Engine command errors raised during Labware Position Check.

# Steps to reproduce

1. Start a run on a robot and start Labware Position Check.
2. Wait for Labware Position Check to encounter a robot-side Protocol Engine command failure.
    * For example, on v6.0.0, it will probably error when it tries to move to a labware atop a Heater-Shaker, because of bug #11125.

# Current behavior

* The app displays a dialog with the literal text `error_modal_text`.
* The dialog goes away on its own after a second or two, without you selecting its close button.

<img width="852" alt="Screen Shot 2022-07-19 at 2 41 47 PM" src="https://user-images.githubusercontent.com/5837799/179998356-a49033d1-2d80-4f82-b568-8b4aa5d2454f.png">

# Expected behavior

* The dialog should have a message that's meaningful to users, instead of the literal string `error_modal_text`.
* The dialog should only go away when it's been closed.
* We might also consider moving the `movement command id abc123...` part to the app's debugging logs, or to a "developer details" dropdown menu within the dialog. It seems like technobabble.

**Comment by ecormany** [comment]
Some possibilities for what `error_modal_text` should say:
- "The robot could not perform a required movement step."
- "A movement command to the robot failed."

As a user, I'd also like a title more specific than "Something went wrong" (might as well just say "Error"). If this is an LPC-specific dialog it could say "Labware Position Check failed" or "Labware Position Check stopped".
