### ISSUE TITLE
App run log: support JSON v6 commands

### ISSUE THREAD

**Issue by shlokamin** [Opentrons/opentrons#11228]
# Overview

Now that JSON v6 commands are first class citizens (both in analysis and as run commands), we need our run log to parse them and display them properly. 

Previously, we were relying on  the `legacyCommandText` we got back from the server to hold the text to render in the run log, but now we'll have to parse he actual command and format the string ourselves.

# Implementation details
 
See `app/src/organisms/Devices/ProtocolRun/StepText.tsx` and implement cases for following commands:
- `magneticModule/engage` -> should map to text "Engaging Magnetic Module"
- `magneticModule/disengage` -> should map to text: "Disengaging Magnetic Module"
- `temperatureModule/setTargetTemperature` -> should map to text "Setting Temperature Module temperature to {temp} °C (rounded off to nearest integer)"
- `temperatureModule/deactivate` -> should map to text "Deactivating Temperature Module"
- `temperatureModule/waitForTemperature` ->  should map to text  "Waiting for Temperature Module to reach temperature {temp} °C (rounded off to nearest integer)"
- `thermocycler/setTargetBlockTemperature` -> should map to text "Setting Thermocycler well block temperature to {temp} °C with a hold time of {seconds} seconds"

- `thermocycler/setTargetLidTemperature` -> should map to text "Setting Thermocycler lid temperature to {temp} °C"
- `thermocycler/waitForBlockTemperature` -> should map to text "Waiting for Thermocycler block to reach target temperature"
- `thermocycler/waitForLidTemperature` -> should map to text "Waiting for Thermocycler lid to reach target temperature"
- `thermocycler/openLid` -> should map to text "Opening Thermocycler lid"
- `thermocycler/closeLid` -> should map to text "Closing Thermocycler lid"
- `thermocycler/deactivateBlock` -> should map to text "Deactivating Thermocycler block"
- `thermocycler/deactivateLid` -> should map to text "Deactivating Thermocycler lid"
- `thermocycler/runProfile` -> should map to text "Thermocycler starting {repetitions} repetitions of cycle composed of the following steps: {steps}"
- `thermocycler/awaitProfileComplete` -> should map to text "Waiting for Thermocycler profile to complete"
- `heaterShaker/setTargetTemperature` -> should map to text "Setting Target Temperature of Heater-Shaker to {{temp}}°C"
- `heaterShaker/waitForTemperature` -> should map to text "Waiting for Heater-Shaker to reach target temperature"
- `heaterShaker/setAndWaitForShakeSpeed` -> should map to text "Setting Heater-Shaker to shake at {{rpm}} rpm and waiting until reached"
- `heaterShaker/deactivateHeater` -> should map to text "Deactivating Heater-Shaker Heater"
- `heaterShaker/openLabwareLatch` -> should map to text "Unlatching labware on Heater-Shaker"
- `heaterShaker/closeLabwareLatch` -> should map to text "Latching labware on Heater-Shaker"
- `heaterShaker/deactivateShaker` -> should map to text "Deactivating Heater-Shaker Shaker"
- `waitForDuration` -> should map to text "Pause for {{seconds}} seconds"

# Acceptance criteria

Magnetic module commands render text above in run log

**Comment by ecormany** [comment]
- `temperatureModule/waitForTemperature` -> could be shortened to "Waiting for Temperature Module to reach ~~temperature~~ {temp} °C (rounded ~~off~~ to nearest integer)"
    - and {temp} should actually be rounded in display! currently it will say something like `50.0 °C (rounded…` 🙃 
- should `thermocycler/waitForBlockTemperature`, `thermocycler/waitForLidTemperature`, and `heaterShaker/waitForTemperature` list what the target {temp} is? or can they not because they don't take an argument?
- `thermocycler/setTargetBlockTemperature` ->  "Setting Thermocycler ~~well~~ block temperature to {temp} °C with a hold time of {seconds} seconds" (to match wording in other TC block actions)
- `heaterShaker/deactivateHeater` -> should map to text "Deactivating ~~Heater-Shaker~~ Heater"
- `heaterShaker/deactivateShaker` -> should map to text "Deactivating ~~Heater-Shaker~~ Shaker"

**Comment by jerader** [comment]
> * should `thermocycler/waitForBlockTemperature`, `thermocycler/waitForLidTemperature`, and `heaterShaker/waitForTemperature` list what the target {temp} is? or can they not because they don't take an argument?

@ecormany yup, I do have access to what the target temp is

**Comment by ecormany** [comment]
No problem, write the best text with what you have, this shouldn't have to be a big data pipeline refactor.
