### ISSUE TITLE
bug: SSH labware calibration offset varied application

### ISSUE THREAD

**Issue by caroline-wyzer** [Opentrons/opentrons#11255]
### Overview

We're attempting to automate running programs through SSH. The labware calibration is being applied differently when we call the run in one line vs in multiple lines. We can't figure out how to apply the correct calibration while calling SSH through only one line. 
I can tell that these programs are being run in a different way, because when it's run through multiple lines (or through Jupyter Notebook), print statements appear as the program is being run. When it's run through one line, though, print statements don't appear until the end. 

### Steps to reproduce

SSH code that causes correct calibration: 

     -ssh -i C:\users\carol\ot2_ssh_key root@169.254.137.167 

     (OPENTRONS LOGO APPEARS) 

     cd /var/lib/jupyter/notebooks 
     python3 384_calibration_test.py 

SSH code that causes incorrect calibration: 

     -ssh -i C:\users\carol\ot2_ssh_key root@169.254.137.167  cd /var/lib/jupyter/notebooks; python3 384_calibration_test.py 

Code being called: 

     import os, sys

     sys.path.append("/var/lib/jupyter/notebooks")
     from Labware_Calibration import tiprack_multi as tiprack_multi_calibration

     from opentrons import protocol_api
     import opentrons.execute
     import json

     #lines below suppress all output because get_protocol_api does an unnecessary error message 
     (https://github.com/Opentrons/opentrons/issues/7248)
     sys.stdout = open(os.devnull, "w")
     sys.stderr = open(os.devnull, "w")
     #connects to robot 
     protocol = opentrons.execute.get_protocol_api(opentrons.protocol_api.MAX_SUPPORTED_VERSION)
     #lines below undo the lines above that suppressed all output
     sys.stdout = sys.__stdout__
     sys.stderr = sys.__stderr__

     def run(protocol: protocol_api.ProtocolContext):
    
         print("running correct program")
         protocol.home()

         tipracks = []
         os.chdir("/var/lib/jupyter/notebooks/")
       
         tipracks.append(protocol.load_labware("opentrons_96_tiprack_20ul", 1))

         #load pipettes
         pip2 = protocol.load_instrument('p20_multi_gen2', "left", tip_racks = tipracks)
   

         for t in tipracks:
             t.set_offset((tiprack_multi_calibration[0]),(tiprack_multi_calibration[1]),(tiprack_multi_calibration[2]))
         pip2.pick_up_tip()

         pip2.return_tip()
         pip2.reset_tipracks()
    
    
    
     try:
         print("here")
         run(protocol)
         protocol.home()
     except KeyboardInterrupt:
         print(" user stopped program!")
         protocol.home()
         for i in protocol.loaded_instruments.values():
             if i.has_tip:
                 i.drop_tip()
     except Exception as e:
         traceback.print_exc()
         protocol.home()
         for i in protocol.loaded_instruments.values():
             if i.has_tip:
                 i.drop_tip()

The Labware Calibration File referenced is a simple python script located in /var/lib/jupyter/notebooks, and it contains labware offset definitions for the robot it's being run on:

     tiprack_multi = (1.00, 3.50, 0.00) 

### Current behavior

When run through a Jupyter Notebook terminal or SSH in multiple lines, the robot picks up the tips without error. Print statements appear throughout the run. When run through a single line to SSH, the robot calibration is off by several mm, and print statements appear only after the run is complete. However, the data from the Labware_Calibration.py file is still being accessed and applied, because if you change those values, the calibration shifts in both instances. It's like there's another layer of calibration data being applied from somewhere else? 

We've also tried using both Opentrons_execute and python3 in the SSH call, and it doesn't seem to change anything. 

### Operating system

Windows

### System and robot setup or anything else?

USB, app version 6.0

**Comment by mcous** [comment]
When you run an SSH command in one line like this...

```shell
ssh root@my_ot2.local "some command"
```

...the machine will simply run the command rather than launching a full interactive shell, as would happen if SSH'd in and _then_ executed the command yourself.

When an interactive shell is launched, certain environment variables are configured that ensure the software functions properly. If you run the command directly in one line, those environment variables will _not_ be set, which will result in the robot software not being able to properly read configuration data. 

If you would like to execute a command in one line over SSH, you should ensure you are running in a login shell using `sh -l`:

```shell
ssh root@my_ot2.local "sh -l \"some command\""
```

**Comment by caroline-wyzer** [comment]
Thank you!
