### ISSUE TITLE
Calibration: Calibrate Labware with Assigned Pipettes

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1128]
As a robot user, I would like to calibrate tipracks used by single channel pipettes last, so that all labware gets calibrated by the single channel pipette.

## Acceptance Criteria
- [ ] All tipracks used by single-channel pipettes should appear after tipracks used by multi-channel pipettes in the trip rack calibration list.
- [ ] By default, tipracks used by single-channel pipettes should be calibrated after tipracks used by multi-channel pipettes.

## Implementation Notes
- Order of calibration of multiple single-channel tipracks does not matter
- Note user can still override order by clicking on tipracks manually. This is okay for now.
- Note this whole story is to avoid scenarios in which the multi-channel gets used to calibrate incompatible labware (like tube racks). Whichever pipette is calibrated to tipracks last is used by default to calibrate labware.
- Note we may eventually do something smarter, like allowing user to decide which pipette to use to calibrate each labware (or calibrating labware with both pipettes when applicable)

**Comment by pantslakz** [comment]
@umbhau is this the same as https://github.com/Opentrons/opentrons/issues/1264 ?

**Comment by umbhau** [comment]
@pantslakz Yes, thanks for the catch! Closed #1264 and migrated details over here.

**Comment by umbhau** [comment]
@mcous good questions on a very ambiguous user story. see updates above.
