### ISSUE TITLE
bug: Help button in Protocol Designer points to Salesforce login

### ISSUE THREAD

**Issue by hartm9** [Opentrons/opentrons#11329]
### Overview

When I click on the Help button in [Protocol Designer](https://designer.opentrons.com/), it opens a page that prompts for a Salesforce login.  It should point to [this link](https://support.opentrons.com/s/protocol-designer) instead.

### Steps to reproduce

Click on the Help button in [Protocol Designer](https://designer.opentrons.com/)

### Current behavior

Opens a page requiring a password, which is incorrect.

### Expected behavior

The Protocol Designer help collection page should open

### Operating system

Windows

### System and robot setup or anything else?

Chrome browser, for what it's worth

**Comment by bndo** [comment]
Closing this in favor of RAUT-136
