### ISSUE TITLE
Unable to connect to robot after disconnecting while paused

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1141]
Unable to connect to robot or load protocol if incorrectly disconnected during run (e.g. while paused)

## Expected Behavior
- User should be able to connect to a robot and resume robot use, even if improperly disconnected
--> Note this may require a user story to prompt user to restart robot.

## Observed Behavior
- User unable to connect to robot or resume use if improperly disconnected during a run

## Steps to Recreate
1. Connect to robot (observed on multiple robots, including divine-night)
2. Open any run app and load and run (any) protocol
3. Pause protocol
4. Physically disconnect from robot or close app
5. Attempt to reconnect to robot
6. Observe that you cannot load a new protocol, even from a separate computer

Reported by @Laura-Danielle

**Comment by mcous** [comment]
Unable to reproduce on `3.1.1`. If there was a bug was present, it appears to have been fixed
