### ISSUE TITLE
Labware: Update Labware Definitions

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1144]
As a robot user, I would like my robot to have labware definitions that match manufacturer's specs, so that my robot can accurately hit labware without substantial calibration.

## Acceptance Criteria
- Add or correct labware definitions for the labware listed below
- Labware definitions should be taken from the spreadsheet listed below

## Labware
- [List of labware](https://docs.google.com/spreadsheets/d/1sbOMbBnn0QFs4J44gIbkitPoEo8gW7d7Nz9nd-5J0EU/edit#gid=0)
Labware to update 
- GEB Tiprack 300uL
- 96-flat
- 96-deep-well
- Trough-12row (? - double check this definition)

**Comment by btmorr** [comment]
Rerun the migration script that was used to create the new base labware definitions and compare the results to the old values. Then use the new definitions on a robot and compare the behavior. For the labware definitions that were updated, default calibrations should be correct (or closer to correct)

**Comment by emernic** [comment]
Are the old designs for tube racks shown here: [https://github.com/Opentrons/otone_hardware/tree/master/models](https://github.com/Opentrons/otone_hardware/tree/master/models) still accurate? Or are there new designs coming out soon? I am about to cut some acrylic for various tube racks.

**Comment by umbhau** [comment]
@btmorr I believe this is done -- could you confirm?

**Comment by btmorr** [comment]
Closing in favor of prioritizing new labware system
