### ISSUE TITLE
bug: cannot install api client with npm

### ISSUE THREAD

**Issue by rickwierenga** [Opentrons/opentrons#11483]
### Overview

```
npm install @opentrons/api-client
```

as described [here](https://github.com/Opentrons/opentrons/tree/edge/api-client) does not work.

### Steps to reproduce

see above

### Current behavior

```
$ npm install @opentrons/api-client
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@opentrons%2fapi-client - Not found
npm ERR! 404 
npm ERR! 404  '@opentrons/api-client@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

### Operating system

Mac

### System and robot setup or anything else?

latest

**Comment by koji** [comment]
@rickwierenga 
Actually, we don't register `@opentrons/api-client` on npm.
The only way to install `@opentrons/api-client` is to clone this repo and build `api-client` and run `npm install` or `yarn add` to install the package to your project.
