### ISSUE TITLE
PD Deck Setup: Well Selection Modal

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1179]
As a protocol designer, I'd like to be able to select wells for a particular step in my protocol.

## Acceptance Criteria
- [ ] User can open up well selection modal from protocol step editor
- [ ] Well selection modal displays pipette used for step
- [ ] Well selection modal displays ingredients available at the start of the step
- [ ] User can click 'save wells' to save wells to step

## Related
- User can click and drag to select wells 
-- See PD Deck Setup: Well Selection Interaction #1186
-- See PD Deck Setup: Well Selection - Selected Well Styling #1187

- Well labels turn blue during hover/selection
-- See PD Deck Setup: Well Selection - Well labels restyling #1196

## Design
- Zeplin > PD screens > Well Selection
![image](https://user-images.githubusercontent.com/35570080/38695657-e4a6270c-3e5a-11e8-8e34-589cf366004a.png)

**Comment by IanLondon** [comment]
ALSO:

- [ ] Well selection text field isn't really a text field, it's just a clickable thing that opens the modal, and shows the number of wells.
