### ISSUE TITLE
feat: Unpin requirements

### ISSUE THREAD

**Issue by ecederstrand** [Opentrons/opentrons#11905]
### Overview

https://github.com/Opentrons/opentrons/blob/edge/api/setup.py pins a handful of Python package dependencies, e.g. anyio==3.3.0. I cannot decide from the commit history that this is due to specific requirements of opentrons.

Pinning packages makes it difficult to combine opentrons with other packages that also depend on e.g. anyio. Instead, it would be helpful to specify dependencies either open, anyio>=3.3.0, or limited to the next major version (anyio>=3.3.0,<4), assuming dependency maintainers adhere to semantic versioning and don't introduce breaking changes between major versions.

### Implementation details

Dependencies that need more specific versions could be pinned with a commit that references the issue describing the reasoning for pinning to exact versions. Then it's easier to go back later and check if the pinning is still necessary.

**Comment by SyntaxColoring** [comment]
See https://github.com/Opentrons/opentrons/pull/11912#issuecomment-1932990863.
