### ISSUE TITLE
PD Deck Setup: Well Selection - Well labels restyling

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#1196]
## overview

![image](https://user-images.githubusercontent.com/35570080/38695657-e4a6270c-3e5a-11e8-8e34-589cf366004a.png)

## behavior

Update `SelectablePlate` so that:

* Well labels are outside of the plate
* Well labels highlight bright blue when wells are hovered (ie, are `preselected`)

## TBD

* 384 reconsideration (number labels bleed together, should we set apart every other label by tint or something?)
* Mouseover without click-and-drag -- does that make the labels blue as well?
* In PD (or anywhere else) are there any circumstances where we want to show well labels inside the plate (as they are now), or should they always be either outside or invisible?

Current labels:

96
![image](https://user-images.githubusercontent.com/11590381/38756974-4f6d0c84-3f39-11e8-99f1-fac1c3e8d294.png)

384 has special every-other-label-gray
![image](https://user-images.githubusercontent.com/11590381/38756999-670a3b50-3f39-11e8-8310-83e9598d42da.png)

trough
![image](https://user-images.githubusercontent.com/11590381/38757011-7324b4e2-3f39-11e8-8532-00905f33dbd4.png)

and one weirdo tuberack:
![image](https://user-images.githubusercontent.com/11590381/38757050-95265802-3f39-11e8-84e0-52adf35dd0b3.png)

**Comment by howisthisnamenottakenyet** [comment]
@IanLondon 
(1) Putting well labels outside of the labware should resolve issues with odd labware like the wierdo tuberack. 
(2) I think making the labels blue should only be a thing for hover/click and drag. 

Is there anything missing from designs?

**Comment by IanLondon** [comment]
@howisthisnamenottakenyet Cool, I think it's all good except: will this work for 384 plate?

**Comment by howisthisnamenottakenyet** [comment]
@IanLondon Wouldn't it look pretty much the same except the text would be white and slightly grey instead of black and slightly grey?

**Comment by IanLondon** [comment]
@howisthisnamenottakenyet so I should do even white & odd light gray for 384?
