### ISSUE TITLE
feat: Protocols "sort by" should remember your last setting

### ISSUE THREAD

**Issue by c-bun** [Opentrons/opentrons#12103]
### Overview

Every time I run a protocol, I'm uploading a new one (cherry picking), so I am always needing to sort the protocol run list by "Most recent updates". It would be great if Opentrons remembered the most recent "Sort by" setting. I'm doubtful that the default setting of "Alphabetical" is the one that most people use anyways. Currently it seems that the setting gets reset every time I upload a new protocol.

Thanks!

**Comment by koji** [comment]
Hi @c-bun,
Thank you for your request.
We added the function that stores the sort key that users used last time.
This function will be included in the next release 6.3.

**Comment by c-bun** [comment]
Yay! Thanks for the quick response!
