### ISSUE TITLE
6.2.1 tip length calibration will not save bug: 

### ISSUE THREAD

**Issue by arstier** [Opentrons/opentrons#12135]
### Overview

Tip length cannot be calibrated in app. Robot will perform calibration prior to protocol run, but will not save results.
![image](https://user-images.githubusercontent.com/125091417/218196453-2dc2d93c-8e80-47ad-816b-72153c0023d8.png)
![image](https://user-images.githubusercontent.com/125091417/218196493-16fd36e9-1098-4676-855f-2a7e7bd6784c.png)

### Steps to reproduce

Updated app to 6.2.1
Updated robot to 6.2.1
[platform was moved and pipettes were changed]
Calibrate Deck
Install new pipettes
Calibrate pipettes (including tip length)
Loaded protocol
->Alert, tip length P300 8-channel gen2 not calibrated
Calibrate tip length
Last two steps repeat
![image](https://user-images.githubusercontent.com/125091417/218196556-7eb525d2-703d-4208-86c9-0b54aa34c886.png)

### Current behavior

Will not allow for tip calibration and does not allow for protocol operation

### Expected behavior

tip length calibration should perform and save to robot, allowing for protocol operation

### Operating system

Windows

### System and robot setup or anything else?

connected through USB connection.
Have attempted re-installation of app and robot versions which did not solve the issue.

**Comment by alexjoel42** [comment]
Hi! 

Sorry that you've been experiencing this issue. 

Would you be able to email Support at support@opentrons.com with:

- The GitHub ticket you've made 
- The protocol file you're using 
- If this happened before, or if it's your first time running a protocol on the OT-2

Then we'll make sure to help you out ASAP.

**Comment by arstier** [comment]
A second factor reset followed by reinstalling the 6.2.1 update onto the OT-2 platform seems to have resolved this issue.

A deck calibration was performed followed by both tip and offset calibrations which were then properly saved to the system.
![image](https://user-images.githubusercontent.com/125091417/218548830-edcdb858-429b-449a-a1c6-edb92f70b212.png)

The same test protocol was loaded and performed without error suggesting troubles have been resolved.
