### ISSUE TITLE
Protocol Library: OT-2 Deck Map

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1214]
As a OT-2 Robot user, I would like to be able to view the deck map setup for OT-2 protocols in the protocol library.

## Acceptance Criteria
- User able to see OT-2 deck map for OT-2 protocols in the protocol library
- Includes deck, containers, pipettes, reagents

## Implementation Notes
- May be able to use PD's React deck map via iframe (use URL params to get appropriate labware, etc.)

**Comment by mcous** [comment]
Duplicate of #2145
