### ISSUE TITLE
Deck Calibration: Show Last Calibrated Date

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1217]
As a user, I would like to be able to see when I last calibrated my deck.

## Acceptance Criteria
- Show last calibrated date on robot settings page
- If null, display 'unknown'
- Should fail gracefully if calibration file does not exist

## Implementation Notes
- Note we don't persist this data in the calibration file today (we only add a timestamp when we archive a calibration), but this is changing with Run App calibration (we'll create a backup copy with timestamp as soon as we calibrate)
- Requires new endpoint (and should be in new api framework)

## Design
https://zpl.io/bz1ZMzE

**Comment by btmorr** [comment]
@mcous @umbhau How should this info be accessed (e.g.: which endpoint/what shape)?
