### ISSUE TITLE
PD Advanced Step Settings: Well Ordering

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1230]
As a user, I would like to be able to choose between row-first and column-first transfers

## Acceptance Criteria
- User can open well ordering modal from step editor
- Each field has four options:
-- left to right
-- right to left
-- top to bottom
-- bottom to top
- User can select any option for the first field
- Second field options are limited based on first field selection (axis chosen is deactivated)
- Changing the first field clears any selection from the second field
- Fields default to T2B and L2R
- Modal includes an image visualizing their selection
-- If either/both fields are empty, the image disappears
- Both fields are required to save order selection
- User has option to cancel

## Design
![image](https://user-images.githubusercontent.com/35570080/44172453-40188280-a0ab-11e8-9a07-224ea75a47eb.png)

**Comment by umbhau** [comment]
@howisthisnamenottakenyet Just need to add 'cancel' to the modal.

**Comment by umbhau** [comment]
@howisthisnamenottakenyet Let's add copy to make it clear that you FIRST do the first field and THEN do the second field.

e.g.
'top to bottom' THEN 'left to right'

**Comment by howisthisnamenottakenyet** [comment]
@umbhau already done
