### ISSUE TITLE
Initial Calibration: Display Calibration Pipette

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1238]
As a user, I would like my robot to know what pipette I am calibrating with.

## Acceptance Criteria
- [ ] When user clicks 'continue' on the clear deck modal, send 'start calibration' to the API
- [ ] App stores mount response from API to use in #1237

## Implementation Notes

- Dependent on API work in #1257
- Blocks #1237

**Comment by mcous** [comment]
Note that this ticket was made smaller by moving pipette selection logic to the API (#1257)
