### ISSUE TITLE
Protocol analysis failure on new and old/previously working protocols

### ISSUE THREAD

**Issue by eyesmo** [Opentrons/opentrons#12418]
I'm trying to import and run a standard protocol I've imported in the past, but with a couple of parameters tweaked. However, each time I try to upload the protocol, I get a Protocol Analysis Failure saying the app failed to parse the protocol. I also get this error for previously uploaded protocols that had run smoothly in the past. I have been unable to fix the problem by restarting the app or the bot, or by re-installing the latest version of the OpenTrons App. Any help very much welcome!

**Comment by eyesmo** [comment]
The problem seems to occur at the import step, since previously uploaded and run protocols will pass re-analysis but fail re-importation

**Comment by koji** [comment]
Hi @eyesmo
Sorry for inconvenience to you.
Could you reach out to the support team?
[support@opentrons.com](mailto:support@opentrons.com)

**Comment by koji** [comment]
@eyesmo if you need this ticket, please re-open.
