### ISSUE TITLE
Multiple Users: Warn Before Taking Control

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1247]
As a user, I would like to be told if I am attempting to take control of a robot that is already in use, so that I don't accidentally interrupt somebody else.

## Acceptance Criteria
- If user attempts to take control of a robot that is in use, warn user that they are interrupting a robot that is in use.

## Implementation Notes
- This user story covers a few different scenarios, including:
-- User clicks 'Calibration' to start deck calibration
-- User starts labware calibration
-- User attempts to start a run

## Design
![image](https://user-images.githubusercontent.com/1682403/39139495-1584f752-46f0-11e8-9a6a-9e15b4287e0e.png)

**Comment by Matt-Zwimpfer** [comment]
Will be addressed in a separate fashion/in the future.
