### ISSUE TITLE
bug: run error

### ISSUE THREAD

**Issue by fernandostuani** [Opentrons/opentrons#12506]
### Overview

bug: cannot run protocol due to the message "opentrons.protocol_reader.file_identifier.FileIdentificationError: PO4 assay upgraded.json is not valid JSON. Expecting value: line 1 column 1 (char 0)"

### Operating system

None

**Comment by koji** [comment]
@fernandostuani 
Could you reach out to our support team [support@opentrons.com](mailto:support@opentrons.com), please?

**Comment by koji** [comment]
If needed, please re-open.
