### ISSUE TITLE
Run App: Home After Calibration

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1261]
As a user, I would like my robot to home after I calibrate, so that I don't have to calibrate at the beginning of a run.

## Acceptance Criteria
- Robot should home all axis when user clicks "Drop tip and proceed to run"
- Robot should not home at the beginning of run

## Design
@pantslakz 

### Notes
- This will result in some users skipping the home at the end of calibration. This is okay because home isn't critical here, and they can manually home

**Comment by mcous** [comment]
Robot now homes when it needs to, and we also provide a mechanism for the user to home the robot manually if they want via the robot page in the app
