### ISSUE TITLE
Usability: Calibrate Single Channel Pipette Last

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1264]
As a user, I would like to calibrate my single channel pipette to tipracks last, so that I can use the single channel pipette for labware calibration.

## Acceptance Criteria
- [ ] If there is a single channel pipette, it should appear second in the pipettes list
- [ ] If there is a single channel pipette, it should be calibrated to tiprack second
- [ ] If there are two single channel pipettes, calibrate the left one first (if we need a default...it doesn't really matter)

**Comment by mcous** [comment]
This ticket seems to also require disabling the tipracks in the list so they cannot be clicked on

**Comment by umbhau** [comment]
Duplicate of 1128
