### ISSUE TITLE
Run App: Run Again

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1270]
As a user, I would like to be able to run a protocol again, after it is complete

## Acceptance Criteria
- 'Reset Run' button in sidebar and link in alert resets the run panel, so that user can run again
-- Run log reset
-- Run time clock reset
-- Run again button reset
- Note this should just return user to the same state that they would see if they clicked on the 'Run' tab for the first time from the 'Calibrate' tab

## Implementation Notes
- Button clears out the state
- User should _not_ be required to recalibrate
- if reset is expected to take a long time (e.g. if robot simulates a run), add spinning icon page
- Dependent on 1269

## Design
Zeplin: Run App Screens > "RUN" tag

![screen shot 2018-05-04 at 1 17 59 pm](https://user-images.githubusercontent.com/2686086/39627045-a565a94a-4fa4-11e8-846f-915a7026ebf7.png)

## Implementation Notes
- For 'Run Again' button resets the run panel: RPC Session.refresh
- ignore "download run log" for now

**Comment by mcous** [comment]
Closed by #1576 and #1577
