### ISSUE TITLE
feat: show labware labels in the app

### ISSUE THREAD

**Issue by arogozhnikov** [Opentrons/opentrons#12780]
### Overview

I put labels on labware (barcodes), but they are not shown in the protocol overview (plates frequently have identical labware type):

<img width="500" alt="Screenshot 2023-05-23 at 9 42 52 AM" src="https://github.com/Opentrons/opentrons/assets/6318811/ac064676-7c1a-4981-8b32-45579dab6a6e">

Below is an example from OT2 protocol library, I'd like to have something similar, but with custom labels shown if they present.
<img src='https://github.com/Opentrons/opentrons/assets/6318811/e4e73fa0-91e4-4374-8467-37a567e988e7' width=300 />

`load_labware` has an argument `label`, which is what should be shown be default on experiment view

BTW congrats on release of OT2 flex!

**Comment by ecormany** [comment]
Hi Alex, thanks for the feedback. The best place to view these labels in the Opentrons App is when setting up a protocol run. Click **Map View** in the Labware Setup section. 
<img width="1092" alt="labware setup map view" src="https://github.com/Opentrons/opentrons/assets/1958332/7ce627c2-9833-4875-9992-f21e5b316fed">


If you're away from your OT-2 or it's busy running another protocol, you can follow our [developer setup instructions](https://github.com/Opentrons/opentrons/blob/edge/DEV_SETUP.md) and run `make -C robot-server dev` to create a virtual robot.
