### ISSUE TITLE
Resize top level nav and title bar

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1285]
As a user I would like Protocol Designer to be easier to read

--

## Background
A good chunk of our users actually have tiny screens. [See spreadsheet from lucy](https://docs.google.com/spreadsheets/u/5/d/13nQskpWOwnDVaTRrkW9y7iwsxUhyL3Eoj9SeJN00JwM/edit?usp=sharing)
We can increase room for the sidebar and page by reducing the width of the top level nav and the height of the title bar. 

## Acceptance Criteria
-In wires top level nav width was reduced from 72 -> 60
-In wires title bar was reduced from 56 -> 48
-At this time additional width was given to the side panel but not to the page.

## Design
![image](https://user-images.githubusercontent.com/35570080/39369188-9b9e2c8e-4a09-11e8-9e27-5af2fce3d5a5.png)
![image](https://user-images.githubusercontent.com/35570080/39369197-a32499fc-4a09-11e8-91ce-a5cba08ab858.png)
![image](https://user-images.githubusercontent.com/35570080/39369363-18bb6a42-4a0a-11e8-9c5d-8060ea26ee2a.png)

**Comment by pantslakz** [comment]
@IanLondon @Kadee80 note this change should reflect in both run app and protocol designer

**Comment by mcous** [comment]
@pantslakz @howisthisnamenottakenyet can you ping this thread when these changes have been uploaded to the components library in Zeplin?

@pantslakz do you think these changes should bu grouped with the text alignment stuff with the titlebar we discussed last week?

**Comment by pantslakz** [comment]
@mcous yes this is related to that - but should be sorted now that you have the new component library. as a general rule:

Title | Subtitle is always left aligned, unless there is a "back" or "exit" button, in which case it is then right aligned. 

Zeplin now contains a component for both versions.
Please let me know if this requires any additional clarification, or if we should make a separate ticket to tackle it.
