### ISSUE TITLE
Switch Protocol Designer design icon from gear

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1289]
As a user I would like to understand the nav

--

## Background
The cog was meant to be a placeholder icon. Got feedback multiple times that it felt more like "settings" than anything else. 

## Acceptance Criteria
-Switch to the SVG in the design assets folder

## Design
![image](https://user-images.githubusercontent.com/35570080/39382499-b0a269d6-4a33-11e8-9f18-999fed48c4be.png)

**Comment by IanLondon** [comment]
Closed #1365
