### ISSUE TITLE
bug: can't connect to robot by ssh

### ISSUE THREAD

**Issue by arogozhnikov** [Opentrons/opentrons#12900]
### Overview

Previously login by ssh worked fine, but it stopped working recently. 
Going again through manual (create new key > register in opentrons via curl call) resulted in key being succesfully added, but still connection is denied. Same problem for other users of this robot.

```
debug1: Offering public key: /Users/axelr/.ssh/id_rsa RSA SHA256:vn/mxBA8tZCu<redacted> explicit agent
debug1: send_pubkey_test: no mutual signature algorithm
debug1: Offering public key: /Users/axelr/.ssh/key_ed25519 ED25519 SHA256:iHLBt7O3Iq6N/0XWFtN9Nv<redacted> explicit agent
debug1: Authentications that can continue: publickey
debug1: Offering public key: ./ot2_ssh_key_alex RSA SHA256:SDbTd19gTkaqi<redacted> explicit
debug1: send_pubkey_test: no mutual signature algorithm
```

so 2 keys are rejected with "no mutual signature".

I've tried switching to ed25519, but api does not accept it and inserting into `authorized_keys` seems to have no effect.

I've been looking for ways to debug this on robot side, but could not find auth logs.

### Operating system

Mac

### System and robot setup or anything else?

Connecting from mac, wired over ethernet (OpenSSH_9.0p1, LibreSSL 3.3.6).
Robot and app updated to the latest available version (6.3.1).

**Comment by arogozhnikov** [comment]
Yes, I can confirm this is the reason

**Comment by ecormany** [comment]
Thanks for confirming!
