### ISSUE TITLE
Well highlights go above labware name

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1291]
As a user I would like to see which wells are being highlighted

--

## Acceptance Criteria
-The blue well highlight is the top layer, and goes above labware name

## Design
It actually used to be this way. Not sure why it isn't now.

**Comment by IanLondon** [comment]
Added WIP label b/c in last PD meeting we discussed:
- there might be a better long-term solution to getting those labels out the the way
- separating the well highlight from the well adds a decent amount of complexity
