### ISSUE TITLE
Remove vestigal 'serialize name' artifacts

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1294]
As a user I would like to not be exposed to unnecessary complexity in this maze of forms

--

## Background
Currently "serialize name" has it's own text field that creates a name separate from the ingredient name. Have not seen this as needed. 

## Acceptance Criteria
-Remove the serialized name text field. Clicking serialize name will now generate names in the format "{Ingredientname} {#}" Instead of "{Serializedname} {#}".

## Design
- [x] remove the text field
- [x] everywhere the ingredient name appears (eg in the sidebars), it should be "{Ingredientname} {#}" -- and not "Sample {#}" (the old fallback serializedname is "Sample")

## Implementation Notes
Removing the text field will be done in #1322, but the code needs to be cleaned up to work right without the text.

**Comment by umbhau** [comment]
@IanLondon @howisthisnamenottakenyet Looks like this one is all done?

**Comment by howisthisnamenottakenyet** [comment]
@umbhau not yet: 
![image](https://user-images.githubusercontent.com/35570080/41172462-ed4dfe0e-6b21-11e8-8c45-84964b24ef93.png)
![image](https://user-images.githubusercontent.com/35570080/41172495-09cee32c-6b22-11e8-9574-520d16412352.png)

**Comment by IanLondon** [comment]
I just hid the text field in another ingred form ticket PR. I also still need to clean up the artifacts in the code left over from 'serializeName' text field
