### ISSUE TITLE
Well selection field number should be multiplied by 8 for multichannel 

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1297]
##Background
In reference to https://github.com/Opentrons/opentrons/pull/1295

##Acceptance Criteria
-The input WellSelectionInput that you click on to open the modal doesn't show accurate number of wells selected for multichannel. It needs to be multiplied by 8 when a multi-channel pipette is selected

**Comment by IanLondon** [comment]
Closed in favor of alternative approach in #1537
