### ISSUE TITLE
Clear well selection if switching from single channel pipette to multichannel

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1298]
As a user I would like to create steps that can be executed by the robot. 

##Background
Multichannel pipettes can't always execute the same well selection pattern as a single channel. However single channel pipettes can execute a multichannel well selection pattern. 

##Acceptance criteria
-If in a step form a user switches the pipette from a single channel to multichannel, the well selection clears. 

##Design
n/a

**Comment by IanLondon** [comment]
Also, switching multichannel to single channel should preserve the selection (not just top rows of columns)
