### ISSUE TITLE
Error: Incompatible Pipettes and Labware

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1300]
As a user I would like to be prevented from creating steps with incompatible labware and pipettes.

## Acceptance Criteria
-When a user tries to select either a pipette (after choosing incompatible labware) or labware (after choosing multichannel pipette), pop up a modal (in browser, or whichever PD is using at this time). After hitting close, that field is cleared. 
-IN THE FUTURE: migrate to having a disabled option in the labware/pipette dropdown with a tooltip explaining why it can't be selected. 

## Design
![image](https://user-images.githubusercontent.com/35570080/39437569-40ba00e6-4c6f-11e8-8dc3-98064b8f3724.png)

**Comment by IanLondon** [comment]
Since this is a short-term feature that will be replaced by a tooltip, is the ugly browser-native warning ok?
