### ISSUE TITLE
Give well de-selection its own highlight state

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1301]
As a user I would like to be able to see which wells I am deselecting

## Background
Currently when you hover over wells while holding shift, there is no highlight state

## Acceptance criteria
-Give well deselection its own highlight so you can see what you are about to deselect

## Design
![image](https://user-images.githubusercontent.com/35570080/39438024-b2b288de-4c70-11e8-9c8a-f7dc709da8ee.png)

**Comment by IanLondon** [comment]
Note: play around with dash sizes for 384 plate? Try it out

**Comment by howisthisnamenottakenyet** [comment]
We have decided this is a good place to start and should proceed with dashed line
