### ISSUE TITLE
Usability: drop tip before detach pipette

### ISSUE THREAD

**Issue by pantslakz** [Opentrons/opentrons#1310]
As a user I would like to avoid crashing the tip when the pipette lowers to detach.

## Background
Ian first brought this up after testing, and I experienced it twice during use as well.

## Acceptance Criteria
- ~Remind user to remove tip in modal~ Fixed with #3959 
- Robot drops tip automatically after homing before moving forward

## Design
-TBD

**Comment by umbhau** [comment]
Partially fixed: warning added to change tip instructions (#3959).

Holding off on automatic tip drop until HTTP functionality is added for drop tip, which is planned as part of the calibration project(s).
