### ISSUE TITLE
bug: during initialization it stops working and it makes a strange noise 

### ISSUE THREAD

**Issue by amerloiu** [Opentrons/opentrons#13137]
### Overview

during initialization , the robot starts to work properly , but a few seconds in it seems as the arm is trying to go over the limit of the chamber , it does deservo itself  it just seems to not be able to continue as it think that there is more space for it to go. After that is stops working
 IntroScreen failed to issue prep commands with message: SmoothieError: M907 A0.1 B1.0 C0.05 X0.3 Y0.3 Z0.1 G4 P0.005 G28.2 B 

 returned ALARM: Homing fail

### Operating system

None

**Comment by ecormany** [comment]
Opentrons Support can help you with this [homing fail error](https://support.opentrons.com/s/article/SmoothieError-Homing-fail). You can contact them at support@opentrons.com.
