### ISSUE TITLE
Usability: remove home step in between tip probing of two pipettes

### ISSUE THREAD

**Issue by pantslakz** [Opentrons/opentrons#1316]
As as a user, I would like to tip probe as quickly as possible. 

## Background
Currently if you have to tip probe two pipettes, the robot homes in between. Kinnari provided feedback that this really slowed her down. Would help save time if we removed it.

## Acceptance Criteria
* When tip probing 2 pipettes, no homing step in between

## Design
* n/a

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535349930) by [Unito](https://www.unito.io/learn-more)

**Comment by sfoster1** [comment]
Wontfix: superceded by calibration overhaul
