### ISSUE TITLE
Usability: Orient user within calibration sub nav

### ISSUE THREAD

**Issue by pantslakz** [Opentrons/opentrons#1317]
As as a user I would like to know where I am in the calibration flow in the sub nav.

## Background
Currently as user progresses through calibration - we do not show a selected state for the calibration step they are on in the sub nav:

![screen shot 2018-05-01 at 2 42 07 pm](https://user-images.githubusercontent.com/2686086/39473162-b4bfce2e-4d4d-11e8-9290-07b03597b0ea.png)

## Acceptance Criteria
 - Show selected state for the pipette/labware they are on.

## Design
- TBD

**Comment by Kadee80** [comment]
@pantslakz  We have a selected state for selected/connected robots on the `RobotSettings` page. Might we start off by copying that selected/active state?

**Comment by pantslakz** [comment]
@Kadee80 yes!
