### ISSUE TITLE
PD Advanced Step Settings: Flow Rate

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1323]
As a protocol designer,  I would like to control the aspirate and dispense speed, so that I can fine-tune pipetting for various liquids.

## Acceptance criteria
- User able to open 'pipetting speed' modal from step editor advanced settings
- Pipetting speed has a default, min, and max
-- For now, default should be pipette capacity / 1 second. (Will revisit after additional testing)
-- Pipetting speed should be > 0
-- Pipetting speed max is specific to pipette (TBD)
-- User should not be able to save form with values outside allowed range
- Pipetting speed is specific to aspirate vs. dispense
- PD should write pipette flow rate to protocols 
-- File-level default
-- Per-step flow rate when requried

## Implementation Notes
- We believe pipettes defaults are currently stored shared data (@btmorr confirming)
- We believe robot is checking shared data at runtime for pipette defaults when executing python protocols (@btmorr confirming)
- If the above two statements are true, we're leaving them alone

## Design
https://zpl.io/agNNKYN

## Pipette defaults from Laura
{
  "p10_single_v1": {
    "displayName": "P10 Single-Channel",
    "nominalMaxVolumeUl": 10,
    "plungerPositions": {
      "top": 18,
      "bottom": 3,
      "blowOut": 1,
      "dropTip": -5
    },
    "pickUpCurrent": 0.1,
    "aspirateFlowRate": 5,
    "dispenseFlowRate": 10,
    "ulPerMm": 0.617,
    "channels": 1,
    "modelOffset": [0.0, 0.0, -13],
    "tipLength": 40
  },
  "p10_multi_v1": {
    "displayName": "P10 8-Channel",
    "nominalMaxVolumeUl": 10,
    "plungerPositions": {
      "top": 18,
      "bottom": 3,
      "blowOut": 1,
      "dropTip": -5
    },
    "pickUpCurrent": 0.2,
    "aspirateFlowRate": 5,
    "dispenseFlowRate": 10,
    "ulPerMm": 0.617,
    "channels": 8,
    "modelOffset": [0.0, 28.0, -25.8],
    "tipLength": 40
  },
  "p50_single_v1": {
    "displayName": "P50 Single-Channel",
    "nominalMaxVolumeUl": 50,
    "plungerPositions": {
      "top": 18,
      "bottom": 4,
      "blowOut": 2,
      "dropTip": -2.5
    },
    "pickUpCurrent": 0.1,
    "aspirateFlowRate": 25,
    "dispenseFlowRate": 50,
    "ulPerMm": 3.08,
    "channels": 1,
    "modelOffset": [0.0, 0.0, 0.0],
    "tipLength": 60
  },
  "p50_multi_v1": {
    "displayName": "P50 8-Channel",
    "nominalMaxVolumeUl": 50,
    "plungerPositions": {
      "top": 18,
      "bottom": 4,
      "blowOut": 2,
      "dropTip": -4
    },
    "pickUpCurrent": 0.3,
    "aspirateFlowRate": 25,
    "dispenseFlowRate": 50,
    "ulPerMm": 3.08,
    "channels": 8,
    "modelOffset": [0.0, 28.0, -25.8],
    "tipLength": 60
  },
  "p300_single_v1": {
    "displayName": "P300 Single-Channel",
    "nominalMaxVolumeUl": 300,
    "plungerPositions": {
      "top": 18,
      "bottom": 3,
      "blowOut": 1,
      "dropTip": -2.5
    },
    "pickUpCurrent": 0.1,
    "aspirateFlowRate": 150,
    "dispenseFlowRate": 300,
    "ulPerMm": 18.51,
    "channels": 1,
    "modelOffset": [0.0, 0.0, 0.0],
    "tipLength": 60
  },
  "p300_multi_v1": {
    "displayName": "P300 8-Channel",
    "nominalMaxVolumeUl": 300,
    "plungerPositions": {
      "top": 18,
      "bottom": 3,
      "blowOut": 1,
      "dropTip": -4
    },
    "pickUpCurrent": 0.3,
    "aspirateFlowRate": 150,
    "dispenseFlowRate": 300,
    "ulPerMm": 18.51,
    "channels": 8,
    "modelOffset": [0.0, 28.0, -25.8],
    "tipLength": 60
  },
  "p1000_single_v1": {
    "displayName": "P1000 Single-channel",
    "nominalMaxVolumeUl": 1000,
    "plungerPositions": {
      "top": 18,
      "bottom": 3,
      "blowOut": 1,
      "dropTip": -2.5
    },
    "pickUpCurrent": 0.1,
    "aspirateFlowRate": 500,
    "dispenseFlowRate": 1000,
    "ulPerMm": 61.69,
    "channels": 1,
    "modelOffset": [0.0, 0.0, 20.0],
    "tipLength": 60
  }
}

## Background
- This design will evolve as we include defaults for liquid classes
-Decided against slider because it's hard to make meaningful in this use case.

**Comment by IanLondon** [comment]
Min and max recommended flow rates will not go into the protocol. Flow rate protocol default and per-step asp/disp flow rates will!

**Comment by IanLondon** [comment]
Closed by #2123
