### ISSUE TITLE
Serialized name should display in sidebar if it exists, not ingredient name

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1337]
As a user I would like to be able to see specifically what's in the well i'm using

## Acceptance Criteria
-In the sidebar if a liquid has a serialization name in addition to an ingredient name, the pill should hold the serialized name
-Colour of pill should be ingredient colour

## Design
![image](https://user-images.githubusercontent.com/35570080/39489509-c2a92f34-4d53-11e8-9dbd-7732942a9c71.png)

**Comment by IanLondon** [comment]
Note to self: see #1294 -- we don't need to have a separate string that is the "serializeName", just a do a reusable fn that 

> generate names in the format "{Ingredientname} {#}" Instead of "{Serializedname} {#}".
