### ISSUE TITLE
bug: Unresponsivness to protocols after opening pipette settings

### ISSUE THREAD

**Issue by VasBrd** [Opentrons/opentrons#13735]
### Overview

Selecting pipette [three dot menu] -> Pipette settings brought up blank subframe window where the settings would be usually. After that, the robot refused to run any protocols (including trying to run again ones that it had already run before). Rebooting it several times did not fix the issue. The following behavior was observed:

1) When trying to send a protocol to robot (from the protocols menu of the app), error "opentrons.protocol_reader.fileIdentificationError: apiLevel not declared in protocol.py" pops up.

2) When booting up, startup lacks the usual homing sequence (pipette adjusts its height, but no XY zeroing is berformed, nor nozzle noize is heard)

3) Recent Protocol Runs tab in Robot->Devices is permanently in loading state:
![Screenshot 2023-10-04 204923](https://github.com/Opentrons/opentrons/assets/86557363/76483b25-dbe2-4b17-a28b-7485a9509546)

Clearing robot data through factory reset reverts it to normal mode of operations. Pipette settings can be accessed immediately following data factory reset. Issue was confirmed to be persistent as after the calibration and a few run protocols another attempt at changing pipette settings was made and the whole process happened again in the exact same way.

### Operating system

Windows

### System and robot setup or anything else?

OT-2 robot, 
firmware v1.1.0-25e5cea,
robot server v6.3.1,
app 6.3.1,
USB connection

Calibration data that can still be downloaded when it becomes unresponsive to protocols:
`{"deck":{"deckCalibrationData":{"type":"attitude","matrix":[[0.9986,0.0008,0],[-0.0016,0.9988,0],[0,0,1]],"lastModified":"2023-09-29T11:34:23.549234+00:00","pipetteCalibratedWith":"P20SV202020021001","tiprack":"60e107ba7e6e5d23beefe9f0c888f860f7b923c71906aaa5e7f460ab25c4f38a","source":"user","status":{"markedBad":false,"source":null,"markedAt":null}},"isDeckCalibrated":true,"markedBad":false},"pipetteOffset":[{"id":"P20SV202020021001&right","pipette":"P20SV202020021001","mount":"right","offset":[-0.4999999999999982,-2,-0.30000000000000426],"tiprack":"60e107ba7e6e5d23beefe9f0c888f860f7b923c71906aaa5e7f460ab25c4f38a","tiprackUri":"opentrons/opentrons_96_tiprack_20ul/1","lastModified":"2023-09-29T11:45:26.962532+00:00","source":"user","status":{"markedBad":false,"source":null,"markedAt":null}}],"tipLength":[{"id":"60e107ba7e6e5d23beefe9f0c888f860f7b923c71906aaa5e7f460ab25c4f38a&P20SV202020021001","tipLength":30.650000000000063,"tiprack":"60e107ba7e6e5d23beefe9f0c888f860f7b923c71906aaa5e7f460ab25c4f38a","pipette":"P20SV202020021001","lastModified":"2023-09-29T11:38:28.023285+00:00","source":"user","status":{"markedBad":false,"source":null,"markedAt":null},"uri":"opentrons/opentrons_96_tiprack_20ul/1"}]}`

**Comment by ecormany** [comment]
Thanks for reporting this! We've already merged a fix and it will be available soon in version 7.0.1 of the robot software.
