### ISSUE TITLE
feat: Upgrade pydantic to v2

### ISSUE THREAD

**Issue by adrijanik** [Opentrons/opentrons#13983]
### Overview

Hi team, 

Do you have any plans to upgrade pydantic to v2 from v1.8.2? Is there maybe any branch that I could use if such transition is happening? It becomes a problem when you want to use opentrons library in a project where packages dependencies requires pydantic v2. I couldn't find any issue that address that.

Thanks!

### Implementation details

I haven't tested that, but this could be a simple fix by using v1 apis from within v2 version, see below:
`from pydantic.v1 import BaseModel` 

There is also a helper package `bump-pydantic` which may help with that. Here is also a [migration guide](https://docs.pydantic.dev/latest/migration/).

### Acceptance criteria

Lift the dependency from pydantic 1.8.2 to pydantic >=2.

**Comment by SyntaxColoring** [comment]
Yeah, we definitely want to upgrade Pydantic. (Internal reference: RSS-227)

Unfortunately we haven't started that work yet, so there's no branch you could use. We don't have a timeline for it, since we're focusing on the new Opentrons Flex.

> There is also a helper package bump-pydantic which may help with that. Here is also a [migration guide](https://docs.pydantic.dev/latest/migration/).

This is helpful. Thank you!

**Comment by ChrisTwig** [comment]
Hello @SyntaxColoring is there any proposed plan for this?
You could even use the new namespace pydantic.v1

**Comment by SyntaxColoring** [comment]
Sorry for the lack of updates here. Yes, we're working on this in PR #14871. It's not our first priority, though, so I can't promise it will be completed soon.

**Comment by silvioscience** [comment]
Hello @SyntaxColoring, any updates on this?

**Comment by SyntaxColoring** [comment]
Latest update: https://github.com/Opentrons/opentrons/pull/14871#issuecomment-2294227559

**Comment by strangemonad** [comment]
please please please prioritize this. Pydantic should have fixed many import perf issues. It's a major pain that we can't easily interoperate between core models in parts of our codebase.

**Comment by SyntaxColoring** [comment]
Done in PR #14871.
