### ISSUE TITLE
Standardize Backlash Values

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1410]
As a robot user, I would like to use the same backlash value as all other users, so that I get consistent and reproducible pipetting results.

## Acceptance Criteria
- Driver and manual testers should use same configured backlash value

## Implementation notes
- Driver currently users a backlash value of 0.5mm; Carlos and other testers are manually setting a value of 0.3mm in test scripts
- Research and make a judgment call on correct value
- Get all users on same blowout value (potentially getting driver in to Carlos' workflow)

**Comment by btmorr** [comment]
Modified test right to match API values
