### ISSUE TITLE
bug: Coroutines decorator removed in python 3.11 

### ISSUE THREAD

**Issue by EraxterCodes** [Opentrons/opentrons#14539]
### Overview

Running 
```
opentrons_simulate <any python protocol>
```
Causes error:
```
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?
```
Some research led me to the fact that the issue seems to be that I am running python 3.11 and Generator based Coroutines are deprecated in python 3.11
 

### Steps to reproduce

Running 
```
opentrons_simulate <any python protocol>
```

### Current behavior

Causes error:
```
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?
```

### Expected behavior

Should run python protocol

### Operating system

Linux

**Comment by ecormany** [comment]
The `opentrons` package is built, tested, and designed to run with Python 3.10, specifically 3.10.13. We recommend using `pyenv` to switch between Python versions as needed. The dev setup documentation has further [info on setting up pyenv](https://github.com/Opentrons/opentrons/blob/edge/DEV_SETUP.md#2-install-pyenv-and-python).

Note: you don't have to do the full dev setup to use `pyenv` in combination with the PyPI release of the `opentrons` package and `opentrons_simulate`.
