### ISSUE TITLE
bug: Tip doesn't go to bottom of well in PCR cycler

### ISSUE THREAD

**Issue by lbcp** [Opentrons/opentrons#14599]
### Overview

Since the update to Version 7.1.1 (from Version 6), the robot does not go to the bottom of the 96-well plate in the Thermocycler Module anymore. It only goes roughly 3 mm into the well and then dispenses its liquid.

This behaviour wasn't seen before.

### Steps to reproduce

minimal working script to reproduce:
```python
metadata = {
    'author': 'lbcp',
    'description': 'Example for 96-well depth bug on PCR cycler',
    'apiLevel': '2.13'
            }

def run(prot):
    cycler = prot.load_module('thermocyclerModuleV1') # By default: Cylcer covers slots 7,8,10,11
    pcr_plate = cycler.load_labware('nest_96_wellplate_100ul_pcr_full_skirt')
    tiprack_1_p300 = prot.load_labware('opentrons_96_filtertiprack_200ul', 2) 

    p300 = prot.load_instrument('p300_single_gen2', 'left',tip_racks=[tiprack_1_p300])

    tube_rack = prot.load_labware(
        'opentrons_24_tuberack_eppendorf_1.5ml_safelock_snapcap', 6)
    tube = tube_rack.wells_by_name()['A1']

    # Transfer to plate
    p300.pick_up_tip()
    for well in pcr_plate.wells()[0:7]:
        p300.aspirate(100, tube, rate=0.5)
        p300.dispense(100, well)
    p300.drop_tip()

    # Transfer back to tube
    p300.pick_up_tip()
    for well in pcr_plate.wells()[0:7]:
        p300.aspirate(100, well, rate=0.5)
        p300.dispense(100, tube)
    p300.drop_tip()
    
    
```

### Current behavior

The pipette tip only goes about 3mm into the PCR plate wells and does not reach the bottom of the tube. This leads to spillage, and, if smaller volumes are used, uneven distribution of samples and buffers to the plate.

Also, the robot is not able to get the liquid out of the plate since the tip is way too high.

Every other tube and location works properly.

### Expected behavior

The pipette tip should go to the bottom of the well plate.

### Operating system

Windows

### System and robot setup or anything else?

App version: 7.1.1
Robot Server Version: v7.1.1
Connection via USB

Any additional information can be given upon request.

**Comment by ecormany** [comment]
Thanks for reporting! We're aware of this issue and it will be fixed in version 7.2.0. 
https://github.com/Opentrons/opentrons/blob/be3467253360d060bc3d57508286b952a83368b4/app-shell/build/release-notes.md?plain=1#L27
