### ISSUE TITLE
bug: No module named 'requests' 

### ISSUE THREAD

**Issue by COOOLFANS** [Opentrons/opentrons#14744]
### Overview

Hello! I used the **'requests'** module in my program and it comes up with **no module named 'requests'.** I used SSH to install the **'requests' on ot-2,** and it shows that the installation was **successful,** but the requests library is not found in the **pip list.** 
I don't know what method to use to install the 'requests' module, please help me~
![屏幕截图 2024-03-28 153642](https://github.com/Opentrons/opentrons/assets/129026112/e54855ba-58d1-485b-85f9-fbf2b4cf0802)
![52f47c54a5e1a7068d48abffd4b8c35](https://github.com/Opentrons/opentrons/assets/129026112/834a4a70-1fc7-4c71-a3fa-7e45d4aaf333)
![52f47c54a5e1a7068d48abffd4b8c35](https://github.com/Opentrons/opentrons/assets/129026112/65f0438c-b2ec-4d16-a8fd-17cfca9b3411)

### Operating system

Windows

**Comment by koji** [comment]
@COOOLFANS 
Could you check this doc's `ModuleNotFoundError`?
https://support.opentrons.com/s/article/Using-Python-packages-in-Python-API-protocols#:~:text=SSH%20into%20your%20OT-2.%20Use%20pip%20to%20install,upload%20protocols%20that%20import%20and%20use%20the%20package.

**Comment by koji** [comment]
@COOOLFANS 
If you still face the same issue, please contact to our support team. support atmark opentrons.com
