### ISSUE TITLE
File Management: Save Button for File Information

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1504]
As a user, I would like to be able to update my protocol information by clicking a save button.

## Acceptance Criteria
- User has access to an 'update' button in the Protocol File > Information section
- If no changes have been made, button is inactive and has copy 'updated'
- If changes have been made, button is active and has copy 'update'
- Clicking update button saves form data ('protocol name', 'org/author', and 'description')

## Implementation Notes
- Note form is currently saved real-time as user updates fields.

## Design
![image](https://user-images.githubusercontent.com/35570080/40736602-7981f2bc-640c-11e8-8a71-4a24c0c38510.png)

**Comment by IanLondon** [comment]
@howisthisnamenottakenyet a few Qs:

Right now it instantaneously saves - the only thing that would update is the protocol name shown in the header.

How can user see that changes are unsaved (when they don't click UPDATE)? 

Should hitting enter in a field also update the "file details form"?

**Comment by howisthisnamenottakenyet** [comment]
@IanLondon Can we do the same thing we do in runapp where the button says "updated" and is disabled if there's nothing to update?
