### ISSUE TITLE
Restyle labware hoverstate buttons

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1519]
## Acceptance Criteria
-~Icon goes on the left~ (already does)
-Button is 100% white even when not hovered on

## Design
![image](https://user-images.githubusercontent.com/35570080/40450857-d9138090-5eaa-11e8-843c-3a487fafb7a7.png)

**Comment by IanLondon** [comment]
# Implementation Note

This is fragile across different versions (or maybe even Mac vs Linux on same version) of Chrome, make sure to test on several computers & look into cause of SVG fragility

**Comment by IanLondon** [comment]
@b-cooper do the icons & text appear misaligned (do they differ from the image in the issue comment) in your browser? They are aligned for me so I can't see if I'm actually fixing it or not.
