### ISSUE TITLE
Labware and Ingredient Setup: Serialization Across Multiple Labware

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1529]
As a user I might want to number samples that span multiple plates

## Acceptance Criteria
- When a serialized ingredient is placed on a second piece of labware it continues counting up from wherever the numbering left off on plate 1
- Serialization does not cross multiple plates (i.e. you can't do 1-13, 18-22  on plate 1, 14 - 18 on plate 2.
- Serialization goes in the order plates / ingredients are created, and is not related to slot # on the deck
-If you've serialized across 3 plates and delete plate #2, the numbers on plate #3 shift downward appropriately

## Design
n/a

**Comment by IanLondon** [comment]
@howisthisnamenottakenyet there will be no way to have 2+ different plates with Samples 1-96 on both, right?

And copying labware will continue serialization (eg Samples 97-192), not replicate it (Samples 1-96 again)

**Comment by howisthisnamenottakenyet** [comment]
@IanLondon Yup! I think that's how we should start for now and maybe add more options if it's something that comes up from users.

**Comment by IanLondon** [comment]
@howisthisnamenottakenyet I don't remember what's going on with this one...
