### ISSUE TITLE
Assigning tip racks

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1533]
As a user I need to define which pipette uses which tip rack

## Acceptance criteria

-When a tip rack is placed on the deck
---(1) If there is one pipette the carat for assignment dropdown doesn't exist and it isn't clickable
---(2) If the pipettes are different sizes and it's clear which tips belong to each pipette, same deal as above
---(3) You have two pipettes that could both use that tip rack, there is a dropdown for pipette assignment

-If you place a copy of your tiprack via the copy feature (not from the labware selection modal), assignment is also copied. 

-You cannot save the tip rack without an assigned pipette 

-If you click off the tip rack while it's initial state is still open
---(1) If a pipette has not been assigned it does not autosave
---(2) If a pipette has been assigned it acts like other labware and clicking off it does autosave

## Design
![image](https://user-images.githubusercontent.com/35570080/40503262-86fec600-5f5b-11e8-8cfd-5a43f9170e37.png)

**Comment by IanLondon** [comment]
Replaced by alternative approach #1573

(Right @howisthisnamenottakenyet ?)
