### ISSUE TITLE
Swap pipettes in PD

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1536]
As a user I would like to be able to swap L and R pipettes in the file details page so I don't have to physically do it on the robot

## Acceptance criteria
- Put Information and Pipettes in their own Card components
- Add a secondary button to file details that switches which pipette is on which side

## Design
SVG called 'swap-horizontal'
![image](https://user-images.githubusercontent.com/35570080/42511171-205762e8-841f-11e8-889e-5bbeb93968e8.png)

**Comment by pantslakz** [comment]
@howisthisnamenottakenyet I have a hunch the arrows might not be clear enough in this situation. Would suggest a button with text in place of icon here.

ie. "Swap pipette positioning"

**Comment by howisthisnamenottakenyet** [comment]
@pantea how about something like this?
![image](https://user-images.githubusercontent.com/35570080/42177197-dd2fec2c-7df9-11e8-9321-ca0dc69cdecb.png)

**Comment by pantslakz** [comment]
@howisthisnamenottakenyet how would it look if both pipettes were populated?
