### ISSUE TITLE
Update Server: Update Firmware via Update Server

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1549]
As a user, I would like to be able to update my robot's API server and Smoothie firmware via the update server.

## Acceptance Criteria
- [ ] Implement API and firmware update endpoint in update server (instead of API)
- [ ] Previous versions of the app and `make` tasks relating to software update should work unmodified

**Comment by btmorr** [comment]
Blocked on #1208

**Comment by btmorr** [comment]
Now that FW update is included in the SW update endpoint, this ticket is pre-empted by one of the sub-tasks in #1208
