### ISSUE TITLE
PD Bugs: Unable to view File page when editing ingredients

### ISSUE THREAD

**Issue by pantslakz** [Opentrons/opentrons#1561]
As a user, I'd like to view the File page even when I'm editing the ingredients

## Expected Behavior
- View File page when you select 'File' tab in primary nav panel

## Observed Behavior
- Deck setup persists after user selects 'File' tab.

## Steps to recreate 
- add ingredient to labware
- select 'File' tab

![screen shot 2018-05-29 at 5 55 57 pm](https://user-images.githubusercontent.com/2686086/40687835-ecf2cdf0-6369-11e8-9601-f5383c3ac6db.png)

**Comment by IanLondon** [comment]
@pantslakz @howisthisnamenottakenyet 

When a user clicks the File page, then clicks back to the Design page, should whatever modals they had open stay open, or should they be closed when you click File page nav icon?

We should make a high-level flow chart of all the "modes" and modals in PD, and what side-effects happen when the user navigates between them

**Comment by IanLondon** [comment]
Covered in #2198
