### ISSUE TITLE
feat: Opentrons App accepting CSVs

### ISSUE THREAD

**Issue by MSMDG** [Opentrons/opentrons#15639]
### Overview

It would be easier for a robot user to load a CSV within the Opentrons software rather than finding other solutions (such as uploading via Jupyter).
Maybe there is a way this could be implemented with the runtime parameters.

**Comment by koji** [comment]
@MSMDG 
thank you for your request.
we are working on adding CSV support to runtime parameters.

**Comment by MSMDG** [comment]
@koji Thank you it will be a nice feature to have.

**Comment by koji** [comment]
@MSMDG 
please try v8.0.0
https://github.com/Opentrons/opentrons/releases/tag/v8.0.0
