### ISSUE TITLE
question: What is different between opentrons.simulate and protocol analysis?

### ISSUE THREAD

**Issue by ChrisTwig** [Opentrons/opentrons#15678]
Opentrons simulate and protocol analysis seems to do very similar things.
Both reads a protocol file and outputs the commands. (simulate outputs run logs (readable) vs analysis outputs ot commands) 

Is there a difference between what is checked? I am currently working on programmically creating protocols and want a way to ensure it is error free.

**Comment by ecormany** [comment]
`opentrons_simulate` and analysis are different, but mostly in terms of how they translate the list of robot commands into human-readable text. In general, if it simulates without error it should analyze without error, and vice versa.

One current limitation of `opentrons_simulate` is that you can't yet change runtime parameter values from their defaults. You have to modify the protocol to try other values. In the Opentrons App, when you change runtime parameters, the app re-runs analysis and lets you know whether that analysis succeeded or failed.
