### ISSUE TITLE
File Management: Tip Selection

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1573]
As a protocol designer, I would like to be able to select tip racks to use with my protocol, when creating a protocol file.

## Acceptance criteria
- User prompted to select one tip rack type per pipette when creating a protocol file
- User can use a dropdown with a list of tip rack 'types' (string names exactly match lab ware types)
- If a pipette is set to none, the tip rack field is disabled (or auto set to 'none', whichever is easiest)
- Tip rack  dropdown only displays tip racks that can fit with the selected pipette

## Implementation Notes
- When designing a protocol, user will only have access to tip rack types selected while creating the protocol
- If pipettes use the same tip rack type then you need to place 2 of the same type (pipettes don't share yet)

## Designs
![image](https://user-images.githubusercontent.com/35570080/40790332-abb400f2-64c2-11e8-993a-9ad4da20a24e.png)

**Comment by IanLondon** [comment]
Nevermind, not closed yet, I forgot part 3 #1866
