### ISSUE TITLE
Chat: Add Intercom Chat to PD

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1587]
As a user, I would like to be able to chat with the Opentrons team in the Protocol Designer

## Acceptance criteria
- Install intercom code as indicated in Intercom SPA instructions (see implementation notes)
- Update page on page change

## Implementation Notes
- Intercom instructions for installing in single page app:
https://developers.intercom.com/docs/integrate-intercom-in-a-single-page-app
- Note we're following instructions for logged-out users
- Note this was done recently in Run App by @mcous , #1224 and PR #1255

**Comment by umbhau** [comment]
@howisthisnamenottakenyet do we want to follow Run App pattern and put the app info/help tab at the bottom of the primary nav?

**Comment by howisthisnamenottakenyet** [comment]
@umbhau Yup. Was talking it over w Pantea. Going to update the wires to stuff it in a More drawer too.

**Comment by IanLondon** [comment]
Blocked: we're not sure if Intercom messenger should be in PD

**Comment by IanLondon** [comment]
@umbhau are we good to close this ticket?

**Comment by mcous** [comment]
Closing in favor of a new ticket if this ever gets revisited
