### ISSUE TITLE
bug: Unable to switch from one protocol to another without restarting the robot.

### ISSUE THREAD

**Issue by dmrdavyd** [Opentrons/opentrons#15884]
### Overview

With OT2 and the current version of Opentrons software, after running any protocol and then attempting to run another one, the software does not show any robot available after clicking on "Run". It only suggests to refresh  However, the robot remains available in "Devices".  At the same time, the previously used protocol can be run again w/o problems. So, the only way to switch from one protocol to another is to turn OT2 off, turn it back again and wait until it reinitializes. The problem appeared after the previous update (not the most recent) update of the software.

### Steps to reproduce

Run any protocol, then select any other in "Protocols" and try to run it. The software won't show any robot (either available  or unavailable) and won't allow to proceed to setup. See the attached screenshot:
![ScreenHunter_001](https://github.com/user-attachments/assets/a84294bf-409a-4a9a-a9fa-de8e7c592613)

### Operating system

Windows

### System and robot setup or anything else?

Opentrons software version 7.5.0. Robot is connected via USB/LAN.

**Comment by ecormany** [comment]
This is a known issue, and fortunately you don't have to restart your OT-2 to work around it:

https://github.com/Opentrons/opentrons/blob/343b8b651a6c022b9b952595d81307b056ad26e5/app-shell/build/release-notes.md?plain=1#L23-L25

Find your robot on the Devices page, click **Go to Run**, and clear the completion banner.
