### ISSUE TITLE
Warning: volume is too specific

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1588]
As a user I should probably be stopped from being able to put "3.333" in the volume field if the robot can't deliver that accuracy.

## Acceptance criteria
- Put a limit on decimal places for volumes with each pipette

## Design
**** We should find out what these limitations are

**Comment by umbhau** [comment]
@howisthisnamenottakenyet should this be a warning, or just a field character limit?

**Comment by umbhau** [comment]
@howisthisnamenottakenyet Closing this as a duplicate of #1589
