### ISSUE TITLE
File Management: Alert User of Unsaved Changes

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1602]
As a protocol designer, I would a warning before I navigate away from a protocol with unsaved changes, so that I don't accidentally lose my changes.

## Acceptance criteria
- Display a dialogue box is user attempts to navigate away from protocol designer browser tab/window
- Only display dialogue box if user has saved/added/deleted any step form or ingredient since last download (even if no changes)
- User has option to continue (and proceed away from PD) or cancel (and return to PD)

## Design and Copy
- Use browser default

**Comment by umbhau** [comment]
FYI @howisthisnamenottakenyet added a 'continue' and 'cancel' button to this story.
