### ISSUE TITLE
File Management: Upload Errors

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1610]
As a user if I can't open my file in PD I'd like to know why

## Acceptance criteria
- A modal in response to uploading a file in any of the following scenarios:

## Scenarios + Designs
- [ ]  **Incorrect file type**
_Title_: Incorrect file type
_Body_: 
- Only JSON files created in the Protocol Designer can be imported. 
- At this time Python protocol files are not supported.

- [ ]  **Invalid JSON file**
_Title_: This JSON file cannot be opened
_Body_: 
This file is either missing information it needs to import properly or contains sections that the Protocol Designer cannot read. 
- At this time we do not support JSON files created outside of the Protocol Designer
- If this is a Protocol Designer file that you have edited outside of this tool you may have introduced errors.

**Comment by umbhau** [comment]
Let's collapse error types:
1) Incorrect file type (and call out that we only support JSON + don't support the old .py files)
2) Invalid protocol file (correct file type but invalid protocol. including invalid pipetting steps, metadata, etc. can call out that files not created in protocol designer may not load)

**Comment by howisthisnamenottakenyet** [comment]
@umbhau Do you think this copy covers our cases?

**Comment by umbhau** [comment]
@howisthisnamenottakenyet -- one minor thing: 
"Only JSON files created in the Protocol Designer can be imported" and "At this time we do not support JSON files created outside of the Protocol Designer" aren't strictly true -- you _could_ create a JSON protocol outside the designer, as long as you followed the right formatting guidelines.

Maybe something like the below?

"Unsupported File Type
Please note the Protocol Designer only supports Opentrons 'JSON' protocol files (look for the .json extension at the end of the filename). "

"Invalid File Format
This protocol may have missing information or formatting errors. For best results, we recommend always using the Opentrons Protocol Designer to edit and save protocol files."
