### ISSUE TITLE
Reload view button breaks the view

### ISSUE THREAD

**Issue by rvinzent** [Opentrons/opentrons#1618]
## overview

This is a bug in the dropdown menu causing all app components to disappear.

## behavior
`Reload` button in the `View` dropdown causes everything to disappear except the menu bar.

## steps to reproduce
Open the app and press `Reload` or `Force reload` in the `View` dropdown. App components should disappear and fail to reload.

OS: Windows 10
App Version: 3.1.1
Robot: OT-2

**Comment by mcous** [comment]
Prod app tries to hit `/:pathname` on reload, which combines with the default electron request protocol of `file://`, so the app tries to hit `file:///pathname` (or `C:/pathname` on Windows) on reload.

The app entry point should check for this condition and re-write appropriately to allow react-router to kick in correctly
