### ISSUE TITLE
Runtime Calibration: Tip-probe should clear labware progress

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#1620]
## overview

- Version: `3.1.2`
- Ticket type: Bug

Depending on the order in which runtime calibration (tip probe, tiprack calibration, labware calibration) is done, the app can get put into a state where it thinks that a tip should be attached to the pipette, but the API thinks there is no pipette attached.

### expected

App should not perform actions that cause the robot to crash during runtime calibration

### actual behavior

If the user goes straight from tip-probe to non-tiprack calibration, the app will think there should be a tip on the pipette (because it assumes labware calibration always comes after tiprack calibration), but because of the tip-probe, the API will think there is no tip on the pipette and crash.

## steps to reproduce

1. Load protocol
2. (Optional) Run tip-probe
3. Calibrate all tipracks
4. (Re)run tip probe
    - Tipracks will now be disabled because they have already been calibrated
5. Try to calibrate the remaining non-tipracks with a tip on
    - Robot will crash

## proposed solution

If running tip-probe clears out tiprack/labware calibration progress in the app, this buggy path can be avoided.

**Comment by pantslakz** [comment]
Mike demo'd this issue, its the real deal 👍
