### ISSUE TITLE
File Management: Created and Modified Date

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1623]
As a protocol designer, I'd like to know when I created and when I last exported my protocol file.

## Acceptance criteria
- Protocol file includes 'created' date and 'last modified' date
- Display 'Date Created' in File Information section (nice to have, not required)
- Display 'Last Modified' in File Information section
- Display format should be Jan 01, 2018 | 2:01 PM EST

## Design
![image](https://user-images.githubusercontent.com/35570080/42100819-447f31de-7b8f-11e8-89cf-d6175560ad41.png)

**Comment by umbhau** [comment]
@howisthisnamenottakenyet @IanLondon 

Should this be 'Last Exported' or 'Last Modified'? I could see exports being a little weird to track, and a little confusing if you have multiple people passing a protocol file around.

**Comment by umbhau** [comment]
@IanLondon defer to you on JSON date format, though probably something human readable?

**Comment by howisthisnamenottakenyet** [comment]
@umbhau Last exported. One of its purposes at this time is to help you track when you last saved your work.

**Comment by umbhau** [comment]
@IanLondon epoch it is (so yes to 1, 2, and 3)
