### ISSUE TITLE
Run App: User Settings

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1632]
As a user, I would like access to settings for my Robot and Run App.

## Acceptance Criteria
- [ ] User can view 'Advanced Settings' section on Robot Settings page
- [x] User can view 'Advanced Settings' section on App Settings page
- [ ] User can toggle robot-level feature flags in the Robot 'Advanced Settings' section
- [x] User can toggle app-level feature flags in the App 'Advanced Settings' section

## Design
Zeplin > Run App Screens > 'Advanced Settings' tab

![screen shot 2018-06-08 at 4 33 04 pm](https://user-images.githubusercontent.com/2686086/41163619-778adef4-6b39-11e8-857a-f7edfbee07b2.png)
![screen shot 2018-06-08 at 4 32 49 pm](https://user-images.githubusercontent.com/2686086/41163621-77ac7c3a-6b39-11e8-8ee1-078f2abcac40.png)

**Comment by mcous** [comment]
@pantslakz for the moment, the only one we need for **app** is:

- Show dev tools (requires restart)

**Comment by pantslakz** [comment]
@mcous when user flicks this on - what do they see in the app? Do we require additional UI within the app to represent these dev tools?

**Comment by mcous** [comment]
@pantslakz, no, this just switches on the normal Chrome/Electron devtools. This is the same option that is automatically enabled when you run the application in development mode from source, so no additional UI is required

**Comment by pantslakz** [comment]
from ben:
https://github.com/Opentrons/opentrons/blob/edge/api/opentrons/config/feature_flags.py

**Comment by btmorr** [comment]
This looks fantastic. For the record, @pantslakz and I talked f2f, and the server is going to report a list of settings to expose through this panel in roughly the form:
```
{
  "settings": [
    {
      "title": "Calibrate to bottom of well",
      "description": "Perform labware calibration by moving the tip to the bottom-center of the well rather than the top-center (which is the default if this option is unset)",
      "value": true
    },
    {
      "title": "Other setting",
      "description": "Long description of next setting",
      "value": false
    }
  ]
}
```
@mcous do you have any thoughts/requests?

**Comment by mcous** [comment]
That response schema looks perfect

**Comment by btmorr** [comment]
Ticket for the backend work: #1656

**Comment by mcous** [comment]
JK still need to do robot settings

**Comment by umbhau** [comment]
@btmorr linking a ticket for blocker.
