### ISSUE TITLE
Use sidebar to hover and select wells in ingredient setup

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1636]
As a user it would be nice to be able to select all wells of an ingredient on a plate by clicking the ingredient list title. 

## Acceptance criteria
- When hovering over an ingredient list all wells containing that ingredient get the hover state
- When the ingredient list is clicked on and the form is opened, those wells get a selected state
- The ingredient list form is identical to the way other well forms behave: i.e. it's just a shorter way to click on all the wells

**Comment by mcous** [comment]
@howisthisnamenottakenyet and @pantslakz, is this ticket still valid?
