### ISSUE TITLE
TempDeck: Wait For Temp

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1657]
As a user, I would like to be able to pause a protocol until my TempDeck hits a specified temperature.

## Acceptance Criteria
- User able to pause (block) a protocol until their TempDeck hits its target temperature
- Target temperature inferred from last TempDeck.set_temp command.
- Note user-specified parameters may be added in a separate story.

## Implementation Notes
- Implement as a join with last set_temp

Sample protocol:
1) TempDeck.set_temp(60)
2) Pipette.transfer(whatever)
3) TempDeck.wait_for_temp()
4) Pipette.transfer(temp critical stuff)

**Comment by sanni-t** [comment]
PR #2144 closes this issue and completes the implementation of wait_for_temp() after going through a few iterations
