### ISSUE TITLE
Labware display names should be unique

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1662]
As a user, I would like to be able to differentiate different labware with the same name or nicknames, so that I can tell them apart when building steps.

## Acceptance Critieria
- First instance of a labware has no disambiguation number. 
- Second instance of same labware has (1) and further copies count up from there.

**Comment by IanLondon** [comment]
@howisthisnamenottakenyet Both are close enough in terms of work to implement that I think we should do whatever is a better experience.

Seems like the "disambiguation number" `Nickname (2)` is the most straightforward to me, and it follows the pattern that the non-nicknamed labwares use

**Comment by IanLondon** [comment]
This problem of sharing names can also happen when creating ingredients

**Comment by howisthisnamenottakenyet** [comment]
@IanLondon I'm a fan of the numbering version too. 

For ingredients if you give something the same name isn't it just treated as the same ingredient? Considering wells with the same ingredient can have different volumes and different descriptions.

**Comment by IanLondon** [comment]
@howisthisnamenottakenyet this is closed, right?

**Comment by mcous** [comment]
Closing this because I assume it was closed by #3600
