### ISSUE TITLE
On deck map slot numbers should be in the center of the slot

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1667]
## Design
![image](https://user-images.githubusercontent.com/35570080/41175657-c9b8d8d8-6b2b-11e8-858e-b28d27470680.png)

**Comment by IanLondon** [comment]
Note: @mcous's new deck map update should fix this (but right now it's forked off into a different component so PD won't use it until we integrate it)

**Comment by mcous** [comment]
I do believe this was fixed by #1892

<img width="803" alt="screenshot 2018-08-22 18 36 37" src="https://user-images.githubusercontent.com/2963448/44494585-56d65080-a63a-11e8-9f64-89f2ee2929dd.png">

**Comment by mcous** [comment]
Gonna close, but feel free to re-open if this was not properly addressed!
