### ISSUE TITLE
Separate Concerns of Form Validation and Processing

### ISSUE THREAD

**Issue by b-cooper** [Opentrons/opentrons#1699]
**Overview**

Currently all of the manipulation and cleaning of raw formData is happening in the same place that we are generating validation errors at the form level. In the interest of extendability, it would be helpful to separate these concerns.  This will particularly help the organization and standardization of our approach to form level validation.

**Comment by mcous** [comment]
@b-cooper is this ticket still valid?

**Comment by b-cooper** [comment]
@mcous This is no longer valid.
