### ISSUE TITLE
Drop tips asap

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1706]
As a user I would like to not have used tips on pipette 1 be dripping across the deck as pipette 2 does work. 

## Acceptance criteria
- If followed by always or once drop tips at end of step
- If followed by never hold onto tips

**Comment by howisthisnamenottakenyet** [comment]
@IanLondon Weird logic but in the case that Step 2 is "change tips never", should we add (or recommend in an alert) a blow out or touch tip to the last dispense in Step 1? I could still see someone not anticipating that their saved tips might be dripping.

**Comment by IanLondon** [comment]
Makes sense to warn them somehow! Is there some way we can make it easy for users to visualize that tips are being carried over?

**Comment by howisthisnamenottakenyet** [comment]
My instinct is: we can start with the disappearing tips in tip racks and see if that makes things clear, then add complexity if it doesn't.

**Comment by IanLondon** [comment]
Related: #969 (re-opened as a bug, feature regressed)

**Comment by IanLondon** [comment]
Also tip dropping on the **last** step for a pipette should happen eagerly - you can think of it like END will count as a "doesn't need tips" step
