### ISSUE TITLE
Tip Management: New Tip Required Error

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#1712]
As a user, I would like to be told if I accidentally create a first step without a tip. 

Note this could happen if your second step has 'change tip: use tip from previous step', and you delete the first step.

## Acceptance Criteria
- [ ] If first step has 'change tip: use tip from previous step', display a form-level error

## Design and Copy
- Error Title:
- Error Body:

**Comment by howisthisnamenottakenyet** [comment]
@IanLondon Would it be possible to disable the 'never' option in that scenario?

**Comment by IanLondon** [comment]
@howisthisnamenottakenyet 
We couuuld but then if a user deletes upstream steps (Step 1: always, Step 2: never, delete number 1) we still have to deal with it. And if later we allow copying and re-arranging steps, disabling options in general based on where the step is in the timeline makes that process more complicated.

**Comment by howisthisnamenottakenyet** [comment]
Fair! I'll add it as an on-blur warning in our errors doc. 

Ideally down the line when we have time it'd be nice to add more complex disabling logic.
