### ISSUE TITLE
Run App: Unsuccessful connection

### ISSUE THREAD

**Issue by pantslakz** [Opentrons/opentrons#1713]
As a user, I'd like to know if my robot is unable to connect to app.

## Design
![screen shot 2018-06-18 at 3 36 55 pm](https://user-images.githubusercontent.com/2686086/41545927-8f136858-731c-11e8-9d8a-231d96192299.png)

**Comment by mcous** [comment]
@pantslakz I assume this ticket also includes the removal of the existing unsuccessful connection modal?

**Comment by Kadee80** [comment]
ping @umbhau @pantslakz, see @mcous question above

**Comment by pantslakz** [comment]
Hey, 

This is a mistake on my end - I forgot we already had a modal here

We are currently in process of figuring out when to use modal vs alert banner - would suggest holding off on this ticket until we have rules defined. Modal is working fine for now - apologies if this caused additional work.

**Comment by mcous** [comment]
@pantslakz thanks for the update! Moving this ticket back to the backlog for the time being

**Comment by mcous** [comment]
Closing because I presume this is covered by existing modal + disabled robots in list via #2434 + new warning banners for unconnectable robots in #2455
