### ISSUE TITLE
API's GPIO module swallows write errors

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#1715]
## overview

If `gpio.py` fails to write a value to a pin, the error is swallowed.

## current behavior

`gpio.py` uses `os.system` to make write and read calls to the filesystem to interact with GPIO. `os.system` does not throw, instead it returns the exit code of the call. `gpio.py` is currently tossing the exit code, non-zero or otherwise.

## steps to reproduce

This is easiest to reproduce with the light toggle hitting virtual smoothie (see #1710). The set request will always `200` and the log will not produce any error. If you throw in `print` statement of the result of the `system` call, the result is non-zero.

## expected behavior

A failed write should throw or otherwise communicate the error

**Comment by mcous** [comment]
This bug is still present in 3.11.x

**Comment by sfoster1** [comment]
It doesn't do this anymore after the switch to `libgpiod` in #5381
