### ISSUE TITLE
Debug and Admin: Download Logs

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1727]
As a robot user, I would like to be able to download robot logs from my run app, so that I can share them with the Opentrons support team.

## Acceptance Criteria
- Button on Robot Settings page in Run App to download logs
- Clicking button downloads robot logs to user's laptop/desktop

## Design
- TBD (keeping it simple for now)
- @pantslakz

**Comment by pantslakz** [comment]
@mcous @umbhau what do you think about including this under "Advanced options" in "Robot Settings" ?

![screen shot 2018-06-22 at 3 23 42 pm](https://user-images.githubusercontent.com/2686086/41778790-1ba81654-7630-11e8-9205-4c2a9dd37cf6.png)
