### ISSUE TITLE
Usability: Deactivate Protocol Upload Button During Run

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1729]
As a user, I should not be able to upload a protocol while I have an active run, because it would interfere with the run.

## Acceptance Criteria
- [x] Deactivate protocol upload button during protocol run

**Comment by umbhau** [comment]
fyi @btmorr

**Comment by Kadee80** [comment]
In the current app, when a protocol run is in progress:
- the [protocol] button, along with the [calibrate] button in main nav is already disabled. 
- Confirmed this on Sunset. Ran a protocol and had Nusrat connect to Sunset. Upload was disabled on her app as well.

<img width="800" alt="screen shot 2018-06-25 at 4 54 31 pm" src="https://user-images.githubusercontent.com/3430313/41875403-c3f6c71e-7898-11e8-9c9c-460f8fac2fc8.png">
<img width="800" alt="screen shot 2018-06-25 at 4 55 22 pm" src="https://user-images.githubusercontent.com/3430313/41875406-c4061cb4-7898-11e8-9f8e-18bcfaf29c9c.png">
