### ISSUE TITLE
Robot Tuning: Blowout Speed Config

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1730]
As a robot tester, I would like to be able to set my robot's blowout speed, so that I can perform testing to determine the ideal default blowout speed.

## Acceptance Criteria
- [ ] Config value for blowout speed

**Comment by umbhau** [comment]
fyi @btmorr

**Comment by btmorr** [comment]
@umbhau is this still relevant?

**Comment by sfoster1** [comment]
You can do this now! The flow rate setters in both API v1 and API v2 let you configure blow out rate (or speed).
