### ISSUE TITLE
Deck Calibration should take Z-height into account for subsequent movements

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#1731]
## overview

During Deck Calibration, the user is directed to jog the pipette (with a tip on) to the deck to set the Z-height of the transformation matrix. However, the z-height data may not be taken into account for subsequent Deck Calibration movements (i.e. to spots 1, 2, and 3).

## current behavior

If this is the case, deck calibration is difficult on an improperly calibrated robot. Using the previous improper Z-height could result in excessive jogging (old Z too high) or crashing with the tip on (old Z too low).

## steps to reproduce

1. DC a robot incorrectly
2. Start DC again
3. Set Z-height correctly in Step 2
4. Observe if robot goes to new or old height in Step 3

## expected behavior

Z-height set in Step 2 should be reflected in following steps

**Comment by luigiferiani** [comment]
Very much second this. Having some issues now with a robot that plunges too deep, don't want to have to crash a new tip at every step of the calibration.
