### ISSUE TITLE
Modules: 'Modules' Information Card

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1735]
As a Run App user, I would like to be able to manage my modules from the 'Modules and Pipettes' page.

## Acceptance Criteria
- [x] New 'Modules' card on the 'Modules and Pipettes' page
- [ ] Modules card includes model 
- [ ] Modules card includes version number
- [ ] Modules card includes status 
- [ ] Modules card includes image of module type
- [x] Modules card displays something sane (either hidden entirely, or 'no modules connected') if the API returns a 404 (i.e., we haven't added the relevant API endpoints yet) 

## Implementation Notes
- We will likely build this before API support (before we have a 'Get Modules' endpoint), so (1) implementation of this story defines the endpoint and (2) we should have some sane handling for 404s

## Dependencies
- Need 'Modules and Pipettes' page #1564

**Comment by pantslakz** [comment]
No modules:
![screen shot 2018-06-23 at 3 34 32 am](https://user-images.githubusercontent.com/2686086/41804395-2751bed6-7696-11e8-87bb-e8ac6a9010bd.png)

Modules:
![screen shot 2018-06-23 at 3 34 43 am](https://user-images.githubusercontent.com/2686086/41804399-30c72b36-7696-11e8-9a22-4330504fac40.png)
