### ISSUE TITLE
Modules: Missing Module

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1737]
As a user, I would like to know if I'm missing a module required for my protocol

## Acceptance Criteria
- If a module required for a protocol is not connected, user should be notified when they reach the deck setup and calibration step.

- [ ] Missing module indicated on deck map
- [x] Text explanation of missing module 
- [x] Button to check for missing module (functionality covered #1738)

## Implementation Notes
- Includes retrieving protocol modules

## API dependency

- Depends on #1733 (modules in RPC API session response)

## Design
- @pantslakz

**Comment by pantslakz** [comment]
![screen shot 2018-06-23 at 4 08 00 am](https://user-images.githubusercontent.com/2686086/41804656-cd397be6-769a-11e8-8964-dbf42fd3c974.png)

Note on this:
@howisthisnamenottakenyet and I are still working out how to apply the alert system developed for PD to this. Morgan, I added the alert to the side nav - but one weird thing is that when you reach this page - the labware and modules are greyed out until tip rack is done... which makes it hard to know whats up - tho we are displaying it in the right hand page.
