### ISSUE TITLE
Modules: View in Deck Map

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1739]
As a user, I would like to be able to see my modules during deck setup and calibration, so I know where to place them.

## Acceptance Criteria
- [x] Modules displayed below labware on deck map during deck setup and calibration
- [ ] Slot labels include module type below labware information
- [x] Visual indication of successful connection (bad connection covered in #1737)

## Implementation Notes
- Dependent on Modules Field in RPC #1654

## Design
- Zeplin > Run App screens > 'modules' tag > 07a

**Comment by pantslakz** [comment]
![screen shot 2018-06-23 at 3 45 19 am](https://user-images.githubusercontent.com/2686086/41804498-a7763438-7697-11e8-9017-9cade68ddb0c.png)

**Comment by umbhau** [comment]
blocked by #1654
