### ISSUE TITLE
TempDeck: Real Time Status During Run

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1740]
As a Run App user, I would like to be able to see my TempDeck's status during a run.

## Acceptance Criteria
- [x] Display current temperature in Run sidebar
- [x] Display target temperature in Run sidebar
- [x] Display status (string) in Run sidebar

## Design Notes
- Status copy: 'heating', 'cooling', 'off', 'holding target temperature' (?)

## Implementation Notes
- What's the range for 'at target temp', and where is it defined? ensure UI status matches actual behavior.
- Dependent on 'Get Modules / 'Info' endpoint, #1653, including current and target temps
- Will just poll this endpoint 

## Design
Zeplin > Run App Screens > "modules" tag > 12

![screen shot 2018-07-24 at 10 45 37 am](https://user-images.githubusercontent.com/2686086/43146712-b99cd3e6-8f2f-11e8-8455-211de37dbc5c.png)

**Comment by pantslakz** [comment]
@umbhau are we tackling this in this sprint? I was under impression we'd include temperature status info in the logs, and come back to this idea later.

**Comment by umbhau** [comment]
No, almost certainly not. I dropped all the module stories in the sprint, but we will not get that far / Ben will move stuff out after estimation.

**Comment by pantslakz** [comment]
![screen shot 2018-07-24 at 9 59 38 am](https://user-images.githubusercontent.com/2686086/43143181-28be05cc-8f28-11e8-9a6e-82394553ea65.png)

**Comment by pantslakz** [comment]
@umbhau @mcous @btmorr just realized we could have more than one temperature module on the deck. Will whip up design to report status on more than one.

**Comment by umbhau** [comment]
If I haven’t forgotten something (totally possible), we’re only supporting one temp deck at launch (no way to distinguish between two USB ports/modules).
