### ISSUE TITLE
Protocol Library: Support for OT-2 Protocols

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1741]
As an OT-2 user, I would like to be able to access OT-2 protocol with full information in the protocol library.

## Acceptance Criteria
- [ ] Deck Map for OT-2 protocols
- [ ] Support for custom fields for OT-2 protocols
- [x] ~Support for CSVs for OT-2 protocols~ This is included in custom fields (-Ian)

## Implementation Notes
- [x] Make separate OT1 (2.5.2) / OT2  (some pinned 3.x.x) `opentrons` Python API virtualenvs to parse differently with each version
- [ ] Parse deckmap & custom field info for OT2 protocols, similar to how existing OT1 is working
- [ ] Now we're parsing protocol + README files individually into separate JSON file for each `*.ot1.py`, `*.ot2.py`, and `*.md` file. OT1 data, OT2 data, README data must be merged into one big JSON for ES under the top-level `protocols` key, and `categories` key must be populated from merging the individual README files
- [ ] Expand "protocols" part of the big final JSON to have keys for OT1 vs OT2 deck maps and customizable fields
- [ ] Using those new keys in the previous step, website (FE) toggles between showing deck maps & fields when user selects OT1/OT2 tabs
- [ ] Iframe mini React app with OT2 deckmap taking URL params to display deck configuration based on the new OT2 deck-related fields
- [ ] Put iframe OT2 deckmap into website

**Comment by umbhau** [comment]
fyi @Laura-Danielle @IanLondon @btmorr -- just created a short ticket to capture PL work for next week.

**Comment by IanLondon** [comment]
corresponding tickets are in `Protocols` repo and `protocol-library` repo (tho idk if `protocol-library` repo's ticket(s) are written yet)
