### ISSUE TITLE
Touch tip: bad coordinates on trough

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#1742]
## overview

It seems like non-circular wells are a problem for `pipette.touch_tip` fn.

Server version: `3.2.0-beta.1`
Firmware version: `edge-6168d32`

## current behavior

See comments in protocol code snippet:

```python
from opentrons import labware, instruments, robot

tiprack = labware.load('tiprack-200ul', 7)
trough = labware.load('trough-12row', 2)

pipette_single = instruments.P300_Single(
    mount='left',
    tip_racks=[tiprack])

pipette_single.pick_up_tip()

# Bad: leaves the bounds of the well, and even leaves the slot
pipette_single.touch_tip(trough[0])

pipette_single.drop_tip()
```

I think this might also be an issue with **other labware with non-circular wells** but I only tested trough. (I couldn't find any definitions for square-well 96 plates, etc)

(Touch-tip with `fixed-trash` and `trash-box` also cause collisions, but that's outside the scope of this issue IMO since there's not a great reason to touch tip on the trash, but it is important to be able to touch tip on a trough.)

## expected behavior

For the trough, I'd expect it to touch tip on each side of the rectangular well. But instead, it knocks the trough over and potentially crashes into a neighboring labware in another slot.

Also with a multi-channel in a well of a trough, I'm not sure if I'd expect it to touch-tip in the same way as I'd expect it to touch-tip with a single-channel. Maybe it would only move perpendicularly to the 8 tips. But it should touch-tip in some way that doesn't knock into or past the sides of the trough's wells, even with a multi-channel.

**Comment by bndo** [comment]
We believe this is limited to API v1 and will be addressed as part of API v2.
