### ISSUE TITLE
HandleKeypress in Styleguide doesn't let you type q/w/e keys in code blocks

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#1764]
## overview

Can't type q/w/e into code blocks in styleguide

## current behavior

`HandleKeypress` example in styleguide page prevents normal behavior of using keys

## steps to reproduce

Type q/w/e in Component Styleguide while trying to modify a code block

## expected behavior

q/w/e keys should type letters into the code blocks, not be ignored

**Comment by mcous** [comment]
`HandleKeypress` prevents default on any keys that are handled. This is necessary for certain use-cases, but should likely be configurable
