### ISSUE TITLE
Nav buttons are different heights

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1775]
## Acceptance criteria
- Nav buttons are currently different heights. Should be the same height. 
![image](https://user-images.githubusercontent.com/35570080/42057456-5874593e-7aeb-11e8-81f6-58fc89228feb.png)

**Comment by IanLondon** [comment]
@howisthisnamenottakenyet is this still messed up or did we fix it a few months ago by making the icons square?

**Comment by howisthisnamenottakenyet** [comment]
@IanLondon It's still messed up. Was not able to figure out how to fix the icons in sketch.
