### ISSUE TITLE
Update labeled value component in PD

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1783]
## Acceptance criteria
- Labels for this component are now bold and Aa case 
- Update the labeled value component that displays pipette information on the file details page

## Design
![image](https://user-images.githubusercontent.com/35570080/42100838-5236e024-7b8f-11e8-8b56-9bd0a26f2952.png)

**Comment by umbhau** [comment]
@howisthisnamenottakenyet Should form labels have the same style?

**Comment by howisthisnamenottakenyet** [comment]
@umbhau Decided on no. In PD there's a bunch of form fields all packed together and I think that'd make it look more cluttered. 
![image](https://user-images.githubusercontent.com/35570080/42172540-49bd61e0-7dea-11e8-8eb7-99499c3fcb43.png)

**Comment by umbhau** [comment]
@howisthisnamenottakenyet sounds good. 

To summarize:
- Value labels will be in **Title Case**, e.g. "Left Pipette"
- Field labels will be in **Sentence case**, e.g. "Tip rack"
- Field 'category headers' (?) will be in **SMALL CAPS**, e.g. "TECHNIQUE", "CHANGE TIP", and "FLOW RATE"

Is that right?

**Comment by howisthisnamenottakenyet** [comment]
@umbhau yup! I updated the component pages for form fields and labeled values in zeplin to reflect that

**Comment by IanLondon** [comment]
How does this affect Run App? Not sure if I'm following

**Comment by howisthisnamenottakenyet** [comment]
@IanLondon The component for pipettes in the run app calibration flow is the same as ours for file details

**Comment by IanLondon** [comment]
@howisthisnamenottakenyet Double-checking: this is just changing the `LabeledValue` component instances inside the pipette group component (called `InstrumentGroup`), and NOT changing all `LabeledValue`s across PD + Run App, right?
