### ISSUE TITLE
Update file page sidebar buttons

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1784]
A couple testers were confused as to why the export primary button existed before they made or imported a protocol. 

## Acceptance criteria
- Disable the export button unless there is a protocol open
- Reorder
- Return "import JSON" button to "import"

## Design
![image](https://user-images.githubusercontent.com/35570080/42334158-98fbc1ae-804a-11e8-83ee-04452d202427.png)

**Comment by pantslakz** [comment]
@howisthisnamenottakenyet curious as to the order of these - 
think it would make most sense to have "Create New" at the top, following by "import" and "export" once option is available. thoughts?

**Comment by pantslakz** [comment]
@IanLondon @howisthisnamenottakenyet let's address ordering and text of the buttons in this ticket as well:

Create new
Import protocol
Export protocol
