### ISSUE TITLE
Website: TempDeck Whitepaper

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1794]
As a potential TempDeck customer on the website, I would like to be able to read the latest TempDeck whitepaper, so that I can get detailed specs and performance characteristics before making a purchasing decisions.

## Acceptance Criteria
- [ ] User able to download TempDeck whitepaper from 'modules' page on Opentrons website.

## Design
- 'Read Whitepaper' button should be in right sidebar (below 'voltage')
- 'Read Whitepaper' button should be blue, and 'Buy' buttons should be changed to orange (see button style in 'Pipettes' section

## Resources
Whitepaper:

[Opentrons Temperature Module White Paper.pdf](https://github.com/Opentrons/opentrons/files/2551061/Opentrons.Temperature.Module.White.Paper.pdf)

https://docs.google.com/document/d/1Mlv2LxL8rmZ9vaOwx3AIiWIqNDltvo2Daxp6-D8AJsI/edit#

**Comment by mcous** [comment]
https://github.com/Opentrons/opentrons/commit/1bf8bd7 referenced the wrong issue. Not sure why. Re-opening

**Comment by mcous** [comment]
Closed by Opentrons/opentrons-dot-com#99
