### ISSUE TITLE
Distribute bug- some destination wells display as mixed

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1812]
In a user test Piul was taking Ingredient 1 and distributing it into wells that had two states: empty or Ingredient 2. 

In the case where Ingredient 1 went into empty wells the side panel showed that Ingredient 1 was going into a well with Ingredient 1 in it. 

In the case where Ingredient 1 was going into wells with Ingredient 2, the side panel showed that Ingredient 1 was going into a well that already contained Ingredients 1 & 2. 

It seems to me like distribute was displaying the destination well state after the distribute, not their state before the distribute. 

---

It happened again in Cindy's usertest in two different ways:
![image](https://user-images.githubusercontent.com/35570080/42775610-cca5cd7c-8902-11e8-83d4-812d0432cff0.png)
![image](https://user-images.githubusercontent.com/35570080/42775692-fe802658-8902-11e8-96c8-3250e4010a0d.png)

**Comment by howisthisnamenottakenyet** [comment]
@IanLondon Feel free to edit this bug ticket to make more sense as to what went wrong technically

**Comment by IanLondon** [comment]
@howisthisnamenottakenyet Looks good to me! I put it in the upcoming sprint
