### ISSUE TITLE
RPC: Remote call errors should include traceback for logging in the app

### ISSUE THREAD

**Issue by rvinzent** [Opentrons/opentrons#1841]
## current behavior
Only the error message is displayed when there is an error loading a Python script. I think it would be beneficial to be able to see the full traceback. There are some situations when writing protocols where it would be highly beneficial to see the full traceback especially without access to the debugger.

## expected behavior
I am proposing that the full traceback be displayed when the developer tools option is turned on.

**Comment by mcous** [comment]
Hey @rvinzent, thanks for the request!

Good idea, the traceback in the console / app logs would be useful in these situations. I just did some experimenting, and it's not too hard to tweak things so the API sends it over to the app in the event of an error. Gonna see if I can sneak this in tomorrow
