### ISSUE TITLE
Feature Request: Show when the deck was last calibrated

### ISSUE THREAD

**Issue by rvinzent** [Opentrons/opentrons#1848]
## overview

Another QOL feature that would display the date of last deck calibration in deck calibration box.

One of the problems with the OT-1 is that the calibrations would slowly become slightly inaccurate over time and lead to crashes. It would be convenient if the app told me when the last calibration was performed, at least for the deck, and possibly for saved protocol calibrations.

## current behavior

The Deck Calibration box looks exactly the same whether the deck has been calibrated or not. After calibration there is no indication that the calibration was just performed.

## expected behavior
Deck calibration box could display the last calibration date in the corner or in the modal when you click calibrate. This would make it easier to ensure the deck has been calibrated within the last month or so to have better QC.

**Comment by mcous** [comment]
Thanks for the request! This feature is already planned and being tracked over in #1217. You can keep an eye on that issue for progress as we develop
