### ISSUE TITLE
Labware Definitions: 364 and 96 Flat

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1863]
As a robot user, I would like accurate labware definitions for the 384 and 96 well plates.

## Acceptance Criteria
- Update labware definition for 384 Flat
- Update labware definition for 96 Flat (recently updated by Z is still incorrect)
- Update should apply to new JSON labware definitions; users of old 'containers' definitions should not be affected

## Resources
- Labware definitions available here:
https://docs.google.com/spreadsheets/d/1sbOMbBnn0QFs4J44gIbkitPoEo8gW7d7Nz9nd-5J0EU/edit#gid=0

**Comment by btmorr** [comment]
Closing in favor of prioritizing the new labware definition system
