### ISSUE TITLE
Edits to not enough tips error

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1881]
As a user i'd like to know which tip rack i need to place on the deck

## Acceptance criteria
- Change body of the error banner to read "Add another {Tip rack type} to an empty slot in Deck Setup"

**Comment by IanLondon** [comment]
Spoke with Morgan & Brian about this, having timeline errors display dynamic info (like tiprack type) would add a moderate amount of complexity to them, it'd be nicer to do this later when either we see several timeline errors needing this or after we do internationalization

**Comment by IanLondon** [comment]
@howisthisnamenottakenyet @umbhau where should punted/backlogged tickets go?
