### ISSUE TITLE
Robot Reliability: Reevaluate Data Types and Locations

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1904]
As a user, I would like to reduce data read/write from the thumb drive, to mitigate impact of thumb drive issues.

## Acceptance Criteria
- Data should be written to both /data (persistent data managed by resin) and thumb drive
- Data should be read from /data
- If data not found in /data, read from thumb drive and copy to /data
- if thumb drive also empty, use defaults.

## Implementation Notes
- We hypothesize that thumb drive may not be able to handle high volume of read/writes, and that this may be contributing to thumb drive going read-only
- Need to define what data is in scope for this

**Comment by umbhau** [comment]
@btmorr fyi, as per our discussion

**Comment by btmorr** [comment]
This has been obviated by other work
