### ISSUE TITLE
Tip Use Per Step: Change Tip Copy

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1933]
As a protocol designer, I would like clear tip management choices, so that I can make accurate choices about when to use a fresh tip.

## Acceptance Criteria
- [ ] Update label and option copy in the 'Change Tip' field as follows:
- [ ] Transfer, Distribute, and Consolidate should be the same (have all options)

Field Label: Change Tips
Option 1: Use a new tip for this step
Option 2: Use a new tip for this step, and every transfer within this step.
Option 3: Use tip from previous step

## Design
![image](https://user-images.githubusercontent.com/35570080/43478385-c2b556c8-94cb-11e8-95c7-a0a7706f5a75.png)

**Comment by IanLondon** [comment]
@howisthisnamenottakenyet is this still WIP or should we remove the WIP label?

**Comment by howisthisnamenottakenyet** [comment]
@IanLondon we're good to go
