### ISSUE TITLE
Fix: labware overlay component PD

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1943]
The save nickname overlay state for deck labware should match the other overlays

## Acceptance criteria
For the nickname save state:
- [ ] Have opacity of the labware overlay match
- [ ] Even vertical spacing of elements

## Currently looks like
![image](https://user-images.githubusercontent.com/35570080/43279791-0af49f9a-90dd-11e8-9c94-f9aa4577fb0f.png)

## Should look match
![image](https://user-images.githubusercontent.com/35570080/43279810-18806d4c-90dd-11e8-9d00-9915e4b620d4.png)

**Comment by b-cooper** [comment]
Closed as it was addressed in #3479 and following updates to the deck map
