### ISSUE TITLE
PD Labware: Add P300 TipRack; Remove P200 TipRack

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1955]
As a protocol designer, I would like to be able to use the P300 tiprack.

## Acceptance Criteria
- Add P300 tip rack to Protocol Designer
- Remove P200 tip rack from Protocol Designer

## Implementation Notes
- We currently only have the P200 tip rack

**Comment by pantslakz** [comment]
@btmorr

**Comment by btmorr** [comment]
We should replace those references in documentation and apps with "opentrons-tiprack-300ul"

**Comment by IanLondon** [comment]
I can get around this quickly for now by just renaming the dropdown, but...

@btmorr is `"opentrons-tiprack-300ul"` labware supported in API yet, or is it blocked by labware migration issues?

**Comment by IanLondon** [comment]
Actually this would be a pretty ugly hack, it would be 300 in the dropdown and 300 in the add labware modal, but 200 in the InstrumentGroup's "Tip Rack" LabeledValue, and also default to "TIPRACK 200 UL (1)" on the deck. I'm gonna call this blocked until there's API support for `"opentrons-tiprack-300ul"` labware
