### ISSUE TITLE
Unable to Connect Over USB

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#1964]
## Expected Behavior:
- User able to connect to robot via Run App over USB

## Observed Behavior
- User unable to see or connect to a robot via Run App over USB

## Steps to Recreate
_Note we have not been able to recreate this internally_
1) Plug in robot over USB
2) Open run app
3) Observe that your robot does not appear in the Robots List sidebar

## Resources

**Comment by btmorr** [comment]
We have primarily observed this on Windows 10 computers. It appears that there are some differences between the way that Windows supports IPv6 vs other OSes, and we have been using an IPv6 address in link-local mode that is not in the specified subnet for IPv6 link-local connections (we are using fd00:0:cafe:fefe::/64, correct link-local addresses are in fe80::/64). This may or may not be the only thing causing the problem, but in general IPv6 addressing is less well supported and understood generally, so we are going to switch to using IPv4 link-local addressing for ethernet connections.

Also, the previous configuration was done with `ip addr`, which does not have access to the host OS (ResinOS), which may have caused inconsistencies/race-conditions in how the ethernet port is initialized, so we are going to switch to using `nmcli` to configure the ethernet port, as `nmcli` does have access to the host OS and is able to ensure that connection management is handled in one place.
