### ISSUE TITLE
Tooltips: Liquid on wells and sidebar

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1985]
As a protocol designer, I would like full ingredient names displayed in tooltips in the deck setup sidebar or the well selection modal, so that I don't have to open the edit form to see my ingredients.

Display Tooltip in 4 (5?) Locations:
1) Sidebar > Source Well Ingredients (Pill)
2) Sidebar > Destination Well Ingredients (Pill)
3) Step Editor > Well Selection (Well)
4) Deck Setup > Well Selection (Well)
5) Deck Map > Well (out of scope for now; tbd if we want to add this eventually)

User Able to See:
1) State of ingredients in well before step 

3) Deckmap

## Implementation notes
1. This would be a good time to experiment a bit with different hover times before generating the tooltip. We don't want this to become annoying when scrolling through the sidebar or trying to select wells. 
2. We're using tooltips instead of the title tag bc these will soon be replaced with a more robust well contents report

## Sidebar Design + Acceptance criteria
- [ ] Hovering over the ingredient pill in the sidebar will produce a tooltip
- [ ] The tooltip will read out the name and volume of each liquid in the well. 
- [ ] The tooltip will contain any subtractions from the well
- [ ] The tooltip will display the "current" total volume in the well. That is to say the volume before aspirating or dispensing in the current tip you're on. 

## Well selection Design + Acceptance criteria
- [ ] Hover over a well in the well selection modal will produce a tooltip
- [ ] Same tooltip content as sidebar design

### Design notes
If it's not hard to have 2 different tooltip backgrounds and not too hard to experiment: I'd like to try it with a white background too. 

## Version with well info and version without well info
![screen shot 2018-09-17 at 10 04 52 am](https://user-images.githubusercontent.com/35570080/45627994-1b744980-ba61-11e8-8652-83d145558768.png)

**Comment by howisthisnamenottakenyet** [comment]
@pantslakz @umbhau 
These are the designs I have for the Sprint 36 'View Liquid Name in Wells and Ingredient Sidebar' part of our roadmap doc.

**Comment by umbhau** [comment]
Hi @howisthisnamenottakenyet, should well tooltip appear in well selection modal during both deck setup and step edit mode?

Otherwise -- made a minor formatting edit but looks good!

**Comment by pantslakz** [comment]
@howisthisnamenottakenyet given we're dealing with small wells and lots of info packed in a small space, would suggest adding a small arrow to the tooltip, so there's no confusion as to what it's referencing. i.e.:
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=2ahUKEwiG_Iecht3cAhVvMewKHW0UCTgQjRx6BAgBEAU&url=https%3A%2F%2Feclipsesource.com%2Fde%2Fblogs%2F2013%2F09%2F27%2Fcoming-up-rap-2-2m2-with-sexy-new-tooltips%2F&psig=AOvVaw0DKf4MFUA-arkFd-ykky-7&ust=1533803696061932

**Comment by howisthisnamenottakenyet** [comment]
@umbhau I don't see a reason why it shouldn't be there for both. 

@pantslakz Ok! I'll make a separate components update ticket for that.

**Comment by pantslakz** [comment]
@howisthisnamenottakenyet do we have a ticket for iteration 2?

**Comment by umbhau** [comment]
Closing in favor of #2409
