### ISSUE TITLE
Blow out destination options default, source well, and dest well

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1989]
Related to issue #1676

As a user I'd like better control over where blowout occurs. Currently my options are source plate A1, destination, trash. 

As a user I'd like a surfaced default selection, so I can't select blow out and then nothing in the destination dropdown

## Acceptance Criteria
- [ ] Blow out destination options are: (1) Source well, (2) Destination well, (3) Trash
- [ ] Blow out default displays in dropdown. There's no null state.

**Comment by IanLondon** [comment]
@howisthisnamenottakenyet did we want to remove blowout for Transfer? What about Consolidate?
