### ISSUE TITLE
Trash box displayed on top of slot number in deck map

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#1992]
## Acceptance criteria
- Trash should replace slot number, not overlap it

![image](https://user-images.githubusercontent.com/35570080/43544772-f8fb1480-95a1-11e8-801b-6e425e65e28b.png)

**Comment by b-cooper** [comment]
Trash box does not exist in PD >=3.0.0 so this is no longer relevant
