### ISSUE TITLE
App should generate and save a unique user ID for intercom

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#1999]
## overview

As an app user, I would like my Intercom conversation history to be preserved through app launches.

## current behavior

If the user closes the app, their intercom conversations and history are lost.

## implementation details

Similarly to how we generate a unique app_id for analytics purposes, we should generate another unique ID for use as the user ID. **This ID should be different than the analytics ID** so we cannot link specific users to specific analytics events.

**Comment by pantslakz** [comment]
@mcous I should note that this is happening even if user just closes app and restarts it - they lose their prior convo.

**Comment by mcous** [comment]
@pantslakz did not realize that was the case. Updated ticket and will prioritize higher, accordingly
