### ISSUE TITLE
Support: Add Run App and Robot Data to Intercom

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2019]
As a member of the support team, I would like to know the robot name and what pipettes they have when they contact us via intercom in the app.

## Acceptance Criteria
App automatically populates intercom with
- [x] the name of the connected robot if available
- [x] information about attached pipettes if available

## Already implemented
- App Version
- UID
- Name
- Email

**Comment by Kadee80** [comment]
Leaving this as blocked. After an extensive back and forth with intercom, it appears we are being throttled (20 calls per 30 minutes) and no intercom('update') calls are being executed properly.

**Comment by mcous** [comment]
Bug with intercom was a problem on our end where we were caching the intercom handler from window before it had been given the chance to load. Fixed by #2179, unblocking this ticket
