### ISSUE TITLE
Pipette swapping is available during protocol simulation, but does not function correctly

### ISSUE THREAD

**Issue by collinedington** [Opentrons/opentrons#2020]
## overview

While simulating a long protocol, you can step back to the robot panel and seemingly perform homing or pipette change operations.  The pipette does not move to the front left as it should be commanded, and does not detect the already installed pipette, even before swapping.

## steps to reproduce
Upload a protocol with a long for loop, then while the loading animation is running, enter the robot panel and try to perform homing or pipette change actions.

## expected behavior
Either gray out the robot panel, or (much better), run the protocol simulation in it's own thread and make the pi responsive to the commands during this process.  On a side not, protocol simulation can be unbearably long for complex recipes with loops, there has to be a way to avoid this step altogether... please.

**Comment by mcous** [comment]
Hey @collinedington, thanks for the feedback! We're aware that protocol simulation is annoyingly long. Unfortunately, it's the result of a series of poor architectural decisions that we're still trying to dig out of. We're making good progress, but we're a small team and don't have a timeline for when this work will be completed.

In the meantime, we can definitely look into the less ideal solution of some app-side workarounds to prevent access to stuff that isn't going to work during protocol simulation/run.

**Comment by Matt-Zwimpfer** [comment]
LMM - will be resolved as a by-product.

**Comment by mcous** [comment]
No longer applicable in the v5 release
