### ISSUE TITLE
Exit well selection mode for step + ingredient forms by clicking on modal outside of the well

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#2021]
As a user I'd like to be able to easily exit the well selection modal

## Notes
Follows a similar pattern for exiting out of move mode while placing labware. If you click on something outside of what is 'selectable' then you exit

## Acceptance criteria
- [ ] Clicking outside of the labware in well selection mode closes the well selection modal

## Design
![image](https://user-images.githubusercontent.com/35570080/43798414-8e666cf8-9a58-11e8-9c66-8d815820a73e.png)

**Comment by umbhau** [comment]
Further design questions:
- Are there modals you can or can't click out of? 
- If so, which modals fall into which categories, and how can we visually differentiate the two situations to users?

**Comment by pantslakz** [comment]
@howisthisnamenottakenyet looks currently implemented for 'steps > well selection', but not for 'starting deck state > labware > name & liquids". 

Also we should add 'esc' as a way to go back as well. please update ticket and check to see if there's any other duplicates.
