### ISSUE TITLE
Debug and Admin: Reset Robot (App)

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2030]
As a Run App user, I would like to be able to reset key robot configs to factory settings, as it's often a helpful troubleshooting step and currently has to be done from CLI.

## Acceptance Criteria
- User able to reset the configs/files specified in #1885 (TBD). 
--  Deck calibration
--  Length of tip
--  User labware calibration
--  Custom boot scripts
- User provided with name and brief description (?) of each config
- User able to select which configs/file to reset, and to reset them all at once
- User given a warning that this cannot be undone, and a chance to cancel or confirm. User also informed that robot will reset and that they will have to reconnect to robot.

## Design
- TBD @pantslakz 

## Implementation Notes
- Dependent on #1885 
- Design should be flexible to accommodate additional configs/data in the future.

**Comment by umbhau** [comment]
Few questions for @btmorr:

1 ) any reason we can't let the user opt to reset one or many configs at the same time (e.g. click reset and delete tip probe and deck calibration, but not labware calibration)?
2) besides deck calibration, tip probe, and user labware calibration, anything we want to include? (will also get input from support team)?
3) any thoughts on how we want to break down tip probe? e.g., can we allow the user to independently reset tip length, mount offset, etc.?

**Comment by Kadee80** [comment]
@umbhau re: conversation with pantea

- Moved the logs and reset buttons to the top of advanced settings card
<img width="1026" alt="screen shot 2018-08-22 at 3 30 01 pm" src="https://user-images.githubusercontent.com/3430313/44486704-5d58ce00-a622-11e8-8822-3917e4343fc9.png">

- Updated settings Names and Descriptions in the API response
- Changed from toggles to checkboxes 
<img width="1023" alt="screen shot 2018-08-22 at 3 30 16 pm" src="https://user-images.githubusercontent.com/3430313/44486705-5df16480-a622-11e8-945b-a7a0b36d5207.png">

- Clicking reset button successfully resets/removes the proper files. But a robot restart is required, much like a robot update
<img width="1024" alt="screen shot 2018-08-22 at 3 30 27 pm" src="https://user-images.githubusercontent.com/3430313/44486706-5df16480-a622-11e8-9843-998d3a6c9b6b.png">

- Once restart is initiated, user is informed that this may take a few minutes and is prompted to close the modal
<img width="1026" alt="screen shot 2018-08-22 at 3 30 36 pm" src="https://user-images.githubusercontent.com/3430313/44486707-5df16480-a622-11e8-8da8-0ddc993e0fd8.png">
