### ISSUE TITLE
Run Cancels After Robot Reset 

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2032]
## Expected Behavior
- User should be able to reset robot and start another run

## Observed Behavior
- Run initiated after a robot reset cancels 1-5 seconds after start

## Steps to Recreate
- Have not attempted to recreate
- Above steps observed on science robot by @kinnari-opentrons and @Laura-Danielle 

## Notes
- Possibly related to session management? - Laura

**Comment by mcous** [comment]
Closing as stale since we can't reproduce
