### ISSUE TITLE
Blow out transfer options doesn't expel all the liquid

### ISSUE THREAD

**Issue by rvinzent** [Opentrons/opentrons#2038]
## overview
The `blow_out` option does not perform its desired function very well.

## current behavior

`blow_out` has typically been a very important option for us especially when transferring small volumes of DNA. On the OT-One, we manually calibrate the plunger location to blow out the remaining liquid from the pipette and it works as expected. With the new pipettes, I guess the calibration is handled automatically, which is nice, but unfortunately the blow out plunger location doesn't work very well. The remaining liquid stays as a droplet on the edge of the tip. It just needs a little more blowing out to actually get the droplet off.

EDIT: 
[Here](https://media.giphy.com/media/jWlYNht6O5bsdtiJtl/giphy.mp4) is a video of the current blow out behavior on a normal transfer with the p10 single. Note the droplet on the edge of the tip.

## steps to reproduce
App version: 3.2.0
Robot server version: 3.2.0-beta3

Use `blow_out` on any transfer with the `P10_Single` pipette from the top of the well. A lot of the time, not all of the liquid is expelled.

## expected behavior

`blow_out` should actually expel all the liquid from the tip. It just needs a little more plunger action. I also don't really see how this would even be a valid option in the middle of a `distribute` command without an `air_gap` set. Perhaps if `blow_out` is set then there could automatically be an air gap set to allow it to function as expected, or it should probably be removed as a valid option for `distribute`.

#### Thanks for all your hard work!

**Comment by mcous** [comment]
Closing this ticket because, since it was written:

- We're on a new major version of the software (`v4`)
- We're on a new hardware revision of pipettes (`GEN2`)
- Pipette blow out position is now configurable (#3202)
