### ISSUE TITLE
Run log out of sync with actions after pause

### ISSUE THREAD

**Issue by rvinzent** [Opentrons/opentrons#2047]
## overview

The real time run log becomes out of sync with the actions of the robot after pausing and unpausing.

## current behavior

The app's log scrolling and highlighting action does not match with the robot's current actions after a pause.

## steps to reproduce

Run any protocol of moderate to long length. Pause in the middle of a run, wait for a minute, then unpause. Repeat if necessary. Actions should be out of sync with the run log after unpausing.

App version `3.2.0`
Robot server version `3.2.0`

## expected behavior

Run log should stay consistent with the actions of the robot.

**Comment by mcous** [comment]
Oops, this is a known issue that should have already been ticketed. Thanks for the report! Run log also may or may not be out of sync _before_ pause, too. Fun times

**Comment by simonchih** [comment]
App Pause may make magnetic module won't do engage or disengage with version 3.6.5.

**Comment by Matt-Zwimpfer** [comment]
LMH - known about and should be resolved in Protocol Engine

**Comment by mcous** [comment]
It gives me great satisfaction to finally mark this issue as resolved in v5
