### ISSUE TITLE
Documentation: Include brand/model of default container definitions

### ISSUE THREAD

**Issue by rvinzent** [Opentrons/opentrons#2050]
## overview

As a user it would be really helpful to know exactly which brands and models the default container definitions are based on. Then we could say "Hey, this isn't the brand of PCR plate I'm using. I should probably double check the dimensions".

This would help us diagnose issues that were invisible on the OT-One due to bottom-of-well calibrations.

**Comment by mcous** [comment]
We've just released our new [Labware Library](https://labware.opentrons.com) site that lists all of our built-in labware along with exactly which brands/models the definitions correspond to
