### ISSUE TITLE
Documentation: Update the container definition JSON location in the docs

### ISSUE THREAD

**Issue by rvinzent** [Opentrons/opentrons#2051]
## overview

Currently the default container visualization is being loaded from a JSON in the `master` branch last updated over a year ago. As a user, I would like to see an up-to-date list from the `edge` branch.

[Current docs](https://docs.opentrons.com/labware.html)

The link in question appears about a third of the way down the page.

**Comment by mcous** [comment]
Our newly launched [Labware Library](https://labware.opentrons.com) documentation site has launched with up-to-date visualizations
