### ISSUE TITLE
Feature request: ability to update custom container definitions

### ISSUE THREAD

**Issue by rvinzent** [Opentrons/opentrons#2059]
## overview

Updating a container definition is currently not supported. There is also no way to remove a custom container definition through the public API. As a user, I would like the labware database to be updated with the new definition when I run `labware.create` a second time on a container with the same name, or use a separate `update` or `delete` method to better interact with the custom labware.

## current behavior

Can only create containers through the API. Cannot update definitions because it violates the unique constraint on the `name` column. Cannot delete container definitions to clean up the database either.

## expected behavior

Basic CRUD operations supported by the API for interacting with the custom labware database.

Edit: I found the functions in `opentrons.data_storage.database.py` but they are not documented. This should be only a matter documenting them and exposing them in the `labware`.

**Comment by buffavaholic** [comment]
I also think it would be useful to be able to overwrite a container definition. Possibly this could be done by keeping the to be deprecated `opentrons.data_storage.database.overwrite_container()` function not as a calibration tool but to actually overwrite custom containers

**Comment by laserson** [comment]
+1. I created a custom container incorrectly and now my preferred identifier is "used up". Perhaps you could post a workaround for this to manually remove the container.

**Comment by mcous** [comment]
While drastic, the "Robot" > [Name] > "Advanced Settings" > "Factory Reset" > [x] "Labware Calibration" option will delete _all_ previously created custom labware in addition to modifications made to existing labware by runtime calibration. After labware reset+restart, the robot will take longer to boot than normal (several minutes) as it re-creates its labware database from the base definitions.

All our engineering energy is currently focused on removing and replacing the labware database with a more sane and reliable management system, so unfortunately additions to the current database API are unlikely. I'll make sure this stuff is on the radar as we continue to push documenation improvements, though. Sorry for the inconvenience and we appreciate your patience

**Comment by mcous** [comment]
We are completely re-doing how the robot deals with labware. We have released the first stage of this project (all new definitions, deprecation of the on-board labware SQL database).

To track the custom labware aspect of this project, I'd keep an eye on this milestone: https://github.com/Opentrons/opentrons/milestone/109
