### ISSUE TITLE
Trash font weight should be heavier

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#2061]
Currently font weight of trash looks lighter weight than the other slots. All slots should look the same (except shape for trash). 

![image](https://user-images.githubusercontent.com/35570080/45177622-74321f80-b1e1-11e8-895a-dd9d33703e41.png)

## Acceptance criteria
- Make TRASH also semibold

**Comment by b-cooper** [comment]
Closed as component was replace in #3479
