### ISSUE TITLE
Support multiple tiprack (and tip) types for one pipette during a protocol

### ISSUE THREAD

**Issue by utimcraig** [Opentrons/opentrons#2176]
Overview

  Hi, This is a feature request for a change in behavior in regards to aspirate_flow_rate and dispense_flow_rate.  I am trying to set up a phynexus phytip purification protocol (see this old video for a brief explanation of phytips: [https://www.youtube.com/watch?v=zYugcmFXDmc] ) . In part of the experiment, I want to use my 8 channel pipette to dispense normal liquids at normal speeds(~400uL/s), then I want to pick up the phytip columns (which have different lengths compared to standard pipette tips) and then aspirate and dispense at the much slower rate (~3uL/s).

current behavior

It would be good to be able to assign multiple aspirate/dispense and calibrations to the same piece of hardware in a single method, like this:

```
phytip_pipette = instruments.P300_Single(
        mount="right",
        aspirate_flow_rate=3.4,
        dispense_flow_rate=3.4,
        tip_racks=[phytip-plate])
p300_normal = instruments.P300_Single(
    mount="right",
    tip_racks=[p200rack],
)
```
Then in the method you could call these two pipettes that have different source racks and aspirate/dispense speeds.  It seems like this would be a good way for things to work because it should trigger calibrations for both the phytip_pipette and p300_normal (the tips are different heights). 
-->

steps to reproduce

  Currently assigning two profiles to the same hardware gives an error that the profile was already assigned.

expected behavior

  If you could assign two or more profiles to a piece of hardware in a method you could call these two pipettes that have different source racks and aspirate/dispense speeds.  It seems like this would be a good way for things to work because it should trigger calibrations for both the phytip_pipette and p300_normal (the tips are different heights).  I suppose the alternative to this is to buy two of the same pipettes, but even that limits the utility of the instrument.  Thanks for the help!

**Comment by utimcraig** [comment]
I suppose a way to suppress the error would also be fine as well as long as a calibration of the new pipette profile would be possible

**Comment by utimcraig** [comment]
Anyone around?

**Comment by mcous** [comment]
Hey @utimcraig, sorry for the delay in response! This is a good feature request; would it be accurate if I was to rephrase like so?

> I would like to be able to use one pipette with multiple kinds of tips during a single protocol

In your use case as described above (which I think you alluded to), you main problem with the software won't be the difference in aspirate and dispense speeds (which you can, and I would recommend should, solve by wrapping your aspirate/dispense functions, where you can also set those speeds).

The biggest problem will be that the tip length calculated by the tip probe procedure is stored as a property of the pipette, not of the tiprack (which was, in hindsight, not a great idea). So, without hacky workarounds, the robot probably won't be able to position itself correctly with one of your two tip lengths.

We've got a couple big projects in flight that deal with these areas of the software, so I'm going to move this ticket in there, where it will be updated if / when there's movement

**Comment by utimcraig** [comment]
Yes that seems correct.  Are the speeds working correctly now?  Good to
know.

**Comment by sfoster1** [comment]
This should actually work in Protocol API V2 - you can use different lengths of tips since the calibration is stored differently. You would still have to wrap your aspirate functions.

**Comment by mcous** [comment]
Closing since we believe using multiple tipracks of differing tip lengths with one pipette is no longer an issue in Protocol API v2. We do not intend to allow more than one pipette object in the protocol to share one physical pipette, so as stated above, to use different speeds, please use the function parameters rather than relying on pipette defaults
