### ISSUE TITLE
Robot Singleton Refactor: Importing labware, containers, instruments should not implicitly require a robot singleton

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#2186]
Today, we have circular import problems because anything that depends on the robot singleton tries to import it and the robot singleton imports other stuff. Instead,

- [ ] Importing any of the things that are currently in Wrappers in `opentrons.__init__` should not implicitly require a robot singleton to exist at import time.
- [ ] There should not be circular dependencies between the robot and (instrument, labware, container) systems.

**Comment by btmorr** [comment]
Superceded by #2240, #2241, #2243, #2244
