### ISSUE TITLE
Distribute rows are not displaying properly

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#2208]
Jeremy User tester couldn't get a distribute From a 2nd column in a trough to display in rows, although deck map updated properly in final deck state. 
I tried changing the step so it aspirated from the first column of a trough instead, and the row in the sidebar appeared fine. 

![image 3](https://user-images.githubusercontent.com/35570080/45240671-75358080-b2b7-11e8-93bd-d9bb8a5a7c8f.png)
![image 4](https://user-images.githubusercontent.com/35570080/45240676-7797da80-b2b7-11e8-96aa-64c10ac22753.png)

Recreated by Morgan:
{
    "protocol-schema": "1.0.0",
    "metadata": {
        "protocol-name": "Problematic protocol",
        "author": "",
        "description": "",
        "created": 1536347041527,
        "last-modified": null,
        "category": null,
        "subcategory": null,
        "tags": []
    },
    "designer-application": {
        "application-name": "opentrons/protocol-designer",
        "application-version": "5af8fab6-dirty",
        "data": {
            "pipetteTiprackAssignments": {
                "pipette:p300_multi_v1.3:fb404df0-b2cf-11e8-ab49-475e427a035b": "tiprack-200ul",
                "pipette:p50_single_v1.3:fb404df1-b2cf-11e8-ab49-475e427a035b": "tiprack-200ul"
            },
            "dismissedWarnings": {
                "form": {},
                "timeline": {}
            },
            "ingredients": {
                "0": {
                    "description": "BTM",
                    "individualize": false,
                    "name": "BTM"
                }
            },
            "ingredLocations": {
                "1e769630-b2d0-11e8-ab49-475e427a035b:trough-12row": {
                    "A1": {
                        "0": {
                            "volume": 20000
                        }
                    },
                    "A2": {
                        "0": {
                            "volume": 20000
                        }
                    },
                    "A3": {
                        "0": {
                            "volume": 20000
                        }
                    }
                }
            },
            "savedStepForms": {
                "0": {
                    "id": 0,
                    "stepType": "distribute",
                    "step-name": "Distribute",
                    "step-details": "",
                    "aspirate_changeTip": "always",
                    "aspirate_disposalVol_checkbox": true,
                    "dispense_blowout_checkbox": true,
                    "dispense_blowout_labware": "trashId",
                    "aspirate_labware": "1e769630-b2d0-11e8-ab49-475e427a035b:trough-12row",
                    "aspirate_wells": [
                        "A1"
                    ],
                    "dispense_labware": "1c33d220-b2d0-11e8-ab49-475e427a035b:96-flat",
                    "dispense_wells": [
                        "A1",
                        "A2",
                        "A3",
                        "A4",
                        "A5",
                        "A6"
                    ],
                    "pipette": "pipette:p300_multi_v1.3:fb404df0-b2cf-11e8-ab49-475e427a035b",
                    "aspirate_disposalVol_volume": 60,
                    "volume": 250
                },
                "1": {
                    "id": 1,
                    "stepType": "distribute",
                    "step-name": "Distribute",
                    "step-details": "",
                    "aspirate_changeTip": "always",
                    "aspirate_disposalVol_checkbox": true,
                    "dispense_blowout_checkbox": true,
                    "dispense_blowout_labware": "trashId",
                    "aspirate_labware": "1e769630-b2d0-11e8-ab49-475e427a035b:trough-12row",
                    "aspirate_wells": [
                        "A2"
                    ],
                    "dispense_labware": "1c33d220-b2d0-11e8-ab49-475e427a035b:96-flat",
                    "dispense_wells": [
                        "A7",
                        "A8",
                        "A9",
                        "A10",
                        "A11",
                        "A12"
                    ],
                    "pipette": "pipette:p300_multi_v1.3:fb404df0-b2cf-11e8-ab49-475e427a035b",
                    "aspirate_disposalVol_volume": 60,
                    "volume": 250
                }
            },
            "orderedSteps": [
                0,
                1
            ]
        }
    },
    "robot": {
        "model": "OT-2 Standard"
    },
    "pipettes": {
        "pipette:p300_multi_v1.3:fb404df0-b2cf-11e8-ab49-475e427a035b": {
            "mount": "left",
            "model": "p300_multi_v1"
        },
        "pipette:p50_single_v1.3:fb404df1-b2cf-11e8-ab49-475e427a035b": {
            "mount": "right",
            "model": "p50_single_v1"
        }
    },
    "labware": {
        "trashId": {
            "slot": "12",
            "display-name": "Trash",
            "model": "fixed-trash"
        },
        "1c33d220-b2d0-11e8-ab49-475e427a035b:96-flat": {
            "slot": "1",
            "display-name": "96-flat",
            "model": "96-flat"
        },
        "1e769630-b2d0-11e8-ab49-475e427a035b:trough-12row": {
            "slot": "4",
            "display-name": "trough-12row",
            "model": "trough-12row"
        },
        "2203b490-b2d0-11e8-ab49-475e427a035b:tiprack-200ul": {
            "slot": "7",
            "display-name": "tiprack-200ul",
            "model": "tiprack-200ul"
        }
    },
    "procedure": [
        {
            "annotation": {
                "name": "TODO Name 0",
                "description": "todo description"
            },
            "subprocedure": [
                {
                    "command": "pick-up-tip",
                    "params": {
                        "pipette": "pipette:p300_multi_v1.3:fb404df0-b2cf-11e8-ab49-475e427a035b",
                        "labware": "2203b490-b2d0-11e8-ab49-475e427a035b:tiprack-200ul",
                        "well": "A1"
                    }
                },
                {
                    "command": "aspirate",
                    "params": {
                        "pipette": "pipette:p300_multi_v1.3:fb404df0-b2cf-11e8-ab49-475e427a035b",
                        "volume": 250,
                        "labware": "1e769630-b2d0-11e8-ab49-475e427a035b:trough-12row",
                        "well": "A1"
                    }
                },
                {
                    "command": "dispense",
                    "params": {
                        "pipette": "pipette:p300_multi_v1.3:fb404df0-b2cf-11e8-ab49-475e427a035b",
                        "volume": 250,
                        "labware": "1c33d220-b2d0-11e8-ab49-475e427a035b:96-flat",
                        "well": "A1"
                    }
                },
                {
                    "command": "blowout",
                    "params": {
                        "pipette": "pipette:p300_multi_v1.3:fb404df0-b2cf-11e8-ab49-475e427a035b",
                        "labware": "trashId",
                        "well": "A1"
                    }
                },
                {
                    "command": "drop-tip",
                    "params": {
                        "pipette": "pipette:p300_multi_v1.3:fb404df0-b2cf-11e8-ab49-475e427a035b",
                        "labware": "trashId",
                        "well": "A1"
                    }
                },
                {
                    "command": "pick-up-tip",
                    "params": {
                        "pipette": "pipette:p300_multi_v1.3:fb404df0-b2cf-11e8-ab49-475e427a035b",
                        "labware": "2203b490-b2d0-11e8-ab49-475e427a035b:tiprack-200ul",
                        "well": "A2"
                    }
                },
                {
                    "command": "aspirate",
                    "params": {
                        "pipette": "pipette:p300_multi_v1.3:fb404df0-b2cf-11e8-ab49-475e427a035b",
                        "volume": 250,
                        "labware": "1e769630-b2d0-11e8-ab49-475e427a035b:trough-12row",
                        "well": "A1"
                    }
                },
                {
                    "command": "dispense",
                    "params": {
                        "pipette": "pipette:p300_multi_v1.3:fb404df0-b2cf-11e8-ab49-475e427a035b",
                        "volume": 250,
                        "labware": "1c33d220-b2d0-11e8-ab49-475e427a035b:96-flat",
                        "well": "A2"
                    }
                },
                {
                    "command": "blowout",
                    "params": {
                        "pipette": "pipette:p300_multi_v1.3:fb404df0-b2cf-11e8-ab49-475e427a035b",
                        "labware": "trashId",
                        "well": "A1"
                    }
                },
                {
                    "command": "drop-tip",
                    "params": {
                        "pipette": "pipette:p300_multi_v1.3:fb404df0-b2cf-11e8-ab49-475e427a035b",
                        "labware": "trashId",
                        "well": "A1"
                    }
                },
                {
                    "command": "pick-up-tip",
                    "params": {
                        "pipette": "pipette:p300_multi_v1.3:fb404df0-b2cf-11e8-ab49-475e427a035b",
                        "labware": "2203b490-b2d0-11e8-ab49-475e427a035b:tiprack-200ul",
                        "well": "A3"
                    }
                },
                {
                    "command": "aspirate",
                    "params": {
                        "pipette": "pipette:p300_multi_v1.3:fb404df0-b2cf-11e8-ab49-475e427a035b",
                        "volume": 250,
                        "labware": "1e769630-b2d0-11e8-ab49-475e427a035b:trough-12row",
                        "well": "A1"
                    }
                },
                {
                    "command": "dispense",
                    "params": {
                        "pipette": "pipette:p300_multi_v1.3:fb404df0-b2cf-11e8-ab49-475e427a035b",
                        "volume": 250,
                        "labware": "1c33d220-b2d0-11e8-ab49-475e427a035b:96-flat",
                        "well": "A3"
                    }
         ...

**Comment by IanLondon** [comment]
^ Whelp, it's been more than a little while. Can't replicate!
