### ISSUE TITLE
Robot Singleton Refactor: Broker singleton should not be accessed through imports

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#2230]
Rather than using the broker singleton by importing the broker module and relying on the file state, we should be able to create a broker and pass it around to the parts of the system that need it.

**Comment by btmorr** [comment]
Need to determine what's going to happen with the broker and live-update in RPC removal, so that we don't waste effort building on something that's going to change.

**Comment by sfoster1** [comment]
This is an unnecessary level of effort on top of the rest of the singleton refactor and will likely organically be removed during future work that will significantly alter the way the RPC works in general.

**Comment by Laura-Danielle** [comment]
This was closed by PR #2920
