### ISSUE TITLE
Robot Singleton Refactor: hardware_control move() and move_rel()

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#2234]
Add move and move_rel commands to the hardware_control module. This includes adding interactions with the smoothie. They should, at this point, duplicate the implementations in robot.

**Comment by btmorr** [comment]
A few comments to flesh out this ticket:
- I think the hardware_control move and move_rel methods should mirror the implementation of movement methods in Mover, not Robot
- we don't want to entangle hardware_control with protocol_api, so the interface for these methods should take strings (probably cannonized in enums that define valid strings) to identify which mount should be moved
- based on the signature of the hardware_control `API.move_to` method, this seems to be combined into a single function, but I think this results in unnecessary complexity (if both None, elif absolute, elif relative, elif both)--going to split it out into an absolute move function and a relative one
- hardware_control API will probably need to keep its own record of "current position" (e.g.: where was the last movement target)
- Controller will need to new up a Driver (and thus will need the config dict to contain whatever info is needed to new up the Driver)
- Simulator will need a behavioral analogue (try to share logic code to keep these in sync if possible), which should act exactly like a Controller would if every command succeeded
