### ISSUE TITLE
Geometry System Refactor: Use tip length from tip rack

### ISSUE THREAD

**Issue by btmorr** [Opentrons/opentrons#2271]
## overview

As a user, I want to be able to specify tip length on each tip rack, so that a pipette can use different types of tips without doing tip probe in the middle of a protocol. Tip probe should update the tip length offset of the associated tiprack definition (in the offset file--see #2269)

**Comment by umbhau** [comment]
@btmorr @sfoster1 @sanni-t 

Should we use tip volume from tip rack as well, as part of this story?
