### ISSUE TITLE
Geometry System Refactor: Create All Supported Labware Definitions

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2277]
Definitions:
- tip racks
  - 10ul
  - 300ul
  - 1000ul
- tube racks
  - 15ml
  - 50ml
  - 15/50ml
  - 2ml screwcap
  - 2ml eppendorf
- aluminum block
  - pcr with plate
  - pcr with strips
  - 2ml tubes screwcap
  - 2ml tubes eppendorf
- plates
  - 96 pcr
  - 384 pcr
- troughs
  - 12 row
  - 1 row
  - trash box
  - short fixed trash
  - tall fixed trash
- modules
  - Temperature Module
  - Magnetic Module

Review list w/ Science and Protocol Dev teams

**Comment by btmorr** [comment]
Done by prior work. Also partially redundant to #2614
