### ISSUE TITLE
AKC timeout error for JSON files

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#2279]
Sometimes i get this error trying to import a JSON file into the run app. If I keep trying eventually it does successfully import though. 
![image](https://user-images.githubusercontent.com/35570080/45569557-d7e5c980-b82d-11e8-9a85-1a0c38515339.png)

**Comment by mcous** [comment]
@howisthisnamenottakenyet do you have a protocol handy where this happens often?

@IanLondon my best guess here is that something about the JSON handling in `session.py` is blocking the RPC server until it's done, which could prevent the ack from coming back within the timeout (currently set to 10 seconds)

**Comment by mcous** [comment]
Haven't seen this happen in a while, and assume it was related to some of the old simulation bugs. Regardless, will no longer be an issue with RPC removed, so closing this issue

**Comment by ethanfjones** [comment]
@mcous I have a user experiencing this at the moment. I am going to reopen the issue. 

Every time I upload this protocol I lose connection with the robot. 

[AKC_timeout.zip]
(https://github.com/Opentrons/opentrons/files/3575714/AKC_timeout.json.zip)
