### ISSUE TITLE
Labware Definition Issue: 96-pcr Aluminum Block

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2292]
Labware definition for 96-pcr aluminum block is slightly off.

## Expected:
- Pipette should move to center of well during labware calibration

## Observed:
- Pipette moves too far back and left during labware calibration (not above well at all)

## Steps to Recreate
- Perform robot deck calibration
- Load a protocol with 96-pcr aluminum block
- Configure deck with aluminum block on temp deck and pcr plate on aluminum block
- Perform labware calibration and observe pipette move outside of well

Note this was only observed with the 96-pcr (other aluminum blocks are better)

**Comment by umbhau** [comment]
FYI @Laura-Danielle @btmorr

2 of 2 labware issues @mcous and I found while testing 3.4.0 labware updates. Let's consider this high priority and blocking 3.4.0 production release (and therefore use of new aluminum blocks)

**Comment by btmorr** [comment]
Strips for reference:

![96-pcr-strip](https://user-images.githubusercontent.com/5034659/45848796-cc971000-bcfd-11e8-8590-0897d34dc876.jpeg)

**Comment by btmorr** [comment]
It also appears that (in the existing labware definition system) we need to offset from the x and y of the machine drawings by -1mm and -6mm respectively, based on practical experimentation on multiple robots.
