### ISSUE TITLE
update server should have a higher limit on the size of request bodies

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#2311]
## overview

The update server uses the default request size limit of 2MiB and should increase that (via specifying a larger request size when creating the `web.Application`; see the `client_max_size` variable [here](http://docs.aiohttp.org/en/v2.3.8/web_reference.html#aiohttp.web.Application)

## current behavior

Uploaded wheels cap out at 2MiB before a 500 is returned. 

## steps to reproduce

Upload a wheel that is larger than 2MiB to server/update.

**Comment by mcous** [comment]
Resolved in 3.11.x
