### ISSUE TITLE
MagDeck engage method errors out when given a height

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#2312]
## overview

Discovered with @ahiuchingau 

MagDeck `engage` supports a `height` kwarg, but it throws an error when you try to use it.

## current behavior

Doing something like `mag_module.engage(height=18)` will throw error:

```
File "/path/to/python3.5/site-packages/opentrons-3.3.0-py3.5.egg/opentrons/commands/commands.py", line 364, in decorated
    res = f(*args, **kwargs)
TypeError: engage() got an unexpected keyword argument 'height'
```

Notice that this is coming from `commands.py`, not `magdeck.py`. I'm pretty sure it's the `@commands.publish` decorator on the MagDeck `engage` method that's failing, not `engage` itself.

## steps to reproduce

Call engage with a height in a protocol, and run the protocol on virtual smoothie or real robot.

## expected behavior

Don't blow up when given `height`. And maybe put the custom height in the message?

**Comment by sfoster1** [comment]
This doesn't happen anymore, though it doesn't put the height in there
