### ISSUE TITLE
PD Deck Setup: Sticky Start and End in Protocol Timeline + background colour

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2334]
As a protocol designer, I always want to be able to see the beginning and end of my protocol timeline in the protocol timeline sidebar.

## Acceptance Criteria
- 'Edit Protocol Deck Setup' is sticky at the top of the sidebar
- 'Result' is sticky at the bottom of the sidebar
- New background color for deck map in 'Edit Protocol Deck Setup'
- Change name of 'Starting Deck State' to 'Edit Deck Setup'
- Change name of 'Result' to 'View Result'

**Comment by umbhau** [comment]
on hold pending open design discussion w/ @pantslakz

**Comment by btmorr** [comment]
I'm pretty sure this is not a useful ticket anymore. Closing. @umbhau , @pantslakz , or @howisthisnamenottakenyet if there is something to be done related to this, please either re-open this ticket with details, or open a new ticket
