### ISSUE TITLE
Protocol Library: Markdown Rendering Omissions

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2337]
## Expected Behavior
- Reagents list (and other copy) included in PL markdown should render on protocol library page

## Observed Behavior
- Reagents list (and other copy) included in PL markdown not viewable in PL page

## Steps to Recreate / Example
1) Add following copy to protocol
```
### Reagents
* Diluent (Pre-loaded in row 1 of trough)
* Samples/Standards (Pre-loaded in Column 1 of 96-well plate)
```
- example here: https://github.com/Opentrons/Protocols/pull/333/files

2) Note list is not rendered on protocol library page:
- example here: http://protocol-delivery.protocols.opentrons.com/protocol/customizable_serial_dilution

**Comment by IanLondon** [comment]
may be fixed just by changing the number of `#`s in the README, a real solution is probably gonna be costly with things as they are

**Comment by btmorr** [comment]
@umbhau is this still relevant?

**Comment by btmorr** [comment]
Closing this as stale. Please open a new ticket if needed. (also note that the example snippet doesn't have any empty lines between the header and the bulleted list, which I'm pretty sure is not valid for a list in standard markdown--that might also be causing problems)
