### ISSUE TITLE
Provide AppImage for download

### ISSUE THREAD

**Issue by probonopd** [Opentrons/opentrons#2343]
https://github.com/Opentrons/opentrons/blob/caade747f405f663ca84e9c96b7bacc3ef5d46a7/app-shell/electron-builder.json#L31

Please provide the AppImage for download. Where can it be downloaded from?

**Comment by mcous** [comment]
Hi, we're in the process of publishing this release. The link will be [on our website](http://opentrons.com/ot-app) later today!

**Comment by mcous** [comment]
Links posted! We don't yet have stable links (our build links include the version number) because we've got some infrastructure consolidation to do. Once that work is done, I'll be looking into posting the AppImage build to the hub!

**Comment by probonopd** [comment]
Thank you very much.
