### ISSUE TITLE
Robots List (Connectivity): Display Reachable Robots

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2345]
As a Run App user, I would like to be able to see and interact with robots that are reachable, even if I cannot connect to them.

#### Robots that are reachable are displayed in the Robots List Sidebar
- [ ] Card is **not** greyed out
- [ ] Card has an alert icon
- [ ] Card should **not** display pipettes and modules
- [ ] Card should have a right chevron in place of the connection toggle

#### Robot Details Page should display a modified set of information and affordances:
- [ ] Update button is available if update server is up
- [ ] Information panel is available if update server is up
  - [ ] Information panel includes robot name, server version, and firmware version (current behavior)
  - Note we have access to but do not display API server version and System/Container version
- [ ] All other cards and affordances are greyed out / inactive

#### User should see a warning explaining their robot's connectivity state over the Robot Details Page 
- [ ] Copy TBD 
- [ ] Copy is different depending on whether:
  1. Robot is advertising but cannot boot any of its servers 
  2. Robot is advertising and can only boot update server

## Design and Copy

- https://zpl.io/aMvXMgJ
- https://zpl.io/25rjnDe

- warning copy: TBD

## Implementation Notes
- This scenario is possible in two cases:
  1. Robot is advertising but cannot boot any of its servers 
  2. Robot is advertising and can only boot update server
- Note we do know the connection method

**Comment by mcous** [comment]
> - This scenario is possible in two cases:
>  1. Robot is advertising but cannot boot any of its servers 

In this scenario, the "update" button cannot function. But this state is still very important to differentiate from a robot that is non-advertising

>  2. Robot is advertising and can only boot update server

In this state, however, with the update server up, the "Update" button can function
