### ISSUE TITLE
Manage Robot Connection: Updated Robot Connection Card

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2346]
As a Run App user, I would like to be able to see full details of my robot's connection state, so that I can make informed decision when managing my robot's connection.

## Acceptance criteria
- Update 'Robot Connection' card information as follows:
  - [ ] Display active connection method
    - "Your app is currently connected to your robot via [ Wifi | USB ]
  - [ ] Display the robot's internet connection status (see copy below)
  - [ ] Display USB connection details
    - [ ] Wired IP Address
    - [ ] Wired MAC Address 
  - [ ] Display WiFi connection details and management options
    - [ ] Wireless IP Address
    - [ ] Wireless MAC address
    - Dropdown filed to select/add WiFi connections (functionality not covered in this user story)

## Design
This design still requires discussion/refinement:
- https://zpl.io/bAExGmo

### Copy (Internet Connection Status)
Internet connection status may be one of the following:
- `"status": "none"` > "The robot is not connected to any network."
- `"status": "portal"` > "The robot is behind a captive portal and cannot reach the full Internet."
- `"status": "limited"` > "The  robot is connected to a network, but it has no access to the Internet."
- `"status": "full"` > "The robot is connected to a network and has full access to the Internet."
- `"status": "unknown"` > "Unknown"

**Comment by umbhau** [comment]
@mcous @pantslakz re: above open question, I'm suggesting we can hold of on persistently displaying connection status for both USB and WiFi, but should include internet status.

Assuming internet status is just 'Connected to Internet' or 'Not Connected to Internet', but please correct me on any of this.

**Comment by umbhau** [comment]
Agreed on the following with @mcous:

- Should we include a visible 'connection status' for both Wifi and USB, regardless of whether it is the actively used connection method? E.g for USB: 'Disconnected' or 'Connected'. This is obviously a little tricky with the word 'connectivity'. **_No_**
- Should we further include a visible differentiation of 'actively used' vs 'inactive' connection methods? 
- E.g. for USB: 'Disconnected', 'Connected - Inactive', or 'Connective - Active' - No? **_No_**
Should we include internet status in this card? If so, what are the options? - Yes? "Connected" | "Not Connected" **_Yes_**

**Comment by pantslakz** [comment]
To keep copy short, suggest "Your app is currently connected to your robot via [ Wifi | USB ]"
