### ISSUE TITLE
Manage Robot Connection: Display Wireless Network Details in Dropdown

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2347]
As a Run App user, I would like to see wifi strength and security details for wifi networks in the networks dropdown, so I can make an informed network choice.

## Acceptance Criteria
- Display 'lock' icon next to wifi network name if network requires authentication
- Display 'wifi' icon with network strength next to network name
- Display 'checkbox' icon next to actively connected network, if any
- Sort by connectivity (active connection at top), then alphabetically a-z.

## Design
- https://zpl.io/Vkn9mG5

**Comment by mcous** [comment]
Should this include some sort of checkmark for "currently connected network"? We've also got #1034 still hanging around

**Comment by pantslakz** [comment]
@mcous yes to checkmark
