### ISSUE TITLE
Robot update: communicate upgrades and downgrades more clearly

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#2354]
## overview

As a user, I would like my app to warn me if my robot's software is out of sync with my app so that I may take some action depending on my needs (see below).

A user may want to:

- Always be running the latest version of everything
- Stay on one specific version without updating
- Switch back and forth between beta and stable versions

Regardless of whether or not the app is fully up to date, if the user wishes to use that specific version of the app, the robot must be on a matching release to guarantee compatibility.

## current behavior

The app will alert the user if there is a version mismatch between the app and the robot, but this alert is generic and always uses language that suggests the user is upgrading the robot, when they may, in fact, be downgrading the robot.

## acceptance criteria

There are 4 scenarios in which a version mismatch could happen, and the app should message to the user accordingly:

- [ ] The app cannot find an update and its version is greater than the API
    - App should prompt the user to either "upgrade" their robot (default)  or
    - Ignore the mismatch
- [ ] The app cannot find an update and its version is lower than the API
    - App should prompt the user to "downgrade" their robot (default) or
    - Ignore the mismatch
    - Message should tell the user to ensure their computer is online so the app can ensure it is fully up to date
    - Example 1: Robot is on a beta version, app is on stable, needs to be downgraded to stable
    - Example 2: Robot was updated to latest stable by Bob, but Alice is currently connected over USB, running an older app, and isn't on wifi, so Alice's app doesn't know it's out of date
- [ ] The app _can_ find an update _and_ its version is greater than the robot's
    - The app should prompt the user to go to the App info page to update their app (default) or
    - Upgrade their robot to the out-of-date version or
    - Ignore the mismatch
- [ ] The app _can_ find an update _and_ its version is lower than the robot's
    - The app should prompt the user to go to the App info page to update their app (default) or
    - Downgrade their robot to the out-of-date version or
    - Ignore the mismatch

**Comment by mcous** [comment]
Re-opening pending final polish after design pass. Skeleton functionality / copy is in, though

**Comment by Kadee80** [comment]
Closing with current functionality/copy in favor of opening a separate design/UI pass ticket.
