### ISSUE TITLE
Feature Request: track tip rack state as a property of the tip rack labware rather than the pipette.

### ISSUE THREAD

**Issue by emernic** [Opentrons/opentrons#2381]
## overview

Changing tip tracking to be a property of the labware rather than pipettes would simplify complex use cases such as tip sharing between compatible pipettes, implementing custom tip iteration for applications such as cherry picking using multichannels, and serializing tip state so that LIMS systems can "remember" which tips have been picked from which tip boxes.

## current behavior
Current state of which tips have been used or not is tracked using an iterator for each pipette. Tip state cannot be determined by inspecting the tip rack labware item object. (if I am misunderstanding please let me know).

## desired behavior

Tip rack objects have some property such as `my_tiprack.unused_tips` which returns an array of the wells which still have tips in them. This array would be updated whenever tips are picked.

**Comment by mcous** [comment]
Related: #2176

**Comment by sfoster1** [comment]
This is how it works in Protocol API V2!
