### ISSUE TITLE
PD: don't use `.toFixed` for rounding

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#2405]
## overview

Everywhere in PD that we use `.toFixed` to round, we should make sure to use exponent notation instead so we don't get rounding errors.

http://www.jacklmoore.com/notes/rounding-in-javascript/

**Comment by mcous** [comment]
Rather than rolling our own thing can we use [`lodash/round`](https://lodash.com/docs/#round) instead?

**Comment by IanLondon** [comment]
@mcous good find, thanks!
