### ISSUE TITLE
Feature Request: Connecting to Robot in separate Network

### ISSUE THREAD

**Issue by aurelschwitter** [Opentrons/opentrons#2419]
## overview

Feature Request: Add the ability to connect to the robot with a specified DNS Name / IP Address. We cannot put the robot in the same network as our clients. So the autodiscover of robots does not work.
Please also provide an overview of what ports are used, so we can open the firewall accordingly.

## current behavior

The robot cannot be discovered.

## steps to reproduce

Place robot in separate network.

## expected behavior

Robot is discovered.

**Comment by aurelschwitter** [comment]
Hi @mcous 

Thank you for clarifying, it works well when using the IP Address in the config file.
However, it would be great if there's also a UI button for connecting to an IP address.

Thank you,
Aurel

**Comment by mcous** [comment]
Ping @pantslakz:

As a user who is able to connect to my robot over USB-to-ethernet (and connect the robot to Wi-Fi / obtain the robot's IP and MAC addresses) but who has a Wi-Fi network that does not support automatic discovery, I would like to tell my app to attempt to find a robot at that known address even though it can't automatically find it.

Reasons a Wi-Fi network may not support automatic discovery (which is based on a technology called mDNS):

- Network is built up of several smaller networks, as in the original feature request, which mDNS cannot traverse
- Network may block mDNS for security reasons

Reasons the initial USB success is important:

- The "Wireless" section of the connectivity card contains the IP address the user would end up entering in this list
    - In the future we can and should automate this
- The "Wireless" section also contains the MAC address that the network administrator could use to assign the robot a static IP address on the network, which would make this feature more reliable
    - Without a static IP, the network may assign a robot a different IP address after a period of time, meaning the user would then have to find that new address and enter it into the app as a new entry

Is there any additional information you need for this ticket?

**Comment by mcous** [comment]
This feature is now being tracked in the following tickets:

- #2740 
- #2741
- #2742
