### ISSUE TITLE
PD Liquids Management: Labware Details Card

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2428]
As a protocol designer, I would like to be able to view labware details in the sidebar during deck setup > liquid placement, so that I can reference the labware I'm working with.

## Acceptance Criteria
- [ ] Updated labware card in the 'initial setup > liquid placement' sidebar
  - [ ] Labware card includes the following:
    - [ ] Labware type
    - [ ] Labware nickname 
- [ ] Nickname is editable, see design below:

## Design
![image](https://user-images.githubusercontent.com/35570080/47461395-b2de6200-d7ae-11e8-942f-c4af4f4fa213.png)

**Comment by howisthisnamenottakenyet** [comment]
@umbhau do we want a separate ticket for that text field component?

**Comment by IanLondon** [comment]
I added the editability function to this ticked and bumped it up to a medium, instead of making a follow-up ticket
