### ISSUE TITLE
On OS X 10.11 app seems to require git installed in production builds

### ISSUE THREAD

**Issue by astaff** [Opentrons/opentrons#243]
The app shows a modal dialog saying `The "git" commands requires the command line developer tools...` on OS X 10.11. Seems like this is caused by some part of Python API calling `opentrons.__version__` which, in turn, when _version.py is missing is trying to call `git`

**Comment by astaff** [comment]
To be fixed by introducing version bump script and removing of versioneer

**Comment by mcous** [comment]
@astaff what version of the app is this referring to and is it still an issue?

**Comment by astaff** [comment]
used to be an issue because of `pyinstaller`-compiled binary was shipped with the app and version management tool (`versioneer`) has this weird dependency. closing this one.
