### ISSUE TITLE
Website: Magnetic Module Whitepaper

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2432]
As a potential MagDeck customer on the website, I would like to be able to read the latest MagDeck whitepaper, so that I can get detailed specs and performance characteristics before making a purchasing decisions.

## Acceptance Criteria
- [ ] User able to download MagDeck whitepaper from 'modules' page on Opentrons website.

## Design
- 'Read Whitepaper' button below 'voltage' on the right side (matching tempdeck whitepaper)

## Resources
Whitepaper:
[Opentrons Magnetic Module White Paper.pdf](https://github.com/Opentrons/opentrons/files/2551062/Opentrons.Magnetic.Module.White.Paper.pdf)

https://docs.google.com/document/d/1GbsSuUD_RzneZea2n_AO11nDeDQRWc8BlBdc2LXhmns/edit#heading=h.j1vxn55sxx1p

**Comment by mcous** [comment]
Closed by Opentrons/opentrons-dot-com#99
