### ISSUE TITLE
PD Liquids Management: Delete Liquids

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2437]
As a user, I would like to be able to delete liquids.

## Acceptance Criteria
- Button in liquids editor to 'delete' liquids
- Button is only active after liquid is created/saved
- User always sees a warning dialogue after clicking the button.
- Optional (time box / small): Skip warning if liquid has not been placed

## Design/Copy
- can use default browser modal (not modal in screenshot)
![image](https://user-images.githubusercontent.com/35570080/46676808-43ae1e80-cbaf-11e8-98e2-8f4cb6ddaf34.png)

**Comment by howisthisnamenottakenyet** [comment]
@umbhau @pantslakz I'd like to revisit the choice to show this every time you delete a liquid if we see that's a action users are doing frequently. In which case this modal is a bit intrusive to the workflow.
