### ISSUE TITLE
Need display names for EAP types

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#2439]
## overview

When we add EAP support to the run app front end we will need user-facing names to display for types of EAP security.

## current behavior

We only have `name` fields suitable for using internally as dict keys:
```json
{
    "options": [
        {
            "name": "ttls/eap-tls",
            "options": [
                {
                    "name": "identity",
                    "displayName": "Username",
                    "required": true,
                    "type": "string"
                },
               ....
```

## expected behavior

We should also expose a `displayName` field with something suitable for the user. We should decide whether we want to list outer and inner types separately, e.g.
```json
{
    "options": [
        {
            "name": "ttls/eap-tls",
            "displayName": {
                 "outer": "EAP-TTLS",
                 "inner": "EAP-TLS"
            },
            ....
```

or as one string, e.g.
```json
{
    "options": [
        {
            "name": "ttls/eap-tls",
            "displayName": "EAP-TTLS with EAP-TLS"
            ....
```

**Comment by mcous** [comment]
My preference would be for `displayName` to be a single string for ease of client use and API consistency.

Inner and outer security type seem like good structured information to have, so I'd be down to either a) add them as top level fields, too (e.g. `"outerType": "EAP-TTLS"`) or to punt until we have UI to display that data in a structured manned
