### ISSUE TITLE
PD Change Pipettes: Open Pipette Editor

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2474]
As a user, I would like to be able to open up the pipette editor from the File Details page.

## Acceptance Criteria
- [ ] New ‘Edit’ button in the ‘Pipettes’ card, next to the ‘Swap’ button
- [ ] ‘Edit’ button is primary button

## Design and Copy
Please treat below as a rough wireframe.

![image](https://user-images.githubusercontent.com/1682403/46891993-de219280-ce39-11e8-87e9-c4eac79ec5ff.png)

**Comment by pantslakz** [comment]
With the introduction of "Edit", would suggest we remove swap to simplify. 
I've not yet seen a user utilize swap and this was a short term solution until edit came up.
Additionally, 'Swap' feels like it belongs in run app more than PD.
