### ISSUE TITLE
PD Change Pipettes: Pipette Editor

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2475]
As a user, I would like to be able to change my protocol’s pipettes.

## Acceptance Criteria
- [ ] Clicking ‘Edit’ button in the ‘Pipettes’ card opens up the Pipette editor
- [ ] Pipette editor has copy explaining what happens when you change pipettes (see below)
- [ ] Pipette editor has the following fields (same as file creation modal);
  - Left Pipette (dropdown)
  - Left Tiprack (dropdown)
  - Right Pipette (dropdown)
  - Right Tiprack (dropdown)
- [ ] Pipette editor displays selected pipette images (same as file creation modal)
- [ ] Pipette editor has button ‘Cancel’ and close modal
- [ ] Pipette editor has ‘Save’ button (button functionality and warning modal in separate ticket.

## Design and Copy
Below is a rough wireframe
![image](https://user-images.githubusercontent.com/1682403/46892114-44a6b080-ce3a-11e8-93c7-3438148eaa55.png)

### Copy
"Please note this will affect any protocol steps you have already created"

**Comment by b-cooper** [comment]
Closed in #2548
