### ISSUE TITLE
Add labware to PD labware list

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#2538]
As a user I'd like to be able to select the tube rack with 1.5mL tubes in it instead of using the 2mL definition.

## Acceptance criteria
- Add the 1.5mL tube rack definition to the PD labware library

**Comment by umbhau** [comment]
@IanLondon @howisthisnamenottakenyet let's review labware list together

**Comment by IanLondon** [comment]
Now a duplicate of #2582 (since 99% of the work is in adding the new definition to Python and share-data)
