### ISSUE TITLE
Touch tip should have a definable height

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#2540]
As a user I would like touch tip to not happen above the well

## Background
- It's common to dispense slightly above a well. Touch tip should happen IN the well. 
- Ian pointed out this is good to have for reproducibility too

## Acceptance Criteria
- If you select touch tip it should generate a unit text field with "mm" as the unit. This field displays the default (measurement for top of well)
- Change touch tip tooltip to read "Touch tip to 4 sides of the well. Defaults to near the top of the well."
- Clicking the text field brings up the tip position modal
- In tip position modal limit height to the top of the well. There's no reason we know of to touch tip to air above the well. 
- Default should be 1mm below top of well

## Design
![image](https://user-images.githubusercontent.com/35570080/47448328-c200e800-d78d-11e8-893a-681facd8b3f6.png)
![image](https://user-images.githubusercontent.com/35570080/47448392-e78df180-d78d-11e8-9779-d8b503215679.png)

**Comment by howisthisnamenottakenyet** [comment]
@IanLondon @pantslakz Thoughts?

**Comment by pantslakz** [comment]
looks good to me!
