### ISSUE TITLE
Feature: Warn user before editing Wi-Fi settings while connected over Wi-Fi

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2551]
As a Run App user, I would like to be warned before editing the Wi-Fi configuration of a robot if I am solely connected to that computer over Wi-Fi.

## acceptance criteria

* [ ] If a user attempts to change or disconnect the robot's current Wi-Fi network, an alert modal is shown
  * This modal should appear _before_ whatever standard change or disconnect modal
* [ ] User has option to 'Cancel' or 'Continue' (and proceed with changing network)
* [ ] Clicking "cancel" closes the modal and cancels whatever change action
* [ ] Clicking "continue" proceeds to display standard disconnect or change UI

## implementation details
Modal title:

> Are you sure you'd like to change your robot's Wi-Fi settings?

Modal copy:

> You are currently connected to your robot via Wi-Fi. We recommend that you connect to your robot over USB before changing Wi-Fi settings. If you change your robot's Wi-Fi settings now, you will be unable to reconnect until you:
> 
> - Connect your computer to your robot via USB
> - Connect your computer to the robot's new Wi-Fi network
> 
> Are you sure you'd like to change your robot's Wi-Fi settings?

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535376428) by [Unito](https://www.unito.io/learn-more)

**Comment by mcous** [comment]
Superseded by #4850 and #4851

**Comment by mcous** [comment]
Ticket tweaked for re-opening

**Comment by Matt-Zwimpfer** [comment]
Not applicable/not a priority.
