### ISSUE TITLE
Robot Update: View Change Log

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2552]
As a robot and run app user, I would like to be able to view the robot change logs.

## Acceptance Criteria
- [ ] When user clicks 'View Update' in #2401, they see the robot update in a second modal
  - [ ] Robot Update contains robot change logs
- [ ] User has the following buttons for robot update
  - [ ] 'Update' 
  - [ ] 'Not Now'

## Design
https://zpl.io/adPpMj7

**Comment by Kadee80** [comment]
Closed via #2685
