### ISSUE TITLE
Robot Update: Downgrade Warning

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2556]
As a robot user, I would like to be warned before downgrading my robot.

## Acceptance Criteria
- [ ] If user opts to sync their robot to a lower version (downgrading their robot), they see a modal warning them that they are downgrading.
- [ ] Modal should show current and intended version of robot

## Design
@pantslakz

**Comment by Kadee80** [comment]
@umbhau @pantslakz this modal is not present in current design flow. Is this ticket still relevant?

**Comment by Kadee80** [comment]
Closing in favor of more recent designs.
