### ISSUE TITLE
Labware: Add Tip Volume to Tip Racks 

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2562]
As a robot user, I would like to know the maximum volume of the tip in my tiprack.

## Acceptance Criteria
- [ ] Track max tip volume as a property of tipracks
- [ ] Parse tip volume from tipracks 

## Implementation Notes
- We may use this to validate tip selection relative to pipette.

**Comment by umbhau** [comment]
@Laura-Danielle @sfoster1 @btmorr @sanni-t

**Comment by Laura-Danielle** [comment]
@umbhau since this is a value on the 'well' object of a tiprack, is this issue still relevant?

The info is accessible.

**Comment by umbhau** [comment]
Interesting! No, if that's the case, we're all set here. Closing this issue.
