### ISSUE TITLE
Tip Volume from Tip Rack

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2563]
As a robot user, I would like to use the tip volume read from the tip rack (tip), rather than from the pipette.

## Acceptance Criteria
- [ ] Use volume from tip rack in pipetting and in validations.

**Comment by umbhau** [comment]
@btmorr @sfoster1 @Laura-Danielle @sanni-t

**Comment by sfoster1** [comment]
Closed by #3781
