### ISSUE TITLE
PD Directory Structure cleanup

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#2589]
We have an inconsistent directory and export/import structure in some parts of PD.

## Redux "Atoms"

`load-file/` is a good example of the structure we want

`labware-ingred/` is probably the worst offender

## Components

* `elements/` - highly reusable, small. Kind of things that might exist in Components Library but are PD-specific (or just not migrated to component library)

* `scenes/` - "main page" that changes when you navigate. It's composed of many compounds.

* `compounds/` - a case-specific component, composed of many elements, is part of a scene (sometimes limited number of a few scenes). Example: Step Edit Form. It's specific for a certain case.

Plus the `App.js` entrypoint

## Containers

Ideally, the `containers/` directory should should go away and everything in there moved to `components/`, with the `index.js` doing the `connect()`.

Practically, that might be a lot of refactoring, but time-box it and see if it can be done.

## CSS

Now we have a lot of `Foo.js` + `foo.css`. Instead we should do:

```
compounds/Foo/
compounds/Foo/index.js
compounds/Foo/style.css

compounds/index.js # <-- so you can do `import {Foo} from '../path/to/compounds'
```

**Comment by umbhau** [comment]
@b-cooper @IanLondon 

Please make a milestone for this one.
