### ISSUE TITLE
Closing electron app does not turn off backend server

### ISSUE THREAD

**Issue by SimplyAhmazing** [OpenTrons/opentrons#260]
When I close my app I see the following log,

```
backend process successfully shutdown
info: Electron App window closed, quitting App
Not rewriting GET /exit because the client did not send an HTTP accept header.
```

And my backend server process is still running although the Electron process was terminated.

**Comment by astaff** [comment]
`Not rewriting GET /exit because the client did not send an HTTP accept header.` sounds like webpack hot reload which is `development`. Can you confirm this happens in `production`?
