### ISSUE TITLE
Marketing Analytics: Facebook Conversion Pixel

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2600]
As an Opentrons marketer, I would like to have the Facebook Ads tag on our website, so that I can retarget our website visitors on Facebook and track their conversions.

## Acceptance Criteria
- [ ] Add Facebook conversion pixel to opentrons.com

## Open Questions
- Conversion pixel, vs. Ad Tags/Ad Label API work?
- Just base pixel, or do we want to track [additional conversion points](https://developers.facebook.com/docs/facebook-pixel/implementation/conversion-tracking/)?
- Just every opentrons.com page, or other properties as well?

## Tag
[add tag here]

**Comment by mmonsees** [comment]
The Facebook pixel should be installed on subdomains www/protocols/shop as outlined in their [specs](https://www.facebook.com/business/help/402791146561655). This can be done first if necessary, as it is both easier and more essential to building up our audiences.

To track events as conversions refer to this [doc](https://www.facebook.com/business/help/952192354843755). I believe this is the direction we need to go: "For inline action events: add the event code between script tags next to the action you want to track (like a button)."

[facebook site Pixel ID 2204203016502596.txt](https://github.com/Opentrons/opentrons/files/2540402/facebook.site.Pixel.ID.2204203016502596.txt)

Discuss options on these:
fbq('track', 'AddToCart'); (for buy now from shopify product pages)
fbq('track', 'Schedule'); (for schedule a demo)
fbq('track', 'Contact'); (for intercom)
fbq('track', 'Lead'); (for email the team)

--




--
