### ISSUE TITLE
mix and blow_out options interact in unexpected way

### ISSUE THREAD

**Issue by jlmaccal** [Opentrons/opentrons#2607]
## overview

Bug: there is a strange interaction when both `mix` and `blow_out` that reduces accuracy.

## current behavior

```python
pipette.transfer(
        volume,
        source,
        dest_row,
        mix_after=(8, volume // 2),
        new_tip="always",
        blow_out=False,
    )
```

This code will result in the following sequence of events:
1. `volume` will be transferred from `source` to the first column of `dest_row`
2. it will be mixed 8 times
3. a blow out will be performed
4. it will be mixed 8 times
5. the tip will be discarded
6. repeat for all columns of dest_row

## expected behavior

The second mix step (step 4) is unexpected and not desired. It results in retaining a small amount of liquid in the tip, which reduces accuracy.

The desired sequence is:
1. `volume` will be transferred from `source` to the first column of `dest_row`
2. it will be mixed 8 times
3. a blow out will be performed
4. the tip will be discarded
5. repeat for all columns of dest_row

**Comment by btmorr** [comment]
@jlmaccal Under "Current Behavior", you have `blow_out=False`. Is this a typo, or is that how it is in your protocol? If it is set to False, I would not expect a blow out to happen at all. If `blow_out` is set to True, then there could be several sources of this behavior. Could you attach a larger portion of your protocol, at least including your pipette model, source, destination, and volume?

**Comment by mcrone** [comment]
I have this same problem. As soon as "blow_out=True" it duplicates the mix procedure.


```
for source, volume, dest, mix, discard_tip in zip(
            sources, volumes, dests, mixes, discard_tips):
        if not pipette.tip_attached:
            pipette.pick_up_tip()
        if mix == 'yes':
            if volume > pipette.max_volume:
                mix_vol = pipette.max_volume
            else:
                mix_vol = volume
            pipette.transfer(volume, source, dest, new_tip='never', blow_out=True, mix_after=(3, mix_vol))
        else:
            pipette.transfer(volume, source, dest, new_tip='never', blow_out=True)
        if discard_tip == 'yes':
            pipette.drop_tip()
    if pipette.tip_attached:
        pipette.drop_tip()
```

When I don't want to mix it is fine (output below):
```
Transferring 2.5 from well D1 in "1" to well B5 in "2"
Aspirating 2.5 uL from well D1 in "1" at 1 speed
Dispensing 2.5 uL into well B5 in "2"
Blowing out
```

When I do want to mix then I get this:
```
Transferring 2.5 from well A4 in "1" to well A4 in "2"
Aspirating 2.5 uL from well A4 in "1" at 1 speed
Dispensing 2.5 uL into well A4 in "2"
Mixing 3 times with a volume of 2.5ul
Aspirating 2.5 uL from well A4 in "2" at 1.0 speed
Dispensing 2.5 uL into ?
Aspirating 2.5 uL from ? at 1.0 speed
Dispensing 2.5 uL into ?
Aspirating 2.5 uL from ? at 1.0 speed
Dispensing 2.5 uL into ?
Blowing out
Mixing 3 times with a volume of 2.5ul
Aspirating 2.5 uL from well A4 in "2" at 1.0 speed
Dispensing 2.5 uL into ?
Aspirating 2.5 uL from ? at 1.0 speed
Dispensing 2.5 uL into ?
Aspirating 2.5 uL from ? at 1.0 speed
Dispensing 2.5 uL into ?
```
