### ISSUE TITLE
Wi-Fi: API disconnects from current network if configure to same network fails

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#2609]
## overview
#2159 added old connection cleanup to the wifi configure command, which was good. Unfortunately, this connection cleanup causes a problem if you attempt (for whatever reason) to reconnect to a network you're already connected to.

## current behavior
If you attempt (and fail) to connect to the Wi-Fi network your robot is already on, after your attempt your robot will not be on any network.

## steps to reproduce
1. Connect to a wifi network
1. Attempt to connect to the same network with bad credentials
1. Notice that your robot will no longer be on a network

## expected behavior
Failing to configure a new connection to the network you're already on shouldn't cause you to disconnect.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535385883) by [Unito](https://www.unito.io/learn-more)

**Comment by sfoster1** [comment]
This is actually not the old connections trimming (that only happens after you successfully connect to the new network), but this segment:

https://github.com/Opentrons/opentrons/blob/78b99c3a5f77d9f314ee0198ec88f35fc93ace49/api/src/opentrons/system/nmcli.py#L448-L453

NetworkManager identifies connections by uuid but still tries to make the human readable network names (which default to the ssid, and we duplicate that behavior for simplicity) unique. So we probably need to change the behavior on reconnect to either:

- Set a flag if a connection already exists
- If the flag is set, use a unique name for the new connection (by appending "-new" or something)
- If the new connection succeeds, trim the old connection and then rename the new one back to the correct name

Or:

- If the connection already exists
- Save the old connection settings
- Modify the connection to have the new settings
- If the connection fails, revert to the old settings
