### ISSUE TITLE
Geometry System Refactor: Generator Labware Defs

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/opentrons#2614]
## overview

With both generator functions now in place, it's time to start generating new labware to ship out! Below will be a comprehensive list of different labware that needs to be created. This is a comprehensive list which should be used as a _guide_, not a ticket.

Each PR which includes 5 labware definitions will be considered a small size. A comprehensive labware list with technical drawings can be found [here](https://docs.google.com/spreadsheets/d/1hXi63baR-oBM9HwKvWDP_Aba7VWVz1AA4dn9kixXgxA/edit#gid=38304232).

## Supported Labware List
- [x] 12 Channel Trough
- [ ] OT 1 Aluminum block
- [ ] Single Channel Trough
- [x] 6 Well Plate
- [x] 12 Well Plate
- [x] 24 Well Plate
- [x] 48 Well Plate
- [x] 96 well plate FLAT
- [ ] 96 well plate DEEP
- [x] 384 well plate
- [x] Fixed trash
- [ ] TipOne 10ul tiprack
- [ ] TipOne 200ul tiprack
- [ ] TipOne 300ul tiprack
- [ ] TipOne 300ul Filtered tiprack
- [ ] TipOne 1000ul tiprack
- [x] Opentrons 300ul tiprack
- [x] Opentrons 10ul tiprack
- [ ] Opentrons 1000ul tiprack
- [x] Opentrons 15mL tuberack
- [x] Opentrons 50mL tuberack
- [x] Opentrons 2mL tuberack snapcap
- [x] Opentrons 2mL tuberack twist
- [x] Opentrons 1.5mL tuberack
- [x] Biorad hardshell 96 well PCR plate
- [ ] Trash-box
- [x] Opentrons aluminum block 2ml eppendorf
- [x] Opentrons aluminum block 2ml screwcap
- [x] Opentrons aluminum block 96 PCR Plate
- [x] Opentrons aluminum block PCR Strips 200 ul

## Unsupported labware list
- Temperature Module [ Implemented in Code, no longer a definition]
- Magnetic Module [ Implemented in Code, no longer a definition]
- MALDI Plate
- E-GELGOL
- Rigaku Compact Crystallization Plate
- Small vial rack 16x45
- T25 and T75 Cell Culture Flasks
- Point
- Wheaton Vial Rack
- Tuberack 2ml 9x9
- Tuberack 5ml 96 wells
- Tiprack 1000ul chem
- Tiprack 1000ul H
- Tiprack 10ul H
- Tuberack 80 well
- Hampton 1mL deep block
- 24 Vial Rack
- 48 Vial Plate
- 96 Well Plate 20 mm

**Comment by btmorr** [comment]
@umbhau which of the unchecked boxes are still required?
