### ISSUE TITLE
Deck Calibration Update: Select Deck Type

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2621]
As a robot user, I would like to be prompted to indicate my deck type before deck calibration, so that my robot knows what deck calibration points to use.

## Acceptance Criteria
- [ ] User asked to indicate whether their robot has a calibration cross in slot 4
  - [ ] If Yes, ‘Deck Version’ advanced setting set to ‘2.2’ (tbd)
- [ ] User has option to remember selection for next time (selected by default)
- [ ] User has option to exit or continue

## Implementation Notes
- Do we want to save and then use the 'deck version' advanced setting to drive the UI (and therefore will the 'remember for next time' feature increase complexity)?

## Design
- https://zpl.io/VQ95MDA

**Comment by sfoster1** [comment]
All the crosses are on all the decks
