### ISSUE TITLE
Deck Calibration Update: Deck Not Compatible With Multi-Channel Pipette

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2622]
As a robot user, I would like to know if my robot cannot be calibrated with its current deck and multichannel pipettes.

## Acceptance Criteria
- [ ] If user indicates that they have an older deck (version =< 2.1; no calibration crosses in slot 4) AND they only have multi-channel pipettes attach, inform them that they cannot perform deck calibration with their current robot configuration
- User should either attach a single-channel pipette or contact our support team (we will send them a new deck or pipette)
- [ ] User has option to exit

## Design
- https://zpl.io/V4vBE84

**Comment by sfoster1** [comment]
All the crosses are on all the decks.
