### ISSUE TITLE
Deck Calibration Update: Deck Calibration With New Points

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2625]
As a robot user, I would like to be able to deck calibrate to the appropriate calibration points depending on the type of deck I have.

## Acceptance Criteria
- [ ] Update deck calibration with new calibration points, depending on type of deck
  - [ ] If user as a new-style deck (version >= 2.2, calibration cross in slot 4), guide user to calibrate to points in slots 4, 6, 10. (multi or single channel pipettes)
  - [ ] If user has an old-style deck (version >= 2.2, calibration cross in slot 4), guide user to calibrate to points in slots 1, 3, 10 (single channel pipettes only)

## Design
- 4 https://zpl.io/bWkxB8K
- 6 https://zpl.io/bLxAB9m
- 10 https://zpl.io/agrJ9mO

**Comment by sfoster1** [comment]
All the crosses are on all the decks.
