### ISSUE TITLE
Front-end tests mysteriously log assertion errors without any failures

### ISSUE THREAD

**Issue by SimplyAhmazing** [OpenTrons/opentrons#263]
Since repo refactor The front end tests seem have a strange error message that doesn't result in a test failure.

https://travis-ci.org/OpenTrons/opentrons/jobs/250194221#L3745

**Comment by astaff** [comment]
If you are referring to:

```
ERROR LOG: '[Vue warn]: Error in nextTick: "AssertionError: expected 0 to equal 1"'
ERROR LOG: AssertionError{message: 'expected 0 to equal 1', showDiff: true, actual: 0, expected: 1}
```

It's a Vue exception

**Comment by SimplyAhmazing** [comment]
It's odd this exception occurs now and what is causing it..
