### ISSUE TITLE
Button to turn PD hints back on

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#2652]
As a user I'd like to be able to restore my hints modals

## Acceptance criteria
- [ ] Rename "privacy" list item "app"
- [ ] Give this page the title "Opentrons Beta | App Settings"
- [ ] Turn the sidebar title to "Settings" (sentence case)
- [ ] Above the privacy card, add a hints card.

Copy:

Hints
"Restore all hint notifications"

## Design
![image](https://user-images.githubusercontent.com/35570080/48802269-c19c3400-ecdc-11e8-925b-bf0a2b069d45.png)

**Comment by howisthisnamenottakenyet** [comment]
@umbhau @pantslakz is this good to go?

**Comment by umbhau** [comment]
@howisthisnamenottakenyet looks good to me. could see us eventually just wanting an 'advanced settings' section like RA, and moving this in there...but with only one thing, this seems :+1::skin-tone-4:

**Comment by pantslakz** [comment]
Looks good, would just update copy:
“Restore all hints and tips modals”

**Comment by howisthisnamenottakenyet** [comment]
@pantslakz I believe modal is a dev/design term, and we can't expect everyone in our user base to know what it means.

**Comment by pantslakz** [comment]
True enough - how about "Restore all hints and tips notifications"

**Comment by howisthisnamenottakenyet** [comment]
@pantslakz updated
