### ISSUE TITLE
Mount Calibration: Migrate Old Mount Offset Data 

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2658]
As a robot user, I would like my robot to be behaviorally unchanged after updating my software to the new deck and mount calibration

## Acceptance Criteria

* [ ] If deck calibration found w/o timestamp
  * [ ] Set timestamp to last edit date (or 'now')
  * [ ] Set right mount offset to '0' with same date
  * [ ] Set left mount offset to mount offset data from robot conlfig with same date

Note: This will allow us to gracefully migrate users, but also _require_ mount calibration going forward

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535386887) by [Unito](https://www.unito.io/learn-more)

**Comment by btmorr** [comment]
@umbhau @sfoster1 is this still relevant? I think it's been superceded by other work

**Comment by mcous** [comment]
Closing as stale
