### ISSUE TITLE
Calibrate Pipette Mount: Prevent Protocol Run With Uncalibrated Pipette

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2660]
As a robot user, I should not be able to run a protocol if my pipette mount is uncalibrated

## Acceptance Criteria

* [ ] User not allowed to run protocol if a pipette that is used in the protocol is uncalibrated

## Design

* TBD @pantslakz 
* Option: User able to click on 'Run' tab, but 'Run Start' button is inactive. Modal permanently displayed with copy telling the user to perform a pipette mount calibration before run. Button to pipettes and modules page.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535387004) by [Unito](https://www.unito.io/learn-more)

**Comment by Matt-Zwimpfer** [comment]
This feature has been implemented. No longer possible to enter protocol run without pipette calibration/other calibrations.
