### ISSUE TITLE
PD liquid placement row edit

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#2673]
As a user it's easier on my eyes when spacing is consistent
![image](https://user-images.githubusercontent.com/35570080/48444193-39101780-e761-11e8-9daa-a7b754b9c7b2.png)

## Acceptance criteria
* Left and right borders for liquid cards is the same as for labware card
* All buttons are right aligned
* All buttons in rows are the same width as the expand/collapse carat
![image](https://user-images.githubusercontent.com/35570080/49738038-636bcc80-fc5c-11e8-8903-a86de8b0fcc6.png)

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535387220) by [Unito](https://www.unito.io/learn-more)

**Comment by umbhau** [comment]
@howisthisnamenottakenyet let's expand this to include alignment for all the data ('well', 'type', etc.) in these two cards.

Would you make explicit (and then we'll add to sprint)?
