### ISSUE TITLE
App should warn user before run that not all required modules are connected

### ISSUE THREAD

**Issue by simonchih** [Opentrons/opentrons#2676]
## overview
Temperature deck works fine if script only load temperature deck and temperature deck is  connected, but it will end at start if script load Temperature and Magnetic deck but only one deck is connected.

## current behavior
Opentrons GUI app will end at start if script load Temperature and Magnetic deck but only connect one.

## steps to reproduce
Version: v3.5.1
1. Open Opentrons GUI app
2. Check only temperature deck is connected
3. Upload script that load temperature and magnetic deck below:
[md.py](https://drive.google.com/open?id=1O_fi98ybiet7jrMqwQQVBeVqH3tWQWN-)
4. Start script
==> It will end at start immediately.

Note: 
It works fine if script only load temperature deck.
script below:
[md_Laura.py](https://drive.google.com/open?id=1eeLB0GAiLVA0pKaN1NNpQxqthUWnDRLS)

## expected behavior
OT2 app will end at start, but user won’t know what happened.
Please add error message "NOT all hardware modules are connected" at OT app stop to run.

**Comment by mcous** [comment]
Proposed fix: disable the **"Run" button** in the run page with a tooltip that says "Please attach all required modules to your robot before running your protocol"
