### ISSUE TITLE
Robot Singleton Refactor: hardware control should be in its own process

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#2684]
The hardware controller should live in its own process and other parts of the system, such as the protocol API or current HTTP apis, should communicate with it via a local socket using either http or some other rpc process.

This eliminates the problem where, for instance, the update server wants to be able to access hardware to get firmware versions of the smoothie board by doing `import opentrons; opentrons.robot.connect(); opentrons.robot.fw_version` . Right now that would cause a lockfile to be generated, which we don't want.

In addition, if the hardware control is its own server, it can be exposed via the network, which would be useful for test scripts.

This ticket is done when

* There is a separate process containing the hardware controller
* There is a well defined network-exposed API for invoking hardware controller methods
* That API has python bindings that look like method calls so that the update server can use them without being aware of the change
* The rest of the system (the main server that runs the protocol API) uses those bindings to implement hardware access
* This system does not significantly increase latency or decrease the speed of protocol execution
* The entire system, both hardware control and main server, are delivered in a single python wheel for backwards compatibility

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535387405) by [Unito](https://www.unito.io/learn-more)

**Comment by mcous** [comment]
Ticket no longer applicable. New hardware control process work will get new tickets
