### ISSUE TITLE
Robot Singleton Refactor: Make smoothie communication async

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#2686]
## overview
Serial communication used in Opentrons should be asynchronous.

## current behavior
Smoothie communications block until the command is complete, and therefore block everything above them up to and including web requests.

## expected behavior
Smoothie communication at the lowest possible levels should be asynchronous, so that web requests and everything above them is not blocked.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535387441) by [Unito](https://www.unito.io/learn-more)

**Comment by mcous** [comment]
No longer applicable
