### ISSUE TITLE
Can't cancel a protocol when it is simulating

### ISSUE THREAD

**Issue by SimplyAhmazing** [OpenTrons/opentrons#269]
When I press cancel when a protocol run is started and it is at the simulating stage, it does not work.

**Comment by astaff** [comment]
How long does the simulation step take and what's the likelihood of this actually happening?

**Comment by SimplyAhmazing** [comment]
Simulation step takes ~5 sec for dinosaur protocol and varies based on protocol length. I think I maybe thought of a cheap, hacky way to fix it..

**Comment by SimplyAhmazing** [comment]
Removing the run against virtual smoothie makes the "simulation" time take <= 1 sec on dinosaur making it extremely unlikely to run into this error.
