### ISSUE TITLE
OT-2 pg on brand site is broken when not accessing internally

### ISSUE THREAD

**Issue by mmonsees** [Opentrons/opentrons#2693]
There appears to be a bug that is breaking the OT-2 page when accessing from a link outside the site. I found it when testing our LinkedIn ads that were pointing to the page. It looks like the only way you can access this page is by clicking on it from the navigation on our site.

To reproduce, try and access this page (not the shopify page, but www version) in any way other than clicking on an internal link (i.e. a link on our site) e.g. Google 'opentrons ot-2' and click on the organic result (not the ad) and you'll be served "The page you requested could not be found." , or just click [](https://opentrons.com/ot-2)

I reproduced on the most recent versions of chrome, edge and firefox, both on and off wifi.

About 300 people a week land on this page from outside our site, meaning they we are likely serving the broken experience. It is our second most landed on page, even if you exclude paid marketing (which I have now paused or redirected). I would think it also breaks our marketing tracking, though I haven't confirmed this.

**Comment by mcous** [comment]
This was 100% my fault. Today around 4:30 PM I was trying to set my Surge.sh account (where our site is deployed) up on the Opentrons domain, and I ended up running a deploy from my machine. I forgot (somehow...) that deploys are only meant to be run from CI, so it failed to push the necessary html file for pages to work directly. I re-ran the last good CI deploy job and everything is back to normal.

I'm very sorry about this. To make sure it doesn't happen again:

1. This happened (ironically enough) as I was ensuring we have a solid release process in place that tracks changes and _only_ runs from CI. That will be how 100% of deploys are done moving forward
2. We will be moving the site to S3 in the medium future, so we'll never have to use the Surge CLI tool whose instructions tell you to run a full deploy to add users to an account
