### ISSUE TITLE
Add guiding text to place liquid dropdown if user has not created any liquids

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#2696]
As a user I want guidance before I make errors.

![image](https://user-images.githubusercontent.com/35570080/48724618-b9b69400-ebf7-11e8-8532-71d316998ca4.png)

## Acceptance criteria

* [ ] When there is no liquids to choose in the dropdown display a disabled option
* [ ] Disabled text should read "Use the liquids tab to create liquids"

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535387777) by [Unito](https://www.unito.io/learn-more)

**Comment by pantslakz** [comment]
@howisthisnamenottakenyet Let's explore what an empty state for this form looks like. 

To consider:
- Should we display the liquids/volume fields if no liquids exist? 
- Can we link user directly to liquids tab
