### ISSUE TITLE
Step Form: Auto-Select Well in Single-Well Labware

### ISSUE THREAD

**Issue by pantslakz** [Opentrons/opentrons#2708]
When user selects Trash or a lab ware which has only 1 well, disable "wells" selection - as there is only 1 well that can be chosen

## Acceptance Criteria
- [ ] If labware only has one well, auto-select that well in the step form

**Comment by umbhau** [comment]
Blocked by ongoing refactor per @IanLondon

**Comment by IanLondon** [comment]
Closed in favor of #3146
