### ISSUE TITLE
Distribute(...Touch_tip=True) returns bad coordinates on 15/50ml rack and trash container

### ISSUE THREAD

**Issue by Austin-Morrell** [Opentrons/opentrons#2712]
## Overview
It seems running distribute with touch_tip=True creates problems for coordinate targeting 
A similar issue was reported here (https://github.com/Opentrons/opentrons/issues/1742) with troughs 

## Current Behavior: 
Pipette tip aspirates Mastermix from correct location , proceeds to lift up 15ml tube and 15_50 tube-rack and moves rack and tube onto slot divider ridge. Pipette tip then touches the 4 corners of 15ml tube and moves to 96 well plate. Robot proceeds to dispense fluid and touch tip to 96 well plate (as expected). Pipette then moves to trash performs blow out and then collides with trash container moving pipette tip well past boundaries of trash container (I assume to touch_tip the trash container). Pipette then moves to slot 2 (one slot below 5) and attempts to aspirate master-mix from empty slot. User terminates run. 

## Steps to Reproduce
#Load API and Labware
from opentrons import labware, instruments

plate = labware.load('96-flat', '3', share=True)
tuberack15ml = labware.load('tube-rack-15_50ml', '5')
p50rack = labware.load('tiprack-200ul', '9')

Mastermix=tuberack15ml.wells('A1')

P50s = instruments.P50_Single(
    mount="right",
    tip_racks=[p50rack])
#Fix tips not dropping bug hopefully
P50s.plunger_positions['drop_tip'] = -6

P50s.distribute(11, Mastermix, plate.cols('1', to= '9'), new_tip='once', touch_tip=True)

--End Relevant Code Lines--

## Expected Behavior:
 The p50 pipette distributes 11 ul of Mastermix fluid located in 15 ml falcon tube in slot 5 location A1 to columns 1-9 of 96 well plate located in slot 3. After each aspirate or dispense step pipette tip touches 4 points on either 15ml falcon tube or well in 96 well plate. 

## Software: 3.5.1 
Hardware: Opentrons 2 bot with most recent software

**Comment by Laura-Danielle** [comment]
Hi @Austin-Morrell !

Thank you for your ticket submission. Have a quick question for you, are you experiencing this behavior using our modular tuberack?

**Comment by Austin-Morrell** [comment]
I am not using the new black modular tube-rack (we just got these in today) . I am however using the clear acrylic tube rack (from the OT1 robot I think) that was supplied with our labs OT2 robot. Hope that helps.

**Comment by mcous** [comment]
I think there's a high probability this was solved by the labware v2 launch, which includes both:

- Legacy acrylic rack: `opentrons_10_tuberack_falcon_4x50ml_6x15ml_conical_acrylic`
- New, modular rack: `opentrons_10_tuberack_falcon_4x50ml_6x15ml_conical`

We should check that touch-tip is good with those definitions using above repro before closing

**Comment by btmorr** [comment]
Need to double-check if this is resolved in 3.13.0

**Comment by umbhau** [comment]
@ethanfjones, just to confirm -- is the pipette moving to the side of the well while still at the bottom of the tube (i.e., at its aspirate location with the pipette stem still in the tube)?

**Comment by ethanfjones** [comment]
@umbhau yes that is correct. 

![tuberack_touch_tip](https://user-images.githubusercontent.com/39735022/69156970-3e115080-0ab2-11ea-8dfc-daaf7d1af254.gif)

**Comment by ethanfjones** [comment]
@umbhau Yes, that is correct.

![tuberack_touch_tip](https://user-images.githubusercontent.com/39735022/69160059-e75a4580-0ab6-11ea-9f23-3c5e651377c7.gif)

**Comment by ethanfjones** [comment]
@umbhau Yes, that is correct. After the pipette is done aspirating it will move to the side of the well then vertically upward.

**Comment by umbhau** [comment]
Thank you @ethanfjones. @mcous, sounds like this is indeed a bug (I would expect the pipette to move vertically to its touch tip z-height before any horizontal movement).

**Comment by btmorr** [comment]
Going to double-check if this has been fixed in APIv2. @sfoster1 would you mind checking, and also posting a tested workaround for v1?

**Comment by ahiuchingau** [comment]
The following behavior is observed in robot server version **3.15.0:**

In APIv1, the pipette would aspirate/dispense at the bottom of the well, then move to side of the well (at the bottom) before moving to the top to perform touch tip. This causes the conical tube to be dislocated from the tube rack. Pipette would then blow out at the trash (the pipette no longer touches tip at the trash therefore no more collision here), before moving to the source to aspirate again. See video [here](https://drive.google.com/file/d/1hSRdIlICRC9edA2o0Bwjdsvk37xzf33v/view?usp=sharing).

The above is already fixed in APIv2. See video [here](https://drive.google.com/file/d/1lBXjZe48jcD569eG3aFMG-53TnNOw45j/view?usp=sharing).

**Comment by nusrat813** [comment]
Tested on APIV1 and APIV2 (3.15.1) 

Behavior APIV1 touch tip in 15_50 tube rack: 
- Pipette aspirates volume 
- Pipette moves to the right after aspiration is complete
- PIpette moves up in the Z
- Pipette attempts touch tip

No issues with 15-50 tube rack touch tip behavior in APIV2
