### ISSUE TITLE
Step Generation Refactor: migrate aspirateUpdateLiquidState to getNextRobotStateAndWarnings

### ISSUE THREAD

**Issue by b-cooper** [Opentrons/opentrons#2734]
## overview

Currently `aspirateUpdateLiquidState` and `dispenseUpdateLiquidState` take args as a parameter that is a subset of robotState.  We would like to consolidate the logic here and eventually have all calculating of the next robot state (liquid, tips etc.) created from one master function called `getNextRobotState`. 

This ticket should start us down that path of clarification by creating the `getNextRobotStateAndWarnings` function and migrating the current usage of aspirateUpdateLiquidState (1 instance + tests) over to the new function.  The following steps to migration will be tackled in follow-up tickets.

**Comment by IanLondon** [comment]
@b-cooper should be `getNextRobotStateAndWarnings` right? 

The aspirateUpdateLiquidState returns this already: `{liquidState: LiquidState, warnings: Array<CommandCreatorWarning>}`

the dispense version has a TODO to return the same type
