### ISSUE TITLE
Aspirate and Dispense flow rates are not being taken from the JSON file created by protocol designer

### ISSUE THREAD

**Issue by utimcraig** [Opentrons/opentrons#2764]
## overview
This bug is related to this one: https://github.com/Opentrons/opentrons/issues/2763 in that the same protocol is being used on the same system.

## current behavior : 

Currently aspirates and dispenses are done at the default rate even if a different rate is specified using the protocol designer.

The software currently shows Dispensing at speed 1.0, which is neither the default nor the speed I put in.
![image](https://user-images.githubusercontent.com/32027355/49404341-2fa11c00-f71d-11e8-95c4-b17a216df3f8.png)

## expected behavior
The robot should dispense at the speed I entered into the protocol designer and in the JSON file.

**Comment by IanLondon** [comment]
@utimcraig thank you for the bug report! I split this into 2 tickets because there is one bug in the Python API and a separate one in Protocol Designer.
