### ISSUE TITLE
PD ignores flow rate settings

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#2773]
Something broke recently in PD: aspirate/dispense flow rates are not being saved in the subprocedures.

Reported in #2764 (from the latest release I assume?) and still true on `edge` b26abddf6b99082591a596a583827bae41f157d1

Example protocol: [slow-asp-then-slow-disp.json.zip](https://github.com/Opentrons/opentrons/files/2641595/slow-asp-then-slow-disp.json.zip) -- open in PD, re-save, and see that the flow rates aren't being set in the `"procedure"` section

Turns out I never implemented them in `step-generation` in #2123 !

**Comment by utimcraig** [comment]
This is really important for my experiment so please fix this one quickly!

**Comment by ajdittmar** [comment]
I'm having this issue as well.

**Comment by utimcraig** [comment]
Hi @IanLondon how is this doing?  I have an experiment waiting for the feature of having control over aspirate and dispense rates.

**Comment by utimcraig** [comment]
Go Ian go!

**Comment by utimcraig** [comment]
Thanks @IanLondon !  Do you know when this will be released so I can update my opentrons 2.0 ?
