### ISSUE TITLE
Rerunning protocol freezes

### ISSUE THREAD

**Issue by Lucajscarano** [Opentrons/opentrons#279]
After running the protocol, when clicking to rerun the protocol, the app freezes. It will home the robot very slowly then stop. The app says in progress at 0% but nothing is happening. When clicked to cancel job, the bar stays the same (attached is the mentioned bar). While frozen, I am unable to re-upload the protocol and am forced to close out of the window to open a new one. 
![screen shot 2017-08-01 at 10 28 25 am](https://user-images.githubusercontent.com/30629007/28830647-61ef7958-76a5-11e7-8868-fcf4bdd5bb15.png)

**Comment by mcous** [comment]
This has been fixed in `v3`. Will re-open this issue if a backport to `v2` seems likely
