### ISSUE TITLE
Permission Error 

### ISSUE THREAD

**Issue by nusrat813** [Opentrons/opentrons#281]
![capture2](https://user-images.githubusercontent.com/30632549/28941428-01dc5762-7866-11e7-99b0-0db260fe5ff8.PNG)

**Comment by astaff** [comment]
@nusrat813 can you confirm this is still happening for 2.5.2?

**Comment by mcous** [comment]
Closing this issue as it seems like a transient Smoothie board problem and does not appear to be an issue with `v3`
