### ISSUE TITLE
Fallback Pipette Selection to Opposite Mount When Removed  

### ISSUE THREAD

**Issue by b-cooper** [Opentrons/opentrons#2814]
## overview
The bug spotted in #2809 brought up an ideal behavior that this feature should create.

Formerly, if you removed a pipette from a it's mount in PD, a pipette thunk would dispatch a change to all of the forms that had used that pipette such that they would now have no pipette selected in the StepForm.  There was a bug in that functionality that led to some confusion, but was mended in #2813. 

Instead of replacing the references to the nuked pipette with null, forcing the user to manually select the new pipette in every form's dropdown, we would like to have the form update the references to the previous pipette, with reference to the new (or old) pipette on the opposite mount. This relies on the fact that you can't make a protocol that doesn't have at least one pipette mounted. We are also assuming, that as a user, you would never remove a used pipette from a mount, if you didn't intend to have the newly specified pipettes handle the steps that were formerly handled by the nuked pipette.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535389279) by [Unito](https://www.unito.io/learn-more)

**Comment by umbhau** [comment]
@b-cooper moved this to backlog to close out the old sprint. 

discuss in sprint planning?
