### ISSUE TITLE
Safety Features: Automatic Door Safety Stop (API)

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2820]
As a robot user, I would like my robot to stop automatically when the top cover or door is open, so that I don't injure myself.

## Acceptance Criteria
- [ ] New API feature flag to stop robot and prevent resume when door or top enclosure is open
- Note this only applies to protocol run movement (not calibration, etc.)

## Technical details

- Use a gpio watcher task in asyncio
- Enable only during protocol run
- Thread a callback to the session that calls `session.pause()` when the switch gets initially triggered
- Save the switch state to a public session variable
- Add some debouncing

Copy for feature flag: https://app.zeplin.io/project/5aa97729db58a2192f10d0d6/screen/5ea8189233694a2667093575

**Comment by mark-nicholas** [comment]
here is how I enabled the door interlock I hope this helps...

#door interlock
import opentrons, threading
def door_stop():
    opentrons.robot.connect()
    while opentrons.robot.is_connected() is True:
        if robot._driver.read_window_switches() is False:
            opentrons.robot._driver.kill()
            try:
                if robot._driver.read_window_switches() is True:
                    opentrons.robot.connect()
                    opentrons.robot.home()
            except:
                continue

doorstopthread = threading.Thread(target= door_stop, args=())
doorstopthread.daemon = True
doorstopthread.start()

**Comment by chazmanc** [comment]
Here's another solution to this problem... @umbhau 

```
from opentrons import labware, instruments, robot
import time
import threading


def door_stop():
    while robot.is_connected() is True and done is False:
        if robot._driver.read_window_switches() is False:
            robot.pause()
            robot._driver.run_flag.wait()
        else:
            time.sleep(2)


done = False

doorstopthread = threading.Thread(target=door_stop, args=(), daemon=True)
doorstopthread.start()

# Protocol goes below

tips = labware.load('opentrons_96_tiprack_300ul', 2)
in_plate = labware.load('biorad_96_wellplate_200ul_pcr', 5)
out_plate = labware.load('biorad_96_wellplate_200ul_pcr', 6)
pip = instruments.P300_Single(mount='left', tip_racks=[tips])

pip.transfer(50, in_plate.wells(), out_plate.wells())

done = True
```
