### ISSUE TITLE
Cannot run API tests without clearing APP_DATA_DIR

### ISSUE THREAD

**Issue by SimplyAhmazing** [Opentrons/opentrons#284]
Developers can't run API tests without clearing the APP_DATA_DIR where calibration data for the API is found. The `make test` command currently clears the APP_DATA_DIR,

```
test:
	export APP_DATA_DIR="${TMPDIR:=${TMP:-$(CDPATH=/var:/; cd -P tmp)}}" ...
```

But clearing this dir for the entire test suite is suitable for CI and makes the tests not runnable on a per unit basis.

**Comment by astaff** [comment]
@jaredgreene1

**Comment by mcous** [comment]
This is no longer the case on the current base branch
