### ISSUE TITLE
Deck calibration issue: pipets crashing on trash bin

### ISSUE THREAD

**Issue by TSchalck** [Opentrons/opentrons#2859]
I am using the most recently released software and server version (3.6.5), but every time I want to calibrate the deck, the OT-2  robot is not able anymore to connect with the Opentrons software upon restarting. When I am running a protocol, the tip calibration procedure is ok, but when the protocol is executed the pipet is crashing against the waste bin instead of dropping off the pipet tips. Also at other slots on the desk, the pipet is not properly positioned at the intended slot coordinates.

## current behavior

1) Connecting the robot with the app after saving the deck calibration coordinates does not seem to work. ('No robots found' message)
2) Position of the pipet does not correspond with the intended positioned described in the protocol, causing the pipet to crash against objects, such as the waste bin and pipet racks.

Probably, both events are related with each other.

## expected behavior

  1) Connection between robot and OT-2 app should be readily established after restarting upon deck calibration.
 2) Actual pipet position should correspond with the intended pipet position (slot coordinates) from the protocol.

**Comment by mcous** [comment]
Hey @TSchalck, sorry for the delay on this response. The issues you've described are best handled by our support team (<https://support.opentrons.com or via in-app chat) if you haven't reached out to them already. The support team is also generally a much faster channel then GitHub for problems with your robot.

If the support team uncovers any software bugs during troubleshooting, we'll re-open this ticket and/or create new bug tickets as necessary!
