### ISSUE TITLE
PD Bugs: Pre-wet tip behavior doesn't match tooltip

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#2901]
## current behavior

For "Pre-wet tip", the tooltip always says it will aspirate and dispense 2/3 of the pipette's max volume.

However, the implemented behavior is different:
- **Transfer:** uses the given volume of the step, or the volume of the chunk when the given volume gets split into chunks. The unit test matches this behavior.
- **Consolidate:** Uses the given volume. Unit test matches this behavior, but the name of the test is misleading (it references chunking, but consolidate doesn't chunk)
- **Distribute:** Not implemented, test exists but is unfinished & skipped.

## steps to reproduce

Check pre-wet tip

## expected behavior

I think we agreed the 2/3 of pipette-with-tip max capacity is the way to go?

## danger zone

Would cause an implicit change to loaded-&-resaved protocols if we change the behavior :/

**Comment by SyntaxColoring** [comment]
We think this was accidentally removed from the bug backlog. Adding it back in.
