### ISSUE TITLE
Unclear error when JSON protocol uploaded without .json filename extension

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#2905]
## overview
Uploading a JSON file with no `.json` filename extension gives a weird error that makes it look like something broke, and doesn't give the user any clue about what to do.

## current behavior
Without the `.json` extension, the file is run as a Python protocol and gets a weird syntax error wherever the JSON first diverges from Python syntax, probably a `NameError: name 'null' is not defined` somewhere.

## expected behavior
Something like...

* Do not assume a protocol file is Python if it doesn't end in `*.json` - require it to end in `.py`
* If file extension of file is missing, give an easy-to-understand error about adding `.py` or `.json` to the end so that users understand they can fix the problem by renaming the file

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535390825) by [Unito](https://www.unito.io/learn-more)

**Comment by amitlissack** [comment]
@IanLondon I believe this can be resolved.

We try to detect protocol type for a file with no extension. If the first character is `{` we assume JSON. Otherwise we assume Python.

**Comment by amitlissack** [comment]
This has been resolved.
