### ISSUE TITLE
Typos in API docs

### ISSUE THREAD

**Issue by lmtgalhardo** [Opentrons/opentrons#292]
- http://docs.opentrons.com/containers.html 
page says `container.load` several times instead of `containers.load`
- http://docs.opentrons.com/index.html
top of page says 
> to transfer from well 'A1' to well 'B1' that even a computer could understand:

but then says 

> Transfer 100uL from the plate's 'A1' well to it's 'A2' well

**Comment by IanLondon** [comment]
@astaff This was fixed in `app-3-0` branch with #323 , should I make a new PR to `develop` making the same docs updates?

**Comment by astaff** [comment]
Yes, @IanLondon
