### ISSUE TITLE
PD Flexible Steps: Step list item title

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#2925]
As a user I would like to tell my steps (not starting deck state, not final deck state) apart from each other

## Design 
- [ ] All steps get a step number. This step number is _not_ effected by any changes to the step name. 
- [ ] When steps are re-ordered the numbers are updated.
- [ ] Staring deck state and final deck state have no step number
![image](https://user-images.githubusercontent.com/35570080/51273723-6cf2fd80-199b-11e9-8dd6-009140221de8.png)

**Comment by IanLondon** [comment]
closed in #2986
