### ISSUE TITLE
Pipette Config: Update Configs Without Reset

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2937]
As an OT-2 user, I would like to be able to update my robot's pipette's configs without resetting my robot or re-loading my protocol.

## Implementation Notes
Changes to configs on disk reflected on behavior when server is started. Methods that save the config should affect the file on disk. Do not require user to reset the robot when changing these settings. Do not require user to re-upload protocol. Add methods to modify the values in the live object and flush them to disk. (Medium)

**Comment by sfoster1** [comment]
The settings in #2936 should take effect immediately on already-loaded instrument objects in both the old and new API.
