### ISSUE TITLE
Pipette Config: Define Plunger Position Relative to Default

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2938]
As an OT-2 user, I would like to be able to specify custom plunger positions relative to the value from `pipetteModelSpecs.json`, rather than as an absolute position.

For example, in the config `pipetteModelSpecs.json`, plunger positions look like:

```json
"plungerPositions": {
      "top": 19.5,
      "bottom": 0.5,
      "blowOut": -2.5,
      "dropTip": -6
    },
```

In the user-set pipette config settings, we should not allow users to set new absolute positions, but instead store the offset as a relative position (added to the absolute position from `pipetteModelSpecs.json`)

**Comment by umbhau** [comment]
@IanLondon @btmorr 

can we close this ticket?

**Comment by btmorr** [comment]
Taken care of by #2941
