### ISSUE TITLE
Labware calibration: App changes for change in calibration point for troughs

### ISSUE THREAD

**Issue by sanni-t** [Opentrons/opentrons#2948]
## overview

protocol_api2 now uses the well's center point as the calibration point for troughs. Specifically, now pipette's center should align with trough well center.  So we need to update the app's calibration step to show this new calibration point

## current behavior

Currently the calibration point for troughs is a point along the upper edge of the first well of a trough

## expected behavior

The image on labware calibration step should show a point in the center of the first well for calibration. In case of multichannels, the pipette should center over the trough well

## design
to top: https://zpl.io/2GmrRLj
to bottom: https://zpl.io/boxj8GW

**Comment by btmorr** [comment]
cc @pantslakz

**Comment by howisthisnamenottakenyet** [comment]
@btmorr @sanni-t Is this right?

![Trough calibration Copy](https://user-images.githubusercontent.com/35570080/62316795-4cd1ea00-b466-11e9-906a-5bb2e2451ff8.png)

**Comment by btmorr** [comment]
Left graphic looks right. Right graphic is for calibrate-to-bottom. I believe this card is supposed to be for calibrate to top.

**Comment by howisthisnamenottakenyet** [comment]
@btmorr Ok! If you confirm the design in the zeplin link then I'll remove the design tag from the ticket.

**Comment by Kadee80** [comment]
@howisthisnamenottakenyet RE: calibrate to bottom image. We will need that as well since we swap out images/text based on if that advanced setting is turned on

**Comment by howisthisnamenottakenyet** [comment]
updated
