### ISSUE TITLE
Thermocycler: API: Reliable Execution of Long Protocols

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#2959]
As a protocol designer, I would like to be able to reliably run extended protocols without issue, so that I can run long library prep protocols on the thermocyler, and/or handle protocols with long 'storage' temp pauses.

## Acceptance Criteria
- [ ] Robot and App able to run 3+ hour protocols reliably 

## Implementation Notes
- Current problems may have something to do with smoothie timeout

**Comment by Laura-Danielle** [comment]
See Doc [here](https://docs.google.com/document/d/19LFrwrRwzgDVdvLcrL-jSS_6kuIFiz4uHBHoPGFqB_Y/edit) for results from testing.
