### ISSUE TITLE
Thermocycler: Driver: Set temperature & ramp rate

### ISSUE THREAD

**Issue by sanni-t** [Opentrons/opentrons#2979]
## overview
As a robot user, I would like to have a TC driver to be able to communicate the following with the TC via gcodes:
- [ ] set a temperature & hold time
- [ ] set the ramp rate

**Comment by btmorr** [comment]
GCodes for thermocycler: https://docs.google.com/document/d/1pfZpxrgS3ecJ3Wtdm7R4jHNMOnyOxCzrRnPm7S7BEYs/edit?usp=sharing
