### ISSUE TITLE
Thermocycler: Driver: Get status of current step/ cycle

### ISSUE THREAD

**Issue by sanni-t** [Opentrons/opentrons#2980]
## overview

As a robot user, I would like to have the TC driver to be able to receive and parse the status of the current cycle/ step via gcodes

**Comment by btmorr** [comment]
GCodes for thermocycler: https://docs.google.com/document/d/1pfZpxrgS3ecJ3Wtdm7R4jHNMOnyOxCzrRnPm7S7BEYs/edit?usp=sharing
