### ISSUE TITLE
Thermocycler: Driver: Pause/ deactivate module

### ISSUE THREAD

**Issue by sanni-t** [Opentrons/opentrons#2981]
## overview

As a robot user, I would like to have a TC driver to be able to communicate the following with the TC via gcodes:
- [ ] pause the TC
- [ ] deactivate TC

## Open question
What does it mean to pause a thermocycler? Stay on its current step or stop doing anything. How does that differentiate the action from deactivate?

@pantslakz does this pause the countdown, and then remainder of countdown runs after un-pause? Or does the countdown continue but pause would keep it from moving on to the next cycle?

**Comment by btmorr** [comment]
GCodes for thermocycler: https://docs.google.com/document/d/1pfZpxrgS3ecJ3Wtdm7R4jHNMOnyOxCzrRnPm7S7BEYs/edit?usp=sharing
