### ISSUE TITLE
P300 single is currently crashing into trash during tip probe.

### ISSUE THREAD

**Issue by msturlese** [Opentrons/opentrons#3008]
## overview
suddently P300 single v1.3 (right-mounted) is currently crashing into trash during tip probe. Server version 3.6.5

## current behavior
p300  crashing into trash box during tip probe, also after pipette re-install, factory reset.

## steps to reproduce

 any protocol  produce such problem (ie with open Dinasour logo protocol)
## expected behavior
p300 complete tip probe without crashing

**Comment by mcous** [comment]
Thanks for the ticket @msturlese! This sounds like a problem that is best handled by our support team at <https://support.opentrons.com> or via in-app chat.

Off the bat, I recommend that you:

1. Make sure "Your Robot > Advanced Settings > Use Protocol API version 2" is turned *off*
    - (It's an Opentrons internal setting)
2. Check if the robot has trouble going to the correct location for labware
    - If it does, perform a deck calibration

I'm going to close this issue for now. If the support team identifies a software bug during troubleshooting we'll reopen this ticket to track it!
