### ISSUE TITLE
Instrument calibration check mark sometimes does not show up

### ISSUE THREAD

**Issue by SimplyAhmazing** [OpenTrons/opentrons#301]
When you calibrate an instruments positions (top, bottom, blowout, droptip), sometimes the app does not show calibration check mark.

**Comment by Kadee80** [comment]
I remember seeing this from time to time when we check for isCalibrated. If I remember correctly the check happens before state is updated.

**Comment by SimplyAhmazing** [comment]
Huh, @Kadee80 are you saying it's something that's been around before 2.5.0 ?

**Comment by Kadee80** [comment]
I saw it on our dynamic deck map branch. Which was never merged in. I assumed it was because we changed the calibration logic due to the deck.

**Comment by SimplyAhmazing** [comment]
Just cleared out my calibrations data directory, opened app 2.5.2, uploaded a protocol, calibrated all positions, and was able to get the green check mark and run my protocl.

Can't reproduce this issue locally.
