### ISSUE TITLE
Pipette+: Figure out how to make smoothie config details changeable at runtime in smoothie

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#3036]
The upcoming Pipette+ models are different sizes than the current pipette models internally, and therefore have different homing requirements compared to current pipettes. This requires changing details about homing, such as

- Home timeout
- Motion extents
- Backlash value for pipettes

These are currently set in the smoothie config (i.e. [here](https://github.com/Opentrons/SmoothiewareOT/blob/db5e71185d956164d098192b9e92f295efb4af24/src/config.default#L184)) and must be made modifiable at runtime. This may involve adding new gcodes and modifying smoothie, or we may find some way to modify this otherwise. 

This ticket is done when we know how to do the modifications.

**Comment by Laura-Danielle** [comment]
Closed by the following:

**Timouts**
Current behavior
Smoothieboard is sent a command, followed by an `M400` command which blocks any other commands from being sent another command. Timeouts are the following:


Receiving a response from smoothie -> 1 sec
Time to complete a movement -> 30 sec
Time for smoothie to Boot -> 3 sec

**Proposed Behavior**
Make commands non-blocking and poll for updates to behavior. We will keep the timeouts for receiving a response and time to boot for smoothie.

To make commands non-blocking requires some changes to both the firmware as well as the driver. This will be quite similar to work that has been done thus far with the Thermocycler.

**Configs: Motion/Homing**
Current behavior
Configs are specific to the old models

**Proposal**
Add a GCODE to send over correct configs based on attached pipette for L vs R mount. This would allow support for robots that may have an old and new pipette attached.
 
**Config Proposal**
Pipette configs are loaded based on the pipette model number written to it.

If configuration values needed by hardware are not the same as the old pipette models, then we will need to have two separate load functions which correctly formats the load value per pipette type. Also dependent on the config values, we may want to add them as properties of the pipette.

Example of ID written to new pipettes: 1234567890; no model type currently being written to pipette+
