### ISSUE TITLE
Usability: App windows installer should be signed with a CSC

### ISSUE THREAD

**Issue by SimplyAhmazing** [Opentrons/opentrons#304]
## overview

Windows alerts the user if they try to installed "untrusted" applications. At the moment, the Opentrons App is unverified and therefor triggers security warnings.

## acceptance criteria

- [ ] App installer should by signed so as to not trigger security warnings on Windows

## implementation details

We should sign the app with a Code Signing Certificate for Windows: https://www.electron.build/code-signing#windows

**Important Note**: Once we purchase a certificate and start signing the app, security notifications _will not_ go away immediately. The mechanisms by which code signing works on Windows (rather, the code signing which we are able to use) means that trust is built up by the number of users, and at some point we hit critical mass and our app is eventually "trusted"

**Comment by mcous** [comment]
App signing has been turned on in AppVeyor and executables are verified by Microsoft Authenticode:

```
C:\Program Files (x86)\Windows Kits\10\App Certification Kit
λ signtool verify /pa C:\Users\mike\Desktop\Opentrons-v3.2.0-beta.3-win-b5505-edge.exe
File: C:\Users\mike\Desktop\Opentrons-v3.2.0-beta.3-win-b5505-edge.exe
Index  Algorithm  Timestamp
========================================
0      sha1       Authenticode

Successfully verified: C:\Users\mike\Desktop\Opentrons-v3.2.0-beta.3-win-b5505-edge.exe
```

It will take some time (and user installs) for the app to start showing up as trusted, but at this point it's out of our hands, so I'm considering this ticket closed.
