### ISSUE TITLE
PD Fixup Round: i18n across step edit form

### ISSUE THREAD

**Issue by b-cooper** [Opentrons/opentrons#3051]
There are a number of TODO's surrounding using i18n for copy across the step edit form. They can be removed once the copy is put into i18n.

**Comment by IanLondon** [comment]
This ticket should maybe be split up?

**Comment by IanLondon** [comment]
Marked as stale b/c I did some of this in the last PD usability sprint, but not closing this yet b/c it should get a second pass to make sure
