### ISSUE TITLE
PD Open Beta: File Update Alert

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3057]
As a protocol designer beta user attempting to open a 'closed beta' file in the new 'open beta' app, I would like to be informed that my file will be automatically updated, and that the new version will no longer be compatible with the 'closed beta' app version.

## Design
![image](https://user-images.githubusercontent.com/35570080/53364413-bde80100-390c-11e9-8de2-fe3994200c0d.png)

## Copy
"Your protocol will be automatically updated to the latest version. Please note that the updated file will be incompatible with older versions of the Protocol Designer. We recommend saving a separate copy of your current protocol before continuing.

Updating the file may make changes to liquid handling actions. Please review your file in the Protocol Designer as well as with a water run on the robot.

As always, please contact us with any questions or feedback."

**Comment by howisthisnamenottakenyet** [comment]
@umbhau @pantslakz Let me know what you think of the copy above

**Comment by IanLondon** [comment]
@howisthisnamenottakenyet what URL does the "click [here](#)" link go to?

**Comment by howisthisnamenottakenyet** [comment]
@IanLondon It goes out to an intercom article on intercom. URL coming later.
