### ISSUE TITLE
PD Warn user if exporting file without any programmed steps

### ISSUE THREAD

**Issue by pantslakz** [Opentrons/opentrons#3060]
## overview

As a user I want to know if I'm exporting a file without any steps, as the file will give me an error if I try to open it up in OT-2 App.

## current behavior

Users are exporting files and not understanding why they cannot run on robot.

## Acceptance criteria
- [ ] When a user attempts to export a file with no steps they get a dismissible pop up/hint
- [ ] This hint links out to the help center (https://intercom.help/opentrons-protocol-designer/en/collections/1606688-building-a-protocol#steps)

## Design
![image](https://user-images.githubusercontent.com/35570080/53346848-dee92b80-38e5-11e9-97aa-40099444ca99.png)

**Comment by IanLondon** [comment]
@howisthisnamenottakenyet I just noticed this ticket, we were talking about something like this yesterday

We also mentioned maybe something in the Run App too
