### ISSUE TITLE
Thermocycler: Run App: Open and Close Lid

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3062]
PLACEHOLDER; TBD

As a Run App user, I would like to be able to open or close my Thermocycler from the Run App, so that I can control it with or without an active protocol running. 

## Acceptance Criteria
- [ ] User able to open and close thermocycler from Run App in the following scenarios
  - [ ] No protocol currently running
  - [ ] Protocol currently running, but paused
- [ ] Button to open thermocycler is inactive if TC is above 70C
  - [ ] Tooltips informing user why button is inactive 

## Design
- TBD @pantslakz 
- Note max safe temp for opening lid per UL compliance is 70C. Max recommended temp per our internal judgment is 30C. Let's pick one temp for now (vs using both thresholds with different treatments), but open to discussion as to what the single cutoff should be.

**Comment by pantslakz** [comment]
IMO this feature is not necessary as user can rely on physical button on module.

But if need be: https://zpl.io/boLe8WG

**Comment by umbhau** [comment]
Closing; will not add a software button to open/close lid for now (except as part of specific user flows)
