### ISSUE TITLE
Thermocycler: Run App: Open Lid Before Calibration

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3066]
As a Thermocycler user, I would like to be prompted to open my TC's lid before calibration, so that my pipettes can access the labware.

## Acceptance Criteria
- [ ] Display a modal informing user that they need to open the lid before calibration
  -  Modal is displayed after connect modules modal and deck setup modal, but before tip pickup

- [ ] If lid is closed
  - inform user that they need to open the lid for calibration
  - user can click a button to open the lid

## Implementation Notes
- Includes polling to get current temp

## Design
- https://zpl.io/boMJjyW

**Comment by pantslakz** [comment]
Should we allow user to cancel out of this for MVP?

**Comment by btmorr** [comment]
70 degree warning will be handled with HW / physical warning stickers, rather than software checks
