### ISSUE TITLE
Thermocycler: Run App: Hold Temp During Pause

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3069]
As a Run App user, I would like to be able to program my protocol to pause until told to resume, so that I can store my samples indefinitely at a set temp.

Note this basic pause functionality already exists. When combined with a 'set_temp' command and improved user communication, it allows users to hold their samples at a set temperature indefinitely.

## Acceptance Criteria
- [ ] Thermocycler should hold current temperature during an indefinite pause step
- [ ] User should be informed if the thermocycler is holding a temp during an indefinite pause (e.g. update pause dialogue box to say 'Thermocycler is holding temperature at X'
- [ ] Pause should stop protocol run clock (existing behavior)
- [ ] Pause dialogue box should display elapsed pause time
- [ ] User has option to 'Resume' protocol

## Design
- TBD @pantslakz

**Comment by b-cooper** [comment]
Closed in favor of differential external to protocol TC control
