### ISSUE TITLE
Not aspirating/dispensing after a move_to() command using direct strategy

### ISSUE THREAD

**Issue by liulisa** [Opentrons/opentrons#307]
We tried to modify the [precision pipetting](http://docs.opentrons.com/examples.html#precision-pipetting) example to aspirate instead of dispense. However, it will move as needed, but it won't actually aspirate anything if we use the 'direct' strategy. However, if we let it move using the default ('arc') strategy, it doesn aspirate.

**Comment by theosanderson** [comment]
I also have this problem. Adding a delay did not help - any solutions, even hacky would be appreciated.

**Comment by mcous** [comment]
Categorizing as a bug out of an overabundance of caution. I have no idea if this is still an issue or not; we should test it out

**Comment by SyntaxColoring** [comment]
I assume the aforementioned "precision pipetting" example is [this one](https://docs.opentrons.com/v1/examples.html?highlight=precision#precision-pipetting).

**Comment by theosanderson** [comment]
> I assume the aforementioned "precision pipetting" example is [this one](https://docs.opentrons.com/v1/examples.html?highlight=precision#precision-pipetting).

Yes that didn't work (haven't tried to replicate on OT2)

**Comment by asogluizzo** [comment]
Close after 4.0.0 release
