### ISSUE TITLE
Labware Library: Labware Cards

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3075]
As a labware library user, I would like to be able to view details of available labware on the Opentrons labware library

## Acceptance Criteria
- [x] New cards displaying high-level labware details
    - Well/tube/tip count
    - Not including well high-level details (see #3245)
- [x] Labware gallery
    - Not including #3269 
- [x] Tags
    - Not including #3444 
- [x] Display name
- [x] Manufacturer
    - Not including tube manufacturer #3447 
- [x] Load name copy button

**Comment by mcous** [comment]
Reopening because designs were revised
