### ISSUE TITLE
Labware Library: Labware Detail Page

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3077]
As a labware library user, I would like a detail page for each labware, so that I can share a link to a specific labware with other users.

## Acceptance Criteria

- [ ] New page displaying details on an individual labware
- [x] New page has nav to return to main labware page
- [x] New page should have a URL unique to the displayed labware
- Note labware details should be identical to those on labware cards on main labware page

## Design

See Zeplin

**Comment by mcous** [comment]
Re-opening issues after designs were re-done
