### ISSUE TITLE
PD Open Beta: Signup Magic Link

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3086]
As an Opentrons user, I would like to be able to access the Protocol Designer with a unique link that identifies me to the app, so that I only have to identify myself once.

Note user identification (1) helps us provide personalized support to users and (2) helps us understand how individual customers are using the platform.

## Acceptance Criteria
- [ ] Expose a web service that: 
  - [ ] Accepts user's email address (note: submitted via TypeForm survey embedded on website; sent to url/web service as TypeForm redirect or via Zapier)
  - [ ] Generates magic link
  - [ ] Send an HTML email to the user 

## Implementation Notes
We have a few alternative options
1) Service can use a transactional email service for email template and/or email delivery
2) Service can call a Zapier URL, and Zapier can handle email send (via another third party service)

## Design / Content
- TBD HTML email

**Comment by btmorr** [comment]
Closing, overlaps with other tickets in this milestone. @umbhau to handle the Typeform/Zapier integration
