### ISSUE TITLE
Labware Library: Images

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3088]
As a labware library user, I would like to be able to see images of labware so that I can quickly and accurately identify them.

## Acceptance Criteria
- [ ] Display one main image per labware
- [ ] Allow user to select and view up to 3 different images from a thumbnail library (thumbnail library is static)
- [ ] One image should be an auto-generated top-down render
- [ ] Gracefully handle more than three images (display 3, don't break)
- [ ] Selected thumbnail should be highlighted 
- [ ] Image cropping should be handled in a sane manner (should be able to handle different aspect ratios without breaking)

## Implementation Notes
- Ticket does not include adding actual images other than top-down render

## Design
@umbhau I propose that there is no highlight on the selected image. Check out how our carousel works in our shop. I think that's fine.

![image](https://user-images.githubusercontent.com/35570080/53107690-93103e00-3503-11e9-9be4-c674152ade4f.png)

**Comment by mcous** [comment]
Removed requirement for actual images from the ticket and re-sized to medium accordingly
