### ISSUE TITLE
Thermocycler: Implement Spanning

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/opentrons#3107]
## overview

Related to issue #2962 . The Thermocycler is our first module to span multiple slots in a robot. We need to have an elegant way to handle this concept. Once this is implemented, it should be able to be applied to any labware that may span multiple slots.

In addition to the extra x,y restritctions of the TC on the deck, it's zDimension is also quite large, which only really becomes relevant with longer gen2 pipettes.  For ensuring safe movement with a TC and gen2 pipettes, we should rethink lw z safety margin and perhaps retract to max_z.  If Max z is somehow still above the max, we should warn/throw during simulation.
  
## current behavior

- Currently there is no way for the robot to account for spanning. It simply relies upon the user to choose the correct slot placement.

## expected behavior

- Robot should remove any slots that would be covered by spanning based on labware dimensions and the input slot

**Comment by IanLondon** [comment]
@Laura-Danielle Please keep me & Brian in the loop so we don't make a roadblock for how PD handles slots!

**Comment by btmorr** [comment]
@umbhau please move to post-MVP milestone

**Comment by kinnari-opentrons** [comment]
Attaching this protocol for reference. The p20 pipette has to clear screw cap tubes in the 2ml aluminum block on the the temperature module and the concern about clearance was raised. @TaylorGoodman

**Comment by kinnari-opentrons** [comment]
[Swift_2S_Turbo_V2_TC_test.txt](https://github.com/Opentrons/opentrons/files/3570544/Swift_2S_Turbo_V2_TC_test.txt)
