### ISSUE TITLE
Thermocycler: Pause and Inform User if TC Lid Opened

### ISSUE THREAD

**Issue by btmorr** [Opentrons/opentrons#3134]
As a Run App user, I would like to be notified if my Thermocycler's lid is opened unexpectedly during run.

## Acceptance Criteria
- [ ] If TC lid is opened unexpectedly, pause protocol, notify user that TC lid is open, and inform them that they need to close the lid before continuing.
- [ ] User should have option to close lid from Run App (e.g. button in notification dialogue box)
- [ ] User should have option to resume protocol if lid is closed

## Implementation Notes
There is already (as of PR #3118 ) an interrupt callback to pause the robot with a message. Need to make sure this gets hooked all the way up into RPC so it gets displayed in the run screen

**Comment by btmorr** [comment]
Consider breaking down into BE & FE tasks

**Comment by b-cooper** [comment]
Closed in favor of designed extra-protocol TC control in addition to physical safety affordances.
