### ISSUE TITLE
[edge] Issue swapping from single to 8-channel pipette

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#3136]
Select 3 wells in a column for single pipette step. Switch to multi channel. Now "3" is in the columns field but when you click and see labware the whole column has been selected. This should have reset well selection.

**Comment by IanLondon** [comment]
@howisthisnamenottakenyet I'm having trouble replicating this - for me the well selection clears out when I go single -> multi. Could this be from a specific labware, or when the form is in a certain state? Definitely important to not allow this to happen!

**Comment by IanLondon** [comment]
I can't replicate in moveLiquids (Transfer) form, but confimed this is an issue with the Mix form. Should be fixed in #3157
