### ISSUE TITLE
Documentation: Labware

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#316]
- [ ] Documentation on json container files (how to write a container). Illustrate what x and y axes are, how offset works.
- [ ] `container.create` - illustrate what the arguments mean

- [ ] Do not set container `label`, unless it's really a different container and needs to be calibrated again
- [x] `trash-box` as canonical trash container instead of `point`

**Comment by IanLondon** [comment]
We should document as we build it :)

**Comment by IanLondon** [comment]
Still need to do

**Comment by mcous** [comment]
Closing in favor of the the Labware v2 and Labware Creator milestones
