### ISSUE TITLE
Modules: Error During Long Run

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3160]
## Expected Behavior
Expected to be able to upload the entire protocol (about 3 hours with pauses) and have the module (tempdeck) respond according to the programmed 

## Observed Behavior
The App will not respond about 1 hour into the protocol. The protocol cannot be resumed after programmed robot.pause in the protocol. Intermittently, this bug will prevent the user from proceeding to calibration in the App. The error messages observed are attached.
[tempdeck_error.txt](https://github.com/Opentrons/opentrons/files/2931510/tempdeck_error.txt)

## Steps to Reproduce
Below is the script that was used when this bug was observed is attached.
[Swift_2S_Turbo_script.txt](https://github.com/Opentrons/opentrons/files/2931549/Swift_2S_Turbo_script.txt)

**Comment by kinnari-opentrons** [comment]
This was all done on robot and software version 3.6.5

**Comment by mcous** [comment]
@sfoster1 do we think this is at all related to #2822?

**Comment by b-cooper** [comment]
Closed by #3219
