### ISSUE TITLE
PD Cleanup: Rearrange FormData object + use HydratedFormData

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#3161]
There should be a single source of truth for fields and types in the form objects.

Write non-hydrated and hydrated form types for mix+pause+moveLiquid and use them instead of the generic placeholder types. 

Several TODO comments about this.

Also, most of the time the forms are not well-defined in Flow. This makes it easy to make mistakes, even when we TDD the form fields are easy to give incorrect field names to. There is no type def to serve as a source of truth for what fields each form is supposed to have and what type they are (usually string but easy to mistakenly think it would be number, often optional values but not always, etc)

# Acceptance Criteria
- [ ] Remove `StepFieldName` type.
- [ ] Nest all form fields under `fields` key, instead of living on the same level as `id`
- [ ] Properly type `FormData`, it is currently mostly `any` typed
- [ ] Wherever the form is "hydrated" aka denormalized, use `HydratedFormData` type
- [ ] Instead of changing eg `pipette` field from string ID PipetteEntity, nest inside the `meta` field (follow example with `moduleId -> meta.module`
- [ ] Get rid of `hydrateField` and `hydrate` key in `fieldLevel/index.js`, this should act on the `hydrated` field instead of rewriting fields
- [ ] Some comments in PD mention this issue, search PD for the text "#3161" and make sure those comments are addressed
- [ ] When generating field-level errors, we iterate thru all keys (eg `id` and `stepType`) and call `getFieldErrors` on them which is super weird

**Comment by mcous** [comment]
Still important, but pretty gnarly 🏄‍♀ . Probably better to tackle after modules in PD. Wait until PD can drop support for saving JSON protocols schema v3
