### ISSUE TITLE
PD: Optimize and split production bundle

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#3170]
Review file sizes of assets, sanity check those files

We currently output 1 "large (~450K) bundle. We should replace and dynamically import dependencies (dynamic import === bundle split) until we have no more "large" bundles.

We should use webpack's [definition of "large](https://webpack.js.org/configuration/performance/#performancehints) - which is 250KB - as our acceptance criteria. Note that sourceMaps do not count in this calculation, because they are only loaded if devtools are open.

**Comment by IanLondon** [comment]
More suggestions for asset cleanup in #3183 comments

**Comment by IanLondon** [comment]
Also addressed in #3196

**Comment by IanLondon** [comment]
@mcous is this closed now or is there anything else left to do?

**Comment by mcous** [comment]
As discussed in RL, updated title and description with acceptance criteria
