### ISSUE TITLE
Robot should not use random MAC  addresses

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#3175]
As a user who needs to enter the MAC address of my robot into my institution's MAC whitelist to connect to the internet, I need that address to not randomly change.

Success criteria:
- The MAC address presented to the app and to the base station is the hardware address of the interface
- The MAC address presented to the app and to the base station does not change with time or with robot reboots

**Comment by kentcr** [comment]
I was told by support that this issue "should be fixed soon I believe." I can't tell if that means someone is already working on it. Is someone? If not, I might have time to look into it.

**Comment by kentcr** [comment]
Adding this to the NetworkManager config fixes it:
```
[device]
wifi.scan-rand-mac-address=no
```
e.g. /etc/NetworkManager/conf.d/00-fixmac.conf

**Comment by mcous** [comment]
Fixed by the buildroot switch in 3.11.x

@kentcr the latest version of the software should resolve this issue
