### ISSUE TITLE
API server fails to boot if a home-lock error is raised during boot

### ISSUE THREAD

**Issue by btmorr** [Opentrons/opentrons#3182]
## overview
While the API server is booting, it attempts to home the robot (if the feature flag related to home-on-boot is unset, which is the default). If a home-lock error is raised during this call, the API server will fail to boot.

## steps to reproduce
Easiest way to reproduce this is to hold down a home switch while the robot is powering up.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535397654) by [Unito](https://www.unito.io/learn-more)

**Comment by asogluizzo** [comment]
Fixed
