### ISSUE TITLE
PD labware diagrams are cropped wrong and mis-aligned

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#3185]
## overview

PD labware diagrams that appear from mousing over items in labware selection modal

## current behavior

![image](https://user-images.githubusercontent.com/11590381/53970950-d5bc4380-40c9-11e9-8f65-f422f29f414c.png)

## expected behavior

I'm not sure when this broke, it was never perfect but it wasn't this mis-aligned.

Instead of fixing it to its former ugly-but-not-this-ugly state, we might want a new design for the labware selection modal?

**Comment by mcous** [comment]
This was fixed by the new labware selection #3439
