### ISSUE TITLE
PAPI2: Have transfer functions accept `Location`  as source and destination

### ISSUE THREAD

**Issue by sanni-t** [Opentrons/opentrons#3198]
## overview

The complex liquid handling functions: `transfer`, `distribute` and `consolidate` should be able to accept a `Location` type for their sources and destinations in addition to `Well` or `List[Well]`

## current behavior

Only a `Well` or a `List[Well]` is acceptable

## steps to reproduce
```
 pipette10.transfer(
        1,
        reagents.wells('B2'),
        plate.wells_by_index()[well_name].bottom())
```
results in error since `.bottom()` returns a `Location` type

**Comment by mcous** [comment]
Fixed by #4276
