### ISSUE TITLE
PD Steps Form Update: Spacing

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#3199]
As a user I'd like the PD Steps form to not be confusing at different screen sizes

## Acceptance Criteria
- [ ] Build the updates to the PD Steps Form to be responsive

## Design
1024: https://zpl.io/2v79kg5
1280: https://zpl.io/beDEp1m
1280+: https://zpl.io/boDQekZ

**Comment by IanLondon** [comment]
@howisthisnamenottakenyet is this a duplicate of #3140 or is something different?

**Comment by umbhau** [comment]
Closed as part of #3140
