### ISSUE TITLE
`Placeable.from_center`, `Placeable.bottom()` working for multiple wells. (+Documentation for these methods)

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#320]
- [ ] `Placeable.from_center` and `Placeable.bottom()` do not work on multiple wells at once, which make them much harder to use. As an OT Protocol Writer, when you need to offset all the wells in a container for a user's customer protocol, you have to iterate through every well in a container and make your own handmade way of accessing those wells (eg in a list of lists). It would be useful to be able to offset a whole container or set of wells in an existing container instance.

This also makes doing this for multichannel significantly harder:
> you can't use the .bottom() or from_center() or .top() functions with rows (which are wellseries), you can only apply those to well objects. So when youre offsetting for a multichannel pipettes, you have to find workarounds and it's really inconvenient

- [ ] Documentation: `Placeable.from_center` is difficult to visualize, would benefit from illustrations.
- [ ] Documentation: `Placeable.bottom`

**Comment by sfoster1** [comment]
We did document them, but we're not going to make them work on multiple wells - the time for that kind of significant feature work on v1 has passed.
