### ISSUE TITLE
Warn when single-channel pipette attempts to reach a container it can't reach across the deck

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#322]
A multi-channel pipette can reach all the containers on the deck.

But a single-channel pipette on Axis A cannot reliably reach slot column A, and a single-channel pipette on Axis B cannot reliably reach slot column E. (It might be able to reach about 1/2 of the plate).

It's not intuitive, and it's very easy to write protocols that can be simulated with no errors or warnings and ship them,

This problem is compounded with parametric protocols with dynamic pipettes, where it's time-consuming and error-prone to test all the parameters and manually cross-check the deck map with the pipette axes.

Since the pipette might actually reach some wells, this should not be a RuntimeError, but just a warning.

## This is an OT-1 issue only. OT-2 pipettes can reach all wells! :tada:

**Comment by theosanderson** [comment]
More generally - it should be great if it were possible to set limits beyond which the bot will not attempt to move?
