### ISSUE TITLE
Labware Library: labware defs in shared-data should only use mm and ul

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#3240]
## overview

In `shared-data/definitions2`, all functional (e.g. not metadata) length and value parameters should use a common volume and length unit. For our purposes, `µl` and `mm` make the most sense.

With the storage of any number that represents a real-world quantity with units, a consistent data model is super important to avoid weird bugs down the road (think datetimes, temperatures, etc.). To avoid positioning and liquid tracking bugs later, we need to make sure distances and volumes in our labware definitions are consistent now.

## current behavior

- ✅ All labware defs appear to use `mm` for distance
- ❌ Some labware use `µl`, some use `ml`, some use `l`
    - `shared-data/definitions2/opentrons_6x15_ml_4x50_ml_tuberack.json`
        - Has `totalLiquidVolume` specified as `15` and `50` depending on the well
    - `shared-data/definitions2/biorad_96_wellplate_pcr_200_ul.json`
        - Has `totalLiquidVolume` specified as `200` depending on the well

There are also two metadata fields that tie into this:

- `metadata.displayVolumeUnits`
- `metadata.displayDistanceUnits`

Right now, they are _not_ metadata because they are required to understand what distance and volume data means. They also wrap up some i18n concerns into the metadata field; `L` is common for liter in N. America and Australia, while `l` is common in Europe (says [Wikipedia](https://en.wikipedia.org/wiki/Litre#Symbol)).

Because of that, I think we should consider removing these fields, and codify a set of display rules in our UIs instead (e.g. above 500 µL, switch to mL; above 500 mL, switch to L; use `l` or `L` depending on locale). Alternatively, we could switch them to a factor (e.g. 1 for µL, 1000 for mL, 1000000 for L)? Open to suggestions

**Comment by Laura-Danielle** [comment]
Spoke F2F with Mike regarding this issue.

Will move forward with changing the total liquid volume to be represented _only_ in `uL`. DisplayVolumeUnits will remain as units and use the convention `uL`, `mL` and so forth.
