### ISSUE TITLE
APIv2 move_to arc can collide with labware

### ISSUE THREAD

**Issue by btmorr** [Opentrons/opentrons#3252]
## overview

In an APIv2 protocol, if you are transferring between two short labware that have a tall labware in-between, it is possible for the arc strategy to fail to raise above the tall middle labware.

## current behavior

This protocol will cause a collision:

```
def run(ctx):
  tr = ctx.load_labware('topentrons_96_tiprack_300_ul', '10')
  plate1 = ctx.load_labware('biorad_96_wellplate_pcr_200_ul', '1')
  tubes = ctx.load_labware('opentrons_6x15_ml_4x50_ml_tuberack', '2')
  plate3 = ctx.load_labware('biorad_96_wellplate_pcr_200_ul', '3')

  pipette = ctx.load_instrument('p300_single', 'right', tip_racks=[tr])

  pipette.transfer(100, tubes.wells()[0], plate1.wells()[0])
  pipette.transfer(50, plate1.wells()[0], plate3.wells()[0])
```

## expected behavior

Compare with the arc strategy in APIv1: https://github.com/Opentrons/opentrons/blob/edge/api/src/opentrons/legacy_api/robot/robot.py#L613

**Comment by sfoster1** [comment]
This was actually fixed by #3242 , the logic is the same as the robot now
