### ISSUE TITLE
Protocol Designer: tutorial modal vertically aligned too low

### ISSUE THREAD

**Issue by b-cooper** [Opentrons/opentrons#3299]
## overview

The modal is appearing too low and requiring scrolling.

<img width="613" alt="Screen Shot 2019-04-03 at 2 39 20 PM" src="https://user-images.githubusercontent.com/4731953/55504171-4483b280-561e-11e9-8ac7-e228038487a8.png">

## steps to reproduce

- make sure your dismissed hints are restored in the settings tab
- add a step before adding liquids

## expected behavior

There is plenty of space for this modal on most screen sizes, it should be vertically centered in the view port.

**Comment by bndo** [comment]
No longer an issue on 800x600, 1366x768, 1920x1080 or 1440x900
