### ISSUE TITLE
Standardize Nav between PD and Run App

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#3305]
As a user I would like when things that do the same thing between PD and Run app look the same. 

## Acceptance Criteria
- [ ] Update Tabs-style nav to have a disabled tab state (lower opacity for font and icon. I believe we do this for our disabled form fields but I don't know what the opacity % is. )
- [ ] Update Tabs-style nav to take the alert bubble
- [ ] Change Run app nav to the Tabs-style nav

## Design
@pantslakz Alert bubble and disabled state were the two things I noticed Run App has styling for that PD's nav doesn't

**Comment by mcous** [comment]
Closing this one as stale and superceded by new work in planning now. Also, I sneakily switched the app's nav over to PD tabs in #6051, so I think the spirit of this ticket when it was written has been satisfied 😄
