### ISSUE TITLE
Allow stateless use of Air Gap; implement in JSON Protocol v3 executor

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#3311]
## overview
The air gap method `pipette.air_gap(volume, height)` does not allow stateless use. The height is "The number of millimiters to move above the current Well to air-gap aspirate".

The params to air gap are different than the rest of the commands that interact with wells, instead of volume+well+offsetMmFromBottom, it would be volume+height where height is distance from **top** of the last well.

If we don't allow `air_gap` to take an arg overriding the `height` with a Location:

* Unlike other JSON commands, air gap would have an implicit "last used Well" stateful property
* If you want to control where the air gap happens, you need to interact a separate command
* This would be the only command referencing the top of a well, all others use bottom

# Acceptance Criteria
* Allow `air_gap` in APIv2 to take an optional `Location` arg (mutually exclusive w/ `height`)
* Implement the `airGap` command in the APIv2's JSON protocol v3 executor

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535402607) by [Unito](https://www.unito.io/learn-more)

**Comment by mcous** [comment]
Air gap removed in favor of vanilla aspirate in JSON Schema v6
