### ISSUE TITLE
V2 Labware: Add new V2 labware defs for all PD Labware

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3330]
As a PD user, I would like to have access to my current PD labware in V2 labware, so that I can continue to use my protocols without interruption.

## Acceptance Criteria
Add following labware to definitions 2
 - [x] "tiprack-200ul"
 - [x] "opentrons-aluminum-block-PCR-strips-200ul"
 - [x] "tube-rack-.75ml"
 - [x] "tube-rack-2ml"
 - [x] "tube-rack-15_50ml"
 - [x] "96-deep-well"
 - [x] "96-PCR-tall"
 - [ ] "PCR-strip-tall"

**Comment by IanLondon** [comment]
NOTE: PD protocols using `PCR-strip-tall` will be migrated to use `opentrons_96_aluminum_tuberack_200_ul` instead
