### ISSUE TITLE
V2 Labware: Reconcile Directory Structure

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3331]
As an Opentrons developer, I would like consistent naming and location for the labware/deck/pipette schemas, of all different versions

Copied from @b-cooper's comments in #3454 --

- '/labware' shared-data pertaining to the labware data model
    - './schemas/' // all labware schemas, named by version
    - './flowTypes/*.js' // all flow types related to labware
    - './fixtures' // all labware tests fixtures (nested by labware schema version)
        - './1/*'
        - './2/*'
     - '/definitions' // (nested by labware schema version)
        - './1/*'
        - './2/*'
- '/protocol' shared-data pertaining to the json protocol data model
    - './schemas/' // all protocol schemas, named by version
    - './flowTypes/*.js' // all flow types related to protocols
    - './fixtures' // all protocol tests fixtures (nested by schema version)
        - './1/*'
        - './2/*'
        - './3/*'
- '/deck' shared-data pertaining to the deck data model
    - './schemas' // all deck schemas, named by version
    - './flowTypes/*.js' // all flow types related to decks
    - './fixtures' // all deck tests fixtures (nested by schema version)
        - './1/*'
     - './definitions' // all deck defintions (nested by schema version)
        - './1/*'
- './module' // shared-data pertaining to the module data model
    - './schemas' // all module schemas, named by version
    - './flowTypes/*.js' // all flow types related to modules
    - './fixtures' // all module tests fixtures (nested by schema version)
        - './1/*'
     - './definitions' // all module definitions [previously called specs] (nested by schema version)
        - './1/*'
- './pipette' // shared-data pertaining to the pipette data model
    - './flowTypes/*.js' // all flow types related to pipettes
    - './schemas'
        - './name/' // all pipette name schemas, named by version
        - './model/' // all pipette model schemas, named by version
    - './fixtures' // all module tests fixtures (nested by schema version)
        - './name/' // all pipette name fixtures, named by version
            - './1/*'
        - './model/' // all pipette model fixtures, named by version
            - './1/*'
    - './definitions'
        - './name/' // all pipette name definitions, named by version
            - './1/*'
        - './model/' // all pipette model definitions, named by version
            - './1/*'

**Comment by IanLondon** [comment]
Bumping to a large because the logistics of getting PRs through to create, swap, and delete folders will take some time
