### ISSUE TITLE
V2 Labware: New Labware Dimensions Keys

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3332]
As an Opentrons user/coder, I would like to be able to easily reason about which labware dimension corresponds to which axis in the robot coordinate system.

## Acceptance Criteria
- [ ] change 'Length' to 'xDimension'
- [ ] change 'Width' to 'yDimension'
- [ ] change 'Height' to 'zDimension'

**Comment by IanLondon** [comment]
CLosed by #3410
