### ISSUE TITLE
API2: Tipracks that are added to pipette and not explicitly used aren't reflected in app

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#3364]
If you have a protocol that only uses tip racks implicitly, for instance

```
def run(context):
    tip_rack_10ul = context.load_labware_by_name('opentrons_96_tiprack_10_uL', '2')
    reagents = context.load_labware_by_name('opentrons_24_tuberack_1.5_mL_eppendorf', '3')
    plate = context.load_labware_by_name('opentrons_96_aluminum_biorad_wellplate_200_uL', '4')
    pipette10 = context.load_instrument('p10_single', 'left',
        tip_racks=[tip_rack_10ul])

    pipette10.pick_up_tip()
    pipette10.mix(10, 10, reagents.wells('A1')[0])
    pipette10.transfer(
        4.5,
        reagents.wells('A1'),
        reagents.wells('A2'),
        new_tip='never')
```

then the tip rack does not appear in the runapp as a piece of labware and cannot be calibrated. If you add a `pick_up_tip` that explicitly references the labware, such as `pipette10.pick_up_tip(tip_rack_10ul.wells()[0])`, then the runapp picks it up.

The API needs to properly report tipracks that are only used as implicit pick-up-tip (or drop-tip or return-tip) targets.

**Comment by mcous** [comment]
Related to #234
