### ISSUE TITLE
Robot.connect error(), list index out of range

### ISSUE THREAD

**Issue by ffffffrank** [Opentrons/opentrons#3384]
I'm trying to control robot via Paramiko ssh in python on the local computer, I ran:

import paramiko
 ssh_client =paramiko.SSHClient() ssh_client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh_client.connect(hostname=’hostname’,username=’username', password=’mypassword’)
stdin,stdout,stderr=ssh_client.exec_command('python3 /data/test.py')

The test.py I'm running over ssh is the following:

#!/usr/local/bin/python
from opentrons import robot, labware, instruments
if robot.is_connected()==False:
    robot.connect()
robot.reset()
p200rack = labware.load('tiprack-200ul', '10')
waterplate = labware.load('12-well-plate', '5')
blankplate = labware.load('12-well-plate', '6')
p300 = instruments.P300_Single(mount="left",tip_racks=[p200rack])
p300.pick_up_tip(p200rack.wells('A1'))
p300.aspirate(50, waterplate.wells('A1'))
p300.dispense(50, blankplate.wells('A1'))
p300.blow_out(blankplate.wells('A1'))
p300.touch_tip(blankplate.wells('A1'))
p300.drop_tip()
robot.home()

the stdout.readlines() shows the following and robot pipet refused to move.
warning: /mnt/usbdrive/config/deckCalibration.json not found, loading defaults
warning: /mnt/usbdrive/config/robotsettings not found, loading defaults.

The error massage:
['Traceback (most recent call last):\n',
 '  File "/data/test.py", line 4, in <module>\n',
 '    robot.connect()\n',
 '  File "/usr/local/lib/python3.6/site-packages/opentrons/robot/robot.py", line 395, in connect\n',
 '    self._driver.connect(port=port)\n',
 '  File "/usr/local/lib/python3.6/site-packages/opentrons/drivers/smoothie_drivers/driver_3_0.py", line 432, in connect\n',
 '    self._connect_to_port(port)\n',
 '  File "/usr/local/lib/python3.6/site-packages/opentrons/drivers/smoothie_drivers/driver_3_0.py", line 452, in _connect_to_port\n',
 '    baudrate=self._config.serial_speed\n',
 '  File "/usr/local/lib/python3.6/site-packages/opentrons/drivers/serial_communication.py", line 116, in connect\n',
 '    port = get_ports_by_name(device_name=device_name)[0]\n',
 'IndexError: list index out of range\n']

However, if I logged on the robot via ssh in command line, and ran the same command and the robot moves perfectly:

I tested the Paramiko using other python scripts, like "print (hello)", the stdout_readlines returns the results, which means the python script did execute properly.

**Comment by sfoster1** [comment]
@ffffffrank Our software relies on a number of environment variables that are only loaded when you start a login shell on the robot. Try changing the argument to `ssh_client.exec_command` to be `'bash -lc "python3 /data/test.py"'`

**Comment by ffffffrank** [comment]
> @ffffffrank Our software relies on a number of environment variables that are only loaded when you start a login shell on the robot. Try changing the argument to `ssh_client.exec_command` to be `'bash -lc "python3 /data/test.py"'`

OMG, that works perfectly! Thank you very much!
