### ISSUE TITLE
API Tests: Use v2 labware fixtures not v2 labware defs

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#3409]
Python API unit tests often use defs directly from `shared-data/definitions2/` eg `usa_scientific_12_trough_22_ml`. If we remove, rename, or modify a def, those unit tests will fail.

Instead, Python API should use fixtures so that tests aren't tightly coupled to any real labware defs. There are some fixtures in `shared-data/fixtures` (probably should be renamed `labwareFixtures2` or something now that I think about it).

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535403809) by [Unito](https://www.unito.io/learn-more)

**Comment by mcous** [comment]
Closing as stale. If you encounter one of these tests (if any still exist), please swap out the labware def with a fixture
