### ISSUE TITLE
PD Bug: Inner Mix asp & disp tip position should be consistent 

### ISSUE THREAD

**Issue by b-cooper** [Opentrons/opentrons#3414]
## overview

@opatel0 reported this bug and associated protocol in the internal PD slack channel on May 3rd 2019. 

In a given transfer step, the aspirate and dispense offsets from bottom are being used respectively in inner mixes in both source and destination.  In the case where you're moving from a tube rack (~80mm tip position) to a well place (~0.5mm tip position), the mix in destination becomes totally useless as it is aspirating the air 79.5mm above the well of the destination plate.    

## expected behavior

The dispense tip position should be used for aspirate and dispense in a given "mix in destination", and conversely the aspirate tip position should be used for both aspirate and dispense in a given "mix in source" for MoveLiquid steps.

**Comment by IanLondon** [comment]
For record-keeping, just rewriting what Brian said after we talked in person:

## Current behavior

I set "Aspirate" section's "Tip Position" to 80mm from bottom for my tall tube rack source
I set "Dispense" section's "Tip Position" to 5mm from bottom for my shallow 96-well destination

Now if I choose the "Aspirate" mix, it will aspirate at 80mm from bottom of the tall tube (a good height), and dispense far far too deep in the tube at 5mm from bottom, potentially submerging the pipette tip.

Now if I choose the "Dispense" mix, it will aspirate 80mm above the 96 well - the well is not that tall, so it will aspirate air! Then it will dispense 5mm from bottom, which would be an OK dispense height if there was actually liquid in there.

## Proposed new behavior

We have 4 heights (aspirate + dispense in source; aspirate + dispense in dest) but only 2 fields ("Aspirate" section and "Dispense" section tip height fields). So we could either:

1. Make the tip height in "Aspirate" section control the source well aspirate+dispense height, and the tip height in the "Dispense" section control the destination well aspirate+dispense height. So now I can set the tall tube to 80mm and the 96-flat to 5mm, and I will get: Inner Mix in source tube (aspirate 80mm, dispense 80mm), aspirate 80mm from source, dispense 5mm from dest, inner mix in dest well (aspirate 5mm, dispense 5mm). No more aspirating air or plunging the pipette too deep. But I can only give one number per labware. With this approach, I cannot aspirate 80mm from the tube and dispense above the tube at let's say 110mm.
2. Add fields so to give the user full control: aspirate in source; dispense in source; aspirate in dest; dispense in dest. We would need to add more fields to the form
3. A variation of the above: add asp/disp fields specific to the inner mixes.
