### ISSUE TITLE
Pipette Gen2: Alert User in Modal if Pipette Incompatible

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/opentrons#3432]
As a robot user, I would like to be alerted if the pipettes attached to my robot are incompatible with the pipettes attached to my robot, even though they appear to be the same model.

## Acceptance Criteria
- [ ] If pipette specified in protocol and pipette attached to robot are incompatible:
  - [ ] Display an error message below the "Go To Pipette Setup" on Pipettes card on File Info page
  - [ ] Display an alert modal warning them of the incompatibility
    - [ ] If pipette is a 1st generation pipette, add 'older' before name (see design).
    - [ ] If robot and protocol both have two incompatible pipettes, list all pipette names in modal
    - [ ] If robot and protocol have one incompatible and one mismatched pipette, display incompatibility modal.

Note full compatibility table is here:
https://docs.google.com/spreadsheets/d/1M6azQXZocWTqnEZDQ1Bpp9V1F9Fn86otdd4Go_LTIlQ/edit#gid=0

## Implementation Note
- Dependent on #3484 for to add in a ~'generational_version'~ 'displayCategory' key in the schema for pipetteNameSpecs

## Design
Single pipette incompatibility:
https://app.zeplin.io/project/5aa97729db58a2192f10d0d6/screen/5d0217088ac43c5dd4da8ef9

Two pipette incompatibility:
https://app.zeplin.io/project/5aa97729db58a2192f10d0d6/screen/5d0323f7ade24819ee212941

## Implementation Notes
- Use this story to add generic warning framework (handle warnings from robot in run app)?

**Comment by umbhau** [comment]
Decided in estimation to display an alert modal for all protocol <> robot pipette incompatibilities, not just gen2/gen1 issues.

FYI @pantslakz

**Comment by mcous** [comment]
@umbhau @pantslakz I have a few questions about this ticket:

- Why are we adding yet another modal instead of augmenting our existing warning section for pipette incompatibilities?
- Why are we allowing the user to continue if we know the pipettes are not compatible?

**Comment by btmorr** [comment]
Closed by #4185
