### ISSUE TITLE
Pipette+: Add configs for Multi-channel Pipette+ Variants

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/opentrons#3433]
## overview
Same set-up as the single channel configurations except the configs should be for multichannel. Constructors should also be added.

Names for the new pipettes should be:
`p+20_multi_v2.0`
`p+300_multi_v2.0`

Names for the constructors should be:
`P20_Plus_Multi()`
`P300_Plus_Multi()`

**Blocked until we have configurations from hardware**

**Comment by sfoster1** [comment]
Happened but wasn't closed
