### ISSUE TITLE
Protocol for Cleaning/Reusing Pipette Tips

### ISSUE THREAD

**Issue by eyesmo** [Opentrons/opentrons#3442]
## overview

Feature request: enable pipette tip washing+reuse between steps, or after a protocol is complete. This would help to minimize the cost and plastic waste per run.

## expected behavior

One possible way to implement this: at every step where tip exchange is required, instead of dumping the current tips in the waste bin, pipette them up and down 3x in 70% EtOH reservoir 1 and then 3x in H2O reservoir 1, and then eject tips into an empty, temporary tip box. Then, after the rest of the protocol is complete, retrieve each used tip from the rack and pipette them 3x sequentially in clean reservoirs of 70% EtOH, H2O, and/or soap solution, pipette the air to dry out the tips, and transfer to a clean/empty tip box. Protocols plating E. coli of different colors and setting up PCR reactions with different primer pairs that amplify DNA of different lengths could be used to validate tip cleanliness.

**Comment by mcous** [comment]
Cool idea @eyesmo! This protocol seems entirely writable in our existing API (which this repo is about), so I'm going to close this issue.

Feel free to open a request in <https://github.com/Opentrons/Protocols> if you would like to talk with our applications development team about contributing this sort of protocol to our public library
