### ISSUE TITLE
Close Opentrons App but 2 Opentrons procedure still run

### ISSUE THREAD

**Issue by simonchih** [Opentrons/opentrons#3482]
## overview
Environment:
Windows 10 x64
Opentrons app version 3.8.3

Just open Opentrons app and then close it.
The procedure of Opentrons are NOT all closed. Why?

## current behavior
Open Opentrons app will create 3 procedure but closed it only remove 1 procedure.
And there are still 2 Opentrons procedure.

## steps to reproduce
1. Open Opentrons app in windows 10 x64, it create 3 related procedure.
Check Task Manager:
[PIC](https://drive.google.com/open?id=1dvDfEcwtcraQdGUHEnHke6d4iV2_-rjh)

2. Close Opentrons app and then there are still 2 Opentrons procedure.
Check Task Manager:
[PIC](https://drive.google.com/open?id=1X5ZHER-_7F8w_IhCk8RQqvOEaSYMmGnO)

## expected behavior
In step 2, we want to end all 3 Opentrons related procedure.

**Comment by mcous** [comment]
Thanks for the bug report @simonchih! We've identified the problem and there is a fix incoming that will be in the next release of the app
