### ISSUE TITLE
Pipette Gen2: Update Name to "Gen2"

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3484]
As an Opentrons user, I would like my new Pipette Gen2 to be consistently named across all the software I used.

## Acceptance Criteria
- [ ] Replace all instances of the "Pipette+" name in SW with "Pipette Gen2"
- [ ] Add in a 'generational_version' key in the schema for pipetteNameSpecs

**Comment by pantslakz** [comment]
@umbhau does this ticket also include adding Pipette Gen2 to PD?

**Comment by Laura-Danielle** [comment]
@pantslakz no, this will be covered in #3483
