### ISSUE TITLE
Run App: Metadata fields in RA uses the file name instead of metadata key from file

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/opentrons#3494]
## overview
Run App should support new metadata shape for v3 protocol designer protocols.

## current behavior
- If you change the "name" of the protocol in metadata nothing happens with a v3 protocol, only when you change file name does the Protocol Name change.

## expected behavior
- The metadata key in v3 should be used for the Protocol Name change, and fall back to file name if metadata cannot be found.

Can use [this protocol](https://github.com/Opentrons/opentrons/files/3208408/full-forSethBot.json.zip) to test

**Comment by Kadee80** [comment]
Just started looking into this issue. Looks like there were more changes than just the protocol name:

- `data.protocol-schema` => `data.schemaVersion` 
- `data.metadata.protocol-name` => `data.metadata.protocolName`
- `designer-application.application-name` => No longer present?

@IanLondon @Laura-Danielle are we planning on putting the `designer-application` info into the V3 protocol designer protocols? If not, we lose the creation method info for PD protocols on the file info page.

**Comment by IanLondon** [comment]
@Kadee80 It's `designerApplication.name` where both `designerApplication` and `name` are optional keys

**Comment by Kadee80** [comment]
@IanLondon same goes for `designer-application.application-version` => `designerApplication.version` ?

**Comment by IanLondon** [comment]
@Kadee80 that's correct!
