### ISSUE TITLE
API V2: Updating Firmware is Unsuccessful, Robot remains in Virtual Smoothie

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/opentrons#3501]
## overview
When you try to update a robot from one firmware version to another in _V2_ api, the firmware remains in `Virtual Smoothie` mode.

## steps to reproduce

Put a robot on a SW version earlier than 3.9.0 and ensure the V2 feature flag is set. Update that robot to 3.9.0 and observe that it remains in `Virtual Smoothie` mode.

Hints: Take a look at how connecting in simulation is handled for V2 vs V1

## expected behavior

Robot should be able to successfully update/connect to a freshly updated firmware.

**Comment by sfoster1** [comment]
Specifically, this is the update that should happen when the API server boots and either has an issue connecting to the smoothie or sees that its version does not match the version of the firmware image stored in the wheel.
