### ISSUE TITLE
V2 labware: API should validate labware defs against schema

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#3504]
## overview

`Labware.load_from_definition` (or maybe `ProtocolContext.load_labware_from_definition`? or the Labware constructor?) should check that a given definition validates for its schema.

Similar to how the JSON executor validates JSON protocols...

* It should raise the validation error from `jsonschema` if validation fails.
* It should throw a "not yet supported" error if the `schemaVersion` is higher than 2.
* It should throw a "not supported" error if the schemaVersion key is missing (NOTE: labware v1 did not have this key, but users never manages v1 labware files)

**Comment by sfoster1** [comment]
It does!
