### ISSUE TITLE
Make it easier to see tip tracking state

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#351]
Often when writing a protocol, I want to figure out how many tips I really need.

I might be missing an easy workaround for this, but since `Pipette.tip_rack_iter` is an `iter`, if I want to look how many tips are left, I can do `list(p200.tip_rack_iter)`. But by doing this, I've 'consumed' all my tips!

Is there an easy win for viewing tip tracking state without deeply changing how Pipette works?

https://github.com/OpenTrons/opentrons/blob/3e21da28a24cabe1f9dad4e80c781eb9ebfd4144/api/opentrons/instruments/pipette.py#L176

**Comment by astaff** [comment]
Try:
```python

def get_tracking_state(pipette):
    from itertools import tee
    pipette.tip_rack_iter, tips = tee(pipette.tip_rack_iter)
    return len(list(tips))
```

if there is a use case for it in the API we can document it and make it a Pipette's property (cc @btmorr @LauraOpentrons )

**Comment by IanLondon** [comment]
Cool! This might be a good item for an "advanced" section in the cookbook docs http://docs.opentrons.com/cookbook.html

**Comment by sfoster1** [comment]
Maybe we'll add this to v2, but let's make a new ticket if so.
