### ISSUE TITLE
rpc: Add a warning message type

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#3535]
To enable us to display warning messages sourced from the api without halting execution for errors, we should add a warning essage to the rpc. This message should be structured like

```
{
"$": {
"type": WARNING_TYPE # This is a new constant to add
},
"message": str, # a human-readable warning message
"origin": str, # a human-readable string indicating the source of the warning (i.e. protocol line)
}
```

Add this in a couple places where we today raise `RuntimeWarning` or use the `warnings` module.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535406713) by [Unito](https://www.unito.io/learn-more)

**Comment by mcous** [comment]
If at all possible, I would really like to avoid sinking any more feature work into RPC. What are the specific warnings we're trying to add, and could they be surfaced in the simulation stage?

**Comment by SyntaxColoring** [comment]
Closing this as `wontfix` in favor of #8042. Our RPC subsystem will soon be deprecated, but we still need to address this in the HTTP API that's replacing it.
