### ISSUE TITLE
Apiv2 Last Mile: Integrate IPC hardware controller with protocol API

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#3545]
Integrate the IPC frontend from #3544 for hardware controller into the various places it might be used. Add an easy way to construct this frontend for use in the protocol API. Have it done by default when the software is used as a library in Jupyter or invoked directly from the robot's command line.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535406769) by [Unito](https://www.unito.io/learn-more)

**Comment by mcous** [comment]
Ticket no longer applicable. Hardware control process / IPC will get new tickets when necessary
