### ISSUE TITLE
Robot Update: View Update Notification

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3561]
As a Run App user, I would like to be notified when a Robot System update is available, so that I can initiate the update process.

## Acceptance Criteria
- [ ] Modal informing user robot system update is available

#### If robot is on balena and requires migration:
- [ ] Inform user that the process will take 10-15 mins, will require two restarts, and that the robot needs to be discoverable the entire time (first link)

#### If robot is on buildroot and requires update:
- [ ] Display standard / simpler update modal (second link)

#### All users/robots:
- [ ] User has option to ignore the update by clicking [NOT NOW]
  - [ ] ~If user started from manually upload robot software, cancel flow~
  - [ ] If flow started from automatic download, cancel flow and mark version ignored
- [ ] User has the option to click [VIEW ROBOT UPDATE]

*note* Implement release notes from buildroot files not current API release notes implementation + dynamic title to be covered in #3562

*note* `If user started from manually upload robot software, cancel flow` may not be applicable based on implementation of #3560

## Design
https://zpl.io/V45J7kp (migration), https://zpl.io/brMN9J1 (update)

**Comment by Kadee80** [comment]
@sfoster1 for the section `If robot is on buildroot and requires update` can we infer this from the capabilities section in health: `capabilities: {'buildroot-update': '/server/update/begin'}`
