### ISSUE TITLE
Robot Update: View Update Errors

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3563]
As a Run App user, I would like to know if any errors occurred during my update, so I can troubleshoot and try again.

## Acceptance Criteria
- [ ] If any errors during robot or robot system update, display a generic error modal in the Run App
- [ ] Modal should include any error message returned from Robot
- [ ] Modal should be dismissable

## Design
- @pantslakz @Kadee80 believe we have a generic error modal we can use for this, but please confirm.

**Comment by btmorr** [comment]
Closed by #3803
