### ISSUE TITLE
Robot Update: Alert When Disconnected During Update

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3564]
As a Run App user, I would like to be alerted if my app disconnects from my robot unexpectedly during a robot update, so that I can reconnect to my robot and continue to monitor update progress.

## Acceptance Criteria
- [ ] If app loses connection to the robot during update, display an alert modal informing using of the connection failure
- [ ] User can dismiss modal

**Comment by mcous** [comment]
Build root update requests are individual requests, not a persistent connection. If the app is unable to make any one of these requests, the regular error handling logic in #3563 will be triggered. Closing this ticket as not applicable to the update process
