### ISSUE TITLE
Robot Update: View Update Server Update Status

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3565]
As a Run App user, I would like to know when my robot is busy updating its API and update server, so that I can sit tight and wait patiently for it to finish.

## Acceptance Criteria
- [ ] Inform user update will take 3-5 min and robot will restart automatically when complete
- [ ] Display an animation to let the user know the robot is working 
- [ ] Restart robot automatically when complete

## Design
https://zpl.io/brMrQgr (migration only)

**Comment by mcous** [comment]
Implementation ideas now that #3765 is in:

We should have enough information in state to have a selector that can return the following:
- Robot update status, one of:
    - Bootstrapping update server (this ticket)
        - Indeterminate progress, anecdotally takes about 1-2 minutes
