### ISSUE TITLE
Runtime error with tuberack 

### ISSUE THREAD

**Issue by Gylianne** [Opentrons/opentrons#3566]
Hi, 
I'm having a Runtime error at:   labware.load('opentrons-tuberack-15ml', '1') and I was wondering if anyone else had encountered similar errors.

**Comment by mcous** [comment]
Hi @Gylianne, sorry for the delay! I recommend that you:

- Ensure your app is fully up to date
- After you've checked the app's version, check that your robot is fully up to date
- Make sure that all your robot's advanced settings are switched off (at the bottom of the robot settings page in the app)

If those initial steps don't help, please reach out to our support team via in-app chat or by going to <https://support.opentrons.com>. I'm going to close this issue as a support request for now, but will re-open and/or update it if we find any sort of underlying bug!
