### ISSUE TITLE
Robot Update: View Robot System Update Status

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3567]
As a Run App user, I would like to be able to see the progress of my robot's system update, so that I know roughly how long it will take.

## Acceptance Criteria
- Inform user that update will take 5 minutes (double check this after testing) and that robot will restart automatically after update.
- Display basic progress bar (single-stage)
- Restart robot when complete
- Title bar differences between migration vs update
    - Migration: Step 2 of 2
    - Update: N/A

## Design
https://zpl.io/aNDpjdZ (migration), https://zpl.io/25pqQdj (update)

**Comment by mcous** [comment]
Resizing to a medium because:

- Update functionality in place via #3771 
- Progress bar component built by #3744 
- State is in place, ticket will require selector buildout (discussed in [this comment](https://github.com/Opentrons/opentrons/issues/3565#issuecomment-514679825))
