### ISSUE TITLE
Robot Update: View Update Success Modal

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3568]
As a Run App user, I’d like confirmation that the robot system update is successful and complete.
## Acceptance Criteria
- [ ] Display modal informing user update is complete after final reboot
- [ ] User can dismiss modal

## Design
~https://zpl.io/bJGKAjW (migration)~ removing to reduce scope (MC), https://zpl.io/V451gD4 (update)

**Comment by mcous** [comment]
Bumping up to a medium because additional polling epic may be required to accurately track robot restart state
