### ISSUE TITLE
No documentation for new_tip='once'

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#357]
I can't find any documentation on docs.opentrons.com for `new_tip='once'` -- is it not supported?

**Comment by astaff** [comment]
`Pipette.transfer` docstring needs to be updated to reflect string values for `new_tip` (`once` /  `never` / `always`) instead of numerical.

**Comment by IanLondon** [comment]
still true in https://docs.opentrons.com/api.html#module-opentrons.instruments
