### ISSUE TITLE
Pipette Gen2: P1000 config modifications

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#3574]
HWeng indicates the following changes to p1000 config:
- Modify aspirate/dispense function
- Add pickup tip shake by default
- New plunger positions

**Comment by ChrisYarka** [comment]
Function Update:

50.05 | 0.0456 | 23.83
77.11 | 0.0250 | 23.78
104.6 | 0.0164 | 24.44
132.1 | 0.0095 | 25.16
187.3 | 0.0062 | 25.60
215.0 | 0.0041 | 25.99
325.6 | 0.0024 | 26.36
436.1 | 0.0011 | 26.76
1075 | 0.0004 | 27.07


![image](https://user-images.githubusercontent.com/47226416/60186162-3c8c7680-97f9-11e9-8439-ae58098c9c4d.png)

**Comment by ChrisYarka** [comment]
steps/mm = 3200

**Comment by ChrisYarka** [comment]
P1000 Plunger Positions:
top = 19.5 
bottom = -18.5
blowout = -23
drop tip = -37

**Comment by ChrisYarka** [comment]
![image](https://user-images.githubusercontent.com/47226416/60192708-57181d00-9804-11e9-830a-9bb2ea5b4f6a.png)

**Comment by ChrisYarka** [comment]
https://docs.google.com/spreadsheets/d/1faebzB-o9H1EFUyCtUBaGqAWodQFq5mfhqbgBL8L8v4/edit#gid=212246552
