### ISSUE TITLE
Pipette Gen2: P20 Config Modification

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#3575]
For DVT, the p20 needs the following config changes:

- New aspirate/dispense function
- New plunger positions

**Comment by ChrisYarka** [comment]
P20 Aspirate AND Dispense Function:


1.307 | 0.0666 | 0.6237
2.095 | 0.0566 | 0.6428
2.865 | 0.0233 | 0.6675
3.600 | 0.0211 | 0.7054
4.412 | 0.0190 | 0.7224
5.135 | 0.0120 | 0.7448
5.900 | 0.0051 | 0.7111
8.913 | 0.0017 | 0.7325
12.01 | 0.0015 | 0.7276
15.11 | 0.0014 | 0.7379
18.22 | 0.0013 | 0.7402
22.00 | 0.0011 | 0.7423


![image](https://user-images.githubusercontent.com/47226416/60205716-f0086180-981f-11e9-8ef4-4a908ac52dd6.png)

**Comment by ChrisYarka** [comment]
steps/mm = 3200

max speed = 30 mm/s

quirks = no change. keep the drop tip shake.

**Comment by ChrisYarka** [comment]
Plunger Positions:

top = 19.5
bottom = -8.5
blowout = -13
dropTip = -27

**Comment by ChrisYarka** [comment]
![image](https://user-images.githubusercontent.com/47226416/60210124-1a5f1c80-982a-11e9-88db-fb0109e794f6.png)

**Comment by ChrisYarka** [comment]
https://docs.google.com/spreadsheets/d/1faebzB-o9H1EFUyCtUBaGqAWodQFq5mfhqbgBL8L8v4/edit#gid=442591547
