### ISSUE TITLE
Pipette Gen2: P300S config modifications

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#3576]
Pipette Gen2 P300s needs the following config modifications:

- Plunger positions

**Comment by ChrisYarka** [comment]
P300 Function Update

17.060 | 0.0472 | 8.1073
26.239 | 0.0236 | 8.1277
35.458 | 0.0128 | 8.4095
44.745 | 0.0091 | 8.5417
63.509 | 0.0070 | 8.6355
110.426 | 0.0062 | 8.6574
148.131 | 0.0038 | 8.7878
330.000 | 0.0005 | 9.1770

![image](https://user-images.githubusercontent.com/47226416/60203927-c0eff100-981b-11e9-93da-19e53eeca483.png)

**Comment by ChrisYarka** [comment]
steps/mm = 3200

max speed = 30 mm/s

quirks = no change from EVT. keep the drop tip shake.

**Comment by ChrisYarka** [comment]
P300 Plunger positions


top = 19.5
bottom = -14.5
blowout = -19
dropTip = -37

**Comment by ChrisYarka** [comment]
![image](https://user-images.githubusercontent.com/47226416/60204337-a0746680-981c-11e9-830b-4fae9b1a94a8.png)

**Comment by ChrisYarka** [comment]
https://docs.google.com/spreadsheets/d/1faebzB-o9H1EFUyCtUBaGqAWodQFq5mfhqbgBL8L8v4/edit#gid=1540046538
