### ISSUE TITLE
Thermocycler: Deactivate at End of Run

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3579]
As a Thermocycler user, I would like my Thermocycler to deactivate at the end of a protocol run, so that I don't accidentally leave it on for an extended period of time.

## Acceptance Criteria
- [ ] Thermocycler should deactivate at end of Protocol run, whether run completes or is cancelled by user.
- [ ] User should be notified that thermocycler will deactivate before cancelling their run (e.g. in the cancel dialogue box)
- Thermocycler lid should remain in current open or closed state by default

**Comment by b-cooper** [comment]
No longer the decided design
