### ISSUE TITLE
Thermocycler: Open and Close Lid With HW Button

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3582]
As a Thermocycler user, I would like to be able to open or close the Thermocycler using the physical button on the module.

## Acceptance Criteria
- [ ] Pushing button toggles physical lid state (opens if closed; closes if open)
- Note opening or closing lid should not disrupt run

## Implementation Notes
- Note TC is not aware of Protocol state

**Comment by pantslakz** [comment]
Updates to this flow:

- user able to open/close regardless of temperature
- user able to open/close mid cycle without disrupting run
- only run pause or run stop enables user option to "deactivate" TC

**Comment by bndo** [comment]
This is addressed in #3808
