### ISSUE TITLE
Pipette Gen2: Inform User on File Overview if Pipette Incompatible

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3595]
As a Run App user, I would like to know if the pipette specified in my protocol is incompatible with the pipette attached to my robot.

## Acceptance Criteria
- [ ] If pipette specified in protocol and pipette attached to robot are incompatible, display "Required pipette is missing" in the "Required Pipettes" card on the "File Overview" page.
  - Note this is an existing alert message.

### Compatibility
Note pipettes are incompatible if:
- Protocol specifies Gen2 pipette and robot has Gen1 pipette
- Protocol specifies a P50 Gen1 pipette and robot has any Gen2 pipette
- Protocol specifies a P20 pipette Gen2 pipette and robot has any Gen1 pipette
- Gen2 pipette specified in the protocol is different than the Gen2 pipette attached to the robot
- Gen1 pipette specified in the protocol is different than the Gen1 pipette attached to the robot

Full list of compatibility here:
https://docs.google.com/spreadsheets/d/1M6azQXZocWTqnEZDQ1Bpp9V1F9Fn86otdd4Go_LTIlQ/edit#gid=0

## Design
https://app.zeplin.io/project/5aa97729db58a2192f10d0d6/screen/5d0217088ac43c5dd4da8ef9

**Comment by Laura-Danielle** [comment]
Covered by #3432 , ticket no longer needed.
