### ISSUE TITLE
Pipette Gen2: Remove Gen2 feature flags from app

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/opentrons#3601]
## overview

Prior to the customer launch of GEN2 pipettes, we need to promote to following feature flags to default behavior:

- The app's `enablePipettePlus` flag

## Acceptance Criteria

- [ ] GEN2 pipettes appear in app's change pipette wizard by default

**Comment by mcous** [comment]
PD FF moved to #4295
