### ISSUE TITLE
Labware V2: Warn User About Labware Migration

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3611]
As a user, I would like to be informed that I am migrating to new labware, so that I know to recalibrate.

## Acceptance Criteria
- [ ] Update copy of migration modal in PD to inform user that labware is being migrated
- [ ] Inform user that they should recalibrate their labware
- [ ] Update line spacing to be a bit bigger ( on the wireframe below it's set to 19)
- [ ] Clicking "cancel" will close the modal and the file will not be uploaded
- [ ] Clicking the lengthy "accept" button will migrate the protocol 

## Design
![image](https://user-images.githubusercontent.com/35570080/59871474-ab834e80-9365-11e9-8901-15b6b355de75.png)

**Comment by pantslakz** [comment]
@IanLondon see new modal copy here:
![Screen Shot 2019-06-26 at 12 16 42 PM](https://user-images.githubusercontent.com/2686086/60172149-5c796580-980c-11e9-96e2-a3f2db1327ad.png)
