### ISSUE TITLE
Pipette Gen2: CLI Deck Calibration

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#3612]
When we move pipette gen2 to production, we will stop production on gen 1s. That means they will no longer be available during robot production to run CLI deck calibration, and may not be available to customers.

CLI deck calibration currently requires and assumes a P300 single with GEB 300ul tips; we need to make it adapt to pipette gen2 p300s (or really, any pipette).

**Comment by umbhau** [comment]
@sfoster1 Given that people are using CLI deck calibration in the field, may make sense to support all Gen2 pipettes (as you called out above).
