### ISSUE TITLE
Inconsistent Tip Position During Transfer

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3654]
## Expected Behavior
- When a single transfer command is broken down into multiple sub-transfers, each sub-transfer should use the same tip height.

## Observed Behavior
- Only the first sub-transfer uses height specified in protocol; following transfers use default height.

## Steps to Recreate
Note did not recreate this on a robot; steps per Kinnari's bug report and Seth's code review.

1) Create a protocol with a single transfer from one well to another, a transfer volume greater than the maximum pipette capacity, and a initial tip height higher than the default (1mm) height.
2) Observe that pipette moves to specified initial tip height for initial transfer, and then to default 1mm tip height for subsequent transfers.

**Comment by sfoster1** [comment]
This is a known issue - or really, known not to be a feature - in protocol API v1. In protocol API V2, it works: you can specify locations (the output of `Well.top()` or other location accessors) in your source and destination lists and they'll be respected even if the transfer plan has to split them up:

This is the internals of a transfer. The transfer plan is the sequence that the robot will execute. Note that the positions it uses correspond with the `.top(z=5)` I specified in the source and destination lists:

```
>>> from opentrons.protocol_api import transfers
>>> from opentrons import simulate
>>> ctx = simulate.get_protocol_api('2.0')
>>> tr = ctx.load_labware('opentrons_96_tiprack_300ul', '1')
>>> plate = ctx.load_labware('corning_96_wellplate_360ul_flat', '2')
>>> instr = ctx.load_instrument('p300_single', 'right', tip_racks=[tr])
>>> tp = transfers.TransferPlan(600, plate['A1'].top(z=5), plate['A2'].top(z=4), instr, 300)
>>> itp = iter(tp)
>>> next(itp)
{'method': 'pick_up_tip', 'args': [], 'kwargs': {}}
>>> next(itp)
{'method': 'aspirate', 'args': [300, Location(point=Point(x=162.88, y=106.24, z=67.22), labware=A1 of Corning 96 Well Plate 360 µL Flat on 2), 1.0], 'kwargs': {}}
>>> plate['A1'].top(z=5)
Location(point=Point(x=162.88, y=106.24, z=67.22), labware=A1 of Corning 96 Well Plate 360 µL Flat on 2)
>>> next(itp)
{'method': 'dispense', 'args': [300, Location(point=Point(x=171.88, y=106.24, z=66.22), labware=A2 of Corning 96 Well Plate 360 µL Flat on 2), 1.0], 'kwargs': {}}
>>> next(itp)
{'method': 'aspirate', 'args': [300, Location(point=Point(x=162.88, y=106.24, z=67.22), labware=A1 of Corning 96 Well Plate 360 µL Flat on 2), 1.0], 'kwargs': {}}
>>> next(itp)
{'method': 'dispense', 'args': [300, Location(point=Point(x=171.88, y=106.24, z=66.22), labware=A2 of Corning 96 Well Plate 360 µL Flat on 2), 1.0], 'kwargs': {}}
>>> next(itp)
{'method': 'drop_tip', 'args': [], 'kwargs': {}}
```
