### ISSUE TITLE
PD: Multichannel pipettes crash when dispensing to trash

### ISSUE THREAD

**Issue by opatel0** [Opentrons/opentrons#3676]
## overview

When dispensing to the fixed trash container on the deck, multichannel pipettes crash against the edge of the fixed trash.

## current behavior

When dispensing to trash using a multichannel pipette, the multichannel is not centered in the trash and is instead positioned so that when the pipette lowers, it crashes against the southern edge of the trash bin, causing tips to fall and liquid to spill on the deck. 

## steps to reproduce

This issue occurred on v3.9.0 of robot server, protocol developed using v1.1.0 of PD, and with v1.3 and v1.5 p10 multi and p300 multi pipettes. In any transfer step in which the destination is the fixed trash, the pipette will collide with the fixed trash's edge.

POTENTIALLY RELATED NOTE: similar behavior can be observed with fixed trash in python protocols depending on how the command is written.
pipette.blow_out(fixed-trash) for example will result in similar behavior, but this issue can be resolved by writing the line as such: pipette.blow_out(fixed-trash[0])

## expected behavior

When dispensing to the fixed trash using a multichannel pipette, the pipette should be centered in the fixed trash and avoid collision with the edge of the trash.

**Comment by opatel0** [comment]
Here are the customer protocols 
[drug addition 2.zip](https://github.com/Opentrons/opentrons/files/3370144/drug.addition.2.zip)
[adding drug3.zip](https://github.com/Opentrons/opentrons/files/3370166/adding.drug3.zip)

**Comment by IanLondon** [comment]
Confirmed that on edge d214c5adef15d4b575beaf29584caa375b80d4f3 v3 JSON protocols still have this issue.

**Comment by IanLondon** [comment]
Also in APIv1 Python protocols, dispense to trash eg `multichannel.transfer(8, samples['A1'], robot.fixed_trash['A1'])` will cause an identical crash.

**Comment by IanLondon** [comment]
Blocked - requires a significant amount of APIv1 refactoring. Hopefully we can move to APIv2?

**Comment by umbhau** [comment]
Closing. Will not fix in API v1; fixed in API v2.

**Comment by btmorr** [comment]
Changing APIv1 server to use APIv2 labware definitions allows us to fix this in an acceptable way. PR forthcoming

**Comment by btmorr** [comment]
Oh, nevermind. I thought an in flight change was going to fix this, but this is intractable.
