### ISSUE TITLE
Pipette 1.5: Add P50S v1.5

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#3680]
# overview

Hardware engineering is doing a minor revision to the SOP and design of the P50S. We need to add a v1.5 config to pipetteModelSpecs.json with the changes.

**Comment by yunhodavidkim** [comment]
P50S V1.5 Function: 

max uL | slope | intercept
5.762111167 | 0.02912395377 | 2.7132
7.208999967 | 0.001758534127 | 2.8709
10.18300033 | 0.008684827443 | 2.8210
35.954444 | 0.003367098915 | 2.8751
42.075889 | 0.001505686352 | 2.9421
50 | 0.001091358226 | 2.9595
