### ISSUE TITLE
Apiv2 Last Mile: Add modules to socket server/client

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#3686]
## overview
The socket server and client introduced in #3650 and #3633 do not yet have support for modules, since that is a more complicated task introducing separate objects. This issue is for adding module support.

The client should provide module proxy objects that can work in place of the hardware control module objects sent to the protocol API. Calls and data should be serializable across jsonrpc. This may require adding server-originated notifications for callbacks to the protocol API.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535408839) by [Unito](https://www.unito.io/learn-more)

**Comment by mcous** [comment]
Ticket no longer applicable. Hardware control process / IPC will get new tickets when necessary
