### ISSUE TITLE
Memoize selectors with reselect

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#371]
## overview

During the alpha push, we've piled up a lot of selectors, especially related to tracking robot and calibration state. At the moment, these selectors are not memoized, which means we're doing a lot of duplicate calculations and generating a bunch of objects for the garbage collector. Memoizing the selectors with [reselect](https://github.com/reactjs/reselect) will reduce duplicate calculations and unnecessary intermediate objects

This issue is for:

- [X] Bug, feature request, or other? **Chore work**
- [X] API, App, both? **App**
- [X] Version? **v3.x.x**
- [X] OS and OS version? **All**

**Comment by IanLondon** [comment]
:tada: woo `reselect` rocks, it also lets you compose selectors with less boilerplate :guitar:

**Comment by IanLondon** [comment]
While we're at it, we may want to clean up robot selectors to make them single-labware-oriented and make "is robot moving now" and "is robot interacting with labware X now" selectors
