### ISSUE TITLE
APIv2: Flow rate setter fails to actually modify the pipette flow rate

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/opentrons#3720]
## overview
This is an issue to record a bug found with the flow rate setter.

## current behavior

Flow rate does not change unless you specify a fractional amount in the atomic `aspirate` and `dispense` functions.

## steps to reproduce

Try this small protocol on API V2:
```
def run(ctx):
    tiprack = ctx.load_labware_by_name('opentrons_96_tiprack_300ul', 1)
    plate = ctx.load_labware_by_name('corning_96_wellplate_360ul_flat', 2)
    pipette = ctx.load_instrument('p300_single', tip_racks=[tiprack], mount='right')
    # without flow rate change
    pipette.transfer(100, plate.wells()[0:8], plate.wells()[8:16])
    # with flow rate change
    pipette.flow_rate = {'aspirate': 50, 'dispense': 50}
    pipette.transfer(100, plate.wells()[16:24], plate.wells()[24:32])
```

## expected behavior
Flow rate should change to the value you set it to in your protocol, and remain at that value until otherwise specified.

**Comment by sfoster1** [comment]
Closed by #3739
