### ISSUE TITLE
"Connect to Robot" button off-screen on low-resolution displays

### ISSUE THREAD

**Issue by btmorr** [Opentrons/opentrons#373]
## overview

On a low-resolution monitor, the "Connect to Robot" button appears below the screen and is unreachable. Screen resolution where bug was observed is 1366x768. I was able to bring the button on-screen by changing the `.nav_panel.grid-template['details']` field to 500px.

This issue is for:

- [x] Bug, feature request, or other? **Bug**
- [x] API, App, both? **App**
- [x] Version? **app-3-0-alpha**
- [x] OS and OS version? **Linux Mint 18 Cinnamon**

**Comment by mcous** [comment]
Pretty sure this was fixed in an earlier PR, too, but it was definitely fixed by #385 where the connect button was moved into a robot card that shows up in the new connectivity panel
