### ISSUE TITLE
Pipette Gen2: warn about plug complications

### ISSUE THREAD

**Issue by b-cooper** [Opentrons/opentrons#3730]
## overview

The design of the GEN2 plug is a little different than before and has the side effect of being hard to plug in once the three mounting screws are tightened (only for older OT2's).

In this case it is easier to plug it in first, and then screw it onto the mount.

Should we warn or guide users in this case?

**Comment by btmorr** [comment]
May no longer be an issue. @b-cooper please double-check, and close this ticket if so

**Comment by b-cooper** [comment]
Looks like this isn't as much of an issue on the DVT models. Closing as this fix won't necessarily make it easier.
