### ISSUE TITLE
Pipetting Behavior: Drop Tips Before Homing Plunger to Avoid Contamination

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3738]
As an OT-2 user, I would like my OT-2 to drop tips before homing the plunger, so that my pipettes aren't contaminated when the OT-2 homes its plunger axis.

## Acceptance Criteria

* [ ] Drop tips in fixed trash before homing pipette plunger axis
* [ ] Note this is a common issue when users cancel runs
* [ ] Wording for cancel modal is modified to:
```
Canceling this run will immediately end the current protocol run, home your robot and drop any attached tips.
Any modules used within this protocol will remain active until you deactivate them.
```

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535409532) by [Unito](https://www.unito.io/learn-more)

**Comment by btmorr** [comment]
Should this be "drop tip before homing plunger"?

**Comment by James-Kitson** [comment]
I'd like to second this, I had to cancel a run today and I forgot that the robot does this. It managed to suck liquidised tissue through a filter up into the pipette before I spotted what was happening.

Ideal behaviour:
1. Cancel run.
2. Pipette moves to fixed waste bin and drops tips without any aspirating action.
3. Pipette does any homing that is required.

**Comment by umbhau** [comment]
@btmorr Yes, updated the issue -- now generalized to any time the pipette homes its plunger axis.

@James-Kitson Thank you for the comment -- this one is on our radar and near the top of the priority list.

**Comment by SyntaxColoring** [comment]
Changed the title of this ticket to match the August 16, 2019 edit, which I think mistakenly just edited the body.

**Comment by SyntaxColoring** [comment]
I'm not 100% sure, but I think ejecting tips before homing plungers isn't always going to be possible.

In particular, when the OT-2 boots, it won't know the pipettes' plunger positions until they're homed for the first time. So, it won't know how far to move the pipette motor to engage the tip ejector.
