### ISSUE TITLE
APIv2: docs: Doc Scrub

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#3751]
## overview
![doc (scrub)](https://vignette.wikia.nocookie.net/scrubs/images/0/09/S8-HQ-Cox.jpg/revision/latest/top-crop/width/240/height/240?cb=20081228195729)

Get through all the docs and find out what's wrong and make little changes. List them here as they come up:

- Call out labels for labware load

**Comment by ahiuchingau** [comment]
* In the table that shows the differences between _transfer_, _consolidate_ and _distribute_ in `new_complex_commands`, all three scenarios are listed as **No** for consolidate. It should say **Yes** for `Many source wells to one destination well`
