### ISSUE TITLE
Apiv2: Timebox: async smoothie

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#3754]
## overview
Take a day to use something like [pyserial-asyncio](https://github.com/pyserial/pyserial-asyncio) and prototype a smoothie driver that correctly runs in an event loop, for apiv2 only. Evaluate the effects it would have on the system.

Figure out whether this will:

* Prevent the event loop from blocking when the robot is paused
* Prevent the event loop from blocking in general during smoothie communications

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535409926) by [Unito](https://www.unito.io/learn-more)

**Comment by mcous** [comment]
No longer applicable
