### ISSUE TITLE
Thermocycler: Alert User of Module Malfunction

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3767]
As a Thermocycler user, I would like to know if my Thermocycler experiences an internal (firmware) failure or malfunction. Currently, this is specifically for internal thermocycler failure (bad thermistor), which would happen (or be detected) during run, and would require a HW replacement.

## Acceptance Criteria
- [ ] Failure terminates run
- [ ] App alerts user with actionable message

**Comment by btmorr** [comment]
Should lid auto-open? How do we envision the user recovering from this?

**Comment by btmorr** [comment]
cc @pantslakz for designs re: how do we show the error to users

**Comment by btmorr** [comment]
This is now centered around physical failures in the Thermocycler, such as a thermistor failure. In these cases, we will raise an error that will terminate a protocol run, and use the existing error modals to show an error message to the user with actionable info.

**Comment by b-cooper** [comment]
This is addressed in a firmware change in https://github.com/Opentrons/opentrons-modules/pull/96 .  The module itself now has a visible error state.  This should eventually be accompanied by a runtime message, though that messaging should ideally be included once the current RPC session api implementation has been replaced.
