### ISSUE TITLE
Buildroot update: UX review and polish

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#3817]
## overview

This ticket is for tracking a UX review of the buildroot update front-end flow once we have an MVP implemented.

## flows

- [x] Migration from Balena to buildroot via automatic app download
- [x] Migration from Balena to buildroot via manual file upload
- [x] Regular buildroot upgrade
- [x] Regular buildroot downgrade
- [x] Regular buildroot re-install
- [x] Re-evaluation of app update available logic

**Comment by Kadee80** [comment]
Closed via meeting/discussion between stakeholders. 
TODO: unify all restart flows within wizards in the run app.
