### ISSUE TITLE
(v3, chore) Fix lint errors to get CI back to green

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#382]
`v3a` is currently [failing due to lint errors](https://travis-ci.org/OpenTrons/opentrons/builds/292767399). It would be lovely to fix those up and get our CI build back to green where it belongs

![giphy-downsized-large](https://user-images.githubusercontent.com/2963448/32037566-e1bf36b4-b9f3-11e7-8583-815fc844e22d.gif)

**Comment by astaff** [comment]
api tests are broken as well with too much debug output to see the error

**Comment by mcous** [comment]
> api tests are broken as well

Shoot, couldn't see that in Travis because the test command is:

```shell
python -m pylama opentrons tests && python -m pytest
```

Do we want to consider switching the test + lint task order in the API? On the app side we run test and then lint to make sure the more important thing (test failures) gets reported

**Comment by mcous** [comment]
Why was this issue closed? `v3a` CI is still red
