### ISSUE TITLE
No instructions to remove tip after successful tip probe

### ISSUE THREAD

**Issue by astaff** [Opentrons/opentrons#386]
# Expected

After successful tip probe, inform the user to remove the tip. Additionally it would be nice to instruct the user that the tip should be off during container calibration.

# Actual

No instructions after successful tip probe or before container calibration. It is likely that the user will leave the tip resulting in colliding with trash at minimum.

`app/ui/components/TipProbe.js` seems to have `ProbeSuccess` mentioning that, but it doesn't seem to be wired.

**Comment by mcous** [comment]
Fixed in #399
