### ISSUE TITLE
(v3) Upload onchange doesn't fire more than once for the same file

### ISSUE THREAD

**Issue by astaff** [Opentrons/opentrons#387]
# Expected

In the app, after loading a protocol containing an error, I expect to be able to fix the error and load the protocol again.

# Actual

1. Upload protocol with an error
2. Error screen is displayed
3. Load valid protocol
4. Screen is not changed and no message dispatched to the backend

Does it have anything to do with https://github.com/Opentrons/opentrons/issues/380 ?

**Comment by mcous** [comment]
Yeah, this sounds very much related to #380, or at the very least difficult to diagnose until #380 is fixed. Are you going to have time to work on that or shall I take care of it?

**Comment by astaff** [comment]
Looks like the user needs to change the screen after upload in order to upload again. Uploading, the switching to connect panel and then switching back seems to resolve the issue

**Comment by mcous** [comment]
Able to confirm that we upload button only works once, outside of #380

**Comment by mcous** [comment]
Fixed by #499
