### ISSUE TITLE
Labware positional data is not updated during calibration session for labware of the same type

### ISSUE THREAD

**Issue by astaff** [Opentrons/opentrons#388]
Deck setup: `96-PCR-flat` in slots `B2` and `C2`

# Expected

When calibrating labware I expect new calibration values to apply to the rest of the containers of the same type on the deck during calibration session.

# Actual

During calibration, when calibrating `96-PCR-flat` in `B2` I jog to correct location of A1 and save calibration data. When the robot moves to the container of the same type in `C2` it moves to un-calibrated position.

**Comment by mcous** [comment]
For collision prevention this is / will be the desired behavior
