### ISSUE TITLE
PL: Create Global parameters field and parse it

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/opentrons#3896]
## overview

Currently on the protocol library we do this ugly injection thing to get parameters working. Now we want to reduce the overhead of this by simply using a global dictionary at the top of the file.

## expected behavior

Proposed shape of the global dictionary:

```
parameters = {
    nameOfParameter: {
            default: defaultParam,
            options: can be a list, int or other object type
}
```

Once this is in place, we will also need to modify the parser to search the file for this dictionary in order to populate the parameters for the UI.

This is considered done when we can have the global parameters appear on the website, download it with any changes and run the protocol successfully on the robot.

**Comment by IanLondon** [comment]
Done as separate `protocols/{protocol_slug}/fields.json` files in `apiv2` branch.

TODO: document the fields.json format
