### ISSUE TITLE
PL: Determine amount of work needed to host api v1 and api v2 protocols

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/opentrons#3897]
## overview

This is a placeholder ticket in the instance that we decide it is a requirement for the library to still have api v1 protocols hosted there. At this point in time, we are unsure how much dev and design work it would take/what those tickets would look like.

## expected behavior

Api v1 and v2 protocols should be hosted/differentiated. This ticket is closed when we decide either 1. not to host api v1 protocols anymore or 2. come up with a plan to host both api v1 and api v2 protocols.

**Comment by btmorr** [comment]
Decided not to host both
