### ISSUE TITLE
PL: Remove 3 branch development environment

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/opentrons#3898]
## overview

Having 3 separate branches to maintain on the protocol library is quite a pain for developers. This ticket serves as a placeholder until we decide on an option found below:

**OPTION 1**: one branch, keep subdomain
- master and develop both contain ALL protocols. Whether they show up on the main site or the protocol-delivery subdomain depends on whether they're in protocols/public or protocols/protocol-delivery in the Protocol repo.
- updates to master are deployed to main and protocol-delivery subdomain, in 2 different sets of artifacts
- updates to develop similarly go to develop.protocols.opentrons.com and develop-protocol-delivery.protocols.opentrons.com, each URL points to a different set of artifacts.

**OPTION 2**: one branch, use special route instead of subdomain
make a route instead of a subdomain. Then protocols.opentrons.com/protocol-delivery is the "secret" delivery site, instead of the equally-not-actually-secret protocol-delivery subdomain. There is then only a single production artifact for each prod deploy, and only a single staging/develop artifact for each staging deploy. Vue is responsible for filtering the public vs private protocols at runtime.

**OPTION 3**: one branch, no subdomain, just don't make them findable
no protocol-delivery subdomain, no special route. The "private" protocols are tagged with .private dotfiles, and the parsers represent that tag in the JSON data. They simply are not listed in the categories or the search. Their URL is not obfuscated, it's just a normal slug.

**Comment by btmorr** [comment]
Going with Op 3
