### ISSUE TITLE
PL: Provide deck data from the executor 

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/opentrons#3899]
## overview
We need some way to provide data to the protocol library about the deck setup. This is currently done by having the protocol library first simulate the protocol to check for syntax errors and then parse the file for labware/module/pipette info.

## expected behavior
Instead, the executor method from the API should also provide the deck information during simulation. @mcous could the app also eventually use this information instead of relying on the RPC?

**Comment by IanLondon** [comment]
Labware & pipettes parsed out in `apiv2` branch. However, in PL the pipettes never show up. Modules TBD, not done yet, not sure how to parse out.

**Comment by IanLondon** [comment]
Closed in `apiv2` branch. Making pipettes show up is not an existing PL feature and needs design, will be separate ticket if we do it.
