### ISSUE TITLE
PL: Remove the elasticsearch lambda on the protocol library

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/opentrons#3905]
## overview
The elasticsearch lambda significantly slows down page loading by nature of how it accesses a given protocol's information. We propose to remove the elasticsearch lambda and separate out the table of contents as well as individual json blobs for each protocol.

## expected behavior

1. Create a manifest file which acts as a table of contents and link to location of the JSON blob for an _individual_ protocol.
2. Split out all protocols into their own individual blob. (We will no longer need the giant JSON blob)
3. Direct the manifest to ping AWS for the content of an individual protocol.

**Comment by IanLondon** [comment]
Hopefully we'll fully rebuild it... closing for now
