### ISSUE TITLE
Current needs to vary between rest/action for plunger motors

### ISSUE THREAD

**Issue by btmorr** [Opentrons/opentrons#392]
## overview

This issue is for:

- Bug/feature
- API

## expected or desired behavior

The plunger motors should be set to low current (~100 mA) when not in use. Before issuing move commands to the plunger, current should be increased to high current (~500 mA) for actions. Return to low current after actions. Issue a dwell command after issuing current commands.

**Comment by mcous** [comment]
Fixed in #396
