### ISSUE TITLE
SSH root now needs password

### ISSUE THREAD

**Issue by mcrone** [Opentrons/opentrons#3925]
# Overview

Bug: New update (3.11.1) adds password to root, but the password is not documented anywhere.

## Current behaviour

Cannot login using SSH, password needed.

## Expected behaviour

Yesterday before update no password was needed

**Comment by mcous** [comment]
Hi @mcrone, thanks for the report! As you noticed, 3.11 does add an additional layer of security to the SSH, but it is not password based (we will be disabling the password prompt in a future release). Rather, it is key based.

The documentation you are looking for is located here: https://support.opentrons.com/en/articles/3203681-enabling-ssh-access-to-your-ot2
