### ISSUE TITLE
User Able to Save Invalid Tip Length Data

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#3945]
## overview
It's currently possible to save invalid tip length data -- for example, a failed tip probe may result in a 'tip length' far shorter than any physical tip.

Bad tip length data may result in failed tip probes, crashes into labware, or crashes during deck calibration.

Note: this is not technically a 'bug', but agreeing to file this here after discussion.

## current behavior
User able to save tip length data outside reasonable/possible tip lengths.

## steps to reproduce
TBD

## expected behavior
TBD

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535413064) by [Unito](https://www.unito.io/learn-more)

**Comment by btmorr** [comment]
Closing this as stale, since all relevant details have been "TBD" for 3 months

**Comment by bndo** [comment]
Putting this into the icebox for future review. Currently, some, maybe all, calibration processes do not have any bounds checking mechanisms.
