### ISSUE TITLE
LC: Add well diagrams to radio groups

### ISSUE THREAD

**Issue by Kadee80** [Opentrons/opentrons#3957]
## overview

As a LC user, I would like some visual guidance when selecting well shape and bottom shape.

## Acceptance Criteria
- ~Refactor `RadioField` component to accept `RadioGroup.options` type~
- [x] Change well bottom shape dropdown to radio group
- [x] Radio groups with SVG icons in label render as expected with mobile first styling

## Design
https://app.zeplin.io/project/5c881cf3fc5f4d194cde50ee/screen/5d60258eff86179b0c092937
<img width="579" alt="Screen Shot 2019-08-27 at 3 45 26 PM" src="https://user-images.githubusercontent.com/3430313/63803118-2591ff80-c8e2-11e9-88da-f696da2f973c.png">

**Comment by IanLondon** [comment]
Ah missed something or had a funky merge, this needs to be fixed:

![image](https://user-images.githubusercontent.com/11590381/64452887-54b02a00-d0b5-11e9-9b83-dbcfe3929c0d.png)

**Comment by Kadee80** [comment]
closed  via #4013
