### ISSUE TITLE
LC: upon file upload, show form & scroll

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#3971]
## overview

As a user, I would like to be able to upload existing labware files and successfully open them in LC.

## acceptance criteria

If user uploads a labware (doesn't matter if it's via clicking the upload button, or via drag-and-drop the file), upon successful upload:
- [ ]  If well plate or reservoir, confirm successful upload by scrolling down and revealing form.
- [ ] If tube rack or aluminum block, replace drag/drop upload box by showing drop down so user may select desired child category. "Upload labware file" button only becomes active once user selects child. Upon clicking upload button, confirm successful upload by scrolling down and revealing form.
- [ ] Load name and display name should be RESET to default/automatic, do not use the loaded definition's names

Upon unsuccessful upload (bad file, unsupported labware):
- [ ] get existing error modal behaviour, no scrolling. no content to hide/show.

## Design
![image](https://user-images.githubusercontent.com/2686086/64204179-7c28ac00-ce95-11e9-84f9-79819dd8d833.png)

**Comment by pantslakz** [comment]
@IanLondon one outstanding concern - if user is able to swap child category during upload - then maybe we should consider resetting the api load name/display name to default?

**Comment by pantslakz** [comment]
Hey Ian - some feedback on http://sandbox.labware.opentrons.com/lc_post-upload-behavior-3971/create:

- when user uploads labware which is aluminum block/tuberack, it should not load child in both "create new" and "upload labware" section.
- instead the 'create new' section should become inactive and not mimic action in "upload" section
- only the "upload" section should show parent
- If user wants to access 'create new' - I assume they would reload the page

Another behaviour thing which maybe best tracking in another ticket:
- if user exports at 96 well tube rack, and user re-uploads it in the LC and picks "24" tube as child -the suggested display/api name of labware does not change and remains 96.  This feels like further reasoning to re-set suggested name each time a definition is re-uploaded.
