### ISSUE TITLE
CLI calibration: spurious movement before picking up a tip with the left pipette

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#3980]
1. SSH in and run `python -m opentrons.deck_calibration.dc_main --pickupTip True`.
0. Jog the right pipette directly over a tip, and press `t` to pick it up. This should succeed.
0. Press `s` to switch to the left pipette. It will lower.
0. Jog the left pipette directly over a tip, and press `t` to pick it up.
0. Observe that the left pipette will slide to the right before attempting to pick up what's below it. I got lucky and it happened to stop over another tip.

I expected picking up with the left pipette to do the same thing as picking up with the right pipette: lowering straight down to pick up the tip that it's directly above.

Video in the Slack thread.

**Comment by btmorr** [comment]
Note: this is a new feature that hasn't been added to factory processes yet. We're planning to investigate and fix it, but not during the current sprint.
