### ISSUE TITLE
Tip probing does not correctly find the south and north switches

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#3983]
Tip probing currently finds the north, east, south, and west switches by assuming a distance from the as-previously-calibrated box center.

In theory, after touching off west and east, the robot should be able to calculate the true x-coordinate of the south and north switches, rather than assuming.

Toma and I believe, based on the following lines, that that's what's intended to happen.

https://github.com/Opentrons/opentrons/blob/30cdf173efdea0685a226a53b483b6d65e2e8267/api/src/opentrons/util/calibration_functions.py#L62-L63

But that calculation isn't actually used.

https://github.com/Opentrons/opentrons/blob/30cdf173efdea0685a226a53b483b6d65e2e8267/api/src/opentrons/util/calibration_functions.py#L38-L40

**Comment by mcous** [comment]
🤦‍♂
