### ISSUE TITLE
Uploading .json protocol results in robot server crashing

### ISSUE THREAD

**Issue by opatel0** [Opentrons/opentrons#3998]
## overview
After uploading a .json protocol, robot server crashes

## current behavior
After uploading protocol, the robot throws the following error message in a pop-up window:
"Could not connect to robot
If this problem persists, we recommend restarting your robot and waiting 30 seconds before trying again. If you're still unable to connect, please contact our support team"
If I try uploading again after the initial failed upload, I get an "ACK Timeout" error

## steps to reproduce
Ping me directly for protocol file that reproduces issue

## expected behavior
protocol should successfully upload and load calibration screen

**Comment by mcous** [comment]
The API has an (arbitrary) size limit on WebSocket message of ~4.1 MiB:

```
2019-09-04 13:33:36,194 opentrons.server.rpc ERROR [Line 259] WebSocket connection closed unexpectedly: WSMessage(type=<WSMsgType.ERROR: 258>, data=WebSocketError('Decompressed message size exceeds limit 4202639',), extra=None)
```

We should take two actions:

- Remove this size limit on the RPC WebSocket for as long as we are planning on using it to shove entire protocols to the robot with
- Switch PD to output compact JSON by default to buy us some clearance (anecdotally, getting ~40% size reduction on large protocols)
