### ISSUE TITLE
Release system 3.12.0

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#4012]
## overview

This ticket is to track work that we want to include in the 3.12.0 release

## chore work

- [x] Release notes branch and PR

## user-facing tickets / PRs

- [x] https://github.com/Opentrons/opentrons/pull/3875 (API <> App clock de-sync workaround)
- [x] https://github.com/Opentrons/opentrons/pull/3891 (Custom labware on deck in App)
- [x] https://github.com/Opentrons/opentrons/pull/3940 (Better tip type messaging in tip probe)
- [x] https://github.com/Opentrons/opentrons/pull/3942 (Pipette change copy fix)
- [x] https://github.com/Opentrons/opentrons/pull/3947 (API response fix for SSH key upload)
- [x] https://github.com/Opentrons/opentrons/pull/3959 (various tip probe fixes)
- [x] https://github.com/Opentrons/opentrons/pull/4001 (tip probe centering fix)
- [x] https://github.com/Opentrons/opentrons/pull/4006 (RPC fixes for running large protocols)
- [x] https://github.com/Opentrons/opentrons/pull/4011 (Electron upgrade)

## labware PRs

- [x] https://github.com/Opentrons/opentrons/pull/3827
- [x] https://github.com/Opentrons/opentrons/pull/3862
- [x] https://github.com/Opentrons/opentrons/pull/3916
- [x] https://github.com/Opentrons/opentrons/pull/3929

## non-user-facing stuff

Please fill this out! Thermocycler + pipette GEN2 stuff, I assume

- [x] https://github.com/Opentrons/opentrons/pull/3933 (allow all gen2's by name or type)
- [x] https://github.com/Opentrons/opentrons/pull/3912 (tc prompts in calibration flow)
- [x] https://github.com/Opentrons/opentrons/pull/3953 (ignore tc lid in height)
- [x] https://github.com/Opentrons/opentrons/pull/3958 (extend tc timeout)
- [x] https://github.com/Opentrons/opentrons/pull/4003 (tc context naming and behavior)
- [x] https://github.com/Opentrons/opentrons/pull/4018 (tc feature flag removal)

**Comment by sfoster1** [comment]
Extra user-facing changes:

- [x] #3979 (corrected fix for swallowing smoothie errors during tip probe, etc)
- [?] it would be kind of nice to get apiv2 entrypoints in but if it doesn't that's not the end of the world

Extra non-user-facing changes:

- [x] #3962 (stop using a lockfile for hc)
