### ISSUE TITLE
When app update fails, it fails silently

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#4035]
## overview

The app uses [electron-updater](https://www.electron.build/auto-update) to detect available updates and update itself to the latest version. Various steps in the update process can fail, and if they do fail, most of the time the user isn't alerted.

## current behavior

Failures observed:

- macOS: failure to find downloaded update file
- Linux: failure to remove previous copy of the application

These failures were not reported to the user and were confusing

## expected behavior

Any self-update failure should notify the user and prompt them to visit the app's download page to update manually.

**Comment by SyntaxColoring** [comment]
From talking to Support:

We don't (and maybe can't) know if this is causing real problems, but if it is, it's a big-ish deal.
