### ISSUE TITLE
Use max Z for Gen2 pipette movement between labware

### ISSUE THREAD

**Issue by btmorr** [Opentrons/opentrons#4043]
## overview

Tall labware (such at a Thermocycler or tubes on an aluminum block on a temperature module), combined with the length Gen2 pipettes makes it impossible currently for Gen2 pipettes to reach all labware while respecting our designated clear distance. For now, instead of moving to a safe height above labware, Gen2 pipettes will retract to max Z when moving to a different labware.

- [ ] when moving from one well to another in the same labware, Gen2 pipettes should retract to a safe height using the same logic as Gen1
- [ ] when moving from one labware to another, Gen2 pipettes should retract to max Z before moving in X or Y

**Comment by btmorr** [comment]
This ticket may not be needed, as it may be addressed by fixing other bugs in Z movement. @b-cooper please update as needed.

**Comment by b-cooper** [comment]
This ticket is not needed for now as other bugs in z movement have been patched, more responsible z movement and buffering will be addressed later on as movement simulation becomes more sophisticated.
