### ISSUE TITLE
API v2 Backcompat: Don't import robot as a global anymore!

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/opentrons#4047]
## overview
Now that API v1 can be fully controlled by an API v2 server, we should remove all instances of building robot globally.

## current behavior

- Robot is fully functional on import, which slows down import time and is generally kinda gross.

## expected behavior

Backcompat makes it easy to set up a robot singleton to pass around via an entrypoint

**Comment by sfoster1** [comment]
This work has already been done as part of several other PRs
