### ISSUE TITLE
Thermocycler: make main thread non-blocking

### ISSUE THREAD

**Issue by b-cooper** [Opentrons/opentrons#4072]
## overview

In order to enable useful status updates to the api/app while lid is opening or closing, let's make the main thread non-blocking. This way, when the TC receives an "open lid" gcode, it responds immediately with a successful "parsed command" message and doesn't block ensuing communication until the lid actually opens all the way.

This also enables the spinner in the Run App's calibration "Open Lid" modal to function properly. Down the road, when exposing the lid motor status to user elsewhere in the app, this will be helpful in ensuring accurate and timely information.

**Comment by btmorr** [comment]
Not going to be possible because we're using micro-stepping and need to update the motor every 60-70 us, which we can't support with higher level asynchrony right now. A better solution might be available later, but not doing this right now (more likely handle this in API server and/or App)
