### ISSUE TITLE
Do not use CIDR (slash) notation for subnet masks when the app shows an IP address

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#4075]
# Overview

The app currently shows IP addresses like this:

* **Wireless IP:** 192.168.1.250/24
* **Wired IP:** 169.254.2.6/16

Instead, it should show them like this:

* **Wireless IP:** 192.168.1.250
* **Wireless subnet:** 255.255.255.0
* **Wired IP:** 169.254.2.6
* **Wired subnet:** 255.255.0.0

Or something similar. The subnet mask is spelled out on its own line, rather than being represented by a number after a slash.

# Why

Users occasionally need to copy their robot's IP for things like SSH and Jupyter. When they do, they have to be careful about copying *just the part that comes before the slash.*

Separating out the subnet mask like this would eliminate that tripping hazard.

**Comment by mcous** [comment]
Going to do this app-side and reconsider the networking endpoints for HAPIv2
