### ISSUE TITLE
container.rows should be rows and container.cols should be columns

### ISSUE THREAD

**Issue by astaff** [Opentrons/opentrons#409]
# Current

```python
from opentrons import containers
plate = containers.load('96-flat', 'A1')
print(plate.rows(0))
```

outputs `<WellSeries: <Well A1><Well B1><Well C1><Well D1><Well E1><Well F1><Well G1><Well H1>>`

# Expected

`A1..A12`

**Comment by LauraOpentrons** [comment]
If we invert them i,e plate.rows() is now A1-12 instead of A1-H1 that will create huge backwards compatibility issues for OT1 users and all past protocols written. Maybe we should have a meeting to discuss?

**Comment by astaff** [comment]
Happy to discuss. We should keep in mind that for these kinds of changes we can automatically convert protocols. Also we should think about development experience for new protocols when writing a protocol we will be using rows instead of cols and vice versa.

**Comment by astaff** [comment]
@IanLondon reassigning this to you since you are consolidating OT1->OT2 changes
