### ISSUE TITLE
apiv2: docs: move apiv1-specific jupyter instructions to v1/ subtree

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#4092]
## overview

The last section of [writing.rst](https://github.com/Opentrons/opentrons/blob/edge/api/docs/source/writing.rst) contains instructions about using jupyter that are specific to apiv1. This should be in a doc in the v1 subtree, rather than at the top level.

**Comment by btmorr** [comment]
No longer relevant (taken care of by another docs deploy PR)
