### ISSUE TITLE
Missing pipette error from Smoothie should not log an exception

### ISSUE THREAD

**Issue by kentcr** [Opentrons/opentrons#4096]
## overview

robot.connect() errors when only one/right pipette is attached

## current behavior

When only the right pipette is attached, running robot.connect() via Jupyter or CLI produces the error `alarm/error: command=M371L, resp=error:no L instrument found`.

Running scripts via the app still works in this configuration. Only tried with the pipette on the right side, but would not be surprised if the same is true on the left.

## steps to reproduce

* Mount a P50 single-channel on the right side.
* Start a Python session via Jupyter or CLI
* Run the following code
```python
from opentrons import robot
robot.connect()
```
Example output
```console
/ # python
Python 3.7.1 (default, Sep 13 2019, 15:47:08)
[GCC 7.3.1 20180425 [linaro-7.3-2018.05 revision d29120a424ecfbc167ef90065c0eeb on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from opentrons import robot
Loading json containers...
Json container file load complete, listing database
Found 0 containers to add. Starting migration...
Database migration complete!
>>> robot.connect()
alarm/error: command=M371L, resp=error:no L instrument found
>>>
```

## expected behavior

No error

**Comment by ethanfjones** [comment]
This issue is not specific to the mount. The error will appear if you try to use robot.connect() with one pipette in Jupyter notebooks.
