### ISSUE TITLE
Protocol Designer: Changing flow rate for single step changes flow rate for whole protocol

### ISSUE THREAD

**Issue by opatel0** [Opentrons/opentrons#4101]
## overview
Issue with changing flow rate in PD protocols

## current behavior
When defining a transfer step, if the flow rate is changed, the flow rate is changed for the entire protocol instead of just the step in which it is being manually adjusted

## steps to reproduce
Create a protocol in PD with two transfer steps, one that uses the default flow rate and one with a manually set flow rate with anything but the default
Observe in the run that the flow rate is changed for both steps

## expected behavior
When changing the flow rate for a transfer step, the flow rate should only be changed from the default for that particular step

**Comment by IanLondon** [comment]
This may be a duplicate of #2772 -- I tested in PD 3.0.4 and it's saving correct flow rates in the JSON. Tested in v3.12.0 (APIv1) and the physical movements seemed like they were picking up on the flow rates correctly, which was consistent with what I saw in the flow rate logs I temporarily added to APIv1 json protocol v3 executor during that run.
