### ISSUE TITLE
Front button fails to light up blue

### ISSUE THREAD

**Issue by opatel0** [Opentrons/opentrons#4102]
## overview
Previously, the front button would light up blue during the robot software's boot process and remain lit up blue as long as the robot was powered on. Since 3.11.0, the button will randomly fail to light up blue and remain off, though the robot can resume all normal functionality otherwise.

## current behavior
Front button LED is off sometimes after the robot has been powered on and connected to the app

## steps to reproduce
N/A - needs repro, seems random

## expected behavior
Front button lights up blue within 1 minute of powering on the robot as long as software is properly booting

**Comment by sfoster1** [comment]
This should be fixed in 3.12 (by https://github.com/Opentrons/buildroot/commit/63988564ca2d9c3ebd09eac541bcda2328ce2e6a)
