### ISSUE TITLE
PL: Banner for v1 section of library

### ISSUE THREAD

**Issue by btmorr** [Opentrons/opentrons#4110]
New banner on v1 library
https://zpl.io/bzLz0lz

**Comment by pantslakz** [comment]
![ProtocolLib](https://user-images.githubusercontent.com/2686086/65924465-1de7de00-e3ed-11e9-9b16-f6344353b7a3.jpg)

**Comment by IanLondon** [comment]
Closed in Opentrons/protocol-library#118
