### ISSUE TITLE
Protocol won't upload if robot and app versions are out of sync

### ISSUE THREAD

**Issue by ahiuchingau** [Opentrons/opentrons#4202]
## overview
This is an issue we began to see in 3.12.0. If the app is updated to 3.13 and the robot is still on 3.12, the protocol cannot be uploaded correctly and the app shows the following message:

![Screen Shot 2019-10-10 at 11 43 39 AM](https://user-images.githubusercontent.com/20424172/66584487-3fff0000-eb53-11e9-9731-d3f9bfa92071.png)

## expected behavior
There should be certain limitations if the app and the robot are out of sync, but should not affect user from uploading and running protocols on the robot.

**Comment by SyntaxColoring** [comment]
Reopening this because it's been reported again on App v3.14.0 and server v3.10.1.

**Comment by IanLondon** [comment]
https://github.com/Opentrons/opentrons/pull/4205/files#diff-4126c2cc2b8a3ba5e347a5700ed5db05R162 this might have to also handle a case where `error.name` is 'TypeError'???

**Comment by SyntaxColoring** [comment]
Reported also on App v3.13.2 and server v.3.10.1.

**Comment by mcous** [comment]
Upon further investigation, #4203 did not actually fix the issue in production. This was the result of the JS minifier used in production (but not dev) re-writing the name of our RPC client's internal `RemoteError` to a mangled shortened name

https://github.com/Opentrons/opentrons/blob/fb5d160e9e33b55e529cf5d51f6cd643710e50dd/app/src/rpc/remote-error.js#L1-L10

Fix incoming
