### ISSUE TITLE
PD: Module visualization on the deck

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#4208]
## Acceptance criteria
- [ ] Modules are represented by grey blocks
- [ ] Each module has a tag pointing toward either the left or right perimeter of the robot (depends on which edge the module is closest too)
- [ ] Tags have the title of the module and 1-2 lines of module status
- [ ] Position/size of thermocycler is slightly exaggerated

## Designs
https://zpl.io/bJ1PNdJ

**Comment by IanLondon** [comment]
NOTE: will not include the status of the module (eg "Engaged" / "Lid: heating" etc), which requires module steps and is an extra-large in itself. Just put "Placeholder status" text there.
