### ISSUE TITLE
APIv1: Add new argument to magdeck.engage() for setting the position of the magnets relative to the bottom of the labware

### ISSUE THREAD

**Issue by mikec116** [Opentrons/opentrons#4212]
Add a new option to set the magnetic module's engage height based on the bottom of the labware. 

The 0 value for the new argument is such that the tops of the magnets are level with the ledge that the labware sits on which is 5mm from the limit switch engage point and can vary +/- 1mm between magdeck units (this data should be added to the API v1 documentation.

**Comment by ahiuchingau** [comment]
Closing this ticket because we are no longer adding new feature to APIv1
