### ISSUE TITLE
LL: Make it possible to show more than one version of a Labware

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#4217]
As a Labware Library user, I should be able to view more than 1 version of a labware. 

## Acceptance criteria
- [ ] If more than one version of a labware exists, it should be possible to tell each version apart in the Labware Library 

## Design
- TBD

## Open Questions
- Should we show each labware version as a separate card or add a version dropdown to the existing card?

**Comment by Kadee80** [comment]
Stale
