### ISSUE TITLE
Protocol actions that need tips will be executed even if no tip has been picked up

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#4219]
## overview

It's easy to accidentally contaminate a pipette by aspirating without first picking up a tip. When this happens, we need to ship customers replacement pipettes.

## current behavior

Protocols that include atomic liquid handling commands, like `aspirate()`, `mix()`, etc. are permitted to run even if they forget to `pick_up_tip()`. The pipette nozzle will move to the well and happily aspirate liquid into itself, contaminating it.

Warning messages are printed during local simulation with `opentrons_simulate`. However, no such messages appear before running a protocol through the app. So, at least some part of the software knows that the protocol is problematic, but that knowledge isn't making its way to the user.

## expected behavior

The user should at least be warned before running such a protocol.

* In the run log, warning messages could be printed as they are with `opentrons_simulate`.
* A warning dialog could confirm the user's intentions before allowing the protocol to run.
* etc.

**Comment by SyntaxColoring** [comment]
See also #3535 and #3536.

**Comment by mcous** [comment]
Since the app has very little to do with protocol execution (except for uploading the contents of the file and issuing "start", "pause", and "cancel" controls), and based on our real life conversation, I've tweaked the name and categorization of this issue to reflect that these actions should be blocked at the robot side

**Comment by btmorr** [comment]
Fix merged to 3.15.0 release branch. Will be merged back into `edge` after release
