### ISSUE TITLE
MustHomeError being raised to client level

### ISSUE THREAD

**Issue by btmorr** [Opentrons/opentrons#4230]
## overview
During labware calibration (and possibly at other times), a `MustHomeError` is being raised by the smoothie driver, and is not handled such that it interrupts RPC calls and is surfaced to users. This is both confusing, and also can make it impossible for the user to proceed through certain flows.

## steps to reproduce
Not entirely clear how to reproduce on other robots, but one of the robots in the lab is currently experiencing this issues as of today (15 Oct 2019).

## expected behavior
When smoothie raises a `MustHomeError` (or other internal operations signals), these should always be handled below the client level, and users should be able to recover and proceed through flows.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535421369) by [Unito](https://www.unito.io/learn-more)

**Comment by btmorr** [comment]
Run logs:
[serial-musthomeerror.log](https://github.com/Opentrons/opentrons/files/3730810/serial-musthomeerror.log)
[api-musthomeerror.log](https://github.com/Opentrons/opentrons/files/3730811/api-musthomeerror.log)

**Comment by btmorr** [comment]
Protocols:


[Archive.zip](https://github.com/Opentrons/opentrons/files/3730815/Archive.zip)

**Comment by Fabbe** [comment]
When simulating my protocol I get no errors on my laptop, on the OT2 I get some out of bounds errors (which I've been told to ignore). 
When executing the protocol I get a MustHomeError when I call instrument.pick_up_tip().
Any ideas?

**Comment by SyntaxColoring** [comment]
Added the `investigate` label. I'm not sure if this is still happening on recent versions.
