### ISSUE TITLE
opentrons_24_tuberack_nest_* definitions are wrong

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#4238]
# Overview

The `opentrons_24_tuberack_nest_1.5ml_screwcap` labware appears to have a problem with both its x-spacing and y-spacing.

The tip will correctly be positioned in A1. However, in D6, the position is noticeably off. Very sloppily measuring with calipers, I'd say the tip is 2 mm too close to the front of the robot and 3 mm too far to the left.

The same tube rack with different tubes, `opentrons_24_tuberack_eppendorf_2ml_safelock_snapcap`, does *not* have this issue.

# Reproducing

This is an APIv2 demo script, but the issue applies equally to APIv1. I ran this without any labware calibration.

```python
from opentrons import protocol_api

metadata = {
    'protocolName': 'Tube rack offset test',
    'author': 'Max Marrone',
}

def run(protocol: protocol_api.ProtocolContext):
    tip_rack = protocol.load_labware('opentrons_96_tiprack_300ul', '1')
    tube_rack_1 = protocol.load_labware('opentrons_24_tuberack_nest_1.5ml_screwcap', '7') # Shows problem.
    tube_rack_2 = protocol.load_labware('opentrons_24_tuberack_eppendorf_2ml_safelock_snapcap', '8') # Does not show problem.

    pipette = protocol.load_instrument('p300_single', 'left', tip_racks=[tip_rack])

    pipette.pick_up_tip()

    for tube_rack in [tube_rack_1, tube_rack_2]:
        pipette.move_to(tube_rack.well("A1").top())
        context.comment("Should be centered in A1.")
        context.pause()
        pipette.move_to(tube_rack.well("D6").top())
        context.comment("Should be centered in D6.")
        context.pause()
```

# Other notes

* I haven't tested to see if the height of the labware is correct.
* I haven't tested any of the other `opentrons_24_tuberack_*` labware.

**Comment by mcous** [comment]
I just did some additional investigation. It looks like all 24 tuberack NEST definitions added by #3916 were generated with their X and Y spacing swapped. This is easily noticeable from looking at the numbers on the labware library; I don't know how we missed this

Moving forward:

- I'm going to add an automatic test to ensure X + Y consistency among our modular tuberack definitions
- We will ensure that 100% of labware definitions merged have first _and last_ wells tested
    - This has been the procedure in a lot of cases but clearly we didn't codify it hard enough
