### ISSUE TITLE
API: Return tip Height is too low for calibration

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/opentrons#4241]
## overview

Over the course of internal testing, there has been a return tip bug popping up every now and again during labware calibration testing.

## current behavior

The robot will sometimes return the tips too low in a tiprack before proceeding to a run. However, if a protocol is run immediately after this it will be able to pick up tips correctly. (Returning tips during a run when this bug occurs has not been tested). *Note* behavior has been seen with any combination of pipette type and tiprack.

## Logs
See logs from a robot below.
[serial.log](https://github.com/Opentrons/opentrons/files/3736372/serial.3.log)
[api.log](https://github.com/Opentrons/opentrons/files/3736373/api.3.log)

## expected behavior
The robot should not return tips low in the tiprack.

**Comment by sfoster1** [comment]
Fixed by https://github.com/Opentrons/opentrons/pull/4828
