### ISSUE TITLE
The offset applied to a tip rack is the sum of all of its instances' calibration offsets

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#4288]
# Overview

When you use multiple instances of the same tip rack in a protocol, tip rack calibration visits each one.

When the protocol is run, the offset applied to each of those tip racks is the *sum* of all of the offsets found during calibration.

So, for example, let's say you have 5 instances of the same tip rack, and you calibrate the same 1 mm offset to each one.  When the protocol runs, there will be a *5 mm offset* in that direction (for each tip rack).

# Expected behavior

Ideally:

* Each instance of a tip rack has its own calibration offset.

But, working within the current model where instances of the same labware share one calibration:

* One calibration offset is chosen to apply to each of the instances.
* Or, all of the calibration offsets are averaged to find the one to apply to each of the instances.

# Reproducing

1. Ensure your OT-2 is set to APIv1.
2. Attach a P300M to the left mount and P300S to the right mount.
3. Do a factory reset of tip length and labware calibration.
4. Upload move_to_crosses.py (supplied below). Do pipette calibration and tip rack calibration as normal.
5. Start the run. Both pipettes will move to the deck calibration crosses in slots 10, 11, and 9, indicating a good deck calibration and pipette calibration.
6. Upload move_to_crosses.py a second time. You can skip pipette calibration this time. **For tip rack calibration, instead of centering the tip over A1, center it over some other well.** I used A3 for the P300M and D4 for the P300S.
7. Run the protocol. **Observe that the pipettes will try to pick up tips from different wells, entirely – wells much farther down and to the right.** However, the pipettes will still find the deck calibration crosses correctly. Cancel the protocol or let it run all the way through.
8. Upload move_to_crosses.py a third time. Do pipette calibration. During tip rack calibration, observe that the pipettes start off at the incorrect position that they went to during the run. **Calibrate normally this time, to well A1.**
9. Start the run. **Calibrating to well A1 will not have resolved the mispositioning issues.** This time, the pipettes will go too far to the *left.* For me, they crashed into the left boundary.

# move_to_crosses.py

```python
from opentrons import labware, instruments, robot

left = instruments.P300_Multi(mount="left", tip_racks=[labware.load("opentrons_96_tiprack_300ul", 1)])
right = instruments.P300_Single(mount="right", tip_racks=[labware.load("opentrons_96_tiprack_300ul", 2)])

calibration_cross_coordinates = [
	[12.13, 348.5, 0.0], # Slot 10.
	[248.37, 348.5, 0.0], # Slot 11.
	[380.87, 258.0, 0.0], # Slot 9.
]

left.pick_up_tip()
right.pick_up_tip()

for coordinates in calibration_cross_coordinates:
	for pipette in [left, right]:
		pipette.move_to((robot.deck, coordinates))
		robot.pause()
		pipette.retract()

left.return_tip()
right.return_tip()
```

**Comment by btmorr** [comment]
Merged into the 3.14.0 release branch
