### ISSUE TITLE
PD: Temp Deck - Set temp

### ISSUE THREAD

**Issue by mikec116** [Opentrons/opentrons#4305]
# User Story
As a PD user, I should be able to create a protocol step that tells the temperature module to go to a temperature and then hold that temperature

# UI Design
New step list: https://zpl.io/aR9ljQN
Set temp: https://zpl.io/adYlqE7
Hint on temp step creation: https://zpl.io/aMjyZ5d

# Acceptance Criteria
- [ ] The temp module should only accepts round numbers. It should not be possible to enter temp values with any decimal places. 
- [ ] The range of accepted temperatures should be from 0 to 95 degrees Celsius

# Implementation details
Field validation rules: https://docs.google.com/spreadsheets/d/1VSF7sWyoKtad_pzNirqaoymBTax8rqWMNId2xl5pIWU/edit#gid=0

**Comment by IanLondon** [comment]
Let's have this ticket represent the form. At this point we're just missing preventing decimal input.

Hooking up the form to `step-generation` is for another ticket, #4693
