### ISSUE TITLE
Final touch: make "recommended labware" link go to final support article

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#4324]
## current behavior

This link in the labware selection modal ~doesn't go anywhere!~ goes to a temporary Google doc (#4337)

![image](https://user-images.githubusercontent.com/11590381/67814919-d2703080-fa7b-11e9-8111-4eb54c5cd45c.png)

Once we have a final support doc (nearer to release time), we need to update that link.

**Comment by mikec116** [comment]
Here's the support page: 
https://support.opentrons.com/en/articles/3540964-what-labware-can-i-use-with-my-modules
