### ISSUE TITLE
PD: Add help article to the recommended labware filter

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#4337]
As a user I would like to get more info on the whole recommended vs compatible vs incompatible labware situation. 

## Context
![image](https://user-images.githubusercontent.com/35570080/67896559-fb9fc800-fb32-11e9-95f3-4a939f47e832.png)

## Acceptance Criteria
- [ ] Add a URL to the blue "here" (NOTE: this will be to the temporary doc, not the final article. Final article will be #4324)

**Comment by btmorr** [comment]
@mikec116 please let us know when the article is ready

**Comment by howisthisnamenottakenyet** [comment]
@mikec116 @IanLondon https://docs.google.com/document/d/1CrK-3uAQYDylb9h7EfJBv2Ri4FIF-XW92Uf0Zd4dWr4/edit?usp=sharing
