### ISSUE TITLE
[Labware Defs] Add new Mag Deck Engage height key and values in labware definitions

### ISSUE THREAD

**Issue by mikec116** [Opentrons/opentrons#4356]
## Context: 
1. All standard labware that is compatible with the mag deck contains an engage height value in its labware definition
2. We'd like to switch the meaning of "engage height = 0" from the magnet being located at the limit switch at the bottom of the mag deck to the plane where the labware meets the mag deck surface

## Proposed options (choose based on LOE for development): 
- ~Change all compatible labware defs to contain updated engage height values...~
- OR add a new engage height key to the labware defs that can be used going forward

**Comment by sfoster1** [comment]
We should go with option 2.

**Comment by IanLondon** [comment]
End of 2019 dev team met and decided that this would be done by adding the offset in Python + PD, keeping the definitions themselves unchanged.
