### ISSUE TITLE
Bug: Error message in GUI unreasonably vague

### ISSUE THREAD

**Issue by rgatkinson** [Opentrons/opentrons#4367]
## overview

I have a Python protocol that contains the lines:

```
temp_slot = 11
temp_module = modules.load('tempdeck', slot=temp_slot)
```

Depending on other settings in the protocol, this module may or may not be used; presently, it is not. Which means that the analysis carried out by the app doesn't require it (good): it's not listed in the manifest of required parts, doesn't participate in calibration, etc.

However, when I go to run the protocol, I get the following message:

![image](https://user-images.githubusercontent.com/111943/68171472-c0cdd380-ff28-11e9-8db3-11a40545677d.png)

This is an unreasonably vague message: it gives me absolutely no indication whatsoever regarding what the problem is; this should be fixed.

After an hour or two of hair pulling and digging around, I finally find, in c:/users/bob/appdata/opentrons/roaming/logs/combined.log, the following line:

```
{"level":"debug","message":"Trackable event","timestamp":"2019-11-05T01:15:38.502Z","label":"renderer","meta":{"event":{"name":"runFinish","properties":{"error":"AbsentModuleError [line 111]: no module of name tempdeck is currently connected","protocolAppName":"","protocolAppVersion":"","protocolAuthor":"0a116ad46b9d246ce10335f3bfd988e1456a728fb161e5a7385f9ae3a786d4c1","protocolName":"Pairwise Interaction: Dilute & Master & Plate","protocolSource":"","protocolText":"fb032ce97084c057fb6aaab02811f7fc6299745281d740147caf77ea13c0652f","protocolType":"python","robotApiServerVersion":"3.14.0","robotFF_calibrateToBottom":false,"robotFF_deckCalibrationDots":false,"robotFF_disableHomeOnBoot":false,"robotFF_disableLogAggregation":false,"robotFF_shortFixedTrash":false,"robotFF_useOldAspirationFunctions":false,"robotFF_useProtocolApi2":false,"robotLeftPipette":"p10_single_v1.5","robotRightPipette":"p50_single_v1.4","robotSmoothieVersion":"edge-8414642","runTime":5,"success":false}},"optedIn":true}}
```

That has a reasonable description of the problem (to wit: "AbsentModuleError [line 111]: no module of name tempdeck is currently connected"). This needs to be shown to the user.

## current behavior

Errors thrown during execution of protcol are hidden from the user and a vague 'something bad happened' is shown.

## steps to reproduce

See above.

## expected behavior

Show the contextually available error information to the user.

**Comment by mcous** [comment]
Thanks for the report @rgatkinson. I really appreciate the time you took to debug the error you were receiving.  Unfortunately the run experience is one of the oldest parts of our app's codebase, and it needs a lot of love, both from an experience and architectural standpoint.

This error state is available in _most_ instances, so we should be able to display it in the UI when we have it
