### ISSUE TITLE
API: Error logs are dropping message or stack trace

### ISSUE THREAD

**Issue by bndo** [Opentrons/opentrons#4380]
## overview

API errors are missing critical information

## current behavior

An example error log looks like:
`Exception during RPC call:`

## steps to reproduce

This is a top-level exception catch for any that are thrown during a protocol action sent via rpc

## expected behavior

The log should include the message associated with the exception

**Comment by bndo** [comment]
Possibly related to #3535

**Comment by sfoster1** [comment]
it's not really related, it's a problem with our syslog-ng config probably
