### ISSUE TITLE
question: Connecting to Smoothie without OT Linux

### ISSUE THREAD

**Issue by theosanderson** [Opentrons/opentrons#4397]
I am trying to do some development beyond the scope of typical "protocols" and therefore want a high level of control over the machine that is connected to the Smoothieboard. (I have considered the various alternatives). It seems to me that I might be able to take an SD card containing a standard Raspbian distro, run `pip install opentrons` and have control over the robot. Unfortunately it hasn't been quite so simple and I wondered if anyone had any tips.

In my current configuration if I try to specify a port I get:
```
>>> robot.connect("/dev/ttyAMA0")
Traceback (most recent call last):
  File "/home/pi/bare/lib/python3.6/site-packages/opentrons/drivers/smoothie_drivers/driver_3_0.py", line 1123, in _setup
    self._wait_for_ack()
  File "/home/pi/bare/lib/python3.6/site-packages/opentrons/drivers/smoothie_drivers/driver_3_0.py", line 907, in _wait_for_ack
    self._send_command('\r\n', timeout=SMOOTHIE_BOOT_TIMEOUT)
  File "/home/pi/bare/lib/python3.6/site-packages/opentrons/drivers/smoothie_drivers/driver_3_0.py", line 943, in _send_command
    return self._send_command_unsynchronized(command, timeout)
  File "/home/pi/bare/lib/python3.6/site-packages/opentrons/drivers/smoothie_drivers/driver_3_0.py", line 965, in _send_command_unsynchronized
    5.0, DEFAULT_COMMAND_RETRIES)
  File "/home/pi/bare/lib/python3.6/site-packages/opentrons/drivers/smoothie_drivers/driver_3_0.py", line 1043, in _write_with_retries
    raise serial_communication.SerialNoResponse()
opentrons.drivers.serial_communication.SerialNoResponse
```

My `/boot/cmdline.txt` currently contains (thanks to trying various things):

`dwc_otg.lpm_enable=0 console=tty1 console=ttyAMA0,115200 root=PARTUUID=d59534e0-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash`

Does anyone have any instincts about what I might be missing? Any thoughts much appreciated.

**Comment by theosanderson** [comment]
```
>>> list_ports.comports()[0].name
'ttyAMA0'
```

**Comment by theosanderson** [comment]
OK I made some progress by adding `dtoverlay=pi3-miniuart-bt` to `/boot/config.txt`. Can now connect to robot and ask it to home which it does, but then I get a timeout waiting for a response from Smoothie. Also `robot.set_rail_lights_on()` has no effect. Trying disabling bt now.

**Comment by theosanderson** [comment]
Woop - I think I've finally got it.

My final `/boot/cmdline.txt`:
`dwc_otg.lpm_enable=0 console=tty1 root=PARTUUID=d59534e0-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash` (no ref to AMA0)

Final section of `/boot/config.txt`:
```
[all]
#dtoverlay=vc4-fkms-v3d
start_x=1
gpu_mem=128
#dtoverlay=w1-gpio
enable_uart=1
dtoverlay=pi3-miniuart-bt
```

At this point I could connect with `robot.connect("/dev/ttyAMA0")` (note you have to specify the full path because normally an environmental variable contains this) but after calling the home command the Smoothie homed but then failed to respond, and commands for turning on the lights work. The problem was that the GPIO pins weren't initialized. Running gpio.initialize() did not fix this on its own. What was missing was running the blinkenlights script (https://github.com/Opentrons/buildroot/blob/opentrons-develop/board/opentrons/ot2/rootfs-overlay/usr/bin/ot-blinkenlights) that starts on startup on a normal OT2. This initializes a bunch of key pins.

After running that script everything seems to work! I think it would be awesome to refactor lines 17 to 29 of that script as gpio.enable_robot() or similar and then expose that within robot. Then the Python library becomes self-contained.

**Comment by theosanderson** [comment]
Wrote this up: https://github.com/theosanderson/Advanced_OT2/tree/master/Raspbian_OT2

**Comment by theosanderson** [comment]
Leaving this open because of the suggestion for simple refactoring - feel free to close it though.

**Comment by theosanderson** [comment]
Related issue: APIv2 does not allow the port to be specified in `protocol = opentrons.execute.get_protocol_api()` so requires the environmental variable to be set. Given that the port parameter is still present downstream it would seem useful to surface this?

**Comment by sfoster1** [comment]
Yeah, you're right. There are probably some slightly thorny issues around making sure that function is called only once, but nothing impossible. Feel free to open a PR - and thank you for this and other contributions!
