### ISSUE TITLE
docs: OT1 docs are not marked as being only for OT1

### ISSUE THREAD

**Issue by theosanderson** [Opentrons/opentrons#4403]
## overview

If I perform a Google search (as many people will) for "opentrons pipette" I get as the top API result a page entitled "Liquid Handling — Opentrons API v2.0" which I would expect to be what I want to use for the OT2. In fact it is the OT1 API, but the only indication of this is in the URL: https://docs.opentrons.com/ot1/pipettes.html

## expected behavior

Put a big warning on all these pages that they are for the OT1 only.

**Comment by DerAndere1** [comment]
@theosanderson and other users: I also stumbled across this confused google result. For people who are looking for the API v2 (BETA, may be subject to change, currently for the OT-2 robot), see this documentation: https://docs.opentrons.com/v2/new_protocol_api.html .

**Comment by sfoster1** [comment]
Note that even though this ticket is marked as closed, we probably won't deploy the docs change until the next release so we don't accidentally deploy documentation only valid in e.g. 3.16.0 and confuse everybody.
