### ISSUE TITLE
Final Touch: Link in the crash info box

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#4414]
## overview

The link in the crash info box (from #4410) doesn't go anywhere yet

Until modules in PD is live, link to google doc:
https://docs.google.com/document/d/1kE8qwlx6jVoPmWe0AwNmHVbnDNa4RHnoLCcDTt0SA1s/edit?usp=sharing

**Comment by btmorr** [comment]
@howisthisnamenottakenyet please provide links for the separate articles once they're posted

**Comment by howisthisnamenottakenyet** [comment]
@IanLondon https://docs.google.com/document/d/1kE8qwlx6jVoPmWe0AwNmHVbnDNa4RHnoLCcDTt0SA1s/edit?usp=sharing
