### ISSUE TITLE
App: Flip temperature module rendering in 3,6,9

### ISSUE THREAD

**Issue by b-cooper** [Opentrons/opentrons#4422]
## overview

When a temperature module is placed in slots 3, 6, or 9, the Run app displays it as if the cords were on the left side. We should treat all tempdecks in slots 3, 6, 9 as flipped in the RobotWorkSpace component.

**Comment by kinnari-opentrons** [comment]
![Screen Shot 2019-11-11 at 12 00 11 PM](https://user-images.githubusercontent.com/37346748/68623743-3135a100-04a3-11ea-97f2-ab02c4ac1845.png)
Software version 3.14.0

**Comment by bndo** [comment]
We're not going to migrate the designs from PD into this, but rather we can just flip it.

**Comment by kinnari-opentrons** [comment]
So glad this is closed!
