### ISSUE TITLE
Labware Creator: Check 3 Deck Crosses Before Labware Test

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#4451]
As a OT-2 user who just created a new labware definition, I would like to confirm my OT-2 has a good deck calibration before testing my labware, so that I do not conflate calibration problems with labware definition problems.

## Acceptance Criteria
- [ ] Update labware test protocol to check all three deck calibration crosses (slots 1, 3, 7) before labware check.

## Design
- Note this update should be released in conjunction with an update the the labware test documentation (@howisthisnamenottakenyet). Adding blocked tag until we're ready to go on documentation.

**Comment by pantslakz** [comment]
@umbhau any ideas why this is blocked?

**Comment by umbhau** [comment]
Just the note from above in the design section (making sure we also have updated documentation ready to go)
