### ISSUE TITLE
PD: Nice-to-have: Auto-fill form fields with previously entered values (engage height field)

### ISSUE THREAD

**Issue by mikec116** [Opentrons/opentrons#4457]
#User Story
As a user, I don't want to have to enter the same values over and over again when creating multiple protocol steps. 

# Acceptance Criteria
- [ ] If a user defines a magnetic module engage height earlier in the protocol, let’s preserve this number the next time the user tries to engage the magnetic module

**Comment by pantslakz** [comment]
re tip position - should it preserve and replicate again for every step created after? or only steps referencing the same labware?

**Comment by mikec116** [comment]
Removing the tip position feature

**Comment by IanLondon** [comment]
Completed in PD Magnetic Module project
