### ISSUE TITLE
Perf opportunity: avoid numpy.isclose()

### ISSUE THREAD

**Issue by rgatkinson** [Opentrons/opentrons#4482]
## overview

The same performance analyis mentioned in #4481 also indicated that 10.2% of time is spent in ``numpy.isclose()``:

![image](https://user-images.githubusercontent.com/111943/69198989-7719e700-0aeb-11ea-8fcc-9dbe48f8fc67.png)

A brief look at ``numpy.isclose()`` shows it to be a very general purpose function, handling cases of arrays, etc which we don't need. All we need is to be able to compare two scalars, for which the following function suffices;

```
def is_close(x, y, atol=1e-08, rtol=1e-05):
    if x == y:
        return True
    return abs(x-y) <= atol + rtol * abs(y)
```

Avoiding ``numpy.isclose()`` in favor of the above sould be a simple but significant performance improvement.

## current behavior

An overabundance of time is spent comparing two scalars for closeness.

## steps to reproduce

See above.

## expected behavior

Simple things should be fast :-).

**Comment by sfoster1** [comment]
@rgatkinson thanks for the report - great catch! We'll take a look at it. It's a fundamental part of our system and requires a lot of testing but the proposed fix does look really simple and valid.
