### ISSUE TITLE
Remove Eppendorf tip racks from the Labware Library

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#4518]
# Background

Our Labware Library has two of Eppendorf's obnoxiously named epT.I.P.S. tip racks:

1. [Eppendorf epT.I.P.S. 96 Tip Rack 10 µL](https://labware.opentrons.com/eppendorf_96_tiprack_10ul_eptips/)
2. [Eppendorf epT.I.P.S. 96 Tip Rack 1000 µL](https://labware.opentrons.com/eppendorf_96_tiprack_1000ul_eptips/)

The tips are unsupported by us, and the tip rack requires an adapter to even fit on the deck.

# Proposal

It was decided in a Slack thread back in August that, because of the adapter requirement, they should be removed from the library until the library can communicate that sort of caveat. (The definitions are still kept around, so this won't break anything.) So, let's do that.

**Comment by mcous** [comment]
Should these tipracks be available in the Protocol Designer? Ping @mikec116 @IanLondon
