### ISSUE TITLE
API: Add pick up tip functionality to deck cal HTTP endpoints

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/opentrons#4520]
## overview

You can already pick up tip with the CLI deck calibration tool, but we should also have this ability in the HTTP endpoints so that we can eventually modify our app deck calibration workflow.

## complete when
- You can load in a tiprack to calibrate to
- You can successfully pick up tip with all pipette models

**Comment by sfoster1** [comment]
We're overhauling robot calibration instead
