### ISSUE TITLE
Custom Labware: MixPanel Analytics Events

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#4537]
As a product manager, I would like to be able to track usage of the custom labware feature, so that I can understand its adoption rate and any usability issues.

## Acceptance Criteria
- [ ] Create new mixpanel events as documented in the Event Tracking spreadsheet (see rows tagged with this user story)

## Resources
[- Event Tracking Plan](https://docs.google.com/spreadsheets/d/1pQxlZPcCg9PX6tmVBoDw36CLexKJ09rr7f2VdUSyyz0/edit#gid=0)

**Comment by mcous** [comment]
Closed by #4544
