### ISSUE TITLE
Remove the defunct "custom labware" factory reset checkbox

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#4568]
<img width="549" alt="Screen Shot 2019-12-09 at 12 09 37 PM" src="https://user-images.githubusercontent.com/3236864/70462119-35e07b80-1a88-11ea-9936-e575a5930577.png">

This checkbox is apparently defunct.

- APIv1 custom labware is actually cleared by the labware calibration factory reset.
- APIv2 custom labware is not persisted on the robot, so there is nothing to clear.

So it should be removed.

**Comment by mcous** [comment]
Re-categorized as an API because the app populates the options in this UI based on the `GET /settings/reset/options` endpoint
