### ISSUE TITLE
AssertionError when calibrating a pipette that's loaded but unused in a Protocol Designer protocol

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#4570]
# Summary

Protocol Designer can export protocols that will trigger an AssertionError in the Opentrons App.

# Steps to reproduce

1. Create a protocol in Protocol Designer with two pipettes.
2. Load the deck with a tip rack for each pipette, and some labware.
3. Add any liquid transport step for one pipette, but not the other.
4. Export and upload the protocol.
5. The used pipette will get through pipette calibration as normal.
6. The unloved pipette will trigger this error:

<img width="535" alt="Screen Shot 2019-12-09 at 3 18 15 PM" src="https://user-images.githubusercontent.com/3236864/70469717-96c38000-1a97-11ea-854f-b83f81aa05b6.png">

# Expected behavior

Either:

- The pipette should be able to get through pipette calibration.
- Or, the pipette should not be subject to pipette calibration (because it's unused).

**Comment by mcous** [comment]
Related to #4538. Also possibly happens with Python protocols with unused pipettes. Workaround for the moment is to avoid tip-probing that unused pipette.

Until RPC calibration sessions can be replaced, we'll need to build some understanding of "unused" into the app's RPC client and void exposing it for calibration (hopefully with a tooltip or something)
