### ISSUE TITLE
App: show and proceed with available module updates

### ISSUE THREAD

**Issue by b-cooper** [Opentrons/opentrons#4576]
## overview

This provides the front-end changes to #4575.
The currently designed "Updated" button in the Modules & Pipettes tab should suffice for an initial UI. 

In the GET /modules response, parse out whether or not there is an available update for a given module by serial number. If there is, enable the button and change its text to "Update".

Upon clicking, show some loading state (preferrably one that states "keep module plugged in and turned on"), and display the module update response.

**Comment by mcous** [comment]
Heads up: I'm planning to refactor the modules state in the app to follow the latest stuff in the cookbooks (see #4440 and #4573 for the same refactor with pipettes, and #4477 for the same refactor for config reset and restart).

Might make sense to knock the refactor out to avoid duplication of work and to hopefully make the implementation of this feature more straightforward; the modules actions and reducer will be more simple after the refactor
