### ISSUE TITLE
Log download button spins infinitely after canceling a file save

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#4579]
When you click the Download button in the app to download logs, you get a prompt to save each file. If you cancel one of those dialogs instead of clicking Save, the spinner in the Download button spins forever. Relaunching the app resets it.

Tested on macOS.

**Comment by ethanfjones** [comment]
I tested this on linux and 4.2.0. It is still happening.

**Comment by mattwelch** [comment]
Bug triage determination: MLM

**Comment by SyntaxColoring** [comment]
Possibly still an issue, but closing as stale.
