### ISSUE TITLE
Pipette Settings dialog Save button should have a spinner

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#4583]
# Overview
Clicking Save in the Pipette Settings dialog apparently involves communicating with the robot.

If that communication is delayed – which is likely, over Wi-Fi – it looks like the Save button isn't doing anything.

# Expected behavior
There should be a spinner (with a timeout, I guess) on the Save button when you click it, until the settings are committed and the dialog closes.

**Comment by mcous** [comment]
Will be trivial to implement once #4573 lanfs
