### ISSUE TITLE
tiprack-200ul should not be referenced in examples and documentation

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#4587]
# Summary

The `tiprack-200ul` definition is purported to be compatible with modern Opentrons 300 µL tip racks. However, its default calibration height is too low in this case. It will put the pipette nozzle slightly inside the pipette tips, which is likely to cause a crash.

This impacts people's ability to run any legacy protocol with an out-of-the-box OT-2 or after a labware calibration factory reset. Notably our Labware Library protocols still use the `tiprack-200ul` definition.

# Steps to reproduce

1. Factory reset labware calibration.
2. Upload a protocol with a `tiprack-200ul`.
3. Load the deck with an Opentrons 300 µL tip rack.
4. Do labware calibration. Note that the initial calibration position will have the pipette nozzle inside the pipette tips, instead of at or above its top.

The default position for`opentrons_96_tiprack_300ul` looks more reasonable.

**Comment by mcous** [comment]
> The tiprack-200ul definition is purported to be compatible with modern Opentrons 300 µL tip racks

@SyntaxColoring who told you this? I don't think it's true. Prior to `opentrons_96_tiprack_300ul` existing, we (SW + API docs) recommended users use the v1 definition `opentrons-tiprack-300ul`. If there are protocols on PL for OT-2 that reference the super-old `tiprack-200ul` (which, IIRC, is possibly a TipOne or GEB tiprack with a 3D printed adapter) then that's a problem in PL

**Comment by SyntaxColoring** [comment]
Any other Opentrons folks, please see the Slack #support thread instead of replying here. 👍
