### ISSUE TITLE
LL/LC: Release of LC with updated PDF matching new test protocol

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#4620]
As a user testing a new custom labware definition, I would like my the test documentation to match the python test protocol, so that I don't get confused.

## Acceptance Criteria
- [ ] New PDF instruction guides user to:
    - [ ] check depth at end of protocol
    - [ ] place labware to be tested in slot 2
- [ ] Update PDF (linked below)

## Implementation Notes
- This ticket should follow #4451.
- The instructions PDF is not part of the LL/LC website release process, it's a separate S3 bucket. When we release LL/LC with the new 3-cross protocol, we need to manually update the PDF at `https://opentrons-publications.s3.us-east-2.amazonaws.com/labwareDefinition_testGuide.pdf`.

## PDF
[Labware Test Guide.pdf](https://github.com/Opentrons/opentrons/files/4833351/Labware.Test.Guide.pdf)

**Comment by umbhau** [comment]
@howisthisnamenottakenyet would you update this pdf to reflect both the 'check depth at end of protocol' and 'place labware to be tested in slot 2' changes?

**Comment by IanLondon** [comment]
Done in release of LL 1.7.0!
