### ISSUE TITLE
Robot HTTP Api: Establish error codes and structures

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#4636]
## overview

Well-structured APIs have well structured error conventions and data. We will create such structured errors and use them on both the API and the app sides, at least through the HTTP api and maybe temporarily through the RPC API.

We should create a json document in shared-data that establishes error numbers, shortnames, and additional types. This document is, essentially, a schema, but also specifies some level of content - the list of available errors.

Once the document is created, we can start adding to it and using it in HTTP responses.

**Comment by mcous** [comment]
https://tools.ietf.org/html/rfc7807
