### ISSUE TITLE
Robot HTTP API: Publish documentation to docs site

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#4638]
## overview
Write documentation about the higher level expectations about how to use the API, versioning contracts, and so on.

In addition, use a tool like swagger to generate documentation from the OpenAPI spec added in #4635 

## acceptance criteria (WIP)

* [ ] API / robot-server docs move to top-level Protocol / HTTP API docs project
* [ ] TODO

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535429662) by [Unito](https://www.unito.io/learn-more)

**Comment by mattwelch** [comment]
Not a bug. (How did it get on this board.)
