### ISSUE TITLE
API docs links with the ".html" missing redirect infinitely

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#4672]
# Overview

If you navigate to an API documentation URL but don't include the `.html` at the end (by typo, for example), the browser is recursively redirected down an ever-deepening `docs.opentrons.com/v2/v2/v2/v2/...` path.

# Steps to repro

1. Pick an APIv2 URL, like `https://docs.opentrons.com/v2/index.html`.
2. Remove the `.html` from it, like `https://docs.opentrons.com/v2/index`.
3. Whee!

**Comment by mcous** [comment]
This is the culrpit:

https://github.com/Opentrons/opentrons/blob/2e73fe56c764a0d32a17a54fb456eb9310bac5ee/api/docs/root/index.html#L11-L13

- The redirect URL should be absolute, not relative
- It should use the [`window.location.replace`](https://developer.mozilla.org/en-US/docs/Web/API/Location/replace) method, not re-assign `window.location.href`
