### ISSUE TITLE
Gen2 Multi: Pre-PVT config changes

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#4699]
Placeholder for required config changes for Gen2 multis based on DVT testing that should be in before PVT

**Comment by ChrisYarka** [comment]
**Changes for P20M:**
pickUpCurrent = 0.6
pickUpDistance = 11
dropTipCurrent = 1.25


**Changes for P300M:**
pickUpCurrent = 0.8
pickUpDistance = 11
dropTipCurrent = 1.25
dropTipSpeed = 7.5


https://docs.google.com/spreadsheets/d/1f-GsQnQkL0mI1pb9OnsZtr9tGj_Fav0TMorvo3RMIyQ/edit#gid=657969563
