### ISSUE TITLE
PD: consistent names + no default exports in StepEditForm/ files

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#4711]
## overview

In our JS Cookbook we regard default exports as bad, largely b/c it allows things like

```js
// forms/Spam.js
const Spammy = () => {...}
export default Spammy
```

then you might even `import SpamForm from './forms/Spam'`. That gets very confusing when you go back and re-read the code. We have 3 names for the same thing: Spam, Spammy, SpamForm.

This problem has gotten notably bad for the components in the folder `protocol-designer/src/components/StepEditForm/`.

## acceptance criteria

Unless there is a good reason to make an exception for certain cases, for all files in `StepEditForm/` we should...

* Remove all default exports
* For files that export a single component / fn, the file name should match the export variable's name exactly.

**Comment by iansolano** [comment]
Yeah, this seems to be a common complaint from other engineers in the community see: [here](https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/). I think what you all are proposing makes sense. Although, it probably warrants putting some additional linter rules using something like [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import).

In the past as part of successful conventions i've experience the directory structure and components follow the same naming conventions, which in turn make grepping around projects much easier.

e.g.
```
Directory: `/components/forms/edit/index.js`
Component Name: `FormEdit`

Directory: `/containers/forms/edit/index.js`
Component Name: `FormEdit`
```
This helps follow the component chain from something like a route entry point all the way down to it's presentational component(s)
