### ISSUE TITLE
API docs: sticky header obscures anchor-linked headings

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#4719]
# Overview
When following a link to a specific heading, that heading is buried behind the fat navbar.

This makes it difficult to show people function documentation.

For example, this is what it looks like 
when I try to directly link to [the Well.bottom() function reference](https://docs.opentrons.com/v2/new_protocol_api.html#opentrons.protocol_api.labware.Well.bottom):

![](https://user-images.githubusercontent.com/3236864/72192110-74908b00-33d2-11ea-98e7-e985c9d364cd.png)

# Expected behavior
The page should load with the linked-to heading positioned just below the navbar.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535431164) by [Unito](https://www.unito.io/learn-more)

**Comment by mattwelch** [comment]
Bug triage determination: MLH

**Comment by mcous** [comment]
Moved to RSS-183. Fix PR up at #12115
