### ISSUE TITLE
PD: Usability Improvement - Revise Deckmap Crash Warning

### ISSUE THREAD

**Issue by mikec116** [Opentrons/opentrons#4725]
## Changes needed

Deck map:
- [ ] In slot copy should be "No GEN1 8-channel access".
![image](https://user-images.githubusercontent.com/35570080/72540929-a16bf480-384f-11ea-9681-2251475ba3be.png)

**Comment by shlokamin** [comment]
@mikec116 @howisthisnamenottakenyet I'm assuming "Channel" should capitalized as in the image
