### ISSUE TITLE
App should display pipette serial numbers

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#4730]
## overview

The app has access to pipette serial numbers, but does not display them. As a user, I would like to view my pipettes' serial numbers without having to remove the pipette from the mount and read the sticker

## acceptance criteria

- [ ] User can view pipette serial numbers in the app

### Design
https://zpl.io/awx7DZ1

**Comment by pantslakz** [comment]
https://zpl.io/awx7DZ1
