### ISSUE TITLE
PD: Hook up wait until tempdeck temp

### ISSUE THREAD

**Issue by Kadee80** [Opentrons/opentrons#4732]
## overview

This ticket is the sibling to #4306. This is a placeholder for wiring up the wait until temperature deck temp reached.

## Acceptance criteria
TBD see #4693 for notes

## State update

These 2 cases should already be done

deactivate:
- change status to TEMPERATURE_DEACTIVATED
- set targetTemperature to null

set temp
- change status to TEMPERATURE_APPROACHING_TARGET
- set targetTemperature to given target temp

### new state updater

await temp case 1: the awaited temp equals the previous state's targetTemperature
- set status to TEMPERATURE_AT_TARGET
- targetTemperature stays the same
NOTE: previous state might be TEMPERATURE_APPROACHING_TARGET or can be TEMPERATURE_AT_TARGET

await temp case 2: the awaited temp is different than targetTemperature
- A: previously was TEMPERATURE_APPROACHING_TARGET -- no update. We're still approaching that temp. Hopefully our await is able to actually resolve 🤞 
- B: previously was TEMPERATURE_AT_TARGET won't happen, will hit timeline error
- C: DEACTIVATED won't happen, will hit timeline error (below)

### errors in command creator

awaiting different temp while already at target (2B)
- In the waitForTemp command creator, return an error if temp mod is TEMPERATURE_AT_TARGET and the targetTemperature in prev state is different than than this command's target temp. Error: "Awaiting temperature but temp module already at target"

awaiting while deactivated (2C)
- In the waitForTemp command creator, return an error if the temperature module is deactivated. This is a timeline error. "Awaiting temperature but temp module is deactivated"

### Background
Case 2B: Holding a temp. Built a wait for temp that isn’t the same as what is being held. 
Case 2C:  Previously was deactivated. Built a wait for temp step. 
Case 2D (not covered in MVP!): wait for temp is outside of the range of current module temp and goal temp. 

### Copy
Error copy that covers cases 2B and 2C for both temp & thermo: 
"Title: Missing Temperature step
Body: Add a Temperature step prior to this Pause step. The module is not currently changing temperature because it has either been deactivated or is holding a temperature."

**Comment by shlokamin** [comment]
Waiting on decision about whether we are awaiting a custom target temp, or whether we are awaiting the previous `set temp` command temperature to be reached
