### ISSUE TITLE
"Calibrate to bottom" diagram incorrect when calibrating reservoirs with multi-channel pipettes

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#4734]
# Overview

The calibration flow has an illustration to explain how to align the pipette tip to the top of a well.

If the calibrate to bottom switch is enabled, that image isn't updated. It will tell the user to calibrate to the top of the well even though they should calibrate to the bottom.

This report comes from a user, who was specifically testing with a 12-well reservoir.

# Expected behavior

If the calibrate to bottom switch is enabled, it should change the image in the labware calibration flow accordingly.

**Comment by mcous** [comment]
Regression introduced by #3823 and exposed by the switch to PAPIv2. The App tries to display calibrate to bottom diagrams for all labware, but the diagram is incorrect in the one case of calibrating a reservoir with a multi-channel pipette
