### ISSUE TITLE
API: Better error message for unsupported schema

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#4735]
## overview

For me, this is most relevant to PD saving v4 JSON protocols. When that release eventually goes out, users will see a hard-to-understand message that may be confusing.

## current behavior

User gets an overly-technical message that does not help them understand what they need to do (eg, they need to update their robot so that it can execute new protocols from the updated version of PD)

![image](https://user-images.githubusercontent.com/11590381/72363145-5670a680-36c2-11ea-8010-f257e93f1daf.png)

## desired behavior

The ideal might be to somehow decouple this error message text from Robot / Run App's release cycle, so that we can update this copy in anticipation of a release.

Instead of getting fancy, we could just make the copy more descriptive and link to a support article that can be updated outside of the robot / run app release cycle.

## implementation side note

We're planning to gradually add a key to all user-managed JSON files (labware definitions and protocols) that defines what kind of file it is so we won't have to infer labware vs protocol etc. This will help us make these messages more targeted

**Comment by pantslakz** [comment]
Updated error messages:

**If user uploads a JSON protocol that is not supported on robot/app version:**
_"Your protocol could not be opened.
The protocol you are trying to open is a JSONv4 protocol and is not supported by your current robot server version. Please update your OT-2 App and robot server to the latest version and try again."_

**If user uploads a JSON Labware definition:**
_"The file you have uploaded is a JSON labware definition, and therefore can not be opened in this app. Please try uploading a JSON protocol file instead."_
