### ISSUE TITLE
Wireless MAC addresses should be predictable before connecting to a wireless network

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#4758]
# Current behavior

* ~The robot uses a different MAC address for each wireless network.~
    * As of at least the 3.19 release, the Wi-Fi interface appears to use the same, real MAC address no matter the network
* Those MACs aren't predictable. You have to actually connect to a network for the app to tell you what MAC address the robot uses for it.
    * As of 3.19, this is still true! When the robot is **disconnected**, the MAC address it reports for it Wi-Fi interface (and that gets shown in the app) is completely random

This makes it somewhat difficult to set up networks that have allow-listing or static IP assignment based on MAC.

# Desired behavior

- [x] There is One Wireless MAC Address To Rule Them All. It doesn't change from network to network.
- [ ] That Wi-Fi MAC address is displayed somewhere *before connecting to Wi-Fi.*

# Prior issues

* #3175 
* #4121 

---
Edited by @mcous upon further investigation

**Comment by mcous** [comment]
Related ticket: #5200

**Comment by mcous** [comment]
Wi-Fi MAC address appears in code and in actual behavior to be stable? Investigating

**Comment by SyntaxColoring** [comment]
> Wi-Fi MAC address appears in code and in actual behavior to be stable? Investigating

Hm!

If it turns out that it *is* stable, let's be careful about closing this issue. One of the expected behaviors is:
> [The] Wi-Fi MAC address is visible somewhere before connecting to Wi-Fi...

If we close this ticket, we should open a new ticket for that. (In hindsight, that should have been in a separate ticket, to begin with.)

**Comment by mcous** [comment]
Updated the original comment. We do not need a separate ticket for displaying MAC in the app, because the MAC has always been displayed in the app.

When connected to Wi-Fi (no matter the network), the MAC address is stable. When disconnected from Wi-Fi, the robot reports a random MAC address for the Wi-Fi interface to the app

**Comment by SyntaxColoring** [comment]
In addition to needing to connect to a wireless network to see the correct wireless MAC address:

It might be a good idea to close and reopen the Opentrons App before checking the MAC.

I'm not 100% sure this actually matters, but I *think* I've seen the Opentrons App show stale IP addresses. (There's no issue ticketed for this, yet.) The same thing might happen for MAC addresses.

**Comment by mcous** [comment]
> I'm not 100% sure this actually matters, but I think I've seen the Opentrons App show stale IP addresses. (There's no issue ticketed for this, yet.) So it might do the same thing for MAC addresses.

The app polls the `/networking/status` endpoint on something like a 5 or 10 second interval. The IP and MAC come from that endpoint. It'll take a second after reconfiguring Wi-Fi for that info to update
