### ISSUE TITLE
The error for a wrong Wi-Fi password should be less cryptic

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#4761]
# Current behavior

1. Try connecting to a Wi-Fi network with a wrong password.
1. The app will give you a message saying "Secrets were required but not provided." This cute but cryptic message apparently bubbles up from NetworkManager.

# Desired behavior
For the common cases of:

* Getting the password wrong for a WPA2 Personal network
* Getting any of the credentials wrong for a WPA2 Enterprise network

We should have copy to the tune of:

> There was a problem connecting to that network. Check your credentials and try again.
>
> _Hint: Try the **Show password** checkbox!_

For WPA2 Enterprise networks, we should also suggest that they ask their IT team or network administrator for help.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535432938) by [Unito](https://www.unito.io/learn-more)

**Comment by mattwelch** [comment]
Bug triage determination: MLL

**Comment by SyntaxColoring** [comment]
Closing as low-priority and sort-of-fixed.

This is how the message shows up today:

<img width="1024" alt="Screenshot 2024-02-27 at 11 48 16 AM" src="https://github.com/Opentrons/opentrons/assets/3236864/3bf24a76-443d-42f2-a4c7-ea5b94ff07c1">

There's a lot of unhelpful technobabble at the top, but it *does* now say to check your network credentials, in the middle.
