### ISSUE TITLE
Custom Tipracks in PD

### ISSUE THREAD

**Issue by Kadee80** [Opentrons/opentrons#4780]

**Comment by umbhau** [comment]
Product Brief: 
https://docs.google.com/document/d/1it06YbZdHpMN0oanyKtFS7jWfBI7VWqHiXeih__Uyo4/edit#

**Comment by umbhau** [comment]
Product Initiative:
https://docs.google.com/document/d/1WRISY-OpYVtsy8YajoClFWIOg3tab_oV-F8XUK_IL2w/edit#
