### ISSUE TITLE
Clean up flow rate terminology and semantics

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#4837]
# Overview
The flow rate adjustment situation is kind of messy.

## "Flow rate" vs. "Speed"
The API [has a distinction](https://docs.opentrons.com/v2/new_pipette.html?highlight=pipette%20flow_rate#plunger-flow-rates) between "speed" and "flow rate."

* `pipette.flow_rate.aspirate` et. al. adjust the plunger speed in µL/sec.
* `pipette.speed.aspirate` et. al. adjust the plunger speed in mm/sec, and are probably _not_ what people want to use.

These terms are too easily conflated.

* In internal communications, we use them interchangeably.
* In the API documentation, we use them sloppily and wrongly.
* In the run log, we wrongly say "speed" instead of "rate."

## Absolute value vs. relative multiplier
* `pipette.flow_rate.aspirate = 10` sets the pipette's aspirate flow rate to 10 µL/sec.
* `pipette.aspirate(vol, well, rate=10)` aspirates 10 times faster than the default, whatever the default is.

This discrepancy is confusing. Plus, it's not always an easy mistake to notice when you watch the robot run through a protocol.

Also, #2772. The run log says "Aspirating...**at speed 1.0**". First, as described above, "speed" should be "rate." But also, the 1.0 is apparently just the raw `rate=` argument. It doesn't take into account any changes made to `pipette.flow_rate.aspirate`.

# Proposals
1. For specificity and correctness, rename the liquid handling functions' `rate` kwarg to something like `flow_rate_multiplier`, and deprecate the old name.
1. For completeness, add a `ul_per_sec` kwarg to the liquid handling functions.
1. For consistency with <span>#</span>2, rename `pipette.flow_rate.aspirate` et. al. to `pipette.ul_per_sec.aspirate`, and deprecate the old name.
1. Change the run log to say "Aspirating...at 123 µL/s." (I'm assuming that the absolute number is what people are most likely to care about. If we still want to mention the multiplier, we should think of a more specific way to say it, like "Aspirating...at 200% the default rate" or something.)

## Alternative outside-the-box proposal
Have fewer functions with kwargs and use context managers instead.

```python
pipette.dispense(loc, 100)
with pipette.ul_per_sec(aspirate=50, dispense=25):
    pipette.mix(repetitions=4)
```

# These terms in other contexts
These are off the top of my head. We should probably do some greps to be exhaustive.

## In the API documentation
Examples and documentation use the terms "speed" and "rate" interchangeably. They should mostly be unified to say "flow rate." We can say "speed" in a few calculated places for searchability.

## In support articles
There's probably some support articles that make the same mistake.

## In Protocol Designer
Protocol Designer seems inconsistent, using "Flow Rate" as a label on the main step screen and "Aspirate Speed" in a popup. They should all probably be changed to "Flow Rate." We can ticket that separately once we're clear on what to do here.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535435621) by [Unito](https://www.unito.io/learn-more)

**Comment by IanLondon** [comment]
Thanks Max!

Related: https://github.com/Opentrons/opentrons/blob/d07efcba8522ee7e0178a68342dc81fb4998387e/api/src/opentrons/protocol_api/execute_v3.py#L33

Since there's no nice way to specify flow rate in uL/sec in blowout/aspirate/dispense, the JSON executor sets the flow rate before blowout/aspirate/dispense in a boilerplate-heavy way. Would be great to have a kwarg to set absolute uL/sec instead of relative %!

**Comment by SyntaxColoring** [comment]
A small part of this was previously ticketed as #2772. Updated this ticket accordingly.

**Comment by MarcelRobitaille** [comment]
I agree. Another thing is that the docs for `aspirate` say that the plunger speed will be `rate * aspirate_speed`, but there is no other mention of `aspirate_speed` in the docs. How do I set it?

**Comment by SyntaxColoring** [comment]
@MarcelRobitaille, I think that's a mistake in the docs. Instead of `aspirate_speed`, it should say [`speed.aspirate`](https://docs.opentrons.com/v2/new_protocol_api.html#opentrons.protocol_api.contexts.InstrumentContext.speed).

Thanks for asking about that. We'll get it fixed soon.

**Comment by SyntaxColoring** [comment]
In our overhaul of the Protocol API back-end ("Protocol Engine"), we're trying to use µL/sec flow rates instead of multipliers. This should address internal DX like what @IanLondon brought up, but won't directly address the DX of the user-facing Python Protocol API.
