### ISSUE TITLE
Feature: App should disable Wi-Fi config if robot isn't connected via Ethernet

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#4850]
## overview

* As a user, I don't want my robot's Wi-Fi configuration to be messed with by anyone who does not have physical access to the robot
* As a user, it is confusing when I change my robot's Wi-Fi network to a network I am not on because it is difficult to figure out if I succeeded

The Wi-Fi configuration of a robot shouldn't be messed with by anyone without physical access to the robot. Given how our Wi-Fi endpoints currently function, it is also difficult to reasonably return a status to the client when telling a robot (via Wi-Fi) to get on a different network that the client is not on

## acceptance criteria

* [ ] Wi-Fi selection options are disabled and greyed out in the app for non-local robots
  * https://zpl.io/beLx9vl
* [ ] App displays tooltip informing user why options are disabled

## implementation details
Takes over for #2718 in conjunction with #4847 and #4849

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535436008) by [Unito](https://www.unito.io/learn-more)

**Comment by mattwelch** [comment]
Bug triage determination: LMM
