### ISSUE TITLE
Feature: API should only allow Wi-Fi config requests over Ethernet interface

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#4851]
## overview

* As a user, I don't want my robot's Wi-Fi configuration to be messed with by anyone who does not have physical access to the robot
* As a user, it is confusing when I change my robot's Wi-Fi network to a network I am not on because it is difficult to figure out if I succeeded

In order to prevent Wi-Fi configuration by users who are not physically connected to the OT-2, the Wi-Fi configuration endpoints should be blocked on the wireless network interface.

## acceptance criteria

* [ ] Calls to Wi-Fi config requests over the Ethernet interface should succeed
* [ ] Calls to the config endpoints over Wi-Fi should 403

## implementation notes

* The SSH key endpoints are only accessibly over link-local IP addresses, which is similar to this functionality as described
* **TODO**: decide what desired behavior is for requests over Ethernet from non-link-local addresses (e.g. robot is on a wired network with a DHCP server)

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535436014) by [Unito](https://www.unito.io/learn-more)

**Comment by mattwelch** [comment]
Bug triage determination: LMM
