### ISSUE TITLE
LC: Update PDF to new test protocol instructions

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#4873]
As a user testing a new custom labware, I would like the test documentation to match the current test protocol, which checks all three crosses.

## Acceptance criteria:
- [x] Updated PDF documentation guiding user through testing all three crosses (see link below)
- [ ] Update PDF in production LC

## Implementation Notes
- The instructions PDF is not part of the LL/LC website release process, it's a separate S3 bucket. When we release LL/LC with the new 3-cross protocol, we need to manually update the PDF at https://opentrons-publications.s3.us-east-2.amazonaws.com/labwareDefinition_testGuide.pdf

## New PDF
[Labware test- 3 calibration crosses.pdf](https://github.com/Opentrons/opentrons/files/4161479/Labware.test-.3.calibration.crosses.pdf)

**Comment by howisthisnamenottakenyet** [comment]
@pantslakz @umbhau Could one of you take a quick peek at the PDF? It's a long doc so I'd love a second set of eyes to see help check if I missed anything while updating it.

**Comment by pantslakz** [comment]
Reads great @howisthisnamenottakenyet 

If I understand correctly - the main difference now is users can set up deck from start - right?

I do wonder how we can effectively communicate this change to prior LC users, so they know to access the new instructions/not be surprised by movement changes.

**Comment by howisthisnamenottakenyet** [comment]
@pantslakz Yup! I'm hoping the visual change on the deck from slot 3 to slot 2 will help cue them in

**Comment by Kadee80** [comment]
Closed via AWS update.
