### ISSUE TITLE
LC: Change test protocol 

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#4874]
## Background
The custom labware in the test protocol currently goes in Slot 3. This was an artifact from when the robot only tested the calibration cross in Slot 3. Now that we're using the other calibration crosses too, we can place the custom labware in Slot 2. This will prevent the user from needing to take their labware on and off the deck. 

## Acceptance Criteria
- [ ] Update the test protocol to use Slot 2 for the custom labware instead of Slot 3.

**Comment by Kadee80** [comment]
Closing in favor of newer ticket #5019 in epic
