### ISSUE TITLE
PD Bug: Pristine unsaved MAGNET form -> whitescreen

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#4908]
## overview

Problem with module ID field not being set in pristine unsaved magnet form when you close & open the form without saving. Whitescreen!

Note: this bug has not been released

## current behavior / steps to reproduce

1. Make a protocol with a magnetic module
2. Add a MAGNET step but don't save it
3. Click on another step eg Initial Deck Setup
4. Click on the MAGNET step again to select it
5. Click "Save" on the MAGNET step form

This causes a whitescreen. `TypeError: Cannot read property ‘moduleState’ of undefined` from `magnetUpdates.js:24`

## expected behavior

Module ID field should be correctly set in magnet steps, even when pristine + unsaved (and eventually, no "pristine unsaved" step forms allowed!)

**Comment by shlokamin** [comment]
Related, but the same thing happens when you try to add a magnet step without selecting labware to go inside of the magnetic module
