### ISSUE TITLE
Bad magdeck was causing the API server to fail to respond to requests

### ISSUE THREAD

**Issue by nusrat813** [Opentrons/opentrons#4924]
## overview
When magdeck with "bad" firmware is connected to the robot, the api server fails to respond to the request

## current behavior

When magdeck with bad firmware is connected to the robot, the robot is shows up in the app but is unable to connect. Furthermore, its move functions (engage/ disengage/ probe) seem to fail to execute in the fw / hw. After the first move gcode, the magdeck becomes unresponsive and doesn’t respond to any further gcodes.

Magdeck Firmware - 1.0.1
Robot app/server version: 3.15.2 

## steps to reproduce

1. Update magdeck firmware 
2. Connect magdeck to robot
3. Attempt to connect robot in app

## expected behavior

Robot should connect with all 3 modules attached

**Comment by sfoster1** [comment]
Same as https://github.com/Opentrons/opentrons-modules/issues/105
