### ISSUE TITLE
PD: Importing protocols with magnetic or temp module loads the wrong module

### ISSUE THREAD

**Issue by jen-fong** [Opentrons/opentrons#4930]
## overview
Magnet and temperature modules are not being imported properly in PD. @IanLondon mentions this may have been introduced in the JSON v4 PR. 

## current behavior

- Importing a protocol with a temperature or magnet module (or both) leads to a thermocycler module being displayed on the deck and loaded under File > Modules
- Importing a protocol with a temperature/magentic module with a thermocycler module leads 2 thermocycler modules being displayed on the deck (one on the temperature module slot) and only thermocycler showing up under File > Modules
- Importing a protocol with just a thermocycler module gives the expected behavior. It is displayed on the deck and shows up under File > Modules

## steps to reproduce

http://sandbox.designer.opentrons.com/edge/

1. Create a new protocol with a magnet or temperature module (or both) and add the required labware to the deck.
2. Export the protocol.
3. Reimport the protocol.
4. Under modules, you should see the the module you added has the Add button on the right. Thermocycler has Edit and Remove buttons.
5. Click on design. 
6. The deck should show a thermocycler module in the slot instead of your module.

## expected behavior

Importing protocols with modules should load their respective module.

**Comment by IanLondon** [comment]
This is a symptom of #4897
