### ISSUE TITLE
Schema v4 Update Guidance: Update Modal

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#4933]
As a PD user opening the latest version of PD, I would like to be informed that PD now supports modules, and that using them requires an App and Robot update.

## Acceptance Criteria
- [ ] Users opening the latest version of PD are informed in an Update Modal that they can now include modules in their protocols.
- [ ] Users are informed that using modules requires their robot on app and robot version > [TBD]
- [ ] Users are informed that the app and robot updates are only required if using modules

## Notes
- users do not have to be made aware of the PD or Protocol Schema version bump
- we decided not to include an 'do not show me again' checkbox; this modal will only display once

## Design
https://app.zeplin.io/project/5c87a3f55f998e3943ad5d38/screen/5e3a06eda3e25f984e06a9e9

## Copy
See design

**Comment by howisthisnamenottakenyet** [comment]
@pantslakz 

"**Note:** Adding modules to your protocols **may require updating the OT-2 app and robot**. Protocols with a module will only run on the **latest versions** (3.17 and higher)."
