### ISSUE TITLE
transfer bug when transfering to rows bottom

### ISSUE THREAD

**Issue by cfblaeb** [Opentrons/opentrons#495]
When using transfer with a multi pipette to transfer 2 rows on plate A to 2 rows on plate B it works correctly in example A below, but in example B it moves both plate A rows to 1 row on plate B.
The difference being whether the transfer target is .bottom() or not.
Workaround is to replace plateB.rows(length=2).bottom() with [x.bottom() for x in plateB.rows(length=2)]

example A:
multipipette.transfer(5,  plateA.rows(length=2), plateB.rows(length=2))
example B:
multipipette.transfer(5,  plateA.rows(length=2), plateB.rows(length=2).bottom())

**Comment by mcous** [comment]
Sorry for the lack of response on this ticket! `.top()` and `.bottom()` should only ever be used on a single well. Your "workaround" above is the correct way to write this transfer

```py
multipipette.transfer(
    5,
    plateA.rows(length=2),
    [ well.bottom() for well in plateB.rows(length=2) ]
)
```
