### ISSUE TITLE
PD: Make enabled modules in PD a full feature, promote "Disable module placement restrictions" to experimental setting

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#4968]
## Acceptance criteria
- [ ] Promote "enable modules in PD" prerelease-mode setting to a full feature (no longer a setting, always on)
- [ ] Promote "disable module placement restrictions" to be a user-facing experimental setting

**Comment by Kadee80** [comment]
This ticket should probably involve the removal of the enable modules in PD modal. Once thats removed we can change the location of the disable module placement restrictions flag.

**Comment by IanLondon** [comment]
Blocked until we're close to doing the Modules in PD release, this should be one of the last steps. Unlikely but possible: if we do this promotion too early and for some reason need to publish a fix to non-modules PD in the meantime, it would be gross.
