### ISSUE TITLE
app: incorrect render of reset/change labware source directory buttons on linux and windows

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#4974]
## overview
In 3.16.0-alpha.0, the reset source and change source labware buttons render with the same dark grey background as the textbox above on windows and linux:

![Screen Shot 2020-02-12 at 11 08 05 AM](https://user-images.githubusercontent.com/3091648/74354006-b6717000-4d88-11ea-80c3-76e99b39e5e9.png)

whereas on mac they look ok:

<img width="606" alt="Screen Shot 2020-02-12 at 11 13 47 AM" src="https://user-images.githubusercontent.com/3091648/74354028-c12c0500-4d88-11ea-9d8b-21b6594868be.png">

**Comment by mcous** [comment]
Closed by #4976
