### ISSUE TITLE
app: opening bad protocol file causes blank screen

### ISSUE THREAD

**Issue by amitlissack** [Opentrons/opentrons#4977]
## overview

Possible to blank the screen with bad protocol json.

## current behavior
Opening a json file with `"schemaVersion": 3` at root level causes blank screen. A refresh is required to bring the UI back.

## steps to reproduce

- Create a file `fail.json` with contents
```
{
	"schemaVersion":3
}
```
- Start run app
- Connect to robot
- Open `fail.json` as a protocol

## expected behavior

An error message should appear

**Comment by mcous** [comment]
Bug introduced by #3891 by the selector `getLabwareDefBySlot` (which, fun fact, is not covered by unit tests).

`getLabwareDefBySlot` assumes `state.protocol.data` is a valid protocol, but in reality it is the eagerly loaded `JSON.parse` of the protocol file.

This is complicated by RPC stuff, but I think our best path forward would be to add some sort of `state.protocol.valid` flag that is set to `true` by the `robot:SESSION_RESPONSE` action (successful upload + simulation) or set to `false` by `robot:SESSION_ERROR` (failed upload + simulation).

`protocolReducer` already listens for `robot:SESSION_RESPONSE`, so a corresponding listener for `robot:SESSION_ERROR` would make sense I think
