### ISSUE TITLE
Protocols can access variables that they don't define

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#4982]
Well, at least one variable, `context`.

I'm assuming an [`eval()`](https://docs.python.org/3/library/functions.html#eval) somewhere is forgetting to pass `globals` and `locals` and accidentally leaking the API server's internals.

Possibly related to #4981.

# Test case

```python
metadata = {"apiLevel": "2.1"}

def run(protocol):
    # Note `context` is never defined here.
    protocol.comment(str(protocol is context))
```

# Output

```
$ opentrons_simulate test.py
...
True
```

# Expected output

A Python error because `context` is not defined.

**Comment by sfoster1** [comment]
I think the farthest we'll go with this is to rename that variable to something a little less likely to collide (e.g. `__context`). To execute the run function properly we need to do it in an eval so we can control the local environment, and to do that we need to provide the function argument, so it needs to be bound in the local environment somewhere.

**Comment by SyntaxColoring** [comment]
That seems fine.

Out of curiosity, why can't we just execute the protocol like:

```python
with open('uploaded_protocol_file.py', 'w') as f:
    f.write(protocol_source)
import uploaded_protocol_file
uploaded_protocol_file.run(context)
```

That would also make `metadata` inspection easier, right?
