### ISSUE TITLE
PD: Tooltip persistence

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#4987]
## Background

This happens in the modal when you try to edit a placed module

![image](https://user-images.githubusercontent.com/35570080/74379404-be93d480-4db5-11ea-8b47-bd6d1ab1cc6d.png)

When you exit the hover area to the left, the tooltip persists. 

## Acceptance criteria
- [ ] When you move your mouse away from the hover area, the tooltip should disappear

**Comment by jen-fong** [comment]
might be related https://github.com/facebook/react/issues/4251
