### ISSUE TITLE
Create an opentrons python library sub-project in mono repo

### ISSUE THREAD

**Issue by amitlissack** [Opentrons/opentrons#5010]
## overview

It can me named py-opentrons or something else more imaginative.
This would contain everything in api project minus opentrons.server and opentrons.app packages. Almost everything in current api is applicable to building a package vs an application.

~~- [ ] new sub project created (was decided to keep API name)~~
~~- [ ] all sources moved from `api` to new sub project minus webservice packages.~~
- [x] move webservice code out of package
- [x] pipfile loses aiohttp and fastapi dependencies
- [x] webservice documentation is removed

**Comment by amitlissack** [comment]
Merged into feature branch `api_splitup`

**Comment by amitlissack** [comment]
This ticket has been re-scoped: 
- The fastapi package will be moved out of api package. The rest remains.
- API will not be the entrypoint into HTTP server. Robot Server will.

**Comment by mcous** [comment]
Closed by #5083
