### ISSUE TITLE
Refactor and simplify request handlers to further divide API and library

### ISSUE THREAD

**Issue by amitlissack** [Opentrons/opentrons#5014]
## overview

The request handlers in `opentrons.server.endpoints` contain a good amount of code that should be moved to the `opentrons` install-able package.

Examples

- the move function in control.py should be moved out to the shared library. Interacting with the motion lock is too much intimate knowledge of the hardware for a request handler.
- take_picture should call a method in the library rather than invoking ffmpeg.

- [ ] All request handlers make simple function calls into opentrons library. (ie take_pictiure() etc.)
- [ ] API has no knowledge of feature flags or any other internal configuration of opentrons library

**Comment by mcous** [comment]
Most, if not all, of this split was accomplished with the #4963 epic
