### ISSUE TITLE
Deck Calibration Check: Tip Pickup and Location Sanity Check (2nd Pipette)

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#5038]
As a user, I would like to be guided through picking up a tip with my second pipette, if any, so that I can use it to check my mount offset. 

I would like the robot to validate that the tip position is close to its expected position for a 'good' calibration before proceeding, to prevent downstream crashes and wasted effort. 

### Tip Pickup
- [ ] If second pipette mounted, guide user through picking up tip second pipette
  - [ ] If second tiprack used (for different tip type), tiprack should be in slot 8, per #5033 
- [ ] Pipette automatically moves to a safe distance from top of pipette tip, ignoring any tiprack labware calibration
- [ ] User prompted to jog to correct tip pickup position
  - [ ] IF single channel and using new tip rack, user guided to A1 tip position
  - [ ] IF single channel and using same tip rack as 1st pipette, user guided to B1 tip position
  - [ ] IF multi channel and using new tip rack, user guided to H1 tip position with rear pipette nozzle
  - [ ] IF multi channel and same tip rack as 1st pipette, user guided to G1 tip position with rear pipette nozzle
- [ ] User provided with visual guidance and standard jog controls
-  [ ] User prompted to initiate tip pickup
- [ ] Pipette picks up tip using standard tip pickup method
- [ ] User prompted to confirm tip pickup was successful
  - [ ] IF tip pickup fails, prompt user to re-try
  - [ ] IF tip pickup successful, check tip pickup position (see below)

### Check Tip Pickup Position
- [ ] Validate that user's specified tip pickup position is close to the expected location of the tip, given the current deck calibration (but ignoring the tiprack's labware calibration)
  - [ ] Range of 'close enough' distances specified in 'resources' below
- [ ] If tip pickup position is outside of range, display ‘Bad Deck Calibration’ modal from #5035 
- [ ] If tip pickup position is inside range, proceed to 'Calibration Check Successful' modal

### Analytics
- [ ] send calibrationCheckFail event and set failureType property = 'Tiprack Location Offset', as specified in Event Tracking Plan (see 'Resources' section)

## Resources
Acceptable difference between nominal and user-specified tip position
- See ranges in #5035 

Analytics [Event Tracking Plan](https://docs.google.com/spreadsheets/d/1pQxlZPcCg9PX6tmVBoDw36CLexKJ09rr7f2VdUSyyz0/edit#gid=0
)

### Design
Animated graphics can be found on storage drive:
Opentrons > UX Design > 00 Product Initiative / HMG / Calibration Check > Animations

**Comment by pantslakz** [comment]
If using same tip rack - will pick up from B1 instead of A1.

**Comment by b-cooper** [comment]
closed by #5499 and #5583
