### ISSUE TITLE
Deck Calibration Check: Evaluate Z Offset (2nd Pipette)

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#5040]
As a user, I would like to be guided through checking my 2nd pipette’s position relative to the deck in the Z axis

### Jog to flush position
- [ ] After successfully picking up tip and passing tip rack location sanity check (#5035), pipette moves automatically to a safe distance (5mm) from deck
  - [ ] Position should be 5mm mm above a flat section of slot 5
- [ ] User prompted to jog in Z direction until pipette is flush with deck
  - [ ] User can use 0.1mm and 1mm jog controls in Z direction only
- [ ] User has option to continue and evaluate Z position
- [ ] User has option to cancel and return to Robot page

### Evaluate Z position
- [ ] After clicking 'continue', user views a new modal with the Z calibration results
- [ ] User informed whether their calibrated location is within acceptable bounds
  - [ ] Tolerances are the absolute values (same in +/- Z direction)
  - [ ] Tolerances are specific to pipette model (see 'resources' for table of tolerances)
- [ ] User can view delta from calibration position
- [ ] If pipette calibration is acceptable, user prompted to **continue**, and proceed to 'Deck Calibration Complete' modal
- [ ] If pipette calibration is unacceptable, user prompted to exit to “Fail Mount Offset Calibration” modal (see below)

### Fail Mount Offset Modal
- [ ] New modal informs user that we’ve detected an offset between their pipettes (this modal will be used for z, x, and y offsets)
- [ ] Inform them that we recommend they reach out to the support team for guidance (fyi: support team will guide them through CLI deck calibration)
- [ ] User prompted to exit modal and calibration check process to Robots page
- [ ] User given option to ignore and continue with 2nd pipette calibration check (proceeding to Deck Calibration Complete modal)

### Design
- https://zpl.io/a3omdWx

### Analytics
- [ ] send calibrationCheckFail event and set failureType property = 'Z Offset', as specified in Event Tracking Plan (see 'Resources' section)

## Resources
Passing Deck Calibration in Z direction. All values are absolute distance.
- See values in #5036 

Analytics [Event Tracking Plan](https://docs.google.com/spreadsheets/d/1pQxlZPcCg9PX6tmVBoDw36CLexKJ09rr7f2VdUSyyz0/edit#gid=0
)

**Comment by b-cooper** [comment]
closed by #5499 and #5583
