### ISSUE TITLE
Deck Calibration Check: Evaluate X/Y Offset (2nd Pipette)

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#5043]
As a user, I would like to be able to check my 2nd pipette's offset from the first pipette.

## Acceptance Criteria
**Calibration Check**
- [ ] After completing Z offset evaluation (and passing, #5040), 2nd pipette moves automatically to calibration cross in slot 1
- [ ] Position should be 0.5mm above deck to allow for any deck warp
- [ ] User has access to Z jog controls only, in order to jog pipette tip flush with deck
- [ ] User prompted to confirm that pipette tip is centered over deck cross
- [ ] User given clear guidance on appropriate margins
- [ ] User prompted to verify calibration and proceed to next step
- [ ] If user indicates that pipette tip is not centered over deck cross, display "Bad Mount Offset" modal (from #5040 )
- [ ] If user indicates that pipette tip is centered over deck cross, proceed to "Deck Calibration Check Complete" modal

## Resources
Acceptable Margins
- TBD per @sfoster1 

## Copy and Design
- https://zpl.io/VkvAoeM

**Comment by b-cooper** [comment]
closed by #5499 and #5583
