### ISSUE TITLE
feat: Keep pipette's position fixed while mixing

### ISSUE THREAD

**Issue by tzeitim** [Opentrons/opentrons#5132]
As mentioned on the [building blocks section](https://docs.opentrons.com/v2/new_atomic_commands.html#mix) the mixing routine forces the position to go up and down between aspiration and dispensation cycles. Sometimes this is undesirable.

Would it be possible to add a flag to the mix routine to keep position fixed?

**Comment by SyntaxColoring** [comment]
Hey @tzeitim! Thanks for requesting this.

I believe this is already being tracked in #4640. A fix is in the works: see #5128.

I'm going to close this ticket as a duplicate, for now. If you think that's a mistake, just let me know, and we'll re-open it. 👍
