### ISSUE TITLE
PD: Scrollable announcements

### ISSUE THREAD

**Issue by jen-fong** [Opentrons/opentrons#5160]
When announcement text gets too long, there should be a white fade at the bottom (similar to run app). Once you scroll, the faded text should come into view.

![image (1).png](https://images.zenhubusercontent.com/5e27310c1016be3885509ac9/d1b2764c-1e8e-455e-9ad0-e5a02099c0b5)

**Comment by IanLondon** [comment]
@howisthisnamenottakenyet is there an alternative to the white fade? If the copy happens to have whitespace in that place, the fade becomes invisible and on Mac the scroll bar can be hidden so it can just look like it's not scrollable
