### ISSUE TITLE
Spike: Collect all instances of robot interactions in the app without error UI

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#5172]
## overview
For many app <> robot interactions, stuff can currently fail silently. The most common cause for this is hard-limit switch hits, but other errors have occurred in the past.

We need a list of all robot <> app interactions that result in robot movements with:

1. Whether or not the robot raises an error to the app if something goes wrong
1. If (1) is "yes", whether or not the app catches and stores that error
1. If (2) is "yes", whether or not the app shows that error to the user

## acceptance criteria

* [ ] List of robot movement interactions
* [ ] Tickets to address any "no" answers from above 

_Aside_: This list of movement interactions is also good to have for current API planning work

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535442302) by [Unito](https://www.unito.io/learn-more)

**Comment by asogluizzo** [comment]
no longer necessary
