### ISSUE TITLE
Discovery Research spike: Document current wired comm system

### ISSUE THREAD

**Issue by sanni-t** [Opentrons/opentrons#5198]
There are quite a few processes involved in making wired communication with robot happen-
Network manager, Avahi, DHCP, networking related systemd processes and usb/ethernet drivers. We don't yet fully understand what each one does and whether all of them are working well together. Also, when you look at a robot's system log, we see some errors and warnings from these processes at quite a regular interval. We should investigate these messages and understand what exactly is going on during a wired communication with the robot. 
Scope of this ticket:
- [ ] Document the components & processes involved in robot's networking 
- [ ] Investigate the most commonly found system messages that are either mysterious or have warnings & errors

**Comment by mcous** [comment]
Closed with: https://coda.io/d/Robot-IP-Address-Assignment_dPkX21A5C1W/Overview_suXiL#_luyTZ
