### ISSUE TITLE
Discovery: Spike: Avahi

### ISSUE THREAD

**Issue by sanni-t** [Opentrons/opentrons#5199]
Why do we need Avahi? Does it come with any issues? Is there a better alternative to it? 
Reasons: Avahi is responsible for advertising the robot's ip on the network. At least that's what we think it does. Is that all it does? Is it necessary? How does it work with Network manager? We don't know the answers to these questions and it is essential to understand this component since it is crucial for robot discovery.
Scope of this ticket:
- [ ] Document how Avahi works with other processes involved in networking.
- [ ] Document any known issues with Avahi
- [ ] If possible, check if we can live without Avahi on the robot

**Comment by mcous** [comment]
Spike results:

- Unable to find any evidence of failures of Avahi advertisements when the rest of the IP system behaves properly
- Going to explore avahi-autoipd (not currently used) as a potential solution to #5200
