### ISSUE TITLE
Discovery: Spike: Analytics

### ISSUE THREAD

**Issue by sanni-t** [Opentrons/opentrons#5201]
There are still quite a lot of unknowns in getting to the root cause of most discovery problems. Can we collect some specific info from the user's system & robot that will help us find patterns in these issues?
Find out the following:
For app:
- [ ] User's computer's driver settings (version, date, eee, etc)
For robot:
- [ ] Robot system logs relevant to discovery problems
- [ ] Robot driver settings

**Comment by mcous** [comment]
Done
