### ISSUE TITLE
api bug: Confusing error message when pick_up_tip is used on a bare location (minor)

### ISSUE THREAD

**Issue by theosanderson** [Opentrons/opentrons#5213]
# Overview
This is a very minor low-priority issue where the error message isn't quite as expected for a niche usage.

# Current behavior
If you say 

```
pipette.pick_up_tip( opentrons.types.Location(opentrons.types.Point(x,y,z),"my_location"))
```

You get the suboptimal error:

```
  File "/home/pi/bare/lib/python3.6/site-packages/opentrons/protocol_api/contexts.py", line 1267, in pick_up_tip
    assert tiprack.is_tiprack, "{} is not a tiprack".format(str(tiprack))
UnboundLocalError: local variable 'tiprack' referenced before assignment
```

This is because this unexpected usage falls through a crack in the if-then logic whereby the location is a location but is neither a well nor labware, and so the tiprack variable is not set. https://github.com/Opentrons/opentrons/blob/edge/api/src/opentrons/protocol_api/instrument_context.py#L634

# Expected behavior
Perhaps a clearer error message saying that bare locations are not supported. ~~Ideally for my use-case this would actually be supported, but I understand that is niche and I'm now figuring out how to work around but I thought I'd log the variable-used-before assignment issue.~~ Ed: I see this wouldn't make sense with tip-lengths etc.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535442965) by [Unito](https://www.unito.io/learn-more)

**Comment by mcous** [comment]
No longer appears to be an issue after reading the current code

**Comment by theosanderson** [comment]
Fwiw it's still an issue, but may well not be worth your time
<img width="649" alt="image" src="https://user-images.githubusercontent.com/19732295/194733847-b7eb90ed-1beb-41a5-82cb-1c86b4ac524b.png">
