### ISSUE TITLE
bug: Pipette paths through tall labware when returning the tip at the end of labware calibration

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#5248]
# Overview
@antonjs noticed this one.

Under certain circumstances, at the end of labware calibration, when the pipette goes to return a tip, it will path through labware.

# Steps to reproduce
I seem to have overwritten my notes (oops), so these reproduction steps are approximate. But it went something like this:

1. Upload a protocol with:
  * A tip rack on one of the right slots.
  * A Temperature Module in slot 4.
  * A short well plate of some kind on the Temperature Module.
  * Either a P300S GEN2 in the left mount or a P20S GEN2 in the right mount (I can't remember which we used).
1. Do pipette calibration as normal.
1. Calibrate the well plate several cm too high.
1. Immediately after calibrating the plate, the robot will want to return the tip to the tip rack. When you click the button to do so, the pipette will descend below the height that you just calibrated, pathing through labware.

# Expected behavior
If I tell the robot that the top of the plate is several cm higher than it expected, it should believe me, and move the pipette to a safe height to clear it.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535443197) by [Unito](https://www.unito.io/learn-more)

**Comment by mcous** [comment]
Labware calibration flow was replaced by LPC, which runs through the `ProtocolEngine` using a newer path planning logic. I believe this issue to be fixed
