### ISSUE TITLE
Deck Calibration Check: Report Error States To the Client

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/opentrons#5255]
## Overview
There are two available error states in the deck calibration check flow.
1. noPipettesAttached error, this will propagate if a user only has 1 pipette attached when starting the flow or no pipettes attached at all.
2. badDeckCalibration error, this will propagate any time the robot detects a move that would result in a crash.

## Requirements
The status message for the session should now have an optional error key that will appear any time one of these errors occurs during a request.

**Comment by Laura-Danielle** [comment]
## Overview

There are two available error states in the deck calibration check flow.
1. noPipettesAttached error, this will propagate if a user only has 1 pipette attached when starting the flow or no pipettes attached at all.
2. badDeckCalibration error, this will propagate any time the robot detects a move that would result in a crash.

## Requirements
The status message for the session should now have an optional error key that will appear any time one of these errors occurs during a request.

**Comment by sfoster1** [comment]
No longer relevant
