### ISSUE TITLE
Button on robot frame doesn't do anything

### ISSUE THREAD

**Issue by btmorr** [Opentrons/opentrons#531]
## overview
The button on the frame is available, and should ostensibly have some function.

## behavior
**Current behavior**: nothing

**Desired behavior**: something

## some design considerations
1. We technically can use all 5 colors but it doesn't mean we should. The meaning of 5 different colors may be hard for a user to keep track of. 
1. We may want to utilize flashing as well as colors for human-intervention-needed states so they can be as attention grabbing for our users who may have varying types of color blindness.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535444059) by [Unito](https://www.unito.io/learn-more)

**Comment by btmorr** [comment]
I haven't heard complete consensus as to what this button should do. The most common behavior I've heard mentioned is to halt the robot, but I haven't seen anything formally specifying this.

**Comment by IanLondon** [comment]
+1 for emergency halt during run

There was talk of a "replay" behavior when the robot is idle.

If the robot is paused during a protocol run (as in "pause until user hits resume"), maybe it can resume there, mimicking the behavior of "Resume" in the app?

@andySigler  ???

**Comment by andySigler** [comment]
Here's a minimal flow Jackson and I made way back last spring

![ot2 button led](https://user-images.githubusercontent.com/3085774/35056974-7c670f9c-fb81-11e7-8293-14f045b5e2b2.png)

**Comment by pantslakz** [comment]
@mcous @btmorr would be lovely to get the above on the robot sometime soon. Morgan and I had the chance to work through this with Andy and Jackson - looks solid!

**Comment by howisthisnamenottakenyet** [comment]
I edited the description to add some design considerations

**Comment by Matt-Zwimpfer** [comment]
MHH - let's make a decision; @readywater has been considering this

**Comment by readywater** [comment]
![A4.png](https://images.zenhubusercontent.com/604bc5a4a968b3ad36dcdea0/a433f573-bdd3-423f-93be-9fea38c75a6a)

Basic pause/play and cancel interactions from the button. Would also suggest adding a log object with timestamp and interaction point (app/robot/api) the pause/play/cancel steps are triggered.

**Comment by readywater** [comment]
Adding a quick revision to this:
**Pause** functions should aim to be non-destructive, since pausing is often used to correct a human or minor robot error. Pausing should retract Z axis to allow for manipulation of labware on the deck. 
If moving, along X or Y, movement should be completed and Z axis should remain retracted (eg. move to dispense location, but don't dispense)

**Cancel** should be immediate, with the idea that canceling an action is to prevent some kind of physically destructive. After canceling, the robot should be homed from a software client.

**Comment by emilywools** [comment]
hey @readywater question for you:

"if the protocol is canceled from the robot, the post-confirm cancelation experience should start in app"

Does that mean the run is not actually cancelled if the user presses + holds the physical button until the user confirms in-app?

**Comment by readywater** [comment]
@emilywools No, the run is canceled by press and hold without in-app confirmation. The app should still have a confirmation dialog though.

**Comment by mattwelch** [comment]
We'll write a new implementation ticket to execute on the outcomes noted on this ticket.
