### ISSUE TITLE
bug: Tip probe for pipettes associated with one tip rack shows tip rack as N/A 

### ISSUE THREAD

**Issue by nusrat813** [Opentrons/opentrons#5311]
# Current behavior

If 2 pipettes are associated with one tip rack, one pipette in the tip probe flow shows tip rack as N/A

Note: The tip probe process, calibration and run is still successful.  

# Steps to reproduce

Upload protocol that has 2 pipettes associated with one tip rack. Go to the calibration screen and check one of the pipettes show tiprack as N/A 

<img width="1014" alt="Screen Shot 2020-03-30 at 12 49 01 PM" src="https://user-images.githubusercontent.com/30632549/77941460-32b40a00-7288-11ea-8fbb-b96856618744.png">

# Expected behavior
Both pipettes should show the tip rack for tip probe

**Comment by mcous** [comment]
Closed by #5319
