### ISSUE TITLE
CI: Run Cypress E2E tests in CI build

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#5318]
# Overview

We're got a bunch of E2E tests now. But we never run them! We should run Cypress tests in Travis.

NOTE: tests may be failing b/c we don't run them often. This ticket will be blocked by any test failures that come up.

**Comment by dozercodes** [comment]
Cypress documentation for [running in CI](https://docs.cypress.io/guides/guides/continuous-integration.html#Examples), includes an example for Travis

**Comment by mcous** [comment]
We should definitely run the E2E tests in a parallel job in the test stage. IIRC, if we're concerned about flakey tests, we can mark the E2E job as allowed to fail until we're confident
