### ISSUE TITLE
bug: PD@edge whitescreens if you try to drag a step before touching the step list

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#5367]
# Overview

Protocol Designer in `edge` (**not in production**) has a bug where the app will whitescreen if you attempt to drag a step in the step list as your first action.

# Steps to reproduce

1. Import a protocol
2. Go to “Design” tab
3. Attempt to drag to reorder the steps before doing anything else with the steps
4. Whitescreen!

![2020-04-03 14 58 06](https://user-images.githubusercontent.com/2963448/78396148-cfdead80-75bc-11ea-9095-8d18ba1cc6ef.gif)

# Expected behavior

Re-ordering steps in the step list at any time should not crash the app

**Comment by Kadee80** [comment]
Just looked into this, I get the bug described above when importing older V4 protocols. `labwareDefRUI` seems to be the culprit.

However, I can not reproduce when I make a new protocol, save it, and import it again.
