### ISSUE TITLE
Inconsistent return values for wells

### ISSUE THREAD

**Issue by btmorr** [Opentrons/opentrons#537]
## overview

When accessing wells, the return type is unpredictable depending on the number of arguments passed. It is possible to get a single Well, a WellSeries of Wells, or a WellSeries of WellSeries of Wells.

## behavior

**Current behavior**: See #319, #320, #331, and #409 

**Desired behavior**: Any function that should return some number of wells should have a return type of `List[Well]`, and functions that take a `List[Well]` should behave predictably when given an empty list, a list with one element, or a list with more than one element.

**Comment by sfoster1** [comment]
This is true (and a wontfix) in v1, and nice and consistent in v2.
