### ISSUE TITLE
Deck Calibration Check: Set Active Pipette

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/opentrons#5410]
## Overview

We want the server to hold responsibility over which pipette to use specifically for any move to location step after a pipette has picked up a tip.

## Acceptance Criteria
- Session status should display an active pipette UUID when relevant
- State machine should be dependent on the correct pipette UUID when moving to a "Calibration Step"
- The following steps should be dependent on a pipette UUID:
          1. move to slots 1,2,3,5
          2. drop tip

**Comment by b-cooper** [comment]
closed by #5583
