### ISSUE TITLE
bug: PD Delay durations are converted to seconds in JSON export

### ISSUE THREAD

**Issue by dozercodes** [Opentrons/opentrons#5414]
# Overview
Delay durations are converted to seconds on the JSON export, so when the protocol runs in the Run App, the duration is read as "0 minutes X seconds". For example, a 5 minute 0 second delay would read as "0 minutes 600 seconds" in the run app logs.

Note: I'm unsure if this is an issue with the PD export converting the time, or the Run App not converting the time

# Current behavior
Durations are converted to only use seconds:
![image](https://user-images.githubusercontent.com/579696/79021670-26fafa00-7b4a-11ea-8015-87eddabbe283.png)

# Steps to reproduce
1. Create a protocol in PD
2. Add a Pause step with a delay duration greater than 1 minute
3. Export the protocol and import it into the Run App
4. Run the protocol
5. Observe the duration item in the log

# Expected behavior
Duration should be read as "X minutes Y seconds"

**Comment by IanLondon** [comment]
IMO, JSON delays should only specify seconds to avoid making the commands more complicated. Instead of only showing the seconds, Run Log could convert into h:m:s from seconds but if the PD user put "90 seconds" the Run Log would show "1m 30s".
