### ISSUE TITLE
bug: PD Module Tags are cut off on the Deck Map

### ISSUE THREAD

**Issue by dozercodes** [Opentrons/opentrons#5417]
# Overview
When the window containing PD is of a narrower aspect ratio, less than 4:3, the Module tags are cut off on the ends. Resizing should account for the full size of the module tags.

# Current behavior
![image](https://user-images.githubusercontent.com/579696/79143154-b858af00-7d8a-11ea-9f2b-cfde37d37697.png)

# Steps to reproduce
1. Create/Import a protocol
2. Open the design tab
3. Make the browser window narrower
4. Observe the module tags

# Expected behavior
Resizing should account for the full size of the module tags.

**Comment by IanLondon** [comment]
As of fa8a16b8, this looks like it has been fixed
