### ISSUE TITLE
chore: Remove Question about "which module is most important for future updates" from signup form

### ISSUE THREAD

**Issue by dozercodes** [Opentrons/opentrons#5420]
# Overview
"Which module would be most important for future updates to add to the Protocol Designer?" question in the signup form is no longer relevant and should be removed.

![image](https://user-images.githubusercontent.com/579696/79144543-24d4ad80-7d8d-11ea-8130-c3561b0de668.png)

# Acceptance criteria

- [ ] Question no longer appears on Signup Form

**Comment by IanLondon** [comment]
Alfie closed this, I just confirmed on prod
