### ISSUE TITLE
Epic: Touch tip fixes for 3.18.0

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#5450]
This epic collates work to prevent pipettes from colliding with adjacent modules during touch tip.

With all pipettes and modules (although the situation is worse with Gen2 Multi pipettes and Gen1 modules), performing a touch tip in the column of a labware immediately adjacent to a module can cause the pipette to collide, since the pipette moves over farther to reach the edges of the well during a touch tip.

To fix this, we'll detect when touch tip is performed on a column adjacent to a module and change the touch tip behavior to not touch the side of the well closest to the module.

**Comment by Laura-Danielle** [comment]
Epic was completed.
