### ISSUE TITLE
Component library should have a GUI for all the components

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#546]
## overview

This issue is for a documentation request to improve the DX of our components library. We should have a GUI / documentation where we can view all our components in the library. This will help us:

* Write new components without necessarily needing to use them in another project right away
    * Smaller PRs
* Discover existing components when working on component consumer projects
* Allow the UI/UX team to easily see which components we've actually implemented

### current

Right now, in order to discover a component, we have to:

* Read the source code
* Find somewhere in the app or protocol designer where the component is used
* Hope the component was documented in the README

### desired

Ideally, we have a website (local spun-up server or published static site) that lists all the components by name with examples of what they look like and list of all their props.

## proposal

I spent all of 30 minutes playing around with [react-styleguidist](https://react-styleguidist.js.org/) and was able to pretty much drop it right into the components library. Off the bat, this gives us a locally runnable static site with:

* Component names
* Props and prop types (works with Flow)

With an amount of work, we would also get:

* Usage instructions of components and props
    * Requires us to write JSDocs for our components
* Live examples of components with editable props
    * Requires us to write and place a ComponentName.md file next to each component
* Organization of components into catgories
    * Requires some styleguidist config and category.md files

It would also require us to be a little more strict about some file + function naming conventions:

* Only actual components can be functions named in `PascalCase`
    * We would need to rename `DeckFactory` because it is a component factory, not a component
* Each component needs its own `PascalCase.js` file using the default export for the component
    * This is already true of every component except PrimaryButton

### potential downsides

* Doesn't look like we can use it to document utility functions and CSS exports automatically
    * Mitigation: we can still just do it manually in Markdown and include that in the docs
* The Flow type detection isn't awesome
    * A type like `number | string` shows up in the PropTypes table as `union`
    * Correct, but unhelpful
    * Mitigation: can put the types in the union into the JSDoc string

**Comment by IanLondon** [comment]
I should have named it lower d `deckFactory.js` since it's a HOC... We were talking about making it a component `Deck.js` that takes the `labwareComponent` prop, would that work with styleguidist?

Related question: how will styleguidist work for components that have required props?
