### ISSUE TITLE
bug: When calibrating a tip rack, retrying tip pickup changes the return height

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#5471]
# Overview
When you're calibrating a tip rack, after the pipette picks up a tip, the app asks you if it succeeded.

If you answer **No, try again,** the tip will be returned higher than normal.

# Current behavior
If I answer **Yes, save calibration:**

![IMG!UNITO-UNDERSCORE!4370](https://user-images.githubusercontent.com/3236864/80026126-75878d00-8496-11ea-81e4-814903629540.JPG)

If I answer **No, try again:**

![IMG!UNITO-UNDERSCORE!4371](https://user-images.githubusercontent.com/3236864/80026108-6ef91580-8496-11ea-919c-9334e3873a3c.JPG)

# Steps to reproduce
1. Upload the test protocol below.
1. Start calibrating a tip rack.
1. Select **No, try again.** Observe the tip return height.
1. Select **Yes, save calibration.** Observe the tip return height.

```python
metadata = {"apiLevel": "2.2"}

def run(protocol):
    tip_racks = [protocol.load_labware("opentrons_96_filtertiprack_20ul", 1)]
    pipette = protocol.load_instrument("p20_single_gen2", mount="right", tip_racks=tip_racks)
    pipette.pick_up_tip()
    pipette.return_tip()
```

I'm on v3.16.1.

# Expected behavior
The tip return height should be the same, whether I answer **Yes, save calibration** or **No, try again.**

I think the height that's used for **Yes, save calibration** is the correct one to use. That appears the same as what `return_tip()` uses in an actual run.

# See also
#5468

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535445821) by [Unito](https://www.unito.io/learn-more)

**Comment by nusrat813** [comment]
The issue does not persist in 3.17.0, API level 2.3+

**Comment by SyntaxColoring** [comment]
^ To clarify, it *does* persist in v3.17.0 *APIv2.2*, so we're keeping this issue open.
