### ISSUE TITLE
Modules: Update production SOP

### ISSUE THREAD

**Issue by sanni-t** [Opentrons/opentrons#5483]
Currently the production team is using much older versions of firmware & associated files on the temp & mag modules. This needs to change esp for mag modules since the older firmware isn't GEN2 compatible.

**Comment by sanni-t** [comment]
https://docs.google.com/document/d/1oDTQsFOEAE4LbT7Stc19WN0A4IbIfkFPu_tBlXS_9vg/edit?usp=sharing

https://docs.google.com/document/d/1Vjx6MT5opi8lOtIWu4_RfaHFi6nB7x3AiFI5suy9uRM/edit?usp=sharing

**Comment by mcous** [comment]
Closed by #115 and attached links
