### ISSUE TITLE
Add NEST 96 Well Deep Well Plate, Square Well 2.2 ml to the Labware Library

### ISSUE THREAD

**Issue by yunhodavidkim** [Opentrons/opentrons#5497]
As an Opentrons user, I would like to be able to use NEST 96 Well Deep Well Plate, Square Well 2.2 ml on my OT-2

## Acceptance Criteria
- [ ] Create a labware def for the following labware:

  - Display Name: NEST 96 Well Deep Well Plate, Square Well 2.2 ml
  - API Name: nest_96_deepwellplate_squarewell_2.2ml

- [ ] Labware definition should match manufacturer's technical diagram
- [ ] Labware should be browseable with images in Labware Library. 
- [ ] Labware should be browseable in Protocol Designer

## Resources
- Labware information the the 'Supported Labware' tab of the '[Labware Definitions](https://docs.google.com/spreadsheets/d/1hXi63baR-oBM9HwKvWDP_Aba7VWVz1AA4dn9kixXgxA/edit#gid=2128909968
)' sheet.
- The technical drawing is located here: https://drive.google.com/drive/u/0/folders/1EJGJAV8y1d6G_v9vTakb09CecYWmMULM
- Labware images will be uploaded here (not there yet): https://drive.google.com/drive/u/0/folders/1eyTLAi7XtEfuwPdTWq_2eNhN6c10ulME

**Comment by sfoster1** [comment]
The loadname will actually be "nest_96_wellplate_2ml_deep"
