### ISSUE TITLE
Thermocycler: Protocol Execution

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#5501]
As a user, I would like to be able to be able to run JSON protocols with Thermocycler steps on my OT-2. 

Acceptance Criteria
- [ ] Robot executor supports JSON protocol commands for Thermocycler
- [ ] User can manually code JSON protocols with any TC step and run it, via the Run App, on the OT-2

**Comment by IanLondon** [comment]
All tickets done!
