### ISSUE TITLE
PD: Define thermocycler profile end state

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#5519]
## Background
As a user I would like to define the state the Thermocycler holds after completing a profile

## Acceptance Criteria

This section of the form has a header and underneath is the exact same fields and layout as the Thermocycler state form. 
^^ Fields are unrelated though and do not share info

## Design
https://zpl.io/VQ53mZR

**Comment by Kadee80** [comment]
This ticket should cover the under the hood work to get the previously saved TC state and pre populate the form.
