### ISSUE TITLE
PD: Thermocycler Profile timeline list (substeps)

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#5522]
## Background
As a user, I would like to be able to see a summary of the Thermocycler profile in the timeline

## Acceptance Criteria

Thermocycler profile step named “Thermocycler Profile” (done)

**_Timeline step list includes_**
**Main section**
- Plate name
- Sample volume
- Lid temp
**Profile (collapsible)**
- Time estimate (sum of cycle times)
- Profile sub steps + cycles
**End hold state (collapsible)**
- Plate name
- Block temp
- Lid status and temp

**Hover state**
Hovering on this step will highlight the whole list item
Note that unlike Transfer steps you cannot highlight individual rows/subrows

## Design
https://zpl.io/25B0P3r

**Comment by Kadee80** [comment]
Closed via #5865 #5876 #5584 and some follow up styling prs
