### ISSUE TITLE
bug: Progress bar slowly advances even if the robot update download fails

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#5546]
# Overview

Under certain circumstances, when an update download errors out, the app UI gets into an inconsistent state where it recognizes the error but slowly advances the progress bar anyway.

![image](https://user-images.githubusercontent.com/3236864/80892713-40e7b280-8c9a-11ea-97d5-3cfda3a0255d.png)

# Logs and such

App logs are available in the Opentrons internal Slack thread.

# Expected behavior

If an error makes the download fail, the progress bar should stop advancing, and the error should be clearly communicated.

**Comment by mcous** [comment]
Update: this was actually a way simpler bug than we realized. The download progress modal had a flipped conditional bug, so the title "Download Error" is displayed only when there's **no** error. Fix will be included in 4.0.0
