### ISSUE TITLE
feat: Provide immediate feedback when setting the Temperature Module temperature through the app

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#5550]
Currently, setting a temperature through the Opentrons App goes something like this:

1. You enter the target temperature.
1. Several seconds pass where nothing happens.
1. Finally, the Temperature Module spins up and the target temperature is shown in the app.

Anecdotally, it seems like this confuses newbie users. While they're waiting in step 2,  it's unclear that the command went through. There's no feedback. So users have an "Uhhh, did it work?" moment.

# Feature request
There should be some kind of immediate feedback when setting a temperature.

I think putting up a loading spinner while waiting for the command to be acknowledged would work, for example.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535447628) by [Unito](https://www.unito.io/learn-more)

**Comment by pantslakz** [comment]
Nice catch match. Would recommend we place the spinner in the Module side bar, rather than the modal - so users can continue to do other things while the temperature change takes place.
