### ISSUE TITLE
bug: App doesn't report internal errors during labware calibration

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#5551]
# Current behavior

As @mcous commented in #4810, during calibration...

> The app collects the error from the API and does not display it.

Instead, it swallows the error silently. This makes things slightly more confusing for users. When something fails, it will look as if clicking the button in the app just didn't do anything. See #4810 for a concrete example.

# Expected behavior

If something goes wrong during calibration, that should somehow be made clear to the user.

**Comment by asogluizzo** [comment]
Check back in on this after 4.0.0 release

**Comment by SyntaxColoring** [comment]
According to @mcous, this is a problem with our RPC layer.

In v4.0.0, that RPC layer is no longer used for *deck calibration* or *pipette offset calibration*, so this should no longer be a problem for those.

It's still a problem for *labware calibration.* But labware calibration is going to be overhauled soon, including replacing its RPC layer.

**Comment by mattwelch** [comment]
This ticket is now only relevant to labware calibration (as the other calibration stuff is handled by http versus rpc). This ticket is on the way too, as the labware cal project comes to completion.

Any lack of calibration errors using the new infrastructure should get their own tickets.

**Comment by mcous** [comment]
Fixed in v5
