### ISSUE TITLE
Merry Christmas and Happy New Year!

### ISSUE THREAD

**Issue by nwags** [Opentrons/opentrons#556]
## Merry Christmas and Happy New Year!

Opentrons Team,

This is the Ghost of Christmas Past. Just kidding, but I do still have an affinity for the code base and occasionally look at the commits when I get updates. I hope you have all had a good year and have an even better new year. It's pretty cool what you guys are doing and I look forward to seeing what comes next.

Best wishes for the new year!
Nick Wagner

**Comment by mcous** [comment]
Nick,

Happy holidays to you, too, from the Opentrons team! Glad you're still enjoying the codebase; we'll do our best to make it even more enjoyable moving forward.

Hope you have a great 2018, too,
Mike (and the rest of the team)
