### ISSUE TITLE
Potential pipette collision with trash container for p10

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/opentrons#557]
## overview
The p10 pipette moves from the home position to other containers on the deck with a very low z height.

## behavior

p10 utilizes the same z-height as the p300, but it is a much longer pipette. If the tip is on the pipette while it moves from the home position it will break the pipette through a collision.

Would like more of a clearance for the p10.

## steps to reproduce
** DO NOT DO THIS WILL BREAK PIPETTE**

-Leave tip on the pipette and home the robot during a protocol
-Leave tip on the pipette after calibration

**Comment by mcous** [comment]
Pretty sure this ticket is from before the P10 was released. Given that we don't even make the P10 anymore, I'm pretty sure this must've been resolved
