### ISSUE TITLE
TC Timeline Step

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#5571]
As a user, I would like to be able to see my thermocycler ‘state change’ steps on my protocol timeline

## Acceptance Criteria
- [ ] User able to see “Thermocycler” step on timeline
- [ ] In step details, user able to see:
  - [ ] Lid Temp or ‘Deactivated’
  - [ ] Base Temp or ‘Deactivated’
  - [ ] Lid Open/Closed State
  - [ ] Labware Display Name

## Design
[- Timeline Step (Invision)](https://projects.invisionapp.com/share/VUWZT27EDJ8#/screens/414817358)

**Comment by IanLondon** [comment]
Replaced with #5694 (oops!)
