### ISSUE TITLE
Machine dwells at high current when inactive

### ISSUE THREAD

**Issue by andySigler** [Opentrons/opentrons#558]
## overview

When a protocol, or any task, is completed, the machine holds it's current position using the motors currents used for fast movements. This is inefficient and creates heat within the head and pipette enclosures.

## behavior

The driver currently cycles the `B` and `C` plunger axis to a lower current when they are inactive, while the rest of the axis (`XYZA`) remain at their high current at all times.

## steps to reproduce

Run `v3a` branch

**Comment by andySigler** [comment]
blocked by #565

**Comment by mcous** [comment]
Fixed
