### ISSUE TITLE
feat: Run App should automatically reconnect to last used robot

### ISSUE THREAD

**Issue by nickcrider** [Opentrons/opentrons#5639]
# Overview
The majority of users only have a single OT-2 robot in their lab. The run App should simplify the experience for these users by having an option to automatically reconnect to the last used robot.

### Observations
* Since the "Searching for robots..." message is only displayed for a few seconds when the app is opened (so short it's tough to get a screenshot of it), while the spinner persists for longer than that, some users interpret that behavior as the app is trying to reconnect to their robot and failing.
* Users who did not initially setup the robot and, during that process learn that you must click to connect to the robot (e.g. a walk up lab user) are confused by the current UI
* If an option to automatically reconnect to the last used robot cannot be implemented, the "Searching for robots..." message should persist until the spinner goes away, hopefully this will give users nudge to click the switch to connect to their robot.

![image](https://user-images.githubusercontent.com/64100326/81574383-f84b8b80-9362-11ea-8eb2-2dfcdad847a2.png)

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535448700) by [Unito](https://www.unito.io/learn-more)

**Comment by mcous** [comment]
No longer applicable due to the release of v6.0.0, which removes the "connect" toggle and the idea of a persistently connected robot
