### ISSUE TITLE
PD: Add thermocycler to 'unused module' export warning

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#5650]
## Background
We display these modals when users try to export a protocol where they have an unused module
![image.png](https://images.zenhubusercontent.com/5e27344f9aca8806bc57bc3b/8b16c18f-4ced-4b3f-a2fe-0d52f5796989)
![image.png](https://images.zenhubusercontent.com/5e27344f9aca8806bc57bc3b/f896d53f-8376-45b1-a3f0-b691a2174b2c)

## Acceptance Criteria
- [ ] Add a modal for when the Thermocycler is the only unused module in a protocol
- [ ] Add an unused Thermocycler to the list of potential cases in the module that covers multiple unused modules

**Comment by Kadee80** [comment]
The current logic for displaying unused modules covers TCs on the deck. 
<img width="647" alt="Screen Shot 2020-05-13 at 10 02 57 AM" src="https://user-images.githubusercontent.com/3430313/81822612-57df9d80-9501-11ea-9f3b-f16653fdfcf3.png">
<img width="651" alt="Screen Shot 2020-05-13 at 10 04 32 AM" src="https://user-images.githubusercontent.com/3430313/81822641-63cb5f80-9501-11ea-97c7-22e9651bb080.png">
