### ISSUE TITLE
feat(robot-server): Create unique error identifiers.

### ISSUE THREAD

**Issue by amitlissack** [Opentrons/opentrons#5661]
Review `Error` in `robot_server.service.models.json_api.Errors`

* [ ] The `id` field needs to be mandatory and an enumeration of all available errors created by the server.
* [ ] Exception handling middlewares populate the `id` field. 
* [ ] Choose which other fields should change from optional to required. They are currently all optional.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535449172) by [Unito](https://www.unito.io/learn-more)

**Comment by mcous** [comment]
Closing as not really applicable. This need is captured in newer code and API conventions
