### ISSUE TITLE
Basic Protocol Designer Action Functionality

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#570]
## Overview

This is an outline of how Step creation and editing will work in Protocol Designer, to inform how the engineering team should design Redux actions for PD.

This iteration will not make the Steps actually do anything, but you can create, edit, and delete them. In this iteration, there is no validation for any inputs And there is no save/load functionality. Starting simple!

## Behavior

Initially, when you get the the "main PD editor page" (Gear icon in Nav), PD starts out with an empty deck and has one Step, "Labware & Ingredient Setup", in the **Steps List**.

## Boxes and component labels

For the boxes, blue and red don't mean anything special. I just used different colors because if the boxes were all red, they overlapped and it was hard to tell them apart.

* Correction: "Header" is `TitleBar` component.
* Note: the Step Editor Form's location/size may change soon, but its contents will be form fields and buttons. It may be resizable via dragging the bottom edge. It may need to scroll later.

![image](https://user-images.githubusercontent.com/11590381/34571234-f7f3a3fa-f13b-11e7-9f78-5be36f356c62.png)

### Expanded Step Creation Button

![image](https://user-images.githubusercontent.com/11590381/34571384-6230ab6e-f13c-11e7-9c4f-6042f47f5007.png)

### Well Selection Modal

Note: this modal grays out the Step Editor Form and the Deck, but does not gray out the TitleBar, Step List, or Nav (for now. Still not decided what gets grayed out, keep it flexible).

![image](https://user-images.githubusercontent.com/11590381/34621717-3f383e7e-f218-11e7-8b08-7e3cbeda6c51.png)

#### Selected Ingredients List

As shown in the image above, the Steps List changes into the **Ingredients List** whenever the Well Selection Modal is open. The Ingredients List displays the currently selected ingredients (*full implementation is left to a later iteration*).

### Selecting Steps

Zero or one Step is selected at any given time (there's no current design for what happens when zero actions are selected, but Morgan would like that state available).

When an Step is selected, the **Step Editor Form** opens with the settings for that selected Step.

Steps can be selected by clicking items in the **Steps List**. This dispatches a `SELECT_STEP` Redux action.

### Creating Steps

Clicking the "+ Add Step" button in the Step List will make the **Step Creation Button** appear (with options like Transfer, Distribute, Mix, etc). Clicking any of these will dispatch some kind of `CREATE_STEP` Redux action. This adds the new Step to the Step List, and the new Step automatically is selected.

A new Step's form fields are empty, except the "Step Name" is prefilled.

The Step Creation Button collapses if you click off of it, so its expansion should be Redux state and not a stateful component.

The Step Creation Button is **disabled** when there are no labwares on the deck.

### Deleting Steps

You can't delete the initial "Labware & Ingredient Setup" Step. Other actions can be deleted: in the Step Editor Form, there is a "Delete" button that dispatches a `DELETE_STEP` Redux action.

As a temporary measure to not have to deal with validation, deleting one Step will delete it and all following steps.

When an Step is deleted, it's deselected.

### Editing Steps

When any Step besides "Labware & Ingredient Setup" is selected, the Step Editor Form section appears, showing settings for the selected Step.

When a user is editing an Step's settings in the Step Editor Form, the Redux store is not updated until the user clicks Save, which dispatches some kind of `EDIT_STEP` Redux action with a payload containing those saved values. The intermediate unsaved settings will be in Redux as well, because they will need to interact with the deckmap later on.

#### Well Selection process within an Step

Most Steps have an "Edit Selection" button that opens a **Well Selection Modal** when clicked. This is paired to a dropdown menu to select the labware instance. When no corresponding labware is selected, the "Edit Selection" button doesn't do anything.

In the Well Selection Modal, the user can select wells, then click the "Save Selection" button in the Well Selection Modal. This assigns a list of wells `['A1', 'A2', 'B1', 'B2']` to that part of that action (eg, to `sourceWells` / `destWells`).

### Special behavior: "Labware & Ingredient Setup" Step

When the "Labware & Ingredient Setup" Step is selected:
* Deck interactivity behavior changes
* Unlike other Steps, the Step Editor Form does not show up when "Labware & Ingredient Setup" is the selected Step.

The Deck acts as it did in the initial labware & ingredient setup prototype we built before. Labware slots allow you to add labware which then get a name, and occupied slots have hover states that let you Edit Ingredients and Remove Labware. There's also a way to Copy labware but the details are TBD.

(There is going to be some way to do multiple Labware & Ingredient Setup Steps to do things like change tipracks, swap out plates, etc, but this behavior may be different from the initial setup. TBD.)

# States Summary

* Ingredient and deck state
* Steps: arranged in a timeline
* Currently Selected Step: action reference, or `null`
* each individual Step's saved settings (initially undefined)
* unsaved Step settings (before clicking Save button in the form). This should be in Redux state because it will interact with the Deck before it is saved.
* Well Selection Modal: what labware is being selected, what wells are currently (temporarily) selected
* Current "page": the Nav on the leftmost side of the screen moves you across different panels. The panels are 1) File Settings and 2) Deck Setup + Step List. We're only implementing panel 2 in this iteration.
* Instrument state: TBD, but I think we're leaning towards an Instrument Page where you select your pipettes before getting to the main PD page. Pipettes must be selected to proceed.
* Step Creation Button expands to show actions when clicked and closes when anywhere else is clicked when it is expanded. So this should go in Redux state.

# Considerations for later on

Deleting Steps can have cascading effects on downstream Steps. For example, if you delete an Step that fills an empty well with Ingredient X, then a later Step aspirates from that well, now you're aspirating nothing. We will need a way to notify the user that deleting an Step effects some downstream Steps. There are designs around this but they are still being tested. The process of showing whether Steps are pristine, messed up, or messed-up then-corrected is still TBD.

Deleting Ingredients (and labware) similarly has cascading effects and needs downstream validation.

# Design de-risking priorities:

Not in this iteration, but very soon, we will allow user to select source and dest plates for actions by clicking them on the deck (as well as using the dropdown).

**Comment by Kadee80** [comment]
RE: `Current "page": the pages that exist are still TBD, but there's an idea that the Nav on the leftmost side of the screen moves you across different pages.`
Not terribly familiar with the PD flow, but the way it works in the app is leftmost `NavBar` changes `SideBar` content. `Sidebar`  actions/routes change larger `task` or `page` panel on the right.

**Comment by IanLondon** [comment]
https://github.com/Opentrons/opentrons/milestone/2 addresses prework, NavBar, SideBar, and Step creation/deletion. It does not address anything happening on the right side of the screen, that stuff will be left to later milestones.
