### ISSUE TITLE
feat: auto-increment apiLevel in docs

### ISSUE THREAD

**Issue by nickcrider** [Opentrons/opentrons#5758]
# Overview
For better or for worse, our users are not primarily software engineers and thus take [less than optimal approaches](https://en.wikipedia.org/wiki/Copy-and-paste_programming) to writing their own python protocols.

Reading the docs for the first time (wanting to spend more time doing science than learning syntax), a novice programmer might be tempted to copy and paste the very first (or any) block of code they see that fits their purpose.

Even though what the user has done is bad practice, we should still try and help make their lives easier by automatically incrementing the `apiLevel` in all example code in the docs to the most current version to ensure they get the best starting experience.

The current process is not automated (eg: https://github.com/Opentrons/opentrons/pull/5054 https://github.com/Opentrons/opentrons/pull/5507 ) and thus the current `apiLevel` is outdated in example code everywhere in the docs ... [even on the page containing the description](https://docs.opentrons.com/v2/versioning.html) of the current `apiLevel`!

To give our customers the best experience it's important new users start their code on the most recent `apiLevel` as it generally contains important fixes. (e.g. https://github.com/Opentrons/opentrons/issues/5448 and particularly https://github.com/Opentrons/opentrons/pull/5039 !!) even if they are using less than optimal coding practices.

# Implementation details
It is possible to specify a `rst_prolog` string in the [Sphinx configuration](https://github.com/Opentrons/opentrons/blob/edge/api/docs/v2/conf.py) and thus automatically supply the latest `apiLevel` in the build for replacement using the `|substitution|` reStructuredText syntax.

This is the currently used method to supply the `|version|` and `|release|` variables to the docs, and we should implement `|apiLevel|` as well.

We could either pull in the `MAX_SUPPORTED_VERSION` to `package.json` or just `str(opentrons.protocol_api.MAX_SUPPORTED_VERSION)` directly in the Sphinx `conf.py` to substitute the most current `apiLevel` in the example code used in the docs.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535451160) by [Unito](https://www.unito.io/learn-more)

**Comment by sfoster1** [comment]
This is a really cool idea and I'm sorry I didn't see it until now!
