### ISSUE TITLE
RFC: front-end repo consolidation

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#578]
## overview

I've been doing some research in my spare time of JavaScript projects that use monorepo structures, and following up on #576 (which blocks this RFC), there's additional consolidation we can do to make everything a little saner.

This PR is focussed on front-end (i.e. JavaScript) code, but anything that comes out of this RFC should be implemented in such a way as to not mess with nor prioritize JS over our Python projects. Given that the language is well suited for it (and we've got prior art with #567), we should default to Python for repo maintenance scripts and the like.

## current state

Right now, our monorepo looks like a bunch of directories in the repo that are effectively their own repositories:

* Good: separation of concerns
* Good: clear monorepo "ejection" path
* Bad: lots of duplicated dependencies
* Bad: lots of duplicated tooling + tooling configuration
* Bad: tools that don't play nicely with this structure (looking at you, `flow`)
* Bad: subtle differences in project layouts (increased cognitive switching costs)
* Bad: risk of dev dep version conflicts (more of a cognitive problem than a bad build problem, because everything is pretty self contained)

## possible consolidation tasks

* [ ] Development dependencies
    * Many [JS monorepos](https://github.com/facebook/react/blob/master/package.json) lift common dev deps up to the repo level `pacakge.json`
    * `jest`, `babel`, etc.
    * Keeps dev dep versions consistent across projects
    * Node module resolution is walks up the tree, so most things just keep working
        * `bin`s are the exception, because `$PATH`, but this can be worked around
* [ ] Development tasks
    * By dev tasks, I'm talking about tests, linting, and typechecking
    * With linting and typechecking, I don't see value in running these in one project at a time vs all of them
    * Tests are a little different, but with Jest's ability to run only tests affected by changed files (and our ability to specify which tests are run with CLI args if we need to isolate them) I think grouping everything into one `jest` task works pretty nicely
        * One caveat here is that we need to make sure our unit tests run quickly, which may mean separating some of our slow running integration-style tests (RPC test) out
* [ ] Webpack configuration
    * Some parts of the webpack configuration are (or should be) completely the same for all front-end projects
    * I'm thinking loader rules for sure, probably optimization plugins, maybe dev server
* [ ] Babel configuration
    * There's no reason each of our projects should have unique babel configs
    * [React's monorepo](https://github.com/facebook/react/blob/master/.babelrc) (and many others) use a single `.babelrc`
* [x] Flow config
    * Similar to the dev tasks item above
    * Flow may have some issues with monorepos, so requires additional investigation
* [ ] Other stuff? Feel free to add more in the comments (or by directly editing the issue)

**Comment by IanLondon** [comment]
* Makes sense to have dev deps at repo level
* Often I think we'll make changes to component library as we make changes to App/PD/other, so it makes sense for jest tests to all run together with the speed caveat you mentioned
* I had to copy stylelint rules to component lib, makes sense to me to be consistent with all linting and have it all in one place. Same with babelrc
* I liked the idea of the webpack named rules being at root level, and each project imports those named rules (like in App right now).
