### ISSUE TITLE
bug(app): software update from file button does not respond after an error

### ISSUE THREAD

**Issue by theosanderson** [Opentrons/opentrons#5781]
# Overview

If you manually update from file (Browse button) and something goes wrong (e.g. unsigned file, not enough space, etc.) and an error message appears, then after this pressing "Browse" again and selecting a file yields no response at all.

(Not a high priority issue)

**Comment by theosanderson** [comment]
Restarting the app restores functionality, suggesting this is indeed an app issue.

**Comment by mcous** [comment]
@theosanderson pretty sure I know why this is happening; two questions to confirm:

- Does the button work if you select a _different_ file(name) from the one that cause the error? 
- Rather than a full app restart, does navigating away from page and then back make the button work again?
