### ISSUE TITLE
test(app): Build E2E Cypress test suite for App Settings Section of the More Tab

### ISSUE THREAD

**Issue by dozercodes** [Opentrons/opentrons#5816]
# Overview

Dependent on Mike's work on #5808. Once that is complete, build Cypress tests against the web UI.

# Acceptance criteria

Test cases in suite:

* [ ] Information section: verify software version (might be tricky to source this value in an E2E test, but worth a shot)
* [ ] Privacy settings: toggle on and off and verify toggle behaves as expected
* [ ] Advanced settings, update channel: Change channel and verify it is changed (modal may or may not pop up so conditional testing will be needed here. This is a potential source of flakiness, but since the modal appears immediately after updating the dropdown, if at all, we should be fine)
* [ ] Advanced settings, enable developer tools, toggle on and off and verify toggle behaves as expected.

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535452000) by [Unito](https://www.unito.io/learn-more)

**Comment by mcous** [comment]
Stale ticket, closing
