### ISSUE TITLE
bug: newline char is mishandled in robot logs

### ISSUE THREAD

**Issue by nickcrider** [Opentrons/opentrons#5846]
# Overview

The update to 3.18.0 (and likely the introduction of the new http backend) caused the logs downloaded through the app to have the newline character rendered as the string literal `\n`

# Current behavior

This has not been fixed as of 3.19.0-alpha.0

# Steps to reproduce

`curl -X GET "http://{ROBOT_IP}:31950/logs/api.log?format=text&records=50000" -H "accept: application/json"` or download the logs through the app

you'll see a bunch of `\n`'s where there should be newlines

# Expected behavior

Logs are readable without `sed`-ing the newline char.

**Comment by sfoster1** [comment]
Well that's awful

**Comment by SyntaxColoring** [comment]
To clarify what's going on here, I think the logs are being encoded in one big JSON string. So it's "correct" that they have a bunch of internal newlines, in an unhelpful sense.

The pedantically correct way to decode it is something like:

```shell
python -c "import json; import sys; print(json.load(open(sys.argv[1])))" ~/Downloads/api.log
```

Which accounts for other escape sequences like `\t` and `\\`.
