### ISSUE TITLE
feat: move door switch feature to the same place as lights

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#5867]
We added the ability for the robot to pause if the door is open. This feature is enabled by a robot-side feature flag, which is treated identically to all the other feature flags and is in a big list on the robot settings page. However, this is a pretty big and useful thing that is frequently requested by users, so it should be more prominent and in the same area as the robot lights control.

Move the button up to that area of the app.

## Design
![Screen Shot 2020-06-10 at 3 58 38 PM](https://user-images.githubusercontent.com/2686086/84277091-51aa0480-ab33-11ea-9135-f95e95ceb2ed.png)

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535452859) by [Unito](https://www.unito.io/learn-more)

**Comment by mcous** [comment]
v6.0.0 introduced a new "Usage Settings" section of the robot settings page where the door switch pause control now lives
