### ISSUE TITLE
refactor: Put App's IPC behind a facade with WebSocket fallback

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#5904]
## overview

During normal operation, the Electron main process and the UI's renderer process communicate by sending plain JS objects back and forth using Electron's [IPC](https://www.electronjs.org/docs/api/ipc-main).

The app uses two IPC channels:
- `dispatch` - for sending Redux actions back and forth between the processes
- `log` - for sending logs from the UI process to the main process

Instead of using Electron's IPC modules directly, we should build a facade around IPC that:
- Is strictly typed
- Ignores the parts of IPC we don't use
- Has a generic "send" and "receive" interface

Once we have a "remote" facade, we can create a fallback implementation that uses WebSockets instead of IPC so that a UI loaded in an external browser can still communicate with the main Electron process

## acceptance criteria

- [ ] `app-shell` has a new `ui` configuration that tells it to avoid spinning up an Electron `BrowserWindow`
- [ ] If it doesn't launch a BrowserWindow, the `app-shell` starts a WebSocket server for IPC purposes
    - On `localhost/127.0.0.1` and some known port we select
- [ ] If the `app` detects that it is launched in a web browser, it attempts to connect to that WebSocket server instead of using Electron's `ipcRenderer` module
    - Detection can be userAgent-based and/or based on the presence of our preloaded `window`variables
- [ ] All references to IPC and WebSockets are contained to `remote` modules on the `app` and `app-shell` side for testability and ease of use

## implementation details

- IPC is available immediately at BrowserWindow launch, but a WebSocket will take some time to connect, so the client-side will likely need some buffering capabilities while the connection is being established
- The WebSocket implementation will probably need to have a keepalive system in place (simple explicit ping and pong messages on a relatively slow interval usually suffice; browsers start to shut WebSockets down when they go quiet for minutes)
- Auto reconnect would be cool but probably unnecessary at this point

**Comment by mattwelch** [comment]
No longer needed.
