### ISSUE TITLE
App CompLib Cancel/Continue modal

### ISSUE THREAD

**Issue by Kadee80** [Opentrons/opentrons#596]
## Overview

Most recent pipette screens require a user to be prompted to remove labware from the deck before initiating a tip probe. 

This ticket is to build `CancelContinueModal` in complib. 

## Reasoning

- This pattern of warning/prompting a user before continuing with calibration may be repeated within the app/PD making a case for adding this component to the component library.
- A follow up ticket will implement in app after blocking state/action refactors have been implemented?

## Steps to implement

- [x] `CancelContinueModal` UI:
     - overlay  fills parent/disabled clicks
     - centered 'box' to contain prompt children
     - title, message, cancel/continue buttons
- [x] `CancelContinueModal` Props:
     - title and description as children
     - cancel button ~href/route~ onclick
     - continue button ~href route +~ onclick

<img width="645" alt="screenshot 2018-01-15 11 02 59" src="https://user-images.githubusercontent.com/2963448/34951274-b591e926-f9e3-11e7-8c7b-22cd5b7a8fd6.png">

---

Removed `href` prop per front-end meeting - @mcous

**Comment by IanLondon** [comment]
Dunno how far off this is from what you're thinking, but a "Are you sure? Cancel/Continue" sort of modal would be very useful in PD as well. I've been using just `window.confirm` for the prototype: it comes up when user deletes labware, when user deletes an ingredient group, and when user closes the tab/window. However, I wouldn't be using routes for this now, just Redux actions.
