### ISSUE TITLE
refactor: Robot-server should use symlinks for I/O operations to make tests run faster

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/opentrons#5983]
## Overview
Previously, the robot-server was reading/writing directly to the default local directory for opentrons config files. If something goes wrong during these tests and clean up is not executed, it could leave some unwanted files hanging around.

In PR #5979, I/O operations were moved to a temporary directory. However, copying over all the files to the new temporary directory takes a long time. In the interim, we are using a 15 second sleep time which greatly increases run time for tavern tests.

## Done When
- We no longer need a 15 second sleep time for CI to pass tavern tests

**Comment by amitlissack** [comment]
Two changes:
- rather than sleep, we poll `/health` endpoint. That eliminates the flakiness of sleep.
- Found that generating `opentrons.db` was taking the bulk of the time. Optimized by reducing the number of db inserts.
