### ISSUE TITLE
refactor(api,robot-server): move `opentrons.calibration` from api to robot-server

### ISSUE THREAD

**Issue by amitlissack** [Opentrons/opentrons#5986]
# Overview

The calibration flows belong in the `robot-server`. Reasons:
- The actions in the flow are exclusively driven by HTTP requests. 
- The flow code would benefit from using models and constants defined in robot-server and vice versa
- The calibration flow is not meant to be used by customers except via HTTP requests. Hence no need for it to be in distributed package.
- Isolate pydantic to robot-server

# Acceptance criteria

- [ ] `opentrons.calibration` is moved to `robot-server`

**Comment by SyntaxColoring** [comment]
Would this affect factory (CLI) calibration?

We currently use this command to launch the tool:

```
python -m opentrons.deck_calibration.dc_main
```

**Comment by amitlissack** [comment]
> Would this affect factory (CLI) calibration?
> 
> We currently use this command to launch the tool:
> 
> ```
> python -m opentrons.deck_calibration.dc_main
> ```

It will not. It will only affect new calibration flows (ie cal check, tip length cal, etc).
