### ISSUE TITLE
bug: App doesn't prompt to update out-of-date OT-2s when computer is disconnected from the Internet

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#5992]
# Overview

When the computer has no Internet connection, the Opentrons App will not prompt you to update an out-of-date OT-2—even when it has enough information downloaded locally to know that the OT-2 is out of date.

This is especially problematic for the users who, for some reason, need to turn on Airplane Mode to connect to their OT-2s. They will never see a robot update prompt.

There are two ways of looking at this issue:

1. The Opentrons App has downloaded the latest robot update file in the background, and stored it for later. This *should* give it enough information to prompt to update any older OT-2, regardless of ongoing Internet connectivity. But the app doesn't take advantage of that.
2. Separately, we know that if the app is on v3.20.1, there must also exist a v3.20.1 *robot software version.* The app could theoretically use this knowledge to prompt to update out-of-date robots, even if it doesn't have the file downloaded. This could apply if you're a new customer who downloaded the latest app, then disconnected from the Internet, and then connected to your out-of-the-box OT-2 for the first time.

# Steps to reproduce

1. Install and open the latest Opentrons App.*
1. Check the `__ot_buildroot__` directory to convince yourself the app has downloaded the latest robot software update files. 
1. Manually put an OT-2 on an older robot software version.*
1. Close and reopen the app. Notice you immediately see an orange circle next to the robot.
1. **Disconnect from the Internet.** Close and reopen the app. Notice there's no orange circle, anymore, and the update button is grayed out.
1. **Reconnect to the Internet.** Close and reopen the app. The orange circle should be back.

*I tested this a little while back with a v3.16.1 app and v3.16.0 robot. But I expect it to be the same in newer versions.

# Current behavior

If you open the Opentrons App without being connected to the Internet, it won't prompt you to update robots, even though it theoretically should have enough information to recognize them as out-of-date.

# Expected behavior

* Once the app downloads the robot software update files, it should be able to update robots to them at any time—regardless of Internet connectivity.
* Or, the app should always identify robots with *server versions* lower than its *app version* as out-of-date—regardless of Internet connectivity.

**Comment by mcous** [comment]
The app currently needs the internet to download the master list of robot software updates to check against what it needs to download or what it has already downloaded.

See this TODO comment in code to cache that releases list and fix this ticket:
https://github.com/Opentrons/opentrons/blob/598f7e65d7ecc3aa75ba23ee9b9ac7132b3e437e/app-shell/src/buildroot/release-manifest.js#L6-L11
