### ISSUE TITLE
PD TC UX: Update tooltip for thermocycler step

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#6001]
## Background
Tooltip for Thermocycler step is outdated and should not only be referencing profiles. 
![image.png](https://images.zenhubusercontent.com/5e27344f9aca8806bc57bc3b/53ed244c-182c-4352-9be7-0e0da8049577)
![image.png](https://images.zenhubusercontent.com/5e27344f9aca8806bc57bc3b/c5beac9a-8074-4e7b-8d44-e3a246c921ff)

## Copy
"Change Thermocycler state or program a profile"

**Comment by pantslakz** [comment]
Hmm, "run profile" could be a bit confusing.

Maybe consider "Change Thermocycler state or program a profile."
