### ISSUE TITLE
feat: PD Dispensing Air gap's air volume

### ISSUE THREAD

**Issue by Kadee80** [Opentrons/opentrons#6020]
# Overview
As a PD user I expect Air gap to be dispensed as part of my dispense action

# Implementation Details

Air gap's air should be dispensed 1mm above the destination well

**1:1 Transfer**
- Dispense air gap with z offset of 1mm above the top of the well

**Multi-dispense**
- Before the first dispense of each chunk, dispense air gap with z offset of 1mm above the top of the first destination well of the chunk

**Multi-aspirate**
- TBD

**Comment by shlokamin** [comment]
closed by https://github.com/Opentrons/opentrons/pull/6401
