### ISSUE TITLE
bug: robot-server fails to start on reboot after factory-resetting labware calibration

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#6029]
# Overview

Sometimes, after factory-resetting labware calibration, the OT-2 won't successfully boot.

On one in-house robot, immediately after factory-resetting labware calibration, we saw the `opentrons-robot-server` systemd unit time out on startup. The blue light on the front of the robot blinked indefinitely, and we couldn't use the OT-2 until we power-cycled it.

On another in-house robot, immediately after factory-resetting labware calibration, we found that the `opentrons-robot-server` systemd unit takes an unusually long time to start up.

We think that factory-resetting labware calibration always makes the next startup take way longer, and, in some cases, this will be *so* long, systemd will give up on it.

# Steps to reproduce

## Steps to reproduce the longer boot time

1. Restart your OT-2.
1. Save the output of `journalctl --boot --output=short-monotonic`.
1. Factory-reset labware calibration. (Click **Advanced Settings > Reset**, then select **Labware calibration**.) Let your OT-2 restart.
1. Save the output of `journalctl --boot --output=short-monotonic` again, and compare the timings to the first time.

Tested on v3.19.0-alpha.0.

## Steps to produce the timeout

Unclear.

This only happened on Annika's robot, OT2CEP20181229A06. It was reproducible every time labware calibration was factory-reset. She was on v3.17.1.

# Current behavior

## Longer boot time 

This happened on Nick C's robot.

Normal boot:

```
[   17.313127] OT2CEP20190528A04 sh[239]: [I 15:11:11.466 NotebookApp] The Jupyter Notebook is running at:
...
[   17.423303] OT2CEP20190528A04 opentrons-api[258]: API server version:  3.19.0-alpha.0
```

After factory-resetting labware calibration:

```
[   20.081141] OT2CEP20190528A04 sh[230]: [I 19:06:51.492 NotebookApp] The Jupyter Notebook is running at:
...
[   72.996172] OT2CEP20190528A04 opentrons-api[247]: API server version:  3.19.0-alpha.0
```

## Timeout

This happened on Annika's robot.

No logs available for a normal boot.

After factory-resetting labware calibration:

```
[  100.598394] OT2CEP20181229A06 systemd[1]: opentrons-robot-server.service: Start operation timed out. Terminating.
[  100.617223] OT2CEP20181229A06 systemd[1]: opentrons-robot-server.service: Failed with result 'timeout'.
[  100.618418] OT2CEP20181229A06 systemd[1]: Failed to start Opentrons Robot HTTP Server.
[  100.624439] OT2CEP20181229A06 systemd[1]: Reached target Opentrons System.
```

A subsequent manually-issued `systemd start opentrons-robot-server` succeeded.

# Expected behavior

The OT-2 should always boot normally after factory-resetting labware calibration.

**Comment by amitlissack** [comment]
I've made a modification that reduces the time to create `opentrons.db` from 2 seconds to about 300ms. 

The change is to insert rows in bulk rather than individual rows. That means there are 58 inserts into `ContainerWells` vs 3404. 

I'll look for more optimizations.
