### ISSUE TITLE
Protocol Designer project: Use same make commands as other JS projects

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#605]
## overview

Right now protocol designer doesn't have the same `make` commands as component library and app. 

## behavior

The basic commands should match for a smoother developer experience.

Eg:

`make dev` - Run dev server (right now you have to `npm start`)
flow-types installation (TODO)

**Comment by mcous** [comment]
👍 

At some point can we discuss how this could relate to #578? Also, I know @btmorr has expressed trepidation about remaining with `make` as a tool, especially in relation to cross-platform compatibility.

**Comment by IanLondon** [comment]
@mcous Oh right, I thought there was a reason I was putting off this little chore

**Comment by IanLondon** [comment]
`make dev` was added
