### ISSUE TITLE
feat: make it easier for support to see a user's deck calibration

### ISSUE THREAD

**Issue by nickcrider** [Opentrons/opentrons#6055]
# Overview

With the introduction of the deck calibration check feature, many more users are coming to support for issues involving deck calibration. Currently, the process for support to investigate the user's deck calibration is manual.

# Implementation details

Support currently asks users to `cat /data/deck_calibration.json /data/robot_settings.json >  /var/lib/jupyter/notebooks/troubleshooting.json ` and then download the resulting file from the Jupyter interface.

Rather than having the user enter these commands the `robot-server` should provide an endpoint and make this process as easy as downloading the `api.log` and `serial.log` files through the app. Ideally troubleshooting.json is part of this package.

This will improve our users (and our Support team's) lives greatly.

# Acceptance criteria

The user should not have to access the command line of the instrument in order to send deck_calibration.json or robot_settings.json information to the support team.

**Comment by sfoster1** [comment]
Add a download robot calibration button per [design](https://www.figma.com/file/sbjDtrRzqd46SEx1NG5QHD/Calibration-Overhaul-Deck-Calibration?node-id=31%3A638). 

The download button should prompt to save ROBOTNAME-deck-calibration.json
