### ISSUE TITLE
PD: Fix how scrolling and expanding the "+ STEP" button interact

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#6056]
## Background
![image.png](https://images.zenhubusercontent.com/5e27344f9aca8806bc57bc3b/b128fbb5-18de-4ca8-9d97-1c1c1541c60c)

@Kadee80 What are our options here? This is the issue that came up on our call with Andy where he couldn't figure out how to add a new TC step.

**Comment by IanLondon** [comment]
My attempt #7083 isn't good because

![image](https://user-images.githubusercontent.com/11590381/101687969-462f8b80-3a39-11eb-9377-f3f17b7e4c22.png)
