### ISSUE TITLE
TC PD UX: Sidebar labware name hover state repeats labware name

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#6061]
## Background
If you you hover on rows of the Thermocycler and Temperature steps that contain labware names, the step name repeats. This does not happen in magnetic module steps. 
![image.png](https://images.zenhubusercontent.com/5e27344f9aca8806bc57bc3b/f2470520-f0e5-4945-89c6-3dbf033df407)

## Acceptance Criteria
- [ ] Only display one name per labware in tooltip. Nickname if a labware has one, labware type if labware has no nickname. (aka whatever the name shown on the deckmap is)
- [ ] Fix for Row 1 of Thermocycler steps
- [ ] Fix for the sub row in Thermocycler Ending hold
- [ ] Fix for Row 1 of Temperature steps

**Comment by IanLondon** [comment]
Should it show the labwre name, or the nickname?

Currently, if the labware nickname is "nick":

![image](https://user-images.githubusercontent.com/11590381/86799585-1cb0a500-c040-11ea-8287-76b9cc270809.png)
