### ISSUE TITLE
TC PD UX: Update copy for TC profile radiobutton

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#6065]
## Background
As a user I want to use the "program a thermal cycling profile" for use cases that don't include any cycling. 

Adding some screenshots to add the context of our existing style of copy:

![image.png](https://images.zenhubusercontent.com/5e27344f9aca8806bc57bc3b/a16fc9c8-fd10-4040-9ddf-9b77d7a04300)
![image.png](https://images.zenhubusercontent.com/5e27344f9aca8806bc57bc3b/3b674747-4dd2-4cbf-96cb-376198954ece)

## Acceptance criteria
- [ ] Update copy

## Copy
"Program a Thermocycler profile"

**Comment by pantslakz** [comment]
how about "Program a Thermocycler profile"?

Run in this instance feels strange, because the user is instructing the machine - not running it.

**Comment by howisthisnamenottakenyet** [comment]
@pantslakz For other steps we use copy that's I think from the perspective of the protocol, not the user. 
Transfer: Move liquid to and from wells/tubes
Mix: Mix contents of wells/tubes
Temperature: Change to temperature, or Deactivate module
