### ISSUE TITLE
TC PD Bug: TC change state form does not remember existing TC state if there is a step between two TC steps

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#6066]
## Dev Note

Related to #6068

## Background
TC step remembers its existing state in the “Change Thermocycler State” part of the form *except* when there are other steps between your current step and the one where you last defined its state

![image.png](https://images.zenhubusercontent.com/5e27344f9aca8806bc57bc3b/70d801c2-3924-4875-bd7a-d54cd5a87fa9)

**Comment by umbhau** [comment]
@howisthisnamenottakenyet potentially duplicate of #6068
