### ISSUE TITLE
feat(api): tell user if API thinks it's a v1 or v2 protocol

### ISSUE THREAD

**Issue by nickcrider** [Opentrons/opentrons#6074]
# Overview

The 3.19.0 update removed the print statements from the simulate output per some user requests (#5847). This feature request proposes a single print statement is added back in to inform the user of the API version.

# Implementation details

Some changes were made to block the import of v1 modules in v2 protocols (#5859), but this left a weird edge case (#6015). Rather than try and stay one step ahead of the user in guessing all of the possible ways to malform a protocol, the API should just print the `apiLevel` it has decided to use for the protocol in question and let the user figure out why nothing else happens in their simulation.

A positive side effect is that this print statement might help nudge users towards considering the `apiLevel` they have chosen for their code.

# Design

Simulating
```python
from opentrons import robot
def run(protocol):
    pipette1 = protocol.load_instrument('p1000_single_gen2', 'left', tip_racks=nonexistant)
    pipette1.pick_up_tip()
```
results in the following output from the simulate utility
```
$ opentrons_simulate bad_protocol.py
Executing using API Version 1.0

$
```
# Acceptance criteria

API version is displayed to users when simulating

**Comment by mcous** [comment]
No longer applicable due to PAPIv1 end-of-life
