### ISSUE TITLE
feat(app): remove legacy HTTP v1 switch from advanced settings

### ISSUE THREAD

**Issue by nickcrider** [Opentrons/opentrons#6079]
# Overview

The legacy HTTP v1 API is depreciated and the API server can no longer communicate with modern versions of the app when the v1 HTTP server is enabled.
![image](https://user-images.githubusercontent.com/64100326/86818255-6353ce80-c043-11ea-9709-304e6710633d.png)

Some users will mistake the switch in the app as a way to switch the robot to PAPIv1, or will flip the switch simply because they are curious and accidentally break the connectivity with their app. The only way to resolve this is `rm /data/feature_flags.json` on the robot terminal.

As this GUI switch is only needed in rare circumstances, it should be removed from the app.

# Implementation details

If the switch can't be removed, the text should at least be changed to **WARNING: Enabling will prevent your version of the app from connecting to this robot again!**

# Acceptance criteria

The HTTP v1 API switch is removed from the app GUI or a strong warning is added.

**Comment by amitlissack** [comment]
Sorry. This is completely an oversight on my part. Will fix asap.
