### ISSUE TITLE
feat: display link to jupyter notebook in robot settings page

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#6102]
# Overview

The process by which we [direct users to get to Jupyter](https://support.opentrons.com/en/articles/1795367-running-the-robot-using-jupyter-notebook) is a little involved. Since our instructions already involve sending users to the app to retrieve the IP address of the robot, would it make more sense to put a link on the robots page to open Jupyter in the user's browser?

This has come up before internally (probably externally, too), but I couldn't find a ticket for it so here we are.

# Acceptance criteria

- [ ] Robot settings page includes a button that will open Jupyter notebook in the user's browser
- [ ] The link will use the "best" IP address available for the robot (e.g. use U2E if it is available)
- [ ] Clicking the link sends an analytics event

# Implementation details

- Robot page has a link to open the robot's Jupyter notebook in an external browser
- ~Link is clickable regardless of the health status of the API server and/or update server~
    - Note: current CSS for the disable logic in the `<Card>` component makes this difficult
- IP in link driven by same IP preference logic (wired over wireless, etc) as other connectivity logic
 
# Proposed design

I think the "Advanced Settings" card makes the most sense, but the link could go anywhere:

![2020-07-09 17 47 48](https://user-images.githubusercontent.com/2963448/87094250-94332f80-c20c-11ea-9071-e6cab9655287.gif)

**Comment by SyntaxColoring** [comment]
This sounds great to me!

An implementation detail: You can connect to Jupyter over either Wi-Fi or USB. I don't think this distinction is generally meaningful to users. But the button should probably favor USB, if it's available.
