### ISSUE TITLE
Update to recommended labware for Temp module

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#6122]
## Background
A labware that is in our PD labware list is not showing up when the list is filtered for recommended Temperature module labware. 
It is listed as recommended in our master doc: https://docs.google.com/spreadsheets/d/1hXi63baR-oBM9HwKvWDP_Aba7VWVz1AA4dn9kixXgxA/edit#gid=170566092

## Solution ambiguity
Should we be adding labware definitions to this list manually or just filter for all labware defs on an aluminum block?

@umbhau @IanLondon

**Comment by IanLondon** [comment]
Did we address this last-month-ish or are there remaining labware?
