### ISSUE TITLE
feat(api): Include self-resolution guidance for multichannel transfer error

### ISSUE THREAD

**Issue by nickcrider** [Opentrons/opentrons#6140]
# Overview

When writing PAPIv2 protocols with 384 well plates, users who haven't bumped their `apiLevel` to 2.2 or greater will hit an error when they attempt to access the second row of the plate (#4678).

https://github.com/Opentrons/opentrons/blob/8271b0fb96d9dc1ddddd09aec90ca42329958656/api/src/opentrons/protocol_api/transfers.py#L786

To resolve this, users writing new protocols simply need to set the correct apiLevel. The error raised should say this.

# Design

A proposed error message follows
```
RuntimeError: Invalid {id} for multichannel transfer: {old_well_list}. 
The multichannel can only access rows 1 and 2 of 384-well plates.
If this is a valid 384-well plate, try using API Version 2.2 or greater.
```

**Comment by sfoster1** [comment]
I think this may not be the root of the error - do we have a minimal reproducing case protocol?

The line called out here I think only executes in API version 2.2 or greater and is intended to catch cases where the protocol requests a transfer including row 3 or subsequent of the plate.

**Comment by nickcrider** [comment]
Good catch! This ticket was opened in error.

Looking at my test case again, #5085 is the underlying issue.
