### ISSUE TITLE
bug: Labware Library definition for nest 2mL deep well plate

### ISSUE THREAD

**Issue by bndo** [Opentrons/opentrons#6171]
# Overview
Our labware definition for the NEST 96 Deepwell Plate 2mL states that it has a `U-bottom` it should be updated to match [NEST's product pages](http://www.cell-nest.com/page94?product_id=101&_l=en). 

# Steps to reproduce

https://labware.opentrons.com/nest_96_wellplate_2ml_deep/

# Current behavior

Our definition currently states `U-bottom` instead of `V-bottom`.

# Expected behavior

Both the text and the image need to be updated to be a `V-bottom`

**Comment by IanLondon** [comment]
Blocked until we have labware versioning :(

**Comment by IanLondon** [comment]
After convo, we decided that it's OK to mutate the definition because we're only changing metadata (`groups[i].metadata.wellBottomShape`)
