### ISSUE TITLE
bug: Consecutive 'Pause' commands skip to last command for protocol modal

### ISSUE THREAD

**Issue by tanaes** [Opentrons/opentrons#6172]
# Overview

I'm writing a protocol that has one step that requires the user to perform multiple interventions without intervening robot activity. I'd like to have three consecutive `protocol.pause()` steps, each describing one of the atomic steps for the user and requiring a "Resume" click as acknowledgement. 

Currently, though, these consecutive pauses just skip to the last one. 

# Steps to reproduce

On my machine, this code reproduces the behavior:

```{python}
from opentrons import protocol_api
from numpy import ceil

metadata = {'apiLevel': '2.5',
            'author': 'Jon Sanders'}

def run(protocol: protocol_api.ProtocolContext):

    protocol.pause('Click one')

    protocol.pause('Click two')

    protocol.pause('Click three')

```

# Current behavior

Only displays an interaction modal for the last pause command in a series. 

# Expected behavior

Should require interaction for each pause.

**Comment by SyntaxColoring** [comment]
Sorry @tanaes, just saw this one. Thanks for reporting it. I've added this to our internal tracking for us to look into.

**Comment by mcous** [comment]
Closing in favor of #8489
