### ISSUE TITLE
feat(robot-server): Create README describing how to run a protocol via HTTP endpoints 

### ISSUE THREAD

**Issue by amitlissack** [Opentrons/opentrons#6191]
An experiment in readme driven development. 

Can we describe how interaction protocol sessions should be in a readme file before development? 

The following work flows must be described:
- [ ] Uploading a protocol. 
- [ ] Creating a protocol session
- [ ] Running, pausing, resuming, simulating.
- [ ] Getting protocol metadata and progress
- [ ] Getting notifications of progress
- [ ] Understanding error conditions/states
- [ ] Cleanup

**Comment by mcous** [comment]
README started + fleshed out at https://coda.io/d/Protocol-Sessions-Initiative_dhJvwM_pE5L/Protocol-Upload-Readme_su_qn#_lueo9

Closing this issue and continuing to document as we go
