### ISSUE TITLE
App crashes during calibration if no single-channel pipette is present

### ISSUE THREAD

**Issue by btmorr** [Opentrons/opentrons#622]
## overview

When trying to calibrate labware for a protocol with no single-channel pipette, the app crashes

## behavior

**Currently:** Calibration flow will crash if no single-channel pipette is configured in the protocol (this is true even if an instrument object is created for a single-channel pipette, if that pipette is not used for any actions)

**Desired:** Calibration should be able to use whatever instruments are present to calibrate labware. Example valid configurations:

- Single channel on right or left mount, none on opposite (currently works)
- Multi channel on right or left mount, none on opposite (currently broken)
- Multi channel on right or left mount, single channel on opposite (currently works)
- Single channel on both mounts (currently works)
- Multi channel on both mounts (currently broken)

## steps to reproduce

Create a protocol with no single-channel pipette actions, and attempt to calibrate labware

**Comment by btmorr** [comment]
Related to #553

**Comment by btmorr** [comment]
May have actually been taken care of by #572? @mcous can you confirm?

**Comment by mcous** [comment]
Yup, it was fixed in #572
