### ISSUE TITLE
App TipProbe Panels should Match Designs

### ISSUE THREAD

**Issue by Kadee80** [Opentrons/opentrons#623]
## overview

Current Designs now call for a single tip probe panel separate from the pipette info area which was addressed in #595. The next step is to update the `TipProbe` container and components to match the design screens and implement cancel continue modal.

## Currently in App:
<img width="600" alt="screen shot 2018-01-17 at 11 30 40 am" src="https://user-images.githubusercontent.com/3430313/35054178-f7866dec-fb79-11e7-82ce-732dc87f1b47.png">

## Updated Design:
- `TipProbe` panels can receive a 1 or 2 column layout based on presence of `onClick` prop.  (Button in left column, or entered Spinner)
<img width="300" alt="screen shot 2018-01-17 at 11 32 41 am" src="https://user-images.githubusercontent.com/3430313/35054272-29e19a14-fb7a-11e7-93dc-decdd4cb7af0.png">
<img width="300" alt="screen shot 2018-01-17 at 11 34 54 am" src="https://user-images.githubusercontent.com/3430313/35054407-7a3aa08c-fb7a-11e7-915a-f199eb90594c.png">
- Cancel/Continue modal displays on first tip probe, or on return to tip probe from labware setup
<img width="300" alt="screen shot 2018-01-17 at 11 33 16 am" src="https://user-images.githubusercontent.com/3430313/35054328-445980be-fb7a-11e7-879d-c7a701cee4d4.png">

## steps to implement

- [x] Display updated panels based on robot constants:   UNPROBED, PREPARING_TO_PROBE, READY_TO_PROBE, PROBING, PROBED
- [x] Utilize comp lib css exports for all new color/border/typography vars while removing @values
- ~[ ] Implement Cancel/Continue modal on `deckPopulated=true` state atom. #594 partially blocks this~

**Comment by Kadee80** [comment]
This issue is in PR now. There is a bit of state work needed to get the probe panels to match designs for confirm tip removed, and display a [next] screen before setting probed to true.

**Comment by mcous** [comment]
Closed by #652
