### ISSUE TITLE
bug: app cannot load custom labware for JSON protocol schema 4

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#6235]
## overview

The app cannot load custom labware into its deckmap from a v4 (or higher) JSON protocol

## steps to reproduce

1. Load v4 JSON protocol with custom labware
2. Navigate the app to calibration
3. Notice the deckmap shows custom labware instead of a render

## expected behavior

Custom labware should render

## notes

The app has a selector to pull the labware definition out of the JSON protocol definition. It is hard-coded to only work if the schema is exactly v3:

https://github.com/Opentrons/opentrons/blob/c23e980395157ffb0b9cbf8f44020ceb5d2209f0/app/src/protocol/selectors.js#L78-L103

**Comment by IanLondon** [comment]
Reminder: should also work with schema version 5 which is coming very soon.

Also consider future versions -- can Run App support them before they're written, or does Run App need to be limited to a max schema version?
