### ISSUE TITLE
Create SOP for flashing a Robot SD card

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#6268]
## overview

Our robot provisioning SOP still uses an initial Balena install to set up new robots. We need a SOP for the factory to remove Balena from this process and flash our [Robot OS](https://github.com/Opentrons/buildroot) directly to an SD card.

## acceptance criteria

The SOP must include the following:

- [x] Station setup (OS, installed software, etc.)
- [x] Robot OS files to use and how to get them
- [x] Instructions on how to flash the SD card
- [ ] Opentrons/buildroot README includes / links to the SOP 

### stakeholders

- The primary users of this SOP will be our factory team
- Secondary stakeholders are the HW team and the SW team
- In an ideal world, a variant or view of this SOP could be available for power-users wishing to (re)provision their own devices

## notes

There is a large amount of pre-existing work for this dating back to the original Robot OS switchover. @sfoster1 is a good person to ask in terms of surfacing that work if you can't find it via Slack

**Comment by theosanderson** [comment]
> In an ideal world, a variant or view of this SOP could be available for power-users wishing to (re)provision their own devices

+1 – I had some issues here
