### ISSUE TITLE
API server doesn't expose info for which instrument is associated with a tiprack

### ISSUE THREAD

**Issue by btmorr** [Opentrons/opentrons#627]
## overview

In order to allow the app to select the "correct" instrument for calibrating a tiprack (e.g.: the instrument that will use tips from that tiprack), the app has to be able to figure out which instrument is associated with which tiprack

## behavior

**Desired:** the API should provide a method during calibration that will accept a tiprack identifier (either a unique id that is shared between the app and the api, a slot number, or other identifier that will uniquely identify a tiprack, even if multiple tipracks of the same type are present in the deck setup) and respond with an identifier for the associated instrument (a similarly unambigouous identifier, even if two instruments of the same type are present--mount would be a possible choice).

**Comment by mcous** [comment]
Looks like the API does actually report this information. `sesssion_manager.session` looks like:

```js
{
  // ...
  containers: Array<{
    // ...
    instruments: Array<{
      // ..
      mount: string
      // ...
    }>,
    // ...
  }>,
  instruments: Array<{
    // ...
    containers: Array<{
      // ..
      slot: string
      // ...
    }>,
    // ...
  }>,
  // ...
}
```

Closing this issue and unblocking #621 accordingly
