### ISSUE TITLE
Ensure factory test scripts run on latest software version

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#6270]
## overview

The monorepo has a set of Python scripts in `api/src/opentrons/tools` that are used by the factory to provision new OT-2's. These tools are not known to work on the latest software release (3.19 / 3.20). The last version they are known to work on is **3.14.0**.

We will eventually remove these scripts from the monorepo in favor of a standalone repo/application for factory work, but in the mean time, we need to ensure these scripts run on our latest software.

## acceptance criteria

- [ ] Test and modify scripts in `api/src/opentrons/tools` as necessary
- [ ] Ensure any changes conform to existing SOP for these scripts
    - This is a stopgap for replacing these scripts with a more concrete SOP and station

## notes

@b-cooper, @Laura-Danielle, and @sanni-t have all worked on and/or looked into these scripts in the context of having them run on the latest version of software, and should be consulted

**Comment by amitlissack** [comment]
Current factory test scripts do work on 3.20
