### ISSUE TITLE
bug: Pipette doesn't fully deliver the amount of liquid as requested.

### ISSUE THREAD

**Issue by ffffffrank** [Opentrons/opentrons#6311]
For example, pipette.consolidate (400, plate.cols('2'), plate.wells('A1')))
The pipette would only deliver 100 or 200 microL sometimes, RANDOMLY. And leave the remaining liquid in the tip.

Sometimes, the pipette would only aspire tiny amount of liquid compared to what's being asked. e.g. 
pipette.aspire (400, plate.cols('2'), plate.wells('A1'))), it would only aspire 50 microL, it happens randomly.

**Comment by MarcMarc94** [comment]
Which pipettes are you using? We had/have similar problems with the Gen1 pipettes. We replaced one of them and the problem was gone.

**Comment by SyntaxColoring** [comment]
Hey @ffffffrank, thanks for opening this issue. As @MarcMarc94 mentioned, this sounds like it could be a problem with the pipette. (But without more details, I can't be sure.)

If you haven't already, please reach out to us at support@opentrons.com, and we'll work with you to troubleshoot.

**Comment by ffffffrank** [comment]
> Which pipettes are you using? We had/have similar problems with the Gen1 pipettes. We replaced one of them and the problem was gone.

I have Gen1 pipette.
