### ISSUE TITLE
Deck Calibration: End Flow (robot side)

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#6353]
Implement the robot side of the [end screen](https://www.figma.com/file/sbjDtrRzqd46SEx1NG5QHD/Calibration-Overhaul-Deck-Calibration?node-id=46%3A10)

When the end screen state exits, it should
1. drop the tip back in the place it came from
2. save the new deck calibration attitude matrix
3. end the flow

**Comment by ahiuchingau** [comment]
Closing this ticket as (1) the matrix will be saved right after the cross in slot 7 is calibrated (see #6389) and (2) dropping the tip when `exit_session` is called has already been implemented (#6282).
