### ISSUE TITLE
App Split LabwareList into TipwareList and LabwareList

### ISSUE THREAD

**Issue by Kadee80** [Opentrons/opentrons#637]
## Overview
Currently in the App all labware is reduced within the `LabwareList` container and renders a `TitledList`  for all `LabwareItems` with the grouped tipracks first.

New `SetupPanel` sidebar designs call for the separation of `LabwareList` into 2  titled lists,  1 for tipracks and 1 for all other labware. 

These lists will need to allow for disabling of individual `TipRackListItems` as well as disabling entire `TitledLists`. 
- For MVP, once a tiprack is calibrated, is can not be revisited. (disable individual item)
- Labware  titled list is disabled until all tipracks are confirmed.
- Once all tipracks confirmed, tipracks titled list is disabled.

These 2 TitledLists will need to be grouped and titled via an upcoming new comp lib component called `SidbarGroup` (#657).

<img width="164" alt="screen shot 2018-01-19 at 9 15 50 am" src="https://user-images.githubusercontent.com/3430313/35154758-66962512-fcf9-11e7-9e21-dd6dafe7301a.png">

## Steps to implement
- [ ] Render tipracks and other labware as 2 different titled lists.
~- [ ] Update TitledList to include `isDisabled` prop.~ #654 
- [ ] Update styles to match designs (headings in particular
- [ ] Wrap labware sidebar section in `SidebarGroup` (this is blocked until `SidebarGroup` exists, #657)

**Comment by Kadee80** [comment]
@pantslakz the current app has some alert/warning text explaining that:
- labware is disabled until pipettes are probed 
- other labware is disabled until tipracks are calibrated. 

This disabling of entire groups, lists, or list items seems pretty clear. Are we removing these alerts?

**Comment by pantslakz** [comment]
@Kadee80 yes we can remove these. In place of that text, we now have the hover tip as shown below:

(to show when user hovers over greyed out options)
![screen shot 2018-01-22 at 2 54 15 pm](https://user-images.githubusercontent.com/2686086/35224078-146507a8-ff84-11e7-8e0f-5b0d8ca9c147.png)
