### ISSUE TITLE
bug: HTTP API returns datetime strings without timezone info

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#6374]
## Overview

- We have several HTTP endpoints that return datetimes
- The API serializes datetimes in JSON as ISO8061 strings
- According to our own conventions, all datetimes should be treated as UTC times
- According to ISO8061, **datetimes without timezone info are to be treated as local time**
- Many of our datetimes are all coming back **without timezone info**

See [Time zone designators](https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators) in the Wikipedia article for ISO8061 for more info. This is a problem because if you pass a datetime string without timezone info into a spec-conforming date library (like `Date` in an ES2015 engine), it will treat it as local time and give you the wrong date.

## Steps to reproduce

Try to hit an endpoint with datetimes, like `GET /labware/calibrations`. You'll get something back like:

```js
{
  "id": "ed323db6ca1ddf197aeb20667c1a7a91c89cfb2f931f45079d483928da056812",
  "type": "LabwareCalibration",
  "attributes": {
    "calibrationData": {
      "offset": {
        "value": [ 0.0, 0.0, 0.0 ],
        "lastModified": "2020-08-17T21:18:49.832437"
      },
      ...
    },
    ...
  }
}
```

Notice that `2020-08-17T21:18:49.832437` **does not end with any timezone info** (e.g. `Z` or `+00.00`). If you were to try to construct a date on the client side, you would get the wrong time, because it would adhere to the ISO spec and create the date in local time:

```js
> var date = new Date('2020-08-17T21:18:49.832437')
undefined
> date.toISOString()
'2020-08-18T02:18:49.832Z'
```

## Root cause + fix

We create most of our datetimes in Python with [`datetime.utcnow`](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow), which creates a timezone-less naive datetime object set to the current UTC datetime.

According to the Python docs:

> **Warning:** Because naive `datetime` objects are treated by many `datetime` methods as local times, it is preferred to use aware `datetimes` to represent times in UTC. As such, the recommended way to create an object representing the current time in UTC is by calling `datetime.now(timezone.utc)`.

Accordingly, we need to change all instances of `datetime.utcnow()` to `datetime.now(timezone.utc)` so that we are creating datetimes that are aware that they represent time in UTC and will thus serialize to a dateime string including timezone info. You can try this out for yourself in the REPL

```python
>>> from datetime import datetime, timezone
>>> datetime.utcnow().isoformat()
'2020-08-17T20:31:29.776284'
>>> datetime.now(timezone.utc).isoformat()
'2020-08-17T20:31:39.497474+00:00'
```

**Comment by amitlissack** [comment]
Dang. Good catch!
