### ISSUE TITLE
App: Reusable Calibration InfoBox

### ISSUE THREAD

**Issue by Kadee80** [Opentrons/opentrons#638]
## Overview
Updated designs share a pattern for all `TipProbe` panels and `LabwareCalibrationPrompt` (before calibrating and  and once calibrated). 

- bordered div
- header with icon (checked unchecked)
- message

The content/children after that point diverge. This ticket is for the creation of a shared InfoBox with the above elements generated by props. All other diagrams, icons, buttons will be rendered as children.

<img width="590" alt="screen shot 2018-01-19 at 9 50 19 am" src="https://user-images.githubusercontent.com/3430313/35156485-fac0c5e4-fcfe-11e7-94f9-d0fa185d8946.png">
<img width="587" alt="screen shot 2018-01-19 at 9 49 45 am" src="https://user-images.githubusercontent.com/3430313/35156498-03f2df62-fcff-11e7-84eb-7876db5d247a.png">
<img width="587" alt="screen shot 2018-01-19 at 9 49 59 am" src="https://user-images.githubusercontent.com/3430313/35156503-059997c0-fcff-11e7-8aec-baa39ac5f51f.png">

## Steps to Implement

- [x] Implement generic CalibrationInfoBox with the following props
    - title
    - icon
    - className
    - optional message 
    - children

**Comment by mcous** [comment]
Closed by #652
