### ISSUE TITLE
RFC: JSON Protocol Schema v6

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#6399]
# Overview

This schema bump is motivated by the addition of a new command, `dispenseAirGap`.

Why do we need `dispenseAirGap` when we already have `dispense`? Both `dispense` and `dispenseAirGap` commands will probably call the same `InstrumentContext.dispense` function in the Python executor. The only difference is semantic. This semantic distinction is important in at least 2 places:
1. Liquid tracking. PD does liquid tracking based on the atomic commands alone, which is a system design goal of these commands. We'd like other consumers of protocols to be able to simulate liquid tracking with just the atomic commands and an initial liquid state. When air gets involved, things get complicated. It's a very hard problem in liquid tracking to determine what's going on in the tip in real life when air gaps are involved. In multi-aspirate, we aspirate liquid, then air, then liquid, then air, forming a layered parfait in the tip. These bubbles might collapse or not depending on factors we can't simulate anytime soon. So it's hard to determine whether `extend pipette plunger 5uL` would put air or liquid in the destination. The best we can do is distinguish though imperative semantics: aspirating air (`airGap` command) vs aspirate liquid (`aspirate` command) gives us that on the aspiration side, we need a similar `dispense` (which should imply liquid) vs `dispenseAirGap`.
2. Protocol inspection. In PD, users can expand every step in the step list to show rows of atomic commands that are involved in the action. We don't want to show "dispense air gap" the same as we show "dispense liquid", because those have different meanings to the protocol -- it's more than the z-offset, it's really a different operation. Perhaps one day the atomic commands will be represented in the Run App's run log in a similar hierarchical manner, so this could be useful for more than PD.

## Alternative

We also discussed adding a new parameter to `dispense` like `isAir: boolean`. But it seems cleaner just to make a new command. This also gives us parity with `aspirate : airGap, as dispense : dispenseAirGap`.

# Schema details

The new command would have the same params as aspirate/dispense/airGap commands, but have the name `dispenseAirGap`.

# Side note: temporary PD workaround

To make liquid tracking work in PD with air gap, we're using the `dispenseAirGap` command in PD's command timeline. But to avoid getting PD release blocked by a robot stack release to support this v6 schema, we have a hack where PD will swap out all `dispenseAirGap`'s for equivalent `dispense` commands before saving the file.

# Additional consideration

From convo with @shlokamin 

Do we want to change `#/definitions/pipetteName` to an enum of all pipette names, with the plan to do another schema bump whenever we add new pipettes to pipetteNameSpecs? The `pipetteName` JSON schema type was originally an enum in JSON schema v2, but we changed it to "string" in v3+.

After making changes, review the [schema bump checklist](https://github.com/Opentrons/opentrons/pull/6285) and make sure that all criteria are fulfilled.

# New commands?? TBD

- return tip to tiprack?
- tip positioning in x/y/z (more??) with the goal to have full positioning functionality relative to a well (for all pipetting commands)? This would enable Python -> JSON atomic commands eg in Protocol Engine.
- Heater/Shaker commands!?!

**Comment by IanLondon** [comment]
From @mcous in #6463 (just copy+pasting so it's not lost):

For the purposes of system alignment, we should also be discussing changes on both ends to match ProtocolEngine commands with JSON Protocol commands. Currently, there is a one-to-one mapping, so complete alignment should be technically feasible. In advance of a more full audit, currently implemented ProtocolEngine commands may be found here:

- Commands: [`api/src/opentrons/protocol_engine/commands`](https://github.com/Opentrons/opentrons/tree/edge/api/src/opentrons/protocol_engine/commands)
- PE > JSON command mapping: [`api/src/opentrons/protocols/runner/json_proto/command_translator.py`](https://github.com/Opentrons/opentrons/blob/edge/api/src/opentrons/protocols/runner/json_proto/command_translator.py)

(As of the time of writing for this comment, the only thing to pay attention to is the payload shapes, currently named `SomeCommandRequest`). The shape of everything else is currently in flux as we simplify things to hook into the HTTP API)

**Comment by mcous** [comment]
Closed by #8271
