### ISSUE TITLE
CSS Fixes for Deck and Plate component

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#645]
## overview

This issue is a stub, reminding me to fully ticket out the problems I commented in on PR #633 

- [ ] Plate label font size
- [ ] Deck `#roundSlotClipPath` no longer works for PD's Add/Copy/Remove overlays
- [ ] Hovering over labware name overlay mysteriously indefinitely hides the overlay even when you mouse off it

**Comment by mcous** [comment]
We should add viewbox corrections to this list, too

**Comment by IanLondon** [comment]
@mcous are there newer tickets for this?

**Comment by mcous** [comment]
@IanLondon don't think so! The font-size and clip-path stuff is still in need of work I think (dunno about the hover stuff). We can keep this one around or close it in favor of a new refactor ticket when we have one

**Comment by IanLondon** [comment]
@b-cooper is working on deck refactor, this ticket is out of date
