### ISSUE TITLE
test: API unit tests keep too many files open

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#6487]
## overview

The API tests (`make -C api test`) open too many files, which seems to consistently cause tests to freeze up if the OS's open file resource limit is exceeded.

- All tests that open a file description should make sure that they close that file when they're done
- Any test that opens many files should be careful to open a "small" number at a time

## steps to reproduce

I've been able to consistently reproduce this on macOS, where **the default open file limit is 256**.

1. Set the open file limit to the default value in case you've overridden it already to work around this issue
    - `ulimit -n 256`
2. Try to run the API tests (or even a subset of the API tests)
    - `make -C api test`
    - `cd api && pipenv run pytest tests/opentrons/protocol_api`

**Comment by amitlissack** [comment]
Root cause is `HardwareManager` creating ephemeral `ThreadManager` objects and leaking threads.
