### ISSUE TITLE
Thermocycler: Detailed status and errors

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#6541]
The thermocycler module has some fault detection capability for problems originating in hardware - burned out thermistors, bad seals, and the like. We currently don't really expose that capability anywhere; when the thermocycler detects one of these problems, it throws up a general error and immediately turns itself off. The only way to debug exactly what's going on without an immediate RMA is to manually execute debug commands through a serial terminal.

We should add more detailed logging and exceptions to the thermocycler stack so that errors can be more rapidly debugged.

**Comment by SyntaxColoring** [comment]
Closing this old ZenHub epic as stale. We've moved these things to Jira.
