### ISSUE TITLE
feat: describe small utility

### ISSUE THREAD

**Issue by kanishka-azimi** [Opentrons/opentrons#6578]
I have a few hours available, if you can describe a small CLI utility that you would find helpful in implementing or managing opentrons (automate some manual process in release, generate test data files, whatever). I am completely new to this domain and I want to contribute briefly to understand the overall project a little better. I will implement the utility using ocaml.

**Comment by mcous** [comment]
Hi @kanishka-azimi, thanks for your interest in contributing to the Opentrons platform! If you're interested in contributing to the Opentrons platform, please read the [contributing guide](https://github.com/Opentrons/opentrons/blob/edge/CONTRIBUTING.md) if you haven't done so already.

If you are interested in learning about the system by submitting pull requests, I would say we have a pretty big need for [documentation about the system itself](https://github.com/Opentrons/opentrons/blob/edge/OT2_ARCHITECTURE.md). We also have a the [easyfix issue label](https://github.com/Opentrons/opentrons/issues?q=is%3Aopen+is%3Aissue+label%3Aeasyfix) for issues that are good for first time contributors, but that list is a little small right now.

If you would like to write some sort of CLI tool in OCaml for working with the OT-2 or the Opentrons system, I would recommend doing that in your own repository. We use Python and JavaScript for our codebase, and we're unable to review or accept any contributions in other languages.

I'm closing this ticket, but please feel free to continue asking questions here (or in any other ticket thread)!
