### ISSUE TITLE
bug: (investigate) -- "last exported" info sometimes doesn't show up

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#6636]
# Overview

For some PD, protocols "Last Exported" is blank upon loading them into PD. For others, it shows a date-time.

# Steps to reproduce

~TODO - I have a lot of protocols from never-released dev versions of PD and don't want to confound the results. Try going to an old sandbox (use **release tag** sandbox, not a feature branch or edge plz) and saving protocols then uploading them into `edge`.~

See Max's post in #SPDDRS slack (I don't want to upload here bc it's from a customer)

# Current behavior

Upon loading some protocols:

![image](https://user-images.githubusercontent.com/11590381/94285690-02d97c80-ff22-11ea-8d7c-7ed991ac5a45.png)

# Expected behavior

Should always show this when you load a protocol

![image](https://user-images.githubusercontent.com/11590381/94285775-1f75b480-ff22-11ea-8203-49a4072aae04.png)

**Comment by SyntaxColoring** [comment]
I posted one random customer's protocol that's exhibiting this problem in Slack.
