### ISSUE TITLE
Chore: migrate LL/LC's QA into SmartSheet

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#6672]
Not a real ticket, just a reminder -- LL/LC's QA is still in a private Coda doc (vs the similar but outdated public Coda doc). We should switch it to SmartSheet

**Comment by Kadee80** [comment]
https://coda.io/d/Opentrons-Labware-Library-Release-QA-Worksheet_dQ6eQrknhVT/1-7-3_suwAD#_luFTL

has LC QA below LL stuff, still need to port but we have a testing script here

**Comment by Kadee80** [comment]
LL and LC are now separate QA Templates in the /Templates folder in smartsheet
