### ISSUE TITLE
Cal Overhaul: Check: Flow refactor (backend)

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#6727]
Calibration health check needs to change to check the new calibration flows (per the flowcharts in [this design](https://www.figma.com/file/nbDHskbW5zaXwtrLvEIKVj/calibration-overhaul?node-id=280%3A113)).

Key notes:
- Use the same tip rack logic as currently (one tiprack if possible, two if necessary)
- MVP: multi tipracks: if there are multiple tipracks, they should always be swapped out when moving from one pipette to another. Only slot 8 should ever be used for the tiprack
- Calibration block should be selectable and loaded into slot 6, tall-side-left if present
- Can keep the style of named state + active pipette but keep in mind what the logic on the frontend will have to look like

**Comment by Laura-Danielle** [comment]
This ticket should also update the error states to correctly match the error map for new calibration flows.
