### ISSUE TITLE
PD Research spike: How do we track whether a form has been edited since its last save (1 of 4)

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#6779]
[Link to research question](https://docs.google.com/document/d/15K7d538tnymHtywM-KzKLvtireHGeylcGz9HglVpKc8/edit#bookmark=id.xoq04tklpumv)

**Comment by shlokamin** [comment]
I've thrown my analysis into the google doc in this ticket!
