### ISSUE TITLE
PD Research spike: How can we display shared values of selected steps in the batch edit form? (2 of 4)

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#6780]
[Link to research question](https://docs.google.com/document/d/15K7d538tnymHtywM-KzKLvtireHGeylcGz9HglVpKc8/edit#bookmark=id.5dip087ctjrc)

**Comment by Kadee80** [comment]
CLosed after discussing as a team. GTG
