### ISSUE TITLE
During pickups in tiprack calibration, robot should move other instrument out of the way

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#681]
## overview

During tiprack calibration, the app calls `calibration_manager.pick_up_tip(instrument, labware)`. When going to pick up the tip, if the the unused pipette was already extended (for example, after a different tiprack calibration), it remains extended while the new pipette goes and picks up a tip.

With the unused pipette down, it looks alarmingly close to colliding with labware, and also obscures the operator's view of the labware under calibration.

## desired behavior

During a tip pickup, the robot should move the unesued pipette out of the way

## steps to reproduce

This is easiest to observe with the new calibrator selection logic, where the robot can switch off between which pipette it uses to calibrate a given tiprack.

TODO: paste branch name + PR with this logic

1. Run `calibrator-validation.py` from the calibrator branch above in the app 
2. Go through tiprack confirmation
3. Observe pipette behavior

**Comment by andySigler** [comment]
fixed in PR #774
