### ISSUE TITLE
PD: Edit pipette modal is way taller than it needs to be

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#6831]
## Acceptance criteria
- [ ] Fit height of modal to modal contents

## Screenshot of current state
![image.png](https://images.zenhubusercontent.com/5e27344f9aca8806bc57bc3b/ae562cc8-9f17-40c3-90e4-0a3231144e32)

**Comment by mcous** [comment]
Similar to #6832, [`<BaseModal>`](https://s3-us-west-2.amazonaws.com/opentrons-components/components_add-base-modal/index.html#basemodal) may be helpful here as its height behavior is a little more sane (sets `max-height: 100%` rather than `height: 100%`)
