### ISSUE TITLE
bug(notify-server): Integration tests in CI freeze

### ISSUE THREAD

**Issue by amitlissack** [Opentrons/opentrons#6843]
# Overview

`notify-server` used to have a number of integration tests that spin up ZMQ connections, pass messages around, then tear everything down. While running one such test passes, running multiple such tests causes CI to freeze.  

# Workaround

The multiple integration tests were redundant so I simply left one test. 

# Complexity

- I was not able to reproduce this on mac or multiple linux docker images. So this ONLY happens in github flow. 
- Solving this will require digging into running the tests with some debug information. I spent a moment with https://github.com/nektos/act to no avail.

**Comment by mcous** [comment]
Doesn't seem to still be an issue. Can re-open if needed
