### ISSUE TITLE
bug: Labware Creator and Opentrons App accept bad labware definitions in the X-axis

### ISSUE THREAD

**Issue by alexjoel42** [Opentrons/opentrons#6910]
# Overview

Too large X Well Spacing and X Grid Offset values are able to be input into both Labware Creator and the Opentrons App

# Steps to reproduce

- Open Labware Creator 
- Input a large well spacing and/or grid offset value 
![x offset and grid innacuracy ](https://user-images.githubusercontent.com/65437763/98135816-495db780-1e8e-11eb-894e-4914c5372554.png)

- Download the labware definition
[Bad_x_grid_and_spacing.zip](https://github.com/Opentrons/opentrons/files/5488979/Bad_x_grid_and_spacing.zip)

- Upload the definition to either Labware Creator or Opentrons App 

# Current behavior

The definition gets uploaded without issue. 
# Expected behavior

When the y grid offset or well spacing is modified to be similarly large, the following error appears: 

Labware Creator:

<img width="873" alt="Screen Shot 2020-11-04 at 11 31 54 AM" src="https://user-images.githubusercontent.com/65437763/98138678-592acb00-1e91-11eb-91fb-4d4e7029e872.png">. 

Opentrons App: 
<img width="610" alt="Screen Shot 2020-11-04 at 11 28 24 AM" src="https://user-images.githubusercontent.com/65437763/98138260-ea4d7200-1e90-11eb-90e9-df7734285d8e.png">

The boundary conditions should behave the same in both the x and y axis when considering grid offset and well spacing.

**Comment by anthonywilleee** [comment]
need to start with validation in labware creator

**Comment by IanLondon** [comment]
Hmm... I can't replicate this validation error in Run App with the attached labware def or labware test .py protocol. Also not sure how to make negative coordinates show up in Labware Creator's output, I can make wells that far fall off the plate in positive x/y directions, but not down the negative axes.

**Comment by anthonywilleee** [comment]
This will be fixed for labware creator with custom tip rack work, but error will not be displayed on Run app. Once we release LC, this will no longer be a problem, but if its a definition that was created prior to custom tipracks LC update, this will still be an issue in Run App.

Consider breaking out separate bug / ticket for Run app

**Comment by IanLondon** [comment]
^ Just to link tickets: addressed for LC in #7165 (but not addressed in Run App)

**Comment by IanLondon** [comment]
Gonna close this bc after #7165 it's a Run App thing, not an LC thing
