### ISSUE TITLE
feature(app): run app can subscribe to notification server events

### ISSUE THREAD

**Issue by amitlissack** [Opentrons/opentrons#6912]

**Comment by amitlissack** [comment]
# Overview

Provide the plumbing to subscribe to events from notification server. 

# Details

Open a websocket connection to robot-server specifying topics.
Topics are in configuration

# Acceptance Criteria

- [ ] Run app creates a websocket connection specifying requested topics.
- [ ] Run app logs received notifications.

**Comment by mcous** [comment]
Stale ticket, closing in favor of new tickets for this behavior when ready
