### ISSUE TITLE
feature(robot-server): robot settings changes notifications

### ISSUE THREAD

**Issue by amitlissack** [Opentrons/opentrons#6926]
# Details

The robot server should issue a notification when the robot's settings (`/settings`) are changed. 

Payload can be what changed or entire object. 

# Acceptance criteria

- [ ] Settings changes trigger publishing event to notification server
- [ ] Modeled in notification package
- [ ] use unique topic: `robot.settings.changed` or something similar.

**Comment by amitlissack** [comment]
# Details

Payload can be what changed or entire object. 

# Acceptance criteria

- [ ] Settings changes trigger publishing event to notification server
- [ ] Modeled in notification package
- [ ] use unique topic: `robot.settings.changed` or something similar.

**Comment by mcous** [comment]
Stale ticket, closing in favor of new tickets for this behavior when needed
