### ISSUE TITLE
Connectivity: Notify User of Dropped Robot Connection

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#695]
As a user, I’d like to be notified if a connection to a robot drops.

## Acceptance Criteria
- [x] User alerted if connection drops, and prompted to re-establish connection
-  [x] Alert should appear regardless of what page you are on

## Design

https://projects.invisionapp.com/share/V5FI4I26QWD#/screens/276429918

## Implementation Notes

- If connection is dropped during a protocol run, protocol will continue running. User will be return to an unconnected state (right panel blank), but will see the current run status when they reconnect
- If connection is dropped during robot calibration, the state will not be preserved, and the user will have to start over.
- We can use the health endpoint to detect whether a robot is missing

**Comment by umbhau** [comment]
@mcous how would you feel about an additional requirement:
- robot is shown as disconnected in sidepanel

**Comment by mcous** [comment]
Ping @umbhau, @pantslakz, and @howisthisnamenottakenyet this ticket is ready for a UX review!

**Comment by mcous** [comment]
UX review completed, feedback to be reviewed and addressed with additional tickets
