### ISSUE TITLE
PD Bug: Well selection instructions does not appear during liquid placement

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#6953]
## Steps to reproduce
Open "name & liquids' view of labware during deck setup
Scroll to the bottom
![image.png](https://images.zenhubusercontent.com/5e27344f9aca8806bc57bc3b/8d5e52b0-775c-4a3b-b3af-90e1492b51fb)

**Comment by IanLondon** [comment]
Could not reproduce, we should keep an eye out and can reopen this if it shows up again.
