### ISSUE TITLE
Connectivity: View-Only Second User

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#696]
As a user, I’d like to know if another user is connected to a robot, so that I don’t accidentally interrupt their work.

## Acceptance Criteria
* After connecting to a robot, user is made aware if any other users are current connected to the same robot (note this should include a persistent/periodically updated status message)
* If user attempts to interact with robot, user is prompted to decide whether to boot the other user (potentially interrupting work), or cancel

## Design
* STILL REQUIRED
* https://projects.invisionapp.com/d/main#/console/13154070/276444868/preview

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535456199) by [Unito](https://www.unito.io/learn-more)

**Comment by Matt-Zwimpfer** [comment]
Addressed separately
