### ISSUE TITLE
bug: Labware Creator outputs invalid definitions for wellplates with more than 26 rows

### ISSUE THREAD

**Issue by TimS-458** [Opentrons/opentrons#6995]
# Overview

Making a wellplate with more than 26 rows using the labware creator results in an invalid labware definition file.

# Steps to reproduce

1. Open the labware creator
2. Make a wellplate with 27 or more rows
3. Download the definition
[generic_1296_wellplate_8ul.zip](https://github.com/Opentrons/opentrons/files/5538636/generic_1296_wellplate_8ul.zip)
4. Upload the definition to the Opentrons app (tested v3.21.2).

# Current behavior

Upon upload, the Opentrons App returns an error:

Invalid Labware Definition
The file generic_1296_wellplate_8ul.json is not a valid Opentrons labware definition. Please check that you selected the correct file.

An otherwise identical definition with 26 rows can be uploaded with no issue.
[generic_1248_wellplate_8ul.zip](https://github.com/Opentrons/opentrons/files/5538747/generic_1248_wellplate_8ul.zip)

## Underlying Issue

Wellplates with more than 26 rows cause the labware creator to run out of letters. When this happens, it starts using special characters instead. This results in well labels in the json file looking like so:
``"X1", "Y1", "Z1", "[1", "\\1", "]1", "^1", "_1", "`1", ``

Upon upload, the Opentrons app takes one look at these row names and freaks out.

# Expected behavior

One of the following:
- The labware creator should return an error saying that wellplates with more than 26 rows are unsupported
- The labware creator should not use special characters for naming rows 27+

**Comment by mcous** [comment]
Thanks for this report @TimS-458! This issue is currently being tracked in #4200, so I'm going to close this one out, but it will remained linked
