### ISSUE TITLE
Calibration: tip probe - failure to attach tip correctly

### ISSUE THREAD

**Issue by pantslakz** [Opentrons/opentrons#702]
User (Kaja) unable to return to "calibrate tip" screen upon tip probe failure. App did not recognize that pipette had no tip attached during tip probe.

_"I run the protocol yesterday and everything went very well! I used only 10 tubes and run the rest dry but I'll run it tomorrow with 96. The only slight issue was when I was calibrating the pipette - I didn't put the tip on very well and it fell off during calibration. There was no way to tell it start the calibration process again - I just had to quit the program."_

Ideal behavior:
- once tip probe begins, if no tip detected - user is returned to this screen:

![screen shot 2018-01-30 at 9 14 04 pm](https://user-images.githubusercontent.com/2686086/35588936-79fe775a-0602-11e8-95c1-529be7996d47.png)

**Comment by umbhau** [comment]
@pantslakz - this solution only works if the tip falls off before the tip probe, right?
"once tip probe begins, if no tip detected - user is returned to this screen:"

but we could solve it generically by building the calibration pause/cancel feature we've been talking about?

**Comment by pantslakz** [comment]
@umbhau chatting with Mike what I understood is that we have ability to detect if there's a tip missing at any point during the tip probing process, and if that happens we can bring them back to this screen.

I havent yet heard about a calibration pause/cancel feature, but sounds very useful (especially in case of potential harm to pipette)

**Comment by mcous** [comment]
As discussed today, reclassifying this from a "bug" to "designs needed". The app captures errors during tip probe but has nowhere to display them

**Comment by mcous** [comment]
Actually just going to close this in favor of #1157
