### ISSUE TITLE
Enter multi-select mode via ctrl/cmd+click or shift+click 

### ISSUE THREAD

**Issue by anthonywilleee** [Opentrons/opentrons#7062]
**User Story**
As a PD user, I would like to SHIFT/CTRL/CMD+CLICK to select multiple steps for editing.

**Requirements**
Entering Multi-step selection

Hold SHIFT & Click (multi-select range)
Hold CMND or CTRL & Click (multi-select steps one at a time)

For policies and selection scenarios for entering batch edit mode, see [Batch Edit Step Bulk Actions Chart](https://www.figma.com/file/6p1uxeeioDikcfSwLCfxi4/Batch-Editing?node-id=827%3A67)

**Acceptance Criteria**

See the Figma chart above for a full list of expected behaviors

- We should dispatch `SELECT_MULTIPLE_STEPS` with a payload containing an array of step ids that should selected (including any step that was already selected in single-step mode, if any)

- All "are you sure" modals described in the chart should appear when their conditions are met.

- Several selectors involved in selection should discriminate between single-mode vs multi-select mode. See epic description (#7061 - eg, `getSelectedStepId`)

**Comment by shlokamin** [comment]
[As per slack convo](https://opentrons.slack.com/archives/G01FLLVK1S5/p1607403737003700), if you have a terminal item selected, even if you shift/command click a non terminal item, you can't enter batch edit mode
