### ISSUE TITLE
feat: (api) User Confirm Statement/Utility Command

### ISSUE THREAD

**Issue by Dardin-dale** [Opentrons/opentrons#7063]
# Overview
Confirm syntax for the api would allow for more flexible protocol development. Similar to the protocol.pause() or a protocol.comment() which produce visual feedback on the Opentrons app during a protocol run. Basic sample selection (e.g. 'left' or 'right' half of the plate) could be achieved as well as allowing for other protocol setup instructions. 

I am currently developing protocols for other people (non-python users) to use. Currently to achieve sample selections I am either writing multiple protocols that have the correct samples to choose from or using global 'selection' variables that are saved in the protocol file prior to running the protocol. I'd like to streamline this process for the end users.

# Design
a method for the protocol context- 

ProtocolContext.confirm(String: prompt, String: true_prompt, String: false_prompt) 

defaults: None, "Yes", "No"
Returns: Boolean

example:
```
plateSeries = []
isLeft = ctx.confirm("Which half of the plate would you like to use?", "Left", "Right")

#both branches can be validated by the simulator.
if (isLeft):
    plateSeries = [plate['A1'], plate['A2'], plate['A3'], plate['A4'], plate['A5'], plate['A6']]

else :
    plateSeries = [plate['A7'], plate['A8'], plate['A9'], plate['A10'], plate['A11'], plate['A12']]

```
yields: a confirm type UI element during protocol execution and blocks the protocol while waiting for response. Similar to ProtocolContext.pause(). 

# Acceptance criteria

- [ ] User input utility method for the protocol context
- [ ] Prompts User during protocol execution with some confim-like widget
- [ ] Properly simulates/validates resulting branches.

**Comment by ecormany** [comment]
[Runtime parameters](https://docs.opentrons.com/v2/runtime_parameters.html), added in Python API v2.18, provide this functionality.
