### ISSUE TITLE
Spike: write project initiative for RPC removal + HTTP upload project

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#7067]

**Comment by amitlissack** [comment]
# Overview

Create a project initiative document for removing RPC. Calibration, protocol upload and execution will happen via HTTP endpoints. 

# Acceptance Criteria

The document illustrates the project's benefits to users.

**Comment by mcous** [comment]
More product documentation exists, can close ticket as there is now clear ownership of that documentation
