### ISSUE TITLE
Cancel Function Does Not Work During Pause

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/opentrons#707]
## overview

Lack of functionality for certain buttons in the app.

## Expected Behavior
- User should be able to cancel a protocol run even if it is paused

## Observed Behavior 
- Pause button non-responsive when protocol run is paused

## steps to reproduce
- Connect to any robot / software version 
- Load any protocol
- Run protocol
- Pause protocl
- Attempt to cancel protocol
- Observe robot/run app does not respond

**Comment by Laura-Danielle** [comment]
@Kadee80 @mcous just to clarify, when I press the 'pause' button and then decide to cancel, the button does nothing. If something goes disastrously wrong in a protocol, would be good if the screen moved back to 'labware set-up' and then homed the robot if someone presses 'Cancel'.

**Comment by umbhau** [comment]
Note this should be resolved by 855.
