### ISSUE TITLE
Step selection behaviors (Selecting a range, selecting a single step, key commands, etc.)

### ISSUE THREAD

**Issue by anthonywilleee** [Opentrons/opentrons#7076]
Rules & scenarios for multi-step step selection. Consider Key commands, operating systems

**Entering Multi-step selection**
- Hold SHIFT & Click (multi-select range)
- Hold CMND or CTRL & Click (multi-select steps one at a time)

Once multiple steps are selected, user is in multi-select mode.

**Select multiple contiguous steps**
--Background--
To think about this interaction we introduce the concept of most recent step clicked. This is not the same as the last step (aka furthest down in the continuity of your protocol). You can see this concept in action in gmail, where the most recent step clicked is indicated with a circle icon around the checkbox. 
Most recent step clicked always defines the start of a contiguous range selection. The end of this range is the next step clicked after SHIFT+Clicking.
---
[Shift click selection chart](https://www.figma.com/file/6p1uxeeioDikcfSwLCfxi4/Batch-Editing?node-id=855%3A19143)
[Shift vs ctrl/command click flowchart](https://www.figma.com/file/6p1uxeeioDikcfSwLCfxi4/Batch-Editing?node-id=827%3A67)

1. Hold the shift key
2. While holding SHIFT, click the step you want to define the end of your range. 
3. If all steps inside the selection aside from that initial most recent step are checked, all steps in selection become unchecked. If all steps inside the selection aside from that initial most recent step are unchecked or mixed case, all steps in selection become checked. 

**Select multiple steps not grouped together while in single edit mode**
1. Click the first step, and then press and hold the CTRL key (PC) or COMMAND key (Mac)
2. While holding down the CTRL or COMMAND key, click another step.
3. Selected steps are highlighted and PD enters batch edit mode

Alternatively, while in multi-select mode, user can click steps one at a time to add to their selection without a holding down a button.

**Select combo of multiple steps grouped and not grouped together** --
1. Click the first step you want to select.
2. Hold down the SHIFT key, select the last step you want selected, and then let go of the SHIFT key.
3. All steps in between are now selected
4. Now hold down the CTRL or COMMAND key and click any other step you would like to add to those already selected.
5. Those steps are now added
6. Holding CTRL or COMMAND while clicking on selected steps deselects that individual step
7. Holding SHIFT and selecting steps above the first or below the last step selected establishes a new range selection (steps outside that new range remain selected? or automatically get deselected?)

**EDIT made on 12/17/2020**: Do not allow users to deselect steps if it means that the deselection would result in 0 steps selected. See [slack convo](https://opentrons.slack.com/archives/G01FLLVK1S5/p1608141909025900)

**Comment by IanLondon** [comment]
On terminal item. Shift+click a step -> nothing happens
On terminal item. Command+click a step -> nothing happens

On step item (single-select mode). Shift+click a step ->

```
{
    type: SELECT_MULTIPLE_STEPS, 
    payload: {
        stepIds: [prevSelected, b, theStepYouShiftClicked],
        lastSelected: 'theStepYouShiftClicked'
    }
}
```

On step item (single-select mode). Command+click a step ->

```
{
    type: SELECT_MULTIPLE_STEPS, 
    payload: {
        stepIds: [prevSelected, theStepYouCommandClicked],
        lastSelected: 'theStepYouCommandClicked'
    }
}
```

In multi-select mode. Shift+click a step ->

```
{
    type: SELECT_MULTIPLE_STEPS, 
    payload: {
        stepIds: [...existingSelection, ...rangeFromLastSelectedItemToNewlySelectedItem],
        lastSelected: 'theStepYouJustClicked'
    }
}
```

In multi-select mode. Command+click a step ->

```
{
    type: SELECT_MULTIPLE_STEPS, 
    payload: {
        stepIds: [...existingSelection, theStepYouJustClicked],
        lastSelected: 'theStepYouJustClicked'
    }
}
```
