### ISSUE TITLE
Connectivity: One Robot at a Time Tooltip

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#709]
As a user, I need to know that I have to disconnect from all robots before connecting to any other robots.

## Acceptance Criteria
- ‘Connect’ button inactive for all robots other than currently connected robot
- User informed that they have to disconnect from all other robots before connecting to a robot (e.g. hover tooltip on connect button)

## Implementation Notes
- Includes creation of tooltip skeleton / framework

## Design
- https://projects.invisionapp.com/share/V5FI4I26QWD#/screens/275374451

**Comment by umbhau** [comment]
Dependent on a tooltips framework.

**Comment by mcous** [comment]
Tooltip framework added in #1855!

**Comment by umbhau** [comment]
I am closing this for now. 

Still a valid feature, but not a prioritized one (no reported issues around this yet)
