### ISSUE TITLE
OT-2 Refresh: Configurable currents depending on hardware revision

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#7093]
Add support for saving, configuring, and changing gantry and Z-stage currents based on the CRB revision.

**Comment by djgomez-opentrons** [comment]
All currents found in the robot settings should be configured dependent on the stepper motor driver hardware revision. 

The exact changes we need for now, these should apply to all stepper driver boards rev A and higher. (12.5 and lower get the old settings)

1. Holding current - we want the X/Y motor holding current to be 0.7A. 
I believe this is the "low_current" in the robot settings. 

2. Z/A general movement current set to 0.5A. The goal here is to have all general movements of the Z/A (so basically everything except tip pick up (which is set separately) to be 0.5A. 
I believe this means the "high_current" and "default_current" should be 0.5A for Z/A but someone should check that that actually gives the desired function.
