### ISSUE TITLE
bug: Can't callibrate a left mounted p1000 gen2 with version 4.0.0

### ISSUE THREAD

**Issue by egenomics** [Opentrons/opentrons#7133]
# Overview

When I click pippette offset callibration, then start tip length callibration, then set the two modules required (p1000 tiprack and metal module to callibrate).
Next step is to click confirm placement and continue. In this point the robot does nothing and just shows me the message again.

# Steps to reproduce

SO: MacOS
App and robot version: 4.0.0

# Current behavior

Can't callibrate pipette

# Expected behavior

Be able to callibrate pipette

**Comment by jeppefock** [comment]
The same behavior is observed with a p20 pipette in the left mount

**Comment by mcous** [comment]
Closing ticket due to age. If this issue has not been resolved, please do file a new ticket!
