### ISSUE TITLE
PD: Hook up batch edit form to display while in batch edit mode

### ISSUE THREAD

**Issue by anthonywilleee** [Opentrons/opentrons#7149]
Dev ticket to hook up the batch edit form ([7128](https://app.zenhub.com/workspaces/opentrons-spddrs-5e1f591ca60369aa0e6b8eaf/issues/opentrons/opentrons/7128)) and associated logic so that it shows up at the correct time.

**Acceptance Criteria**

1. The batch edit form will display while in batch edit mode
2. Single step form will display while not in batch edit mode

**Comment by anthonywilleee** [comment]
Would be nice to make this logic before actually hooking up the component. this ticket is for that logic

**Comment by IanLondon** [comment]
Considering this closed as part of #7350 since this ticket isn't for UI
