### ISSUE TITLE
PD: Batch Edit Disabled Form Field States

### ISSUE THREAD

**Issue by anthonywilleee** [Opentrons/opentrons#7151]
**User Story**

As a PD user in batch edit mode, I would like a non-editable setting to display as disabled / inactive, so that I know I can't edit that setting.  

This is part of an overarching user story: As a user I would like to know what states the fields in my batch edit form are in

**Description**

This ticket breaks out the work for disabled fields in batch edit (top of the logic tree in [figma design](https://www.figma.com/file/6p1uxeeioDikcfSwLCfxi4/Batch-Editing?node-id=705%3A15352) frame 68)

**Requirements**

- Enabled / disabled conditions are specified in this [doc](https://docs.google.com/spreadsheets/d/1dbEeeFj3Bdi9IsRQUl_N-xUr3XnERoJkL2BhEuWO9gw/edit#gid=0) (see transfer & transfer under aspirate and dispense)
- If an advanced setting is not editable, display form field as empty and disabled
- Use new tool tip for multistep field connector 
- TO DO: Tooltip copy for selected states (e.g., pipette must be the same to edit flow rate across steps)

![image.png](https://images.zenhubusercontent.com/5f772bd73389cd8dbeb34a48/26f3306c-d594-4fd2-a570-200cdecd7687)

**Comment by IanLondon** [comment]
Closed as part of #7193 and will finally be hooked up in #7128
