### ISSUE TITLE
bug: Not able to Factory Reset using opentrons app 4.0. 

### ISSUE THREAD

**Issue by jeppefock** [Opentrons/opentrons#7157]
# Overview

It is not possible to do factory reset in App 4.0 because the bottom is not accessible. 
# Steps to reproduce

Click Reset botton
# Current behavior
no bottons availeble

# Expected behavior
botton availeble
<img width="469" alt="screen" src="https://user-images.githubusercontent.com/51740424/102907362-3a4ebb00-4476-11eb-91ee-eef7795d81b0.PNG">

**Comment by mcous** [comment]
Fixed in the 4.1 release
