### ISSUE TITLE
LC: New footprint error -- too small for slot

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#7163]
## Background
As a user I would like to know that there is a way to get adapters for labware that is too small to fit in slots. This will trigger for all labware. Logic for existing "too big for slot" error to be updated for this "too small for slot" error.  Bounds for too big or too small contained in labware form schema code as min / max. 

## Design
![image.png](https://images.zenhubusercontent.com/5e27344f9aca8806bc57bc3b/27bb8d15-dab6-49f4-8981-9e6be1c57ea1)

## Acceptance criteria
- [ ] When a labware is too small (beyond the lower bounds of what is acceptable to the form field) user should see an additional error. `MIN_X_DIMENSION = 127` `MIN_Y_DIMENSION = 85`  (error will trigger if under the min)
- [ ] The link in the error goes to: https://docs.google.com/forms/d/e/1FAIpQLScvsHlXQrtIhIQYO0zr6mYwmzOCGpYPqepeDIorFIyj2jT-UQ/viewform
- [ ] E2E tests updated to verify too small error is triggered

@Kadee80 - can you add bounds for this

**Comment by anthonywilleee** [comment]
@howisthisnamenottakenyet 
1. agree, i can follow up with apps eng, unless you think otherwise. do you know what's the margin of error for too big?
2. can't think of a reason to not do this for all labware types, but i can add that q to apps eng

**Comment by Kadee80** [comment]
MIN_X_DIMENSION = 127 MIN_Y_DIMENSION = 85
