### ISSUE TITLE
bug: Infrequent systematic issues with pause and run clock features

### ISSUE THREAD

**Issue by ethanfjones** [Opentrons/opentrons#7167]
# Overview

There are three different events that seem to be happening with different OT-2s. 

* ~~**Event 1**~~ Moved to a separate issue: #7216
* ~~**Event 2**~~ Moved to a separate issue: #7272
* ~~**Event 3**~~ Moved to a separate issue: #7273

# Steps to reproduce

I have not tried to reproduce the issue yet.

**Comment by amitlissack** [comment]
We believe that Event 1 is fixed (#7216)

**Comment by SyntaxColoring** [comment]
Closing this in favor of several smaller tickets.
