### ISSUE TITLE
bug(robot-server): Opentrons-Version header requirement broke /api interactive UI

### ISSUE THREAD

**Issue by amitlissack** [Opentrons/opentrons#7171]
# Issue

The `/api` UI is broken after 4.0. All requests are rejected due to absence of `Opentrons-Version: 2` header.

# Acceptance Criteria

1. the `Opentrons-Version` header requirement is present in the OpenAPI spec with a default value of the maximum version. *
2. the `/api` UI can be used to try out API requests

# Technical details

* doing this by adding `opentrons-version: int = Header(API_VERSION_LATEST)` in each route is possible, but certainly too tedious. More research in the FastApi/Starlette docs is required to find a clean solution.

**Comment by SyntaxColoring** [comment]
> doing this by adding `opentrons-version: int = Header(API_VERSION_LATEST)` in each route is possible, but certainly too tedious.

One possible solution could be to have a function decorator to wrap routes and add that automatically. Still boilerplatey, but at least less repetitious.
