### ISSUE TITLE
Refactor: Gcode objects with deferred stringification

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/opentrons#7214]
we should have some objects (maybe dataclasses) that represent gcode commands while stored in memory. Smoothie driver functions should build and handle sequences of these gcode objects, and pass them to the serial interface.

Once you have that, testing becomes much easier because you don’t have to do any string comparison at all. You can also have richer types - smoothie gcodes vs magnetic module gcodes, etc. 

You can also do the same thing in reverse, decoding responses to dataclasses as early as possible and feeding them to the smoothie driver; this makes it easier for test harnesses to stimulate the smoothie driver response handling.

**Comment by amitlissack** [comment]
I have started working on this as part of the api-driver-refactor branch. 

https://github.com/Opentrons/opentrons/blob/api-driver-refactor/api/src/opentrons/drivers/asyncio/communication/command_builder.py
