### ISSUE TITLE
bug: pyserial 3.4 incompatible with macOS Big Sur

### ISSUE THREAD

**Issue by gregmedlock** [Opentrons/opentrons#7226]
# Overview
Running/simulating any protocol on macOS Big Sur leads to an error within pyserial; the issue has been resolved in the latest release of pyserial (3.5) and has been documented in other packages (https://github.com/pyserial/pyserial/issues/509). Opentrons has a fixed requirement of v3.4 (pyserial==3.4), but upgrading to pyserial==3.5 resolves the issue. Not sure if upgrading pyserial will break anything--if it does, I haven't run into the issue yet.

# Steps to reproduce
simulate any protocol on Big Sur.

# Current behavior
Raises:
```
ValueError: dlsym(RTLD_DEFAULT, kIOMasterPortDefault): symbol not found
```

# Expected behavior

No error

**Comment by SyntaxColoring** [comment]
Thanks for the report!

We ran into the same thing internally, and I think we've already fixed it in https://github.com/Opentrons/opentrons/pull/7207 and https://github.com/Opentrons/buildroot/pull/118.

Those fixes aren't in v4.0.0, but they should be in the upcoming v4.1.0, which you can monitor https://github.com/Opentrons/opentrons/releases for. When v4.1.0 comes out, you'll have to:

```
pip install --upgrade opentrons
```

(Or however updating Python packages works on your system.)

Meanwhile, your workaround of manually upgrading to `pyserial==3.5` should work.
