### ISSUE TITLE
Hardware API: Create version of protocol engine for hardware

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#7232]
We need a way to manage in flight commands and present a coherent API. Luckily, we already have one: the protocol engine. The hardware control API can mirror the organization of the protocol engine in many ways.

Create a version of the protocol engine (probably inheriting from those classes) somewhere in a new directory of the robot server to manage hardware control commands.

**Comment by mcous** [comment]
No longer applicable for this issue tracker
