### ISSUE TITLE
Hardware API: Create HTTP handlers, client, and commands for move, move_rel, and send_command

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#7234]
A core capability for the hardware API is the ability to move the robot as a six-axis motion controlled machine. Implement the handlers, the commands, and client bindings for the hardware control methods `move_to`, `move_rel`, and a special method `send_command` that accepts a raw gcode string and sends it to the motor controller. In addition, implement it in the client.

Also, add elements to the status for the position of the robots' axes.

**Comment by mcous** [comment]
No longer applicable for this issue tracker
