### ISSUE TITLE
Hardware API client: Bundle discovery

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#7236]
Add bundled binary discovery clients to the hardware API and basic python interfaces for them. These can and should be used
- interactively to list found robots
- automatically to find robots by name

**Comment by Laura-Danielle** [comment]
With this ticket, we should pull the discovery tool into its own separate repository and set it up as a subtree project (not dissimilar to the cmake-utils repository).

Once this is complete, we should notify the cpx team so they can pull out the discovery client from the monorepo and factory tools.

**Comment by mcous** [comment]
No longer applicable for this issue tracker
