### ISSUE TITLE
PD Basic Pipetting Steps: Mix Form (Validate and Save)

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#724]
As a protocol designer, I’d like to be able to save a mix step

## Acceptance Criteria
- User able to save a 'mix' step
- User able to cancel 'mix' step
- Mix configuration validate on save
-- (validations tbd?)

**Comment by IanLondon** [comment]
I'm taking out some options for now, so Mix form will look like

![image](https://user-images.githubusercontent.com/11590381/39724434-ce20c922-5216-11e8-8db6-e23d2a76d7cf.png)
