### ISSUE TITLE
PD: Labware name in Dispense dropdown should truncate with a "..."

### ISSUE THREAD

**Issue by anthonywilleee** [Opentrons/opentrons#7247]
Labware in Dispense dropdown should truncate with a "..." so as to not overlap with the drop down arrow. 

Currently, labware name overlaps with the dropdown arrow, and it looks janky.

![Screen Shot 2021-01-22 at 11.36.46 AM.png](https://images.zenhubusercontent.com/5f772bd73389cd8dbeb34a48/79e25146-ae3b-4bfe-8432-105c7748f768)

![Screen Shot 2021-01-22 at 11.37.01 AM.png](https://images.zenhubusercontent.com/5f772bd73389cd8dbeb34a48/adfdead2-3df0-4c5f-a9ee-4a8f93871329)

**Comment by sanni-t** [comment]
Moved to AUTH-665
