### ISSUE TITLE
refactor(robot-server): protocol upload and analysis run in threadpool executor

### ISSUE THREAD

**Issue by amitlissack** [Opentrons/opentrons#7254]
# Overview

The `/protocols` endpoint handlers perform file IO and protocol analysis, both of which can be long running. 

These actions are currently happening in synchronous calls that block the main thread. They should be converted to `async` and run in a `ThreadpoolExecutor`.

# Implementation details

- The public methods of `ProtocolManager` and `UploadedProtocol` should be marked `async`.
- The methods exported by `analyze` and `contents` modules should also be `async` and their work should be done in a `ThreadpoolExecutor`.

# Acceptance criteria

POST and PATCH `/protocols` will not block the main thread.

**Comment by mcous** [comment]
No longer applicable
