### ISSUE TITLE
feat(robot-server): HTTP protocol and session api supports labware calibration

### ISSUE THREAD

**Issue by amitlissack** [Opentrons/opentrons#7260]
# Overview

Labware calibration will be rebuilt this year.  It will not be built on RPC but on HTTP protocol and sessions API. There must be access to:
- Labware definitions for labware loaded by protocol
- ???

# Implementation details

# Design

# Acceptance criteria

- Labware calibration UI has access to all the data it needs to calibration labware.

**Comment by mcous** [comment]
LPC built on the HTTP API released in v5
