### ISSUE TITLE
bug: Protocol unpauses on its own?

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#7272]
Splitting this bug out of #7167.

Reported by @ethanfjones:

> The OT-2 was paused and the customer went for lunch. When they had gotten back to the OT-2 it said: "run complete". The time though was showing the time they hit the pause button at. (13 mins) According to the logs, the protocol ran perfectly fine.
> 
> [Event 2.zip](https://github.com/Opentrons/opentrons/files/5739942/Event.2.zip)

**Comment by SyntaxColoring** [comment]
CPX should investigate the .zip file and determine if we need further repro steps from Support.

**Comment by amitlissack** [comment]
There are a lot long delays in the protocol. If `pause` is clicked during the `delay` the `pause` will be ignored.

**Comment by SyntaxColoring** [comment]
Possibly related to #6898?

If the customer paused during a delay step, that suggests this is a symptom of the same underlying problem?
