### ISSUE TITLE
Protocol Upload: Session class has a "simulate" method for RPC

### ISSUE THREAD

**Issue by amitlissack** [Opentrons/opentrons#7287]
# Overview

Simulation will be optional. Run app needs a way to initiate a simulation.

The purpose of the simulation is only to find potential errors in the protocol.

# Acceptance Criteria

- Session has a public simulate method available over RPC.
- `simulate` does not alter the state of the `Session` object (ie does not recreate run log, equipment list, etc.).

**Comment by mattwelch** [comment]
Closing due to different route taken w/ "fast sim" work.
