### ISSUE TITLE
Protocol Upload: History of protocol simulations

### ISSUE THREAD

**Issue by amitlissack** [Opentrons/opentrons#7289]
# Overview

It may be necessary to simulate a protocol at least once successfully before running.

# Details

The robot should have a database table of protocols that have been successfully executed.  Column suggestions:
- Protocol name
- Author
- time stamp
- content hash
- API version 
- Robot SW version

When a protocol completes simulation, a row is inserted to the table.

# Acceptance Criteria

- robot server stores metadata about a protocol when it completes simulation
- robot server can detect if an uploaded protocol has been successfully simulated

**Comment by mattwelch** [comment]
Closing due to different route taken w/ "fast sim" work.
