### ISSUE TITLE
Prototype a new protocol upload experience

### ISSUE THREAD

**Issue by amitlissack** [Opentrons/opentrons#7290]
# Overview 

Define the mechanism and conditions required for the robot to record the fact that a specific protocol has been successfully “slow simmed”. Make this status available to external entities (run app) for use in user-facing experiences.

Prototype experiences where:
- Simulation is optional. 
- A protocol must pass simulation once before running.
- Upload uses an analyze stop (formerly known as "fast sim") to create run log and equipment requirements.

Acceptance criteria:

- A "new" (to the robot) always executes both fast and slow sim, as is the case now.
- A previously uploaded, and not-changed-since protocol can optionally skip slow sim.
- The robot reports back (via RPC or http) the status of slow sim (run, not run, not required but run anyway, etc)
- Upload uses an analyze stop (formerly known as "fast sim") to create run log and equipment requirements.

**Comment by mattwelch** [comment]
Closing due to different route taken w/ "fast sim" work.
