### ISSUE TITLE
feat(protocol-engine): ProtocolEngine ProtocolContextInterface implements load labware

### ISSUE THREAD

**Issue by amitlissack** [Opentrons/opentrons#7325]
# Overview 

The `ProtocolEngine` accepts a `LoadLabwareRequest` command. 

# Acceptance Criteria

- [ ] ~`load_labware` method in `ProtocolContextInterface` derived class created in #7323 sends `LoadLabwareRequest` command to `ProtocolEngine`.~ This acceptance criteria moved to #7390
- [ ] Return an instance of `LabwareInterface` defined in #7332

**Comment by amitlissack** [comment]
This ticket can be closed, right?

**Comment by mcous** [comment]
Oops, yeah. I must've messed up the autoclose comment or somrthing
