### ISSUE TITLE
bug: Running protocol via Jupyter Notebook, pipette movement is slightly off calibration. Same protocol, directly uploaded to OT-2, runs perfectly. 

### ISSUE THREAD

**Issue by Matt-Zwimpfer** [Opentrons/opentrons#7347]
# Overview

If a protocol (Python file) is uploaded and run on the OT-2, it runs without issue. When running the identical protocol with the same labware and pipette tip/type via Jupyter Notebook, there is a slight positional error and the pipette does not move to the exact location (off by 1-2 mm). 

# Steps to reproduce

Still testing to reproduce these conditions with off positional movement, but in general:

1. Upload python file version of the protocol
2. Go through full calibration routine
3. Run the protocol to ensure it is running properly
4. Run the identical Jupyter Notebook version of the protocol afterwards.
5. Note if the movement will be slightly off (1-2 mm)

# Current behavior

# Expected behavior

Jupyter Notebook should be pulling the calibration data from that already on the OT-2, so the pipette positioning/movement shouldn't be any different than that seen when uploading and running a python file protocol.

**Comment by mcous** [comment]
Ticket no longer relevant since calibration data in question replaced by LPC
