### ISSUE TITLE
Investigate scope of failing protocol incidence

### ISSUE THREAD

**Issue by mattwelch** [Opentrons/opentrons#7349]
As an Opentrons experience owner, I'd like to understand how often and in what context actual "slow sim" failures occur. I would like to also understand the impacts of these failures if they went uncaught.

Process

- [x] Investigate errors on Mixpanel to determine "slow sim" coverage
- [ ] Chat with support and other internal teams to get understanding of their view of upload failures

I will use this info to guide future work around sim experience.

Output should be a verification, with supporting evidence, that protocol upload failures are significantly caught by "fast sim".

**Comment by mattwelch** [comment]
[Mixpanel report](https://docs.google.com/spreadsheets/d/1qQc55aTIOma4REhYnIzJqebwReHTa9bWLSyRkAzCokU/edit?usp=sharing) generated listing protocol upload errors over the past 3 months.

Will spend some time at the next pairing brainstorming how we can eliminate noise here (remove syntax errors for instance).

**Comment by mcous** [comment]
Considering closed by Matt's research and the addition of #7631 to augment fast-sim with the additional failures we identified
