### ISSUE TITLE
PD Basic Pipetting Steps: Add Ingredients (DRAFT)

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#735]
As a protocol designer, I'd like to be able to add ingredients to my protocol.

### Open Ingredient Editor
- User able to open 'edit ingredients' view by hovering over relevant labware and selecting 'edit ingredients'
-- Note: is 'ingredients' the right word?
- User able to select which wells to edit (note: well selection modal is not covered in this story)

### Edit Ingredient Properties
- User is able to set the following ingredient properties
-- Name (note: shouldn't we already have this?)
-- Description (ditto)
-- Volume (in µl) (note: is µl sufficient?)
-- Concentration
- User is able to choose to serialize the name 
-- (note: how would this behave? 'Name'+Well ID?)

Note
### Validate and Save
- User is able to cancel
- User is able to save
- Ingredient configuration validated on save (TBD)

**Comment by IanLondon** [comment]
done or covered in other tickets
