### ISSUE TITLE
Split apart "Advanced Setting" and "Internal Development Setting" in API

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#7388]
## overview

The Robot Server / API has a concept of "advanced settings", which are used interchangeably in our code with the term "feature flag". In reality, however, these two things are separate concepts:

- **Advanced Setting** - A user-facing configuration
    - e.g. "Enable robot door safety switch"
- **Feature flag** - A configuration to enable a new feature that _is probably incomplete_ for testing purposes
    - e.g. "Enable Experimental HTTP Protocol Sessions"

In terms of UI, the biggest difference is that **feature flags should not be presented to users under normal circumstances**. In our `GET /settings` endpoint and its associated UI, though, internal feature flags are intermingled with user-facing advanced settings.

### prior art

The app's configuration system includes a `devInternal` subtree. Controls for this subtree are only present in the UI if the developer tools are enabled.

Even though they are hidden by default, though, the app's internal developer settings still have a problem where they are too easy for users to discover and turn on, inadvertently enabling incomplete features. 

### related tickets

- feat: move door switch feature to the same place as lights (#5867)

## proposal / acceptance criteria

- [ ] A new endpoint exists to read and update robot server feature flags
- [ ] **If-and-only-if** the app's developer tools are enabled, the robot UI presents a location to set those feature flags

### notes

- A simpler path might be to allow an advanced setting to be marked as a feature flag
- However, the advanced settings system in the API (and its endpoints) are suffering from a fair amount of bitrot, so IMO a new system for feature flags would be better move for incremental tech debt paydown

**Comment by mattwelch** [comment]
@readywater to work w/ @emilywools on how to take this one on. Planning for future sprint.
