### ISSUE TITLE
PD Deck Setup: Ingredient Sidebar

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#740]
As a protocol designer, I'd like to be able to view the ingredients I've configured in the app sidebar, so I can track my available ingredients.

### Ingredient Information
* User can see ingredient name
* User can see ingredient notes (?)
* User can see ingredient volume
* ~User can see ingredient concentration~

### Interaction and Design
* Sidebar changes to 'ingredient' mode when user is in 'ingredient' step
* User can expand or collapse ingredient details
* Ingredient is color-coded to match wells
* Style matches design mockups
* Design leverages component library (new components if necessary)

### Design Mockup:
* @howisthisnamenottakenyet 
![image](https://user-images.githubusercontent.com/35570080/38110912-2c085570-336b-11e8-865c-e35ba63d23d2.png)
![image](https://user-images.githubusercontent.com/35570080/38110958-4e50c766-336b-11e8-984c-8ca61245e3dc.png) 
![image](https://user-images.githubusercontent.com/35570080/38111020-8429a0e2-336b-11e8-9327-fbce05a5ea72.png)

^^^^ When decimals become involved add a ".0" after whole numbers so that right aligned volume maintains correct scale

┆Issue is synchronized with this [Wrike Task](https://www.wrike.com/open.htm?id=535458547) by [Unito](https://www.unito.io/learn-more)

**Comment by IanLondon** [comment]
@howisthisnamenottakenyet is this old card still current?
