### ISSUE TITLE
Protocol Engine labware naming

### ISSUE THREAD

**Issue by amitlissack** [Opentrons/opentrons#7425]
# Overview

`protocol_api.Labware` has a public setter quality for `name`. 

In the protocol engine implementation, state is only changed during command execution. 

# Questions

- Is this public setter required?

- How would this property be translated to protocol engine implementation?

**Comment by amitlissack** [comment]
See @SyntaxColoring comment: https://github.com/Opentrons/opentrons/pull/7436#discussion_r587712307

**Comment by mattwelch** [comment]
Closing due to http/experience-led protocol engine story/roadmap route taken.
