### ISSUE TITLE
Protocol Engine labware calibration (Labware.set_calibration)

### ISSUE THREAD

**Issue by amitlissack** [Opentrons/opentrons#7426]
# Overview

`Labware.set_calibration` is a public method but not marked with api version. 

Due to altering Labware state, It does not play nicely with the protocol engine.

# Questions

- It appears to that this method's existence is tied to RPC and the labware calibration process. Is that so? 
- Can't the calibration offset be supplied to `LabwareImplementation` on construction?

**Comment by amitlissack** [comment]
See @SyntaxColoring  comment here https://github.com/Opentrons/opentrons/pull/7436#discussion_r587717671

**Comment by mattwelch** [comment]
Closing due to http/experience-led protocol engine story/roadmap route taken.
