### ISSUE TITLE
Protocol Engine WellImplementation and WellGeometry

### ISSUE THREAD

**Issue by amitlissack** [Opentrons/opentrons#7449]
# Overview 

See https://github.com/Opentrons/opentrons/pull/7436#discussion_r587837555

`WellImplementation` and `WellGeometry` were created as refactors to reduce size of `Well` class. 

These two classes should be modified to better support Protocol Engine as the keeper of state. Perhaps creating a `WellInterface` and `WellGeometryInterface` that can be implemented as pass throughs to PE state.

# Acceptance criteria

- [ ] `WellImplementation` type class that does not keep state but gets data from PE state
- [ ] `WellGeometry` type class that does not keep state but gets data from PE state

**Comment by mattwelch** [comment]
Closing due to http/experience-led protocol engine story/roadmap route taken.
