### ISSUE TITLE
Labware definition file refactor

### ISSUE THREAD

**Issue by btmorr** [Opentrons/opentrons#746]
### Problem

Labware definitions are currently stored in a single large json file, and duplicated with some transformations in a sqlite database.

Specific problems:

- There is currently no mechanism for keeping these two databases in sync with each other
- The human-readable datastore (the json file) is not the source of truth at run time
- The labware definitions themselves have some problems in either file, such as the fact that the wells are not given any strict order or organization into or within rows and columns, which has caused unpredictable behavior in user protocols
- The migration process (creating the sqlite database from the json file if it does not previously exist) is slow and unnecessary
- The current state of the server keeps all of both the json datastore and the sqlite database in memory, which nullifies any gains made from keeping the data in a structured database
- It is difficult to incorporate and share user labware definitions
- The "container-offsets" field in the labware definition is confusing (and unnecessary, because the labware itself is never targeted for movements apart from targeting a well within the labware)

### Proposal

1. Remove the sqlite database from the server
1. Break the single large json file into a directory containing one json file per labware (example schema below)
1. Remove "container-offsets" and fold these values into the x/y/z of each well
1. For each definition, add an array of arrays as an explicit ordering of wells into rows and columns, where each inner array is a column (e.g.: A1 to H1 on a 96-well plate), and row N would be obtained by selecting the Nth element from each column.
1. Keep standard labware definitions in one directory in the Docker container, and keep user labware definitions in a corresponding directory in persistent storage (when loading a labware, check user directory first, then standard directory)
1. Add/modify `create` method that will accept new data format and save to the user definition directory
1. When calibrating labware, instead of modifying existing definitions, create an "offsets" record representing the delta from the base definition for that labware, in a directory in persistent storage (when loading a labware, check for an offset and apply it if it exists) (example schema below)
1. Only load a definition into memory when that specific labware is requested, which will reduce the run time memory footprint

Definition schema example:

```json
{
  "metadata": { "name": "4-well-plate" },
  "ordering": [ 
    [ "A1", "A2" ], 
    [ "B1", "B2" ] 
  ],
  "wells": {
    "A1": {
      "depth": 26,
      "diameter": 10,
      "total-liquid-volume": 78.6,
      "x": 40,
      "y": 40,
      "z": 30},
    "A2": {
      "depth": 26,
      "diameter": 10,
      "total-liquid-volume": 78.6,
      "x": 40,
      "y": 80,
      "z": 30
    },
    "B1": {
      "depth": 26,
      "diameter": 10,
      "total-liquid-volume": 78.6,
      "x": 40,
      "y": 80,
      "z": 30
    },
    "B2": {
      "depth": 26,
      "diameter": 10,
      "total-liquid-volume": 78.6,
      "x": 80,
      "y": 80,
      "z": 30
    }
  }
}
```

Offset schema example:

```json
{ "name": "4-well-plate", "x": 10, "y": -10, "z": 100}
```

Upon load, the x/y/z coordinates of each well would have the corresponding value from the offset file added. In the example above, the A1 well would be at (50, 30, 130) after having the offset applied.

**Comment by Laura-Danielle** [comment]
Not sure if this belongs under this issue, but also making sure that labware definitions are actually correct + naming conventions for each labware include either manufacturing company name and/or model number

**Comment by IanLondon** [comment]
Sounds good!!!

Also, we talked about moving labware to the repo root as its own `labware/` project, and adding a barebones package.json so JS projects can import it -- if that's done as a secondary follow-up PR after the initial big refactor labware PR(s), that's OK with me!

@Laura-Danielle maybe model number & manufacturer would go under the `metadata` field?

Something else we talked about was not treating "stackable" modules (like temperature deck) as a normal labware, since it doesn't have any wells. (But it does have an offset that it applied to its child/children, and js world would probably benefit from being able to read that offset...)

@btmorr Did we also talk about being able to create any container that you could make with JSON using `containers.create`? Or is that a separate thing outside this RFC?

**Comment by btmorr** [comment]
@IanLondon I actually think @Laura-Danielle 's idea about having separate named definitions per manufacturer is smart, to avoid confusion between one plate and another, but that doesn't change the overall plan at all

I do think that `containers.create` should work with the json schema

**Comment by btmorr** [comment]
Also, happy to put the definitions into a repo-level directory with a package.json file. Might as well do it right from the start.
