### ISSUE TITLE
Ensure tip is always dropped after run ends

### ISSUE THREAD

**Issue by sfoster1** [Opentrons/opentrons#7466]
If a protocol does not end with a drop tip command, or if a protocol is cancelled partway through due to user action or an internal error, a tip that may have liquid will be attached to a pipette when it homes its plunger. This results in two things: a) the home action could overaspirate and get liquid inside the pipette body; b) the tip will stay on there and the user will have to take it off manually.

Instead, when a protocol ends the robot should
- home z/a
- home x/y
- do a drop tip
- home b/c

This will ensure that the tips are dropped in the trash along with any liquid they contain before that liquid is overaspirated.

**Comment by SyntaxColoring** [comment]
Related / maybe dupes?

* #3738
* #5428

**Comment by mattwelch** [comment]
@nusrat813 we have brought this in to sprint 37. when does this work need to be merged to make 4.5 (July 28).

**Comment by nusrat813** [comment]
@mattwelch we would need this to be merged no later then July 26 if we want a release on July 30th

**Comment by mcous** [comment]
Revising estimate from 3 to 5 due to discussions with the embedded team. It's hard
