### ISSUE TITLE
bug: PD - touch tip minus button should go down to 0 instead of min

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#7508]
# Bug

Tip position modal currently disables the `-` button when approaching the minimum. This is apparent in `Touch Tip -> Tip Position` (as opposed to Aspirate/Dispense Tip Position)

# Desired behavior

- Don't disable the `-` button in Tip Position modal.
- If the user clicks it and it's close to 0 eg `0.1mm`, go to 0mm (don't go below zero)
- If the  user clicks `-` and it's already at 0, do nothing (but button is still enabled)

**Comment by IanLondon** [comment]
I think this one is desired behavior, because in prod (old Tip Position modal) we didn't allow out-of-range values, which was annoying bc you couldn't type freely. Now we do allow values even when out of range. The pattern of allowing any number to be entered through typing is continue in allowing any height to be set with the arrow keys.

**Comment by reachojhaneha** [comment]
I just checked with Morgan about this and we concluded that we should preserve the "minus button" lowering the value to minimum value and not below minimum. Because the minus button does not lower the value to "0". For example if the minimum value for tip position is 12.5, minus button if clicked multiple times lowers the value till 12 and not 0.

**Comment by IanLondon** [comment]
Could we rename + relabel this as a feature and not a bug? Was not specified in the ticket #7143 when this was done

**Comment by anthonywilleee** [comment]
@howisthisnamenottakenyet - also curious your thoughts on this one..should we preserve not being able to go past min / max when hitting minus button
