### ISSUE TITLE
bug: PD - incorrect step count displayed

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#7509]
Generate the error "Not enough tips to complete action"
And enter into the batch edit mode, number of steps shown is increased by 1

**Comment by reachojhaneha** [comment]
unable to attach the screen recording

**Comment by shlokamin** [comment]
https://user-images.githubusercontent.com/5788529/111636120-8d62b080-87ce-11eb-904e-0af5d6cf6c55.mov
