### ISSUE TITLE
Pipette moves to wrong location during tip probe

### ISSUE THREAD

**Issue by btmorr** [Opentrons/opentrons#753]
## overview

Observed on a life-testing robot

## behavior

During factory calibration tip probe is successful, then during run tip probe goes to middle of fixed trash box.

## steps to reproduce

Run tip probe from app on `morning-sound`

**Comment by umbhau** [comment]
@btmorr I haven't observed this -- have you been able to recreate it / seen it in the wild since?

**Comment by mcous** [comment]
Closed because this doesn't happen anymore
