### ISSUE TITLE
bug: simulation allows aspirating and dispensing on a tip rack

### ISSUE THREAD

**Issue by andeecode** [Opentrons/opentrons#7552]
# Overview

The robot does not raise an error or warning when trying to aspirate and dispense on a tip rack. This occurs during the simulation and the tip rack is from the Opentrons labware library, not customized. 

# Steps to reproduce

apiLevel = 2.8 

Load plate with tip rack:

    plate = protocol.load_labware('geb_96_tiprack_10ul',4)

Perform a mock transfer (same problem happens when using aspirate and dispense):

    pipette.transfer(5, plate.wells_by_name()['A2'], plate.wells_by_name()['B2'])

# Current behavior

![image](https://user-images.githubusercontent.com/70355341/112745064-8593d080-8f73-11eb-96bf-cb80cdd6b41e.png)

# Expected behavior

Raise a warning so that users are aware of this type of mismatch when using labware from the Opentrons labware library. This is helpful when new users are still getting used to loading labware.

**Comment by SyntaxColoring** [comment]
Thanks for reporting this. We agree: this is confusing, and the API should guard against this mistake.
