### ISSUE TITLE
Batch Edit Mix: E2E test coverage

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/opentrons#7561]
This ticket is a placeholder, once we define testing criteria for Batch Edit Mix we can add it here!

This has to be divided into two -- multiselect and advanced transfer settings

**Comment by anthonywilleee** [comment]
this particular e2e test will be manual 3-4 days. if devs can add properties will give automation script to it

**Comment by reachojhaneha** [comment]
#7827 closes this
