### ISSUE TITLE
Add Import / Export Event tracking to Mixpanel Web Apps

### ISSUE THREAD

**Issue by anthonywilleee** [Opentrons/opentrons#7605]
As a Product Manager (and as anyone on the product dev team), I would like to track events for import / export in PD, so that I can gain more insight into usage and behavior and help inform decision making.

As a start, It'd be great if we could track Import / Export as events in Mixpanel Web Apps project.  But, to make this more useful, I'd like to explore what other things we can tie to these events (similar to how we can break down "save step" into various specific data).  This , I hope, will help us understand a little more the characteristics and life of an individual protocol.  

Some related things that would be interesting - 

- number of steps in an imported or exported protocol

- composition of steps in an imported or exported  protocol

- protocol names and meta data for an imported or exported protocol

- Some kind of ID of the protocol so we can track whether steps were added or deleted? Would be cool to give a protocol an analytics ID so we can track it... we do have the created timestamp from fileMetadata. In the analytics middleware, this timestamp is reported as __dateCreated in a saveStep event

- Import could tell us % of users who just import and don't do any saveStep stuff

- Maybe add analytics for how many people migrate a file vs abandon import at file migration

**Comment by sanni-t** [comment]
Closing as outdated
