### ISSUE TITLE
feat(robot-server,api): protocol upload api uses new models

### ISSUE THREAD

**Issue by amitlissack** [Opentrons/opentrons#7648]
# Overview

In `protocols.runner.json_proto.models` are pydantic models of the PD/JSON protocol schema. These were mostly generated as demonstrated in https://github.com/Opentrons/opentrons/pull/7541. 

The robot-server's `/protocols` endpoint returns a `ProtocolResponseAttributes` including `RequiredEquipment` and `Metadata`. We should instead use the the new models in `protocols.runner.json_proto.models.` 

This would standardize our data format on JSON protocol schemas.

# Acceptance criteria

- [ ] `ProtocolResponseAttributes` contains a `protocols.runner.json_proto.models.json_protocol.Model` 
- [ ] (bonus) move modules from this package `protocols.runner.json_proto.models` to a less deep location or even to `shared-data`

**Comment by SyntaxColoring** [comment]
Moving this back to the backlog because after a discussion, we don't feel like right now is the right time to work on this.

**Comment by mcous** [comment]
No longer applicable
