### ISSUE TITLE
Accordion steps: 1 - robot calibration

### ISSUE THREAD

**Issue by asogluizzo** [Opentrons/opentrons#7663]
**Background**

After a user uploads a protocol, they will be greeted to a series of accordion steps to ensure robot and deck are set up correctly.  The first accordion and focus of this ticket is robot calibration.  Follow link to frame here: https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Labware-Calibration?node-id=3205%3A47

Please note, screen below is for easy reference only. Consult the source link above to ensure you're looking at the most up to date screens

### **Step 1 Accordion**

![Screen Shot 2021-07-06 at 11.17.44 AM.png](https://images.zenhubusercontent.com/5f772bd73389cd8dbeb34a48/9ba27f48-5f7a-431e-be4b-ef09b7439954)

**Acceptance Criteria**

* All following AC's are for JSON protocols at this time. 
* All components are thoroughly unit and functionality tested

- [ ] If user expands Step 1 accordion, they will see a title section with a header, sub-header copy, and a right-justified link to [robot calibration help modal](https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Labware-Calibration?node-id=3309%3A5571). 
- [ ] "Proceed to Module Setup" Button is enabled if users have completed all calibration steps. This button is disabled if any calibration steps are not successfully completed. There will be a tooltip for disabled button (copy TBD @emilywools) 
- [ ] Users are able to collapse this section and move to other sections (e.g. step 2 module set up) even if CTA is disabled. 
- [ ] CTA button will display "Proceed to Module Setup" if there are modules associated with the protocol, or "Proceed to Labware Setup" if there are no modules associated with protocol
- [ ] Clicking the "Proceed to Module Setup" or "Proceed to Labware Setup" button will collapse the current section and proceed user to the next section
- [ ] A green check icon is displayed with accompanying text on the collapsed step if that calibration step is complete (see [figma frame](https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Labware-Calibration?node-id=3010%3A27390)). a "attention needed icon" is displayed if user has navigated away from this step while not complete @emilywools 
- [ ] For each calibration step within the Step 1 accordion, a green check icon is displayed if there is data stored in that value. If not, an empty circle icon is displayed. 
- [ ] @emilywools different treatment needed if no pipette is attached.
- [ ] At any point that user clicks the top right "x" to close out of the protocol, they will get a [confirm close confirmation screen / modal](https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Labware-Calibration?node-id=3205%3A152)

_Deck Calibration_

- [ ] If deck has been calibrated (i.e., there is a stored calibration value for the item), user will see a green check icon. Note, deck calibration will persist once calibrated, unless a user initiates a factory reset (in this case, it will clear the deck cal and the user will have to redo it before they can proceed to upload protocols).
- [ ] If there is no stored calibration value for the deck, display an empty circle icon.
- [ ] if the deck is not calibrated we have gating scenarios that prevent the user from proceeding. See this [figma link](https://www.figma.com/file/nbDHskbW5zaXwtrLvEIKVj/calibration-overhaul?node-id=84%3A770). @emilywools - follow up on this

_Required Pipettes_

- [ ] This section displays required pipettes as determined by the uploaded protocol.  The left/right mount only displays if a pipette is required in that mount per protocol
- [ ] The user will see green check icons if pipettes are connected and have calibration data. if the correct pipette is attached (and in the correct mount), and the app has stored values, it will display a green check mark.
- [ ] If a Left or Right pipette has not been calibrated, we will kick off that flow here

_Required Tip Length Calibrations_

- [ ] User will see tipracks contained in the protocol sectioned underneath the appropriate pipette header (if a tiprack is used in multiple pipettes, it will display under each)
- [ ] Calibrated tipracks will have a green check icon, as well as calibrations z value 
- [ ] Calibrated tipracks have a link directing users to recalibrate if they so desire. This kicks off the calibration workflow.
- [ ] Non-calibrated tipracks have an empty circle icon, and a button with CTA to "Calibrate Now." This triggers calibration workflow
- [ ] Load state is displayed when loading required tip length calibrations (see [figma frame](https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Labware-Calibration?node-id=3519%3A0))

**Comment by emilywools** [comment]
_Outstanding tip cal questions_

tip length calibration is different than tip rack calibration. Tip length calibration is the z distance between the top of the tip and the bottom of the pipette nozzle. the value is meant to establish the value that is required for the tip to adhere to the nozzle. this is a value associated with Robot Calibration.

The measurement displayed for a tip length calibration is the z value. 

Tip rack calibration is part of the labware setup experience and is not part of robot calibration.

**Comment by emilywools** [comment]
**_Outstanding deck calibration questions_**

_When if at all does a calibration "expire"? (i dont think it does, but want to confirm)_
It does not expire. If a user initiates a factory reset it will clear the deck cal and the user will have to redo it before they can proceed to upload protocols.

_What happens if deck is not calibrated? does this launch a deck calibration workflow, and if so, what does that look like?_
if the deck is not calibrated we have gating scenarios that prevent the user from proceeding. [See this figma link](https://www.figma.com/file/nbDHskbW5zaXwtrLvEIKVj/calibration-overhaul?node-id=84%3A770)
_How do we know when to display a check or an empty circle?_
empty circle:

1. there is not a store calibration value for the deck, a given pipette or a required tip length
2. the correct pipette is not attached

green check:

1. there is a stored calibration value for the item

**_Outstanding required pipettes questions_**

_Does left mount / right mount always display, and if no pipette display "none"? Or do we only display Left/Right mount if there is a pipette?_
please hold, trying to get this info for you

_If a Left or Right pipette has not been calibrated, do we kick off that flow here?_
Yes

_How do we know whether to display a check or an empty circle?_
if the correct pipette is attached (and in the correct mount), and the app has stored values, it will display a green check mark.


@b-cooper i am not sure how we handle robot calibration check on the protocol upload page today, do you happen to know?

**Comment by b-cooper** [comment]
@emilywools, currently we don't expose the Robot Calibration Check anywhere in the protocol upload page. It is only accessible from the Calibration Card on the robot page. 

One part of the existing Protocol Info page that isn't yet captured in the new designs is the different callouts for missing pipettes or inexact matches (e.g. p300 Single GEN1 specified in protocol, p300 GEN2 attached).  

A missing pipette currently has a CTA to the attach pipette flow like this:
![Screen Shot 2021-07-07 at 2.57.29 PM.png](https://images.zenhubusercontent.com/5e1e15beea955f9181a402d3/2f23b5b5-a12f-4e02-9cf6-15b29d8716c2) 

An inexact match has an info link to an article explaining things.  link is [here](https://support.opentrons.com/en/articles/3450143-gen2-pipette-compatibility) for reference
![Screen Shot 2021-07-07 at 3.14.53 PM.png](https://images.zenhubusercontent.com/5e1e15beea955f9181a402d3/0715e9fd-eafc-49ed-857f-cd192a98d6c2)
