### ISSUE TITLE
Accordion step 2: Sometimes displayed module setup

### ISSUE THREAD

**Issue by asogluizzo** [Opentrons/opentrons#7664]
Module setup is the second step of the revamped protocol upload accordion. It will only display if the uploaded protocol contains a module to set up, if it does not, this step will be skipped. See figma file for designs [here](https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Labware-Calibration?node-id=3205%3A412)

The below screenshot is for easy reference, and may be subject to change. Please refer to the above link for final designs:

![Screen Shot 2021-07-14 at 2.56.42 PM.png](https://images.zenhubusercontent.com/5f772bd73389cd8dbeb34a48/6ee0f518-89a8-4630-9975-2af2ea638382)

Acceptance Criteria:

Note: For purposes of this ticket, this flow applies to JSON protocols only. Python protocol support will be added at a later time

- [x] Step 2 Module set up displays if (and only if) a module is required in the uploaded protocol
- [x] If no modules are present in the protocol, the module set up step will not display (labware setup thus becomes step 2) see [figma](https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Labware-Calibration?node-id=3010%3A27390)
- [x] User can expand and collapse module set up step, and/or move to other steps at anytime, even if not complete
- [ ] User is prompted to place module(s) as shown in deck map, and to plug in and power up the module via OT-2 USB port(s)
- [ ] The deck map will display a visual of the required module(s) in the correct spot on the deck map per the protocol
- [ ] If module is not connected, it will display with a red status and "Not Connected" description ([figma](https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Labware-Calibration?node-id=3205%3A412))
- [ ] Once a module is connected, it will display with a green status and "connected" description ([figma](https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Labware-Calibration?node-id=3205%3A522))
- [ ] User will see a "Proceed to Labware" CTA/Button on the bottom of this step. If modules are required but not connected, this button will be disabled. If required modules are connected, this button will be enabled
- [ ] If multiple modules are called for, a "Multiple Modules Help" callout linking to a help modal will appear on the right side of the step, along with some additional copy in the description ([Modal](https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Labware-Calibration?node-id=3283%3A10013)) ([Step with add'l copy](https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Labware-Calibration?node-id=3283%3A10013)).  Examples of different FPO module configs can be found in Figma [here](https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Labware-Calibration?node-id=3283%3A10013)

**Comment by emilywools** [comment]
the only thing that is worth calling out here, for background info, is that the module has to be plugged in to the wall (or power strip or some external power source), powered on, AND connected via USB to the robot.
