### ISSUE TITLE
Upload protocol to http session instead of RPC 

### ISSUE THREAD

**Issue by asogluizzo** [Opentrons/opentrons#7666]
This ticket will be used to capture CPX dependencies needed to enable the rollout of protocol upload revamp ([7633](https://app.zenhub.com/workspaces/app--ui-5f6248dba845b000139aa767/issues/opentrons/opentrons/7633))

The protocol upload revamp (along with [labware position check](https://app.zenhub.com/workspaces/app--ui-5f6248dba845b000139aa767/issues/opentrons/opentrons/7635)) will present users with a clear mental model and step by step process for successfully setting up a protocol run. You can see the basic flow in the screenshot below.

This flow should be rolled out for both JSON and Python protocols concurrently, and in order to do so we have some dependencies on CPX work with protocol engine, specifically:

- Protocol Upload Response parity between JSON and Python. When a protocol is sent to POST'ed  to `protocols/`, the successful response JSON should adhere to the protocol JSON Schema. JSON protocol schema version 6 will include affordances to capture all PE command concepts in JSON ([Protocol Schema V6 doc](https://opentrons.atlassian.net/wiki/spaces/RPDO/pages/edit-v2/694387662?))
- New endpoints are needed that mimic the functionality of calibration endpoints. The should be nested within a `session` resource and be accessible via a labware's unique identifier within the protocol (e.g. GET or POST to `sessions/:id/offsets/:labwareId`

![Screen Shot 2021-07-27 at 3.11.30 PM.png](https://images.zenhubusercontent.com/5f772bd73389cd8dbeb34a48/185d9b96-48f0-4f34-a2fc-aa790cf78396)

**Comment by asogluizzo** [comment]
This will include back and forth with CPX to ensure we can backup the 3 accordion views

**Comment by mcous** [comment]
Stale ticket, superseded by other work
