### ISSUE TITLE
Connectivity: No Robots Found

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#768]
As a Run App user, I would like to know if the Run App was unable to find any robots, so that I know to either plug one in, check my wifi, or retry searching.

## Acceptance Criteria
- If the Run App is not aware of any robots, and is not actively searching for robots, display "No robots found!"
- Display copy: "If you haven't set up wifi on your robot, please connect it by USB"
- Display "Try Again" button
- "Try Again" button should initiate a new connectivity search

## Design
https://projects.invisionapp.com/share/V5FI4I26QWD#/screens/275374441

**Comment by mcous** [comment]
Closed by #775
