### ISSUE TITLE
PD bug: Indeterminate tooltip is empty

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#7711]
tooltip of Indeterminate state tip position , Touch tip and blowout in batch edit mix form is empty.
<img width="1377" alt="Screen Shot 2021-04-25 at 10 27 55 PM" src="https://user-images.githubusercontent.com/39049853/116002069-7d33c180-a615-11eb-8006-47615ba9be7f.png">

**Comment by reachojhaneha** [comment]
same with blowout also: empty tooltip for indeterminate state.
<img width="1418" alt="Screen Shot 2021-04-25 at 10 41 18 PM" src="https://user-images.githubusercontent.com/39049853/116002438-5bd3d500-a617-11eb-925c-63ae2fd678e2.png">

**Comment by shlokamin** [comment]
I'm not able to reproduce this issue for touch tip, I am able to see the issue for tip position and blowout though
