### ISSUE TITLE
LC: Custom Tip Racks auto-suggested display name should use the Tip Rack name format

### ISSUE THREAD

**Issue by anthonywilleee** [Opentrons/opentrons#7727]
The auto-suggested display name should use the Tip Rack name format

-  expect this to autocomplete in file section (this is more of a reminder ticket to double check)

![Screen Shot 2021-04-26 at 3.00.33 PM.png](https://images.zenhubusercontent.com/5f772bd73389cd8dbeb34a48/22b93241-bfa7-4d15-92a4-a8b940ba2c1e)

## Notes

What's the Tip Rack name format? Some examples:

```
GEB 96 Tip Rack 10 µL
GEB 96 Tip Rack 1000 µL
Opentrons 96 Tip Rack 10 µL
TipOne 96 Tip Rack 200 µL
```

So it's `{brand} {number of tips} Tip Rack {volume} µL`.

**Comment by IanLondon** [comment]
existing display name machinery handles tip racks just as we want ✔️
