### ISSUE TITLE
bug: Canceling an infinite-looping protocol leaves the OT-2 unconnectable

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#7741]
# Overview

If you're running a protocol on the OT-2, and that protocol gets stuck in an infinite loop, trying to cancel the protocol will leave the whole OT-2 in a weird unconnectable state.

# Steps to reproduce

Run this protocol on an OT-2 and try to cancel it.

```python
metadata = {
    'apiLevel': '2.9'
}

def run(protocol):
    tip_rack = protocol.load_labware('opentrons_96_tiprack_300ul', 8)
    pipette = protocol.load_instrument('p300_multi_gen2', 'left')

    if not protocol.is_simulating():
        while True:
            pass

    pipette.pick_up_tip(tip_rack.wells()[0])
    pipette.drop_tip(tip_rack.wells()[0])
```

# Current behavior

1. Canceling will give you an infinite spinner on the Run tab in the Opentrons App.
2. If you close and reopen the Opentrons App, the "Connect" button and the toggle next to the robot's name won't do anything. The "Connect" button will show an infinite spinner.
3. Most robot controls in the Opentrons App will be disabled.
4. Eventually, you'll get a "Could not connect to robot" dialog.

# Expected behavior

Canceling an infinite-looping protocol should behave as if you're canceling a well-behaved protocol. The cancelation should be reflected promptly in the Opentrons App. The robot should be usable after the cancelation, as normal.

# See also

* #6126, which is about the lack of timeout/cancel when infinite-looping protocols are *simulated.*
* #7742, which is arguably a problem caused by the same underlying architecture problem as this issue: we don't run protocols in their own processes, so they're hard to clean up, in nontrivial cases.

**Comment by SyntaxColoring** [comment]
There's one more ticket on infinite protocols that we should find and link this to.

**Comment by SyntaxColoring** [comment]
I haven't looked at the code, but here's my technical understanding of the problem, gathered from internal chats:

* We implement protocol cancelation by having `opentrons`-controlled code check an "is canceled" flag. If the protocol has been canceled, the `opentrons`-controlled code raises a special exception.
* The exception bubbles up through the user-written protocol code to terminate it.
* Protocols normally call into `opentrons`-controlled code frequently, so this works.
* On the other hand, infinite-looping protocols (and probably other kinds of "weird" protocols) will rarely, or never, call into `opentrons`-controlled code. So the exception will never be raised.
* The robot is left in a weird unconnectable state because the ongoing thread occupies one of the RPC thread slots? (I don't really get this part.)

**Comment by mcous** [comment]
Fixed in v5
