### ISSUE TITLE
bug: X/ Y offset in 4.2.1

### ISSUE THREAD

**Issue by Gyliann** [Opentrons/opentrons#7745]
# Overview

An X/Y offset is seen while running protocols, despite multiple calibration attempts. 

# Steps to reproduce

Currently can't reproduce 

# Current behavior

The calibration is off a couple mm or more in the X/Y direction when the protocol is running

# Expected behavior

The protocol should run without a X/Y offset

**Comment by mcous** [comment]
Closing as unable to reproduce
