### ISSUE TITLE
LC: Labware is too big for slot error

### ISSUE THREAD

**Issue by howisthisnamenottakenyet** [Opentrons/opentrons#7792]
## Acceptance criteria
- [ ] Add a new error that shows when the labware footprint is too big for a slot `MAX_X_DIMENSION = 129` `MAX_Y_DIMENSION = 87` (error will trigger if over the max)
- [ ] New error links to the labware definition request form
- [ ] Remove the old error that showed when labware is too big or small for a slot `MIN_X_DIMENSION = 127` `MIN_Y_DIMENSION = 85`
- [ ] E2E test updated to validate too big error is triggered

@Kadee80 - can you add bounds for this?

## Design
![image.png](https://images.zenhubusercontent.com/5e27344f9aca8806bc57bc3b/99edd0ea-eaad-4740-93fe-3c485c46b870)

**Comment by Kadee80** [comment]
MAX_X_DIMENSION = 129 MAX_Y_DIMENSION = 87
