### ISSUE TITLE
Protocol engine: Basic JSON protocol upload over HTTP

### ISSUE THREAD

**Issue by sanni-t** [Opentrons/opentrons#7816]
# Overview

As an OT-2 user, I want to use an HTTP endpoint to send a single basic JSON protocol file to the robot.
Related to: #7808 

# Acceptance criteria

- [ ] a `/protocol_upload` http POST endpoint that is able to fetch the protocol file as form data
- [ ] the robot-server, upon receiving the request with the file, sends the file to Protocol runner which translates, extracts metadata and returns appropriate response* data to robot-server. The protocol runner does all things necessary to prepare the protocol in order to be run using P.E (covered in another ticket.)
- [ ] *Appropriate response to robot-server should include:
- Metadata
- Labware
- Handles to get:
-- Labware definitions
-- Protocol steps (Run log)
-- Start protocol (or protocol session)

# Out of scope for this ticket
- Features related to protocol simulation. Since this ticket relates to JSON protocols only, we should be able to implement the protocol upload w/o simulation.

**Comment by amitlissack** [comment]
Important to keep in mind that this functionality already exists in the robot-server.

**Comment by mcous** [comment]
This ticket was implemented by standing up a separate, feature-flagged router to avoid collision with any of the existing (working) HTTP protocol upload beta stuff.

All stuff about "metadata" in the original ticket was punted on in favor of a separate ticket about protocol simulation
