### ISSUE TITLE
bug: PD crashes when adding a second temperature step with I will pause later 

### ISSUE THREAD

**Issue by Gyliann** [Opentrons/opentrons#7819]
# Overview

When creating a protocol in Protocol Designer, if you add a second temperature step and then select I will build a pause later, PD crashes 

# Steps to reproduce

Add temperature module to Protocol Designer Protocol 
Add a temperature step and save it 
Add a new temperature step and save it as I will build a pause later 
The screen of PD should turn white 

# Current behavior

Protocol Designer crashes and doesn't save any of the steps created 

# Expected behavior

The temperature step saves properly

**Comment by IanLondon** [comment]
In `FormAlerts` L54, `getHydratedUnsavedForm` selector returns `null` but is expected to return a form. Possibly a timing issue with thunk actions?
