### ISSUE TITLE
Bug: Pipette moves too low when calibrating labware

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#790]
Currently, robot moves too low when calibrating labware, potentially crashing into labware

## Issue:
Expected: Pipette moves approximately to top of labware
Observed: Pipette crashes into deck

## Environment
Robot: Small Smoke (commit 321538)
Run App: v3.0.0-mac-2018-02-07_20-18-v3a-3210538
Protocol: multiple, including basic logo.py
[logo.txt](https://github.com/Opentrons/opentrons/files/1709577/logo.txt)

**Comment by andySigler** [comment]
fixed in PR #774
