### ISSUE TITLE
Bug: Pipette not proceeding to second tiprack during calibration

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#792]
Currently, pipette is not proceeding to second tiprack during calibration

## Issue: 
Expected: After calibrating first tip rack, robot moves to calibrate second tip rack
Observed: Pipette does not move to second tip rack 

## Environment:
Robot: Mikebot (commit 321538)
Protocol:
Serial_dilution_OT2_ekker_v2.txt

**Comment by btmorr** [comment]
@umbhau Is this still happening in the new version of the run app? Can you add the run app version to the "Environment" heading?

**Comment by umbhau** [comment]
Now unable to recreate.
