### ISSUE TITLE
refactor(engine): pause HardwareAPI when engine is paused

### ISSUE THREAD

**Issue by sanni-t** [Opentrons/opentrons#7923]
## Overview

[Note: this ticket is under investigation to determine if this story/spec is desired]

As a JSONv6 protocol operator, when I pause my protocol run, I would like the robot to stop moving as soon as possible.

## Acceptance criteria

- [ ] If a `ProtocolEngine` is paused, motion stops as soon as the hardware control layer is able to stop the motion
    - This may be in the middle of a `ProtocolEngine` command

We will not be implementing a new command or run status string for this change, just the ProtocolEngine <> HardwareAPI interactions when pauses and resumes happen.

## Implementation notes

To implement this behavior, we would add a call to `self._hardware_api.pause(HardwarePauseType.PAUSE)` in `ProtocolEngine.pause` and a call to `self._hardware_api.pause(HardwarePauseType.RESUME)` in `ProtocolEngine.resume`. This will be _in addition to_ the existing action dispatch, which will pause the queue worker, update statuses, etc.

This is exactly what the `LegacyContextPlugin` that translates PAPIv2 runs to PE runs does, so the implementation can more-or-less be cut-and-pasted over. We should take care to avoid interference with #9125.

This nice thing about this change is that while the Hardware API _can_ be paused, it's no longer the mechanism by which the protocol run pause is fundamentally accomplished, so it doesn't violate the architectural reason for ProtocolEngine existing, even though it might feel like it at first glance after years of the HardwareAPI being fundamentally in charge of run pauses

**Comment by mcous** [comment]
Ticket under investigation as a potential 6.1.0 release requirement

**Comment by mcous** [comment]
Discussed this with @SyntaxColoring and @sanni-t, going to move forward with this as a 6.1.0 requirement based on the goal of achieving as much parity as possible between JSONv6 execution and JSONv5 execution unless we have a strong reason (e.g. a bug) to avoid parity. We could not identify a strong reason to avoid parity for the 6.1.0 release, so we're going to move forward with this ticket accordingly.

We do not anticipate any architectural problems with implementing this behavior as spec'd. If we _do_ hit any show stoppers, the current behavior of command-level-pauses is ok, but would require additional documentation.
