### ISSUE TITLE
Bug: Multichannel does not raise before moving

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#794]
Currently, the multichannel pipette does not raise before moving, potentially crashing into labware.

## Issue: 
Expected: second pipette (multi channel) should raise before moving across the deck
Observed: multichannel does not raise, hitting any labware in the way (esp. tube racks)

## Environment: 
Robot: Mikebot (commit 321538)
Protocol: 
[Serial_dilution_OT2_ekker_v2.txt](https://github.com/Opentrons/opentrons/files/1709162/Serial_dilution_OT2_ekker_v2.txt)

Note: Ben attempting to reproduce with latest branch (including Andy’s fix). May be quick follow-on to Andy’s current work.

**Comment by mcous** [comment]
Related (I think): #681

**Comment by andySigler** [comment]
This was addressed in PR #774
