### ISSUE TITLE
LC: Show footprint section for non-OT tube racks

### ISSUE THREAD

**Issue by anthonywilleee** [Opentrons/opentrons#7977]
![Screen Shot 2021-06-22 at 9.09.35 AM.png](https://images.zenhubusercontent.com/5f772bd73389cd8dbeb34a48/4d0de6f1-8c38-4b37-8ca8-cd2251feea01)

Acceptance Criteria:
- Footprint section is displayed between regularity and total height sections of tube rack creator form
- e2e selectors added as needed

**Comment by IanLondon** [comment]
Closed by #8060 with no additional work needed
