### ISSUE TITLE
LC: Volume section update description for tube racks

### ISSUE THREAD

**Issue by anthonywilleee** [Opentrons/opentrons#7980]
![Screen Shot 2021-06-22 at 9.22.27 AM.png](https://images.zenhubusercontent.com/5f772bd73389cd8dbeb34a48/353e54fd-4269-4cdc-87b5-d2545638e95b)

Acceptance Criteria:
- Update description from well to tube in volume section
- e2e selectors added appropriately

Notes:
- Unit of measure is uL
- In future, consider error if uL are under certain volume

**Comment by IanLondon** [comment]
already has dynamic wells/tubes copy in production
