### ISSUE TITLE
LC: Update caption in Check Your Work section

### ISSUE THREAD

**Issue by anthonywilleee** [Opentrons/opentrons#7985]
![Screen Shot 2021-06-22 at 9.55.00 AM.png](https://images.zenhubusercontent.com/5f772bd73389cd8dbeb34a48/c7cc909e-d169-45f0-8896-04284031fec0)

Acceptance Criteria:
- Update caption below render from well to tube
- e2e selectors added as needed

**Comment by IanLondon** [comment]
well/tube text already works in this section in production ✔️
