### ISSUE TITLE
LC: Rack & Tube meta data fields in Description section

### ISSUE THREAD

**Issue by anthonywilleee** [Opentrons/opentrons#7986]
![Screen Shot 2021-06-22 at 10.20.46 AM.png](https://images.zenhubusercontent.com/5f772bd73389cd8dbeb34a48/59b84336-5efc-4ad1-a147-16f7fda55129)

## Labware Definitions - where rack vs tube brands are represented

https://labware.opentrons.com/opentrons_10_tuberack_nest_4x50ml_6x15ml_conical is an example of different brand/manufacturer for tubes vs rack.
- Rack is "Opentrons" brand, this is the top-level `brand.brand` key in the def.
- Tubes are  "NEST" brand, represented in `groups[i].brand.brand` in the def.

Then in LC:
- the "Rack Brand" field is just a new label for the existing LC "Brand" field
- the "Tube Brand" field is new and should populate `groups[i].brand.brand` for each `i` in `groups`. We might want to call this field `groupBrand` so it's generic, bc though right now it's only for tubes, we might want to set this later for other stuff as well.

## Acceptance Criteria:
- `brand` and `brandId` continue to work the same as for any other labware, but when Tube Rack is selected, the label is `Rack Brand` not just `Brand`
- Add new fields `groupBrand` and `groupBrandId`. They are required for tubeRack labware type, but should be null for all other labware types
- Wire up `groupBrand` and `groupBrandId` into `fieldsToLabware` and `labwareDefToFields`
- For non-custom tube racks, only "Tube Brand" field (+ corresponding brand id) should be visible, and "Rack Brand" (with its own corresponding brand id) should not be shown.
- In contrast, for custom tube racks, both Rack Branch and Tube Brand should be shown (plus both fields' corresponding brand ID field)
- e2e selectors added as needed

**Comment by IanLondon** [comment]
Not a tube rack: Just "Brand" `brand`

Opentrons tube rack: Just "Tube Brand" `groupBrand` (we know the `brand` is Opentrons)

Custom tube rack: Both "Rack Brand" `brand` and "Tube Brand" `groupBrand`
