### ISSUE TITLE
LC: New PDF for definition test for all labware (removing cal crosses)

### ISSUE THREAD

**Issue by anthonywilleee** [Opentrons/opentrons#7989]
We no longer need to have cross-check in custom labware def PDF / .py file

This ticket is to update that PDF for all labware, to be done alongside Custom Tube Racks.

# PDFS
[Tip Rack test guide (3).pdf](https://github.com/Opentrons/opentrons/files/6895205/Tip.Rack.test.guide.3.pdf)
[Labware test guide (1).pdf](https://github.com/Opentrons/opentrons/files/6823661/Labware.test.guide.1.pdf)

# Acceptance Criteria:
- New PDF is generated for custom tube rack def test
- New PDF is generated for all other custom labware definitions, except for custom tip racks

# Blocked

Do NOT change the main PDFs in production until just after the release.

**Comment by IanLondon** [comment]
Done! Not in GH, so no PR
