### ISSUE TITLE
Protocol Engine: Allow v2 PAPI protocol execution using old infrastructure

### ISSUE THREAD

**Issue by sanni-t** [Opentrons/opentrons#8002]
### As a user, I want to be able to send a v2 PAPI protocol and understand that it will be executed using the old protocol handling infra.

# Acceptance criteria

- [ ] The protocol is recognized as a v2 protocol to be run without P.E.
- [ ] The protocol is simulated correctly
- [ ] The protocol executes exactly as it does currently (in the non-PE infrastructure)

**Moved to #8374**
- ~The protocol is able to be paused, resumed & canceled as it currently does~
- ~The Run Log is still available~

# Implementation details

- The protocol is recognized as a v2 protocol by the HTTP server. The app doesn't need to know whether it's v2 or v3. The protocol is uploaded to the same HTTP endpoint
- This would look something like the current HTTP API beta endpoint that accepts protocols over /protocols and executes it without the protocol engine

**Comment by mcous** [comment]
Assigning myself to this ticket, but I'm only doing research at this phase, so don't let that stop you from assigning yourself and thinking about it, too
