### ISSUE TITLE
bug: notify-server cannot send hardware events

### ISSUE THREAD

**Issue by julian-hausner** [Opentrons/opentrons#8023]
# Overview

When subscribing to the notify-server with the "hardware_events" topic no events are parsed to the subscriber.

# Steps to reproduce

Subscribe to the notify-server with
`python3 -m notify_server.app_sub -s tcp://<ROBOT_IP>:5555 hardware_events
`
Trigger door sensor to trigger a hardware event.

# Current behavior

No event is parsed by the notify-server. [short_api.log](https://github.com/Opentrons/opentrons/files/6737306/short_api.log) shows the following:

> Jun 28 05:19:38 OT2CEP20210408B13 opentrons-api[243]: New state: 'stopped'
Jun 28 05:19:38 OT2CEP20210408B13 opentrons-api[243]: New state: 'paused'
Jun 28 05:19:38 OT2CEP20210408B13 opentrons-api[243]: Updating the window switch status: closed
Jun 28 05:19:38 OT2CEP20210408B13 opentrons-api[243]: Errored during door state event callback
                                                      Traceback (most recent call last):
                                                        File "usr/lib/python3.7/site-packages/opentrons/hardware_control/api.py", line 130, in _update_door_state
                                                        File "usr/lib/python3.7/site-packages/robot_server/hardware_wrapper.py", line 70, in _publish_hardware_event
                                                      AttributeError: 'Depends' object has no attribute 'send_nowait'

Might be caused by [this](https://github.com/tiangolo/fastapi/issues/1881) leading to the dependency of the hardware_wrapper being invoked instead of the harware_wrapper.

# Expected behavior

hardware_wrapper should be invoked to trigger a hardware_event, which should then be parsed to all topic subscribers.

**Comment by SyntaxColoring** [comment]
Thanks for the report and pointer to that FastAPI issue. We'll look into this. 👀
