### ISSUE TITLE
App Update: View App Version

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#809]
As a user, I would like to be able to see what app version I am on, so that I know when to upgrade.

## Acceptance Criteria
- [x] User able to view the current app version number on the 'About' page.
- [x] 'Update' | 'Updated' link displayed
    - If current app version matches latest version, display inactive 'Updated' text
- Note link function (dialogue to update modal) covered in #810

## Design:
- https://projects.invisionapp.com/d/main#/console/13154070/277137239/comments

## Dependencies

- #808 (Create the 'About' page)

**Comment by umbhau** [comment]
Closing; merged with #808

**Comment by mcous** [comment]
Closed by #896
