### ISSUE TITLE
App Update: Dialogue Box & Initiate Update

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#810]
As a user, I would like to be given the option to update to the latest run app version.

## Acceptance Criteria

- [x] 'Update' | 'Updated' link displayed in 'Information' card on 'App Settings' page
    - If current App version matches latest version, display inactive 'Updated' text
    - If current App version is behind latest version, display 'Update' link'
- [x] Clicking button opens a app update alert modal
    - Alert modal includes latest available app version number
    - Alert modal includes option to cancel ('not now') or 'update'
- [x] Selecting 'Update' initiates an app update

## Dependencies

- #870 (Publish release information)
- #809 (Create the App Information card)
- #TBD (Plumbing so app can talk to app-shell)

## Design

- https://projects.invisionapp.com/d/main#/console/13154070/277137159/comments

**Comment by mcous** [comment]
Closed by #1125
