### ISSUE TITLE
module set up steps in Protocol upload flow

### ISSUE THREAD

**Issue by anthonywilleee** [Opentrons/opentrons#8103]
provide instructions / a guide for users to set up their modules on their deck, aside from "put them on the deck"

design work needed
TC: need to ensure the lid is open for robot movement, and need to make sure the latch is engaged after putting labware inside.
Mag: clamp needs to be engaged
H/S: tbd but will require module setup + labware setup steps

**Comment by emilywools** [comment]
for now, we only need to guide users for the mag module. we will need to revist and perhaps adjust these designs when we do h/s work. 

https://opentrons.atlassian.net/browse/UX-3

https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Labware-Calibration?node-id=3283%3A10013
