### ISSUE TITLE
App Update: Update Icon in Nav and Sidebar

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#811]
As a run app user, I would like a visual indicator that I need to update my app in the nav, so that I know to check out the 'about' tab for the latest version.

## Acceptance Criteria
- When user's Run App version is behind the latest Run App version:
-- Display visual indicator (orange dot) on 'About' icon in left nav tab 
-- Display visual indicator (orange dot) on 'About' icon sidebar nav

## Design
- https://projects.invisionapp.com/d/main#/console/13154070/277137159/comments
- Note design does not show left nav icon or orange dot (@howisthisnamenottakenyet)

**Comment by mcous** [comment]
Closed by 1125
