### ISSUE TITLE
PD Protocols not performing delay after aspiration or dispense

### ISSUE THREAD

**Issue by ethanfjones-zz** [Opentrons/opentrons#8153]
# Overview

A delay after aspirate/dispense is not performed on the OT-2 when the command is enabled in the advanced settings of a transfer step in Protocol Designer. I looked at the OT-2 api logs and there was no mention of a delay after any aspirate or dispense. If you watch the video and review the app run print-out there is no delay. 

[no-delay.zip](https://github.com/Opentrons/opentrons/files/6864894/no-delay.zip)

In addition to the above, the following values were null in the PD protocol's JSON file: 

"aspirate_delay_mmFromBottom":null
"dispense_delay_mmFromBottom":null

This might be a red herring though. 

# Steps to reproduce

1. Create a protocol with a transfer step in Protocol Designer 
2. Enable "Delay" under the advanced settings for that step 
3. Add values in the associated fields  
4. Run protocol on OT-2

# Expected behavior

The OT-2 should perform a delay after aspirate/dispense exactly how is was programmed to.

**Comment by anthonywilleee** [comment]
Capturing next steps for this here:

We will start the next steps to release this fix mid to late September 2021. It will require:
- Migration work to change old protocol files to effectively uncheck these asp/disp delay boxes
- Testing & QA
- Clear messaging in an alert modal to explain to users what happened, and what if anything they need to do
e.g., _This bug fix addresses an issue where Asp/Disp delay was not working. If you had this setting checked, your delay was functionally 0.  To preserve your protocol behavior in this fix, we have unchecked this setting, so no action is needed on your part. Asp/Disp delay is now working if you do wish to adjust delay settings_
We can sync with Melissa here ahead of time
- This fix will Introduce a changed protocol from PD perspective, but the protocol behavior will not be changed. As a principle, we strive to preserve protocol behavior
