### ISSUE TITLE
Choose Starting Tip in App Research/Dependencies

### ISSUE THREAD

**Issue by anthonywilleee** [Opentrons/opentrons#8202]
This ticket is to establish major dependencies regarding "Choose Starting Tip" functionality in the Run App.

**What is it?**
Choose starting tip is a popular request (and seemingly a basic expectation for many customers). Essentially, this functionality means the ability for a user to start a run using a partial tip rack (in other words, starting from something other than tip position A1), so that they do not have to use a fresh tip rack each time or need to replenish the tip rack by hand, which is tedious and can risk contamination. 

**User Story**
As an Opentrons user, I would like the ability to choose my starting tip at runtime, so that I do not need to either use a new tip rack or have to manually replenish my tip rack before every run.

**Questions and Considerations**
- Introducing this functionality allows us to dip our toes into the world of runtime variables. It also presents us with many of the related challenges, such as ensuring predictability and reproducability with each protocol run. We will want to document our thinking & decisions here
- What needs to be added/changed on the protocol schema to allow for this?
- What needs to be added in the protocol engine to allow for this? (any changes to PE approach, new endpoints, etc.)

**Comment by sanni-t** [comment]
Closing as outdated
