### ISSUE TITLE
PD Deck Setup: Move & Copy Labware

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#821]
As a protocol designer, I would like to be able to move labware to different locations on the deck

## Acceptance Criteria- Move:
- [ ] User can click 'move' in the labware hover menu
- [ ] When user clicks 'move', labware takes on disabled overlay with instructions
- [ ] If user hits ESC or clicks on something that isn't a slot, UI is no longer in move mode
- [ ] User can then click 'move here' when hovering over empty deck slots
- [ ] If user moves a labware into an occupied slot, the labware switches places

## Design- Move:
![move](https://user-images.githubusercontent.com/35570080/42598418-1ee0959a-852a-11e8-8bca-730dd4817aca.png)

## Acceptance Criteria- Copy:
- [ ] User can click 'add labware' and pick existing labware from the modal
- [ ] (if we can!) User can hover over existing labware and get a pic of what it is. 
- [ ] Copy labware has disambiguation number in name

## Design- Copy:
![screen shot 2018-07-17 at 2 44 02 pm](https://user-images.githubusercontent.com/35570080/42838858-e07e5a08-89cf-11e8-9c8a-d1b9c0322495.png)

**Comment by IanLondon** [comment]
Closed (with drag-and-drop!) by PRs from @b-cooper
