### ISSUE TITLE
Labware Position Check: Generic Step Screen

### ISSUE THREAD

**Issue by b-cooper** [Opentrons/opentrons#8217]
Implement the view outlined in this figma [node](https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Protocol-Upload-Revamp?node-id=4327%3A835599)

The user goes through the appropriate steps to check their labware's A1 position

**Details**
- [ ] dynamically show the name of the labware and the slot #
- [ ] highlight the current step in the step list
- [ ] highlight the current slot/labware that the user is checking on the deck map
- [ ] show either a  single/multi channel pulse animation over the A1/1-column wells respectively
- [ ] dynamically show what slot the user is moving to next in the copy of the CTA button to proceed
- [ ] if the user needs to make an edit they can reveal the jog controls
- [ ] if there is a new offset applied the CTA copy should reflect that a "new offset" will be saved

NOTE: if the next step is "pick up tip and then move", as opposed to "just move", then the CTA copy should reflect the extra action

**Comment by mikecardarelli** [comment]
This was covered in other tickets
