### ISSUE TITLE
Identity Platform

### ISSUE THREAD

**Issue by crease-elliott** [Opentrons/opentrons#8231]
The scope of this epic includes the cloud infrastructure and integrations necessary to enable the Identity Platform MVP, as described in [this requirements doc](https://opentrons.atlassian.net/l/c/6uccyP1A). As noted in the PRD:

> All of the experiences described in the relevant [PRFAQ](https://docs.google.com/document/d/17LkWlnfFmLP8PfbAbhg70rkFwErn6tUTIK00vRqCWbQ/edit?usp=sharing) and [PID](https://opentrons.atlassian.net/wiki/spaces/RPDO/pages/823099528) should start with a common platform. Without one, features based on user identity will be reliant on bespoke backend infrastructure and therefore inevitably diverge from one another in terms of experience.

Therefore, this epic itself does not address specific user stories, but lays the foundation for further epics that will.

**Comment by SyntaxColoring** [comment]
Closing this old ZenHub epic as stale. We've moved these things to Jira.
