### ISSUE TITLE
Module Setup Accordion Step: link usb connection connection status 

### ISSUE THREAD

**Issue by b-cooper** [Opentrons/opentrons#8233]
Part of functionality that lives within the Modules Setup Accordion Step whose reqs are outlined here #7664.  The rendered modules also display whether or not the connected robot has detected a module of that type plugged in. There are two visual possibilities for the USB status overlay: "Not Connected" and "Connected" the designs are details in this figma [node](https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Protocol-Upload-Revamp?node-id=3283%3A10013) 

- [ ] Poll the robots GET /modules endpoint every 5 seconds while the Module Setup Step is mounted. This will allow us to update the UI as soon as a new module is detected by the robot's operating system. As this feature will not take advantage of the legacy RPC session, this component must manage its own poll of the GET /modules endpoint. A similar poll has been implemented already at line 100 of `AttachedModulesCard.tsx` [here](https://github.com/Opentrons/opentrons/blob/d00cbf95ceed3350566ebd2b54944d937b01ca69/app/src/pages/Robots/ModuleSettings/AttachedModulesCard.tsx#L100)
- [ ] Use the `usbPort` property of each `module` object to populate the correct contents of the new usb info overlay component. Current logic for this is implemented [here](https://github.com/Opentrons/opentrons/blob/d00cbf95ceed3350566ebd2b54944d937b01ca69/app/src/molecules/DeckMap/index.tsx#L135) for reference.
- [ ] if any of the modules required by the protocol are not detected by the robot, the main "Proceed to Labware Setup" CTA should be disabled with a hover tooltip that explains that the modules must be connected via USB to the robot, power cables plugged in, and switched on.

**Comment by jerader** [comment]
Additional acceptance criteria for this ticket, mentioned in a comment on PR #8224:

> would we be able to have this copy be dynamic based on there being 1 vs more than 1 module? so if 
> there's one module it says
>
> Plug in and power up the required module via the OT-2 USB Port. Place the module(s) as shown in the deck map.
> 
> if there are more than 1 module, it says
> 
> Plug in and power up the required module(s) via the OT-2 USB Port(s). Place the module(s) as shown in the deck map.
