### ISSUE TITLE
bug: Labware Library allows creating tube racks without a brand name, causing errors in Protocol Designer and the Opentrons App

### ISSUE THREAD

**Issue by alexjoel42** [Opentrons/opentrons#8248]
# Overview

The "brand section" on labware is necessary for it to be used in Labware Library, protocols, and the app. If you use the Tube Rack section, it won't stop you from creating labware. 

`
/definitions/brandData/properties/brand/type: should be string. ({"type":"string"})
`

# Steps to reproduce/Curren Behavior 

1. Open Labware Creator
2. Create Tube Rack (it can be 6,15, or 24 tubes)
3. Don't include brand name 
![Screen Shot 2021-08-19 at 5 24 50 PM](https://user-images.githubusercontent.com/65437763/130146274-2b0542fa-91d1-49fe-a238-4b9d3154f65a.png)
4. Export (example here: [opentrons_24_tuberack_1500ul_s.zip](https://github.com/Opentrons/opentrons/files/7017781/opentrons_24_tuberack_1500ul_s.zip))
5. If you try and load the brandless labware, you get this `#/definitions/brandData/properties/brand/type: should be string. ({"type":"string"})` error on labware creator and a labware error message on the app as well

![Screen Shot 2021-08-19 at 5 25 40 PM](https://user-images.githubusercontent.com/65437763/130146363-970a7fdf-e0ba-47dc-99bd-4de8ae42aefd.png) 

 

# Expected behavior

The software should behave like the well plates where it stops you with the error message "Brand is a required field" 

![Screen Shot 2021-08-19 at 5 31 33 PM](https://user-images.githubusercontent.com/65437763/130147073-6c7017df-357e-474a-98ad-be8b91e3e4e0.png)

# Current resolution

1. Contact Technical Support 
2. Go to JSON file
3. Locate Brand ![Screen Shot 2021-08-19 at 5 33 03 PM](https://user-images.githubusercontent.com/65437763/130147243-75733a40-f637-4114-a78a-af37bb153b03.png)
4. Replace `null` with `"Opentrons" `

**Comment by reachojhaneha** [comment]
Created custom labware with brand name and it reflected in json protocol, also created opentrons labware without brand name. Json protocol showed brand as "opentrons".
Question: while creating opentrons labware , Tube brand is not a mandatory field. Is that an expected behavior?
