### ISSUE TITLE
bug: In APIv2 docs, code block "Running A Previously-Written Protocol" is not rendered

### ISSUE THREAD

**Issue by DerAndere1** [Opentrons/opentrons#8260]
# Overview

Looking at the APIv2 docs at https://docs.opentrons.com/v2/new_advanced_running.html#running-a-previously-written-protocol the following code example is missing. Same for the rendered view of the rst at https://github.com/Opentrons/opentrons/blob/edge/api/docs/v2/new_advanced_running.rst . The missing code block is present in the unrendered file:

https://raw.githubusercontent.com/Opentrons/opentrons/edge/api/docs/v2/new_advanced_running.rst . quote:

```
.. code-block:: python
    :substitutions:

   import opentrons.execute
   from opentrons import protocol_api
   def run(protocol: protocol_api.ProtocolContext):
       # the contents of your protocol are here...

   protocol = opentrons.execute.get_protocol_api('|apiLevel|')
   run(protocol)  # your protocol will now run
```

# Steps to reproduce

Observe missing example code at https://docs.opentrons.com/v2/new_advanced_running.html#running-a-previously-written-protocol 

# Current behavior

example code block is missing from https://docs.opentrons.com/v2/new_advanced_running.html#running-a-previously-written-protocol

# Expected behavior

https://docs.opentrons.com/v2/new_advanced_running.html#running-a-previously-written-protocol should show example code block
```
import opentrons.execute
from opentrons import protocol_api
def run(protocol: protocol_api.ProtocolContext):
    # the contents of your protocol are here...

protocol = opentrons.execute.get_protocol_api('|apiLevel|')
run(protocol)  # your protocol will now run
```

**Comment by SyntaxColoring** [comment]
This is fixed now in our `edge` branch, but it might take until the next release until the fix applies to docs.opentrons.com.

Thanks again for the report!
