### ISSUE TITLE
feat: prevent developer sites of the ot-docs to be listed in google

### ISSUE THREAD

**Issue by DerAndere1** [Opentrons/opentrons#8263]
# Overview

When I searched "install python packages opentrons", the following pages showed up in the google results. I removed the https:// here:
nickcrider.github.io/ot-docs/simulate_with_jupyter/  
nickcrider.github.io/ot-docs/examples/install_module/

In case that is a developer site, I guess you want to prevent google from listing it so that all internet traffic goes to you official support page.

# Implementation details

Im no SEO specialist. In case that page is a dev site under your control, you can probably follow these steps: https://stackoverflow.com/questions/32468200/how-do-you-prevent-a-development-site-from-being-indexed . 

# Design

# Acceptance criteria

None. SEO is optional and sometimes it takes forever to get the desired results.

**Comment by SyntaxColoring** [comment]
Thanks for the report!

For anyone else finding this: Those nickcrider.github.io links do indeed point to internal developer experiments. The official public Python Protocol API documentation is at docs.opentrons.com.

We're looking into hiding the nickcrider.github.io pages from search results.

**Comment by SyntaxColoring** [comment]
[It looks like this has been resolved](https://www.google.com/search?q=install+python+packages+opentrons&oq=install+&aqs=chrome.0.69i59j69i57j69i65l3j69i60l3.858j0j7&sourceid=chrome&ie=UTF-8).

Thanks for reporting this!
