### ISSUE TITLE
calibration_manager.tip_probe should ignore tip state

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#828]
## overview

When doing a tip probe, the user is instructed by the app to add and remove tips by hand. This means that we can be "sure" that the tip state is correct for a tip probe prior to the call being made. However, changes in the tip state due to protocol simulation or tiprack calibration can change the state of an instrument such that a tip probe will fail with an `AssertionError`

Inside `calibration_manager.tip_probe`, a call to `instrument._add_tip` is made:

```py
# calibration_functions.py
# snip...
def probe_instrument(instrument, robot, tip_length=None) -> Point:
    from statistics import mean

    robot.home()

    if tip_length is None:
        tip_length = robot.config.tip_length[instrument.mount][instrument.type]
    instrument._add_tip(tip_length)
# snip...
```

`instrument._add_tip` will raise if the instrument already has a tip, which is proper behavior in the normal use case of _add_tip (during tip pickups from tip racks). However, in the context of tip probe, getting one of these raises is confusing.

### current

`calibration_manager.tip_probe` may raise because of instrument tip state

### desired

`calibration_manager.tip_probe` does not raise because of (or possibly clears out) instrument tip state

**Comment by btmorr** [comment]
#1160 causes these to no longer assert. Will want to revisit tip state protections in the future
