### ISSUE TITLE
Remove Labware calibration from Robot Configuration Reset Modal

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#8283]
remove the labware calibration checkbox from the Robot Configuration Reset ("factory reset") Modal.

![Screen Shot 2021-09-01 at 4.38.33 PM.png](https://images.zenhubusercontent.com/5f57e13054c0d9cd55c2adb3/c087033d-bc0f-4231-a5e5-9c70bb279b04)

**Comment by mikecardarelli** [comment]
Make sure this goes into the BETA branch but not Edge/4.7
