### ISSUE TITLE
bug: Pressing "CHANGE" on the Pipettes tab for a GEN1 pipette causes it to collide with deck 

### ISSUE THREAD

**Issue by Matt-Zwimpfer** [Opentrons/opentrons#8288]
# Overview
GEN1 pipettes are colliding with the deck surface as they descend after the user presses "CHANGE" on the Pipettes tab to switch in a new pipette. Currently only tested with GEN1 P300 multichannel pipettes, but suspect this impact all GEN1 pipettes.

# Steps to reproduce
1. Have robot updated to 4.1.1 or higher
2. Attach GEN1 pipette to either mount
3. Navigate to Pipettes tab on Opentrons App and click "CHANGE" for the GEN1 pipette
4. Watch the pipette as it descends

# Current behavior
GEN1 Pipette descends too far and collides with the deck

https://user-images.githubusercontent.com/69972997/131864182-0fdb1355-0fdc-4a17-ad58-d118c2c0e809.MOV

GEN2 P300 multichannel pipette lowers properly

https://user-images.githubusercontent.com/69972997/131864161-52eac5b0-4c5d-457f-8038-ac300b2330bc.MOV

# Expected behavior
GEN1 pipette should not contact the deck as it descends.

**Comment by SyntaxColoring** [comment]
Reproduced on my robot after attaching a P300 8-Channel GEN1, skipping pipette offset calibration, and then going to detach the P300 8-Channel GEN1.

My calibration data: https://gist.github.com/SyntaxColoring/62b6182ec9bbac2bac5b7dfb81b19e88

I also noticed a related problem. If you:

1. Start with a P20 Single-Channel GEN2 attached.
2. Detach it.
3. Choose that you want to attach another pipette, and select P300 8-Channel GEN1.

Then the mount will remain at its prior height, which was fine for the GEN2, but is too low for the GEN1.
