### ISSUE TITLE
Update Aluminum Block with BioRad Well Plate Labware Definition

### ISSUE THREAD

**Issue by anthonywilleee** [Opentrons/opentrons#8308]
[Opentrons 96 Well Aluminum Block with Bio-Rad Well Plate 200 µL](https://labware.opentrons.com/opentrons_96_aluminumblock_biorad_wellplate_200ul/)

[Slack thread](https://opentrons.slack.com/archives/CA0K6UV5W/p1631018003003100)

Add a new version of the Alum Block with Bio-Rad well plate to the with correct dimension to the shared labware database. 

This definition can be provided ad hoc to customers experiencing issues with the bad definition. Date for a fuller release of the correct definition TBD

![image (3).png](https://images.zenhubusercontent.com/5f772bd73389cd8dbeb34a48/b85154b8-b593-4ba4-93dc-9cd9a1f16c71)

**Comment by anthonywilleee** [comment]
@b-cooper @mikec116 -- FYI, here is the ticket for the reported bad labware definition

**Comment by b-cooper** [comment]
related to #4179

**Comment by SyntaxColoring** [comment]
Moved to Jira: RSS-208
