### ISSUE TITLE
Move Proceed to Run to outside of the Labware Setup accordion

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#8324]
Move the Proceed to Run CTA to be outside of the Labware Setup accordion. See this figma link:

[https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Protocol-Upload-Revamp?node-id=5415%3A140817](url)

Inside the Labware setup accordion, restyle the offset data and LPC CTA as shown in Figma (same link as above)

- Create a section for Data offsets. The copy will be variable if there is or is not offset data applied
- Create a tooltip for the Data offset header
- Convert the "clear offsets" text link to a secondary CTA
- Create a section for LPC and move the LPC CTA into that section

if the necessary requirements (see below) are not fulfilled, disable the Proceed To Run CTA. display a tooltip for these scenarios:

- user has not completed robot calibration or module setup

> complete required robot calibrations and connect required modules before proceeding to run

- user's protocol does not have modules

> complete required robot calibrations before proceeding to run

- user has not completed module setup

> connect and power on the required modules before proceeding to run

**Comment by b-cooper** [comment]
Closed by code written by @jerader that was merged in #8355
