### ISSUE TITLE
PAPIv3 Features/Improvements

### ISSUE THREAD

**Issue by mattwelch** [Opentrons/opentrons#8359]
We will use v3 of the Python Protocol API (PAPI) to roll out Protocol Engine. At the same time, we can consider new/additive functionality and improvements, as long as existing v2 PAPI protocols continue to run correctly. 

This epic contains proposed PAPIv3 updates.

**Comment by SyntaxColoring** [comment]
Closing this old ZenHub epic as stale. We've moved these things to Jira.
