### ISSUE TITLE
Run Detail Page: PD steps known

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#8372]
## Overview

This is a nice-to-have addition and can and should be scoped out if necessary.

Because the protocol steps are not just anticipated, we are 100% certain what they will be, instead of displaying "Anticipated Steps," if the protocol has not started yet, display "Protocol Steps" and once the protocol has started, update the copy to "Next Steps"

figma link: https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Milestone-0:-Protocol-Upload-Revamp?node-id=5629%3A145096

## Acceptance Criteria

- [ ] when a JSON protocol is loaded, the commands list label switches between "Protocol Steps" and "Next Steps" instead of just "Anticipated Steps"

**Comment by mikecardarelli** [comment]
Punting on this. We'll rework this section in the unified app/5.1.0
