### ISSUE TITLE
chore(python): don't create universal wheels for our python packages.

### ISSUE THREAD

**Issue by amitlissack** [Opentrons/opentrons#8377]
# Overview

See @mcous comment: https://github.com/Opentrons/opentrons/pull/8363#issuecomment-923504707

# Implementation details

1.
Remove this from setup.cfg in our python projects.
```
[bdist_wheel]
universal = 1
```

2.
Change the name of the wheel file to omit py2. (`poetry_python_get_wheelname` vs `python_package_version`). Make sure `make wheel` doesn't always rebuild file.

# Acceptance criteria

- [ ] shared-data/python
- [ ] hardware
- [ ] g-code-testing
- [ ] robot-server
- [ ] update-server
- [ ] api

**Comment by sanni-t** [comment]
Moved to EXEC-670
