### ISSUE TITLE
App: Look through calibration modals and replace the word "even" with "level"

### ISSUE THREAD

**Issue by anthonywilleee** [Opentrons/opentrons#8385]
We noticed some confusion with the word "even" in the the calibration flow modals during september 2021 usability testing. The designs indicate that this word should be "level," not "even"

This ticket is to make the updates in the appropriate places.

**Comment by SyntaxColoring** [comment]
This sort of contradicts our support documentation style guide:

> ***flush***: Use *level* instead, like "make sure the tip is level with the top of the well" instead of "make sure the tip is flush with the top of the well." This is based on a user interview with someone who spoke English as a second language. *Flush* meant something different. 💩

The user interview referred to was for the v4.0.0 robot calibration overhaul.

If more recent interviews have shown that *even* is in turn better than *level,* we should update style guidance.

**Comment by anthonywilleee** [comment]
I think we're saying the same thing! dont use even, use level. the word "even" wrongly showed up in the user testing mockups. we want to make sure we say level.

**Comment by SyntaxColoring** [comment]
Ah wow I must have totally misread this, sorry!
