### ISSUE TITLE
Determine http api pagination method

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#8391]
* Take inventory of which HTTP API resources are likely to need pagination
    * "Needs pagination" is itself not well-defined right now, but it probably means something like "is a collection with a potentially unbounded number of elements"
* Investigate API patterns and figure out which one is most appropriate for us (page-based vs. cursor-based, size-based vs. number-of-resources-based, HATEOAS links vs. other kinds of tokens, ...)
    *  If cursor-based, what happens if the resource that the cursor pointed to is deleted?
* Spike should anticipate future cloud-based APIs as well and determine what, if any, consistency between LAN and Cloud needs to be established

## Acceptance criteria
* Document on confluence listing prescribed first stab at pagination method, circulated and agreed to by stakeholders (AUI, CS).

**Comment by SyntaxColoring** [comment]
Some prior discussion: https://github.com/Opentrons/opentrons/pull/8006#discussion_r660179236

**Comment by mcous** [comment]
Closing as complete
