### ISSUE TITLE
question: Running protocols with Opentrons python library on PC

### ISSUE THREAD

**Issue by Marios1995** [Opentrons/opentrons#8397]
How can I run protocols on the OT-2 by having the Opentrons python library installed on my PC?

Essentially what I'm looking to achieve is to be able to write protocols like shown below and being able to run from my PC without having to upload them to the OT-2 with scp and running them there using ssh.

```
import opentrons.execute

protocol = opentrons.execute.get_protocol_api('2.11')

protocol.home()

plate =protocol.load_labware('nest_96_wellplate_200ul_flat', '2')

tiprack_1 = protocol.load_labware('opentrons_96_tiprack_1000ul',location = '1')

p1000 = protocol.load_instrument('p1000_single_gen2','right', tip_racks=[tiprack_1])

p1000.transfer(100, plate['A1'], plate['A2'])
```

**Comment by SyntaxColoring** [comment]
Hello! 👋 

**Short answer:** this isn't possible today.

**Longer answer...**

Today, the best way to do this, as you mentioned is this:

1. Upload the protocol to the OT-2 with `scp`.
2. `ssh` in.
3.  Run it with `opentrons_execute`.

In the future, there will be an HTTP API to upload and run protocols, which we hope will be a much nicer way to accomplish this.

But note that even with the future HTTP API to upload and run protocols, it's still conceptually two big steps: upload a protocol to the OT-2 and then tell the OT-2 to run that protocol. It's not feeding live *commands* from a connected PC.

We are also working on an HTTP API for live commands. But for maintainability reasons, they will be very pared-down and won't match up 1:1 with the functions that you're used to from the Python Protocol API.

It will theoretically be possible for us (or anyone) to build an implementation of the Python Protocol API that runs locally on a PC, automatically translates to live HTTP commands, and controls an OT-2 over the network. But this isn't currently on our roadmap.

Let me know if this answers your question!
