### ISSUE TITLE
COPY: Labware Position Check Copy Updates

### ISSUE THREAD

**Issue by anthonywilleee** [Opentrons/opentrons#8431]
This ticket is to ensure all copy changes finalized on 9/28 make it into the final screens.

Since this work is in progress as of this writing, let's keep this ticket simple with AC's

Acceptance Criteria:

- [ ] All Labware Position Check copy should match [Figma designs](https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Milestone-0:-Protocol-Upload-Revamp?node-id=6236%3A191647), including sub-copy, modals, links, and buttons. (Variables such as labware names & slot numbers are naturally exceptions, but should follow the format provided in the designs)

**Comment by mikecardarelli** [comment]
This was covered in separate tickets
