### ISSUE TITLE
HTTP API: persist previous runs

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#8474]
## Overview

As an HTTP API client, I'd like to retrieve a history of previous run sessions, so that I can inspect and re-create a given run.

In order to satisfy the needs of the Protocol Upload Revamp project, the new ProtocolEngine-based `/sessions` endpoints need the following changes:

1. More than one run should be allowed
2. A run can be created from the state of another run
3. Previous run' state should be persisted through reboot

This ticket covers item (3). See #8470 for item (1) and #8473 for item (2).

## Acceptance Criteria

- [x] When a protocol run becomes stopped, its state is persisted to disk
- [ ] When a client initiated a protocol run update, its ProtocolEngine state is also persisted to disk

Writing to disk every time a run changes would be... a lot, so I think for our MVP we can leave this as "when the protocol ends or is stopped," and leave "unexpected shutdown during a run" undefined.

## Implementation Notes

TBD

**Comment by TamarZanzouri** [comment]
@mcous RunResource contains a prop of actions. it is a list on RunActions which contains id, createAt and RunActionType (str\enum). we have a few ways to conquer this. we can store it all in a RunActions table with a reference to the run or we can store it as a blob object (in case we can assume it wont change a lot). would love to hear your take about this

**Comment by TamarZanzouri** [comment]
create_run_action -> to update a run

**Comment by TamarZanzouri** [comment]
create_run_action, update_run -> update a current run

**Comment by TamarZanzouri** [comment]
@mcous looks like an acceptance criteria for this task is to update the run notes.
Should I add this? or should we leave it for 5.2?

**Comment by TamarZanzouri** [comment]
@mcous Meeting notes 4/19/2022

**Comment by TamarZanzouri** [comment]
**### Meeting notes 4/19/22:**
@mcous Following our meeting. Please let me know if there is anything I am missing.

- Persist base_router.py/update_run ->  engine_store.get_state(run.run_id) and actions_router.py -> protocol_runner.run 
- Use ProtocolRunData, move to shared location. add labware_offsets from engine_state.labware.get_labware_offsets() 
- Store state as one blob using pydantic models
- Create a CommandStore inside robot-server commands directory 
- Make sure when translating to json that the order is preserved - if its lists it will be - if its dicts it prob won’t
- EngineStore stores a dictionary[run_id, protocol_engine]. We might be able to removed it after persisting to the DB. 
- ProtocolEngine commands in the CommandsState are associated to the run in the engine_store
