### ISSUE TITLE
See How Rerunning a protocol works modal

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#8484]
create a modal for the empty state of the protocol tab that is displayed in the "last protocol run" section. 

this modal explains how cloning a protocol works. 

figma link to modal: 
https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Milestone-0:-Protocol-Upload-Revamp?node-id=6957%3A167940

Copy is updated!!!

**Comment by b-cooper** [comment]
covered by #8464
