### ISSUE TITLE
HTTP API: Protocol and run record persistence

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#8495]
## Overview

As a user, I would like to see the last protocol run on my OT-2 so that I can quickly re-run it with the same settings.

This epic tracks HTTP API work necessary to enable this user story, which is further implemented by the Protocol Upload Revamp and Labware Position Check projects

**Comment by y3rsh** [comment]
## Acceptance tests

### Persistence

> [run state mapping](https://docs.google.com/spreadsheets/d/1CD2c7U0W7qddrB8M5p9xuy4KUlRBwIB3uOY5sWLRt2k/edit?usp=sharing)

#### for run_state in [Succeeded, Stopped, Running (Robot turned off during run?), Idle]

1. POST protocol
2. POST run with protocol
3. Issue action commands and/or act to achieve run_state
4. restart the robot
5. GET all endpoints and by_id endpoints for protocols, runs, analyses, commands, ... are as expected.

### Record limit tests

> Proposed limit states used below. May change on implementation.

for state in ["1 protocol 20 runs", "20 protocols 1 run each"]

1. achieve state
2. \+ 1
3. validate "outside limit" record(s) deleted as expected so limit is not exceeded

**Comment by mcous** [comment]
Closing as completed. The single ticket that remains is an important tech debt tracker, but the overall feature defined by this epic is complete
