### ISSUE TITLE
feature(api): remove mypy exceptions in api project

### ISSUE THREAD

**Issue by amitlissack** [Opentrons/opentrons#8511]
# Overview

Mypy is a valuable tool for identifying errors.

The `mypy.ini` file in `api` project has exceptions for a number of sub packages. These exceptions should be removed.  

List of packages:

- [x] opentrons.algorithms.*
- [ ] opentrons.api.*
- [ ] opentrons.calibration_storage.*
- [x] opentrons.commands.*
- [ ] opentrons.config.*
- [x] opentrons.drivers.*
- [ ] opentrons.hardware_control.*
- [ ] opentrons.protocol_api.*
- [ ] opentrons.protocols.*
- [ ] opentrons.system.*
- [ ] opentrons.tools.*
- [ ] opentrons.util.*
- [x] opentrons
- [ ] opentrons.broker
- [ ] opentrons.execute
- [ ] opentrons.simulate
- [ ] opentrons.types
- [x] tests.opentrons.algorithms.*
- [ ] tests.opentrons.api.*
- [ ] tests.opentrons.broker.*
- [ ] tests.opentrons.calibration_storage.*
- [x] tests.opentrons.commands.*
- [ ] tests.opentrons.config.*
- [ ] tests.opentrons.data.*
- [ ] tests.opentrons.drivers.*
- [ ] tests.opentrons.system.*
- [ ] tests.opentrons.util.*
- [ ] tests.opentrons.conftest
- [ ] tests.opentrons.test_execute
- [ ] tests.opentrons.test_init
- [ ] tests.opentrons.test_simulate
- [ ] tests.opentrons.test_types

**Comment by sanni-t** [comment]
Moved to EXEC-201.
