### ISSUE TITLE
Run Detail Page: banner above run log when stopped, failed, or completed

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#8573]
Display a success banner at the top of the protocol run log when it is complete
Display a canceled banner at the top of the protocol run log when a user cancels the run
Display a failed banner at the top of the protocol run log when a step fails and therefore fails the run

Use the existing `AlertItem` component from the shared component library.

see Figma for details:

https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Milestone-0:-Protocol-Upload-Revamp?node-id=5629%3A145096

**Comment by mikecardarelli** [comment]
@jerader @smb2268 Is this work covered in your recent PR #8682

**Comment by smb2268** [comment]
@mikecardarelli The failed banner is in there but not the others so let's keep this ticket as a followup
