### ISSUE TITLE
Use / Don't Use PE Feature for PD Protocols after 6.0

### ISSUE THREAD

**Issue by anthonywilleee** [Opentrons/opentrons#8579]
for 5.1 release, we'll want a PD feature to "use PE/not use PE" (output v6/v5 protocols behind the scenes) so folks can switch their PD protocols back and forth

**Comment by SyntaxColoring** [comment]
Stale. Protocol Designer always outputs Protocol Engine commands now. As far as I know, there is no downgrade option.
