### ISSUE TITLE
bug: Stopping robot-server waits for pending analyses to complete

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#8588]
# Overview

When systemd requests the `robot-server` service to stop, `robot-server` waits for its pending protocol analyses to complete. This can prevent the robot from rebooting quickly.

# Steps to reproduce

1. Upload a protocol over the HTTP API.
2. While the protocol's analysis is pending, run `systemctl stop opentrons-robot-server`.

# Current behavior

```
Oct 25 16:09:56 67de75 systemd[1]: Stopping Opentrons Robot HTTP Server...
Oct 25 16:09:56 67de75 opentrons-api[3430]: Shutting down
Oct 25 16:09:56 67de75 opentrons-api[3430]: Waiting for background tasks to complete. (CTRL+C to force quit)
Oct 25 16:11:26 67de75 systemd[1]: opentrons-robot-server.service: State 'stop-sigterm' timed out. Killing.
Oct 25 16:11:26 67de75 systemd[1]: opentrons-robot-server.service: Killing process 3430 (uvicorn) with signal SIGKILL.
Oct 25 16:11:26 67de75 systemd[1]: opentrons-robot-server.service: Main process exited, code=killed, status=9/KILL
Oct 25 16:11:26 67de75 systemd[1]: opentrons-robot-server.service: Failed with result 'timeout'.
Oct 25 16:11:26 67de75 systemd[1]: Stopped Opentrons Robot HTTP Server.
```

# Expected behavior

robot-server should `.cancel()` its background analysis task and shut down gracefully and promptly.

**Comment by mcous** [comment]
Protocol analysis runs in a background thread, which cannot be easily cancelled. Instead, I think it should run in a [background process](https://anyio.readthedocs.io/en/stable/subprocesses.html), which can be canceled.

From there, as Max stated above, we need to allow our background task system to accept cancellations based on shutdown or resource deletion

**Comment by SyntaxColoring** [comment]
> Protocol analysis runs in a background thread, which cannot be easily cancelled. Instead, I think it should run in a [background process](https://anyio.readthedocs.io/en/stable/subprocesses.html), which can be canceled.

Agreed.

For the sake of completeness: we theoretically could maybe get this to work with threads if we configured the background thread to be daemonic. But I don't think we should do that, because a subprocess will be more parallel.

**Comment by SyntaxColoring** [comment]
# Implementation suggestions

I'm addressing this part:

> Make our background task tracking more sophisticated so we have something to call .cancel() on.

Not this part:

> Shunt this to a background process instead of a background thread.

## Changes to our `TaskRunner` class

1. Remove its dependency on FastAPI's `BackgroundTasks`.

3. In place of that, add a dependency on an AnyIO `TaskGroup`, injected through `__init__()`.

4. Document `__init__()` as private, not to be called by anything outside of that module.

5. To replace `__init__()`'s place in the public interface, add an `async` `@classmethod` called something like `make_new()`. This new method should...

   1. Create a new AnyIO `TaskGroup`.

   2. **Enter the AnyIO `TaskGroup` as if we were using it as a context manager, without actually using it as a context manager.**

      This is tricky and unfortunate, and you need to be familiar with nuances of AnyIO and FastAPI to understand why it's necessary.
     
      A `TaskGroup` is a context manager, and `AnyIO` sensibly requires that we enter it before using it, as a safety feature. But that style doesn't mesh well with how FastAPI does startup and shutdown handlers. (Basically. I'm glossing over a lot.) Something needs to act as an adapter layer between the two styles, and that thing will be `TaskRunner`.

      To implement this, I think the simplest thing is to manually call `await task_group.__enter__()`. We could also use a [`contextlib.AsyncExitStack`](https://docs.python.org/3/library/contextlib.html#contextlib.AsyncExitStack). Both are confusing in their own ways, so it's really whichever option feels like the least bad.

  3. Create a new `TaskRunner`, passing the new `TaskGroup` to its `__init__()`, and return it.

6. Add a new `async` method called something like `cancel_all_and_clean_up()`. It should...
    1. Request that every task owned by this `TaskRunner` is canceled, via `self.task_group.cancel_scope.cancel()`.
    2. Wait for everything to wrap up. Here, we need to undo whatever we did in `make_new()`. For the same reasons, this will be tricky and confusing. How to implement this depends on how we implemented `make_new()`. If we manually called `await task_group.__enter__()` there, we need to call `await task_group.__exit__()` here.

## Changes to `app_setup.py`

In the startup handler:

1. Create a `TaskRunner`.
2. Get the `FastAPI` object's `state`.
3. Attach the `TaskRunner` to the `state`, at some place we'll know to retrieve it later.

In the shutdown handler:

1. Retrieve the `TaskRunner` from the `FastAPI` object's `state`.
2. Call `cancel_all_and_clean_up()` on the `TaskRunner`. You should be able to add this the existing `gather()` call there.

## Changes to router functions

Every router function that's currently requesting:

```python
task_runner = Depends(TaskRunner)
```

Should change to something like:

```python
task_runner = Depends(get_task_runner)
```

`get_task_runner()` is a FastAPI dependency function that does not currently exist. We will need to write it.

The new `get_task_runner()` function should retrieve the `TaskRunner` from the app's `state` and return it. See existing dependency functions like `get_protocol_store()` for a sketch of how to retrieve something from `state`.
