### ISSUE TITLE
PUR: Wire up protocol metadata to protocol record

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#8592]
## Overview

Using the `useCurrentProtocolRun` hook, access the `protocolRecord.metadata` and map it's values to the corresponding labeled values in the `MetatdataCard`. 

## Acceptance Criteria

- [ ] all sections ('author', 'last updated', 'creation method', 'description' ) of the `MetadataCard` should be populated with the corresponding values found within the `protocolRecord`

**Comment by mikecardarelli** [comment]
This may be fixed now, we should re-check if it's still happening
