### ISSUE TITLE
Change Pipettes: View attached pipettes in Calibration

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#861]
As a user, I would like to be prompted to change my pipette if I currently have the wrong pipette attached.

## Acceptance Criteria

- [ ] User sees no alert if correct pipette(s) is/are attached
- [ ] User sees a visual alert on the calibration page if attached pipette does not match the pipette specified in protocol
    - No alert if robot has pipette attached but protocol does not use that mount
- [ ] ~User sees a (disabled for this ticket) button if pipette is wrong~ Requirement removed
    - If the wrong type of pipette is currently attached, button says "Change Pipette"
    - If no pipette is attached, button says "Attach Pipette"
    - Button action and wizard is covered by #860, #863, and #864
- [ ] ~Calibration cannot proceed until pipettes are correct~ Requirement removed

### Dependencies

- App able to retrieve attached pipettes (covered by #862)

### Design

Zeplin > Attach/Detach pipette > screens tagged as 'calibration'

## Test Plan

1. Connect to a robot with a left pipette attached
2. Load a protocol that calls for the attached left pipette
    - [ ] Confirm calibration page raises no pipette warnings
3. Load a protocol that calls for a different pipette in the left mount
    - [ ] Page raises an 'incorrect pipette attached' warning
    - [ ] Button says "change" pipette
    - [ ] Page does not raise a warning for the right pipette
    - [ ] App does not allow user to proceed with calibration
4. Load a protocol that calls for one pipette in the right mount 
    - [ ] Page raises a 'no pipette detected' warning in the right mount
    - [ ] Button says "attach" pipette
    - [ ] Page does not raise a warning for the left pipette
    - [ ] App does not allow user to proceed with calibration

**Comment by pantslakz** [comment]
@umbhau should we also add to story that user is unable to move forward in calibration unless correct pipette is attached?

**Comment by umbhau** [comment]
Note decided to implement change pipettes without this feature.

**Comment by mcous** [comment]
Closed by #1263
