### ISSUE TITLE
Change Pipettes: View attached pipettes in Settings

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#862]
## Overview

As a user, I would like to view my robot's available pipettes from the robot settings page.

## Acceptance Criteria

- [x] User able to see currently attached right and left pipette (or 'no pipette') on the Robot Settings Page
- [x] Button to initiate change is present (but disabled for this ticket)
    - Button says "Change" if pipette is attached
    - Button says "Attach" if no pipette is attached
    - Button action and wizard covered in #860, #863, and #864
- [x] Pipette info refreshes on page open or user interaction (note pipette info will not auto-refresh)

### Dependencies

- Pipette info endpoint (#998)

### Design

Robot Settings page (pipettes attached state): https://projects.invisionapp.com/d/main#/console/13387293/279764520/preview
Robot setting page (no pipettes state): https://projects.invisionapp.com/d/main#/console/13387293/279592170/preview

## Test Plan

* Connect to robot with no pipettes attached
    - [ ] Both pipettes show 'no pipette', and both buttons show 'attach'
* Attach only left pipette 
    - [ ] Only left pipette image shows up, and right pipette says 'none'
    - [ ] Left pipette button says 'change', and right pipette says 'attach'
* Attach only right pipette 
    - [ ] Only right pipette image shows up, and left pipette says 'none'
    - [ ] Right pipette button says 'change', and left pipette says 'attach' 
* Attach both pipettes 
    - [ ] Both pipettes show images, and both buttons show 'change'

**Comment by mcous** [comment]
Closed by #1131 and #1182
