### ISSUE TITLE
feat: Abstract specification conversion.

### ISSUE THREAD

**Issue by MattyCrowther** [Opentrons/opentrons#8632]
# Overview
This is more of a question as opposed to a request. 
Currently, we use autoprotocol (see link below) to specify formally our protocols. 
Is there any existing work into a semi or fully automated generation of OT2 protocols from protocol standards (autoprotocol and allotrope are specified below but could be more generally)?

# Implementation details
https://autoprotocol.org/specification/
https://www.allotrope.org/ontologies

# Design
N/A

# Acceptance criteria
N/A

**Comment by mcous** [comment]
Hey @MattyCrowther, thanks for the question! I'm not personally aware of any such work, but I'd also recommend reaching out to our support team, as they may be more aware of this sort of work amongst our community. Going to close this issue as a question, but feel free to continue commenting in this thread and we'll do our best to answer any more questions you have.

If you were looking to tackle this sort of project yourself, a place to start on our end might be our [JSON protocol specification](https://github.com/Opentrons/opentrons/blob/edge/shared-data/protocol/schemas/6.json)
