### ISSUE TITLE
Replacing p20 single channel with a p300 multi-channel

### ISSUE THREAD

**Issue by yorgomoubayed** [Opentrons/opentrons#8640]
Hi all,

I am working on this transformation protocol. At some point, the robot has to transfer 88 transformants from a 96-well plate using a p20 single channel to an agar plate. The goal here is to replace that pipette with a p300 multi-channel to reduce the protocol time.

When I try to conduct the substitutions in the code it loads successfully in the OT-2 software. The robot picks up the p300 multi-channel, but does not transfer transformants column by column, it keeps doing that well by well.

I am trying to find the piece of code that takes care of that to modify it, but it's not working.

Does anyone have any recommendations or can help?

Please find attached:
- The original script (4_transformation_ot2_APIv2.8_original.py) that uses the p20 single to spot transformants.
- The modified script (4_transformation_ot2_APIv2.8_modified.py) where I tried to replace the p20 single channel with a p300 multi-channel.

[code.zip](https://github.com/Opentrons/opentrons/files/7473723/code.zip

Thank you,
Best

**Comment by mcous** [comment]
Hi @yorgomoubayed! I think this question is better directed at our support team via support.opentrons.com, so I'm going to close this issue. Feel free to continue commenting in this thread, and I'll do my best to answer any questions you have.

My recommendation for getting help (either here in the issue tracker or via our support team) would be try to create the smallest possible protocol that exhibits the issue you're experiencing, and then go from there. The protocol you posted is a little to big / complicated for me to quickly read and understand
