### ISSUE TITLE
Change Pipettes: Test New Pipette

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#865]
## Overview

As a user, I would like my robot to test and confirm that I successfully attached a new pipette. To allow the user to test a pipette, the Run App must offer the UI to do so.

## Acceptance Criteria

- [x] After a user confirms that a new pipette is attached (#864), verify pipette is detected
- [x] If unable to detect pipette, display 'unable to detect pipette' message
    - Give user option to retry detection or exit pipette setup
- [x] If wrong pipette detected, display 'wrong pipette' message
    - Give user option to retry detection or exit pipette setup
- [x] If pipette detected, show success message and give user option to exit pipette setup
- [x] On exit pipette is homed
    - See design question below

### dependencies

- Pipette info in the app (PR #862) 
- Home pipette HTTP endpoint (PR #999)
- Pipette attach guidance (PR #864)

### Questions

- The following features are interesting but add scope. Need to discuss possible technical implementation (and let's consider them out-of-scope until we do):
    - Should success and failure messages contain the expected and discovered pipettes?
    - Should we give the user the option to continue by changing the other pipette? ([design](https://projects.invisionapp.com/d/main#/console/13387293/279592172/preview))
    - Should we give the user feedback if the pipette plunger was unable to home? 

### Design

- [Success](https://projects.invisionapp.com/d/main#/console/13387293/279592171/preview)
- [Unable to detect pipette](https://projects.invisionapp.com/d/main#/console/13387293/279592173/preview)
- [Wrong pipette detected](https://projects.invisionapp.com/d/main#/console/13387293/279592172/preview)

## Test Plan

This test plan overlaps with the Test Plan for #864: Attach Pipette Guidance

TBD

**Comment by mcous** [comment]
Closed by #1210 on the front-end and #1212 on the backend
