### ISSUE TITLE
Copy update: Remove all spaces between volumes and units

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#8651]
# Overview
Let's remove the spaces between the volume quantity and the units label so that the text wraps better at smaller breakpoints (for example, "2000 mL" should be updated to "2000mL"). 

Note: This change will be needed for the upcoming Next Gen App work.

# Acceptance Criteria
This change should be made to the labware display names and volumes that appear on the following pages (see screenshots attached inline): 

1. Labware Library landing page
![Screen_Shot_2021-11-05_at_2_28_48_PM.png](https://images.zenhubusercontent.com/5e20a4f595a33208d0d768ab/9f7b27ce-26d6-42b1-a1ed-327dc7f14442)

2. Labware Library detail pages
![Screen_Shot_2021-11-05_at_2_31_28_PM.png](https://images.zenhubusercontent.com/5e20a4f595a33208d0d768ab/dff48e8e-6b4f-4a1b-8503-7d1d613b8af8)

**Comment by mikecardarelli** [comment]
@Kadee80 After talking with Morgan, I'm not sure we still want to make this change. Before you start on this, let's discuss quickly on Slack/Hangouts. Sorry for the confusion

**Comment by mcous** [comment]
FWIW I support leaving this one alone! A space between numbers and their corresponding SI units is [recommended by NIST](https://physics.nist.gov/cuu/Units/checklist.html), and was why we included the space in the first place (if I'm remembering that hazy time correctly).

If we're concerned about line-wrapping, we can replace the space between the number and the units with a [non-breaking space character](https://en.wikipedia.org/wiki/Non-breaking_space)
