### ISSUE TITLE
Next Gen App: Main Navigation

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#8655]
# Overview

The Next Gen App will have a redesigned main navigation on the left, and the customer support chat will get a new styling and link to a new Salesforce-hosted chat portal. 

# Implementation details
- Note the new active state on the selected tab. Otherwise, see the new UI designs linked below. 

# Design
- New main nav design with the support chat closed and expanded: https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/%5Bworking%5D-Milestone-1%3A-Read-and-Execute?node-id=1506%3A105457

# Acceptance criteria

- [ ] Opentrons logo

- [ ] 3 New main nav options (Protocols, Labware, Devices)

- [ ] Active state for the selected tab

- [ ] Settings icon linking to App Settings

- [ ] Salesforce chat/help icon [linking to customer support chat](https://app.zenhub.com/workspaces/app--ui-5f6248dba845b000139aa767/issues/opentrons/opentrons/8667)

**Comment by b-cooper** [comment]
Closed by #9907
