### ISSUE TITLE
Change Pipettes: Pipette Memory

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#867]
As a run app user, I would like to be able to see details about my attached pipettes.

## Acceptance Criteria

- Store pipette model (and tbd other info) in pipette's onboard memory (completed #989)
- ~Expose a user-facing API endpoint to access pipette info~ moved to #998

## Implementation Notes

- ~Should we split writing info to pipette chip and exposing it via API into separate stories?~

**Comment by umbhau** [comment]
@andySigler, I'm told you've already through through the proper pipette data structure and content. Let's discuss this week!

**Comment by mcous** [comment]
Pipette memory done, HTTP API moved to separate ticket.

Closed by #989
