### ISSUE TITLE
Devices Landing: Robot Actions Menu

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#8673]
# Design 
Each robot card has a three-dot menu in the top right corner. The available actions in the menu depend on the state of the robot's status (Idle or Busy) and connectivity (Available or Not Available).
You can see all of the available menu actions here: 
https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/%5Bworking%5D-Milestone-1%3A-Read-and-Execute?node-id=1297%3A88551

# Implementation Details

Available Actions by robot state: 
- Robots that are Available + Idle: Go to robot, Run a protocol
- Robots that are Available + Busy: Go to robot
- Robots that are Not Available: Why is this robot not available?

# Acceptance Criteria

- [ ] The correct menu actions appear for Available + Idle robots
- [ ] The correct menu actions appear for Available + Busy robots
- [ ] The correct menu actions appear for Not Available robots

**Comment by mikecardarelli** [comment]
Hidden robots are out of scope for 5.1

**Comment by bndo** [comment]
Closed via #10188
