### ISSUE TITLE
LPC: warn about offset destruction

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#8684]
add an info section that tells users that the previously created labware offsets will be discarded. Also make sure the offsets are cleared once the LPC flow kicks off (anchored off of the main CTA on the intro screen).

Figma link:
https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Milestone-0%3A-Protocol-Upload-Revamp?node-id=4647%3A112043

when a user prematurely exits LPC, update the copy on the modal and buttons to be more explicit that the offset data will be lost.

figma link:
https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Milestone-0%3A-Protocol-Upload-Revamp?node-id=4327%3A54757

**Comment by smb2268** [comment]
> Also make sure the offsets are cleared once the LPC flow kicks off (anchored off of the main CTA on the intro screen)
This will be handled in [#8845](https://github.com/Opentrons/opentrons/issues/8845)
