### ISSUE TITLE
Device Details: Software Update Banner

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#8694]
# Overview
When a version of Robot Software is available that is newer than what the connected robot is running, a yellow banner should appear at the top of the device details page. 
This banner should appear above the purple "active protocol running" banner if both appear at the same time

# Design
- Software Update banner designs: 
https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/%5Bworking%5D-Milestone-1%3A-Read-and-Execute?node-id=1297%3A91474
- Software Update Available modal (for reference): 
https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/%5Bworking%5D-Milestone-1%3A-Read-and-Execute?node-id=1297%3A88764

# Implementation Details
- Clicking on the "View update" link should open up the Software Update Available modal.
- Clicking on the "X" should dismiss the banner until the next time the app is opened.

# Acceptance Criteria

- [ ] The banner appears whenever a newer robot software update is available

- [ ] The banner does not appear if the robot's software is up-to-date

- [ ] Dismissing the banner removes it until the next time the app is opened

- [ ] Clicking the "view update" link opens the Software Update Available modal

- [ ] This banner should always appear on top if the "active protocol running" banner is also present

# Selector for E2E

- [ ] Software update banner
- [ ] Remind me later
- [ ] Update app now

**Comment by b-cooper** [comment]
This was handled in the larger robot server update work, we just need to confirm that the banner also renders properly in the device card of the landing page

**Comment by koji** [comment]
This has been solved by #10010
