### ISSUE TITLE
Protocol Runs Page: Export to CSV

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#8736]
# Overview
If the user needs to download the full robot run logs, they have that option via the "Export list to .csv" link above the protocol runs list.

# Design
The export CSV link can be found in the top right corner here: 
https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/%5Bworking%5D-Milestone-1%3A-Read-and-Execute?node-id=1297%3A101196

# Implementation Details

- After clicking the "Export list to .csv" link the user should be prompted to name the file click download via an OS system dialog
- The robot's full protocol run log should be included in the .csv file

# Acceptance Criteria

- [ ] Clicking the "Export list to .csv" link prompts the user to download the full robot protocol run logs

**Comment by sanni-t** [comment]
Closing as outdated issue.
