### ISSUE TITLE
Epic: Protocol Run Details

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#8744]
# Overview
When the user clicks on a specific row in the protocol runs list (or kicks off a new run using the protocol runs list action menu), they should proceed to the protocol run details page for that protocol run. 

# Design
All the designs for this page live here: 
https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/%5Bworking%5D-Milestone-1%3A-Read-and-Execute?node-id=1297%3A101653

**Comment by SyntaxColoring** [comment]
Closing this old ZenHub epic as stale. We've moved these things to Jira.
