### ISSUE TITLE
Epic: Robot Settings Page

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#8756]
# Overview
Clicking on the "Robot Settings" secondary action button at the top of the Device Details page will bring you to the Robot Settings page. This page contains 3 tabs: Calibration, Networking, and Advanced.

# Design
All the designs for this epic can be found here: 
https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/%5Bworking%5D-Milestone-1%3A-Read-and-Execute?node-id=1297%3A90420

**Comment by SyntaxColoring** [comment]
Closing this old ZenHub epic as stale. We've moved these things to Jira.
