### ISSUE TITLE
Advanced - About this Robot

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#8763]
# Overview
The About section is the first section on the Robot Settings page's Advanced tab. 
It displays the robot name, robot server version, serial number, firmware version, and supported python API versions. There's also a button that opens up a Rename your Robot slideout. 

# Design
This tab's design (including the software update available banner) can be found here: https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/%5Bworking%5D-Milestone-1%3A-Read-and-Execute?node-id=1297%3A90420

# Acceptance Criteria

- [ ] All robot metadata should display correctly in the About section

- [ ] The "Change robot name" button should open the Rename Robot slideout

- [ ] The "Update now" button should open the robot software update modal

**Comment by koji** [comment]
This was fixed by #10044
