### ISSUE TITLE
Advanced - Troubleshooting

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#8765]
# Overview
The Troubleshooting section is the third section on the Robot Settings page's Advanced tab. The user can use this section to download logs, reset to factory, and toggle whether to use the older protocol analysis method. 

# Design
The designs can be found here: https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/%5Bworking%5D-Milestone-1%3A-Read-and-Execute?node-id=1297%3A90420

# Acceptance Criteria

- [ ] The "Download logs" button should prompted the user to name and download the robot's logs

- [ ] The "Choose reset settings" log should open up the Factory Reset slideout

- [ ]  The toggle should turn on/off protocol analysis functionality as expected

**Comment by koji** [comment]
This was closed by #10010
