### ISSUE TITLE
Advanced - Usage Settings

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#8766]
# Overview
The Usage Settings section is the second section on the Robot Settings page's Advanced tab.
This section has toggles for pausing a protocol when the door opens, calibrating to the bottom of A1 wells, and disabling home the gantry after a restart. There's also buttons to launch Jupyter Notebook and update software with a  local .zip file. 

# Design
The design of this section can be found here: https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/%5Bworking%5D-Milestone-1%3A-Read-and-Execute?node-id=1297%3A90420

# Acceptance Criteria
- [ ] All three toggles should turn on/off functionality as expected

- [ ] The "Launch Jupyter Notebook" button should open up Jupyter Notebook outside the OT App

- [ ] The "Learn more about using Jupyter notebook with the OT-2" link should open this link in a new browser tab: https://docs.opentrons.com/v2/new_advanced_running.html#jupyter-notebook

- [ ] The "Launch Opentrons software update page" should open this link in a new browser tab: https://opentrons.com/ot-app/

**Comment by koji** [comment]
This was closed by #10010
