### ISSUE TITLE
Advanced - Legacy Settings

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#8767]
# Overview
The Legacy Settings section is the fourth section on the Robot Settings page's Advanced tab.
The user can use this section to control 3 settings related to legacy robots: calibrating to dots, using a short trash bin, and using older aspirate behavior.

# Design
The designs for this page can be found here: https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/%5Bworking%5D-Milestone-1%3A-Read-and-Execute?node-id=1297%3A90420

# Acceptance Criteria

- [ ] All three toggles should turn on/off functionality as expected

**Comment by koji** [comment]
This was closed by #10010
