### ISSUE TITLE
Intercom Chat - Remove Chat Icon from OT App

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#8768]
The Intercom chat service is going to be discontinued at the end of the year, and the Support team is switching to a chat service from Salesforce. We should remove the Intercom chat from our next public release of the OT app, and the Salesforce chat should be added for Next Gen App - Milestone 1. 

The chat icon can be seen in the bottom right corner here: 

![Screen Shot 2021-11-15 at 9.15.39 AM.png](https://images.zenhubusercontent.com/5e20a4f595a33208d0d768ab/0ce0efab-18d6-46b9-928d-106df3b50975)

**Comment by mikecardarelli** [comment]
Let's add this change to the BETA branch, not Edge

**Comment by ethanfjones** [comment]
Hey @mikecardarelli and @b-cooper wanted to confirm that intercom or any chat functionality will not be in 5.0.0
