### ISSUE TITLE
Canceling a run state

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#8783]
when the user cancels a run, there will be a "canceling in progress" state where the run is in the process of canceling. when this happens, the status will be "canceling" and the main CTA will disable and say "Canceling run...".

also, once the run is canceled, the previously in-progress step will be marked as failed, and it won't have an end time. 

see figma:

https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Milestone-0%3A-Protocol-Upload-Revamp?node-id=5629%3A145096

**Comment by mikecardarelli** [comment]
This may have been addressed in a different ticket. Let's close it, if so
