### ISSUE TITLE
Rename Robot - Slide-out

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#8793]
# Overview
The Rename Robot slide-out can be access from a "Rename robot" button in the About section on the Robot Settings page's Advanced tab.

# Design
The slide-out designs live here: https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/%5Bworking%5D-Milestone-1%3A-Read-and-Execute?node-id=1297%3A106103

# Acceptance Criteria

- [ ] If the user hasn't entered any text, the "Rename and Restart" button should be inactive

- [ ] If a robot name is entered, clicking the "Rename and Restart" button should update the robot name successfully and restart the robot

**Comment by koji** [comment]
This was fixed by #10044
