### ISSUE TITLE
PUR: Wire up missing URL link in Rerunning a Protocol Modal

### ISSUE THREAD

**Issue by jerader** [Opentrons/opentrons#8801]
## Overview
The link in `RerunningProtocolModal` is currently missing since the support article is not ready yet

## Acceptance Criteria
- [ ] link in the component should work

**Comment by b-cooper** [comment]
@emilywools @mikecardarelli This is blocked until we receive the final link url

**Comment by emilywools** [comment]
getting the URL from Marisa momentarily!

**Comment by emilywools** [comment]
here's the URL for the article that will be titled How Labware Offsets work on the OT-2:

http://support.opentrons.com/en/articles/5742955-how-labware-offsets-work-on-the-ot-2
