### ISSUE TITLE
Epic: Protocols Landing Page

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#8813]
# Overview
The protocols landing page can be accessed via the "Protocols" link in the main navigation. 

# Design
The protocols landing page designs live here: 
https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/%5Bworking%5D-Milestone-1%3A-Read-and-Execute?node-id=1297%3A90568

**Comment by SyntaxColoring** [comment]
Closing this old ZenHub epic as stale. We've moved these things to Jira.
