### ISSUE TITLE
Epic: Protocol Details Page

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#8820]
# Overview 
The protocols details page can be accessed by clicking on any of the protocol cards on the protocols landing page. This page can also be accessed by clicking on the protocol name in the protocol runs list or the protocol run details page. 

# Design
The designs for this page live here: https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/%5Bworking%5D-Milestone-1%3A-Read-and-Execute?node-id=1482%3A105272

**Comment by SyntaxColoring** [comment]
Closing this old ZenHub epic as stale. We've moved these things to Jira.
