### ISSUE TITLE
Epic: Deck Setup Page

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#8831]
# Overview 
The Deck Setup Page can be accessed via the "View" button next to the Deck Setup section on the Protocol Details page.

# Design
The Deck Setup Page's design lives here: https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/%5Bworking%5D-Milestone-1%3A-Read-and-Execute?node-id=1482%3A105272

**Comment by SyntaxColoring** [comment]
Closing this old ZenHub epic as stale. We've moved these things to Jira.
