### ISSUE TITLE
Re-analyze Python Protocol Banner

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#8856]
# Overview
If a file related to a Python protocol changes, the user will be prompted to re-analyze their protocol with this alert banner. Note: This feature does not affect PD protocols. 

# Design
This banner can be found here: https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/%5Bworking%5D-Milestone-1%3A-Read-and-Execute?node-id=1482%3A105272

# Acceptance Criteria

- [ ] The user can reanalyze their protocol by clicking the "Re-Analyze" button in the banner

- [ ] The banner appears when a Python protocol file is changed

- [ ] The banner disappears if the analysis is run, or if the Python protocol is run on a robot

- [ ] Dismissing the banner will dismiss it until the next time the OT-app is opened

- [ ] The "Last Analyzed" field should not appear for PD protocols

# Selectors for E2E

Re-analyse banner
last analyzed field

**Comment by reachojhaneha** [comment]
revisit for updating the Selector
