### ISSUE TITLE
Epic: App Settings

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#8878]
# Overview
The App Settings page can be accessed from the gear icon in the left-side main navigation.

# Design
All of the App Settings designs can be found here: https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/%5Bworking%5D-Milestone-1%3A-Read-and-Execute?node-id=1297%3A88764

**Comment by SyntaxColoring** [comment]
Closing this old ZenHub epic as stale. We've moved these things to Jira.
