### ISSUE TITLE
Update Trash Bin Height

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#891]
As a user, I would like a larger-volume trash bin, so that I can store more tips.

## Acceptance Criteria
- Trash bin replaced with larger trash bin (HW)
- Container definition updated to reflect new dimensions
- Tip probe updated to reflect new dimensions

## Implementation Notes
- This is a breaking change
- Actual trash boxes will have to be replaced at the same time as the software update
- This includes our two beta robots (one already in the wild, one scheduled for delivery 2/22)

**Comment by btmorr** [comment]
Not a breaking change. Has been deployed under a feature flag, described in PR #897
