### ISSUE TITLE
Flesh out Protocol Engine's handling of Thermocycler movements

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#8911]
#8910 implemented just enough of module loading in Protocol Engine to support the Labware Position Check beta. Since the Thermocycler module is a little special, we left some gaps in our support for it that we'll now have to fill in.

* [ ] Protocol Engine should refuse to move to a labware when that labware is in a Thermocycler whose lid is currently closed, but it currently does not.
    * #8941
* [ ] Moves to non-thermocycler locations should dodge the thermocycler once a thermocycler is loaded in the run.
    * #8931

**Comment by mattwelch** [comment]
Closing because work is covered in other tickets
