### ISSUE TITLE
Missing link for how do offsets work support article

### ISSUE THREAD

**Issue by b-cooper** [Opentrons/opentrons#8963]
The "Learn more about Labware Offset Data" link within the in app's "How Offset Data Works" modal is missing. Replace it with a link to the corresponding support article.

**Comment by b-cooper** [comment]
@emilywools once the link is available, please update the description and move this ticket into "Ready for Dev"

**Comment by emilywools** [comment]
per https://github.com/Opentrons/opentrons/issues/8801#issuecomment-971761711, heres the link for the article (it does not currently work but that's where it will be going)

http://support.opentrons.com/en/articles/5742955-how-labware-offsets-work-on-the-ot-2
