### ISSUE TITLE
Rename or remove labware calibration from factory reset dialog

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#8975]
In the Opentrons App, the "Factory Reset" dialog currently has a "Labware Calibration" option. This won't make sense past v5.0.0, which replaces labware calibration with the Labware Position Check.
 
# Acceptance criteria

* Decide whether we want to retain this factory reset checkbox despite labware calibration not existing anymore. If we're keeping the files around on the filesystem past v5.0.0 for downgrade purposes, it might also make sense to keep the checkbox around.
* Then, either remove that checkbox, or, if we're retaining it, consider renaming it to clarify that the offsets are legacy-only.

**Comment by emilywools** [comment]
hey @SyntaxColoring we are going to remove this checkbox per #8283

**Comment by SyntaxColoring** [comment]
👍 Closing as a duplicate of #8283.
