### ISSUE TITLE
feat(engine): add `key` hash to v3 command for analysis-to-run matching

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#8986]
## Overview

As an PAPIv3 user, I'd like to associate simulated commands from a `/protocols` analysis with the actually run commands in a `/runs` run.

## Acceptance criteria

We'd like to add a `key` (or other appropriate name, e.g. `hash`) field to a `Command` resource. This matching key has two requirements:

- A given command's match key is unique in the protocol
- In a deterministic protocol, a command's match key is stable across an analysis and a run 

## Implementation details

A hashing of the following items should do the trick

- Command type
- Command intent (`setup` vs `protocol`)
- Command order in the stream
- Command params

### Hashing the command order

- The keys of previous commands should affect the keys of subsequent commands, or else we end up with issues like #9548

### Hashing the command params

- Basic params values can be sent into the hashing mechanism directly
- We have to do something different with param fields that represent equipment IDs, like `labwareId`, `pipetteId`, and `moduleId`
    - Equipment IDs will not be stable from analysis to run, intentionally
    - We instead need to hash the request properties of the load commands of those equipment instead
    - This will be pretty similar to how we associate labware offsets to load labware commands

### Why not use the command ID?

A command's ID represents something subtly different: it's a unique identifier for a single instance of a command. A command that was executed in an analysis is a different instance than one that was executed in a real run; if nothing else, the execution environment is vastly different.

Additionally, an ID is (read: will be) used for record persistence. Persisting things becomes much less technically fraught if we know that child command resources owned by different parents (like an analysis resource or a run resource) won't have ID collisions in some database table.

**Comment by SyntaxColoring** [comment]
We might also want to include the previous command hash as an input to the current command hash.

So if analysis does:

1. Pick up tip
2. Aspirate from A1
3. Dispense in A2
4. Aspirate from B1

And the actual run does:

1. Pick up tip
2. Aspirate from *C1*
3. Dispense in *C2*
4. Aspirate from B1

The run key for step (4) will *not* match the analysis key for step (4), reflecting that the physical and logical state of the robot has permanently diverged.

**Comment by mcous** [comment]
Ticket under investigation as a potential 6.1.0 release requirement

**Comment by mcous** [comment]
Not a 6.1.0 release requirement. Command key additions required for the 6.1.0 release are tracked in #10799

**Comment by mcous** [comment]
Moved to RCORE-326
