### ISSUE TITLE
Missing pause and delay commands in the run log

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#9011]
Pause and delay commands are not shown in the run log

Update: Pause command shows up as long as it follows at least one pipetting command. If it is the first command in the protocol/ if there are only equipment loading commands before the pause, then it is not included in the logs.

cc @sanni-t

**Comment by b-cooper** [comment]
It's possible this is a generic problem that is leading to the first command being trimmed, if this is the case, then we should solve that problem and the delay command problem separately.
