### ISSUE TITLE
bug: beta 0 - Protocol is stuck half way while using dual pipette

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#9012]
Protocol is stuck half way while using dual pipette. While on run page, protocol is not terminated, run time kept increasing. Protocol has to be manually terminated
Steps to reproduce:
1. Using 2 pipettes, P300 gen2 and P20 gen 2, multi channel
2. After the execution of P300 gen 2 step, after pause step, the protocol was stuck and pipette 2 did not perform the operation.
3. Protocol continued running on the Run page , Run time kept increasing and current step was highlighted.
[Test_PUR_Robot_1.json.zip](https://github.com/Opentrons/opentrons/files/7671958/Test_PUR_Robot_1.json.zip)

**Comment by b-cooper** [comment]
Investigate if this is still reproducible on beta.5/beta.6
