### ISSUE TITLE
Epic: Heater Shaker Support in backend

### ISSUE THREAD

**Issue by mattwelch** [Opentrons/opentrons#9020]
As a protocol creator, I'd like to be able to exercise the OT H/S via Python Protocols (v3) and via Protocol Designer protocols (JSON schema v6).

These are the acceptance criteria outlined in [QB-T163/Heater Shaker Protocol JIRA story](https://opentrons.atlassian.net/projects/QB?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/QB-T163):

- Validate Python protocol with H/S can be created
- Validate H/S works with other modules on deck
- Validate multiple H/S can be ran in same protocol
- Validate all H/S python commands can be successfully executed
- Validate all controls can be accessed in modules and run tab
- Validate modals pop up when starting protocol to confirm you want to stop heating and shaking
- Validate H/S SVG is correct
- Validate H/S SVG is in correct location according to protocol
- Validate correct shaking and heating state
- Validate correct current and target temperature
- Validate correct current and target RPM
- Validate correct module power start
- Validate module alerts when hot to touch

**Comment by SyntaxColoring** [comment]
Closing this old ZenHub epic as stale. We've moved these things to Jira.
