### ISSUE TITLE
Spike: write documentation for heater shaker python API functions

### ISSUE THREAD

**Issue by mattwelch** [Opentrons/opentrons#9037]
H/S commands defined in [this page](https://opentrons.atlassian.net/l/c/EZZ1diXF) 

Proposed methods defined on [this page](https://opentrons.atlassian.net/l/c/K01qHeNn)

## Deliverables
- Preliminary set of *actual* methods & classes for h/s support in python to realize the capabilities linked in second page above
- Preliminary documentation for above

## Caveats
These will be preliminary python features. Changes will likely occur when we build the actual support.

**Comment by sanni-t** [comment]
Updated the python API methods [here](https://opentrons.atlassian.net/l/c/K01qHeNn)
