### ISSUE TITLE
add a new case for users who close an in progress protocol from the protocols page

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#9049]
For users who have a protocol in progress and navigate to the protocol tab and close the protocol, we should show a modal that says

"Protocol run in progress. Cancel run and close protocol?
Buttons: 
no, go back
Yes, cancel and close protocol"

> dev-speak: add new conditional text to the confirm close modal when you launch it from the protocol tab to account for a situation when the user has started the protocol. and render the upload empty state as soon as either a stop or dismiss request is in progress. 

This should also include a CPX ticket to allow dismiss an unstated protocol cc @shlokamin can you add some color to this part

**Comment by b-cooper** [comment]
This is theoretically stale, we want close and cancel functionality to be identical across both tabs, will follow up and close
