### ISSUE TITLE
Spike: Define proposed user experience for LO availability in Jupyter

### ISSUE THREAD

**Issue by mattwelch** [Opentrons/opentrons#9055]
UX to work w/ engineers from CPX and Apps & UI (to understand technical possibilities/restrictions) to define the experience of making Labware Offset info available for protocol runs initiated via Jupyter. 

Target is to have this complete for 5.0 release. Public-facing testing can be part of 5.0 beta, but that timing may be difficult.

**Comment by mattwelch** [comment]
@emilywools has already provided a Figma sketch as part of opentrons#9059!

**Comment by mcous** [comment]
Proposal posted here: https://github.com/Opentrons/opentrons/issues/9059#issuecomment-1011286300
