### ISSUE TITLE
add a way for SSH/Jupyter users to download offset data

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#9059]
SSH and Jupyter users need a way to download offset data. This is an edge case for a small set of users.

1. add an advanced app setting that enables /disables showing the "download offset data" link
2. this setting is defaulted to OFF
3. when ENABLED, the link to download offset data will display on
a. the last protocol run / empty state
b. the LPC summary screen
c. the LPC section below the deck map in the labware accordion
4. if there is no offset data present (all identity offsets), do not display the link

see figma:

https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Milestone-0%3A-Protocol-Upload-Revamp?node-id=9846%3A186829

this is related to #9028 and #9029

cc @b-cooper in case there is more tech info that needs to be shared here

**Comment by mcous** [comment]
Proposal for the copy-paste block!

1. Enumerate all labware checked by LPC
2. Follow each load with a call to `labware.set_offset`

For example, given the following LPC:

| labware/module                           | location         | calculated offset |
| ---------------------------------------- | ---------------- | ----------------- |
| `temperatureModuleV1`                    | Slot 3           | N/A               |
| `opentrons_96_tiprack_300ul`             | Slot 1           | x: 1, y: 2, z: 3  |
| `nest_96_wellplate_100ul_pcr_full_skirt` | Module in slot 3 | x: 4, y: 5, z: 6  |

### Jupyter

```py
import opentrons.execute
protocol = opentrons.execute.get_protocol_api("2.12")

module_1 = protocol.load_module("temperatureModuleV1", location="3")

labware_1 = protocol.load_labware("opentrons_96_tiprack_300ul", location="1")
labware_1.set_offset(x=1.0, y=2.0, z=3.0)

labware_2 = module_1.load_labware("nest_96_wellplate_100ul_pcr_full_skirt")
labware_2.set_offset(x=4.0, y=5.0, z=6.0)
```

### `opentrons_execute` CLI (aka SSH)

```py
from opentrons import protocol_api

metadata = {
    "apiLevel": "2.12"
}

def run(protocol: protocol_api.ProtocolContext):
    module_1 = protocol.load_module("temperatureModuleV1", location="3")

    labware_1 = protocol.load_labware("opentrons_96_tiprack_300ul", location="1")
    labware_1.set_offset(x=1.0, y=2.0, z=3.0)

    labware_2 = module_1.load_labware("nest_96_wellplate_100ul_pcr_full_skirt")
    labware_2.set_offset(x=4.0, y=5.0, z=6.0)
```

Not sure about the whole `labware_1`, `module_1` naming scheme, but the important points here are:

- Must use API version `2.12` or higher
- Make sure to include both deck labware and module labware

**Comment by b-cooper** [comment]
This task should be broken into three separate PRs:

- create an advanced setting for the app for this to hide behind
- create a link with modal that only shows the jupyter snippet in a textarea
- add the ssh/cli snippet to that modal
