### ISSUE TITLE
robot-server: allow an unstarted, idle run to be marked "closed" without stop

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#9068]
## Overview

A run should be allowed to be "closed" if it is:

- Idle
- Has not been "play"'d

Related but distinct from #8996

**Comment by mattwelch** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/opentrons-cpx-5e1f6ed55b295a3f514f2283/issues/Opentrons/opentrons/9068?planning-poker) with ZenHub @mcous @sanni-t @SyntaxColoring
