### ISSUE TITLE
bug: App doesn't show an error for failed attempts to upload an invalid protocol

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#9077]
# Overview

If an uploaded protocol is so invalid that `POST /protocols` immediately returns with a non-2XX HTTP response, the app doesn't show an error.

Note that this is different from the case where an upload succeeds (returns 2XX) but its *analysis completes with a `not-ok` result.*

# Steps to reproduce

On 5.0.0-beta.3, upload this protocol:

```python
metadata = {"apiLevel": 2.11}

def run(protocol):
    tip_rack = protocol.load_labware("opentrons_96_tiprack_300ul", 1)
    well_plate = protocol.load_labware("corning_96_wellplate_360ul_flat", 2)
    pipette = protocol.load_instrument("p300_multi_gen2", mount="left", tip_racks=[tip_rack])

    pipette.transfer(300, well_plate.columns()[0], well_plate.columns()[2])
```

The error in this protocol is that it uses a float, for `apiLevel` where it should use a string.

# Current behavior

The protocol upload screen in the app does not mention the error, and returns to its state where it's waiting for you to drag in a protocol.

# Expected behavior

The app should show a descriptive error message. In this specific example, it should mention something about the protocol's metadata.

**Comment by b-cooper** [comment]
If robot returns "file is not of the expected shape" or something pre-analysis then we should surface the error in a similar way to the analysis errors
