### ISSUE TITLE
bug: Whitescreen when starting Labware Position Check on a protocol that loads, but does not use, a plate and pipette

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#9090]
# Steps to reproduce

Upload this protocol on v5.0.0-beta.3:

```python
metadata = {"apiLevel": "2.11"}

def run(protocol):
    plate = protocol.load_labware("biorad_96_wellplate_200ul_pcr", 1)
    pipette = protocol.load_instrument("p300_single_gen2", mount="left")
```

Then, start Labware Position Check.

# Current behavior

The app whitescreens. In the devtools console, I see:

> Uncaught Error: expected to be able to find labware location, but could not

# Expected behavior

Either LPC should be disabled with a descriptive tooltip, or it should not whitescreen.

**Comment by mcous** [comment]
This is the same console error I see with #9082 / #9083
