### ISSUE TITLE
beta 4 - closing the protocol throws error first and then closes the protocol

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#9107]

**Comment by reachojhaneha** [comment]
Steps to reproduce:
Open a protocol, and click on the close button on the top right corner.
there is an error generated and then protocol is closed. 
![Screen Shot 2021-12-14 at 5.00.09 PM.png](https://images.zenhubusercontent.com/6022db4fed6ea443cf5a06ed/91c67d3b-e35a-40c0-a5c2-1ac9a2da8328)

[https://app.zenhub.com/files/38644841/2ed00c4f-8330-4d0a-9066-6eb8411b4f36/download](https://app.zenhub.com/files/38644841/2ed00c4f-8330-4d0a-9066-6eb8411b4f36/download)

**Comment by mikecardarelli** [comment]
This ticket will be covered in #9231

**Comment by b-cooper** [comment]
Closed by #9231
