### ISSUE TITLE
bug: 'temperature module gen2' not recognized via Jupyter interface

### ISSUE THREAD

**Issue by danolson1** [Opentrons/opentrons#9115]
# Overview
I have a python protocol, and I am trying to troubleshoot a few steps using the Jupyter interface. The protocol works fine when run via the Opentrons app, but causes an error related to not being able to find the temperature module when I run it via the Jupyter interface.

# Steps to reproduce
```
import opentrons.execute
from opentrons import protocol_api, simulate, types
protocol = opentrons.execute.get_protocol_api('2.11')
temp_module = protocol.load_module('temperature module gen2', '7')
temp_module.set_temperature(4)
```

# Current behavior
Error message

# Expected behavior
A protocol that runs via the Opentrons app interface should also run via the Jupyter interface.

**Comment by mcous** [comment]
Unable to reproduce on latest version of the software
