### ISSUE TITLE
feat(engine): pause protocol execution if front door is opened

### ISSUE THREAD

**Issue by mattwelch** [Opentrons/opentrons#9125]
## Overview

As a JSONv6 protocol operator with my robot's "pause execution if door is open" setting turned on, I'd like my protocol run to automatically pause if my robot's front door is opened.

## Acceptance criteria

If the door pause setting is enable:

- [ ] If the front-door is opened while a protocol run is ongoing, the engine and hardware API are paused
- [ ] If the front-door is opened during protocol setup (i.e. LPC), the engine continues to process commands

## Implementation notes

- The behavior is currently implemented in the `LegacyContextPlugin` for PAPIv2 protocols
    - We can probably move at least aspects of that implementation over to the engine proper
- We can check the command store's `started_at` field to know if the run has been started and if we should pause due to a door open
- Care should be taken to make sure this interacts cleanly with #7923
    - This is also already a concern of `LegacyContextPlugin`

**Comment by mcous** [comment]
Ticket under investigation as potential 6.1.0 release requirement

**Comment by mcous** [comment]
This ticket is required for the 6.1.0 release. Updated tracking information accordingly

**Comment by mcous** [comment]
After #10882 is merged, this is my implementation proposal to bring this home:

- Rename `HardwareEventForwarder` to `DoorWatcher`
- Simplify `HardwareEventAction` to `DoorChangeAction`
    - We don't use any other hardware events
    - When we do in the future, I don't want to continue to use this callback interface; it's too dangerous with the `ThreadManager` and protocol child thread in place
- On door change notification from the hardware control API:
    1. Check if queue status is `running`
    2. If it is, pause the hardware API
    3. Dispatch a `DoorChangeAction` with the door state
- Remove remaining action handling from the `LegacyContextPlugin`, and perhaps remove the abstract `handle_action` method from the generic plugin interface, too
