### ISSUE TITLE
empty state is not showing the last protocol

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#9130]
the empty state is not showing the last protocol I ran. it is showing a protocol from a few runs ago.

last run:
robotics_demo.json

run before:
robotics_demo.json

run before that:
testosauraus.py

![Screen Shot 2021-12-16 at 2.59.04 PM.png](https://images.zenhubusercontent.com/5f57e13054c0d9cd55c2adb3/165d8583-4a1b-4668-80bc-25b5b0f69899)

![Screen Shot 2021-12-16 at 2.50.21 PM.png](https://images.zenhubusercontent.com/5f57e13054c0d9cd55c2adb3/3d17d3c9-56a7-4090-b818-74ba4338f78f)

**Comment by brenthagen** [comment]
I believe this is fixed in edge and will be included in the next beta (fixed by https://github.com/Opentrons/opentrons/pull/9073)

**Comment by anthonywilleee** [comment]
@b-cooper - confirmed on 5.0.0-beta.5 that Run Again correctly updates to the last run protocol.

**Comment by b-cooper** [comment]
appears fixed in beta.5
