### ISSUE TITLE
Deck map looks rly small when the warnings are there

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#9132]
when the app is at the default size, and the modules have warnings, the deck map displays realllllly small. can we increase the wide of the deck map when this happens?
![Screen Shot 2021-12-15 at 12.48.38 PM.png](https://images.zenhubusercontent.com/5f57e13054c0d9cd55c2adb3/1d155736-113d-401f-83e5-932be29926bf)

**Comment by sakibh** [comment]
This should be addressed by #9184
