### ISSUE TITLE
bug: Protocol execution stalls when unrelated tasks hog the main thread's async event loop

### ISSUE THREAD

**Issue by mattwelch** [Opentrons/opentrons#9133]
# Overview

This ticket tracks a specific theory for why an OT-2 running the v5.0.0 beta would be unusually janky (jittery, stuttery, sluggish, slow) when executing a protocol.

# The user-reported problem

> It was extremely slow. I ran a protocol involving a bunch of mixing and transferring and the robot was frequently pausing and much less [smooth] than usual.

(See Matt for a copy of this user's protocol.)

My own testing shows that it gets much worse when you spam the robot with HTTP requests, especially `GET /protocols` or `GET /runs`.

# The technical theory

APIv2 protocols are written in plain old synchronous Python, without any `async` or `await`. We execute them in a separate thread, so they *should* be mostly isolated, performance-wise, from the HTTP server doing HTTP things.

However, even though the protocol isn't *directly* participating in the main thread's event loop, it will *effectively* still need to wait for that event loop to be free at certain times:

* When moving the hardware. At a low level, hardware control is async in the main thread's event loop. If the low-level async hardware control gets stuck waiting behind something else that's hogging the event loop, the protocol thread will feel it, because it can't proceed until the hardware command has completed.
* When reporting the protocol's activity to the `ProtocolEngine`. The `ProtocolEngine` is owned by the main thread, shared with the HTTP API, and is generally async. Currently, when a command is executed in the protocol thread, the APIv2 internals schedule an async task to run in the main thread and update the `ProtocolEngine`. But, they wait until that update has completed before allowing the protocol to continue. The update itself should be quick, but it may be stuck waiting behind something else hogging the event loop.

Some things are known or suspected to hog the event loop:

* HTTP response serialization and validation, especially for unbounded responses like `GET /protocols/{id}` and `GET /runs/{id}`.
* Parsing and filesystem queries, like in #6951.
* Inefficient data structure access.
* Possibly, other things that we're missing. `robot-server` is a big process, responsible for a lot.

# Acceptance criteria

This ticket can be closed when the robot *doesn't* visibly stutter or slow down when an ill-behaved task accidentally hogs the event loop.

**Comment by SyntaxColoring** [comment]
I bet this is the problem we theorized in https://github.com/Opentrons/opentrons/pull/8701#pullrequestreview-803063214. I've sent the user a troubleshooting step to confirm.

**Comment by SyntaxColoring** [comment]
This will be closed by the combination of:

* #9170
  Access certain data much more efficiently while occupying the event loop, so we don't hog the event loop as much.
* #9199
  Make it so hardware commands don't have to wait for the main thread's event loop to be free.
* #9238
  Make it so the protocol thread doesn't have to wait for the main thread's event loop to be free when the protocol thread has activity to report.
* #9188
  Make response serialization faster and avoid some unnecessary validation.
* #9197
  Move response serialization out of the event loop and into a worker thread. 

Unfortunately, despite all of this, there's still a user-facing problem of the robot moving more slowly and jittery when it gets busy with HTTP requests. 😢  I will ticket this separately.
