### ISSUE TITLE
Touch tip is slower in 5.0

### ISSUE THREAD

**Issue by mattwelch** [Opentrons/opentrons#9135]
From a user:

> Hi, I’m running a protocol using transfer with `touch_tip=True`. I didn’t set any extra parameters for the touch tip.
Using 5.0.0-beta.4, I found `touch_tip` is much slower (3-5 sec. for example) from 4.x.x (1 sec. or so.). Is it an expected behavior (possibly with updated API) or a bug? I rather expect the same behavior with the same program if the API version is the same.

**Comment by SyntaxColoring** [comment]
I suspect this is the same underlying cause as #9133.

**Comment by SyntaxColoring** [comment]
Closing as a presumed duplicate of #9133.
