### ISSUE TITLE
Containers.create not working

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#915]
As a user, I would like to be able to create containers. 

Note: This is blocking the effort to translate OT1 protocols for OT2 (remaining protocols have custom containers)

## Expected Behavior
- User able to create a container by calling containers.create

## Observed Behavior
- Containers.create fails to create container

## Steps to recreate
- Connect to a robot (observed on wandering-dream, on commit #487124e, as well as other robots)

- Run the following basic container.create() command:

containers.create(
    '3x6_plate',                    # name of you container
    grid=(3, 6),                    # specify amount of (columns, rows)
    spacing=(12, 12),               # distances (mm) between each (column, row)
    diameter=5,                     # diameter (mm) of each well on the plate
    depth=10)                       # depth (mm) of each well on the plate

- Attempt to load the container

- Get the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/opentrons/__init__.py", line 36, in load
    return cnt.load(self.robot, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/opentrons/containers/__init__.py", line 73, in load
    return robot.add_container(container_name, slot, label, share)
  File "/usr/local/lib/python3.6/site-packages/opentrons/robot/robot.py", line 845, in add_container
    container = _setup_container(name)
  File "/usr/local/lib/python3.6/site-packages/opentrons/robot/robot.py", line 120, in _setup_container
    container_name)
  File "/usr/local/lib/python3.6/site-packages/opentrons/data_storage/old_container_loading.py", line 87, in get_persisted_container
    .format(container_name, containers_file_list)
ValueError: Container type "3x6_plate" not found in files: ['/usr/local/lib/python3.6/site-packages/opentrons/config/containers/default-containers.json']

**Comment by umbhau** [comment]
fyi @andySigler @btmorr. 

This is a blocker for updating OT1 protocols to OT2 (we're through 90% of the protocols, but the remaining ones have customer containers).

**Comment by btmorr** [comment]
@umbhau I don't know how this used to work, but currently `containers.create` has a parameter named `save` with a default value of `False`. If save is false, the container is returned (so it can be assigned to a variable and used in the protocol) but is not saved to the database. To get the desired behavior, add `save=True` to the parameters.
