### ISSUE TITLE
Protocol upload - Protocol name is not updating

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#9163]
# Overview
The name at the top of the protocol upload page still shows "Protocol - Untitled". Even though the protocol has a name. 
Note: Reopening this. Nusrat reported the same issue in BETA-6. The python protocol in question is attached to this ticket.

# Acceptance Criteria

- [ ] The protocol name should be displayed at the top of the Protocol Upload page for both json and python protocols

**Comment by sakibh** [comment]
I am able to see the protocol names for both JSON and Python protocols (screenshots below) on the latest version (5.0.0-beta.5). Perhaps the JSON protocol was exported without a title so it displayed as "Untitled"?

![image](https://user-images.githubusercontent.com/14794021/147962334-c8562cb9-a7b4-4d58-b496-c8d7215b197b.png)

![image](https://user-images.githubusercontent.com/14794021/147962364-4a4075d8-c36a-4dea-8120-d2d01adb44a2.png)

**Comment by b-cooper** [comment]
Investigate if the name is properly falling back to the filename

**Comment by mikecardarelli** [comment]
Anthony W. to attempt to repro on the new BETA

**Comment by anthonywilleee** [comment]
@b-cooper I gave this shot on 5.0.0-beta.5

Sakib is correct - if the JSON protocol is exported without a protocol title the name reads "untitled"
If the JSON protocol is exported with a title, the title displays.

If that's the intended functionality I think we're good here.  FWIW, it's easy to miss the title field in PD, so I expected the filename to show as the protocol name.

**Comment by anthonywilleee** [comment]
@b-cooper followed up with Emily on this, shes agrees something we can tackle later, perhaps with milestone 1 work. Closing this ticket.

**Comment by mikecardarelli** [comment]
[https://app.zenhub.com/files/38644841/a584c9a3-0357-4bf3-b547-21c86974f1e9/download](https://app.zenhub.com/files/38644841/a584c9a3-0357-4bf3-b547-21c86974f1e9/download)
