### ISSUE TITLE
Re-run protocol - A previously run protocol is re-run not the most recent one

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#9164]
# Overview
Reported by Anthony W.: "after running a new protocol, my re-run option does not update with the latest protocol. instead, i only have the option to re-rerun my first attempted protocol of the day. i have closed the app and disconnected from the robot, and tried again, but the issue persists"

# Acceptance criteria

- [ ] The re-run protocol button should kick off the most recent protocol that was run on the robot

**Comment by shlokamin** [comment]
I thought this was fixed in https://github.com/Opentrons/opentrons/pull/9073, but let's make sure

**Comment by sakibh** [comment]
> I thought this was fixed in #9073, but let's make sure

I just tested this, the changes in #9073 does address this issue and works fine. Perhaps the ticket is prior to #9073 being merged?

**Comment by shlokamin** [comment]
great, thanks for testing @sakibh! @mikecardarelli im gonna close this
