### ISSUE TITLE
protocol engine: drop tip on cancel-> Paired pipette support

### ISSUE THREAD

**Issue by sanni-t** [Opentrons/opentrons#9191]
After #9169 is merged, the robot will perform a drop tip after a protocol is canceled mid-run. But it won't reliably do so for protocols using paired pipettes or 'twinning'.

In order to support paired pipettes:

1. Protocol engine will need to add support for updating multiple pipette states in a single pipette handling command.
2. The legacy command mapper will need to map paired pipette commands to issue the correct engine commands.

A quick way of implementing this feature is bypassing protocol engine's tip tracking and using the hardware controller's tip tracking to get pipette tip status, and then dropping tip if found attached. This will be quite similar to the v4.7 version of drop tip on cancel.

**Comment by mattwelch** [comment]
Closing as twinning isn't supported post 4.7.
