### ISSUE TITLE
PD: Tip positioning graphic doesn't match value

### ISSUE THREAD

**Issue by b-cooper** [Opentrons/opentrons#9227]
Initial bug report: 

"PD and it says 1mm from the bottom of the well, but it looks much higher on the picture below."

![Screen Shot 2022-01-10 at 5.14.54 PM.png](https://images.zenhubusercontent.com/5e1e15beea955f9181a402d3/b96e8de8-4947-4bc2-9c82-b08c7a765f38)

protocol where this was encountered: https://opentrons.slack.com/files/U016YAES93P/F02TT6GU28H/test___4_.json

**Comment by y3rsh** [comment]
Created in Jira, please do fixes and further docs there
https://opentrons.atlassian.net/browse/RQA-164
