### ISSUE TITLE
Error thrown after LPC with JSON protocols

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#9239]
Reported from a BETA tester: 
> The protocol can be uploaded, recognized. The labware position check can be finished for the tip rack, but then the error 422 will occur. I can not proceed the following position check for other labware. 

![Screen Shot 2022-01-11 at 6.57.52 PM.png](https://images.zenhubusercontent.com/5e20a4f595a33208d0d768ab/bcdbec7e-20d7-4f33-8167-344eb643f91a)

The JSON files can be found here: 
[https://app.zenhub.com/files/38644841/8914bb2e-011e-42bb-a1a5-8f34ced484c5/download](https://app.zenhub.com/files/38644841/8914bb2e-011e-42bb-a1a5-8f34ced484c5/download)

**Comment by sakibh** [comment]
Was unable to reproduce this error on the robot in Beta 6.
