### ISSUE TITLE
Protocol upload fails when trying to upload make_sound.py

### ISSUE THREAD

**Issue by skyewindsor** [Opentrons/opentrons#9240]
# Overview

Protocol upload fails when trying to upload make_sound.py

# Steps to reproduce

App on 5.0.0-beta.5 
Firmware Version: v1.1.0-25e5cea
Wireless connection

Try to upload the [make_sound.py](https://drive.google.com/file/d/13XFBYKTvYdD_7pyT-2zIqIgu0jErBnwR/view) protocol via the "Choose File..." button and by dragging and dropping.

# Current behavior

App fails to complete protocol upload for make_sound.py, both when using "choose file" button and dragging and dropping. The spinning circle loading modal pops up and quickly disappears before returning to the empty state protocol upload view. 

Screen capture of the behavior here: [https://drive.google.com/file/d/1k3mAz8Gh6hEA9SvAdDWQtfVpo6dOw07V/view?usp=sharing](https://drive.google.com/file/d/1k3mAz8Gh6hEA9SvAdDWQtfVpo6dOw07V/view?usp=sharing)

# Expected behavior

Upon uploading make_sound.py on the protocol upload page (both via the "choose file" button and dragging and dropping), the spinning circle loading screen should pop up for a short while before the protocol overview/setup page pops up.  

Protocol upload page designs here: [https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Milestone-0%3A-Protocol-Upload-Revamp?node-id=3205%3A22](https://www.figma.com/file/JCQNOTTK9tTmYPhRqeOfSj/Milestone-0%3A-Protocol-Upload-Revamp?node-id=3205%3A22)

**Comment by shlokamin** [comment]
closing this since the protocol attached is an invalid python file. it misuses literal backslashes in python, which is why the server won't accept it. since this ticket was filed we implemented logic to properly display errors to users, so now they'd see that the python file is invalid
