### ISSUE TITLE
Pipette generation mismatch error is not displayed - Regression introduced

### ISSUE THREAD

**Issue by reachojhaneha** [Opentrons/opentrons#9259]
robot-server has gen1 pipette, and when i upload a protocol with Gen 2 pipette, there is Pipette missing error shown instead of pipette generation mismatch.
<img width="1021" alt="Screen Shot 2022-01-24 at 4 05 05 PM" src="https://user-images.githubusercontent.com/39049853/150864641-9bc2174a-7e96-4182-97b2-53c9cd867df4.png">

Protocol Used:
[gen1 pipette.json.zip](https://github.com/Opentrons/opentrons/files/7928860/gen1.pipette.json.zip)

**Comment by reachojhaneha** [comment]
pipette generation mismatch was working in previous beta releases but now its failing in beta-5

**Comment by shlokamin** [comment]
@reachojhaneha I am unable to repro this issue. Can you please add a body to this ticket, and include which pipettes you have attached, along with the protocol you used to test this?

**Comment by shlokamin** [comment]
@reachojhaneha the protocol you've attached uses a p20 which does not have a gen 1 counterpart.

**Comment by shlokamin** [comment]
I can't seem to repro with a p300 gen1 vs gen2 mismatch. Are you sure this is a bug?

**Comment by shlokamin** [comment]
I'm going to close this ticket until we can reopen with repro steps that reflect the bug
