### ISSUE TITLE
bug: App is redirecting to robot page instead of pipettes page when attach pipette is clicked 

### ISSUE THREAD

**Issue by nusrat813** [Opentrons/opentrons#9267]
# Current behavior

When a user clicks attach pipette for a missing pipette on the protocol page in 5.0.0-beta.6, the app redirects the user to the main robot page. The user then needs to navigate to the pipettes page to attach pipette. 
# Expected behavior

If a user clicks attach pipette, the app should redirect users to the attach pipette flow

**Comment by mikecardarelli** [comment]
Someone should look into this, but if we don't have a good way to link to the pipettes page directly, we should consider punting on tis to 5.0.1 or later
