### ISSUE TITLE
H/S Module Card: Overflow Menu

### ISSUE THREAD

**Issue by anthonywilleee** [Opentrons/opentrons#9289]
# Overview

The dropdown menu on the H/S module card is where all the action happens outside of a protocol run.  It offers users control of the heater, shaker, and labware latch, in addition to the ability to redo set up, test shake, firmware update, and look at more module information.  

# Implementation Details

General
- Module actions are disabled if a protocol is running. There will be a hover state on the menu icon that reads" Module actions unavailable while protocol is running."

There are a total of six items in the overflow menu:

- **Change temperature** - Opens up the temperature control slideout when clicked. 
-- This changes to "Deactivate' when there's already a temperature target. 

- **Set shake speed** - Opens up the shaker control slideout when clicked. 
-- This changes to 'Deactivate' if shaking is happening
-- This is disabled if labware latch is open. 
-- When disabled, there is a hover state that reads "Cannot shake when labware latch is open."

- **Open/Close labware latch** - Directly opens/closes labware latch appropriately when clicked. 
-- If labware latch is currently closed, the action in the dropdown should read "Open labware latch"
-- If labware latch is currently open, the action in the dropdown should read "Close labware latch"
--  This is disabled if the heater shaker is currently shaking (cannot open latch while module is shaking)
-- When disabled, there is a hover state that reads "Cannot open labware latch while module is shaking."

- **About module** - Opens up About module slideout.

- **See hot to attach to deck** - Triggers set up wizard

- **Test Shake** -  Open the test shake slide out. This shares functionality with the test shake modal in the set up wizard

# Design Links
- https://www.figma.com/file/695ogls23YsQYImRcGYDE1/Heater-Shaker?node-id=1877%3A84179

# Acceptance Criteria

**General**
- [x] Module actions are disabled if a protocol is running. There is a hover state on the menu icon that reads "Module actions unavailable while protocol is running."
- [x] Overflow menu adheres to design linked in this ticket, including layout, copy, colors, etc.

**Change Temperature**
- [x] Clicking "Change temperature" opens temp control slideout
- [x] "Change temperature" changes to "Deactivate" if a temperature target is set
- [x] Clicking "Deactivate" deactivates the heater

**Set shake speed**
- [x] Set shake speed opens shake control slideout when clicked
- [x] "Set shake speed" changes to 'Deactivate' if shaking is happening
- [x] Clicking "Deactivate" deactivates the shaker
- [x] "Set shake speed" is disabled if labware latch is open. 
- [x] When disabled, there is a hover state that reads "Cannot shake when labware latch is open."

**Open/Close labware latch**
- [x] If labware latch is currently closed, the action in the dropdown reads "Open labware latch." Clicking directly opens the labware latch
- [x] If labware latch is currently open, the action in the dropdown reads "Close labware latch." Clicking directly closes the labware latch
- [x] Selection is disabled if the heater shaker is currently shaking (cannot open latch while module is shaking)
- [x] If disabled, there is a hover state that reads "Cannot open labware latch while module is shaking."

**About module** 
- [x] Clicking opens up About module slideout.

**See how to attach to deck**
- [x] Clicking triggers set up wizard

**Test Shake** 
- [x] Clicking opens the test shake slide out.

**Comment by shlokamin** [comment]
@jerader @sakibh i think this was done a while ago, forgot to close this earlier

**Comment by shlokamin** [comment]
oops sorry wrong ticket please ignore, reopening
