### ISSUE TITLE
bug: Multiple modules of the same type are swapped between protocol setup and execution

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#9309]
# Overview

In protocols with multiple modules of the same type, the wrong module will be controlled.

# Steps to reproduce

I've tested this with two Temperature Module GEN1s and a non-refresh OT-2 running the v5.0 beta.

@nusrat813 has tested this with a refresh OT-2 running v4.7.

1. Load the two Temperature Modules into slots 1 and 3.
2. Plug the *right* module into the *left*  USB port and the *left* module into the *right*  USB port.
3. Upload the test protocol.
4. Confirm that in the module setup, the USB ports match reality. It should look like this: ![Screen Shot 2022-01-24 at 5.27.11 PM.png](https://images.zenhubusercontent.com/5ed6bd6554659c8604d11840/a2cd7817-f6fc-4e88-adf3-75babeba4b41)
5. Run the protocol.

## Test protocol

```python
metadata = {"apiLevel": "2.11"}

def run(protocol):
    tip_rack = protocol.load_labware("opentrons_96_tiprack_300ul", 2)
    tm_right = protocol.load_module("temperature module", 3)
    tm_left = protocol.load_module("temperature module", 1)
    plate_right = tm_right.load_labware("biorad_96_wellplate_200ul_pcr")
    plate_left = tm_left.load_labware("biorad_96_wellplate_200ul_pcr")

    pipette = protocol.load_instrument("p300_single_gen2", mount="left", tip_racks=[tip_rack])

    tm_right.set_temperature(40)
    tm_left.set_temperature(20)

    pipette.transfer(150, plate_right["A1"], plate_left["A1"])
```

# Current behavior

The module on the right goes to 20 °C and the module on the left goes to 40 °C.

# Expected behavior

The opposite. The module on the right should go to 40 °C and the module on the left should go to 20 °C.

**Comment by SyntaxColoring** [comment]
Possibly caused by #9253.

**Comment by mcous** [comment]
Investigation results on v5.0.1:

- PAPIv2 / ProtocolEngine
    - Modules are "consumed" in descending order by port number
- App
    - Modules are assumed to be "consumed" in ascending order by port number
- App instructions
    - Users are instructed to plug modules in according to deck slot

Conclusions:

- The app and the API disagree on how load order maps to physical port order
- The app's instructions are straight up wrong and I can't think of any way we could make the system behave as the instructions specify

**Comment by splaisan** [comment]
we have a similar issue with two mag-modules but the issue is semi-random and occurs or not in the same protocol at a given code locations (works in the beginning of the protocol and swaps the deviced further on)
I suggest the program be improved to avoid having to sort anything, devices are declared on top of the code and should be addressed correctly I believe.
the fact our error is semi random suggests a more complex issue with USB ports being somehow wrongly addressed/incremented! ([ ref:_00Df44lpsm._5002S1SsrOb:ref ])

**Comment by SyntaxColoring** [comment]
@splaisan Can you tell me what you see as:

1. **The version of your Opentrons App:** <img width="1024" alt="Screen Shot 2022-05-09 at 10 48 25 AM" src="https://user-images.githubusercontent.com/3236864/167436522-08fc8b25-7f4d-4938-882d-bf93e8e8b202.png">
2. **Your OT-2's server version:** <img width="1024" alt="Screen Shot 2022-05-09 at 10 48 19 AM" src="https://user-images.githubusercontent.com/3236864/167436341-8c014b5a-6e8e-4cb7-84cb-e1fafb85f553.png">

(In these example screenshots, mine is `5.1.0-beta.0`, but yours will probably say something different.)


The modules swapping themselves in the *middle* of a protocol is pretty alarming. Can you share your full protocol file along with any custom labware definitions that might be required to run it?

**Comment by braldrich** [comment]
@SyntaxColoring I am working with this customer in Salesforce, but they are on 5.0.2 app and robot server version. 

@splaisan Please provide your protocol here or in our email correspondence.

**Comment by splaisan** [comment]
Hi @braldrich 
I already provided the protocol with my above-linked ticket few days ago. and explained our issue in the ticket.
Can you access this directly? I am not at the lab now.

**Comment by braldrich** [comment]
[Archive.zip](https://github.com/Opentrons/opentrons/files/8652983/Archive.zip)

Protocols here
