### ISSUE TITLE
Deck map: Add hover state to each labware

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#9314]
Right now the labware name gets truncated on the deck map making it hard to know which labware is required during deck setup. Let's show the full labware name without truncation when the mouse hovers over any labware on the deck.

![Screen_Shot_2022-01-26_at_10_43_27_AM.png](https://images.zenhubusercontent.com/5e20a4f595a33208d0d768ab/91cfa847-c91c-4c01-8723-c1d5ec057f6f)

**Comment by nusrat813** [comment]
Fixed in 5.0.2
