### ISSUE TITLE
Device Details: H/S Module Card

### ISSUE THREAD

**Issue by shlokamin** [Opentrons/opentrons#9329]
# Overview

This ticket outlines the frontend side of the heater shaker module card in device details.

# Implementation details
The module card should be composed out of a generic `ModuleCard` component that can be shared by all other modules

Conditionally render the heater shaker module card inside of `app/src/pages/Devices/DeviceDetails/index.tsx` if there is/are heater module(s) attached.

# Design
https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=1864%3A117484

# Acceptance criteria
Module card should display...
- [ ] A rendering of the heater shaker module
- [ ] The port the module is connected in
- [ ] The heater shaker icon icon
- [ ] The module's display name
- [ ] The module's heater status (idle, heating, heated)
- [ ] The modules target temperature (in Celcius) 
- [ ] The module current temperature (in Celcius) 
- [ ] The module's shaker status (idle, shaking)
- [ ] The module's target RPM 
- [ ] The module's current RPM 
- [ ] Labware latch status (open, closed, closed and locked)
- [ ] Labware latch lock icon when latch status is closed and locked
- [ ] When clicking on the settings button, it should display 4 dropdown buttons that say `Change temperature`, `Set shake speed`, `Close labware latch`, and `About module`. For now, just `console.log` when each button is pressed

**Comment by anthonywilleee** [comment]
@shlokamin those are the correct heater statuses.  The dropdown menu may also have selection for set up and test shake, TBD based on user testing this week

**Comment by anthonywilleee** [comment]
Dup with [9288](https://app.zenhub.com/workspaces/app--ui-5f6248dba845b000139aa767/issues/opentrons/opentrons/9288). Closing
