### ISSUE TITLE
bug: APIv2 sometimes uses geometry for the wrong generation of a loaded module

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#9365]
# Overview

When you do `protocol.load_module("temperature module gen2")` in your protocol, two things happen, in this order:

1. The API loads the geometry of a Temperature Module GEN2.
2. The API searches for any physically connected Temperature Module GEN1s or Temperature Module GEN2s, and uses the first one that's available. (Either GEN1 or GEN2 is allowed because they are compatible with each other.)

The problem is that depending on what step (2) returns, the geometry returned by step (1) might be wrong.

The relevant code:

https://github.com/Opentrons/opentrons/blob/466e0567065d8773a81c25cd1b5c7998e00adf2c/api/src/opentrons/protocols/context/protocol_api/protocol_context.py#L185-L206

# Steps to reproduce

1. Set up a robot with a GEN1 Temperature Module.
2. Have a protocol do `load_module("temperature module gen2")`.

Or vice-versa.

# Current behavior

The Python Protocol API loads the 

From reading our module definition code, our only current pair of compatible modules is Temperature Module GEN1 and Temperature Module GEN2.

One of the differences between Temperature Module GEN1 and Temperature Module GEN2 is a 1.3 mm labware offset in the x-axis. (Compare [temperatureModuleV1.json](https://github.com/Opentrons/opentrons/blob/decbcbb753acdae9d7f0f1d79b332fb3a535e0cb/shared-data/module/definitions/3/temperatureModuleV1.json#L5-L9) with [temperatureModuleV2.json](https://github.com/Opentrons/opentrons/blob/decbcbb753acdae9d7f0f1d79b332fb3a535e0cb/shared-data/module/definitions/3/temperatureModuleV2.json#L5-L9).)

I haven't tested this, but I *think* this means: if your protocol loads a compatible but non-identical Temperature Module, the positioning before labware calibration will always be 1.3 mm wrong.

In v4.7 and prior, it's possible that this offset would have been visible during labware calibration, so it would have been calibrated out, hiding the bug. With the changes in v5.0, this will no longer be the case.

# Expected behavior

During protocol execution, the Python Protocol API should use the geometry for the module model that it actually found physically connected. Not the module model that the user wrote in their Python script.

During protocol simulation, what the user wrote in their Python script should map directly to what the simulating hardware API reports as "connected," so it shouldn't matter there.

**Comment by mcous** [comment]
Closed by #9364
