### ISSUE TITLE
feat: move homing, light, open lid and modules into Protocol Engine

### ISSUE THREAD

**Issue by mattwelch** [Opentrons/opentrons#9366]
Have the protocol engine http handlers also handle homing, light, open lid and modules. Further, define, along with UX and Apps&UI, the behavior when the robot is engaged in various activities and it's asked via http to engage in another activity.

## Acceptance criteria
- [ ] homing, light, open lid and modules are now handled by PE endpoints
- [ ] a grid is constructed w/ robot activities (run, calibrate, open lid, etc) along both axis and the grid is populated with what the robot should respond with if it's doing the thing on the left, and it's asked to do the thing on the top
- [ ] a new ticket to implement the behaviors defined in the grid

**Comment by mcous** [comment]
Superseded by #9617
