### ISSUE TITLE
Protocol upload: Clearer error messaging needed when custom labware definition is missing

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#9378]
# Current Behavior
When uploading a protocol without uploading the custom labware files first, the OT app displays a vague error: something about an erroneous "tip_state" on ~ line 1653 

After uploading the custom labware, the protocol successfully uploaded after 5-10 minutes. 

# Expected Behavior
The error message should indicate that the custom labware is missing. 

# Files to reproduce the issue
[Protocol + labware defs](https://app.zenhub.com/files/38644841/eb3b08bc-5f4b-4c26-b5a1-e20e3d37c208/download)

**Comment by mikecardarelli** [comment]
[https://app.zenhub.com/files/38644841/eb3b08bc-5f4b-4c26-b5a1-e20e3d37c208/download](https://app.zenhub.com/files/38644841/eb3b08bc-5f4b-4c26-b5a1-e20e3d37c208/download)

**Comment by mcous** [comment]
This is an issue with the protocol itself. It is written in a way that swallows the labware missing error. If the protocol is not written to swallow errors from `load_labware`, the user will receive a labware missing error in the app.

![Screen Shot 2022-02-04 at 12 30 39](https://user-images.githubusercontent.com/2963448/152593775-e469a554-facf-451e-bf2f-13306d9be91e.png)

Excerpts from the attached protocol, with comments added for clarity around what the protocol file is doing wrong, exactly.

```python
try:
    protocol.load_labware(...)  # <- bad idea to wrap a `load_labware` in a try. If
                                #    custom labware is missing, it will raise an error.
    ...                         # <- some other setup code normally happens here,
                                #    but it will never run if `load_labware` raises

except:                         # < bad idea to not filter your except
    raise                       # < also not a good idea to uselessly re-raise like this

finally:                        # < the code inside `finally` gets no matter what.
    ...                         #   Something in here raises an unrelated error because
                                #   it tries to use a variable that was never set up
                                #   because the `load_labware` failed and the error was
                                #   swallowed. The missing labware error is completely lost
```
