### ISSUE TITLE
Error thrown when running the Swift smoke test

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#9381]
# Current Behavior
Ran into thermocycler error when running swift smoke api.log line 1260 shows the error.

![image (4) - Derek Maggio.png](https://images.zenhubusercontent.com/5f57e13054c0d9cd55c2adb3/23a2df76-e9e9-4d3a-b768-8db112c1c603)
![image (5) - Derek Maggio.png](https://images.zenhubusercontent.com/5f57e13054c0d9cd55c2adb3/26db2784-cffe-46c3-9c12-7ee2333e8df3)

# Expected Behavior
The protocol should run without errors.

**Comment by emilywools** [comment]
[https://app.zenhub.com/files/38644841/21705787-06b3-4803-a5e1-08e625f4a8ac/download](https://app.zenhub.com/files/38644841/21705787-06b3-4803-a5e1-08e625f4a8ac/download)

**Comment by mikecardarelli** [comment]
@nusrat813 Can you recreate this?

**Comment by mikecardarelli** [comment]
@nusrat813 Can you check with Derek and see if this is hardware-related?

**Comment by mikecardarelli** [comment]
Hardware issue. Closing this
