### ISSUE TITLE
PAPIv3/PAPIv2 capabilities parity (PE Public release)

### ISSUE THREAD

**Issue by mattwelch** [Opentrons/opentrons#9394]
This epic tracks the work to enable full 1:1 feature parity support between PAPIv2 and PAPIv3. This will officially "finish" the first phase of protocol engine development, and provide a path for our users to start using protocol engine infrastructure.

**Comment by SyntaxColoring** [comment]
I think this was replaced by https://opentrons.atlassian.net/browse/RCORE-379 or https://opentrons.atlassian.net/browse/RCORE-601.
