### ISSUE TITLE
feat(engine): analyze ctx.load_module during protocol analysis

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#9416]
## Overview

As a user uploading a PAPIv3 protocol for analysis, I would like the analysis to report module usage.

## Acceptance criteria

- [ ] A PAPIv3 protocol uploaded via `POST /protocols` reports back module loads and usage in its analysis

## Implementation notes

At the moment, a simulating `ProtocolRunner` + `ProtocolEngine` will fail on `loadModule` commands due to the lack of attached hardware to the simulator. Broadly, I see our two best options as:

1. Use or augment the `HardwareAPI` in simulator mode to get module hardware simulators
    - Something like the logic in `HardwareAPI.find_modules`
    - Do not modify the ProtocolEngine
    - This is similar to how PE currently analyzes `loadPipette` commands
2. Add a config to the protocol engine to "virtualize" modules
    - Something like what we do in the ProtocolEngine to analyze `ctx.pause` in PAPIv3

I'm quite partial to exploring option (2), but option (1) may be a better place to start

**Comment by SyntaxColoring** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/opentrons-cpx-5e1f6ed55b295a3f514f2283/issues/Opentrons/opentrons/9416?planning-poker) with ZenHub @mcous @sanni-t @y3rsh

**Comment by mcous** [comment]
Taking option number 2, and leaving the HW API out of it for now. We'll might have to come back in and fold in the hardware simulator when we get to module commands, but for now option 2 should be sufficient to hit the acceptance criteria
