### ISSUE TITLE
Definition of __main__ function for Protocols

### ISSUE THREAD

**Issue by ajbarrett** [Opentrons/opentrons#9439]
I am trying to get a better understanding of how the API works. When we write our protocols, we fill out the "run()" methods, which receives a ProtocolContext object as a parameter. I assume the ProtocolContext object is created in "__main__", and that main then calls the "run()" method. (It may not be exactly like this, but something like that).

I was wondering where I can find the definition for __main__, or where I can find the definition for the method that calls "run()".

**Comment by mcous** [comment]
This is an area of active development, so I'll point you towards the code that will be in the upcoming v5 release, as well as the code for the current v4 line.

In version 5.x onwards, the [`ProtocolRunner`](https://github.com/Opentrons/opentrons/blob/edge/api/src/opentrons/protocol_runner/protocol_runner.py) interface is in charge of provisioning a `ProtocolContext` object and passing it along to the protocol's `run` method.

In this area of the code, you will find Protocol API v2 protocols referred to as "legacy" protocols, on account of the Protocol API v3 release coming later this year. Protocol API v2 will continue to be supported for some time after the PAPIv3 release.

In version 4.x, the `run` method is called by a function called [`run_protocol`](https://github.com/Opentrons/opentrons/blob/v4.7.0/api/src/opentrons/protocols/execution/execute.py). When running a PAPIv2 protocol on the v5.x software, the `ProtocolRunner` will still delegate to this same function for backwards compatibility reasons.
