### ISSUE TITLE
Deprecate schema v6 adapter 

### ISSUE THREAD

**Issue by shlokamin** [Opentrons/opentrons#9467]
# Overview

Currently the client uses an [adapter](https://github.com/Opentrons/opentrons/blob/edge/shared-data/js/helpers/schemaV6Adapter.ts) to transform a protocol's analysis response from the server to conform to JSON schema v6. We'd eventually like the server's protocol analysis response to conform to the schema v6. This ticket documents the remaining transformations the schema adapter does to the protocol analysis response:

- Pipettes key
    - PE returns a list of LoadedPipette objects with id, pipetteName, and mount
    - Adapter converts this list into an object keyed by pipette id, who’s value holds objects keyed by “name” (not “pipetteName”)
- Labware key
    - PE returns a list of LoadedLabware objects with id, loadName, definitionUri, and location
    - Adapter converts this into an object keyed by labware id, who’s value holds on object keyed by “definitionId” and “displayName”
- Labware Definitions key
    - PE does not return a “labwareDefinitions” key
    - Adapter iterates through the load labware commands and constructs it’s own “labwareDefinitions” object which conforms to the schema v6 spec (an object keyed by definition Id, who’s value is the labware definition) 
- Modules key
    - PE does not return a "modules" key
    - Adapter iterates through the load module commands and constructs it’s own “modules” object which conforms to the schema v6 spec (an object keyed by module Id, who’s value is an object keyed by “model”)

**Comment by SyntaxColoring** [comment]
@shlokamin This is stale, right? I'm cleaning up old `robot-svcs` tickets.
