### ISSUE TITLE
bug: Robot status displayed as running while LPC is exited and robot homing 

### ISSUE THREAD

**Issue by nusrat813** [Opentrons/opentrons#9479]
# Overview

When a user completes LPC the robot is homing, while the robot is homing user clicks proceed to run and is now in the run tab. The run tab displays the status of the robot as running and only lets user pause run instead of start run. Once the homing is complete the user then sees the button change to start run

# Steps to reproduce

# Current behavior
<img width="1024" alt="Screen Shot 2022-02-15 at 4 33 47 PM" src="https://user-images.githubusercontent.com/30632549/154160683-61b0f02b-a614-4e63-940d-8cf6748de15a.png">

# Expected behavior

<img width="1118" alt="Screen Shot 2022-02-15 at 4 34 05 PM" src="https://user-images.githubusercontent.com/30632549/154160695-18c252fd-09d9-422a-a5fe-fc5665777c37.png">

**Comment by b-cooper** [comment]
confirm this is not a problem with smoketest before release candidate is tagged

**Comment by mikecardarelli** [comment]
@hartm9 to check if this is still happening

**Comment by hartm9** [comment]
This behavior is still happening - I grabbed a screenshot of the app while the robot was homing after LPC: 
![image](https://user-images.githubusercontent.com/95253324/171920600-ed594583-3a71-40f5-b45d-6e1c413e2321.png)

After clicking the Pause Run button, the homing routine paused, and clicking Resume Run caused the protocol to begin.

**Comment by b-cooper** [comment]
This is no longer reproducible in edge, as of recent changes to the robot-server that make sure the run status is not set to "running" until after LPC is finished and the run has been initiated.
