### ISSUE TITLE
Separation of Robot functions into different processes

### ISSUE THREAD

**Issue by mattwelch** [Opentrons/opentrons#9486]
Currently, robot functions like protocol execution, hardware control and http server all share a single process, resulting in robot slowdowns when too many things need to be serviced at once.

This epic tracks the Robot Services work to investigate solutions and work with other teams to implement those solutions.

This work is a prerequisite for a dev platform launch, as the possibility of multiple clients connecting to the robot cannot be confidently accommodated currently.

**Comment by SyntaxColoring** [comment]
Hardware controller in its own process: moved to RET-1379
Protocol analysis in its own process: moved to RSS-93
