### ISSUE TITLE
UI Updates for App Settings

### ISSUE THREAD

**Issue by smb2268** [Opentrons/opentrons#9528]
Complete the UI updates from Mel's review of App Settings. The designs are side by side [here](https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=5216%3A194475) in Figma.
Also look into whether we can use `NavLink` to apply tab styles in the `AppSettingsHeader`

**Comment by mikecardarelli** [comment]
Looks like this is done
