### ISSUE TITLE
bug: Protocol Designer and the Python Protocol API calculate default Magnetic Module engage heights differently

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#9529]
# Background

Some labware define a default engage height for when they're used on a Magnetic Module.

In Python, this lets you do `magnetic_module.engage()`, without specifying a height yourself, and the magnets will automatically rise to that default engage height.

In Protocol Designer, this populates the default and recommended values for the height field:

<img width="309" alt="Screen Shot 2022-02-18 at 5 57 35 PM" src="https://user-images.githubusercontent.com/3236864/154772339-841cb92d-f347-41af-a7a1-0325d85b725c.png">
 
At the time of writing, these standard labware define a default engage height:

* `biorad_96_wellplate_200ul_pcr`
* `nest_96_wellplate_100ul_pcr_full_skirt`
* `nest_96_wellplate_2ml_deep`
* `thermoscientificnunc_96_wellplate_1300ul`
* `thermoscientificnunc_96_wellplate_2000ul`
* `usascientific_96_wellplate_2.4ml_deep`

(Found by grepping `shared-data/labware/definitions/*.json` for `magneticModuleEngageHeight`).

I don't know if any custom labware do. They might.

# Problem overview

For at least some of those labware, the default height chosen by Protocol Designer is not the same as what the Python Protocol API will choose if you do `magnetic_module.engage()` without any arguments.

(Fortunately, though, if you manually set your Python `height_from_base` to match Protocol Designer, I think it will match.)

# Steps to reproduce

Here are Python and Protocol Designer protocols that should be equivalent.

They each load a `nest_96_wellplate_100ul_pcr_full_skirt` atop a Magnetic Module GEN2.

The Python Protocol does `.engage()` (with no arguments), and the Protocol Designer protocol engages to 6 mm from the bottom of the labware, which is the default that Protocol Designer recommends.

* [Raise magnets to default.json.zip](https://github.com/Opentrons/opentrons/files/8100957/Raise.magnets.to.default.json.zip)
* [raise_magnets_to_default.py.zip](https://github.com/Opentrons/opentrons/files/8100962/raise_magnets_to_default.py.zip)

(Based on investigation and test cases from @Gyliann and @alexjoel42 in #8165. Thank you!)

I tested this on Protocol Designer 5.2.6 and app+robot v5.0.0, but I'd also expect it to be a problem on app+robot v4.7.0.

# Current behavior

With the Protocol Designer protocol:

* Protocol Designer shows the height as "6" above the bottom of the labware.
* Physically, measured with calipers, the magnets successfully move to 6 mm from the bottom of the labware.
* The OT-2 sends this serial command to the module: `G0 Z8.5`. 8.5 is 2.5 higher than 6 because it needs to include [the distance from the magnets' home point to the bottom of the labware](https://github.com/Opentrons/opentrons/blob/9fadafce7cd575ae3db08aca7e5257dd6c186ddc/api/src/opentrons/hardware_control/modules/magdeck.py#L20).
* The Opentrons App shows the module engaged to 8.5 mm, which makes sense, given [other bugs](https://github.com/Opentrons/opentrons/issues/9515).

With the Python protocol:

* Physically, measured with calipers, the magnets move to 7.5 mm.
* The OT-2 sends this serial command to the module: `G0 Z10.0`. As with the Protocol Designer test, 10.0 is 2.5 higher than 7.5 because it needs to include the distance from the magnets' home point to the bottom of the labware.
* The Opentrons App shows the module engaged to 10 mm, which, as with the Protocol Designer test, makes sense, given [other bugs](https://github.com/Opentrons/opentrons/issues/9515).

The default in the Python protocol is 1.5 mm higher than the default in the Protocol Designer protocol.

# Expected behavior

If a Protocol Designer protocol uses the default recommended engage height, that should cause the same physical outcome as a Python protocol that does `.engage()`. (Assuming neither side deliberately preserves different behavior for the sake of backwards-compatibility.)

It's difficult for me to tell which side is currently behaving correctly. Our [labware definition specification](https://github.com/Opentrons/opentrons/blob/9fadafce7cd575ae3db08aca7e5257dd6c186ddc/shared-data/labware/schemas/2.json#L156-L159) is ambiguous, *and* I believe different labware currently have different interpretations of it.

* When is `magneticModuleEngageHeight` in true millimeters, and when is it in "short millimeters"?
* What is the origin point? The magnets' home position, or the bottom of the labware, or something else?

Possibly, both sides are behaving incorrectly.

The documentation ambiguity is ticketed as part of #10830.

**Comment by SyntaxColoring** [comment]
It's 7:00 PM on a Friday, so I'll fill in this comment later, but very briefly, I'm noticing two discrepancies between Python's `_determine_lw_engage_height()` and JS's `getLabwareDefaultEngageHeight()`:

* For the offset between the home position and the bottom of the labware, Python uses 2.5 mm (true mm), whereas JS uses 4 mm (true mm). In the specific repro steps above, this is where the difference of 1.5 mm comes from.
    * I don't know which is correct. I'd *guess* Python because if I do `engage(height_from_base=0)` with a Magnetic Module GEN2, that looks pretty dead-on to me.
* There are 3 specificlabware where `magneticModuleEngageHeight` is apparently interpreted in "short mm" instead of true mm. JS and Python both do this. *However,* in addition to interpreting those labware's heights as short mm, JS interprets them as being measured from the home position, and Python does *not.*
    * Note that this discrepancy will currently affect one Opentrons standard labware: `nest_96_wellplate_2ml_deep`. It may also affect custom labware.
    * I haven't the faintest idea which side correct.

Also, I've only been thinking through the GEN2 Magnetic Module cases, so far I'm not sure how things change when GEN1 Magnetic Modules get involved. Presumably, not in a good way.

**Comment by mcous** [comment]
This ticket has been split into several issues under the RSS-109 epic
