### ISSUE TITLE
Add H/S Step Form Container

### ISSUE THREAD

**Issue by anthonywilleee** [Opentrons/opentrons#9565]
# Overview

This ticket is create an empty version of the Heater Shaker step form.  

The design of the step form is in progress.  This ticket can be updated with the specifics or we can create a new ticket when design is complete.

# Implementation Details
- The Heater Shaker step form should display when a Heater Shaker is present in a protocol and a Heater Shaker step is selected from the "Add Step" dropdown
- This ticket is to build the basic container for the form. It will share basic design and layout with other forms, including placement, styling, secondary CTA's of "Delete" and "Notes", and primary CTAs of "Cancel" and "Save"

# Design Links
https://www.figma.com/file/695ogls23YsQYImRcGYDE1/Heater-Shaker?node-id=2770%3A83961

# Acceptance Criteria
- The Heater Shaker step form displays when Heater Shaker step is selected from the drop down menu. This can be empty for now
- Any universal characteristics of the step form are present, including placement, styling, framing & basic layout, and CTAs

**Comment by howisthisnamenottakenyet** [comment]
Updated this to the final files figma link

**Comment by shlokamin** [comment]
think this was closed a while ago, if style changes need to be made we can create a new ticket
