### ISSUE TITLE
Add H/S Step in Protocol Timeline

### ISSUE THREAD

**Issue by anthonywilleee** [Opentrons/opentrons#9566]
# Overview

This ticket is for adding the Heater Shaker step into the protocol timeline. This should behave and function the same as other steps in the protocol timeline.

# Implementation Details

- A Heater Shaker Step should display, along with the h/s icon, in the protocol timeline in the order it was added
- Step is expandable/collapsable.  
- Step displays status for all H-S elements:
-- Temperature references and displays the labware that is on the module. It will display the specified temp in C. If no temp specified, display "Deactivated"
-- Labware Latch displays Open, Closed, Closed and Locked as specified by user. Closed and Locked will always appear while the shaker is shaking
-- Shaker displays RPM as specified by user. If no RPM specified, display "Deactivated"
-- "Deactivate after" displays the time specified by user when a Set Timer is set. If no timer is set, display nothing 
- If selected, step should be highlighted per current styling
- Step should be clickable. Clicking on the h/s step in the protocol timeline opens the h/s step form
- Step should work with batch edit functionality, meaning it is shift+clickable, and can be acted on with the batch edit toolbar

# Design Links
- https://www.figma.com/file/695ogls23YsQYImRcGYDE1/Heater-Shaker?node-id=2770%3A83961

# Acceptance Criteria
- [ ] A Heater Shaker Step displays, along with the h/s icon, in the protocol timeline in the order it was added
- [ ] Step is expandable/collapsable.
- [ ] Temperature status references and displays the labware that is on the module. It will display the specified temp in C. If no temp specified, it displays "Deactivated"
- [ ] Labware Latch displays Open, Closed, Closed and Locked as specified by user. Closed and Locked will always appear while the shaker is shaking
- [ ] Shaker status displays RPM as specified by user. If no RPM specified, display "Deactivated"
- [ ] "Deactivate after" status displays the time specified by user when a Set Timer is set. This line is removed if no timer is set 
- [ ] Step is clickable in the protocol timeline, and when clicked opens the h/s step form
- [ ] Step works with batch edit functionality, meaning it is shift+clickable, and can be acted on with the batch edit toolbar
- [ ] Step is highlighted per current styling if selected

**Comment by howisthisnamenottakenyet** [comment]
Updated the figma link to final files version
