### ISSUE TITLE
Updated Opentrons App Will not Calibrate Before Protocol

### ISSUE THREAD

**Issue by kf7jxb** [Opentrons/opentrons#9570]
When we are trying to calibrate the robot before we run our protocol, the Opentrons App crashes and all we see is a white screen. This has not happened before, but we just updated the Opentrons app yesterday, and have ran into this issue multiple times since.

**Comment by mcous** [comment]
There was an issue running calibration on protocols that load, but do not use, pipettes. It was resolved in the 5.0.1 release yesterday. Can you confirm you are running version 5.0.1?

**Comment by kf7jxb** [comment]
We just updated to the new version and the problem is fixed. Thanks!
