### ISSUE TITLE
Support APIv2 magnet engage units in APIv3?

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#9580]
For expedience and simplicity, PR #9539 implemented PAPIv3's `MagneticModule.engage()` in a way that breaks compatibility with PAPIv2. It assumes all input parameters are in units of true mm, whereas PAPIv2 uses half-mm for GEN1 Magnetic Modules.

We need to:

* Decide if this compatibility break is good and okay.
    * If yes, consider also renaming `height` to `height_from_home` and making everything kwarg-only. If we're breaking compatibility anyway, we may as well reduce these sources of confusion while we're at it.
* If no, fix it.
* If yes, document it in the changelog and in the method docstring.

**Comment by mcous** [comment]
Moved to RSS-109, with the plan to issue a PAPIv2 bump that switches GEN1 magnetic modules to use real millimeters
