### ISSUE TITLE
Basic Protocol Execution Support in OT-3

### ISSUE THREAD

**Issue by mattwelch** [Opentrons/opentrons#9581]
_As a scientist I would like to execute python on JSON Protocols with current OT-2-level capabilities on the OT-3._

This epic will track work to "port" protocol execution infrastructure to the OT-3.

## Acceptance Criteria
- Any protocol that can be run on OT-2 can be run on OT-3, with any modifications required for hardware differences (deck changes, trash location, etc)
- HTTP endpoints required for 1st and 3rd party app integration are available.

**Comment by SyntaxColoring** [comment]
We sure did do this.
