### ISSUE TITLE
bug: 5.0.1: analysis never completes on protocol with unsupported api version

### ISSUE THREAD

**Issue by sanni-t** [Opentrons/opentrons#9598]
# Overview

On 5.0.1, if you `POST` a protocol with an unsupported api version, for example, with a metadata like `metadata={"apiLevel": "2.13"}`, then the `POST` request succeeds but the analysis stays `pending` forever. 

# Current behavior

`POST` a python protocol with above unsupported `apiLevel` to the `/protocols` endpoint. Keep polling for `GET` `/protocols` and you'll see the analysis never completes. 
However if you try to create a new run, the `POST request fails with the error:
```
RuntimeError: API version 2.13 is not supported by this robot software. Please either reduce your requested API version or update your robot."
```

# Expected behavior

The analysis itself should result in error.

**Comment by mcous** [comment]
I accidentally filed a duplicate #10733. Closing this ticket in favor of the newer one only because the fix is in flight as #10780 referencing the newer ticket
