### ISSUE TITLE
PD Liquid Tracking: Final State

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#963]
As a protocol designer, I'd like to see the expected final state of my robot, after my protocol has completed.

## Acceptance Criteria

Pt 1:
- 'End' step appears by default in step editor
- Hovering over 'finished' step shows anticipated final state of robot after protocol has completed

Pt 2:
- 'End' step appears **below** the "ADD STEP" button
- "ADD STEP" button acts as popover when expanded, its contents appear on a layer above the 'End' sted

## Design (@howisthisnamenottakenyet)
![image](https://user-images.githubusercontent.com/35570080/36981615-a29816e4-205b-11e8-8cdc-18178aa7f849.png)

**Comment by howisthisnamenottakenyet** [comment]
@umbhau Can this story be updated to say you can also click on the finished step? That would allow you to hover over wells across the deck to see what's in them.
