### ISSUE TITLE
heater-shaker: create support documentation for heater-shaker

### ISSUE THREAD

**Issue by sanni-t** [Opentrons/opentrons#9639]
# Overview

Create a 'How-To' guide for using the heater-shaker with the OT2.

# Implementation details

- Write a dedicated guide for heater shaker like [this one](https://support.opentrons.com/en/articles/3469797-thermocycler-module) (@marisafenn & @Matt-Zwimpfer will be working on this)
- Also outline h/s usage in python protocol [in this docs page](https://docs.opentrons.com/v2/new_modules.html) (@ecormany working on this)

**Comment by ecormany** [comment]
Completed (long ago) by #10686
