### ISSUE TITLE
Give users a way to see release notes for the current app version

### ISSUE THREAD

**Issue by emilywools** [Opentrons/opentrons#9665]
# Overview
give users a way to see the release notes for the current app version. In the App Settings > App Software version section, display a link to see release notes on Github:
https://github.com/Opentrons/opentrons/blob/edge/app-shell/build/release-notes.md

# Design
https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=1297%3A88764

# Acceptance Criteria

- [ ] App software version should link out to Github release notes doc

**Comment by mikecardarelli** [comment]
Nice-to-have for 5.1

**Comment by koji** [comment]
This has been solved by #10097
