### ISSUE TITLE
bug: The order of multiple of a modules setup is reversed in the UI

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#9669]
# Overview
The deck map UI needs to tell the user to plug in modules according to the load order in the protocol, not by the slot number. 
In other words, the first module loaded in the protocol should be connected to usb slot 1. The second module loaded in the protocol should be connected to usb slot 2. 

![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565643662643635353436353963383630346431313834302f61326364373831372d663666632d346538382d616466332d373562616265626134623431.png](https://images.zenhubusercontent.com/5e20a4f595a33208d0d768ab/4383b797-f7c5-42a1-be57-9f3ac16ba8ce)

# Implementation details
This front-end ticket relates to the following CPX ticket: https://app.zenhub.com/workspaces/app--ui-5f6248dba845b000139aa767/issues/opentrons/opentrons/9620

**Comment by emilywools** [comment]
update the copy in the first paragraph to:

> To use more than one of the same module in a protocol, you first need to plug in the module that’s called first in your protocol  to the lowest numbered USB port on the OT-2. Continue in the same manner with additional modules.

update [this image](https://github.com/Opentrons/opentrons/blob/edge/app/src/assets/images/MoaM_modal_Image.svg) to the attached one here.![20220310_updated_moam_image.svg](https://images.zenhubusercontent.com/5f57e13054c0d9cd55c2adb3/c087007f-2e99-449d-95ef-2572c12fae98)
