### ISSUE TITLE
bug: Hitting cancel run during the end of LPC while robot is homing leaves app in spinning infinity 

### ISSUE THREAD

**Issue by nusrat813** [Opentrons/opentrons#9670]
<img width="1440" alt="Screen Shot 2022-03-09 at 3 52 21 PM" src="https://user-images.githubusercontent.com/30632549/157534547-4a93b6b0-c15f-4997-9bc0-a8e0332dc41c.png">

# Steps to reproduce

1. Go through LPC flow
2. Apply offsets 
3. The robot should be homing 
4. Hit `cancel run`

**Comment by anthonywilleee** [comment]
investigate to make sure this doesnt happen with new UI

**Comment by mikecardarelli** [comment]
@hartm9 to check if this is still happening

**Comment by hartm9** [comment]
Still seeing this behavior.  The Cancel Run button is blocked by the "Robot is in motion" pop up while the tip is being returned after LPC, but when the homing process starts, the "Robot is in motion" pop up disappears.  If I click through the "apply labware offsets" pop up and try to hit cancel, I get the following screen that doesn't resolve:
![image](https://user-images.githubusercontent.com/95253324/171919152-c7cc2622-0e8b-46ad-bebe-add575332ac4.png)

I've been waiting for a couple of minutes so far, and no change.  I'm able to click around to different tabs, etc., but the run status still doesn't change.

**Comment by b-cooper** [comment]
Closing as this is now fixed on edge. This dead-end does not appear to be reachable since #10170 was merged.
