### ISSUE TITLE
Delete a protocol from the App

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#9681]
# Overview
This is a new requirement that popped up during development. When a protocol file is added to the OT app, a copy is made in the app's protocol directory and the original file is left alone in the filesystem. If a user wants to remove a protocol from the protocols landing page, we should enable the user to delete the imported copy from the protocol card's 3-dot menu

# Implementation details
If a user has a protocol in User/Downloads/, they select it in the upload slide-out in the app, We make a copy of that protocol and put it in /secretAppFolder/, when they click "remove" in the app, we move the copy to the trash, but the original file is still present in User/Downloads/

# Design
Warning modal: https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=1297%3A90568

# Acceptance criteria

- [ ] The user should be able to delete the imported copy of a protocol, removing that protocol from their protocols landing page

- [ ] The original file should be untouched in the user's filesystem

- [ ] The user should be prompted with a confirmation modal after they select "delete protocol" in the 3-dot menu

# Selector for E2E

- [ ] Overflow menu
- [ ] Delete option
- [ ] cancel button
- [ ] yes delete protocol

**Comment by mikecardarelli** [comment]
@reachojhaneha Would this ticket need a selector for the delete protocol option in the 3-dot menu or the confirmation modal?

**Comment by reachojhaneha** [comment]
yes mike, thanks for bringing this. I will add the selectors
