### ISSUE TITLE
PD: Drop Tips at End of Protocol

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#969]
As a protocol designer, I would like all of my protocols to automatically include a 'drop tips' command at the end of my protocol, so that I don't accidentally finish a protocol with dirty tips still on the pipette.

## Acceptance Criteria
- Generated protocol file includes a 'drop tips' command at the end for each pipette if that pipette has tips.

## Implementation Notes
- Is there a possible conflict with user-generated drop-tips command
- Assuming the user doesn't need to delete this step, is there any reason to show it in the step list (can we just do this invisibly)

## Design
None needed

**Comment by IanLondon** [comment]
This seems like it's not working anymore
