### ISSUE TITLE
App:  Labware Offsets are all applied with the same pipette if two pipettes are loaded, but only one is used. Including unused tip racks 

### ISSUE THREAD

**Issue by alexjoel42** [Opentrons/opentrons#9691]
# Overview

The Ot-2 should not use an incorrect tip rack to pick up a tip from and then apply labware offsets to the rest of the labware. 
<img width="874" alt="Screen Shot 2022-03-14 at 12 19 13 PM" src="https://user-images.githubusercontent.com/65437763/158215464-51e9c62c-6fdd-4510-b9df-6dc62ea22ab9.png">

# Steps to reproduce

1. Load protocol
2. Have both pipettes defined and two labwares defined in the protocol. 
3. Don't use one of the two pipettes in the protocol 
4. Try to do Labware Offset Calibration 

```Python3
from opentrons import protocol_api

 

# metadata

metadata = {

    'protocolName': 'My Protocol',

    'apiLevel': '2.11'
}

 

# protocol run function. the part after the colon lets your editor know

# where to look for autocomplete suggestions

def run(protocol: protocol_api.ProtocolContext):

    # labware

      quantPlate = protocol.load_labware('biorad_96_wellplate_200ul_pcr', 4)

      storePlate = protocol.load_labware('biorad_96_wellplate_200ul_pcr', 1)

      reagentRack = protocol.load_labware('opentrons_10_tuberack_falcon_4x50ml_6x15ml_conical', 9)

      tiprackA = protocol.load_labware('opentrons_96_tiprack_300ul', '2')

      tiprackB = protocol.load_labware('opentrons_96_tiprack_1000ul', '8')

 

    # pipettes

      left_pipette = protocol.load_instrument('p300_multi_gen2', 'left', tip_racks=[tiprackA])

      right_pipette = protocol.load_instrument('p1000_single_gen2', 'right', tip_racks=[tiprackB])

     

 

    # commands

      right_pipette.distribute(500, reagentRack.wells_by_name()['A3'], quantPlate.wells()[:])

```

# Current behavior

1. P1000 verifies correct position on slot 11
2. P1000 then attempts to pick up 300uL tip to use to calibrate remaining labwarE
3. This crashes the pipette against the labware
4. The rest of the labware can't have Labware Offsets applied because the P1000 tried to pick up the incorrect tip

# Expected behavior
1. P1000 verifies the correct position on slot 10 if the tip rack is compatible. If not, it doesn't move to it. 
2. P1000 picks up a tip on slot 11
3. P1000 uses that tip to calibrate the remaining labware.
4. The rest of the labware have Labware Offsets applied

**Comment by alexjoel42** [comment]
Work around: 

Both pipettes need to be used in the protocol, or any unused pipette should be commented out. Otherwise, one pipette is used to calibrate all tip racks. This can lead to a p1000 trying to pick up 300uL tips (like in this case).

**Comment by alexjoel42** [comment]
I just wanted to add some use cases, because I think that the fundamental assumption is "customers won't define unused labware on the deck.

Here are a few use cases (based on customer experiences) that I have seen:

1. Folks can have one "basic protocol"  that they modify for different locations. 
2. 

3.

**Comment by Matt-Zwimpfer** [comment]
@nusrat813 to review
