### ISSUE TITLE
Epic: Labware Position Check Enhancements

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#9722]
# Overview
Post-5.0 enhancements to the labware position check workflow. 

# Design
Small screens of the updated flow live here: https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=6434%3A247057

**Comment by SyntaxColoring** [comment]
Closing this old ZenHub epic as stale. We've moved these things to Jira.
