### ISSUE TITLE
Add Settings: Override Python path 

### ISSUE THREAD

**Issue by mikecardarelli** [Opentrons/opentrons#9788]
# Overview
In-app protocol analysis uses a version of Python bundled with the OT App by default. If the user prefers to use their local Python instead this app setting lets them override the app's default.

# Design
The new app setting can be found here: 
https://www.figma.com/file/bVtCogdwiXj3ndpk4AWXCx/Milestone-1%3A-Read-and-Execute?node-id=1297%3A88764

# Acceptance Criteria
- [ ] If an override path is **not** set, the CTA button should read "Add override path"
- [ ] If an override path is set, the folder name and a link to the filesystem should be shown in the Override Path field
- [ ] If an override path is set, clicking "Reset to default" should clear the override

**Comment by bndo** [comment]
Closed via #10188
