### ISSUE TITLE
Move Protocol Engine command request shapes into shared-data

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#9803]
# Overview

Protocol Engine command shapes are shared between:

* The OT-2's HTTP API
* The JSON protocol v6 schema

But they're currently are defined in `api`. They should be moved to `shared-data`.

# Why

The Python bindings that are currently in `shared-data` model the `params` in a JSON v6 protocol [a bit too loosely](https://github.com/Opentrons/opentrons/blob/db0a5268a490b77cd6a00700df55a1de8460b786/shared-data/python/opentrons_shared_data/protocol/models/protocol_schema_v6.py#L30-L56). This makes it [difficult](https://github.com/Opentrons/opentrons/pull/9772) for `robot-server` to read them and send them to a Protocol Engine. We lose a lot of type safety, opening the door to silly bugs where, for example, we could accidentally drop a field, causing a runtime error at best or a wrongly-executed command at worst.

# Acceptance criteria

* The `params` models, at least, are moved to shared-data, so we can do away with the current `Params` amalgamation.
* Perhaps full command request shapes (including `commandType`, for example) are also moved there.

# Implementation notes

In a JSON v6 protocol, the `commands` list is not *quite* a `List[Union[CommandCreate]]`. Certain commands, like `loadPipette`, refer to data outside the `commands` list. Our Python bindings should accurately reflect this distinction; we should have separate models for those quasi-commands as they appear in the JSON protocol v6 spec.

**Comment by mcous** [comment]
Not required for 6.1.0

**Comment by SyntaxColoring** [comment]
Moved to RSS-53.
