### ISSUE TITLE
Wire up Don't ask me again checkbox in H/S confirm attachment modal

### ISSUE THREAD

**Issue by jerader** [Opentrons/opentrons#9814]
# Overview

Right now, the modal has a checkbox to allow the user to never show the modal again. That checkbox needs to be wired up.

The modal is used both when 1) confirming set shake via the Set shake slideout and 2) clicking `proceed to run` when a heater shaker module is attached

# Implementation Details
- Probably need to use `Alerts` (`app/src/organisms/Alerts/index.tsx`) 

# Acceptance Criteria
- checkbox functionality should work

**Comment by b-cooper** [comment]
look to the "don't show me again check box" from the calibration block modal for implementation example
