### ISSUE TITLE
bug: Labware Creator: Default Format Key Incorrect for 96 and 384 Well Plate Definitions

### ISSUE THREAD

**Issue by skyewindsor** [Opentrons/opentrons#9842]
# Overview

The Labware Creator automatically lists the format key of 96-well plate and 384-well plate definitions to be "irregular". This [prevents multichannel pipettes](https://github.com/Opentrons/opentrons/issues/5085) from interacting correctly with custom labware definitions generated from LC. 

More info on correct format keys to use for labware definitions here: https://github.com/Opentrons/opentrons/pull/1752

# Steps to reproduce

I created a 96 well plate and 384 well plate definition using the Labware Creator. The format key input was listed as "irregular". JSON definition files [are here](https://drive.google.com/drive/u/1/folders/1HPQCrEl0wdBR8AWEmI_GS0n_A2YqudLM). 

# Expected behavior

The Labware Creator should input the format key "96-standard" or "384-standard" into the definitions for those types of labware.

**Comment by mikecardarelli** [comment]
New JIRA ticket lives here: https://opentrons.atlassian.net/browse/RAUT-199
