### ISSUE TITLE
refactor(robot-server): Compute basic protocol info on-the-fly, don't store it persistently

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#9858]
# Overview

This ticket is to fix a hack that I did in #9826 for the sake of getting stuff merged incrementally.

# Details

Currently, the `ProtocolSource` component of a `ProtocolResource` is shoved into the database as a serialized binary object. This is very fragile: `ProtocolSource` is internal, complex, deeply structured, and unstable interface-wise.

Fortunately, the contents of a `ProtocolSource` object are, theoretically, readily computable from raw protocol files on the filesystem. So, I think we should:

1. Modify `opentrons.protocol_reader` to separate its two current jobs: (1) copying and storing uploads, and (2) computing `ProtocolSource` info from those uploads.
    * For the sake of discussion, let's say we split it into two units: `ProtocolSaver` puts FastAPI `UploadFiles` on the filesystem; and `ProtocolBasicAnalyzer` takes stuff from the filesystem and computes `ProtocolSource` objects from it.
    * We've discussed stuff like this before, a little bit. [Here's a `# todo` about it.](https://github.com/Opentrons/opentrons/blob/0375ca35881a869376b6ebacdbcdd776f1fcc5b7/api/src/opentrons/protocol_reader/protocol_reader.py#L72-L73)
2. Take these big complex `ProtocolSource` objects out of the database.
3. When we need the `ProtocolSource` of a stored protocol, use `ProtocolBasicAnalyzer` to compute it. Only keep it in memory; don't store it anywhere.
    * We can either do this for all persisted protocols when `robot-server` boots, or do it the first time each protocol is accessed in a given boot.
    
Edit: Discussed on CPX. We agree with the above approach.

**Comment by mattwelch** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/opentrons-cpx-5e1f6ed55b295a3f514f2283/issues/Opentrons/opentrons/9858?planning-poker) with ZenHub @mcous @sanni-t @SyntaxColoring @TamarZanzouri @y3rsh @X-sam
