### ISSUE TITLE
Wifi Robots Not Appearing on Windows

### ISSUE THREAD

**Issue by umbhau** [Opentrons/opentrons#990]
## Expected Behavior:
- Robots available over wifi should appear in available robots list (robots sidebar)

## Observed Behavior: 
- Robots connected over wifi do not appear in available robots list.

## Steps To Recreate
reported by @Laura-Danielle:
1. Open run app on Windows (version >= 2018-03-06)
2. Note wifi robots are not visible in robots list (the sidebar)

**Comment by umbhau** [comment]
@mcous @Kadee80 

Just an FYI -- not sure if this is related to any ongoing connectivity work.

**Comment by mcous** [comment]
@umbhau ongoing connectivity work as not touched existing discovery logic. @Laura-Danielle what version of Windows and which exact build did you see this behavior on?

I'm unable to reproduce this on my Windows 10 (v10.0.16299) with latest `edge` (commit 148d316 at time of writing)

**Comment by umbhau** [comment]
@mcous Reproduced this again on @Carlos-fernandez laptop:
- Last stable build: https://s3.amazonaws.com/opentrons-app/builds/Opentrons-v3.0.0-beta.2-win-b3193.exe
- PP2 Robot: OPENTRONS-OT2P20180327A04
- Was able to successfully connect on my mac
