### ISSUE TITLE
HTTP API: separate protocol analysis endpoint

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#9965]
## Overview

I really thought this ticket already existed, but I couldn't find it. Please close if this turns out to be a duplicate.

As an HTTP API user, I would like the `GET /protocols` endpoint to respond quickly. Analysis results tend to be very large and cause the response to take a long time.

## Acceptance criteria

- `GET /protocols` and `GET /protocols/:id` does not provide full analysis responses, but does:
    - Provide enough information to tell whether a protocol has a completed analysis
- `GET /protocols/:id/analyses` returns full analyses

**Comment by sanni-t** [comment]
> `GET /protocols/:id/analyses` returns full analyses

Should this be `/protocols/:id/analysis`?

**Comment by mcous** [comment]
> > `GET /protocols/:id/analyses` returns full analyses
> 
> Should this be `/protocols/:id/analysis`?

"Analyses" as in the plural of "analysis". The protocol has a list field called `analyses`, which may contain 0 or more analysis objects
