### ISSUE TITLE
Delete old runs, protocols, and analyses

### ISSUE THREAD

**Issue by SyntaxColoring** [Opentrons/opentrons#9966]
# Overview

Currently, `robot-server` never deletes the things that it persists across reboots. They will accumulate indefinitely and eventually make the database very big. To prevent performance and storage capacity problems, `robot-server` should automatically trim these records.

# Acceptance criteria

* A heavily-used robot must not create persistent records infinitely. At some reasonable limit, creating new records should be disallowed, or old records should be automatically deleted, or both.
* Consistency of the database and the API must be preserved. For example, we shouldn't leave runs that refer to protocols that no longer exist.
* Auto-deletion behavior must be documented in the OpenAPI spec.
* Auto-deletes should be logged, for debuggability.

# Implementation proposal

## Analyses

The server will store a small, bounded number of analyses (maybe 5) for each protocol. When something creates an additional analysis, the server will automatically push out the oldest one on that protocol to make room, if needed.

## Runs

The server will store a bounded number of runs. (Approximately 20—see #9367.) 

When the client `POST`s a new run, if the server has reached its run limit, the server will make room by automatically deleting the oldest run.

This is automatic instead of explicit to relieve client-side burden. In particular, v5.0 clients expect to be able to `POST` runs over and over without limit.

## Protocols

The server will store a bounded number of protocols. (20 is reasonable, to match the limit on runs.)

When the client `POST`s a new protocol, if the server has reached its protocol limit, the server will make room by automatically deleting the oldest protocol *that is not linked to a run.*

If every existing protocol is linked to a run, the server can't safely delete any of them without violating the database's consistency. In this case, the server will repeatedly delete *the oldest run that is linked to a protocol* until any protocol is orphaned, and then delete that protocol.

As with runs, this is automatic instead of explicit in order to relieve client-side burden.

When we need to delete runs to free up some protocols to be deleted, we delete the oldest *runs*, not the runs with the oldest *protocols,* to avoid confusing scenarios where runs disappear from the middle of a robot's run history. With our current UIs, preserving a sensible run history is more important than preserving a sensible protocol history.

When the client *explicitly* `DELETE`s a protocol, the server will return some kind of conflict error (like a 409) if that protocol is linked to a run. We can reconsider this in the future, but for now, this seems like the simplest and most explicit thing.

Whenever a protocol is deleted, all of its analyses are also deleted automatically.

**Comment by mcous** [comment]
I think this is a good spec. If we encounter any roadblocks during implementation, I believe we have an simplification offramp available that might help:

> If every existing protocol is linked to a run, the server can't safely delete any of them without violating the database's consistency. In this case, the server will repeatedly delete the oldest run that is linked to a protocol until any protocol is orphaned, and then delete that protocol.

We could potentially drop this requirement for simplicity and still maintain consistency, by treating the 20 protocol limit as soft and allowing the POST to succeed.

Then, one of two things will happen:

1. User will `POST /runs` using the new protocol
    - New run will cause the oldest run to be evicted, probably orphaning a protocol
    - Subsequent `POST /protocols` will evict that newly orphaned protocol
2. User will `POST /protocols` with another new protocol, without ever creating a run
    - Since the previously created protocol that exceeded the limit was never used in a run, it is deleted
    - New protocol is created

The simplification here might be worth it:

- `POST /runs` _never_ has to modify the protocols table
- `POST /protocols` _never_ has to modify the runs table

**Comment by SyntaxColoring** [comment]
Interesting, yeah, that could work.

One possible downside is that, in a sense, it sort of degenerates to a maximum protocol limit of 1, I think.

1. We start with 20 protocols and 20 runs (mapped 1:1) uploaded.
2. Client A uploads protocol 21. This is over the soft limit, but doesn't evict anything because everything else is linked to a run.
3. Client B uploads protocol 22. This evicts protocol 21.
4. Client A tries to start a run with protocol 21, but it's already gone.

I *think* we could solve this in practice by making the protocol limit something like 40, keeping the run limit at 20? It's making my head hurt.
