### ISSUE TITLE
spike: Investigate required endpoints to support DSM first-party client experiences

### ISSUE THREAD

**Issue by mattwelch** [Opentrons/opentrons#9969]
Investigate what information is required by the Opentrons app to realize the deck state modification as defined by UX.

## Acceptance Criteria
- [ ] List of required endpoints and the facet of the app user experience they feed
- [ ] Technical description of the endpoints (url, request body, response)

**Comment by SyntaxColoring** [comment]
Tracked on Jira...somewhere.
