### ISSUE TITLE
 Change Pipettes: Get attached pipettes HTTP endpoint

### ISSUE THREAD

**Issue by mcous** [Opentrons/opentrons#998]
## overview

As a Run App user, I would like to see details about my robot's attached pipettes. For the Run App to display pipette details, the robot HTTP API needs a mechanism for retrieving that information

## Acceptance Criteria

- Server responds to a GET request with attached pipette information

## Implementation Notes

Pipette information is stored on the pipette itself and can be retrieved by the server (see #989)

### Specifications

Actual spec TBD based on review w/ FE and BE teams

- GET request
- Based on recent front-end discussions, a JSON object keyed by mount would be the preferred response body
- When an uncommissioned (i.e. nothing on the memory chip) pipette is attached, return 'uncommissioned' (not an error)

## Test Plan

- Attach a commissioned pipette to the left mount
    - [ ] GET request returns the correct pipette info on `left` and `'uncommissioned'` on `right`
- Attach a commissioned pipette to the right mount
    - [ ] GET request returns `'uncommissioned'` on `left` and the correct pipette info on `right`
- Attach commissioned pipettes on both mounts
    - [ ]  GET request returns correct pipette info on `left` and `right`
- Attach an uncommissioned pipette
    - [ ] GET request returns `'uncommissioned'` on relevant mount key

**Comment by btmorr** [comment]
I revised the Test Plan section as currently there is not a differentiation between having an uncommissioned pipette present and having no pipette present (Smoothie returns an empty string response in both cases, so the API can't tell which case happened)
